# Clean up

In this notebook we go over every data set and make sure the ClinVar records can be matched to protein sequences in our ortholog collections.  Along the way we detect and correct errors in the data.

## Extract transcript IDs from variants

Pull the transcript record IDs from the ClinVar records of each gene.

**Output:** `'vartranscripts'` dictionary with genes as keys and lists of transcripts as values.

In [1]:
run kondrashov

In [66]:
import os
os.getcwd()
os.chdir('C:\\Users\\adesi\\Documents\\GitHub\\kondrashov\\pathogenic')

In [67]:
vv= pd.read_csv("ABCD1.csv")
#vv.head()
trans = vv['Name'].str.split("(").str[0]
trans

0      NM_000033.4
1      NM_000033.4
2      NM_000033.4
3      NM_000033.4
4      NM_000033.4
          ...
322    NM_000033.4
323    NM_000033.4
324    NM_000033.4
325    NM_000033.4
326    NM_000033.4
Name: Name, Length: 327, dtype: object

In [68]:
import pandas as pd

var_transcripts = {}

for gene in loci:
    vv = pd.read_csv(f"{gene}.csv")
    trans = vv['Name'].str.split("(").str[0]
    transls = trans.tolist()
    unique_trans = trans.unique().tolist()
    
    var_transcripts[gene] = {
        "genetranscript": unique_trans,
        "number of unique transcripts": len(unique_trans),
        "number of transcripts": len(transls)
    }

    print(gene, '\t', len(unique_trans), 'unique transcripts', '\t' 'of', len(transls), 'transcripts')

ABCD1 	 1 unique transcripts 	of 327 transcripts
ALPL 	 1 unique transcripts 	of 404 transcripts
AR 	 1 unique transcripts 	of 269 transcripts
ATP7B 	 1 unique transcripts 	of 424 transcripts
BTK 	 1 unique transcripts 	of 245 transcripts
CASR 	 1 unique transcripts 	of 209 transcripts
CBS 	 1 unique transcripts 	of 198 transcripts
CFTR 	 3 unique transcripts 	of 773 transcripts
CYBB 	 1 unique transcripts 	of 141 transcripts
F7 	 5 unique transcripts 	of 80 transcripts
F8 	 2 unique transcripts 	of 515 transcripts
F9 	 4 unique transcripts 	of 274 transcripts
G6PD 	 4 unique transcripts 	of 207 transcripts
GALT 	 1 unique transcripts 	of 247 transcripts
GBA1 	 1 unique transcripts 	of 293 transcripts
GJB1 	 2 unique transcripts 	of 201 transcripts
HBB 	 11 unique transcripts 	of 183 transcripts
HPRT1 	 3 unique transcripts 	of 71 transcripts
IL2RG 	 1 unique transcripts 	of 113 transcripts
KCNH2 	 1 unique transcripts 	of 320 transcripts
KCNQ1 	 1 unique transcripts 	of 365 transcripts
L1CAM 	 1 unique transcripts 	of 146 transcripts
LDLR 	 2 unique transcripts 	of 1096 transcripts
MPZ 	 1 unique transcripts 	of 143 transcripts
MYH7 	 1 unique transcripts 	of 412 transcripts
TYR 	 1 unique transcripts 	of 237 transcripts
PAH 	 1 unique transcripts 	of 692 transcripts
PMM2 	 2 unique transcripts 	of 174 transcripts
RHO 	 1 unique transcripts 	of 173 transcripts
TP53 	 1 unique transcripts 	of 417 transcripts
TTR 	 1 unique transcripts 	of 130 transcripts
VWF 	 1 unique transcripts 	of 310 transcripts

You can use this `dict` to look up the transcripts associated with a given gene in the ClinVar data.

In [73]:
var_transcripts

{'ABCD1': {'genetranscript': ['NM_000033.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 327},
 'ALPL': {'genetranscript': ['NM_000478.6'],
  'number of unique transcripts': 1,
  'number of transcripts': 404},
 'AR': {'genetranscript': ['NM_000044.6'],
  'number of unique transcripts': 1,
  'number of transcripts': 269},
 'ATP7B': {'genetranscript': ['NM_000053.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 424},
 'BTK': {'genetranscript': ['NM_000061.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 245},
 'CASR': {'genetranscript': ['NM_000388.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 209},
 'CBS': {'genetranscript': ['NM_000071.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 198},
 'CFTR': {'genetranscript': ['NM_000492.4',
   'NM_000492.3',
   'NC_000007.14:g.117675861C>T'],
  'number of unique transcripts': 3,
  'number of transcripts': 773},
 'CYBB': {'genetranscript': ['NM_000397.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 141},
 'F7': {'genetranscript': ['NM_019616.4',
   'NC_000013.11:g.113105748C>G',
   'NM_000131.4',
   'NM_000131.5',
   'NC_000013.11:g.113105784G>A'],
  'number of unique transcripts': 5,
  'number of transcripts': 80},
 'F8': {'genetranscript': ['NM_000132.4', 'NC_000023.11:g.155022771G>A'],
  'number of unique transcripts': 2,
  'number of transcripts': 515},
 'F9': {'genetranscript': ['NC_000023.11:g.139530716T>A',
   'NM_000133.4',
   'NC_000023.11:g.139530731A>T',
   'NC_000023.11:g.139530710G>C'],
  'number of unique transcripts': 4,
  'number of transcripts': 274},
 'G6PD': {'genetranscript': ['NM_000402.4',
   'NM_001360016.2',
   'G6PD ZURICH',
   'NM_001042351.3'],
  'number of unique transcripts': 4,
  'number of transcripts': 207},
 'GALT': {'genetranscript': ['NM_000155.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 247},
 'GBA1': {'genetranscript': ['NM_000157.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 293},
 'GJB1': {'genetranscript': ['NM_000166.6', 'NM_001097642.3'],
  'number of unique transcripts': 2,
  'number of transcripts': 201},
 'HBB': {'genetranscript': ['NM_000518.5',
   'NM_000518.4',
   'Hb Little Rock',
   'NC_000011.10:g.5227159G>A',
   'NC_000011.10:g.5227172G>A',
   'NC_000011.10:g.5227100T>C',
   'NC_000011.10:g.5227096C>A',
   'NC_000011.10:g.5227097T>G',
   'NC_000011.10:g.5227098T>A',
   'NC_000011.10:g.5227101A>C',
   'NC_000011.10:g.5227147G>T'],
  'number of unique transcripts': 11,
  'number of transcripts': 183},
 'HPRT1': {'genetranscript': ['NM_000194.2', 'NM_000194.3', 'HPRT CHERMSIDE'],
  'number of unique transcripts': 3,
  'number of transcripts': 71},
 'IL2RG': {'genetranscript': ['NM_000206.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 113},
 'KCNH2': {'genetranscript': ['NM_000238.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 320},
 'KCNQ1': {'genetranscript': ['NM_000218.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 365},
 'L1CAM': {'genetranscript': ['NM_001278116.2'],
  'number of unique transcripts': 1,
  'number of transcripts': 146},
 'LDLR': {'genetranscript': ['NM_000527.5', 'NM_000527.4'],
  'number of unique transcripts': 2,
  'number of transcripts': 1096},
 'MPZ': {'genetranscript': ['NM_000530.8'],
  'number of unique transcripts': 1,
  'number of transcripts': 143},
 'MYH7': {'genetranscript': ['NM_000257.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 412},
 'TYR': {'genetranscript': ['NM_000372.5'],
  'number of unique transcripts': 1,
  'number of transcripts': 237},
 'PAH': {'genetranscript': ['NM_000277.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 692},
 'PMM2': {'genetranscript': ['NM_000303.3', 'NC_000016.10:g.8797716G>T'],
  'number of unique transcripts': 2,
  'number of transcripts': 174},
 'RHO': {'genetranscript': ['NM_000539.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 173},
 'TP53': {'genetranscript': ['NM_000546.6'],
  'number of unique transcripts': 1,
  'number of transcripts': 417},
 'TTR': {'genetranscript': ['NM_000371.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 130},
 'VWF': {'genetranscript': ['NM_000552.5'],
  'number of unique transcripts': 1,
  'number of transcripts': 310}}

In [71]:
gene_transcripts.items()
gene_transcripts["AR"]

{'genetranscript': ['NM_000044.6'],
 'number of unique transcripts': 1,
 'number of transcripts': 269}

## Extract human protein sequence records from the fasta files

Take the fasta files containing ortholog sequences, search for human sequences and extract the corresponding record.

**Output:** `'protrecs'` dictionary with genes as keys and lists of protein records as values.

In [82]:
os.chdir('C:\\Users\\adesi\\Documents\\GitHub\\kondrashov')

In [83]:
gene = "ABCD1"
for record in SeqIO.parse('fasta/{0}.fasta'.format(gene), 'fasta'):
    #print(len(record))
    print(gene, record.id, len(record))

ABCD1 NP_000024.2 745
ABCD1 NP_001427676.1 845
ABCD1 XP_047297873.1 575
ABCD1 NP_002981.2 93
ABCD1 XP_047290405.1 106
ABCD1 XP_054169574.1 106
ABCD1 XP_054169575.1 93
ABCD1 XP_001085640.2 745
ABCD1 XP_028698141.1 734
ABCD1 XP_077844975.1 757
ABCD1 XP_016800023.1 745
ABCD1 XP_005594970.1 745
ABCD1 XP_065394918.1 757
ABCD1 XP_065394919.1 734
ABCD1 XP_065394920.1 592
ABCD1 XP_073885705.1 517
ABCD1 XP_035143923.1 734
ABCD1 XP_069320677.1 755
ABCD1 XP_069320678.1 746
ABCD1 XP_069320679.1 744
ABCD1 XP_055123101.1 745
ABCD1 XP_055123102.1 637
ABCD1 XP_055123103.1 417
ABCD1 XP_054326858.1 745
ABCD1 XP_063516340.1 748
ABCD1 XP_053434865.1 812
ABCD1 XP_053434866.1 755
ABCD1 XP_045394135.1 755
ABCD1 XP_045394136.1 744
ABCD1 XP_033057557.1 836
ABCD1 XP_032613804.1 745
ABCD1 XP_058297732.1 417
ABCD1 XP_032121107.1 744
ABCD1 XP_025227537.1 745
ABCD1 XP_025227538.1 736
ABCD1 XP_017736271.1 745
ABCD1 XP_017736272.1 734
ABCD1 XP_017372177.1 744
ABCD1 XP_012612660.1 746
ABCD1 XP_075855825.1 701
ABCD1 XP_012517442.1 746
ABCD1 XP_012517443.1 743
ABCD1 XP_012293282.1 741
ABCD1 XP_011943801.1 785
ABCD1 XP_011857640.1 745
ABCD1 XP_011857641.1 736
ABCD1 XP_011811252.1 745
ABCD1 XP_011811253.1 736
ABCD1 XP_008047830.1 745
ABCD1 XP_037844725.1 843
ABCD1 XP_072869438.1 846
ABCD1 XP_072869439.1 734
ABCD1 XP_004065132.2 745
ABCD1 XP_003943925.1 745
ABCD1 XP_003918511.1 745
ABCD1 XP_003804888.1 745
ABCD1 XP_003802584.1 746
ABCD1 XP_012668657.1 770
ABCD1 XP_012668658.1 755
ABCD1 XP_030662307.1 745
ABCD1 XP_024096876.1 745
ABCD1 XP_063577189.1 417

In [84]:
i = 1
protrecs = {}
for gene in loci:
    protrecs.update({gene: []})
    for record in SeqIO.parse('fasta/{0}.fasta'.format(gene), 'fasta'):
        sp = get_species(record)
        if sp=='Homo sapiens':
            protrecs[gene].append(record)
            print(gene, '\t', record.id, '\t', 'sequence length:', len(record))

ABCD1 	 NP_000024.2 	 sequence length: 745
ABCD1 	 NP_001427676.1 	 sequence length: 845
ABCD1 	 XP_047297873.1 	 sequence length: 575
ABCD1 	 NP_002981.2 	 sequence length: 93
ABCD1 	 XP_047290405.1 	 sequence length: 106
ABCD1 	 XP_054169574.1 	 sequence length: 106
ABCD1 	 XP_054169575.1 	 sequence length: 93
ALPL 	 NP_000469.3 	 sequence length: 524
ALPL 	 NP_001120973.2 	 sequence length: 469
ALPL 	 NP_001170991.1 	 sequence length: 447
ALPL 	 XP_016856392.1 	 sequence length: 472
ALPL 	 XP_054191723.1 	 sequence length: 472
AR 	 NP_000035.2 	 sequence length: 920
AR 	 NP_001011645.1 	 sequence length: 388
AR 	 NP_001334990.1 	 sequence length: 644
AR 	 NP_001334992.1 	 sequence length: 648
AR 	 NP_001334993.1 	 sequence length: 572
AR 	 NP_001648.1 	 sequence length: 252
AR 	 NP_001333071.1 	 sequence length: 172
AR 	 NP_001619.1 	 sequence length: 316
ATP7B 	 NP_000044.2 	 sequence length: 1465
ATP7B 	 NP_001005918.1 	 sequence length: 1258
ATP7B 	 NP_001230111.1 	 sequence length: 1354
ATP7B 	 NP_001317507.1 	 sequence length: 1387
ATP7B 	 NP_001317508.1 	 sequence length: 1381
ATP7B 	 NP_001393442.1 	 sequence length: 1463
ATP7B 	 NP_001393443.1 	 sequence length: 1454
ATP7B 	 NP_001393444.1 	 sequence length: 1447
ATP7B 	 NP_001393446.1 	 sequence length: 1433
ATP7B 	 NP_001393448.1 	 sequence length: 1420
ATP7B 	 NP_001393449.1 	 sequence length: 1417
ATP7B 	 NP_001393452.1 	 sequence length: 1404
ATP7B 	 NP_001393453.1 	 sequence length: 1406
ATP7B 	 NP_001393454.1 	 sequence length: 1400
ATP7B 	 NP_001393455.1 	 sequence length: 1397
ATP7B 	 NP_001393459.1 	 sequence length: 1385
ATP7B 	 NP_001393463.1 	 sequence length: 1369
ATP7B 	 NP_001393464.1 	 sequence length: 1355
ATP7B 	 NP_001393465.1 	 sequence length: 1355
ATP7B 	 NP_001393466.1 	 sequence length: 1352
ATP7B 	 NP_001393467.1 	 sequence length: 1339
ATP7B 	 NP_001393468.1 	 sequence length: 1322
ATP7B 	 NP_001393469.1 	 sequence length: 1316
ATP7B 	 NP_001393470.1 	 sequence length: 1303
ATP7B 	 NP_001393472.1 	 sequence length: 1301
ATP7B 	 NP_001393473.1 	 sequence length: 1271
ATP7B 	 NP_001393474.1 	 sequence length: 1249
ATP7B 	 NP_001393475.1 	 sequence length: 1238
ATP7B 	 NP_001393476.1 	 sequence length: 1184
ATP7B 	 NP_001393477.1 	 sequence length: 1035
BTK 	 NP_000052.1 	 sequence length: 659
BTK 	 NP_001274273.1 	 sequence length: 693
BTK 	 NP_001274274.1 	 sequence length: 483
CASR 	 NP_000379.3 	 sequence length: 1078
CASR 	 NP_001171536.2 	 sequence length: 1088
CASR 	 XP_047305021.1 	 sequence length: 917
CASR 	 XP_054204069.1 	 sequence length: 1078
CASR 	 XP_054204072.1 	 sequence length: 917
CBS 	 NP_000062.1 	 sequence length: 551
CBS 	 NP_001308001.1 	 sequence length: 446
CBS 	 XP_011528076.1 	 sequence length: 582
CBS 	 XP_011528079.1 	 sequence length: 565
CBS 	 XP_011528085.1 	 sequence length: 460
CBS 	 XP_047296974.1 	 sequence length: 568
CBS 	 XP_047296988.1 	 sequence length: 496
CBS 	 XP_054180885.1 	 sequence length: 582
CBS 	 XP_054180887.1 	 sequence length: 568
CBS 	 XP_054180903.1 	 sequence length: 461
CFTR 	 NP_000483.3 	 sequence length: 1480
CYBB 	 NP_000388.2 	 sequence length: 570
CYBB 	 XP_047297811.1 	 sequence length: 468
F7 	 NP_000122.1 	 sequence length: 466
F7 	 NP_001254483.1 	 sequence length: 382
F7 	 NP_062562.1 	 sequence length: 444
F7 	 XP_006720026.2 	 sequence length: 412
F7 	 XP_011535776.2 	 sequence length: 495
F7 	 XP_011535777.2 	 sequence length: 433
F7 	 XP_011535778.1 	 sequence length: 364
F7 	 XP_047286081.1 	 sequence length: 452
F8 	 NP_000123.1 	 sequence length: 2351
F8 	 NP_063916.1 	 sequence length: 216
F9 	 NP_000124.1 	 sequence length: 461
F9 	 NP_001300842.1 	 sequence length: 423
F9 	 XP_005262454.1 	 sequence length: 418
F9 	 XP_054182657.1 	 sequence length: 418
G6PD 	 NP_000393.4 	 sequence length: 545
G6PD 	 NP_001035810.1 	 sequence length: 515
GALT 	 NP_000146.2 	 sequence length: 379
GALT 	 NP_001245261.1 	 sequence length: 270
GALT 	 NP_919299.3 	 sequence length: 498
GALT 	 XP_006719831.1 	 sequence length: 479
GALT 	 XP_011533238.1 	 sequence length: 458
GALT 	 XP_011533240.1 	 sequence length: 449
GALT 	 XP_047286067.1 	 sequence length: 298
GBA1 	 NP_000148.2 	 sequence length: 536
GBA1 	 NP_001165282.1 	 sequence length: 449
GBA1 	 NP_001165283.1 	 sequence length: 487
GJB1 	 NP_000157.1 	 sequence length: 283
HBB 	 NP_000509.1 	 sequence length: 147
HPRT1 	 NP_000185.1 	 sequence length: 218
IL2RG 	 NP_000197.1 	 sequence length: 369
IL2RG 	 NP_001425799.1 	 sequence length: 260
KCNH2 	 NP_000229.1 	 sequence length: 1159
KCNH2 	 NP_001191727.1 	 sequence length: 548
KCNH2 	 NP_001393682.1 	 sequence length: 1063
KCNH2 	 NP_001393684.1 	 sequence length: 829
KCNH2 	 NP_001393685.1 	 sequence length: 792
KCNH2 	 NP_001393686.1 	 sequence length: 788
KCNH2 	 NP_742053.1 	 sequence length: 888
KCNH2 	 NP_742054.1 	 sequence length: 819
KCNH2 	 XP_011514487.1 	 sequence length: 1059
KCNH2 	 XP_016867684.1 	 sequence length: 1109
KCNH2 	 XP_016867685.1 	 sequence length: 1100
KCNH2 	 XP_047276304.1 	 sequence length: 1185
KCNH2 	 XP_047276305.1 	 sequence length: 936
KCNQ1 	 NP_000209.2 	 sequence length: 676
KCNQ1 	 NP_001393765.1 	 sequence length: 644
KCNQ1 	 NP_001393766.1 	 sequence length: 586
KCNQ1 	 NP_001393767.1 	 sequence length: 496
KCNQ1 	 NP_001393768.1 	 sequence length: 180
KCNQ1 	 NP_861463.1 	 sequence length: 549
L1CAM 	 NP_000416.1 	 sequence length: 1257
L1CAM 	 NP_001137435.1 	 sequence length: 1248
L1CAM 	 NP_076493.1 	 sequence length: 1253
LDLR 	 NP_000518.1 	 sequence length: 860
LDLR 	 NP_001182727.1 	 sequence length: 858
LDLR 	 NP_001182728.1 	 sequence length: 819
LDLR 	 NP_001182729.1 	 sequence length: 692
LDLR 	 NP_001182732.1 	 sequence length: 682
LDLR 	 NP_001393790.1 	 sequence length: 202
LDLR 	 XP_011526312.1 	 sequence length: 834
LDLR 	 XP_047294787.1 	 sequence length: 596
MPZ 	 NP_000521.2 	 sequence length: 248
MPZ 	 NP_001302420.1 	 sequence length: 312
MPZ 	 XP_016856810.1 	 sequence length: 240
MYH7 	 NP_000248.2 	 sequence length: 1935
TYR 	 NP_000363.1 	 sequence length: 529
TYR 	 XP_011541272.1 	 sequence length: 471
TYR 	 XP_054225790.1 	 sequence length: 471
PAH 	 NP_000268.1 	 sequence length: 452
PAH 	 XP_016874859.1 	 sequence length: 240
PMM2 	 NP_000294.1 	 sequence length: 246
PMM2 	 XP_047290171.1 	 sequence length: 163
RHO 	 NP_000530.1 	 sequence length: 348
RHO 	 NP_001287815.1 	 sequence length: 144
RHO 	 NP_055393.1 	 sequence length: 210
TP53 	 NP_000537.3 	 sequence length: 393
TP53 	 NP_001119585.1 	 sequence length: 346
TP53 	 NP_001119586.1 	 sequence length: 341
TP53 	 NP_001119587.1 	 sequence length: 261
TP53 	 NP_001119588.1 	 sequence length: 209
TP53 	 NP_001119589.1 	 sequence length: 214
TP53 	 NP_001119590.1 	 sequence length: 354
TP53 	 NP_001263624.1 	 sequence length: 307
TP53 	 NP_001263625.1 	 sequence length: 302
TP53 	 NP_001263626.1 	 sequence length: 234
TP53 	 NP_001263627.1 	 sequence length: 182
TP53 	 NP_001263628.1 	 sequence length: 187
TTR 	 NP_000362.1 	 sequence length: 147
VWF 	 NP_000543.3 	 sequence length: 2813
VWF 	 XP_054229108.1 	 sequence length: 2813

You can use this `dict` to look up the unique human proteins in the ortholog collections associated with each gene.

In [55]:
protrecs['AR']

[SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...HTQ'), id='NP_000035.2', name='NP_000035.2', description='NP_000035.2 androgen receptor isoform 1 [Homo sapiens]', dbxrefs=[]),
 SeqRecord(seq=Seq('MILWLHSLETARDHVLPIDYYFPPQKTCLICGDEASGCHYGALTCGSCKVFFKR...HTQ'), id='NP_001011645.1', name='NP_001011645.1', description='NP_001011645.1 androgen receptor isoform 2 [Homo sapiens]', dbxrefs=[]),
 SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...TRP'), id='NP_001334990.1', name='NP_001334990.1', description='NP_001334990.1 androgen receptor isoform 3 [Homo sapiens]', dbxrefs=[]),
 SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...WLP'), id='NP_001334992.1', name='NP_001334992.1', description='NP_001334992.1 androgen receptor isoform 4 [Homo sapiens]', dbxrefs=[]),
 SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...QQK'), id='NP_001334993.1', name='NP_001334993.1', description='NP_001334993.1 androgen receptor isoform 5 [Homo sapiens]', dbxrefs=[]),
 SeqRecord(seq=Seq('MRAPLLPPAPVVLSLLILGSGHYAAGLDLNDTYSGKREPFSGDHSADGFEVTSR...AIA'), id='NP_001648.1', name='NP_001648.1', description='NP_001648.1 amphiregulin preproprotein [Homo sapiens]', dbxrefs=[]),
 SeqRecord(seq=Seq('MEELVDEGLVKAIGISNFNHLQVEMILNKPGLKYKPAVNQIECHPYLTQEKLIQ...EEF'), id='NP_001333071.1', name='NP_001333071.1', description='NP_001333071.1 aldo-keto reductase family 1 member B1 isoform 2 [Homo sapiens]', dbxrefs=[]),
 SeqRecord(seq=Seq('MASRLLLNNGAKMPILGLGTWKSPPGQVTEAVKVAIDVGYRHIDCAHVYQNENE...EEF'), id='NP_001619.1', name='NP_001619.1', description='NP_001619.1 aldo-keto reductase family 1 member B1 isoform 1 [Homo sapiens]', dbxrefs=[])]

Let's look more carefully at the first of the TYR protein records.  It is an object with the following attributes:

* name
* id
* seq
* description

In [60]:
prot = protrecs['AR'][3]
prot

SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...WLP'), id='NP_001334992.1', name='NP_001334992.1', description='NP_001334992.1 androgen receptor isoform 4 [Homo sapiens]', dbxrefs=[])

In [61]:
prot.name

'NP_001334992.1'

In [62]:
prot.id

'NP_001334992.1'

In [63]:
prot.description

'NP_001334992.1 androgen receptor isoform 4 [Homo sapiens]'

In [64]:
prot.seq

Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...WLP')

## Match variant transcript IDs with ortholog proteins

Take variant transcript ID, query the NCBI database, extract the corresponding protein, and look for it in the ortholog set.  Flag problems.

**Output:** `translation` dictionary with transcript IDs as keys and lists of protein IDs as values.

In [79]:
import os
os.getcwd()
os.chdir('C:\\Users\\adesi\\Documents\\GitHub\\kondrashov')

In [80]:
run kondrashov

In [86]:
var_transcripts

{'ABCD1': {'genetranscript': ['NM_000033.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 327},
 'ALPL': {'genetranscript': ['NM_000478.6'],
  'number of unique transcripts': 1,
  'number of transcripts': 404},
 'AR': {'genetranscript': ['NM_000044.6'],
  'number of unique transcripts': 1,
  'number of transcripts': 269},
 'ATP7B': {'genetranscript': ['NM_000053.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 424},
 'BTK': {'genetranscript': ['NM_000061.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 245},
 'CASR': {'genetranscript': ['NM_000388.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 209},
 'CBS': {'genetranscript': ['NM_000071.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 198},
 'CFTR': {'genetranscript': ['NM_000492.4',
   'NM_000492.3',
   'NC_000007.14:g.117675861C>T'],
  'number of unique transcripts': 3,
  'number of transcripts': 773},
 'CYBB': {'genetranscript': ['NM_000397.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 141},
 'F7': {'genetranscript': ['NM_019616.4',
   'NC_000013.11:g.113105748C>G',
   'NM_000131.4',
   'NM_000131.5',
   'NC_000013.11:g.113105784G>A'],
  'number of unique transcripts': 5,
  'number of transcripts': 80},
 'F8': {'genetranscript': ['NM_000132.4', 'NC_000023.11:g.155022771G>A'],
  'number of unique transcripts': 2,
  'number of transcripts': 515},
 'F9': {'genetranscript': ['NC_000023.11:g.139530716T>A',
   'NM_000133.4',
   'NC_000023.11:g.139530731A>T',
   'NC_000023.11:g.139530710G>C'],
  'number of unique transcripts': 4,
  'number of transcripts': 274},
 'G6PD': {'genetranscript': ['NM_000402.4',
   'NM_001360016.2',
   'G6PD ZURICH',
   'NM_001042351.3'],
  'number of unique transcripts': 4,
  'number of transcripts': 207},
 'GALT': {'genetranscript': ['NM_000155.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 247},
 'GBA1': {'genetranscript': ['NM_000157.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 293},
 'GJB1': {'genetranscript': ['NM_000166.6', 'NM_001097642.3'],
  'number of unique transcripts': 2,
  'number of transcripts': 201},
 'HBB': {'genetranscript': ['NM_000518.5',
   'NM_000518.4',
   'Hb Little Rock',
   'NC_000011.10:g.5227159G>A',
   'NC_000011.10:g.5227172G>A',
   'NC_000011.10:g.5227100T>C',
   'NC_000011.10:g.5227096C>A',
   'NC_000011.10:g.5227097T>G',
   'NC_000011.10:g.5227098T>A',
   'NC_000011.10:g.5227101A>C',
   'NC_000011.10:g.5227147G>T'],
  'number of unique transcripts': 11,
  'number of transcripts': 183},
 'HPRT1': {'genetranscript': ['NM_000194.2', 'NM_000194.3', 'HPRT CHERMSIDE'],
  'number of unique transcripts': 3,
  'number of transcripts': 71},
 'IL2RG': {'genetranscript': ['NM_000206.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 113},
 'KCNH2': {'genetranscript': ['NM_000238.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 320},
 'KCNQ1': {'genetranscript': ['NM_000218.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 365},
 'L1CAM': {'genetranscript': ['NM_001278116.2'],
  'number of unique transcripts': 1,
  'number of transcripts': 146},
 'LDLR': {'genetranscript': ['NM_000527.5', 'NM_000527.4'],
  'number of unique transcripts': 2,
  'number of transcripts': 1096},
 'MPZ': {'genetranscript': ['NM_000530.8'],
  'number of unique transcripts': 1,
  'number of transcripts': 143},
 'MYH7': {'genetranscript': ['NM_000257.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 412},
 'TYR': {'genetranscript': ['NM_000372.5'],
  'number of unique transcripts': 1,
  'number of transcripts': 237},
 'PAH': {'genetranscript': ['NM_000277.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 692},
 'PMM2': {'genetranscript': ['NM_000303.3', 'NC_000016.10:g.8797716G>T'],
  'number of unique transcripts': 2,
  'number of transcripts': 174},
 'RHO': {'genetranscript': ['NM_000539.3'],
  'number of unique transcripts': 1,
  'number of transcripts': 173},
 'TP53': {'genetranscript': ['NM_000546.6'],
  'number of unique transcripts': 1,
  'number of transcripts': 417},
 'TTR': {'genetranscript': ['NM_000371.4'],
  'number of unique transcripts': 1,
  'number of transcripts': 130},
 'VWF': {'genetranscript': ['NM_000552.5'],
  'number of unique transcripts': 1,
  'number of transcripts': 310}}

In [94]:
protrecs

{'ABCD1': [SeqRecord(seq=Seq('MPVLSRPRPWRGNTLKRTAVLLALAAYGAHKVYPLVRQCLAPARGLQAPAGEPT...AST'), id='NP_000024.2', name='NP_000024.2', description='NP_000024.2 ATP-binding cassette sub-family D member 1 isoform 1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPVLSRPRPWRGNTLKRTAVLLALAAYGAHKVYPLVRQCLAPARGLQAPAGEPT...AST'), id='NP_001427676.1', name='NP_001427676.1', description='NP_001427676.1 ATP-binding cassette sub-family D member 1 isoform 2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPVLSRPRPWRGNTLKRTAVLLALAAYGAHKVYPLVRQCLAPARGLQAPAGEPT...VTR'), id='XP_047297873.1', name='XP_047297873.1', description='XP_047297873.1 ATP-binding cassette sub-family D member 1 isoform X2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MDRLQTALLVVLVLLAVALQATEAGPYGANMEDSVCCRDYVRYRLPLRVVKHFY...LSQ'), id='NP_002981.2', name='NP_002981.2', description='NP_002981.2 C-C motif chemokine 22 precursor [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MDMTPGLRHTGQSMDRLQTALLVVLVLLAVALQATEAGPYGANMEDSVCCRDYV...LSQ'), id='XP_047290405.1', name='XP_047290405.1', description='XP_047290405.1 C-C motif chemokine 22 isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MDMTPGLRHTGQSMARLQTALLVVLVLLAVALQATEAGPYGANMEDSVCCRDYV...LSQ'), id='XP_054169574.1', name='XP_054169574.1', description='XP_054169574.1 C-C motif chemokine 22 isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MARLQTALLVVLVLLAVALQATEAGPYGANMEDSVCCRDYVRYRLPLRVVKHFY...LSQ'), id='XP_054169575.1', name='XP_054169575.1', description='XP_054169575.1 C-C motif chemokine 22 isoform X2 [Homo sapiens]', dbxrefs=[])],
 'ALPL': [SeqRecord(seq=Seq('MISPFLVLAIGTCLTNSLVPEKEKDPKYWRDQAQETLKYALELQKLNTNVAKNV...VLF'), id='NP_000469.3', name='NP_000469.3', description='NP_000469.3 alkaline phosphatase, tissue-nonspecific isozyme isoform 1 preproprotein [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MFLGDGMGVSTVTAARILKGQLHHNPGEETRLEMDKFPFVALSKTYNTNAQVPD...VLF'), id='NP_001120973.2', name='NP_001120973.2', description='NP_001120973.2 alkaline phosphatase, tissue-nonspecific isozyme isoform 2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPWSFRSSTPTWLRMSSCSWEMTYNTNAQVPDSAGTATAYLCGVKANEGTVGVS...VLF'), id='NP_001170991.1', name='NP_001170991.1', description='NP_001170991.1 alkaline phosphatase, tissue-nonspecific isozyme isoform 3 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPWSFRSSTPTWLRMSSCSWEMGQLHHNPGEETRLEMDKFPFVALSKTYNTNAQ...VLF'), id='XP_016856392.1', name='XP_016856392.1', description='XP_016856392.1 alkaline phosphatase, tissue-nonspecific isozyme isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPWSFRSSTPTWLRMSSCSWEMGQLHHNPGEETRLEMDKFPFVALSKTYNTNAQ...VLF'), id='XP_054191723.1', name='XP_054191723.1', description='XP_054191723.1 alkaline phosphatase, tissue-nonspecific isozyme isoform X1 [Homo sapiens]', dbxrefs=[])],
 'AR': [SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...HTQ'), id='NP_000035.2', name='NP_000035.2', description='NP_000035.2 androgen receptor isoform 1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MILWLHSLETARDHVLPIDYYFPPQKTCLICGDEASGCHYGALTCGSCKVFFKR...HTQ'), id='NP_001011645.1', name='NP_001011645.1', description='NP_001011645.1 androgen receptor isoform 2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...TRP'), id='NP_001334990.1', name='NP_001334990.1', description='NP_001334990.1 androgen receptor isoform 3 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...WLP'), id='NP_001334992.1', name='NP_001334992.1', description='NP_001334992.1 androgen receptor isoform 4 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...QQK'), id='NP_001334993.1', name='NP_001334993.1', description='NP_001334993.1 androgen receptor isoform 5 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MRAPLLPPAPVVLSLLILGSGHYAAGLDLNDTYSGKREPFSGDHSADGFEVTSR...AIA'), id='NP_001648.1', name='NP_001648.1', description='NP_001648.1 amphiregulin preproprotein [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MEELVDEGLVKAIGISNFNHLQVEMILNKPGLKYKPAVNQIECHPYLTQEKLIQ...EEF'), id='NP_001333071.1', name='NP_001333071.1', description='NP_001333071.1 aldo-keto reductase family 1 member B1 isoform 2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MASRLLLNNGAKMPILGLGTWKSPPGQVTEAVKVAIDVGYRHIDCAHVYQNENE...EEF'), id='NP_001619.1', name='NP_001619.1', description='NP_001619.1 aldo-keto reductase family 1 member B1 isoform 1 [Homo sapiens]', dbxrefs=[])],
 'ATP7B': [SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_000044.2', name='NP_000044.2', description='NP_000044.2 copper-transporting ATPase 2 isoform a [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001005918.1', name='NP_001005918.1', description='NP_001005918.1 copper-transporting ATPase 2 isoform b [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001230111.1', name='NP_001230111.1', description='NP_001230111.1 copper-transporting ATPase 2 isoform c [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001317507.1', name='NP_001317507.1', description='NP_001317507.1 copper-transporting ATPase 2 isoform d [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001317508.1', name='NP_001317508.1', description='NP_001317508.1 copper-transporting ATPase 2 isoform e [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393442.1', name='NP_001393442.1', description='NP_001393442.1 copper-transporting ATPase 2 isoform f [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393443.1', name='NP_001393443.1', description='NP_001393443.1 copper-transporting ATPase 2 isoform g [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393444.1', name='NP_001393444.1', description='NP_001393444.1 copper-transporting ATPase 2 isoform h [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MKKSFAFDNVGYEGGLDGLGPSSQVATSTVRILGMTCQSCVKSIEDRISNLKGI...QYI'), id='NP_001393446.1', name='NP_001393446.1', description='NP_001393446.1 copper-transporting ATPase 2 isoform i [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393448.1', name='NP_001393448.1', description='NP_001393448.1 copper-transporting ATPase 2 isoform j [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393449.1', name='NP_001393449.1', description='NP_001393449.1 copper-transporting ATPase 2 isoform k [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393452.1', name='NP_001393452.1', description='NP_001393452.1 copper-transporting ATPase 2 isoform m [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393453.1', name='NP_001393453.1', description='NP_001393453.1 copper-transporting ATPase 2 isoform l [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393454.1', name='NP_001393454.1', description='NP_001393454.1 copper-transporting ATPase 2 isoform n [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393455.1', name='NP_001393455.1', description='NP_001393455.1 copper-transporting ATPase 2 isoform o [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MKKSFAFDNVGYEGGLDGLGPSSQVATSTVRILGMTCQSCVKSIEDRISNLKGI...QYI'), id='NP_001393459.1', name='NP_001393459.1', description='NP_001393459.1 copper-transporting ATPase 2 isoform p [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393463.1', name='NP_001393463.1', description='NP_001393463.1 copper-transporting ATPase 2 isoform q [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393464.1', name='NP_001393464.1', description='NP_001393464.1 copper-transporting ATPase 2 isoform r [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MKKSFAFDNVGYEGGLDGLGPSSQVATSTVRILGMTCQSCVKSIEDRISNLKGI...QYI'), id='NP_001393465.1', name='NP_001393465.1', description='NP_001393465.1 copper-transporting ATPase 2 isoform s [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393466.1', name='NP_001393466.1', description='NP_001393466.1 copper-transporting ATPase 2 isoform t [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393467.1', name='NP_001393467.1', description='NP_001393467.1 copper-transporting ATPase 2 isoform u [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MKKSFAFDNVGYEGGLDGLGPSSQVATSTVRILGMTCQSCVKSIEDRISNLKGI...QYI'), id='NP_001393468.1', name='NP_001393468.1', description='NP_001393468.1 copper-transporting ATPase 2 isoform v [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393469.1', name='NP_001393469.1', description='NP_001393469.1 copper-transporting ATPase 2 isoform w [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393470.1', name='NP_001393470.1', description='NP_001393470.1 copper-transporting ATPase 2 isoform x [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MKKSFAFDNVGYEGGLDGLGPSSQVATSTVRILGMTCQSCVKSIEDRISNLKGI...QYI'), id='NP_001393472.1', name='NP_001393472.1', description='NP_001393472.1 copper-transporting ATPase 2 isoform y [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MKKSFAFDNVGYEGGLDGLGPSSQVATSTVRILGMTCQSCVKSIEDRISNLKGI...QYI'), id='NP_001393473.1', name='NP_001393473.1', description='NP_001393473.1 copper-transporting ATPase 2 isoform z [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393474.1', name='NP_001393474.1', description='NP_001393474.1 copper-transporting ATPase 2 isoform aa [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393475.1', name='NP_001393475.1', description='NP_001393475.1 copper-transporting ATPase 2 isoform bb [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393476.1', name='NP_001393476.1', description='NP_001393476.1 copper-transporting ATPase 2 isoform cc [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'), id='NP_001393477.1', name='NP_001393477.1', description='NP_001393477.1 copper-transporting ATPase 2 isoform dd [Homo sapiens]', dbxrefs=[])],
 'BTK': [SeqRecord(seq=Seq('MAAVILESIFLKRSQQKKKTSPLNFKKRLFLLTVHKLSYYEYDFERGRRGSKKG...EES'), id='NP_000052.1', name='NP_000052.1', description='NP_000052.1 tyrosine-protein kinase BTK isoform 1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MASWSIQQMVIGCPLCGRHCSGGEHTGELQKEEAMAAVILESIFLKRSQQKKKT...EES'), id='NP_001274273.1', name='NP_001274273.1', description='NP_001274273.1 tyrosine-protein kinase BTK isoform 3 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MAAVILESIFLKRSQQKKKTSPLNFKKRLFLLTVHKLSYYEYDFERGRRGSKKG...EES'), id='NP_001274274.1', name='NP_001274274.1', description='NP_001274274.1 tyrosine-protein kinase BTK isoform 2 [Homo sapiens]', dbxrefs=[])],
 'CASR': [SeqRecord(seq=Seq('MAFYSCCWVLLALTWHTSAYGPDQRAQKKGDIILGGLFPIHFGVAAKDQDLKSR...VNS'), id='NP_000379.3', name='NP_000379.3', description='NP_000379.3 extracellular calcium-sensing receptor isoform 2 precursor [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MAFYSCCWVLLALTWHTSAYGPDQRAQKKGDIILGGLFPIHFGVAAKDQDLKSR...VNS'), id='NP_001171536.2', name='NP_001171536.2', description='NP_001171536.2 extracellular calcium-sensing receptor isoform 1 precursor [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MYQVSYASSSRLLSNKNQFKSFLRTIPNDEHQATAMADIIEYFRWNWVGTIAAD...VNS'), id='XP_047305021.1', name='XP_047305021.1', description='XP_047305021.1 extracellular calcium-sensing receptor isoform X2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MAFYSCCWVLLALTWHTSAYGPDQRAQKKGDIILGGLFPIHFGVAAKDQDLKSR...VNS'), id='XP_054204069.1', name='XP_054204069.1', description='XP_054204069.1 extracellular calcium-sensing receptor isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MYQVSYASSSRLLSNKNQFKSFLRTIPNDEHQATAMADIIEYFRWNWVGTIAAD...VNS'), id='XP_054204072.1', name='XP_054204072.1', description='XP_054204072.1 extracellular calcium-sensing receptor isoform X2 [Homo sapiens]', dbxrefs=[])],
 'CBS': [SeqRecord(seq=Seq('MPSETPQAEVGPTGCPHRSGPHSAKGSLEKGSPEDKEAKEPLWIRPDAPSRCTW...DQK'), id='NP_000062.1', name='NP_000062.1', description='NP_000062.1 cystathionine beta-synthase isoform 1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MAKCEFFNAGGSVKDRISLRMIEDAERDGTLKPGDTIIEPTSGNTGIGLALAAA...DQK'), id='NP_001308001.1', name='NP_001308001.1', description='NP_001308001.1 cystathionine beta-synthase isoform 2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MRQRMGIWRVCGWPRPGCAGGHLRCGLRPPGKGISLQDAVSRLKNVEGIPKGRS...DQK'), id='XP_011528076.1', name='XP_011528076.1', description='XP_011528076.1 cystathionine beta-synthase isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPSETPQAEVGPTGCPHRSGPHSAKGSLEKGSPEDKEAKEPLWIRPDAPSRCTW...DQK'), id='XP_011528079.1', name='XP_011528079.1', description='XP_011528079.1 cystathionine beta-synthase isoform X3 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MAKCEFFNAGGSVKDRISLRMIEDAERDGTLKPGDTIIEPTSGNTGIGLALAAA...DQK'), id='XP_011528085.1', name='XP_011528085.1', description='XP_011528085.1 cystathionine beta-synthase isoform X6 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MRQRMGIWRVCGWPRPGCAGGHLRCGLRPPGKGISLQDAVSRLKNVEGIPKGRS...DQK'), id='XP_047296974.1', name='XP_047296974.1', description='XP_047296974.1 cystathionine beta-synthase isoform X2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPLWFPQSCSAPCRTGRMGCRGRSSDRLVPRCRCRGVAKCEFFNAGGSVKDRIS...DQK'), id='XP_047296988.1', name='XP_047296988.1', description='XP_047296988.1 cystathionine beta-synthase isoform X5 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MRQRMGIWRVCGWPRPGCAGGHLRCGLRPPGKGISLQDAVSRLKSVEGIPKGRS...DQK'), id='XP_054180885.1', name='XP_054180885.1', description='XP_054180885.1 cystathionine beta-synthase isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MRQRMGIWRVCGWPRPGCAGGHLRCGLRPPGKGISLQDAVSRLKSVEGIPKGRS...DQK'), id='XP_054180887.1', name='XP_054180887.1', description='XP_054180887.1 cystathionine beta-synthase isoform X2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MPSETPQAEVGPTGCPHRSGPHSAKGSLEKGSPEDKEAKEPLWIRPDAPSRCTW...CRV'), id='XP_054180903.1', name='XP_054180903.1', description='XP_054180903.1 cystathionine beta-synthase isoform X8 [Homo sapiens]', dbxrefs=[])],
 'CFTR': [SeqRecord(seq=Seq('MQRSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADNLSEKLE...TRL'), id='NP_000483.3', name='NP_000483.3', description='NP_000483.3 cystic fibrosis transmembrane conductance regulator [Homo sapiens]', dbxrefs=[])],
 'CYBB': [SeqRecord(seq=Seq('MGNWAVNEGLSIFVILVWLGLNVFLFVWYYRVYDIPPKFFYTRKLLGSALALAR...ENF'), id='NP_000388.2', name='NP_000388.2', description='NP_000388.2 NADPH oxidase 2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MVAWMIALHSAIHTIAHLFNVEWCVNARVNNSDPYSVALSELGDRQNESYLNFA...ENF'), id='XP_047297811.1', name='XP_047297811.1', description='XP_047297811.1 NADPH oxidase 2 isoform X1 [Homo sapiens]', dbxrefs=[])],
 'F7': [SeqRecord(seq=Seq('MVSQALRLLCLLLGLQGCLAAGGVAKASGGETRDMPWKPGPHRVFVTQEEAHGV...PFP'), id='NP_000122.1', name='NP_000122.1', description='NP_000122.1 coagulation factor VII isoform a preproprotein [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MVSQALRLLCLLLGLQGCLAADGDQCASSPCQNGGSCKDQLQSYICFCLPAFEG...PFP'), id='NP_001254483.1', name='NP_001254483.1', description='NP_001254483.1 coagulation factor VII isoform c precursor [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MVSQALRLLCLLLGLQGCLAAVFVTQEEAHGVLHRRRRANAFLEELRPGSLERE...PFP'), id='NP_062562.1', name='NP_062562.1', description='NP_062562.1 coagulation factor VII isoform b precursor [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MGNVNRQGQHCRDFIMVSQALRLLCLLLGLQGCLAAVFVTQEEAHGVLHRRRRA...PFP'), id='XP_006720026.2', name='XP_006720026.2', description='XP_006720026.2 coagulation factor VII isoform X4 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MGNVNRQGQHCRDFIMVSQALRLLCLLLGLQGCLAAVFVTQEEAHGVLHRRRRA...PFP'), id='XP_011535776.2', name='XP_011535776.2', description='XP_011535776.2 coagulation factor VII isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MGNVNRQGQHCRDFIMVSQALRLLCLLLGLQGCLAADGDQCASSPCQNGGSCKD...PFP'), id='XP_011535777.2', name='XP_011535777.2', description='XP_011535777.2 coagulation factor VII isoform X2 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MAQGPEESPASWRRLKREASCWSSGSRMPGDLCSALVPSSPDKDDQLICVNENG...PFP'), id='XP_011535778.1', name='XP_011535778.1', description='XP_011535778.1 coagulation factor VII isoform X5 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MSTGRGSTAEISSWSPRPSGSSAFCLGFRAAWLQEEAHGVLHRRRRANAFLEEL...PFP'), id='XP_047286081.1', name='XP_047286081.1', description='XP_047286081.1 coagulation factor VII isoform X3 [Homo sapiens]', dbxrefs=[])],
 'F8': [SeqRecord(seq=Seq('MQIELSTCFFLCLLRFCFSATRRYYLGAVELSWDYMQSDLGELPVDARFPPRVP...DLY'), id='NP_000123.1', name='NP_000123.1', description='NP_000123.1 coagulation factor VIII isoform a preproprotein [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MRIQDPGKVFFGNVDSSGIKHNIFNPPIIARYIRLHPTHYSIRSTLRMELMGCD...DLY'), id='NP_063916.1', name='NP_063916.1', description='NP_063916.1 coagulation factor VIII isoform b [Homo sapiens]', dbxrefs=[])],
 'F9': [SeqRecord(seq=Seq('MQRVNMIMAESPGLITICLLGYLLSAECTVFLDHENANKILNRPKRYNSGKLEE...KLT'), id='NP_000124.1', name='NP_000124.1', description='NP_000124.1 coagulation factor IX isoform 1 preproprotein [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MQRVNMIMAESPGLITICLLGYLLSAECTVFLDHENANKILNRPKRYNSGKLEE...KLT'), id='NP_001300842.1', name='NP_001300842.1', description='NP_001300842.1 coagulation factor IX isoform 2 precursor [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MQRVNMIMAESPGLITICLLGYLLSAECTVFLDHENANKILNRPKRYNSGKLEE...KLT'), id='XP_005262454.1', name='XP_005262454.1', description='XP_005262454.1 coagulation factor IX isoform X1 [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MQRVNMIMAESPGLITICLLGYLLSAECTVFLDHENANKILNRPKRYNSGKLEE...KLT'), id='XP_054182657.1', name='XP_054182657.1', description='XP_054182657.1 coagulation factor IX isoform X1 [Homo sapiens]', dbxrefs=[])],
 'G6PD': [SeqRecord(seq=Seq('MGRRGSAPGNGRTLRGCERGGRRRRSADSVMAEQVALSRTQVCGILREELFQGD...HKL'), id='NP_000393.4', name='NP_000393.4', description='NP_000393.4 glucose-6-phosphate 1-dehydrogenase isoform a [Homo sapiens]', dbxrefs=[]),
  SeqRecord(seq=Seq('MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKKKIYPTIWW...HKL'), id='NP_001035810.1', name='NP_001035810.1', description='NP_001035810.1 glucose-6-phosphate 1-dehydrogenase isoform b [Homo sapiens]', dbxrefs=[])],
 'GALT': [SeqRecord(seq=Seq('MSRSGTDPQQRQQASEADAAAATFRANDHQHIRYNPLQDEWVLVSAHRMKRPWQ...TIA'), id='NP_000146.2', name='NP_000146.2', description='NP_000146.2 galactose-1-phosphate uridylyltransferase isoform 1 [Homo sapiens]', dbxrefs=[]),

In [88]:
%%time
translation = {}
i = 1
for gene in loci:
    for transcript in var_transcripts[gene]:
        if transcript[:3] == 'NM_':
            rec = get_transcript(transcript)
            seq = get_CDS(rec)
            match = False
            for prot in protrecs[gene]: 
                if seq[4] == prot.seq:
                    print(i, gene, transcript, prot.id)
                    match = True
                    translation.update({transcript: prot.id})
            if not match:
                print(i, gene, transcript, 'no matching protein         <<<<<')
        else:
            print(i, gene, transcript, 'invalid transcript name         *****')
        i += 1

1 ABCD1 genetranscript invalid transcript name         *****
2 ABCD1 number of unique transcripts invalid transcript name         *****
3 ABCD1 number of transcripts invalid transcript name         *****
4 ALPL genetranscript invalid transcript name         *****
5 ALPL number of unique transcripts invalid transcript name         *****
6 ALPL number of transcripts invalid transcript name         *****
7 AR genetranscript invalid transcript name         *****
8 AR number of unique transcripts invalid transcript name         *****
9 AR number of transcripts invalid transcript name         *****
10 ATP7B genetranscript invalid transcript name         *****
11 ATP7B number of unique transcripts invalid transcript name         *****
12 ATP7B number of transcripts invalid transcript name         *****
13 BTK genetranscript invalid transcript name         *****
14 BTK number of unique transcripts invalid transcript name         *****
15 BTK number of transcripts invalid transcript name         *****
16 CASR genetranscript invalid transcript name         *****
17 CASR number of unique transcripts invalid transcript name         *****
18 CASR number of transcripts invalid transcript name         *****
19 CBS genetranscript invalid transcript name         *****
20 CBS number of unique transcripts invalid transcript name         *****
21 CBS number of transcripts invalid transcript name         *****
22 CFTR genetranscript invalid transcript name         *****
23 CFTR number of unique transcripts invalid transcript name         *****
24 CFTR number of transcripts invalid transcript name         *****
25 CYBB genetranscript invalid transcript name         *****
26 CYBB number of unique transcripts invalid transcript name         *****
27 CYBB number of transcripts invalid transcript name         *****
28 F7 genetranscript invalid transcript name         *****
29 F7 number of unique transcripts invalid transcript name         *****
30 F7 number of transcripts invalid transcript name         *****
31 F8 genetranscript invalid transcript name         *****
32 F8 number of unique transcripts invalid transcript name         *****
33 F8 number of transcripts invalid transcript name         *****
34 F9 genetranscript invalid transcript name         *****
35 F9 number of unique transcripts invalid transcript name         *****
36 F9 number of transcripts invalid transcript name         *****
37 G6PD genetranscript invalid transcript name         *****
38 G6PD number of unique transcripts invalid transcript name         *****
39 G6PD number of transcripts invalid transcript name         *****
40 GALT genetranscript invalid transcript name         *****
41 GALT number of unique transcripts invalid transcript name         *****
42 GALT number of transcripts invalid transcript name         *****
43 GBA1 genetranscript invalid transcript name         *****
44 GBA1 number of unique transcripts invalid transcript name         *****
45 GBA1 number of transcripts invalid transcript name         *****
46 GJB1 genetranscript invalid transcript name         *****
47 GJB1 number of unique transcripts invalid transcript name         *****
48 GJB1 number of transcripts invalid transcript name         *****
49 HBB genetranscript invalid transcript name         *****
50 HBB number of unique transcripts invalid transcript name         *****
51 HBB number of transcripts invalid transcript name         *****
52 HPRT1 genetranscript invalid transcript name         *****
53 HPRT1 number of unique transcripts invalid transcript name         *****
54 HPRT1 number of transcripts invalid transcript name         *****
55 IL2RG genetranscript invalid transcript name         *****
56 IL2RG number of unique transcripts invalid transcript name         *****
57 IL2RG number of transcripts invalid transcript name         *****
58 KCNH2 genetranscript invalid transcript name         *****
59 KCNH2 number of unique transcripts invalid transcript name         *****
60 KCNH2 number of transcripts invalid transcript name         *****
61 KCNQ1 genetranscript invalid transcript name         *****
62 KCNQ1 number of unique transcripts invalid transcript name         *****
63 KCNQ1 number of transcripts invalid transcript name         *****
64 L1CAM genetranscript invalid transcript name         *****
65 L1CAM number of unique transcripts invalid transcript name         *****
66 L1CAM number of transcripts invalid transcript name         *****
67 LDLR genetranscript invalid transcript name         *****
68 LDLR number of unique transcripts invalid transcript name         *****
69 LDLR number of transcripts invalid transcript name         *****
70 MPZ genetranscript invalid transcript name         *****
71 MPZ number of unique transcripts invalid transcript name         *****
72 MPZ number of transcripts invalid transcript name         *****
73 MYH7 genetranscript invalid transcript name         *****
74 MYH7 number of unique transcripts invalid transcript name         *****
75 MYH7 number of transcripts invalid transcript name         *****
76 TYR genetranscript invalid transcript name         *****
77 TYR number of unique transcripts invalid transcript name         *****
78 TYR number of transcripts invalid transcript name         *****
79 PAH genetranscript invalid transcript name         *****
80 PAH number of unique transcripts invalid transcript name         *****
81 PAH number of transcripts invalid transcript name         *****
82 PMM2 genetranscript invalid transcript name         *****
83 PMM2 number of unique transcripts invalid transcript name         *****
84 PMM2 number of transcripts invalid transcript name         *****
85 RHO genetranscript invalid transcript name         *****
86 RHO number of unique transcripts invalid transcript name         *****
87 RHO number of transcripts invalid transcript name         *****
88 TP53 genetranscript invalid transcript name         *****
89 TP53 number of unique transcripts invalid transcript name         *****
90 TP53 number of transcripts invalid transcript name         *****
91 TTR genetranscript invalid transcript name         *****
92 TTR number of unique transcripts invalid transcript name         *****
93 TTR number of transcripts invalid transcript name         *****
94 VWF genetranscript invalid transcript name         *****
95 VWF number of unique transcripts invalid transcript name         *****
96 VWF number of transcripts invalid transcript name         *****
CPU times: total: 0 ns
Wall time: 6.95 ms

## Invalid transcript names

The following transcripts have invalid names:

* [G6PD A-](https://www.ncbi.nlm.nih.gov/clinvar/variation/10361/): includes two variants.  **Delete.**

* [HBB Little Rock](https://www.ncbi.nlm.nih.gov/clinvar/variation/15250/): should be `NM_000518.5(HBB):c.432C>R (p.His144Gln)`.  **Fix.**

* [FH Aarhus](https://www.ncbi.nlm.nih.gov/clinvar/variation/3737/): includes two variants.  **Delete.**

### G6PD A-

In [12]:
vardata = pd.read_csv('pathogenic/G6PD_clinvar.csv')
i = vardata['Name'].tolist().index('G6PD A-')
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
48,NM_001360016.2(G6PD):c.209A>G (p.Tyr70Cys),G6PD,"Y100C, Y70C",not provided,"Likely pathogenic(Last reviewed: Oct 13, 2017)","criteria provided, single submitter",VCV000449323,X,153764210,X,154535995,449323,446587,rs782090947,NC_000023.11:154535994:T:C,NaN
49,NM_000402.4(G6PD):c.298T>C (p.Tyr100His),G6PD,"Y100H, Y70H","G6PD NAMORU|Anemia, nonspherocytic hemolytic, ...",Likely pathogenic,"criteria provided, single submitter",VCV000010416,X,153764211,X,154535996,10416,25455,rs137852349,NC_000023.11:154535995:A:G,NaN
50,G6PD A-,G6PD,"V68M, V98M, N126D, N156D",Glucose 6 phosphate dehydrogenase deficiency,"Pathogenic(Last reviewed: Mar 31, 2000)",no assertion criteria provided,VCV000010361,X|X,153764217,X|X,154536002,10361,25400|25399,rs1050828|rs1050829,NC_000023.11:154536001:C:T|NC_000023.11:154535...,NaN
51,NM_001360016.2(G6PD):c.152C>T (p.Thr51Ile),G6PD,"T51I, T81I","Anemia, nonspherocytic hemolytic, due to G6PD ...","Likely pathogenic(Last reviewed: Apr 28, 2021)","criteria provided, single submitter",VCV001098498,X,153764362,X,154536147,1098498,1087248,NaN,NC_000023.11:154536146:G:A,NaN
52,NM_001360016.2(G6PD):c.98T>C (p.Ile33Thr),G6PD|IKBKG,"I33T, I63T",not provided,"Pathogenic(Last reviewed: Sep 6, 2012)","criteria provided, single submitter",VCV000093504,X,153774273,X,154546058,93504,99409,rs398123552,NC_000023.11:154546057:A:G,NaN

In [15]:
vardata.drop(i, inplace=True)
vardata.to_csv('pathogenic/G6PD_clinvar.csv', index=False)
vardata = pd.read_csv('pathogenic/G6PD_clinvar.csv')
vardata[vardata.index>i-3]

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
48,NM_001360016.2(G6PD):c.209A>G (p.Tyr70Cys),G6PD,"Y100C, Y70C",not provided,"Likely pathogenic(Last reviewed: Oct 13, 2017)","criteria provided, single submitter",VCV000449323,X,153764210,X,154535995,449323,446587,rs782090947,NC_000023.11:154535994:T:C,NaN
49,NM_000402.4(G6PD):c.298T>C (p.Tyr100His),G6PD,"Y100H, Y70H","G6PD NAMORU|Anemia, nonspherocytic hemolytic, ...",Likely pathogenic,"criteria provided, single submitter",VCV000010416,X,153764211,X,154535996,10416,25455,rs137852349,NC_000023.11:154535995:A:G,NaN
50,NM_001360016.2(G6PD):c.152C>T (p.Thr51Ile),G6PD,"T51I, T81I","Anemia, nonspherocytic hemolytic, due to G6PD ...","Likely pathogenic(Last reviewed: Apr 28, 2021)","criteria provided, single submitter",VCV001098498,X,153764362,X,154536147,1098498,1087248,NaN,NC_000023.11:154536146:G:A,NaN
51,NM_001360016.2(G6PD):c.98T>C (p.Ile33Thr),G6PD|IKBKG,"I33T, I63T",not provided,"Pathogenic(Last reviewed: Sep 6, 2012)","criteria provided, single submitter",VCV000093504,X,153774273,X,154546058,93504,99409,rs398123552,NC_000023.11:154546057:A:G,NaN

### FH Aarhus

In [16]:
vardata = pd.read_csv('pathogenic/LDLR_clinvar.csv')
i = vardata['Name'].tolist().index('FH Aarhus')
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
630,NM_000527.5(LDLR):c.1687C>T (p.Pro563Ser),LDLR,"P563S, P395S, P522S, P436S",Familial hypercholesterolemia 1,"Likely pathogenic(Last reviewed: Dec 16, 2016)","criteria provided, multiple submitters, no con...",VCV000251970,19,11226870,19,11116194,251970,246275,rs879254986,NC_000019.10:11116193:C:T,NaN
631,NM_000527.5(LDLR):c.1688C>A (p.Pro563His),LDLR,"P563H, P395H, P436H, P522H",Familial hypercholesterolemia 1,"Likely pathogenic(Last reviewed: Mar 25, 2016)","criteria provided, single submitter",VCV000251971,19,11226871,19,11116195,251971,246276,rs879254987,NC_000019.10:11116194:C:A,NaN
632,FH Aarhus,LDLR,"N564H, N437H, N523H, N396H",Homozygous familial hypercholesterolemia|Famil...,"Pathogenic(Last reviewed: Dec 7, 2018)","criteria provided, multiple submitters, no con...",VCV000003737,19|19,11226873,19|19,11116197,3737,18776|71434,NaN,NC_000019.10:11116196:A:C|NC_000019.10:1112951...,NaN
633,NM_000527.5(LDLR):c.1691A>G (p.Asn564Ser),LDLR,"N564S, N396S, N523S, N437S",Familial hypercholesterolemia|Familial hyperch...,Pathogenic/Likely pathogenic(Last reviewed: Ma...,"criteria provided, multiple submitters, no con...",VCV000224616,19,11226874,19,11116198,224616,226401,rs758194385,NC_000019.10:11116197:A:G,NaN
634,NM_000527.5(LDLR):c.1694G>C (p.Gly565Ala),LDLR,"G565A, G438A, G524A, G397A",Familial hypercholesterolemia 1,Pathogenic/Likely pathogenic(Last reviewed: Ma...,"criteria provided, multiple submitters, no con...",VCV000226366,19,11226877,19,11116201,226366,228178,rs28942082,NC_000019.10:11116200:G:C,NaN

In [17]:
vardata.drop(i, inplace=True)
vardata.to_csv('pathogenic/LDLR_clinvar.csv', index=False)
vardata = pd.read_csv('pathogenic/LDLR_clinvar.csv')
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
630,NM_000527.5(LDLR):c.1687C>T (p.Pro563Ser),LDLR,"P563S, P395S, P522S, P436S",Familial hypercholesterolemia 1,"Likely pathogenic(Last reviewed: Dec 16, 2016)","criteria provided, multiple submitters, no con...",VCV000251970,19,11226870,19,11116194,251970,246275,rs879254986,NC_000019.10:11116193:C:T,NaN
631,NM_000527.5(LDLR):c.1688C>A (p.Pro563His),LDLR,"P563H, P395H, P436H, P522H",Familial hypercholesterolemia 1,"Likely pathogenic(Last reviewed: Mar 25, 2016)","criteria provided, single submitter",VCV000251971,19,11226871,19,11116195,251971,246276,rs879254987,NC_000019.10:11116194:C:A,NaN
632,NM_000527.5(LDLR):c.1691A>G (p.Asn564Ser),LDLR,"N564S, N396S, N523S, N437S",Familial hypercholesterolemia|Familial hyperch...,Pathogenic/Likely pathogenic(Last reviewed: Ma...,"criteria provided, multiple submitters, no con...",VCV000224616,19,11226874,19,11116198,224616,226401,rs758194385,NC_000019.10:11116197:A:G,NaN
633,NM_000527.5(LDLR):c.1694G>C (p.Gly565Ala),LDLR,"G565A, G438A, G524A, G397A",Familial hypercholesterolemia 1,Pathogenic/Likely pathogenic(Last reviewed: Ma...,"criteria provided, multiple submitters, no con...",VCV000226366,19,11226877,19,11116201,226366,228178,rs28942082,NC_000019.10:11116200:G:C,NaN
634,NM_000527.5(LDLR):c.1694G>T (p.Gly565Val),LDLR,"G565V, G524V, G438V, G397V",Homozygous familial hypercholesterolemia|Famil...,Pathogenic/Likely pathogenic(Last reviewed: Ma...,"criteria provided, multiple submitters, no con...",VCV000003688,19,11226877,19,11116201,3688,18727,rs28942082,NC_000019.10:11116200:G:T,NaN

### Hb Little Rock

In [18]:
vardata = pd.read_csv('pathogenic/HBB_clinvar.csv')
i = vardata['Name'].tolist().index('Hb Little Rock')
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
6,NM_000518.5(HBB):c.436T>C (p.Tyr146His),HBB|LOC107133510|LOC110006319,Y146H,none provided|HEMOGLOBIN BETHESDA|Erythrocytos...,"Pathogenic(Last reviewed: Jan 2, 2020)","criteria provided, single submitter",VCV000015112,11,5246836,11,5225606,15112,30151,rs33949869,NC_000011.10:5225605:A:G,NaN
7,NM_000518.5(HBB):c.435G>C (p.Lys145Asn),HBB|LOC107133510|LOC110006319,K145N,HEMOGLOBIN ANDREW-MINNEAPOLIS|Erythrocytosis 6...,"Pathogenic(Last reviewed: Jan 27, 2019)","criteria provided, single submitter",VCV000015096,11,5246837,11,5225607,15096,30135,rs35020585,NC_000011.10:5225606:C:G,NaN
8,Hb Little Rock,HBB|LOC107133510|LOC110006319,H144Q,"Erythrocytosis 6, familial","Pathogenic(Last reviewed: Jan 1, 1987)",no assertion criteria provided,VCV000015250,11,5246840,11,5225610,15250,30289,NaN,NC_000011.10:5225609:G:Y,NaN
9,NM_000518.5(HBB):c.431A>C (p.His144Pro),HBB|LOC107133510|LOC110006319,H144P,"Erythrocytosis 6, familial|HEMOGLOBIN SYRACUSE...","Pathogenic(Last reviewed: Jun 20, 2019)","criteria provided, single submitter",VCV000015365,11,5246841,11,5225611,15365,30404,rs33918338,NC_000011.10:5225610:T:G,NaN
10,NM_000518.5(HBB):c.431A>G (p.His144Arg),HBB|LOC107133510|LOC110006319,H144R,not provided|none provided|HEMOGLOBIN ABRUZZO,Pathogenic/Likely pathogenic(Last reviewed: Ju...,"criteria provided, multiple submitters, no con...",VCV000015090,11,5246841,11,5225611,15090,30129,rs33918338,NC_000011.10:5225610:T:C,NaN

In [19]:
vardata.loc[i, 'Name'] = 'NM_000518.5(HBB):c.432C>R (p.His144Gln)'
vardata.to_csv('pathogenic/HBB_clinvar.csv', index=False)
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
6,NM_000518.5(HBB):c.436T>C (p.Tyr146His),HBB|LOC107133510|LOC110006319,Y146H,none provided|HEMOGLOBIN BETHESDA|Erythrocytos...,"Pathogenic(Last reviewed: Jan 2, 2020)","criteria provided, single submitter",VCV000015112,11,5246836,11,5225606,15112,30151,rs33949869,NC_000011.10:5225605:A:G,NaN
7,NM_000518.5(HBB):c.435G>C (p.Lys145Asn),HBB|LOC107133510|LOC110006319,K145N,HEMOGLOBIN ANDREW-MINNEAPOLIS|Erythrocytosis 6...,"Pathogenic(Last reviewed: Jan 27, 2019)","criteria provided, single submitter",VCV000015096,11,5246837,11,5225607,15096,30135,rs35020585,NC_000011.10:5225606:C:G,NaN
8,NM_000518.5(HBB):c.432C>R (p.His144Gln),HBB|LOC107133510|LOC110006319,H144Q,"Erythrocytosis 6, familial","Pathogenic(Last reviewed: Jan 1, 1987)",no assertion criteria provided,VCV000015250,11,5246840,11,5225610,15250,30289,NaN,NC_000011.10:5225609:G:Y,NaN
9,NM_000518.5(HBB):c.431A>C (p.His144Pro),HBB|LOC107133510|LOC110006319,H144P,"Erythrocytosis 6, familial|HEMOGLOBIN SYRACUSE...","Pathogenic(Last reviewed: Jun 20, 2019)","criteria provided, single submitter",VCV000015365,11,5246841,11,5225611,15365,30404,rs33918338,NC_000011.10:5225610:T:G,NaN
10,NM_000518.5(HBB):c.431A>G (p.His144Arg),HBB|LOC107133510|LOC110006319,H144R,not provided|none provided|HEMOGLOBIN ABRUZZO,Pathogenic/Likely pathogenic(Last reviewed: Ju...,"criteria provided, multiple submitters, no con...",VCV000015090,11,5246841,11,5225611,15090,30129,rs33918338,NC_000011.10:5225610:T:C,NaN

## Transcripts not matching any human protein

### VWF NM_000552.4

We compare it with the transcript with the later version number:

* They have the same length.

* They differ at only one site.  

Thus, we can analyse variants referencing the old transcript as long as we avoid position 851.  I add it to the `translation`dictionary in the [find_CPDs.ipynb](find_CPDs.ipynb) notebook.

In [20]:
old_rec = get_transcript('NM_000552.4')
old_prot = get_CDS(old_rec)[4]
old_prot

Seq('MIPARFAGVLLALALILPGTLCAEGTRGRSSTARCSLFGSDFVNTFDGSMYSFA...CSK')

In [21]:
new_rec = get_transcript('NM_000552.5')
new_prot = get_CDS(new_rec)[4]
new_prot

Seq('MIPARFAGVLLALALILPGTLCAEGTRGRSSTARCSLFGSDFVNTFDGSMYSFA...CSK')

In [22]:
print(len(old_prot), len(new_prot))

2813 2813

In [23]:
for i in range(2813):
    if old_prot[i]!=new_prot[i]:
        print(i, old_prot[i], new_prot[i])

851 R Q

### PAH NM_004316.4

The following cell shows that this unmatched transcript is not of the PAH gene.  **I delete the variant associated with this transcript.**

In [24]:
# should have been PAH
transcript = 'NM_004316.4'
rec = get_transcript(transcript)
rec['GBSeq_definition']

'Homo sapiens achaete-scute family bHLH transcription factor 1 (ASCL1), mRNA'

In [25]:
# example of a PAH transcript (control)
transcript = 'NM_000277.3'
rec = get_transcript(transcript)
rec['GBSeq_definition']

'Homo sapiens phenylalanine hydroxylase (PAH), transcript variant 1, mRNA'

In [26]:
vardata = pd.read_csv('pathogenic/PAH_clinvar.csv')
vardata['Gene(s)'].value_counts()

PAH          357
PAH|ASCL1      1
Name: Gene(s), dtype: int64

In [27]:
i = vardata['Gene(s)'].tolist().index('PAH|ASCL1')
i

357

In [28]:
vardata.tail()

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
353,NM_000277.3(PAH):c.2T>C (p.Met1Thr),PAH,M1T,not provided|Phenylketonuria,"Likely pathogenic(Last reviewed: Jul 7, 2019)",reviewed by expert panel,VCV000203873,12,103310907,12,102917129,203873,200225,rs62508575,NC_000012.12:102917128:A:G,NaN
354,NM_000277.3(PAH):c.2T>G (p.Met1Arg),PAH,M1R,not provided|Phenylketonuria,"Pathogenic(Last reviewed: Jul 7, 2019)",reviewed by expert panel,VCV000102647,12,103310907,12,102917129,102647,108383,rs62508575,NC_000012.12:102917128:A:C,NaN
355,NM_000277.3(PAH):c.1A>T (p.Met1Leu),PAH,M1L,Phenylketonuria|not provided,"Pathogenic(Last reviewed: Jul 7, 2019)",reviewed by expert panel,VCV000102626,12,103310908,12,102917130,102626,108362,rs62514891,NC_000012.12:102917129:T:A,NaN
356,NM_000277.3(PAH):c.1A>G (p.Met1Val),PAH,M1V,"not provided|Hyperphenylalaninemia, non-pku|Ph...","Pathogenic(Last reviewed: Aug 7, 2018)",reviewed by expert panel,VCV000000586,12,103310908,12,102917130,586,15625,rs62514891,NC_000012.12:102917129:T:C,NaN
357,NM_004316.4(ASCL1):c.52C>A (p.Pro18Thr),PAH|ASCL1,P18T,Congenital central hypoventilation,"Pathogenic(Last reviewed: Dec 1, 2003)",no assertion criteria provided,VCV000018332,12,103352074,12,102958296,18332,33371,rs267606667,NC_000012.12:102958295:C:A,NaN

In [29]:
vardata.drop(i, inplace=True)
vardata.to_csv('pathogenic/PAH_clinvar.csv', index=False)
vardata = pd.read_csv('pathogenic/PAH_clinvar.csv')
vardata.tail()

,Name,Gene(s),Protein change,Condition(s),Clinical significance (Last reviewed),Review status,Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,AlleleID(s),dbSNP ID,Canonical SPDI,Unnamed: 15
352,NM_000277.3(PAH):c.3G>A (p.Met1Ile),PAH,M1I,Phenylketonuria|not provided,"Pathogenic(Last reviewed: Jul 7, 2019)",reviewed by expert panel,VCV000000622,12,103310906,12,102917128,622,15661,rs62514893,NC_000012.12:102917127:C:T,NaN
353,NM_000277.3(PAH):c.2T>C (p.Met1Thr),PAH,M1T,not provided|Phenylketonuria,"Likely pathogenic(Last reviewed: Jul 7, 2019)",reviewed by expert panel,VCV000203873,12,103310907,12,102917129,203873,200225,rs62508575,NC_000012.12:102917128:A:G,NaN
354,NM_000277.3(PAH):c.2T>G (p.Met1Arg),PAH,M1R,not provided|Phenylketonuria,"Pathogenic(Last reviewed: Jul 7, 2019)",reviewed by expert panel,VCV000102647,12,103310907,12,102917129,102647,108383,rs62508575,NC_000012.12:102917128:A:C,NaN
355,NM_000277.3(PAH):c.1A>T (p.Met1Leu),PAH,M1L,Phenylketonuria|not provided,"Pathogenic(Last reviewed: Jul 7, 2019)",reviewed by expert panel,VCV000102626,12,103310908,12,102917130,102626,108362,rs62514891,NC_000012.12:102917129:T:A,NaN
356,NM_000277.3(PAH):c.1A>G (p.Met1Val),PAH,M1V,"not provided|Hyperphenylalaninemia, non-pku|Ph...","Pathogenic(Last reviewed: Aug 7, 2018)",reviewed by expert panel,VCV000000586,12,103310908,12,102917130,586,15625,rs62514891,NC_000012.12:102917129:T:C,NaN