# ----------------------------------------
# Clinvar

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')

## Step 1.  fiLTER Database from Clinvar

In [6]:
Clinvar_main= pd.read_csv("/Users/adesinamary/Documents/Variant_summary_genes/variant_summary.txt", sep="\t")

/var/folders/31/rr38lns17x78c7dt588fmqmw0000gs/T/ipykernel_56612/1228737715.py:1: DtypeWarning: Columns (0: Chromosome) have mixed types. Specify dtype option on import or set low_memory=False.
  Clinvar_main= pd.read_csv("/Users/adesinamary/Documents/Variant_summary_genes/variant_summary.txt", sep="\t")

In [7]:
pd.set_option('display.max_columns', 50)
Clinvar_main.head(5)
#Clinvar_main.columns

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),nsv/esv (dbVar),RCVaccession,PhenotypeIDS,PhenotypeList,Origin,OriginSimple,Assembly,ChromosomeAccession,Chromosome,Start,Stop,ReferenceAllele,AlternateAllele,Cytogenetic,ReviewStatus,NumberSubmitters,Guidelines,TestedInGTR,OtherIDs,SubmitterCategories,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh37,NC_000007.13,7,4820844,4820847,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4820844,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh38,NC_000007.14,7,4781213,4781216,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4781213,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh37,NC_000007.13,7,4827361,4827374,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4827360,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh38,NC_000007.14,7,4787730,4787743,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4787729,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,-,RCV000000014,"MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",Galloway-Mowat syndrome 1,germline,germline,GRCh37,NC_000015.9,15,85342440,85342440,na,na,15q25.3,no assertion criteria provided,1,-,N,"ClinGen:CA210674,UniProtKB:Q92610#VAR_064583,O...",1,4,85342440,G,A,-,-,-,-,-,-,SCV000020157,-,-

In [8]:
Clinvar_main.shape
Clinvar_main.dtypes
Clin1= Clinvar_main[[#'#AlleleID', 
    'Type', 'Name', 
    'GeneID', 
    'GeneSymbol', 
    #'HGNC_ID',
       'ClinicalSignificance', 
       #'ClinSigSimple', 'LastEvaluated', 'RS# (dbSNP)',
       #'nsv/esv (dbVar)', 'RCVaccession', 'PhenotypeIDS', 'PhenotypeList',
       #'Origin', 'OriginSimple', 
       'Assembly', 
       #'ChromosomeAccession',
       #'Chromosome', 'Start', 'Stop', 'ReferenceAllele', 'AlternateAllele',
       #'Cytogenetic', 'ReviewStatus', 'NumberSubmitters', 'Guidelines',
       #'TestedInGTR', 'OtherIDs', 'SubmitterCategories', 
       'VariationID',
       #'PositionVCF', 'ReferenceAlleleVCF', 'AlternateAlleleVCF',
       #'SomaticClinicalImpact', 'SomaticClinicalImpactLastEvaluated',
       #'ReviewStatusClinicalImpact', 'Oncogenicity',
       #'OncogenicityLastEvaluated', 'ReviewStatusOncogenicity',
       #'SCVsForAggregateGermlineClassification',
       #'SCVsForAggregateSomaticClinicalImpact',
       #'SCVsForAggregateOncogenicityClassification'
       ]]

## Jump to step 2 belowww

In [9]:
Clinvar_main.shape

(8990435, 43)

In [10]:
Clin1.shape

(8990435, 7)

In [82]:
Clin1.head(10)
Clin1.to_csv("/Users/adesinamary/Documents/variant_summary_filtered.csv", index=False)

KeyboardInterrupt:

In [ ]:
Clin1.ClinicalSignificance.unique().tolist()

['Pathogenic/Likely pathogenic',
 'Pathogenic',
 'Uncertain significance',
 'Likely pathogenic',
 'Conflicting classifications of pathogenicity',
 'Pathogenic/Pathogenic, low penetrance; risk factor',
 'Conflicting classifications of pathogenicity; other',
 'Benign',
 'risk factor',
 'Likely benign',
 'association',
 'Likely pathogenic; risk factor',
 'Benign/Likely benign',
 'no classification for the single variant',
 'Conflicting classifications of pathogenicity; risk factor',
 'drug response',
 'Affects',
 'Benign; drug response',
 'Likely benign; drug response',
 'Conflicting classifications of pathogenicity; association; risk factor',
 'Pathogenic; risk factor',
 'Benign; risk factor',
 'no classifications from unflagged records',
 'Benign/Likely benign; other',
 'Pathogenic/Likely pathogenic; risk factor',
 'Benign; other',
 'not provided',
 'protective; risk factor',
 'Likely benign; other',
 'Conflicting classifications of pathogenicity; association',
 'Pathogenic; Affects',
 'Benign/Likely benign; association',
 'association; drug response; risk factor',
 'Benign/Likely benign; other; risk factor',
 'Benign; protective',
 'Pathogenic/Likely pathogenic/Likely pathogenic, low penetrance',
 'drug response; risk factor',
 'Pathogenic; drug response',
 'protective',
 'Likely risk allele',
 'Uncertain significance/Uncertain risk allele',
 'Conflicting classifications of pathogenicity; protective',
 'Uncertain significance; risk factor',
 'drug response; other',
 'Likely benign; drug response; other',
 '-',
 'Uncertain significance; drug response',
 'Likely pathogenic; drug response',
 'other',
 'Pathogenic; other',
 'Conflicting classifications of pathogenicity; drug response; other',
 'Conflicting classifications of pathogenicity; drug response',
 'Benign; association',
 'Pathogenic/Likely pathogenic/Pathogenic, low penetrance',
 'Likely pathogenic; association',
 'Pathogenic/Likely pathogenic/Pathogenic, low penetrance/Established risk allele; risk factor',
 'Pathogenic/Likely risk allele',
 'Likely pathogenic/Likely risk allele',
 'Pathogenic/Likely pathogenic/Likely risk allele',
 'Conflicting classifications of pathogenicity; other; risk factor',
 'Pathogenic; protective',
 'other; risk factor',
 'Uncertain significance; other',
 'Pathogenic/Likely pathogenic; other',
 'Likely pathogenic, low penetrance',
 'Pathogenic, low penetrance',
 'Benign/Likely benign; drug response; other',
 'Benign; Affects',
 'Pathogenic/Pathogenic, low penetrance; other',
 'Likely benign; Affects; association',
 'conflicting data from submitters',
 'Uncertain significance; Pathogenic/Likely pathogenic',
 'Uncertain significance/VUS-high',
 'Uncertain risk allele; risk factor',
 'Pathogenic/Likely pathogenic; drug response',
 'Pathogenic/Likely pathogenic; association',
 'VUS-high',
 'Uncertain significance/VUS-mid',
 'Likely benign; risk factor',
 'Benign/Likely benign; drug response',
 'Benign/Likely benign; risk factor',
 'Pathogenic/Pathogenic, low penetrance',
 'Uncertain risk allele',
 'Benign; confers sensitivity',
 'Uncertain significance; association',
 'Likely pathogenic/Pathogenic, low penetrance',
 'association; risk factor',
 'Pathogenic; confers sensitivity',
 'Conflicting classifications of pathogenicity; Affects',
 'Pathogenic; association',
 'Likely pathogenic; Affects',
 'association not found',
 'Likely benign; association',
 'Likely pathogenic; protective',
 'Benign; Affects; association; other',
 'Pathogenic/Likely pathogenic/Established risk allele',
 'Uncertain significance; Affects',
 'confers sensitivity',
 'confers sensitivity; other',
 'Established risk allele; association',
 'Likely pathogenic/Likely pathogenic, low penetrance',
 'Pathogenic/Likely pathogenic, low penetrance',
 'Uncertain significance/VUS-low',
 'VUS-low',
 'Established risk allele',
 'VUS-mid']

terms = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, low penetrance"]

#for gene in ["ABCD1"]:
    filtered = Clin[
        (Clin2["GeneSymbol"] == "ABCD1" )&
        (Clin2["ClinicalSignificance"].isin (terms)) &
        (Clin2["Type"] == "single nucleotide variant") &
        (Clin2["Assembly"] == "GRCh38")
        ]
    #filtered.to_csv(f"clinvar/{gene}.txt", sep="\t", index= False)
    #print(f"{gene}: {len(filtered)} variants written to clinvar/{gene}.txt")

In [ ]:
terms = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, low penetrance"]

#for gene in ["ABCD1"]:
variant_summary_filtered_ABCD1 = Clin1[
    (Clin1["GeneSymbol"] == "ABCD1" )&
    (Clin1["ClinicalSignificance"].isin (terms)) &
    (Clin1["Type"] == "single nucleotide variant")&
    (Clin1["Assembly"] == "GRCh38")
    ]
#variant_summary_filtered_ABCD1.to_csv("/Users/adesinamary/Documents/variant_summary_filtered_ABCD1.csv", index=False)

variant_summary_filtered_ABCD1

,Type,Name,GeneSymbol,ClinicalSignificance,Assembly
20554,single nucleotide variant,NM_000033.4(ABCD1):c.871G>A (p.Glu291Lys),ABCD1,Pathogenic,GRCh38
20556,single nucleotide variant,NM_000033.4(ABCD1):c.1451C>G (p.Pro484Arg),ABCD1,Pathogenic,GRCh38
20558,single nucleotide variant,NM_000033.4(ABCD1):c.1635-2A>G,ABCD1,Pathogenic,GRCh38
20560,single nucleotide variant,NM_000033.4(ABCD1):c.1165C>G (p.Arg389Gly),ABCD1,Pathogenic,GRCh38
20562,single nucleotide variant,NM_000033.4(ABCD1):c.443A>G (p.Asn148Ser),ABCD1,Pathogenic/Likely pathogenic,GRCh38
...,...,...,...,...,...
8877161,single nucleotide variant,NM_000033.4(ABCD1):c.1640A>T (p.Tyr547Phe),ABCD1,Pathogenic,GRCh38
8877167,single nucleotide variant,NM_000033.4(ABCD1):c.1976A>G (p.His659Arg),ABCD1,Likely pathogenic,GRCh38
8915686,single nucleotide variant,NM_000033.4(ABCD1):c.796G>C (p.Gly266Arg),ABCD1,Likely pathogenic,GRCh38
8977633,single nucleotide variant,NM_000033.4(ABCD1):c.274G>C (p.Gly92Arg),ABCD1,Likely pathogenic,GRCh38
8980660,single nucleotide variant,NM_000033.4(ABCD1):c.1256T>C (p.Val419Ala),ABCD1,Pathogenic,GRCh38

In [ ]:
variant_summary_filtered_ABCD1.shape

(327, 5)

In [ ]:
#Clin1.GeneSymbol
#Clin1.GeneSymbol.values
Clin1["GeneSymbol"]
list(Clin1["GeneSymbol"])
Clin1.GeneSymbol.nunique()

41092

In [ ]:
yy= Clin1.GeneSymbol.unique().tolist()
print(len(yy))
yy

41092

['AP5Z1',
 'ZNF592',
 'FOXRED1',
 'NUBPL',
 'HFE',
 'WDR35',
 'ABHD12',
 'ZNF513',
 'HOGA1',
 'FAM161A',
 'WDR62',
 'WDPCP',
 'TBC1D24',
 'XPNPEP3',
 'MTRFR',
 'CEP152',
 'SDCCAG8',
 'OPN1SW',
 'UROD',
 'LIPA',
 'HPSE2',
 'ASAH1',
 'TCN2',
 'PCARE',
 'MIR2861',
 'TMEM127',
 'VIPAS39',
 'POMP',
 'CBS',
 'TPRN',
 'SLC52A3',
 'OAT',
 'DPYS',
 'SH3PXD2B',
 'ATXN8;ATXN8OS;LOC109461478',
 'GRXCR1',
 'TMEM216',
 'USB1',
 'KCNJ18',
 'PEPD',
 'AGA',
 'CYB5A',
 'WDR72',
 'CYB5R3',
 'XPC',
 'DNAAF1',
 'RBM20',
 'KLHDC8B',
 'SERPINF2',
 'CANT1',
 'VWF',
 'TSPAN12',
 'NEXN',
 'RETREG1',
 'NF1',
 'CTSA',
 'GM2A',
 'LOXHD1',
 'INPP5E',
 'SDHAF2',
 'TAT',
 'UROC1',
 'HTT',
 'TMEM126A',
 'TACO1',
 'RNASET2',
 'PGAM2',
 'NDUFAF3',
 'TUBB1',
 'TUBB2B',
 'SDHAF1',
 'COQ9',
 'DPYD',
 'BCAM',
 'DUOXA2',
 'CCBE1',
 'CPOX',
 'ALDOB',
 'PTS',
 'RNF168',
 'QDPR',
 'RFX6',
 'RSPH4A',
 'ANK1',
 'LMBRD1',
 'FBN2',
 'DNAAF2',
 'DCAF17',
 'EYS',
 'TMEM70',
 'LRTOMT',
 'NDUFAF6',
 'FECH',
 'SLC29A3',
 'NDUFAF5',
 'KNG1',
 'PAH',
 'CILK1',
 'FASTKD2',
 'F5',
 'PROC',
 'FUCA1',
 'ADAMTSL2',
 'GALNS',
 'ZFP57',
 'NAT2',
 'TPCN2',
 'UQCRQ',
 'ZNF469',
 'RBM28',
 'BEAN1',
 'TMEM43',
 'RNF212',
 'IYD',
 'CC2D2A',
 'ZFYVE26',
 'GIGYF2',
 'TRAPPC9',
 'MMADHC',
 'SACK1H',
 'ISCU',
 'SLC16A12',
 'RFT1',
 'GPD1L',
 'NDUFAF4',
 'NKX2-6',
 'LMF1',
 'APC',
 'KCTD7',
 'ATP6V0A2',
 'TTBK2',
 'SART3',
 'SLC46A1',
 'UBIAD1',
 'MIR96',
 'FBP1',
 'UPK3A',
 'NCR3',
 'ARSB',
 'FOXD3',
 'EMG1',
 'RARS2',
 'CISD2',
 'GUSB',
 'CYP4F22',
 'CA2',
 'MBD5',
 'PLEKHM1',
 'GLB1',
 'DOCK8',
 'OCA2',
 'LCA5',
 'DIP2B',
 'FANCI',
 'FANCI;POLG',
 'RNF135',
 'ARMS2',
 'NHEJ1',
 'CDKAL1',
 'IFT80',
 'XPA',
 'ATXN10',
 'SLC30A8',
 'MFSD8',
 'KLHL7',
 'FGD4',
 'ACAD9',
 'PLEKHG5',
 'MTMR14',
 'MIAT',
 'FAM20C',
 'SETBP1',
 'CCDC50',
 'G6PC3',
 'FA2H',
 'OBSL1',
 'INF2',
 'FTO',
 'YARS2',
 'DARS2',
 'RPGRIP1L',
 'PSAT1',
 'NOBOX',
 'ZFAT',
 'CHMP4B',
 'FLVCR2',
 'AGL',
 'SPG11',
 'SLC25A38',
 'SLC35D1',
 'ATG16L1',
 'DOLK',
 'STRA6',
 'DDX25;HYLS1;PUS3',
 'HIBCH',
 'BBS12',
 'PFKM',
 'WASHC5',
 'F12',
 'CYP11B1',
 'PRCD',
 'ARHGAP9',
 'RSPO4',
 'MARVELD2',
 'PDSS2',
 'MAT1A',
 'GNAS;GNAS-AS1',
 'WWC1',
 'HYCC1',
 'ATP13A2',
 'SEC23B',
 'SEC23A',
 'SAMD9',
 'HGSNAT',
 'LAMTOR2',
 'RAX2',
 'PALB2',
 'P3H1',
 'RNASEH2C',
 'RNASEH2B',
 'B3GLCT',
 'BANK1',
 'GALNT12',
 'DOK7',
 'ORAI1',
 'PIGV',
 'PIGM',
 'ZFYVE27',
 'TRMU',
 'ZNF750',
 'RIN2',
 'PJVK',
 'SLC4A11',
 'MED25',
 'GLIS3',
 'CCDC28B',
 'CCT5',
 'BBS10',
 'CEP290',
 'VANGL1',
 'ADAMTSL4',
 'SIAE',
 'CC2D1A',
 'ALDH5A1',
 'CLDN19',
 'EHBP1',
 'TMEM67',
 'MKS1',
 'SPATA7',
 'TMPRSS6',
 'SPATA16',
 'SI',
 'SLC24A4',
 'MMACHC',
 'SLC34A3',
 'COQ2',
 'HMBS',
 'SLC24A5',
 'NEK8',
 'BLOC1S3',
 'TRIOBP',
 'ACOX1',
 'PKLR',
 'LPL',
 'NAGLU',
 'HPD',
 'SLITRK1',
 'WDR36',
 'NLRP7',
 'NDUFAF2',
 'NLRP12',
 'FANCM',
 'NECTIN4',
 'RSPO1',
 'GLRX5',
 'L2HGDH',
 'CUL7',
 'ACADL',
 'ACADVL',
 'PLEKHG4',
 'ALDH3A2',
 'THAP1',
 'CHMP2B',
 'TOPORS',
 'CYP27B1',
 'MANBA',
 'MAN2B1',
 'HAL',
 'NDUFA13',
 'LHFPL5',
 'PIKFYVE',
 'ERCC6',
 'ERCC8',
 'ERCC8;NDUFAF2',
 'STOX1',
 'FIG4',
 'NIPAL4',
 'KIFBP',
 'ESCO2',
 'CBLIF',
 'DBH',
 'MSH2',
 'SLC25A22',
 'CYP17A1',
 'SPRED1',
 'CPAP',
 'RAB3GAP2',
 'CRBN',
 'LIPI',
 'GPSM2',
 'LPAR6',
 'IQCB1',
 'MRPS16',
 'MRAP',
 'MPLKIP',
 'SUGCT',
 'D2HGDH',
 'REEP1',
 'PDCD10',
 'POU6F2',
 'PNPLA2',
 'MMUT',
 'KRT75',
 'PNKD',
 'BTD',
 'HLCS',
 'ERMAP',
 'MCCC2',
 'MCCC1',
 'LRRK2',
 'ADAMTS10',
 'DNAJC19',
 'CABP4',
 'ADA',
 'ADA;PKIG',
 'FREM2',
 'FREM1',
 'ARL13B',
 'PITPNM3',
 'ATPAF2',
 'UNC13D',
 'SGCG',
 'AHI1',
 'SLC6A19',
 'CHD7',
 'PPARGC1B',
 'ARL6',
 'RDH12',
 'SUMO4;TAB2',
 'EFHC1',
 'GJC2',
 'GCDH',
 'GCDH;KLF1;LOC117125594',
 'GSDME',
 'PC',
 'GTF2H5',
 'ANKK1',
 'MED13L',
 'DLAT',
 'PDHX',
 'LLGL2;TSEN54',
 'TSEN54',
 'TSEN34',
 'TSEN2',
 'C1QTNF5',
 'ALG3',
 'SLC39A13',
 'CYP2R1',
 'DNAAF4',
 'FIGLA',
 'NIPBL',
 'PEX26',
 'ANO5',
 'SEC63',
 'CASP12',
 'ROBO3',
 'STRADA',
 'CYP4V2',
 'NPSR1',
 'RP1L1',
 'GRHL2',
 'MYH14',
 'VPS33B',
 'HMCN1',
 'VKORC1',
 'VHL',
 'NCF2',
 'NCF1',
 'CYBA',
 'MFN2',
 'PRICKLE1',
 'SETX',
 'PYGM',
 'ETHE1',
 'SYNE2',
 'SYNE1',
 'CHST14',
 'MCEE',
 'PLCE1',
 'USH2A',
 'SLC9A9',
 'CERKL',
 'HJV',
 '-',
 'BCKDHA',
 'SLC36A2',
 'ARG1',
 'ASL',
 'PINK1',
 'CPS1',
 'NAGS',
 'IGF2BP2',
 'KIF21A',
 'NEU1',
 'SCN4B',
 'KRT74',
 'ADSL',
 'MASTL',
 'SCN3B',
 'EXT2',
 'SH3TC2',
 'UNC93B1',
 'CDK5RAP2',
 'SPG21',
 'EXT1',
 'CACNA2D4',
 'SEMA3E',
 'SOX9',
 'SATB2',
 'NIPA1',
 'NSMF',
 'ARHGEF10',
 'ASPN;CENPP',
 'TTC8',
 'XYLT2',
 'XYLT1',
 'FANCL',
 'PUS1',
 'MEFV',
 'ALG8',
 'CLN5',
 'PALLD',
 'APOC4-APOC2;APOC2',
 'APOC2',
 'NHLRC1',
 'ETFA',
 'ANTXR2',
 'ASPA',
 'HSPB8',
 'NPC1L1',
 'SIL1',
 'NPHP3',
 'TPP1',
 'GORAB',
 'COX4I2',
 'BBS9',
 'SUMF1',
 'SUMF2',
 'CCM2',
 'WHRN',
 'A4GALT',
 'ALG2',
 'CACNA1H',
 'FERMT3',
 'FERMT1',
 'DSG4',
 'BEST1',
 'LEMD3',
 'GNPTAB',
 'GBE1',
 'GNPTG',
 'CLN8',
 'FRAS1',
 'ZNF365',
 'VPS13B',
 'RGS9BP',
 'ACAT1',
 'CNNM4',
 'ABCA12',
 'MCFD2',
 'PCSK9',
 'HSD3B7',
 'KIRREL3',
 'ITGA2B',
 'TAS2R38',
 'TJP2',
 'KANK1',
 'SBF2',
 'USH1G',
 'SECISBP2',
 'SAR1B',
 'CLCF1',
 'GNS',
 'CTH',
 'OSTM1',
 'FSCN2',
 'RAI1',
 'ATXN7',
 'XDH',
 'NPC1',
 'APBB1;SMPD1',
 'SMPD1',
 'KRT9',
 'KCNV2',
 'BBS7',
 'ATM',
 'ARSA',
 'MMAB',
 'EPM2A',
 'IL23R',
 'SLC17A8',
 'LRPPRC',
 'KCNQ1',
 'HPS6',
 'HPS5',
 'ADAMTS17',
 'MMAA',
 'APCDD1',
 'TPH2',
 'HGD',
 'CDAN1',
 'DYM',
 'UTP4',
 'SBDS',
 'FKTN',
 'POMT2',
 'PDSS1',
 'POMT1',
 'NME8',
 'MC2R',
 'CDC73',
 'NF2',
 'LIPH',
 'AIRE',
 'SALL4',
 'GABBR2',
 'RP9',
 'SRD5A2',
 'PRPF3',
 'PRPF8',
 'SEMA4A',
 'FLCN',
 'EVC2',
 'TMIE',
 'IRF5',
 'NPHP4',
 'CARD9',
 'ALOXE3',
 'IRF6',
 'TDP1',
 'PTF1A',
 'CRELD1',
 'DTNBP1',
 'ALG12',
 'FANCA',
 'PROKR2',
 'MCPH1',
 'SPART',
 'PAX6',
 'WT1',
 'NPHP1',
 'SLC22A12',
 'MTHFR',
 'HYAL1',
 'FKBP10',
 'SLC39A4',
 'IMPG2',
 'ATXN3',
 'CLN3',
 'ABCC11',
 'OTOA',
 'IVD',
 'SUFU',
 'TRPM6',
 'ACADM',
 'PROK2',
 'EHMT1',
 'GALT',
 'MPO',
 'LPO;MPO',
 'COQ8A',
 'COG8',
 'COG7',
 'COG4',
 'COG1',
 'LCAT',
 'GALE',
 'LDLR',
 'LDLR;MIR6886',
 'ALG9',
 'UROS',
 'TRPM4',
 'TYR',
 'LYST',
 'GALC',
 'SUOX',
 'ACADS',
 'IRAK4',
 'ATP7B',
 'PHGDH',
 'HEXB',
 'HEXA',
 'SERPING1',
 'GCLC',
 'TCOF1',
 'ALMS1',
 'RB1CC1',
 'FXN',
 'POMGNT1',
 'COG5',
 'ALDH4A1',
 'PRODH',
 'MYO3A',
 'FTCD',
 'GAA',
 'ST14',
 'TPO',
 'MLYCD',
 'DUOX2',
 'SAMHD1',
 'TLL1',
 'CLN6',
 'SLC26A2',
 'PRSS12',
 'TMC1',
 'PKHD1',
 'EIF2B4',
 'EIF2B1',
 'HPS4',
 'NSD1',
 'UPB1',
 'GP1BA',
 'RXFP2',
 'GFM1',
 'NLRP1',
 'TMPRSS15',
 'RIMS1',
 'GNMT',
 'SMARCAL1',
 'TREX1',
 'EDARADD',
 'GDAP1',
 'PAX3',
 'FKRP',
 'ENAM',
 'OPA3',
 'MYLK2',
 'LZTS1',
 'MYO5B',
 'SCGB3A2',
 'CYP27A1',
 'MLPH',
 'SLC25A19',
 'HAVCR1',
 'ZMPSTE24',
 'ITPKC',
 'NOP10',
 'NHP2',
 'HAMP',
 'GBA1',
 'EIF2B2',
 'HTRA2;LOXL3',
 'HTRA2',
 'STRC',
 'ATL1',
 'EGLN1',
 'PRPF31',
 'DHCR24',
 'NLRP3',
 'BSND',
 'ANTXR1',
 'ITCH',
 'CLRN1',
 'CLRN1-AS1;CLRN1',
 'CATSPER1',
 'APOA5',
 'ALS2',
 'ESPN',
 'APTX',
 'PSTPIP1',
 'SIX6',
 'EIF2B3',
 'CTNS',
 'TNFRSF13C',
 'WNT10A',
 'CLEC7A',
 'TIRAP',
 'DICER1',
 'MFRP',
 'NT5C3A',
 'SELENON',
 'SLC45A2',
 'WFS1',
 'BHLHE41',
 'BSCL2',
 'BSCL2;HNRNPUL2-BSCL2',
 'PANK2',
 'MIR103A2;MIR103B2;PANK2',
 'SLC19A3',
 'BBS2',
 'SLC2A10',
 'RAB23',
 'SLC2A9',
 'SLURP1',
 'HPS3',
 'PIP5K1C',
 'TWNK',
 'SMC3',
 'TBX20',
 'IFT122',
 'CD96',
 'RNASEH2A',
 'ALX3',
 'BTNL2',
 'HAX1',
 'KIF1B',
 'PDP1',
 'DCLRE1C',
 'UBR1',
 'VPS13A',
 'NOD2',
 'DPM3',
 'PCNT',
 'STIM1',
 'ANGPTL4',
 'MLC1',
 'ALG1',
 'LDB3',
 'BRIP1',
 'SLC35C1',
 'KCNK9',
 'DMGDH',
 'HERC2',
 'TMC8',
 'TMC6',
 'NUP62',
 'MRPS22',
 'ZEB2',
 'AMN',
 'BCO1',
 'LDLRAP1',
 'TUBA8',
 'SOST',
 'PRX',
 'SPTLC2',
 'SPTLC1',
 'VAPB',
 'TRPM7',
 'FBXO7',
 'SLC26A4',
 'SLC35A1',
 'SLC6A20',
 'PNKP',
 'CLDN14',
 'FOXL2',
 'HSD17B3',
 'RTN4R',
 'RETN',
 'FGF20',
 'AIP',
 'CD244',
 'LMBR1',
 'LMBR1;ZRS',
 'ZRS;LMBR1',
 'LPIN2',
 'LPIN1',
 'CDH23',
 'PCDH15',
 'ELOVL4',
 'TMPRSS3',
 'CRTAP',
 'DNAI2',
 'ASPM',
 'ABCG8',
 'ABCG5;ABCG8',
 'ABCG5',
 'RPGRIP1',
 'ADIPOQ',
 'PRKCH',
 'TRPV4',
 'GJB4',
 'DHH',
 'ALX4',
 'MINPP1',
 'FGF23',
 'GAN',
 'AAAS',
 'DMPK',
 'ARFGEF2',
 'ARHGAP26',
 'ELAC2',
 'GAD1',
 'GHRL',
 'CFHR1;CFHR3',
 'CYP3A5',
 'FOXP2',
 'HDAC4',
 'CHST6',
 'OPA1',
 'CAPN10',
 'TSC1',
 'SERPINA10',
 'CARD14;SGSH',
 'SGSH',
 'SGSH;SLC26A11',
 'JPH3',
 'NDRG1',
 'AICDA',
 'MCOLN1',
 'USH1C',
 'ATP6V0A4',
 'HNMT',
 'WNK1',
 'DISC1',
 'HCN4',
 'ADCY10',
 'TOR1A',
 'MESP2',
 'CFC1',
 'ANKH',
 'ANKH;ANKH-DT',
 'WWOX',
 'SPINT2',
 'AASS',
 'MASP2',
 'TAB2',
 'TREM2',
 'FRZB',
 'CNGB3',
 'TARDBP',
 'TRIM37',
 'VSX1',
 'CYLD',
 'STX11',
 'SPINK5',
 'NHERF1',
 'SPTBN2',
 'POLG2',
 'HPS1',
 'HPS1;MIR4685',
 'PRKAG3',
 'FCN3',
 'PDE11A',
 'SLC26A5',
 'TBCE',
 'MUTYH',
 'CTDP1',
 'TNFRSF13B',
 'MKKS',
 'TBX21',
 'NEUROG3',
 'SLC12A6',
 'TAS2R16',
 'LRAT',
 'CD207',
 'EVC',
 'KL',
 'ABHD5',
 'ACAD8',
 'NPHS2',
 'SYCP3',
 'AKR1D1',
 'TSFM',
 'TFR2',
 'TSPYL1',
 'RRM2B',
 'LTBP4',
 'MERTK',
 'AKAP10',
 'PTGDR',
 'HOXA2',
 'CD209',
 'SLC40A1',
 'MAPK8IP1',
 'ACTN4',
 'EFEMP2',
 'NR0B2',
 'MMP20',
 'HSPB3',
 'LGI1',
 'TBX19',
 'WRN',
 'BLM',
 'KALRN',
 'TCIRG1',
 'FCGR2B',
 'PDGFRL',
 'AFG3L2',
 'FBLN5',
 'FZD4',
 'CNTNAP2',
 'ALG6',
 'ICOS',
 'ADAMTS2',
 'IDH3B',
 'BLNK',
 'TRIP11',
 'SACS',
 'AMACR',
 'TCAP',
 'NR2E3',
 'IRAK3',
 'SP110',
 'KCNE3;LIPT2',
 'KCNE3',
 'GJB6',
 'covers 17 genes, none of which curated to show dosage sensitivity',
 'GPC6',
 'ST3GAL5',
 'MLH3',
 'AREL1;MLH3',
 'AIPL1',
 'TRPS1',
 'ATP2C1',
 'CHEK2',
 'DNAI1',
 'PROM1',
 'B4GALT7',
 'PPP2R2B',
 'SLC17A5',
 'TINF2',
 'GALK1',
 'CST3',
 'GRHPR',
 'RAD54B',
 'AGXT',
 'PRG4',
 'SPAST',
 'SCO2',
 'LRP4',
 'STAT5B',
 'DLC1',
 'RNF6',
 'CD2AP',
 'CRLF1',
 'SLC34A2',
 'KRIT1',
 'CRB1',
 'SLC27A4',
 'SLC22A4',
 'RPL11',
 'KISS1R',
 'SLC6A5',
 'SGCE',
 'SLC7A9',
 'TYROBP',
 'ADAMTS13',
 'TBX15',
 'RBBP8',
 'KCNQ1OT1',
 'ADGRG1',
 'MYOT',
 'GRM6',
 'EDAR',
 'PPP1R17',
 'RGS9',
 'SEPTIN9',
 'MPDU1',
 'RAD50',
 'EIF2AK3',
 'AXIN2',
 'UNC119',
 'AKAP9',
 'POLH',
 'SCN4A',
 'CLDN16',
 'KCNMB1',
 'EIF2B5',
 'GYG1',
 'SLC19A2',
 'RP1',
 'GPHN',
 'HABP2',
 'SUCLA2',
 'ITM2B',
 'BAG3',
 'RAB27A',
 'SLC25A15',
 'SLC25A13',
 'PHOX2B',
 'DNM1L',
 'NDUFS6',
 'NDUFS3',
 'GNE',
 'AXIN1',
 'TGM5',
 'CHST3',
 'KCNE2',
 'LITAF',
 'RECQL4',
 'SNCAIP',
 'KLK4',
 'APOL1',
 'ALOX12B',
 'ELP1',
 'CLDN1',
 'GCM2',
 'SIX3',
 'CYP7B1',
 'MOCS2',
 ...]

In [ ]:
#xx = Clin1["GeneSymbol"] == "ATXN8;ATXN8OS;LOC109461478"
xx= Clin1[(Clin1["GeneSymbol"] == "ATXN8;ATXN8OS;LOC109461478" )]
xx

,Type,Name,GeneSymbol,ClinicalSignificance,Assembly
370,Microsatellite,NR_002717.2(ATXN8OS):n.1103CTG[15_40],ATXN8;ATXN8OS;LOC109461478,Benign,GRCh37
371,Microsatellite,NR_002717.2(ATXN8OS):n.1103CTG[15_40],ATXN8;ATXN8OS;LOC109461478,Benign,GRCh38

In [2]:
lociii = ['AP5Z1',
 'ZNF592',
 'FOXRED1',
 'NUBPL',
 'HFE',
 'WDR35',
 'ABHD12',
 'ZNF513',
 'HOGA1',
 'FAM161A',
 'WDR62',
 'WDPCP',
 'TBC1D24',
 'XPNPEP3',
 'MTRFR',
 'CEP152',
 'SDCCAG8',
 'OPN1SW',
 'UROD',
 'LIPA',
 'HPSE2',
 'ASAH1',
 'TCN2',
 'PCARE',
 'MIR2861',
 'TMEM127',
 'VIPAS39',
 'POMP',
 'CBS',
 'TPRN',
 'SLC52A3',
 'OAT',
 'DPYS',
 'SH3PXD2B',
 'ATXN8;ATXN8OS;LOC109461478',
 'GRXCR1',
 'TMEM216',
 'USB1',
 'KCNJ18',
 'PEPD',
 'AGA',
 'CYB5A',
 'WDR72',
 'CYB5R3',
 'XPC',
 'DNAAF1',
 'RBM20',
 'KLHDC8B',
 'SERPINF2',
 'CANT1',
 'VWF',
 'TSPAN12',
 'NEXN',
 'RETREG1',
 'NF1',
 'CTSA',
 'GM2A',
 'LOXHD1',
 'INPP5E',
 'SDHAF2',
 'TAT',
 'UROC1',
 'HTT',
 'TMEM126A',
 'TACO1',
 'RNASET2',
 'PGAM2',
 'NDUFAF3',
 'TUBB1',
 'TUBB2B',
 'SDHAF1',
 'COQ9',
 'DPYD',
 'BCAM',
 'DUOXA2',
 'CCBE1',
 'CPOX',
 'ALDOB',
 'PTS',
 'RNF168',
 'QDPR',
 'RFX6',
 'RSPH4A',
 'ANK1',
 'LMBRD1',
 'FBN2',
 'DNAAF2',
 'DCAF17',
 'EYS',
 'TMEM70',
 'LRTOMT',
 'NDUFAF6',
 'FECH',
 'SLC29A3',
 'NDUFAF5',
 'KNG1',
 'PAH',
 'CILK1',
 'FASTKD2',
 'F5',
 'PROC',
 'FUCA1',
 'ADAMTSL2',
 'GALNS',
 'ZFP57',
 'NAT2',
 'TPCN2',
 'UQCRQ',
 'ZNF469',
 'RBM28',
 'BEAN1',
 'TMEM43',
 'RNF212',
 'IYD',
 'CC2D2A',
 'ZFYVE26',
 'GIGYF2',
 'TRAPPC9',
 'MMADHC',
 'SACK1H',
 'ISCU',
 'SLC16A12',
 'RFT1',
 'GPD1L',
 'NDUFAF4',
 'NKX2-6',
 'LMF1',
 'APC',
 'KCTD7',
 'ATP6V0A2',
 'TTBK2',
 'SART3',
 'SLC46A1',
 'UBIAD1',
 'MIR96',
 'FBP1',
 'UPK3A',
 'NCR3',
 'ARSB',
 'FOXD3',
 'EMG1',
 'RARS2',
 'CISD2',
 'GUSB',
 'CYP4F22',
 'CA2',
 'MBD5',
 'PLEKHM1',
 'GLB1',
 'DOCK8',
 'OCA2',
 'LCA5',
 'DIP2B',
 'FANCI',
 'FANCI;POLG',
 'RNF135',
 'ARMS2',
 'NHEJ1',
 'CDKAL1',
 'IFT80',
 'XPA',
 'ATXN10',
 'SLC30A8',
 'MFSD8',
 'KLHL7',
 'FGD4',
 'ACAD9',
 'PLEKHG5',
 'MTMR14',
 'MIAT',
 'FAM20C',
 'SETBP1',
 'CCDC50',
 'G6PC3',
 'FA2H',
 'OBSL1',
 'INF2',
 'FTO',
 'YARS2',
 'DARS2',
 'RPGRIP1L',
 'PSAT1',
 'NOBOX',
 'ZFAT',
 'CHMP4B',
 'FLVCR2',
 'AGL',
 'SPG11',
 'SLC25A38',
 'SLC35D1',
 'ATG16L1',
 'DOLK',
 'STRA6',
 'DDX25;HYLS1;PUS3',
 'HIBCH',
 'BBS12',
 'PFKM',
 'WASHC5',
 'F12',
 'CYP11B1',
 'PRCD',
 'ARHGAP9',
 'RSPO4',
 'MARVELD2',
 'PDSS2',
 'MAT1A',
 'GNAS;GNAS-AS1',
 'WWC1',
 'HYCC1',
 'ATP13A2',
 'SEC23B',
 'SEC23A',
 'SAMD9',
 'HGSNAT',
 'LAMTOR2',
 'RAX2',
 'PALB2',
 'P3H1',
 'RNASEH2C',
 'RNASEH2B',
 'B3GLCT',
 'BANK1',
 'GALNT12',
 'DOK7',
 'ORAI1',
 'PIGV',
 'PIGM',
 'ZFYVE27',
 'TRMU',
 'ZNF750',
 'RIN2',
 'PJVK',
 'SLC4A11',
 'MED25',
 'GLIS3',
 'CCDC28B',
 'CCT5',
 'BBS10',
 'CEP290',
 'VANGL1',
 'ADAMTSL4',
 'SIAE',
 'CC2D1A',
 'ALDH5A1',
 'CLDN19',
 'EHBP1',
 'TMEM67',
 'MKS1',
 'SPATA7',
 'TMPRSS6',
 'SPATA16',
 'SI',
 'SLC24A4',
 'MMACHC',
 'SLC34A3',
 'COQ2',
 'HMBS',
 'SLC24A5',
 'NEK8',
 'BLOC1S3',
 'TRIOBP',
 'ACOX1',
 'PKLR',
 'LPL',
 'NAGLU',
 'HPD',
 'SLITRK1',
 'WDR36',
 'NLRP7',
 'NDUFAF2',
 'NLRP12',
 'FANCM',
 'NECTIN4',
 'RSPO1',
 'GLRX5',
 'L2HGDH',
 'CUL7',
 'ACADL',
 'ACADVL',
 'PLEKHG4',
 'ALDH3A2',
 'THAP1',
 'CHMP2B',
 'TOPORS',
 'CYP27B1',
 'MANBA',
 'MAN2B1',
 'HAL',
 'NDUFA13',
 'LHFPL5',
 'PIKFYVE',
 'ERCC6',
 'ERCC8',
 'ERCC8;NDUFAF2',
 'STOX1',
 'FIG4',
 'NIPAL4',
 'KIFBP',
 'ESCO2',
 'CBLIF',
 'DBH',
 'MSH2',
 'SLC25A22',
 'CYP17A1',
 'SPRED1',
 'CPAP',
 'RAB3GAP2',
 'CRBN',
 'LIPI',
 'GPSM2',
 'LPAR6',
 'IQCB1',
 'MRPS16',
 'MRAP',
 'MPLKIP',
 'SUGCT',
 'D2HGDH',
 'REEP1',
 'PDCD10',
 'POU6F2',
 'PNPLA2',
 'MMUT',
 'KRT75',
 'PNKD',
 'BTD',
 'HLCS',
 'ERMAP',
 'MCCC2',
 'MCCC1',
 'LRRK2',
 'ADAMTS10',
 'DNAJC19',
 'CABP4',
 'ADA',
 'ADA;PKIG',
 'FREM2',
 'FREM1',
 'ARL13B',
 'PITPNM3',
 'ATPAF2',
 'UNC13D',
 'SGCG',
 'AHI1',
 'SLC6A19',
 'CHD7',
 'PPARGC1B',
 'ARL6',
 'RDH12',
 'SUMO4;TAB2',
 'EFHC1',
 'GJC2',
 'GCDH',
 'GCDH;KLF1;LOC117125594',
 'GSDME',
 'PC',
 'GTF2H5',
 'ANKK1',
 'MED13L',
 'DLAT',
 'PDHX',
 'LLGL2;TSEN54',
 'TSEN54',
 'TSEN34',
 'TSEN2',
 'C1QTNF5',
 'ALG3',
 'SLC39A13',
 'CYP2R1',
 'DNAAF4',
 'FIGLA',
 'NIPBL',
 'PEX26',
 'ANO5',
 'SEC63',
 'CASP12',
 'ROBO3',
 'STRADA',
 'CYP4V2',
 'NPSR1',
 'RP1L1',
 'GRHL2',
 'MYH14',
 'VPS33B',
 'HMCN1',
 'VKORC1',
 'VHL',
 'NCF2',
 'NCF1',
 'CYBA',
 'MFN2',
 'PRICKLE1',
 'SETX',
 'PYGM',
 'ETHE1',
 'SYNE2',
 'SYNE1',
 'CHST14',
 'MCEE',
 'PLCE1',
 'USH2A',
 'SLC9A9',
 'CERKL',
 'HJV',
 '-',
 'BCKDHA',
 'SLC36A2',
 'ARG1',
 'ASL',
 'PINK1',
 'CPS1',
 'NAGS',
 'IGF2BP2',
 'KIF21A',
 'NEU1',
 'SCN4B',
 'KRT74',
 'ADSL',
 'MASTL',
 'SCN3B',
 'EXT2',
 'SH3TC2',
 'UNC93B1',
 'CDK5RAP2',
 'SPG21',
 'EXT1',
 'CACNA2D4',
 'SEMA3E',
 'SOX9',
 'SATB2',
 'NIPA1',
 'NSMF',
 'ARHGEF10',
 'ASPN;CENPP',
 'TTC8',
 'XYLT2',
 'XYLT1',
 'FANCL',
 'PUS1',
 'MEFV',
 'ALG8',
 'CLN5',
 'PALLD',
 'APOC4-APOC2;APOC2',
 'APOC2',
 'NHLRC1',
 'ETFA',
 'ANTXR2',
 'ASPA',
 'HSPB8',
 'NPC1L1',
 'SIL1',
 'NPHP3',
 'TPP1',
 'GORAB',
 'COX4I2',
 'BBS9',
 'SUMF1',
 'SUMF2',
 'CCM2',
 'WHRN',
 'A4GALT',
 'ALG2',
 'CACNA1H',
 'FERMT3',
 'FERMT1',
 'DSG4',
 'BEST1',
 'LEMD3',
 'GNPTAB',
 'GBE1',
 'GNPTG',
 'CLN8',
 'FRAS1',
 'ZNF365',
 'VPS13B',
 'RGS9BP',
 'ACAT1',
 'CNNM4',
 'ABCA12',
 'MCFD2',
 'PCSK9',
 'HSD3B7',
 'KIRREL3',
 'ITGA2B',
 'TAS2R38',
 'TJP2',
 'KANK1',
 'SBF2',
 'USH1G',
 'SECISBP2',
 'SAR1B',
 'CLCF1',
 'GNS',
 'CTH',
 'OSTM1',
 'FSCN2',
 'RAI1',
 'ATXN7',
 'XDH',
 'NPC1',
 'APBB1;SMPD1',
 'SMPD1',
 'KRT9',
 'KCNV2',
 'BBS7',
 'ATM',
 'ARSA',
 'MMAB',
 'EPM2A',
 'IL23R',
 'SLC17A8',
 'LRPPRC',
 'KCNQ1',
 'HPS6',
 'HPS5',
 'ADAMTS17',
 'MMAA',
 'APCDD1',
 'TPH2',
 'HGD',
 'CDAN1',
 'DYM',
 'UTP4',
 'SBDS',
 'FKTN',
 'POMT2',
 'PDSS1',
 'POMT1',
 'NME8',
 'MC2R',
 'CDC73',
 'NF2',
 'LIPH',
 'AIRE',
 'SALL4',
 'GABBR2',
 'RP9',
 'SRD5A2',
 'PRPF3',
 'PRPF8',
 'SEMA4A',
 'FLCN',
 'EVC2',
 'TMIE',
 'IRF5',
 'NPHP4',
 'CARD9',
 'ALOXE3',
 'IRF6',
 'TDP1',
 'PTF1A',
 'CRELD1',
 'DTNBP1',
 'ALG12',
 'FANCA',
 'PROKR2',
 'MCPH1',
 'SPART',
 'PAX6',
 'WT1',
 'NPHP1',
 'SLC22A12',
 'MTHFR',
 'HYAL1',
 'FKBP10',
 'SLC39A4',
 'IMPG2',
 'ATXN3',
 'CLN3',
 'ABCC11',
 'OTOA',
 'IVD',
 'SUFU',
 'TRPM6',
 'ACADM',
 'PROK2',
 'EHMT1',
 'GALT',
 'MPO',
 'LPO;MPO',
 'COQ8A',
 'COG8',
 'COG7',
 'COG4',
 'COG1',
 'LCAT',
 'GALE',
 'LDLR',
 'LDLR;MIR6886',
 'ALG9',
 'UROS',
 'TRPM4',
 'TYR',
 'LYST',
 'GALC',
 'SUOX',
 'ACADS',
 'IRAK4',
 'ATP7B',
 'PHGDH',
 'HEXB',
 'HEXA',
 'SERPING1',
 'GCLC',
 'TCOF1',
 'ALMS1',
 'RB1CC1',
 'FXN',
 'POMGNT1',
 'COG5',
 'ALDH4A1',
 'PRODH',
 'MYO3A',
 'FTCD',
 'GAA',
 'ST14',
 'TPO',
 'MLYCD',
 'DUOX2',
 'SAMHD1',
 'TLL1',
 'CLN6',
 'SLC26A2',
 'PRSS12',
 'TMC1',
 'PKHD1',
 'EIF2B4',
 'EIF2B1',
 'HPS4',
 'NSD1',
 'UPB1',
 'GP1BA',
 'RXFP2',
 'GFM1',
 'NLRP1',
 'TMPRSS15',
 'RIMS1',
 'GNMT',
 'SMARCAL1',
 'TREX1',
 'EDARADD',
 'GDAP1',
 'PAX3',
 'FKRP',
 'ENAM',
 'OPA3',
 'MYLK2',
 'LZTS1',
 'MYO5B',
 'SCGB3A2',
 'CYP27A1',
 'MLPH',
 'SLC25A19',
 'HAVCR1',
 'ZMPSTE24',
 'ITPKC',
 'NOP10',
 'NHP2',
 'HAMP',
 'GBA1',
 'EIF2B2',
 'HTRA2;LOXL3',
 'HTRA2',
 'STRC',
 'ATL1',
 'EGLN1',
 'PRPF31',
 'DHCR24',
 'NLRP3',
 'BSND',
 'ANTXR1',
 'ITCH',
 'CLRN1',
 'CLRN1-AS1;CLRN1',
 'CATSPER1',
 'APOA5',
 'ALS2',
 'ESPN',
 'APTX',
 'PSTPIP1',
 'SIX6',
 'EIF2B3',
 'CTNS',
 'TNFRSF13C',
 'WNT10A',
 'CLEC7A',
 'TIRAP',
 'DICER1',
 'MFRP',
 'NT5C3A',
 'SELENON',
 'SLC45A2',
 'WFS1',
 'BHLHE41',
 'BSCL2',
 'BSCL2;HNRNPUL2-BSCL2',
 'PANK2',
 'MIR103A2;MIR103B2;PANK2',
 'SLC19A3',
 'BBS2',
 'SLC2A10',
 'RAB23',
 'SLC2A9',
 'SLURP1',
 'HPS3',
 'PIP5K1C',
 'TWNK',
 'SMC3',
 'TBX20',
 'IFT122',
 'CD96',
 'RNASEH2A',
 'ALX3',
 'BTNL2',
 'HAX1',
 'KIF1B',
 'PDP1',
 'DCLRE1C',
 'UBR1',
 'VPS13A',
 'NOD2',
 'DPM3',
 'PCNT',
 'STIM1',
 'ANGPTL4',
 'MLC1',
 'ALG1',
 'LDB3',
 'BRIP1',
 'SLC35C1',
 'KCNK9',
 'DMGDH',
 'HERC2',
 'TMC8',
 'TMC6',
 'NUP62',
 'MRPS22',
 'ZEB2',
 'AMN',
 'BCO1',
 'LDLRAP1',
 'TUBA8',
 'SOST',
 'PRX',
 'SPTLC2',
 'SPTLC1',
 'VAPB',
 'TRPM7',
 'FBXO7',
 'SLC26A4',
 'SLC35A1',
 'SLC6A20',
 'PNKP',
 'CLDN14',
 'FOXL2',
 'HSD17B3',
 'RTN4R',
 'RETN',
 'FGF20',
 'AIP',
 'CD244',
 'LMBR1',
 'LMBR1;ZRS',
 'ZRS;LMBR1',
 'LPIN2',
 'LPIN1',
 'CDH23',
 'PCDH15',
 'ELOVL4',
 'TMPRSS3',
 'CRTAP',
 'DNAI2',
 'ASPM',
 'ABCG8',
 'ABCG5;ABCG8',
 'ABCG5',
 'RPGRIP1',
 'ADIPOQ',
 'PRKCH',
 'TRPV4',
 'GJB4',
 'DHH',
 'ALX4',
 'MINPP1',
 'FGF23',
 'GAN',
 'AAAS',
 'DMPK',
 'ARFGEF2',
 'ARHGAP26',
 'ELAC2',
 'GAD1',
 'GHRL',
 'CFHR1;CFHR3',
 'CYP3A5',
 'FOXP2',
 'HDAC4',
 'CHST6',
 'OPA1',
 'CAPN10',
 'TSC1',
 'SERPINA10',
 'CARD14;SGSH',
 'SGSH',
 'SGSH;SLC26A11',
 'JPH3',
 'NDRG1',
 'AICDA',
 'MCOLN1',
 'USH1C',
 'ATP6V0A4',
 'HNMT',
 'WNK1',
 'DISC1',
 'HCN4',
 'ADCY10',
 'TOR1A',
 'MESP2',
 'CFC1',
 'ANKH',
 'ANKH;ANKH-DT',
 'WWOX',
 'SPINT2',
 'AASS',
 'MASP2',
 'TAB2',
 'TREM2',
 'FRZB',
 'CNGB3',
 'TARDBP',
 'TRIM37',
 'VSX1',
 'CYLD',
 'STX11',
 'SPINK5',
 'NHERF1',
 'SPTBN2',
 'POLG2',
 'HPS1',
 'HPS1;MIR4685',
 'PRKAG3',
 'FCN3',
 'PDE11A',
 'SLC26A5',
 'TBCE',
 'MUTYH',
 'CTDP1',
 'TNFRSF13B',
 'MKKS',
 'TBX21',
 'NEUROG3',
 'SLC12A6',
 'TAS2R16',
 'LRAT',
 'CD207',
 'EVC',
 'KL',
 'ABHD5',
 'ACAD8',
 'NPHS2',
 'SYCP3',
 'AKR1D1',
 'TSFM',
 'TFR2',
 'TSPYL1',
 'RRM2B',
 'LTBP4',
 'MERTK',
 'AKAP10',
 'PTGDR',
 'HOXA2',
 'CD209',
 'SLC40A1',
 'MAPK8IP1',
 'ACTN4',
 'EFEMP2',
 'NR0B2',
 'MMP20',
 'HSPB3',
 'LGI1',
 'TBX19',
 'WRN',
 'BLM',
 'KALRN',
 'TCIRG1',
 'FCGR2B',
 'PDGFRL',
 'AFG3L2',
 'FBLN5',
 'FZD4',
 'CNTNAP2',
 'ALG6',
 'ICOS',
 'ADAMTS2',
 'IDH3B',
 'BLNK',
 'TRIP11',
 'SACS',
 'AMACR',
 'TCAP',
 'NR2E3',
 'IRAK3',
 'SP110',
 'KCNE3;LIPT2',
 'KCNE3',
 'GJB6',
 'GPC6',
 'ST3GAL5',
 'MLH3',
 'AREL1;MLH3',
 'AIPL1',
 'TRPS1',
 'ATP2C1',
 'CHEK2',
 'DNAI1',
 'PROM1',
 'B4GALT7',
 'PPP2R2B',
 'SLC17A5',
 'TINF2',
 'GALK1',
 'CST3',
 'GRHPR',
 'RAD54B',
 'AGXT',
 'PRG4',
 'SPAST',
 'SCO2',
 'LRP4',
 'STAT5B',
 'DLC1',
 'RNF6',
 'CD2AP',
 'CRLF1',
 'SLC34A2',
 'KRIT1',
 'CRB1',
 'SLC27A4',
 'SLC22A4',
 'RPL11',
 'KISS1R',
 'SLC6A5',
 'SGCE',
 'SLC7A9',
 'TYROBP',
 'ADAMTS13',
 'TBX15',
 'RBBP8',
 'KCNQ1OT1',
 'ADGRG1',
 'MYOT',
 'GRM6',
 'EDAR',
 'PPP1R17',
 'RGS9',
 'SEPTIN9',
 'MPDU1',
 'RAD50',
 'EIF2AK3',
 'AXIN2',
 'UNC119',
 'AKAP9',
 'POLH',
 'SCN4A',
 'CLDN16',
 'KCNMB1',
 'EIF2B5',
 'GYG1',
 'SLC19A2',
 'RP1',
 'GPHN',
 'HABP2',
 'SUCLA2',
 'ITM2B',
 'BAG3',
 'RAB27A',
 'SLC25A15',
 'SLC25A13',
 'PHOX2B',
 'DNM1L',
 'NDUFS6',
 'NDUFS3',
 'GNE',
 'AXIN1',
 'TGM5',
 'CHST3',
 'KCNE2',
 'LITAF',
 'RECQL4',
 'SNCAIP',
 'KLK4',
 'APOL1',
 'ALOX12B',
 'ELP1',
 'CLDN1',
 'GCM2',
 'SIX3',
 'CYP7B1',
 'MOCS2'
 ]

In [ ]:
Clin1.head(20)

,Type,Name,GeneID,GeneSymbol,ClinicalSignificance,Assembly,VariationID
0,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,Pathogenic/Likely pathogenic,GRCh37,2
1,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,Pathogenic/Likely pathogenic,GRCh38,2
2,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,Pathogenic,GRCh37,3
3,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,Pathogenic,GRCh38,3
4,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,Uncertain significance,GRCh37,4
5,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,Uncertain significance,GRCh38,4
6,single nucleotide variant,NM_017547.4(FOXRED1):c.694C>T (p.Gln232Ter),55572,FOXRED1,Pathogenic,GRCh37,5
7,single nucleotide variant,NM_017547.4(FOXRED1):c.694C>T (p.Gln232Ter),55572,FOXRED1,Pathogenic,GRCh38,5
8,single nucleotide variant,NM_017547.4(FOXRED1):c.1289A>G (p.Asn430Ser),55572,FOXRED1,Likely pathogenic,GRCh37,6
9,single nucleotide variant,NM_017547.4(FOXRED1):c.1289A>G (p.Asn430Ser),55572,FOXRED1,Likely pathogenic,GRCh38,6
10,single nucleotide variant,NM_025152.3(NUBPL):c.166G>A (p.Gly56Arg),80224,NUBPL,Conflicting classifications of pathogenicity,GRCh37,214885
11,single nucleotide variant,NM_025152.3(NUBPL):c.166G>A (p.Gly56Arg),80224,NUBPL,Conflicting classifications of pathogenicity,GRCh38,214885
12,single nucleotide variant,NM_000410.4(HFE):c.845G>A (p.Cys282Tyr),3077,HFE,"Pathogenic/Pathogenic, low penetrance; risk fa...",GRCh37,9
13,single nucleotide variant,NM_000410.4(HFE):c.845G>A (p.Cys282Tyr),3077,HFE,"Pathogenic/Pathogenic, low penetrance; risk fa...",GRCh38,9
14,single nucleotide variant,NM_000410.4(HFE):c.187C>G (p.His63Asp),3077,HFE,Conflicting classifications of pathogenicity; ...,GRCh37,10
15,single nucleotide variant,NM_000410.4(HFE):c.187C>G (p.His63Asp),3077,HFE,Conflicting classifications of pathogenicity; ...,GRCh38,10
16,single nucleotide variant,NM_000410.4(HFE):c.193A>T (p.Ser65Cys),3077,HFE,Conflicting classifications of pathogenicity,GRCh37,11
17,single nucleotide variant,NM_000410.4(HFE):c.193A>T (p.Ser65Cys),3077,HFE,Conflicting classifications of pathogenicity,GRCh38,11
18,single nucleotide variant,NM_000410.4(HFE):c.314T>C (p.Ile105Thr),3077,HFE,Uncertain significance,GRCh37,12
19,single nucleotide variant,NM_000410.4(HFE):c.314T>C (p.Ile105Thr),3077,HFE,Uncertain significance,GRCh38,12

In [ ]:
terms = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, low penetrance"]

for gene in lociii:
    filtered = Clin1[
        (Clin1["GeneSymbol"] == gene )&
        (Clin1["ClinicalSignificance"].isin (terms)) &
        (Clin1["Type"] == "single nucleotide variant") &
        (Clin1["Assembly"] == "GRCh38")
        ]
    filtered.to_csv(f"/Users/adesinamary/Documents/Variant_summary_genes/{gene}.csv", sep="\t", index= False)
    print(f"{gene}: {len(filtered)} variants written to clinvar/{gene}.csv")

AP5Z1: 32 variants written to clinvar/AP5Z1.csv
ZNF592: 0 variants written to clinvar/ZNF592.csv
FOXRED1: 44 variants written to clinvar/FOXRED1.csv
NUBPL: 13 variants written to clinvar/NUBPL.csv
HFE: 30 variants written to clinvar/HFE.csv
WDR35: 48 variants written to clinvar/WDR35.csv
ABHD12: 30 variants written to clinvar/ABHD12.csv
ZNF513: 0 variants written to clinvar/ZNF513.csv
HOGA1: 97 variants written to clinvar/HOGA1.csv
FAM161A: 77 variants written to clinvar/FAM161A.csv
WDR62: 64 variants written to clinvar/WDR62.csv
WDPCP: 28 variants written to clinvar/WDPCP.csv
TBC1D24: 73 variants written to clinvar/TBC1D24.csv
XPNPEP3: 13 variants written to clinvar/XPNPEP3.csv
MTRFR: 7 variants written to clinvar/MTRFR.csv
CEP152: 76 variants written to clinvar/CEP152.csv
SDCCAG8: 53 variants written to clinvar/SDCCAG8.csv
OPN1SW: 0 variants written to clinvar/OPN1SW.csv
UROD: 37 variants written to clinvar/UROD.csv
LIPA: 102 variants written to clinvar/LIPA.csv
HPSE2: 12 variants written to clinvar/HPSE2.csv
ASAH1: 90 variants written to clinvar/ASAH1.csv
TCN2: 29 variants written to clinvar/TCN2.csv
PCARE: 53 variants written to clinvar/PCARE.csv
MIR2861: 0 variants written to clinvar/MIR2861.csv
TMEM127: 44 variants written to clinvar/TMEM127.csv
VIPAS39: 23 variants written to clinvar/VIPAS39.csv
POMP: 0 variants written to clinvar/POMP.csv
CBS: 197 variants written to clinvar/CBS.csv
TPRN: 6 variants written to clinvar/TPRN.csv
SLC52A3: 21 variants written to clinvar/SLC52A3.csv
OAT: 91 variants written to clinvar/OAT.csv
DPYS: 23 variants written to clinvar/DPYS.csv
SH3PXD2B: 10 variants written to clinvar/SH3PXD2B.csv
ATXN8;ATXN8OS;LOC109461478: 0 variants written to clinvar/ATXN8;ATXN8OS;LOC109461478.csv
GRXCR1: 13 variants written to clinvar/GRXCR1.csv
TMEM216: 28 variants written to clinvar/TMEM216.csv
USB1: 14 variants written to clinvar/USB1.csv
KCNJ18: 0 variants written to clinvar/KCNJ18.csv
PEPD: 55 variants written to clinvar/PEPD.csv
AGA: 68 variants written to clinvar/AGA.csv
CYB5A: 3 variants written to clinvar/CYB5A.csv
WDR72: 25 variants written to clinvar/WDR72.csv
CYB5R3: 30 variants written to clinvar/CYB5R3.csv
XPC: 108 variants written to clinvar/XPC.csv
DNAAF1: 31 variants written to clinvar/DNAAF1.csv
RBM20: 52 variants written to clinvar/RBM20.csv
KLHDC8B: 0 variants written to clinvar/KLHDC8B.csv
SERPINF2: 2 variants written to clinvar/SERPINF2.csv
CANT1: 29 variants written to clinvar/CANT1.csv
VWF: 310 variants written to clinvar/VWF.csv
TSPAN12: 25 variants written to clinvar/TSPAN12.csv
NEXN: 11 variants written to clinvar/NEXN.csv
RETREG1: 15 variants written to clinvar/RETREG1.csv
NF1: 1881 variants written to clinvar/NF1.csv
CTSA: 46 variants written to clinvar/CTSA.csv
GM2A: 10 variants written to clinvar/GM2A.csv
LOXHD1: 253 variants written to clinvar/LOXHD1.csv
INPP5E: 45 variants written to clinvar/INPP5E.csv
SDHAF2: 23 variants written to clinvar/SDHAF2.csv
TAT: 40 variants written to clinvar/TAT.csv
UROC1: 3 variants written to clinvar/UROC1.csv
HTT: 5 variants written to clinvar/HTT.csv
TMEM126A: 4 variants written to clinvar/TMEM126A.csv
TACO1: 8 variants written to clinvar/TACO1.csv
RNASET2: 7 variants written to clinvar/RNASET2.csv
PGAM2: 7 variants written to clinvar/PGAM2.csv
NDUFAF3: 7 variants written to clinvar/NDUFAF3.csv
TUBB1: 12 variants written to clinvar/TUBB1.csv
TUBB2B: 72 variants written to clinvar/TUBB2B.csv
SDHAF1: 8 variants written to clinvar/SDHAF1.csv
COQ9: 17 variants written to clinvar/COQ9.csv
DPYD: 82 variants written to clinvar/DPYD.csv
BCAM: 3 variants written to clinvar/BCAM.csv
DUOXA2: 17 variants written to clinvar/DUOXA2.csv
CCBE1: 13 variants written to clinvar/CCBE1.csv
CPOX: 23 variants written to clinvar/CPOX.csv
ALDOB: 84 variants written to clinvar/ALDOB.csv
PTS: 82 variants written to clinvar/PTS.csv
RNF168: 10 variants written to clinvar/RNF168.csv
QDPR: 48 variants written to clinvar/QDPR.csv
RFX6: 25 variants written to clinvar/RFX6.csv
RSPH4A: 33 variants written to clinvar/RSPH4A.csv
ANK1: 222 variants written to clinvar/ANK1.csv
LMBRD1: 30 variants written to clinvar/LMBRD1.csv
FBN2: 116 variants written to clinvar/FBN2.csv
DNAAF2: 23 variants written to clinvar/DNAAF2.csv
DCAF17: 29 variants written to clinvar/DCAF17.csv
EYS: 483 variants written to clinvar/EYS.csv
TMEM70: 14 variants written to clinvar/TMEM70.csv
LRTOMT: 17 variants written to clinvar/LRTOMT.csv
NDUFAF6: 20 variants written to clinvar/NDUFAF6.csv
FECH: 54 variants written to clinvar/FECH.csv
SLC29A3: 26 variants written to clinvar/SLC29A3.csv
NDUFAF5: 68 variants written to clinvar/NDUFAF5.csv
KNG1: 8 variants written to clinvar/KNG1.csv
PAH: 689 variants written to clinvar/PAH.csv
CILK1: 5 variants written to clinvar/CILK1.csv
FASTKD2: 18 variants written to clinvar/FASTKD2.csv
F5: 64 variants written to clinvar/F5.csv
PROC: 96 variants written to clinvar/PROC.csv
FUCA1: 55 variants written to clinvar/FUCA1.csv
ADAMTSL2: 20 variants written to clinvar/ADAMTSL2.csv
GALNS: 222 variants written to clinvar/GALNS.csv
ZFP57: 6 variants written to clinvar/ZFP57.csv
NAT2: 0 variants written to clinvar/NAT2.csv
TPCN2: 1 variants written to clinvar/TPCN2.csv
UQCRQ: 0 variants written to clinvar/UQCRQ.csv
ZNF469: 51 variants written to clinvar/ZNF469.csv
RBM28: 2 variants written to clinvar/RBM28.csv
BEAN1: 0 variants written to clinvar/BEAN1.csv
TMEM43: 2 variants written to clinvar/TMEM43.csv
RNF212: 0 variants written to clinvar/RNF212.csv
IYD: 5 variants written to clinvar/IYD.csv
CC2D2A: 194 variants written to clinvar/CC2D2A.csv
ZFYVE26: 211 variants written to clinvar/ZFYVE26.csv
GIGYF2: 0 variants written to clinvar/GIGYF2.csv
TRAPPC9: 45 variants written to clinvar/TRAPPC9.csv
MMADHC: 36 variants written to clinvar/MMADHC.csv
SACK1H: 16 variants written to clinvar/SACK1H.csv
ISCU: 2 variants written to clinvar/ISCU.csv
SLC16A12: 2 variants written to clinvar/SLC16A12.csv
RFT1: 14 variants written to clinvar/RFT1.csv
GPD1L: 0 variants written to clinvar/GPD1L.csv
NDUFAF4: 1 variants written to clinvar/NDUFAF4.csv
NKX2-6: 2 variants written to clinvar/NKX2-6.csv
LMF1: 17 variants written to clinvar/LMF1.csv
APC: 764 variants written to clinvar/APC.csv
KCTD7: 24 variants written to clinvar/KCTD7.csv
ATP6V0A2: 41 variants written to clinvar/ATP6V0A2.csv
TTBK2: 3 variants written to clinvar/TTBK2.csv
SART3: 8 variants written to clinvar/SART3.csv
SLC46A1: 10 variants written to clinvar/SLC46A1.csv
UBIAD1: 12 variants written to clinvar/UBIAD1.csv
MIR96: 2 variants written to clinvar/MIR96.csv
FBP1: 32 variants written to clinvar/FBP1.csv
UPK3A: 1 variants written to clinvar/UPK3A.csv
NCR3: 1 variants written to clinvar/NCR3.csv
ARSB: 166 variants written to clinvar/ARSB.csv
FOXD3: 0 variants written to clinvar/FOXD3.csv
EMG1: 1 variants written to clinvar/EMG1.csv
RARS2: 140 variants written to clinvar/RARS2.csv
CISD2: 3 variants written to clinvar/CISD2.csv
GUSB: 67 variants written to clinvar/GUSB.csv
CYP4F22: 41 variants written to clinvar/CYP4F22.csv
CA2: 16 variants written to clinvar/CA2.csv
MBD5: 53 variants written to clinvar/MBD5.csv
PLEKHM1: 3 variants written to clinvar/PLEKHM1.csv
GLB1: 229 variants written to clinvar/GLB1.csv
DOCK8: 61 variants written to clinvar/DOCK8.csv
OCA2: 199 variants written to clinvar/OCA2.csv
LCA5: 73 variants written to clinvar/LCA5.csv
DIP2B: 1 variants written to clinvar/DIP2B.csv
FANCI: 141 variants written to clinvar/FANCI.csv
FANCI;POLG: 1 variants written to clinvar/FANCI;POLG.csv
RNF135: 0 variants written to clinvar/RNF135.csv
ARMS2: 0 variants written to clinvar/ARMS2.csv
NHEJ1: 24 variants written to clinvar/NHEJ1.csv
CDKAL1: 0 variants written to clinvar/CDKAL1.csv
IFT80: 35 variants written to clinvar/IFT80.csv
XPA: 45 variants written to clinvar/XPA.csv
ATXN10: 0 variants written to clinvar/ATXN10.csv
SLC30A8: 0 variants written to clinvar/SLC30A8.csv
MFSD8: 95 variants written to clinvar/MFSD8.csv
KLHL7: 29 variants written to clinvar/KLHL7.csv
FGD4: 21 variants written to clinvar/FGD4.csv
ACAD9: 103 variants written to clinvar/ACAD9.csv
PLEKHG5: 42 variants written to clinvar/PLEKHG5.csv
MTMR14: 0 variants written to clinvar/MTMR14.csv
MIAT: 0 variants written to clinvar/MIAT.csv
FAM20C: 21 variants written to clinvar/FAM20C.csv
SETBP1: 61 variants written to clinvar/SETBP1.csv
CCDC50: 1 variants written to clinvar/CCDC50.csv
G6PC3: 33 variants written to clinvar/G6PC3.csv
FA2H: 41 variants written to clinvar/FA2H.csv
OBSL1: 31 variants written to clinvar/OBSL1.csv
INF2: 55 variants written to clinvar/INF2.csv
FTO: 3 variants written to clinvar/FTO.csv
YARS2: 18 variants written to clinvar/YARS2.csv
DARS2: 47 variants written to clinvar/DARS2.csv
RPGRIP1L: 178 variants written to clinvar/RPGRIP1L.csv
PSAT1: 21 variants written to clinvar/PSAT1.csv
NOBOX: 8 variants written to clinvar/NOBOX.csv
ZFAT: 0 variants written to clinvar/ZFAT.csv
CHMP4B: 3 variants written to clinvar/CHMP4B.csv
FLVCR2: 13 variants written to clinvar/FLVCR2.csv
AGL: 307 variants written to clinvar/AGL.csv
SPG11: 236 variants written to clinvar/SPG11.csv
SLC25A38: 37 variants written to clinvar/SLC25A38.csv
SLC35D1: 10 variants written to clinvar/SLC35D1.csv
ATG16L1: 0 variants written to clinvar/ATG16L1.csv
DOLK: 12 variants written to clinvar/DOLK.csv
STRA6: 17 variants written to clinvar/STRA6.csv
DDX25;HYLS1;PUS3: 1 variants written to clinvar/DDX25;HYLS1;PUS3.csv
HIBCH: 30 variants written to clinvar/HIBCH.csv
BBS12: 58 variants written to clinvar/BBS12.csv
PFKM: 70 variants written to clinvar/PFKM.csv
WASHC5: 30 variants written to clinvar/WASHC5.csv
F12: 15 variants written to clinvar/F12.csv
CYP11B1: 126 variants written to clinvar/CYP11B1.csv
PRCD: 8 variants written to clinvar/PRCD.csv
ARHGAP9: 0 variants written to clinvar/ARHGAP9.csv
RSPO4: 9 variants written to clinvar/RSPO4.csv
MARVELD2: 17 variants written to clinvar/MARVELD2.csv
PDSS2: 3 variants written to clinvar/PDSS2.csv
MAT1A: 33 variants written to clinvar/MAT1A.csv
GNAS;GNAS-AS1: 1 variants written to clinvar/GNAS;GNAS-AS1.csv
WWC1: 0 variants written to clinvar/WWC1.csv
HYCC1: 13 variants written to clinvar/HYCC1.csv
ATP13A2: 46 variants written to clinvar/ATP13A2.csv
SEC23B: 62 variants written to clinvar/SEC23B.csv
SEC23A: 3 variants written to clinvar/SEC23A.csv
SAMD9: 30 variants written to clinvar/SAMD9.csv
HGSNAT: 113 variants written to clinvar/HGSNAT.csv
LAMTOR2: 0 variants written to clinvar/LAMTOR2.csv
RAX2: 4 variants written to clinvar/RAX2.csv
PALB2: 391 variants written to clinvar/PALB2.csv
P3H1: 79 variants written to clinvar/P3H1.csv
RNASEH2C: 6 variants written to clinvar/RNASEH2C.csv
RNASEH2B: 37 variants written to clinvar/RNASEH2B.csv
B3GLCT: 15 variants written to clinvar/B3GLCT.csv
BANK1: 0 variants written to clinvar/BANK1.csv
GALNT12: 0 variants written to clinvar/GALNT12.csv
DOK7: 60 variants written to clinvar/DOK7.csv
ORAI1: 11 variants written to clinvar/ORAI1.csv
PIGV: 8 variants written to clinvar/PIGV.csv
PIGM: 1 variants written to clinvar/PIGM.csv
ZFYVE27: 0 variants written to clinvar/ZFYVE27.csv
TRMU: 80 variants written to clinvar/TRMU.csv
ZNF750: 0 variants written to clinvar/ZNF750.csv
RIN2: 6 variants written to clinvar/RIN2.csv
PJVK: 23 variants written to clinvar/PJVK.csv
SLC4A11: 97 variants written to clinvar/SLC4A11.csv
MED25: 5 variants written to clinvar/MED25.csv
GLIS3: 10 variants written to clinvar/GLIS3.csv
CCDC28B: 0 variants written to clinvar/CCDC28B.csv
CCT5: 1 variants written to clinvar/CCT5.csv
BBS10: 88 variants written to clinvar/BBS10.csv
CEP290: 463 variants written to clinvar/CEP290.csv
VANGL1: 1 variants written to clinvar/VANGL1.csv
ADAMTSL4: 68 variants written to clinvar/ADAMTSL4.csv
SIAE: 0 variants written to clinvar/SIAE.csv
CC2D1A: 35 variants written to clinvar/CC2D1A.csv
ALDH5A1: 89 variants written to clinvar/ALDH5A1.csv
CLDN19: 22 variants written to clinvar/CLDN19.csv
EHBP1: 0 variants written to clinvar/EHBP1.csv
TMEM67: 162 variants written to clinvar/TMEM67.csv
MKS1: 107 variants written to clinvar/MKS1.csv
SPATA7: 29 variants written to clinvar/SPATA7.csv
TMPRSS6: 22 variants written to clinvar/TMPRSS6.csv
SPATA16: 0 variants written to clinvar/SPATA16.csv
SI: 103 variants written to clinvar/SI.csv
SLC24A4: 5 variants written to clinvar/SLC24A4.csv
MMACHC: 88 variants written to clinvar/MMACHC.csv
SLC34A3: 58 variants written to clinvar/SLC34A3.csv
COQ2: 24 variants written to clinvar/COQ2.csv
HMBS: 108 variants written to clinvar/HMBS.csv
SLC24A5: 26 variants written to clinvar/SLC24A5.csv
NEK8: 23 variants written to clinvar/NEK8.csv
BLOC1S3: 1 variants written to clinvar/BLOC1S3.csv
TRIOBP: 51 variants written to clinvar/TRIOBP.csv
ACOX1: 45 variants written to clinvar/ACOX1.csv
PKLR: 94 variants written to clinvar/PKLR.csv
LPL: 115 variants written to clinvar/LPL.csv
NAGLU: 183 variants written to clinvar/NAGLU.csv
HPD: 20 variants written to clinvar/HPD.csv
SLITRK1: 1 variants written to clinvar/SLITRK1.csv
WDR36: 0 variants written to clinvar/WDR36.csv
NLRP7: 18 variants written to clinvar/NLRP7.csv
NDUFAF2: 6 variants written to clinvar/NDUFAF2.csv
NLRP12: 6 variants written to clinvar/NLRP12.csv
FANCM: 87 variants written to clinvar/FANCM.csv
NECTIN4: 10 variants written to clinvar/NECTIN4.csv
RSPO1: 3 variants written to clinvar/RSPO1.csv
GLRX5: 7 variants written to clinvar/GLRX5.csv
L2HGDH: 33 variants written to clinvar/L2HGDH.csv
CUL7: 68 variants written to clinvar/CUL7.csv
ACADL: 0 variants written to clinvar/ACADL.csv
ACADVL: 286 variants written to clinvar/ACADVL.csv
PLEKHG4: 0 variants written to clinvar/PLEKHG4.csv
ALDH3A2: 94 variants written to clinvar/ALDH3A2.csv
THAP1: 25 variants written to clinvar/THAP1.csv
CHMP2B: 6 variants written to clinvar/CHMP2B.csv
TOPORS: 5 variants written to clinvar/TOPORS.csv
CYP27B1: 57 variants written to clinvar/CYP27B1.csv
MANBA: 68 variants written to clinvar/MANBA.csv
MAN2B1: 187 variants written to clinvar/MAN2B1.csv
HAL: 0 variants written to clinvar/HAL.csv
NDUFA13: 4 variants written to clinvar/NDUFA13.csv
LHFPL5: 15 variants written to clinvar/LHFPL5.csv
PIKFYVE: 16 variants written to clinvar/PIKFYVE.csv
ERCC6: 178 variants written to clinvar/ERCC6.csv
ERCC8: 80 variants written to clinvar/ERCC8.csv
ERCC8;NDUFAF2: 3 variants written to clinvar/ERCC8;NDUFAF2.csv
STOX1: 0 variants written to clinvar/STOX1.csv
FIG4: 74 variants written to clinvar/FIG4.csv
NIPAL4: 29 variants written to clinvar/NIPAL4.csv
KIFBP: 7 variants written to clinvar/KIFBP.csv
ESCO2: 56 variants written to clinvar/ESCO2.csv
CBLIF: 8 variants written to clinvar/CBLIF.csv
DBH: 6 variants written to clinvar/DBH.csv
MSH2: 614 variants written to clinvar/MSH2.csv
SLC25A22: 15 variants written to clinvar/SLC25A22.csv
CYP17A1: 107 variants written to clinvar/CYP17A1.csv
SPRED1: 69 variants written to clinvar/SPRED1.csv
CPAP: 38 variants written to clinvar/CPAP.csv
RAB3GAP2: 27 variants written to clinvar/RAB3GAP2.csv
CRBN: 8 variants written to clinvar/CRBN.csv

KeyboardInterrupt:

In [ ]:
terms = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, low penetrance"]

for gene in lociii:
    filtered = Clin1[
        (Clin1["GeneSymbol"] == gene) &
        (Clin1["ClinicalSignificance"].isin(terms)) &
        (Clin1["Type"] == "single nucleotide variant") &
        (Clin1["Assembly"] == "GRCh38")
    ]

    print(gene, len(filtered))

- 16
A4GALT 1
AAAS 66
AASS 16
ABCA12 134
ABCC11 0
ABCG5 46
ABCG5;ABCG8 0
ABCG8 43
ABHD12 30
ABHD5 22
ACAD8 32
ACAD9 103
ACADL 0
ACADM 253
ACADS 59
ACADVL 286
ACAT1 119
ACOX1 45
ACTN4 15
ADA 106
ADA;PKIG 1
ADAMTS10 27
ADAMTS13 81
ADAMTS17 43
ADAMTS2 49
ADAMTSL2 20
ADAMTSL4 68
ADCY10 21
ADGRG1 74
ADIPOQ 1
ADSL 62
AFG3L2 55
AGA 68
AGL 307
AGXT 232
AHI1 134
AICDA 30
AIP 36
AIPL1 52
AIRE 120
AKAP10 0
AKAP9 3
AKR1D1 18
ALDH3A2 94
ALDH4A1 10
ALDH5A1 89
ALDOB 84
ALG1 86
ALG12 23
ALG2 6
ALG3 29
ALG6 77
ALG8 39
ALG9 25
ALMS1 435
ALOX12B 104
ALOXE3 46
ALS2 77
ALX3 8
ALX4 9
AMACR 2
AMN 32
ANGPTL4 0
ANK1 222
ANKH 9
ANKH;ANKH-DT 1
ANKK1 0
ANO5 127
ANTXR1 7
ANTXR2 21
AP5Z1 32
APBB1;SMPD1 1
APC 764
APCDD1 1
APOA5 8
APOC2 12
APOC4-APOC2;APOC2 0
APOL1 0
APTX 24
AREL1;MLH3 0
ARFGEF2 16
ARG1 67
ARHGAP26 0
ARHGAP9 0
ARHGEF10 0
ARL13B 21
ARL6 41
ARMS2 0
ARSA 263
ARSB 166
ASAH1 90
ASL 176
ASPA 112
ASPM 151
ASPN;CENPP 0
ATG16L1 0
ATL1 82
ATM 1343
ATP13A2 46
ATP2C1 33
ATP6V0A2 41
ATP6V0A4 53
ATP7B 424
ATPAF2 2
ATXN10 0
ATXN3 0
ATXN7 2
ATXN8;ATXN8OS;LOC109461478 0
AXIN1 2
AXIN2 67
B3GLCT 15
B4GALT7 11
BAG3 65
BANK1 0
BBS10 88
BBS12 58
BBS2 133
BBS7 70
BBS9 93
BCAM 3
BCKDHA 113
BCO1 0
BEAN1 0
BEST1 278
BHLHE41 0
BLM 221
BLNK 11
BLOC1S3 1
BRIP1 326
BSCL2 31
BSCL2;HNRNPUL2-BSCL2 1
BSND 26
BTD 161
BTNL2 0
C1QTNF5 6
CA2 16
CABP4 16
CACNA1H 8
CACNA2D4 3
CANT1 29
CAPN10 2
CARD14;SGSH 1
CARD9 14
CASP12 0
CATSPER1 1
CBLIF 8
CBS 197
CC2D1A 35
CC2D2A 194
CCBE1 13
CCDC28B 0
CCDC50 1
CCM2 50
CCT5 1
CD207 0
CD209 0
CD244 0
CD2AP 7
CD96 4
CDAN1 26
CDC73 72
CDH23 382
CDK5RAP2 47
CDKAL1 0
CEP152 76
CEP290 463
CERKL 104
CFC1 1
CFHR1;CFHR3 0
CHD7 426
CHEK2 295
CHMP2B 6
CHMP4B 3
CHST14 15
CHST3 36
CHST6 36
CILK1 5
CISD2 3
CLCF1 4
CLDN1 5
CLDN14 10
CLDN16 41
CLDN19 22
CLEC7A 0
CLN3 127
CLN5 67
CLN6 68
CLN8 58
CLRN1 54
CLRN1-AS1;CLRN1 1
CNGB3 147
CNNM4 28
CNTNAP2 55
COG1 9
COG4 24
COG5 42
COG7 21
COG8 9
COQ2 24
COQ8A 56
COQ9 17
COX4I2 0
CPAP 38
CPOX 23
CPS1 262
CRB1 357
CRBN 8
CRELD1 8
CRLF1 16
CRTAP 33
CST3 1
CTDP1 1
CTH 2
CTNS 113
CTSA 46
CUL7 68
CYB5A 3
CYB5R3 30
CYBA 44
CYLD 35
CYP11B1 126
CYP17A1 107
CYP27A1 124
CYP27B1 57
CYP2R1 19
CYP3A5 0
CYP4F22 41
CYP4V2 57
CYP7B1 45
D2HGDH 20
DARS2 47
DBH 6
DCAF17 29
DCLRE1C 103
DDX25;HYLS1;PUS3 1
DHCR24 6
DHH 14
DICER1 326
DIP2B 1
DISC1 0
DLAT 11
DLC1 1
DMGDH 2
DMPK 0
DNAAF1 31
DNAAF2 23
DNAAF4 17
DNAI1 93
DNAI2 58
DNAJC19 9
DNM1L 48
DOCK8 61
DOK7 60
DOLK 12
DPM3 10
DPYD 82
DPYS 23
DSG4 10
DTNBP1 7
DUOX2 145
DUOXA2 17
DYM 35
EDAR 64
EDARADD 15
EFEMP2 24
EFHC1 0
EGLN1 7
EHBP1 0
EHMT1 129
EIF2AK3 56
EIF2B1 19
EIF2B2 23
EIF2B3 14
EIF2B4 26
EIF2B5 91
ELAC2 53
ELOVL4 13
ELP1 229
EMG1 1
ENAM 8
EPM2A 33
ERCC6 178
ERCC8 80
ERCC8;NDUFAF2 3
ERMAP 0
ESCO2 56
ESPN 13
ETFA 41
ETHE1 53
EVC 149
EVC2 173
EXT1 242
EXT2 115
EYS 483
F12 15
F5 64
FA2H 41
FAM161A 77
FAM20C 21
FANCA 528
FANCI 141
FANCI;POLG 1
FANCL 62
FANCM 87
FASTKD2 18
FBLN5 6
FBN2 116
FBP1 32
FBXO7 26
FCGR2B 0
FCN3 0
FECH 54
FERMT1 30
FERMT3 12
FGD4 21
FGF20 1
FGF23 12
FIG4 74
FIGLA 4
FKBP10 33
FKRP 119
FKTN 87
FLCN 156
FLVCR2 13
FOXD3 0
FOXL2 66
FOXP2 40
FOXRED1 44
FRAS1 180
FREM1 46
FREM2 54
FRZB 0
FSCN2 2
FTCD 14
FTO 3
FUCA1 55
FXN 15
FZD4 39
G6PC3 33
GAA 451
GABBR2 16
GAD1 13
GALC 233
GALE 32
GALK1 57
GALNS 222
GALNT12 0
GALT 247
GAN 39
GBA1 293
GBE1 121
GCDH 257
GCDH;KLF1;LOC117125594 1
GCLC 2
GCM2 15
GDAP1 62
GFM1 99
GHRL 0
GIGYF2 0
GJB4 6
GJB6 8
GJC2 36
GLB1 229
GLIS3 10
GLRX5 7
GM2A 10
GNAS;GNAS-AS1 1
GNE 137
GNMT 2
GNPTAB 195
GNPTG 77
GNS 40
GORAB 23
GP1BA 43
GPC6 2
GPD1L 0
GPHN 27
GPSM2 20
GRHL2 18
GRHPR 70
GRM6 34
GRXCR1 13
GSDME 5
GTF2H5 8
GUSB 67
GYG1 20
HABP2 0
HAL 0
HAMP 6
HAVCR1 0
HAX1 30
HCN4 17
HDAC4 9
HERC2 15
HEXA 207
HEXB 103
HFE 30
HGD 203
HGSNAT 113
HIBCH 30
HJV 43
HLCS 97
HMBS 108
HMCN1 0
HNMT 2
HOGA1 97
HOXA2 4
HPD 20
HPS1 92
HPS1;MIR4685 0
HPS3 122
HPS4 51
HPS5 76
HPS6 39
HPSE2 12
HSD17B3 49
HSD3B7 14
HSPB3 0
HSPB8 7
HTRA2 6
HTRA2;LOXL3 0
HTT 5
HYAL1 21
HYCC1 13
ICOS 6
IDH3B 16
IFT122 54
IFT80 35
IGF2BP2 0
IL23R 0
IMPG2 80
INF2 55
INPP5E 45
IQCB1 55
IRAK3 0
IRAK4 16
IRF5 1
IRF6 99
ISCU 2
ITCH 11
ITGA2B 165
ITM2B 3
ITPKC 0
IVD 107
IYD 5
JPH3 0
KALRN 0
KANK1 1
KCNE2 1
KCNE3 0
KCNE3;LIPT2 0
KCNJ18 0
KCNK9 8
KCNMB1 0
KCNQ1 365
KCNQ1OT1 0
KCNV2 54
KCTD7 24
KIF1B 2
KIF21A 14
KIFBP 7
KIRREL3 3
KISS1R 11
KL 0
KLHDC8B 0
KLHL7 29
KLK4 4
KNG1 8
KRIT1 156
KRT74 3
KRT75 0
KRT9 19
L2HGDH 33
LAMTOR2 0
LCA5 73
LCAT 29
LDB3 19
LDLR 1093
LDLR;MIR6886 2
LDLRAP1 34
LEMD3 32
LGI1 45
LHFPL5 15
LIPA 102
LIPH 5
LIPI 0
LITAF 8
LLGL2;TSEN54 1
LMBR1 3
LMBR1;ZRS 5
LMBRD1 30
LMF1 17
LOXHD1 253
LPAR6 11
LPIN1 23
LPIN2 23
LPL 115
LPO;MPO 1
LRAT 14
LRP4 38
LRPPRC 169
LRRK2 9
LRTOMT 17
LTBP4 41
LYST 150
LZTS1 2
MAN2B1 187
MANBA 68
MAPK8IP1 0
MARVELD2 17
MASP2 2
MASTL 0
MAT1A 33
MBD5 53
MC2R 23
MCCC1 107
MCCC2 133
MCEE 4
MCFD2 7
MCOLN1 67
MCPH1 62
MED13L 149
MED25 5
MEFV 16
MERTK 73
MESP2 33
MFN2 162
MFRP 34
MFSD8 95
MIAT 0
MINPP1 9
MIR103A2;MIR103B2;PANK2 1
MIR2861 0
MIR96 2
MKKS 55
MKS1 107
MLC1 86
MLH3 1
MLPH 7
MLYCD 31
MMAA 72
MMAB 67
MMACHC 88
MMADHC 36
MMP20 10
MMUT 288
MOCS2 25
MPDU1 11
MPLKIP 8
MPO 11
MRAP 6
MRPS16 0
MRPS22 12
MSH2 614
MTHFR 130
MTMR14 0
MTRFR 7
MUTYH 212
MYH14 17
MYLK2 0
MYO3A 45
MYO5B 72
MYOT 8
NAGLU 183
NAGS 62
NAT2 0
NCF1 8
NCF2 45
NCR3 1
NDRG1 35
NDUFA13 4
NDUFAF2 6
NDUFAF3 7
NDUFAF4 1
NDUFAF5 68
NDUFAF6 20
NDUFS3 5
NDUFS6 19
NECTIN4 10
NEK8 23
NEU1 50
NEUROG3 10
NEXN 11
NF1 1881
NF2 161
NHEJ1 24
NHERF1 0
NHLRC1 26
NHP2 3
NIPA1 4
NIPAL4 29
NIPBL 309
NKX2-6 2
NLRP1 5
NLRP12 6
NLRP3 63
NLRP7 18
NME8 0
NOBOX 8
NOD2 21
NOP10 1
NPC1 361
NPC1L1 0
NPHP1 74
NPHP3 82
NPHP4 84
NPHS2 88
NPSR1 0
NR0B2 2
NR2E3 73
NSD1 365
NSMF 2
NT5C3A 11
NUBPL 13
NUP62 1
OAT 91
OBSL1 31
OCA2 199
OPA1 210
OPA3 21
OPN1SW 0
ORAI1 11
OSTM1 17
OTOA 44
P3H1 79
PAH 689
PALB2 391
PALLD 0
PANK2 85
PAX3 126
PAX6 227
PC 78
PCARE 53
PCDH15 205
PCNT 188
PCSK9 17
PDCD10 37
PDE11A 6
PDGFRL 1
PDHX 19
PDP1 2
PDSS1 10
PDSS2 3
PEPD 55
PEX26 31
PFKM 70
PGAM2 7
PHGDH 56
PHOX2B 22
PIGM 1
PIGV 8
PIKFYVE 16
PINK1 27
PIP5K1C 5
PITPNM3 2
PJVK 23
PKHD1 786
PKLR 94
PLCE1 34
PLEKHG4 0
PLEKHG5 42
PLEKHM1 3
PNKD 3
PNKP 57
PNPLA2 19
POLG2 17
POLH 30
POMGNT1 139
POMP 0
POMT1 86
POMT2 86
POU6F2 2
PPARGC1B 0
PPP1R17 0
PPP2R2B 0
PRCD 8
PRG4 8
PRICKLE1 2
PRKAG3 0
PRKCH 0
PROC 96
PRODH 11
PROK2 6
PROKR2 8
PROM1 94
PRPF3 11
PRPF31 117
PRPF8 49
PRSS12 2
PRX 33
PSAT1 21
PSTPIP1 4
PTF1A 3
PTGDR 0
PTS 82
PUS1 33
PYGM 157
QDPR 48
RAB23 17
RAB27A 31
RAB3GAP2 27
RAD50 210
RAD54B 1
RAI1 50
RARS2 140
RAX2 4
RB1CC1 1
RBBP8 7
RBM20 52
RBM28 2
RDH12 100
RECQL4 180
REEP1 55
RETN 0
RETREG1 15
RFT1 14
RFX6 25
RGS9 28
RGS9BP 1
RIMS1 2
RIN2 6
RNASEH2A 29
RNASEH2B 37
RNASEH2C 6
RNASET2 7
RNF135 0
RNF168 10
RNF212 0
RNF6 3
ROBO3 27
RP1 129
RP1L1 36
RP9 1
RPGRIP1 93
RPGRIP1L 178
RPL11 18
RRM2B 32
RSPH4A 33
RSPO1 3
RSPO4 9
RTN4R 0
RXFP2 1
SACK1H 16
SACS 339
SALL4 16
SAMD9 30
SAMHD1 73
SAR1B 13
SART3 8
SATB2 117
SBDS 25
SBF2 57
SCGB3A2 0
SCN3B 2
SCN4A 135
SCN4B 2
SCO2 19
SDCCAG8 53
SDHAF1 8
SDHAF2 23
SEC23A 3
SEC23B 62
SEC63 34
SECISBP2 10
SELENON 57
SEMA3E 0
SEMA4A 3
SEPTIN9 3
SERPINA10 0
SERPINF2 2
SERPING1 201
SETBP1 61
SETX 54
SGCE 69
SGCG 55
SGSH 124
SGSH;SLC26A11 1
SH3PXD2B 10
SH3TC2 95
SI 103
SIAE 0
SIL1 17
SIX3 18
SIX6 5
SLC12A6 116
SLC16A12 2
SLC17A5 78
SLC17A8 3
SLC19A2 36
SLC19A3 48
SLC22A12 16
SLC22A4 0
SLC24A4 5
SLC24A5 26
SLC25A13 118
SLC25A15 43
SLC25A19 14
SLC25A22 15
SLC25A38 37
SLC26A2 86
SLC26A4 438
SLC26A5 13
SLC27A4 35
SLC29A3 26
SLC2A10 33
SLC2A9 13
SLC30A8 0
SLC34A2 10
SLC34A3 58
SLC35A1 4
SLC35C1 7
SLC35D1 10
SLC36A2 0
SLC39A13 1
SLC39A4 58
SLC40A1 38
SLC45A2 68
SLC46A1 10
SLC4A11 97
SLC52A3 21
SLC6A19 34
SLC6A20 0
SLC6A5 48
SLC7A9 54
SLC9A9 1
SLITRK1 1
SLURP1 12
SMARCAL1 81
SMC3 63
SMPD1 225
SNCAIP 0
SOST 6
SOX9 84
SP110 20
SPART 11
SPAST 354
SPATA16 0
SPATA7 29
SPG11 236
SPG21 6
SPINK5 71
SPINT2 15
SPRED1 69
SPTBN2 43
SPTLC1 12
SPTLC2 10
SRD5A2 71
ST14 10
ST3GAL5 28
STAT5B 18
STIM1 26
STOX1 0
STRA6 17
STRADA 14
STRC 42
STX11 13
SUCLA2 23
SUFU 52
SUGCT 4
SUMF1 89
SUMF2 0
SUMO4;TAB2 0
SUOX 39
SYCP3 1
SYNE1 235
SYNE2 4
TAB2 33
TACO1 8
TARDBP 24
TAS2R16 0
TAS2R38 0
TAT 40
TBC1D24 73
TBCE 32
TBX15 1
TBX19 20
TBX20 25
TBX21 0
TCAP 15
TCIRG1 135
TCN2 29
TCOF1 65
TDP1 5
TFR2 87
TGM5 13
THAP1 25
TINF2 18
TIRAP 0
TJP2 49
TLL1 3
TMC1 118
TMC6 19
TMC8 15
TMEM126A 4
TMEM127 44
TMEM216 28
TMEM43 2
TMEM67 162
TMEM70 14
TMIE 11
TMPRSS15 47
TMPRSS3 97
TMPRSS6 22
TNFRSF13B 19
TNFRSF13C 1
TOPORS 5
TOR1A 11
TPCN2 1
TPH2 0
TPO 73
TPP1 131
TPRN 6
TRAPPC9 45
TREM2 17
TREX1 18
TRIM37 65
TRIOBP 51
TRIP11 44
TRMU 80
TRPM4 7
TRPM6 38
TRPM7 4
TRPS1 86
TRPV4 64
TSC1 281
TSEN2 17
TSEN34 1
TSEN54 42
TSFM 40
TSPAN12 25
TSPYL1 0
TTBK2 3
TTC8 42
TUBA8 1
TUBB1 12
TUBB2B 72
TWNK 64
TYR 237
TYROBP 5
UBIAD1 12
UBR1 49
UNC119 1
UNC13D 105
UNC93B1 7
UPB1 12
UPK3A 1
UQCRQ 0
UROC1 3
UROD 37
UROS 27
USB1 14
USH1C 112
USH1G 21
USH2A 1202
UTP4 0
VANGL1 1
VAPB 2
VHL 235
VIPAS39 23
VKORC1 5
VPS13A 242
VPS13B 474
VPS33B 38
VSX1 0
VWF 310
WASHC5 30
WDPCP 28
WDR35 48
WDR36 0
WDR62 64
WDR72 25
WFS1 154
WHRN 25
WNK1 34
WNT10A 66
WRN 220
WT1 102
WWC1 0
WWOX 63
XDH 33
XPA 45
XPC 108
XPNPEP3 13
XYLT1 13
XYLT2 4
YARS2 18
ZEB2 159
ZFAT 0
ZFP57 6
ZFYVE26 211
ZFYVE27 0
ZMPSTE24 22
ZNF365 0
ZNF469 51
ZNF513 0
ZNF592 0
ZNF750 0
ZRS;LMBR1 4

In [ ]:
variant_counts = Clin1["GeneSymbol"].value_counts().sort_index().reset_index()
variant_counts.columns = ["GeneSymbol", "Number of Variants"]
#print(variant_counts)
variant_counts.head(20)

                                           GeneSymbol  Number of Variants
0                                                   -                9802
1                                          A-GAMMA3'E                   2
2   A-GAMMA3'E;BGLT3;HBE1;HBG1;HBG2;HS-E1;LOC10609...                   1
3                                                A1BG                 172
4                                            A1BG-AS1                   8
5                                                A1CF                 140
6                             A1CF;ASAH2B;PRKG1;SGMS1                   2
7                                                 A2M                 466
8                                             A2M-AS1                   2
9          A2M;A2ML1;KLRG1;M6PR;MFAP5;PHC1;PZP;RIMKLB                   1
10                          A2M;A2ML1;KLRG1;M6PR;PHC1                   1
11                                          A2M;KLRG1                   2
12                            A2M;KLRG1;M6PR;PHC1;PZP                   1
13                                              A2ML1                3992
14                                            A3GALT2                  16
15                                             A4GALT                 282
16                                     A4GALT;ARFGAP3                   3
17  A4GALT;ATP5MGL;CYB5R3;NFAM1;POLDIP3;RRP7A;SERH...                   1
18                                              A4GNT                 118
19                                         A4GNT;DBR1                   1

In [ ]:
import os
os.getcwd()
path = "/Users/adesinamary/Documents/GitHub/kondrashov/"
#os.mkdir('path')
os.listdir(path)

['variable_sites_old.tsv',
 'variable_sites.tsv',
 'find_CPDs_Mary.ipynb',
 'Clinvar_variants_written_from_database.txt',
 'clinvar',
 'clean_up_Mary.ipynb',
 'kondrashov.py',
 '.DS_Store',
 'orthologs_xml_updated.ipynb',
 'invalidated_CPDs_match_JUL31.tsv',
 'protein_Sequence_length.txt',
 'gene_transcript_changes.tsv',
 'gencode.v50.metadata.HGNC.xlsx',
 'Translation.xlsx',
 'invalidated_CPDs.tsv',
 'Variable_sites_match_29JUL.tsv',
 'Clinvar_variants_written_from_database.xlsx',
 'fasta',
 'pathogenic',
 'README.md',
 'orthologs_Rodentia.ipynb',
 'aln_match',
 'Validate_CPDs_Mary.ipynb',
 '.gitignore',
 'fasta_match_Copy',
 'fasta_match',
 'find_closest.ipynb',
 'Variable_sites_match_30JUL.tsv',
 '.github',
 'find_CPDs_Match.ipynb',
 'orthologs.ipynb',
 'orthologs_xml.ipynb',
 '.ipynb_checkpoints',
 'find_CPDs.ipynb',
 '.git',
 'orthologs_Mary_Primates.ipynb',
 'find_closest_Mary.ipynb',
 'clean_up.ipynb',
 'aln_match - Copy',
 'align.ipynb',
 'pathogen_Mary.ipynb',
 'orthologs_new.ipynb',
 'pathogen.ipynb',
 'aln']

In [ ]:
run kondrashov

In [ ]:
variant_counts['GeneSymbol']
variant_counts
Clin1
#loci

,Type,Name,GeneSymbol,ClinicalSignificance,Assembly
0,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,AP5Z1,Pathogenic/Likely pathogenic,GRCh37
1,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,AP5Z1,Pathogenic/Likely pathogenic,GRCh38
2,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),AP5Z1,Pathogenic,GRCh37
3,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),AP5Z1,Pathogenic,GRCh38
4,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),ZNF592,Uncertain significance,GRCh37
...,...,...,...,...,...
8990430,Deletion,NM_004621.6(TRPC6):c.1359del (p.Leu454fs),TRPC6,Likely pathogenic,GRCh38
8990431,Deletion,NM_004621.6(TRPC6):c.2379del (p.Gly794fs),TRPC6,Likely pathogenic,GRCh37
8990432,Deletion,NM_004621.6(TRPC6):c.2379del (p.Gly794fs),TRPC6,Likely pathogenic,GRCh38
8990433,Deletion,NM_004621.6(TRPC6):c.1841del (p.Leu614fs),TRPC6,Likely pathogenic,GRCh37
8990434,Deletion,NM_004621.6(TRPC6):c.1841del (p.Leu614fs),TRPC6,Likely pathogenic,GRCh38

In [ ]:
print(variant_counts[variant_counts["GeneSymbol"] == "BRCA1"])

     GeneSymbol  Number of Variants
4558      BRCA1               31226

In [ ]:
import os
os.chdir('/Users/adesinamary/Documents/Variant_summary_genes/')

## STEP 2 
### For each gene filter variants with above 99 variants. Save output to .csv file

In [11]:
xx = ['ABCD1',
'ALPL',
'AR',
'BTK',
'CASR',
'CFTR',
'CYBB',
'F7',
'F8',
'F9',
'G6PD',
'GJB1',
'HBB',
'HPRT1',
'IL2RG',
'KCNH2',
'L1CAM',
'MPZ',
'MYH7',
'PMM2',
'RHO',
'TP53',
'TTR']

In [13]:
terms = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, low penetrance"]

for gene in sorted(lociii):
    variants = Clin1[
        (Clin1["GeneSymbol"] == gene) &
        (Clin1["ClinicalSignificance"].isin(terms)) &
        (Clin1["Type"] == "single nucleotide variant") &
        (Clin1["Assembly"] == "GRCh38")
    ]
    if len(variants) > 99:
        variants.to_csv(f"/Users/adesinamary/Documents/GitHub/kondrashov/pathogenic_lociii/{gene}.csv", sep="\t", index=False)
        print(gene, len(variants), "variants exists")
            # to print the gene names in a list format for further analysis (lociii)
        # print(f"'{gene}',")
    else:
        ignore = True

    

    #print(variant_counts[variant_counts["GeneSymbol"] == gene])

ABCD1 327 variants exists
ALPL 404 variants exists
AR 269 variants exists
BTK 244 variants exists
CASR 206 variants exists
CFTR 773 variants exists
CYBB 141 variants exists
F7 80 variants exists
F8 512 variants exists
F9 274 variants exists
G6PD 207 variants exists
GJB1 201 variants exists
HBB 183 variants exists
HPRT1 71 variants exists
IL2RG 113 variants exists
KCNH2 320 variants exists
L1CAM 146 variants exists
MPZ 143 variants exists
MYH7 406 variants exists
PMM2 174 variants exists
RHO 173 variants exists
TP53 414 variants exists
TTR 130 variants exists