# Find putative CPDs

## Rerun clean up commands

Since the ClinVar data was modified we begin by rerun the commands in the [clean_up.ipynb](clean_up.ipynb) notebook.

### Extract transcript IDs from variants

Pull the transcript record IDs from the ClinVar records of each gene.

**Output:** `vartranscripts` dictionary with genes as keys and lists of transcripts as values.  The new `dict` has 68 transcripts instead of 72.

In [2]:
import os
os.getcwd()

'c:\\Users\\adesi\\Documents\\GitHub\\kondrashov'

In [8]:
run kondrashov

#### Step 1

In [9]:
i = 0
vartranscripts = {}
for gene in loci:
    vt = get_transcripts_from_variants(gene, True)
    #i += len(vt)    
    print(gene, vt[0], len(vt), 'transcripts')
    vartranscripts.update({gene: vt})

ABCD1 NM_000033.4 1 transcripts
ALPL NM_000478.6 1 transcripts
AR NM_000044.6 1 transcripts
ATP7B NM_000053.4 1 transcripts
BTK NM_000061.3 1 transcripts
CASR NM_000388.4 1 transcripts
CBS NM_000071.3 1 transcripts
CFTR NM_000492.4 3 transcripts
CYBB NM_000397.4 1 transcripts
F7 NC_000013.11:g.113105748C>G 5 transcripts
F8 NC_000023.11:g.155022771G>A 2 transcripts
F9 NC_000023.11:g.139530710G>C 4 transcripts
G6PD NM_000402.4 3 transcripts
GALT NM_000155.4 1 transcripts
GBA1 NM_000157.4 1 transcripts
GJB1 NM_001097642.3 2 transcripts
HBB NC_000011.10:g.5227096C>A 10 transcripts
HPRT1 NM_000194.2 3 transcripts
IL2RG NM_000206.3 1 transcripts
KCNH2 NM_000238.4 1 transcripts
KCNQ1 NM_000218.3 1 transcripts
L1CAM NM_001278116.2 1 transcripts
LDLR NM_000527.4 2 transcripts
MPZ NM_000530.8 1 transcripts
MYH7 NM_000257.4 1 transcripts
TYR NM_000372.5 1 transcripts
PAH NM_000277.3 1 transcripts
PMM2 NC_000016.10:g.8797716G>T 2 transcripts
RHO NM_000539.3 1 transcripts
TP53 NM_000546.6 1 transcripts
TTR NM_000371.4 1 transcripts
VWF NM_000552.5 1 transcripts

In [12]:
vartranscripts_filtered = {
    gene: [v for v in values if v.startswith("NM_")]
    for gene, values in vartranscripts.items()
}
vartranscripts_filtered

{'ABCD1': ['NM_000033.4'],
 'ALPL': ['NM_000478.6'],
 'AR': ['NM_000044.6'],
 'ATP7B': ['NM_000053.4'],
 'BTK': ['NM_000061.3'],
 'CASR': ['NM_000388.4'],
 'CBS': ['NM_000071.3'],
 'CFTR': ['NM_000492.4', 'NM_000492.3'],
 'CYBB': ['NM_000397.4'],
 'F7': ['NM_019616.4', 'NM_000131.5', 'NM_000131.4'],
 'F8': ['NM_000132.4'],
 'F9': ['NM_000133.4'],
 'G6PD': ['NM_000402.4', 'NM_001360016.2', 'NM_001042351.3'],
 'GALT': ['NM_000155.4'],
 'GBA1': ['NM_000157.4'],
 'GJB1': ['NM_001097642.3', 'NM_000166.6'],
 'HBB': ['NM_000518.5', 'NM_000518.4'],
 'HPRT1': ['NM_000194.2', 'NM_000194.3'],
 'IL2RG': ['NM_000206.3'],
 'KCNH2': ['NM_000238.4'],
 'KCNQ1': ['NM_000218.3'],
 'L1CAM': ['NM_001278116.2'],
 'LDLR': ['NM_000527.4', 'NM_000527.5'],
 'MPZ': ['NM_000530.8'],
 'MYH7': ['NM_000257.4'],
 'TYR': ['NM_000372.5'],
 'PAH': ['NM_000277.3'],
 'PMM2': ['NM_000303.3'],
 'RHO': ['NM_000539.3'],
 'TP53': ['NM_000546.6'],
 'TTR': ['NM_000371.4'],
 'VWF': ['NM_000552.5']}

### Step 2
##### Extract human protein sequence records from the fasta files

Take the fasta files containing ortholog sequences, search for human sequences and extract the corresponding record.

**Output:** `protrecs` dictionary with genes as keys and lists of protein records as values. Unchanged.

In [13]:
import os
os.listdir('fasta_match')

['ABCD1_NP_000024.2_match.fasta',
 'ALPL_NP_000469.3_match.fasta',
 'AR_NP_000035.2_match.fasta',
 'ATP7B_NP_000044.2_match.fasta',
 'BTK_NP_000052.1_match.fasta',
 'CASR_NP_000379.3_match.fasta',
 'CBS_NP_000062.1_match.fasta',
 'CFTR_NP_000483.3_match.fasta',
 'CYBB_NP_000388.2_match.fasta',
 'F7_NP_000122.1_match.fasta',
 'F7_NP_062562.1_match.fasta',
 'F8_NP_000123.1_match.fasta',
 'F9_NP_000124.1_match.fasta',
 'G6PD_NP_000393.4_match.fasta',
 'G6PD_NP_001035810.1_match.fasta',
 'GALT_NP_000146.2_match.fasta',
 'GBA1_NP_000148.2_match.fasta',
 'GJB1_NP_000157.1_match.fasta',
 'HBB_NP_000509.1_match.fasta',
 'HPRT1_NP_000185.1_match.fasta',
 'IL2RG_NP_000197.1_match.fasta',
 'KCNH2_NP_000229.1_match.fasta',
 'KCNQ1_NP_000209.2_match.fasta',
 'L1CAM_NP_000416.1_match.fasta',
 'LDLR_NP_000518.1_match.fasta',
 'MPZ_NP_000521.2_match.fasta',
 'MYH7_NP_000248.2_match.fasta',
 'PAH_NP_000268.1_match.fasta',
 'PMM2_NP_000294.1_match.fasta',
 'RHO_NP_000530.1_match.fasta',
 'TP53_NP_000537.3_match.fasta',
 'TTR_NP_000362.1_match.fasta',
 'TYR_NP_000363.1_match.fasta',
 'VWF_NP_000543.3_match.fasta']

### This code works for fasta_match/ directory which has a different naming scheme

In [15]:
import os
from Bio import SeqIO

protrecs = {}
i = 1
for filename in os.listdir("fasta_match"):
    if not filename.endswith(".fasta"):
        continue
    gene = filename.split("_")[0]
    protrecs.setdefault(gene, [])
    filepath = os.path.join("fasta_match", filename)

    for record in SeqIO.parse(filepath, "fasta"):
        if get_species(record) == "Homo sapiens":
            protrecs[gene].append(record)
            print(i, gene, record.id, len(record))
            i += 1

1 ABCD1 NP_000024.2 745
2 ALPL NP_000469.3 524
3 AR NP_000035.2 920
4 ATP7B NP_000044.2 1465
5 BTK NP_000052.1 659
6 CASR NP_000379.3 1078
7 CBS NP_000062.1 551
8 CFTR NP_000483.3 1480
9 CYBB NP_000388.2 570
10 F7 NP_000122.1 466
11 F7 NP_062562.1 444
12 F8 NP_000123.1 2351
13 F9 NP_000124.1 461
14 G6PD NP_000393.4 545
15 G6PD NP_001035810.1 515
16 GALT NP_000146.2 379
17 GBA1 NP_000148.2 536
18 GJB1 NP_000157.1 283
19 HBB NP_000509.1 147
20 HPRT1 NP_000185.1 218
21 IL2RG NP_000197.1 369
22 KCNH2 NP_000229.1 1159
23 KCNQ1 NP_000209.2 676
24 L1CAM NP_000416.1 1257
25 LDLR NP_000518.1 860
26 MPZ NP_000521.2 248
27 MYH7 NP_000248.2 1935
28 PAH NP_000268.1 452
29 PMM2 NP_000294.1 246
30 RHO NP_000530.1 348
31 TP53 NP_000537.3 393
32 TTR NP_000362.1 147
33 TYR NP_000363.1 529
34 VWF NP_000543.3 2813

In [16]:
protrecs['TYR']

[SeqRecord(seq=Seq('MLLAVLYCLLWSFQTSAGHFPRACVSSKNLMEKECCPPWSGDRSPCGQLSGRGS...SHL'), id='NP_000363.1', name='NP_000363.1', description='NP_000363.1 tyrosinase precursor [Homo sapiens]', dbxrefs=[])]

### STEP 3 
##### Match variant transcript IDs with ortholog proteins

Take variant transcript ID, query the NCBI database, extract the corresponding protein, and look for it in the ortholog set.  Flag problems.

**Output:** `translation` dictionary with transcript IDs as keys and lists of protein IDs as values.

In [17]:
#%%time
translation = {}
i = 1
for gene in loci:
    for transcript in vartranscripts_filtered[gene]:
        if transcript[:3] == 'NM_':
            rec = get_transcript(transcript)
            seq = get_CDS(rec)
            match = False
            for prot in protrecs[gene]: 
                if seq[4] == prot.seq:
                    print(i, gene, transcript, prot.id)
                    match = True
                    translation.update({transcript: prot.id})
            if not match:
                print(i, gene, transcript, 'no matching protein         <<<<<')
        else:
            print(i, gene, transcript, 'invalid transcript name         *****')
        i += 1

1 ABCD1 NM_000033.4 NP_000024.2
2 ALPL NM_000478.6 NP_000469.3
3 AR NM_000044.6 NP_000035.2
4 ATP7B NM_000053.4 NP_000044.2
5 BTK NM_000061.3 NP_000052.1
6 CASR NM_000388.4 NP_000379.3
7 CBS NM_000071.3 NP_000062.1
8 CFTR NM_000492.4 NP_000483.3
9 CFTR NM_000492.3 NP_000483.3
10 CYBB NM_000397.4 NP_000388.2
11 F7 NM_019616.4 NP_062562.1
12 F7 NM_000131.5 NP_000122.1
13 F7 NM_000131.4 NP_000122.1
14 F8 NM_000132.4 NP_000123.1
15 F9 NM_000133.4 NP_000124.1
16 G6PD NM_000402.4 NP_000393.4
17 G6PD NM_001360016.2 NP_001035810.1
18 G6PD NM_001042351.3 NP_001035810.1
19 GALT NM_000155.4 NP_000146.2
20 GBA1 NM_000157.4 NP_000148.2
21 GJB1 NM_001097642.3 NP_000157.1
22 GJB1 NM_000166.6 NP_000157.1
23 HBB NM_000518.5 NP_000509.1
24 HBB NM_000518.4 NP_000509.1
25 HPRT1 NM_000194.2 NP_000185.1
26 HPRT1 NM_000194.3 NP_000185.1
27 IL2RG NM_000206.3 NP_000197.1
28 KCNH2 NM_000238.4 NP_000229.1
29 KCNQ1 NM_000218.3 NP_000209.2
30 L1CAM NM_001278116.2 NP_000416.1
31 LDLR NM_000527.4 NP_000518.1
32 LDLR NM_000527.5 NP_000518.1
33 MPZ NM_000530.8 NP_000521.2
34 MYH7 NM_000257.4 NP_000248.2
35 TYR NM_000372.5 NP_000363.1
36 PAH NM_000277.3 NP_000268.1
37 PMM2 NM_000303.3 NP_000294.1
38 RHO NM_000539.3 NP_000530.1
39 TP53 NM_000546.6 NP_000537.3
40 TTR NM_000371.4 NP_000362.1
41 VWF NM_000552.5 NP_000543.3

## clean up variants not matching any protein
* HBB 
* G6PD
#### Clean up is required only once

In [ ]:
vardata = pd.read_csv('pathogenic/HBB.csv')
i = vardata['Name'].tolist().index('Hb Little Rock')
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

In [10]:
vardata.loc[i, 'Name'] = 'NM_000518.5(HBB):c.432C>R (p.His144Gln)'
vardata.to_csv('pathogenic/HBB.csv', index=False)
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
40,30404,single nucleotide variant,NM_000518.5(HBB):c.431A>C (p.His144Pro),3043,HBB,HGNC:4827,Pathogenic,1,"Jul 14, 2025",33918338,...,G,-,-,-,-,-,-,SCV001158641,-,-
41,30417,single nucleotide variant,NM_000518.4(HBB):c.320T>A (p.Leu107Gln),3043,HBB,HGNC:4827,Pathogenic,1,"May 20, 2023",33941844,...,T,-,-,-,-,-,-,SCV005329471,-,-
42,30425,single nucleotide variant,NM_000518.5(HBB):c.432C>R (p.His144Gln),3043,HBB,HGNC:4827,Pathogenic,1,"Nov 13, 2020",33954632,...,T,-,-,-,-,-,-,SCV002046407,-,-
43,30429,single nucleotide variant,NM_000518.4(HBB):c.293A>T (p.His98Leu),3043,HBB,HGNC:4827,Likely pathogenic,1,"May 22, 2025",33951978,...,A,-,-,-,-,-,-,SCV005876053,-,-
44,30434,single nucleotide variant,NM_000518.4(HBB):c.440A>C (p.His147Pro),3043,HBB,HGNC:4827,Pathogenic,1,"May 24, 2024",33954264,...,G,-,-,-,-,-,-,SCV006104266,-,-

### G6PD

In [ ]:
vardata = pd.read_csv('pathogenic/G6PD.csv')
i = vardata['Name'].tolist().index('G6PD ZURICH') 
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

In [12]:
vardata.loc[i, 'Name'] = 'NM_001360016.2(G6PD):c.1288-2A>G)'
vardata.to_csv('pathogenic/G6PD.csv', index=False)
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
40,25455,single nucleotide variant,NM_000402.4(G6PD):c.298T>C (p.Tyr100His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Nov 25, 2024",137852349,...,G,-,-,-,-,-,-,SCV001443096|SCV002599323|SCV003445326|SCV0038...,-,-
41,25456,single nucleotide variant,NM_000402.4(G6PD):c.683G>A (p.Arg228His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Jan 02, 2026",137852332,...,T,-,-,-,-,-,-,SCV001142107|SCV002599340|SCV004299714|SCV0050...,-,-
42,25459,single nucleotide variant,NM_001360016.2(G6PD):c.1288-2A>G),2539,G6PD,HGNC:4057,Pathogenic,1,"Aug 12, 2022",2070350038,...,C,-,-,-,-,-,-,SCV002599384,-,-
43,25461,single nucleotide variant,NM_000402.4(G6PD):c.1466G>C (p.Arg489Pro),2539,G6PD,HGNC:4057,Pathogenic,1,"Feb 05, 2024",72554665,...,G,-,-,-,-,-,-,SCV000330997|SCV000914284|SCV001367223|SCV0013...,-,-
44,99398,single nucleotide variant,NM_001360016.2(G6PD):c.1360C>T (p.Arg454Cys),2539,G6PD,HGNC:4057,Pathogenic,1,"Apr 29, 2026",398123546,...,A,-,-,-,-,-,-,SCV000225263|SCV000281545|SCV000603769|SCV0006...,-,-

### STEP 5 
#### Match variant transcript to corresponding protein (this will serve as reference protein)
### Identify all mutant amino acid sites in the clinvar variants (pathogenic/)

In [25]:
run kondrashov

In [ ]:
variants = {}
print('gene \t transcript \t protein \t no_of_sites \t sites')

for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        sites, wilds, muts = get_all_changes(gene, transcript, True)
        if len(sites)>0:
            variants[transcript] = {
                "gene": gene,
                "protein": translation[transcript],
                "sites": sites,
                "wilds": wilds,
                "muts": muts
            }
            #variants.update({'gene':gene, transcript: (sites, wilds, muts)})
        print(gene, transcript, translation[transcript], len(sites), sites, sep='\t')

gene 	 transcript 	 protein 	 no_of_variants 	 variant_sites
ABCD1	NM_000033.4	NP_000024.2	327	['291', '484', None, '389', '148', '174', '266', '401', '418', '464', '477', '515', '518', None, '606', '617', '617', None, '300', '141', '280', '466', '518', '529', '554', '560', '591', '601', None, '116', '136', '554', '609', '401', '296', '296', '430', None, '217', '389', '177', '163', '632', '189', '254', None, '679', '104', '148', '591', '660', None, '98', '174', '424', '666', '401', '296', '679', None, '281', '523', '543', '518', '668', '292', '609', '145', '152', '376', '626', None, '366', '512', '660', '107', '221', '27', '163', '198', '389', '396', '533', '658', '300', '116', '277', '298', '307', '485', '595', '640', None, None, '174', '141', '339', '407', '656', '114', '293', '382', '501', '666', '1', '148', '266', '283', '332', '343', '544', '560', '654', None, '543', '664', '567', '137', '220', '343', '472', '503', '559', '193', '194', '263', '631', '669', None, '221', '608', '633', '97', '495', '590', '636', '10', '108', '152', '617', '277', '200', '416', '291', '481', '262', '322', '380', '594', '606', '74', None, '173', '277', '161', '10', None, '132', '90', '163', None, None, '283', '163', '163', '311', '152', '507', '560', '631', '104', '608', '284', '408', '574', '667', '52', '559', '283', '174', '97', '211', '684', '510', '254', '512', '152', '285', None, '508', '629', '595', '98', None, '601', '373', '359', '513', '195', '318', '516', '672', '358', '343', '525', '510', '113', '157', '302', '339', '420', None, '507', '524', None, '484', None, '266', '336', '418', None, '571', '144', '534', None, None, '116', '667', '625', '133', '74', '504', '312', '111', '326', '298', '694', '485', None, '277', '560', None, '291', '493', '277', '152', '275', '331', '33', '84', '98', '120', '174', '263', '279', '290', None, '493', '534', '556', '591', '640', '414', '408', '611', '654', None, '529', '194', '103', '284', '306', '626', '220', '647', None, '229', '298', '511', '476', '558', None, '298', '418', '611', '665', None, '31', '132', '178', '190', '223', '254', None, '302', '511', '547', '556', '300', None, '313', '55', '401', '326', None, '533', None, '669', '211', '611', '396', '104', '194', '143', '572', None, None, '630', '632', '145', '163', '170', '547', '659', '266', '92', '419']
ALPL	NM_000478.6	NP_000469.3	404	['179', '71', '294', '71', '207', '33', '298', '378', '334', '327', '136', '162', '116', None, '417', '108', '456', '249', '176', '272', '72', '181', '223', '264', '270', '291', '297', None, '30', '44', None, None, None, '382', '455', '476', '223', '76', '468', '114', '272', '63', '184', '29', '166', '88', '141', None, '347', '106', '123', '136', '445', '459', '112', '210', '224', '348', '378', '442', '459', '294', '337', '491', '220', '221', '391', '391', '429', '487', '332', '132', '381', '308', '100', '111', '473', '476', None, '428', '191', '467', None, '275', '359', '388', '136', '317', '192', '450', '32', '40', '167', '167', None, '206', '246', '428', '341', '472', '410', '443', '219', '221', '112', '170', '382', None, '68', '71', '75', '101', '162', '178', '186', '220', '296', '326', '333', '414', '389', '219', '476', '292', '181', '493', '454', '121', '201', '72', '83', '473', '95', '1', '116', '184', '141', '179', '132', '395', '388', '153', '456', '476', None, '336', '456', '272', '327', '411', '468', '482', '399', '423', '377', '388', '191', '339', '374', '426', '446', '468', '476', '341', '40', '452', '132', '178', '299', '311', '455', '101', '297', '235', '459', '397', '351', '37', '171', '221', '291', '292', '295', '395', '93', '428', '173', '334', '466', '173', None, '285', '61', '477', '340', '389', '227', '414', '129', '51', '10', '420', '318', '341', '387', '82', '82', '176', '443', '416', '378', '386', '220', '171', '420', '420', '236', '178', '138', '71', '128', '76', '426', None, '117', '399', None, '497', '256', '268', '187', '1', None, '423', '71', '148', '307', '339', '371', '406', '490', None, '220', '177', '33', '294', '102', '359', '174', '466', '452', '184', '298', '262', '327', None, '63', '191', '391', '239', None, '297', '414', '294', '115', None, '443', '291', '58', '489', '441', '107', '195', '386', '55', None, '268', '489', '384', '221', '226', '226', '236', None, '111', '339', '66', '134', '408', None, '1', '306', None, '102', '491', '261', '218', '378', '389', '456', '162', '155', '171', '326', '76', None, None, '306', '102', '28', '445', None, '436', '106', '109', '112', '17', '134', '136', '148', '153', '154', None, None, '28', '29', '188', '199', '212', '226', '235', '236', None, '288', '289', '290', '292', '295', '297', '297', '328', None, None, '47', '334', '337', '340', '341', '348', '351', '371', '379', '386', '393', '1', '406', None, '420', '426', '426', '429', '430', None, '62', '441', '443', '62', '454', '466', '62', '478', '63', '489', '497', '497', '69', '75', '6', '84', '84', '85', '93', None, None, '101', '208', None, '235', '295', '384', '178', '447', '294', '377', '76', '146', '294', '306', '341', '356', '393', '393', '146', '396']
AR	NM_000044.6	NP_000035.2	269	['775', '719', '867', '797', '591', '648', '764', '884', '597', '788', '857', '775', '608', '867', '856', '870', '60', '609', '841', '841', '878', '678', '878', '875', '903', '708', '580', '583', '2', '781', None, '174', '808', '889', None, '713', '578', '866', '690', '744', '744', '741', '702', '602', '753', '562', None, '772', '856', '74', '616', '856', '890', '608', '289', '753', '713', '574', '766', None, '914', '630', '750', '131', '743', '890', '908', '616', '697', None, '605', '813', '98', '766', '900', '90', '579', '602', '617', '726', '787', '832', '899', '107', '481', '701', '535', '72', '73', '248', '395', '563', '580', '605', '682', '696', '702', '706', '719', '724', '753', '767', '781', '865', '871', '77', '569', '685', None, None, '91', '633', '747', '843', '893', '155', '572', '781', '856', '710', '916', '68', '488', '611', '739', '741', '742', '764', '804', '780', '681', '746', '355', '742', '724', '752', '588', None, '886', None, '829', '752', '523', '581', '59', '904', '733', '890', '742', '832', '709', '709', '481', '1', '120', '773', None, '838', '839', '493', '70', '399', '403', '728', '828', None, '835', '692', '686', '832', '645', '579', '252', '583', '696', '719', '752', '904', '921', '102', '408', None, '586', '323', '740', '854', '741', '474', '386', '736', '454', '879', '773', '757', '596', '782', '691', '511', '825', '447', '780', '429', '535', '658', '723', '745', '831', '893', '187', '64', '581', '742', None, '63', '618', '687', '787', None, '625', '693', '612', '763', '1', '768', '426', '765', '365', '688', None, '871', '204', '610', '807', '586', '682', '871', '859', '905', '749', '914', '590', None, '682', '777', '856', '581', '711', '811', '602', '900', '766', '79', '596', '406', '584', '831', '1', '585', '58', '585', '860', '604', '893', '577', '691', '348', '723', '864', '587']
ATP7B	NM_000053.4	NP_000044.2	424	['1069', '1266', '765', '943', '969', '766', '645', '289', '708', '691', '1176', None, '769', '977', '1220', '1319', '1353', '305', '710', '778', '779', '779', '41', '626', '869', None, '1341', '1363', '1351', '1299', '1273', '1200', None, '1186', '1173', '1151', '1101', '1088', '1003', None, None, '840', '795', '642', None, '271', '111', '105', '85', '591', '717', '1041', None, '919', '1372', None, '1177', '1099', '1064', '1035', '939', None, '768', '719', None, None, '490', '458', '35', '988', '857', '1079', '778', '1095', None, '765', '711', None, '1083', '642', None, '1288', '1279', '1241', None, '1232', '1169', '1089', '980', None, '779', '710', '667', None, '1355', '1262', '1221', None, '1025', '988', '850', None, '715', '691', '281', '188', '1052', '1000', '995', '915', None, None, '810', '778', '547', '523', '355', '332', '1373', '1267', '1186', '1146', '1064', '1043', '1029', None, '943', '711', None, None, '680', '616', '217', '1305', '784', '492', '1149', None, None, '932', '766', '511', '324', '1341', '1027', '767', None, '744', '95', None, '898', '741', '616', None, None, '133', None, '1288', '788', '649', None, '1010', '286', '544', '1175', '1105', '1079', '1055', '983', '844', '607', '567', '532', '169', '77', '74', '29', '1256', None, '614', '785', None, '1288', None, '1069', '1021', '1010', None, None, '396', '383', '1382', '1274', '1183', '1106', '1025', '836', None, None, '553', '457', None, '559', '1067', '1003', '991', '779', '604', None, '703', '1324', '932', None, '869', None, '1094', '921', '767', None, '447', '1359', '768', '1258', '1230', '816', None, None, '858', None, '1341', '1094', '1000', '936', None, '728', None, '939', None, '135', None, None, '241', '1090', None, '1146', '1399', '969', '1102', '1195', '498', '829', '513', None, '765', None, '1222', '1270', None, None, '138', '1253', '1104', '1089', '499', '489', None, '70', '1410', '1304', '1004', '988', '986', '921', '854', '843', None, None, '829', '1074', '691', '1035', '793', None, '888', '1030', '735', '894', '1410', '650', None, '301', '1095', None, None, '1018', '921', '996', '703', '951', '1069', '860', '1153', None, None, '890', '1299', '1001', '1076', '878', '1104', '713', None, '102', None, '1362', '1235', None, None, '652', None, None, None, '1010', None, '766', '493', '1020', '190', '1384', '1313', '1041', None, '707', '154', '1095', '712', '1272', '1452', '1178', None, '1452', '921', '538', None, '1275', '874', '1138', '1368', None, '943', '741', '789', '301', '141', None, '987', '187', '1251', '122', None, None, '1149', '990', '799', '496', '692', '177', '1279', '765', '1266', None, '1188', '1092', '836', None, None, '515', '1337', '1078', '1287', '1142', '1427', None, None, '155', '1063', None, None, '767', None, '1031', '1267', '228', None, None, '1321', '998', None, '760', '1363', '1387', None, '603', '1246', None, '56', '85', '734', '768', '779', '919', '1010', '1120', '1230', '1242', '1267', None, '44', None, None, '1370', '335', '488', '1376']
BTK	NM_000061.3	NP_000052.1	245	['525', '430', '13', '15', '361', None, '28', '1', '33', None, None, '113', '240', '252', '255', None, '288', '307', '334', '375', '408', '425', '502', '520', '520', None, '562', '581', '589', '591', '607', '613', '630', '636', '652', '562', None, '485', None, None, None, '587', None, '103', '157', '525', '355', '368', '602', '14', '223', '124', '527', '630', '586', '395', None, '660', None, '594', '40', '569', None, '372', '318', '288', '145', '124', '55', None, '497', '16', '498', '520', '563', '93', '563', '509', '335', '380', '80', None, '567', None, '588', '566', '566', '525', '516', '505', '441', '421', '252', '78', '11', None, None, '12', None, '527', '279', '634', '583', '417', '112', '1', None, None, '630', '571', '28', '589', '155', '112', None, None, None, '166', '56', '295', None, '100', '641', '567', None, '369', '644', '460', '368', None, None, '28', '21', '594', None, '452', '277', '598', '112', None, '199', '588', '467', '117', '102', None, '521', None, None, None, '644', '502', '512', '362', None, '281', '392', None, '42', '124', '302', '612', '598', None, None, '582', '575', '565', '563', '544', '544', None, '506', '391', '379', None, '154', '152', None, None, '359', '134', '454', '562', '91', None, '596', '509', None, '641', '371', None, '641', '631', '594', '588', None, None, None, '581', '454', '454', '297', '260', None, '165', '536', '96', '545', '151', None, '155', None, '598', '543', '316', '241', '65', '598', '597', '526', None, '358', None, None, '111', '61', '430', '541', '196', '583', '496', None, None, '589', '512', '392', '434', '373', '588', '311', '288', '627', '1', '521']
CASR	NM_000388.4	NP_000379.3	209	['795', '297', '185', '127', '227', '582', '681', '151', '118', '128', '191', '612', '773', '670', '39', '227', '138', '143', '62', '66', '788', '47', '616', '881', '648', None, '843', '185', '125', '820', '788', '604', '94', '465', '727', '180', '582', '553', '509', '559', '645', '69', '748', '812', '882', '127', '215', '221', '29', '828', '143', '680', '55', '788', '544', '25', '395', '817', '218', '584', '811', '886', '172', '610', '802', '871', '178', '680', '798', '95', '551', '193', '227', '217', '220', '220', '128', '245', '227', '392', '66', None, '168', '555', '818', None, '557', '56', '582', None, '661', '886', '218', '767', None, '127', '810', '844', '554', '839', '459', '509', '352', '361', '70', '681', '718', '173', None, '1', '530', '802', None, '670', '549', None, '832', '117', '128', '514', None, '670', '53', '719', '47', '167', '689', '64', '839', '572', None, '1', '69', '24', '1', '220', '245', '728', '352', '1', '613', None, None, '767', '675', '787', '147', '697', '173', '118', None, '133', '101', '657', None, '190', '228', '607', None, '293', '63', None, None, '368', '350', '571', '842', '636', '489', '53', '221', '326', '835', '744', '456', '581', '132', '671', '299', None, '562', None, None, '476', '608', '742', '388', '1', '787', '183', '140', '224', '296', '551', '309', '171', '164', '208', '20', '241', '742', '112', '829', '754', '802', '119', '174', '218', '812']
CBS	NM_000071.3	NP_000062.1	198	['307', '145', '114', '278', '144', '384', '539', '266', '444', None, '353', '191', '336', None, '379', '347', '257', '121', '116', '101', '125', '262', '121', '408', '379', '371', '351', '331', '323', None, '234', '176', '121', '109', '85', '54', '49', '125', None, '441', '336', '320', None, '301', '226', '148', None, None, '370', '272', None, '165', '259', None, '217', None, '288', None, '526', None, None, None, None, '228', None, None, None, None, '165', '176', None, '376', None, '384', '456', '409', '151', '52', '228', '228', '409', '143', '314', '404', '239', '213', '177', '144', '301', '336', None, '290', None, '466', '88', '290', '288', None, None, '158', None, None, '47', '52', '208', None, '114', '390', None, None, '65', '262', '359', '454', '338', '317', None, '515', '47', '148', None, '352', '128', '176', None, '256', '436', '230', None, '243', '305', None, '136', '486', None, None, '420', '440', '297', '232', None, None, '266', '346', '145', '88', '307', '262', '259', '152', '349', '336', '176', '349', '307', '158', '109', '528', None, '275', '65', '95', '371', '379', '121', '307', '226', '453', None, None, '278', None, None, None, None, '295', '410', None, '348', None, '355', None, None, '160', '279', '1', '242', '444', '153', '148', '349', '393', None, '518', '540', None, '283', '65']
CFTR	NM_000492.4	NP_000483.3	770	['493', '117', '347', '455', None, '560', '563', '542', '549', '574', '551', '553', '559', '1255', '846', '913', '1282', '458', '1316', '1303', '1162', None, '334', '851', '85', '1158', '520', '524', '1291', '311', '492', '560', '827', '1066', None, '1066', '1283', None, '347', '716', None, '1238', None, '57', '1313', '92', '347', '91', '92', '480', '338', '1089', '109', '552', '648', '710', '890', '1065', '1071', '1085', '1092', '1204', '1234', '1303', '1455', '7', '1244', '561', None, '38', '456', '466', '467', '5', None, '558', None, '923', '970', '978', '996', None, '1032', None, '124', None, '1333', None, '1427', '275', None, None, None, '1092', '60', '122', '1101', '75', '1196', None, None, None, '330', '364', '334', '336', '341', '346', '353', '356', None, None, '375', '379', '39', '4', '401', '401', None, '403', '403', None, None, '414', '44', '456', '46', None, '464', None, None, '466', '469', '479', '480', '489', '491', '493', '496', '50', '501', '502', '504', '513', '525', None, None, None, None, None, None, None, None, None, '550', None, None, None, None, None, '560', '563', '57', '57', '568', '569', '569', '569', '569', '57', '571', '572', '574', '58', '585', None, None, None, None, None, '589', '589', '60', '598', '601', '601', '604', '609', '613', '614', '618', '620', '628', '628', '637', '656', '664', '1', '673', '679', '685', '709', '715', '719', '720', '72', '730', '732', '745', '764', '776', '781', '785', '79', '792', '814', '822', '822', '823', '830', None, '831', '832', '846', '849', '85', '867', None, '88', '88', '882', None, None, '912', '913', None, None, None, '927', '970', None, '98', '979', '98', '99', None, None, '1', '1', '1005', '1006', '101', '102', '1035', '1036', '1042', None, None, '105', '1054', '1061', '1063', '1065', '1066', '1066', '1067', '1070', '1071', '1077', '1093', '109', '1098', '1098', '1098', '1100', '1101', '1102', '1104', '111', '1118', None, '1123', None, '1128', '114', '1137', '1140', '1144', '1145', '1156', None, '116', '1159', '1159', '117', '117', '117', '1177', '1182', '1186', '1204', '1206', '1206', None, '1239', None, '1240', '1244', '1246', '1247', '1249', '1254', '126', '1274', '1281', '1282', '1282', '1291', None, None, '13', '1303', '1308', '1310', None, None, '1324', '1', '1335', '14', '1371', '1375', '1382', '1390', '139', '139', '1401', '1411', '1412', None, None, '1418', '145', '1473', '1476', '149', '151', '152', '161', '162', None, None, None, None, '165', '166', '2', '175', None, '192', '193', None, None, None, '19', None, '199', '199', '199', '202', '205', '207', '216', '218', '220', '225', '227', '232', '237', None, None, '27', '27', '27', '276', '290', '30', '304', '314', '320', None, '277', '815', '900', None, None, None, None, '1098', None, '19', None, '289', None, None, '1178', None, '1381', '1424', '1092', None, '1021', '19', '549', None, '1330', '381', '407', '465', '91', '191', None, None, '1023', None, None, '507', None, '149', '279', '434', None, None, '628', None, '1433', None, None, '102', '110', None, None, '1366', '1424', None, None, '1455', None, None, '1021', None, None, '799', None, '205', None, '1', '56', None, '109', None, None, None, '317', None, '376', '434', '502', '509', '517', '520', '563', '587', '646', '826', '1011', '1036', '1037', '1063', '1098', None, None, '1243', '1247', '1249', '1309', None, '660', None, None, '15', '453', '474', '1269', '372', '442', '919', None, '464', '867', '298', None, '288', '1409', '810', '85', '1266', '270', '292', '689', '767', '852', '1280', '1351', None, None, None, None, None, '163', '1135', None, None, '1045', '1287', '474', '1283', '384', '464', None, None, None, None, '90', '247', '248', '251', '273', '483', '496', '514', '577', '621', '657', '666', '804', '809', '873', '882', '1089', '1196', '1228', '1282', '1317', '1352', '819', '1074', None, '501', '109', None, '1087', '378', '779', '973', '194', None, '194', '552', '551', '277', '103', '671', '958', '168', '311', '517', '919', '1303', '178', None, '257', '282', None, '506', '579', None, None, '1098', '913', None, None, '1270', None, '33', '403', '179', '24', '250', '1310', '563', '588', '69', None, '107', None, '1344', '558', '1183', '1143', '1265', '555', '1279', '95', '206', '1145', None, None, None, '560', '962', '563', '1248', '914', '738', '52', '578', '1410', None, '509', '192', '1145', None, '1470', '570', '559', '1036', None, None, '380', '647', '527', None, None, None, None, '356', None, '451', '1302', '829', '385', None, None, '1247', '952', None, None, None, '1439', '1094', '311', '110', '1098', '590', '1182', None, '1046', '458', None, '1061', None, '512', '466', '525', '483', '510', '520', '521', '476', '503', '497', '479', '372', None, '1073', '1104', None, None, '216', '681', None, '1075', '1125', None, '1314', None, '402', None, '1064', None, '449', '153', '652', None, '190', None, '509', '577', '1165', '79', '84', '60', '29', '471', '485', '490', '472', '471', '520', '492', '491', '507', '604', None, '853', None, '341', None, '237', None, '314', None, '313', None, '359', '361', '461', '461', '512', None, '571', '63', '67', '679', '688', '746', '762', '812', '872', None, None, '921', '1038', None, '1061', '1069', '1078', '1104', '1239', '1276', '1303', None, None, None, '1423', None, None, '202', '15']
CFTR	NM_000492.3	NP_000483.3	2	[None, None]

#### save output to file "gene_transcript_changes.tsv"

In [ ]:
with open("gene_transcript_changes.tsv", "w") as outfile:

    # Write header
    print("gene\ttranscript\tprotein\tchanges", file=outfile)
    for gene in loci:
        transcripts = vartranscripts_filtered[gene]
        for transcript in transcripts:
            sites, wilds, muts = get_all_changes(gene, transcript, True)
            print(gene, transcript, translation[transcript], len(sites), sep="\t", file=outfile)
print("Results saved to 'gene_transcript_changes.tsv'")

Results saved to 'gene_transcript_changes.tsv'

### STEP 7A
##### Examine sequence alignment (aln_match/) for potential CPDs 
##### this code is drawn from 'get_variables_sites', I modified it to fit genes with multiple reference proteins

In [203]:
import os
from Bio import AlignIO

variable = {}
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        protein = translation[transcript]
        #print(transcript)
        print(protein)

        fasta_file = os.path.join("fasta_match", f"{gene}_{protein}_match.fasta")
        aln_file = os.path.join("aln_match", f"{gene}_{protein}_match.aln")

        #print(protein, fasta_file, aln_file)

        fasta = None
        for record in SeqIO.parse(fasta_file, "fasta"):
            recordid = record.description.split()[0]
            if recordid == protein:
                fasta = record
                break
        if fasta is None:
            raise ValueError(f"{protein} not found in {fasta_file}")    
        #print(fasta)

        align = AlignIO.read(aln_file, "fasta")
        aln = None
        for record in align:
            if record.id == protein:
                aln = record
                break
        if aln is None:
            raise ValueError(f"{protein} not found in {aln_file}")
        #print(aln)
        #print("gene\tHum\tAln\tsite\tvariable_amino_acids")
        
        alni = get_aln_positions(gene, protein)
        L = len(fasta)
        for i in range(L):
            j = alni[i]
            counts = pd.Series(list(align[:, j])).value_counts()
            alleles = counts.index.tolist()
            remove_element(alleles, "-")
            n = len(alleles)
            remove_element(alleles, fasta[i])
            if n > 1:
                variable.setdefault(transcript, {})
                variable[transcript][i + 1] = alleles


                #variable.update({i + 1: alleles})
                #variable.update({transcript: {i + 1: alleles}})
                #variable.update({transcript: alleles})
                #variable[(transcript, i + 1)] = alleles
                #if verbose:
                
                print(gene, transcript, protein, i + 1, j + 1, fasta[i], alleles, sep="\t")

    #variable.update({transcript: get_variable_sites(gene, protein, False)})

NP_000024.2
ABCD1	NM_000033.4	NP_000024.2	6	6	R	['T', 'M']
ABCD1	NM_000033.4	NP_000024.2	9	9	P	['T', 'S']
ABCD1	NM_000033.4	NP_000024.2	10	10	W	['S']
ABCD1	NM_000033.4	NP_000024.2	12	12	G	['V']
ABCD1	NM_000033.4	NP_000024.2	13	13	N	['S', 'T']
ABCD1	NM_000033.4	NP_000024.2	14	14	T	['R']
ABCD1	NM_000033.4	NP_000024.2	21	21	L	['V']
ABCD1	NM_000033.4	NP_000024.2	25	25	A	['T']
ABCD1	NM_000033.4	NP_000024.2	29	29	A	['V']
ABCD1	NM_000033.4	NP_000024.2	32	32	V	['I', 'A']
ABCD1	NM_000033.4	NP_000024.2	35	35	L	['W']
ABCD1	NM_000033.4	NP_000024.2	39	39	C	['Y']
ABCD1	NM_000033.4	NP_000024.2	42	42	P	['L', 'S', 'V']
ABCD1	NM_000033.4	NP_000024.2	43	43	A	['V']
ABCD1	NM_000033.4	NP_000024.2	45	45	G	['D', 'V', 'S']
ABCD1	NM_000033.4	NP_000024.2	46	46	L	['P', 'S', 'T']
ABCD1	NM_000033.4	NP_000024.2	47	47	Q	['P']
ABCD1	NM_000033.4	NP_000024.2	48	48	A	['V', 'G']
ABCD1	NM_000033.4	NP_000024.2	49	49	P	['L']
ABCD1	NM_000033.4	NP_000024.2	50	50	A	['T']
ABCD1	NM_000033.4	NP_000024.2	51	51	G	['R', 'K']
ABCD1	NM_000033.4	NP_000024.2	52	52	E	['D']
ABCD1	NM_000033.4	NP_000024.2	53	53	P	['S']
ABCD1	NM_000033.4	NP_000024.2	54	54	T	['A', 'M']
ABCD1	NM_000033.4	NP_000024.2	56	56	E	['D']
ABCD1	NM_000033.4	NP_000024.2	57	57	A	['V', 'S']
ABCD1	NM_000033.4	NP_000024.2	58	58	S	['P']
ABCD1	NM_000033.4	NP_000024.2	60	60	V	['A', 'S']
ABCD1	NM_000033.4	NP_000024.2	61	61	A	['T', 'S']
ABCD1	NM_000033.4	NP_000024.2	62	62	A	['V', 'T']
ABCD1	NM_000033.4	NP_000024.2	65	65	A	['T']
ABCD1	NM_000033.4	NP_000024.2	67	67	M	['V']
ABCD1	NM_000033.4	NP_000024.2	70	70	V	['I']
ABCD1	NM_000033.4	NP_000024.2	76	76	L	['M']
ABCD1	NM_000033.4	NP_000024.2	86	86	V	['I']
ABCD1	NM_000033.4	NP_000024.2	87	87	L	['V']
ABCD1	NM_000033.4	NP_000024.2	95	95	A	['V']
ABCD1	NM_000033.4	NP_000024.2	99	99	A	['S', 'G']
ABCD1	NM_000033.4	NP_000024.2	100	100	A	['T']
ABCD1	NM_000033.4	NP_000024.2	128	128	R	['Q']
ABCD1	NM_000033.4	NP_000024.2	132	132	W	['R']
ABCD1	NM_000033.4	NP_000024.2	139	139	L	['F']
ABCD1	NM_000033.4	NP_000024.2	147	147	V	['I']
ABCD1	NM_000033.4	NP_000024.2	159	159	A	['T']
ABCD1	NM_000033.4	NP_000024.2	172	172	R	['S']
ABCD1	NM_000033.4	NP_000024.2	176	176	S	['A']
ABCD1	NM_000033.4	NP_000024.2	195	195	Q	['H']
ABCD1	NM_000033.4	NP_000024.2	231	231	R	['Q']
ABCD1	NM_000033.4	NP_000024.2	236	236	R	['H']
ABCD1	NM_000033.4	NP_000024.2	261	261	F	['C']
ABCD1	NM_000033.4	NP_000024.2	288	288	A	['S']
ABCD1	NM_000033.4	NP_000024.2	300	300	E	['K']
ABCD1	NM_000033.4	NP_000024.2	308	311	R	['H', 'Q']
ABCD1	NM_000033.4	NP_000024.2	312	315	D	['N', 'R', 'E']
ABCD1	NM_000033.4	NP_000024.2	360	363	S	['T']
ABCD1	NM_000033.4	NP_000024.2	361	364	D	['A']
ABCD1	NM_000033.4	NP_000024.2	362	365	A	['S', 'P', 'Q']
ABCD1	NM_000033.4	NP_000024.2	365	368	V	['M', 'T']
ABCD1	NM_000033.4	NP_000024.2	366	369	K	['R']
ABCD1	NM_000033.4	NP_000024.2	367	370	K	['H']
ABCD1	NM_000033.4	NP_000024.2	368	371	A	['S']
ABCD1	NM_000033.4	NP_000024.2	370	373	L	['V']
ABCD1	NM_000033.4	NP_000024.2	372	375	K	['E']
ABCD1	NM_000033.4	NP_000024.2	373	376	K	['R', 'E']
ABCD1	NM_000033.4	NP_000024.2	374	377	E	['G', 'K']
ABCD1	NM_000033.4	NP_000024.2	375	378	E	['K']
ABCD1	NM_000033.4	NP_000024.2	376	379	E	['K']
ABCD1	NM_000033.4	NP_000024.2	387	390	I	['K']
ABCD1	NM_000033.4	NP_000024.2	388	391	A	['K']
ABCD1	NM_000033.4	NP_000024.2	389	392	R	['K']
ABCD1	NM_000033.4	NP_000024.2	399	402	I	['T']
ABCD1	NM_000033.4	NP_000024.2	402	405	I	['K']
ABCD1	NM_000033.4	NP_000024.2	403	406	M	['K']
ABCD1	NM_000033.4	NP_000024.2	404	407	S	['K']
ABCD1	NM_000033.4	NP_000024.2	415	418	Y	['K']
ABCD1	NM_000033.4	NP_000024.2	416	419	T	['K']
ABCD1	NM_000033.4	NP_000024.2	417	420	A	['K']
ABCD1	NM_000033.4	NP_000024.2	427	430	E	['A']
ABCD1	NM_000033.4	NP_000024.2	429	432	V	['K']
ABCD1	NM_000033.4	NP_000024.2	430	433	Q	['H', 'K', 'R']
ABCD1	NM_000033.4	NP_000024.2	431	434	R	['H', 'K']
ABCD1	NM_000033.4	NP_000024.2	432	435	C	['S']
ABCD1	NM_000033.4	NP_000024.2	433	436	H	['R']
ABCD1	NM_000033.4	NP_000024.2	435	438	K	['R']
ABCD1	NM_000033.4	NP_000024.2	437	440	P	['A']
ABCD1	NM_000033.4	NP_000024.2	438	441	R	['G']
ABCD1	NM_000033.4	NP_000024.2	440	443	L	['P']
ABCD1	NM_000033.4	NP_000024.2	443	446	A	['T', 'E', 'S']
ABCD1	NM_000033.4	NP_000024.2	444	447	Q	['K']
ABCD1	NM_000033.4	NP_000024.2	445	448	A	['P', 'K', 'L']
ABCD1	NM_000033.4	NP_000024.2	446	449	G	['N']
ABCD1	NM_000033.4	NP_000024.2	447	450	S	['P']
ABCD1	NM_000033.4	NP_000024.2	449	452	T	['A']
ABCD1	NM_000033.4	NP_000024.2	450	453	I	['M']
ABCD1	NM_000033.4	NP_000024.2	451	454	G	['V', 'A']
ABCD1	NM_000033.4	NP_000024.2	452	455	R	['Q']
ABCD1	NM_000033.4	NP_000024.2	453	456	S	['A', 'P']
ABCD1	NM_000033.4	NP_000024.2	456	459	R	['H', 'Y']
ABCD1	NM_000033.4	NP_000024.2	457	460	V	['M', 'L']
ABCD1	NM_000033.4	NP_000024.2	458	461	E	['D']
ABCD1	NM_000033.4	NP_000024.2	460	463	P	['A', 'S']
ABCD1	NM_000033.4	NP_000024.2	464	467	R	['Q', 'L']
ABCD1	NM_000033.4	NP_000024.2	469	472	D	['E']
ABCD1	NM_000033.4	NP_000024.2	470	473	V	['K']
ABCD1	NM_000033.4	NP_000024.2	471	474	E	['K']
ABCD1	NM_000033.4	NP_000024.2	472	475	Q	['K']
ABCD1	NM_000033.4	NP_000024.2	482	485	V	['I']
ABCD1	NM_000033.4	NP_000024.2	484	487	P	['K']
ABCD1	NM_000033.4	NP_000024.2	485	488	S	['T', 'A', 'K']
ABCD1	NM_000033.4	NP_000024.2	486	489	G	['K']
ABCD1	NM_000033.4	NP_000024.2	491	494	A	['T']
ABCD1	NM_000033.4	NP_000024.2	495	498	I	['M']
ABCD1	NM_000033.4	NP_000024.2	496	499	R	['K']
ABCD1	NM_000033.4	NP_000024.2	498	501	E	['K']
ABCD1	NM_000033.4	NP_000024.2	509	512	N	['K']
ABCD1	NM_000033.4	NP_000024.2	510	513	G	['K']
ABCD1	NM_000033.4	NP_000024.2	511	514	C	['K']
ABCD1	NM_000033.4	NP_000024.2	512	515	G	['K']
ABCD1	NM_000033.4	NP_000024.2	519	522	I	['V']
ABCD1	NM_000033.4	NP_000024.2	521	524	G	['S']
ABCD1	NM_000033.4	NP_000024.2	524	527	W	['K']
ABCD1	NM_000033.4	NP_000024.2	525	528	P	['K']
ABCD1	NM_000033.4	NP_000024.2	526	529	T	['K']
ABCD1	NM_000033.4	NP_000024.2	527	530	Y	['N']
ABCD1	NM_000033.4	NP_000024.2	532	535	Y	['C']
ABCD1	NM_000033.4	NP_000024.2	538	541	R	['Q']
ABCD1	NM_000033.4	NP_000024.2	539	542	M	['K']
ABCD1	NM_000033.4	NP_000024.2	540	543	F	['K']
ABCD1	NM_000033.4	NP_000024.2	541	544	Y	['N']
ABCD1	NM_000033.4	NP_000024.2	549	552	S	['T']
ABCD1	NM_000033.4	NP_000024.2	555	558	D	['E', 'N']
ABCD1	NM_000033.4	NP_000024.2	556	559	Q	['K']
ABCD1	NM_000033.4	NP_000024.2	557	560	V	['K']
ABCD1	NM_000033.4	NP_000024.2	558	561	I	['N']
ABCD1	NM_000033.4	NP_000024.2	564	567	E	['A', 'G']
ABCD1	NM_000033.4	NP_000024.2	567	570	Q	['R']
ABCD1	NM_000033.4	NP_000024.2	570	573	G	['K']
ABCD1	NM_000033.4	NP_000024.2	571	574	Y	['H', 'K']
ABCD1	NM_000033.4	NP_000024.2	572	575	S	['K']
ABCD1	NM_000033.4	NP_000024.2	574	577	Q	['R', 'K']
ABCD1	NM_000033.4	NP_000024.2	575	578	D	['H']
ABCD1	NM_000033.4	NP_000024.2	578	581	A	['T']
ABCD1	NM_000033.4	NP_000024.2	582	585	V	['I']
ABCD1	NM_000033.4	NP_000024.2	584	587	H	['K']
ABCD1	NM_000033.4	NP_000024.2	585	588	L	['K']
ABCD1	NM_000033.4	NP_000024.2	586	589	H	['K', 'Q']
ABCD1	NM_000033.4	NP_000024.2	587	590	H	['N']
ABCD1	NM_000033.4	NP_000024.2	598	601	M	['V']
ABCD1	NM_000033.4	NP_000024.2	599	602	C	['R']
ABCD1	NM_000033.4	NP_000024.2	604	607	V	['I']
ABCD1	NM_000033.4	NP_000024.2	611	614	Q	['K']
ABCD1	NM_000033.4	NP_000024.2	612	615	R	['K']
ABCD1	NM_000033.4	NP_000024.2	613	616	I	['K']
ABCD1	NM_000033.4	NP_000024.2	623	626	P	['K']
ABCD1	NM_000033.4	NP_000024.2	635	638	V	['E']
ABCD1	NM_000033.4	NP_000024.2	636	639	S	['K']
ABCD1	NM_000033.4	NP_000024.2	637	640	I	['K']
ABCD1	NM_000033.4	NP_000024.2	638	641	D	['N']
ABCD1	NM_000033.4	NP_000024.2	649	652	D	['E']
ABCD1	NM_000033.4	NP_000024.2	650	653	A	['K', 'T']
ABCD1	NM_000033.4	NP_000024.2	651	654	G	['K']
ABCD1	NM_000033.4	NP_000024.2	652	655	I	['K']
ABCD1	NM_000033.4	NP_000024.2	661	664	P	['S']
ABCD1	NM_000033.4	NP_000024.2	674	690	D	['K']
ABCD1	NM_000033.4	NP_000024.2	675	691	G	['K']
ABCD1	NM_000033.4	NP_000024.2	676	692	E	['Q', 'K']
ABCD1	NM_000033.4	NP_000024.2	677	693	G	['S']
ABCD1	NM_000033.4	NP_000024.2	678	694	G	['S']
ABCD1	NM_000033.4	NP_000024.2	682	698	E	['Q']
ABCD1	NM_000033.4	NP_000024.2	686	702	S	['P']
ABCD1	NM_000033.4	NP_000024.2	688	704	A	['T', 'V']
ABCD1	NM_000033.4	NP_000024.2	703	719	L	['K']
ABCD1	NM_000033.4	NP_000024.2	704	720	A	['K']
ABCD1	NM_000033.4	NP_000024.2	705	721	G	['K']
ABCD1	NM_000033.4	NP_000024.2	709	725	M	['I']
ABCD1	NM_000033.4	NP_000024.2	711	727	R	['Q']
ABCD1	NM_000033.4	NP_000024.2	714	730	Q	['R']
ABCD1	NM_000033.4	NP_000024.2	717	733	C	['R']
ABCD1	NM_000033.4	NP_000024.2	724	740	V	['M']
ABCD1	NM_000033.4	NP_000024.2	727	743	A	['G']
ABCD1	NM_000033.4	NP_000024.2	728	744	H	['Q', 'E']
ABCD1	NM_000033.4	NP_000024.2	729	745	V	['P', 'A', 'L', 'S']
ABCD1	NM_000033.4	NP_000024.2	730	746	P	['L']
ABCD1	NM_000033.4	NP_000024.2	731	747	A	['V', 'S']
ABCD1	NM_000033.4	NP_000024.2	732	748	P	['L', 'Q']
ABCD1	NM_000033.4	NP_000024.2	733	749	S	['G', 'R', 'W']
ABCD1	NM_000033.4	NP_000024.2	734	750	P	['S', 'C', 'L']
ABCD1	NM_000033.4	NP_000024.2	735	751	Q	['E', 'M']
ABCD1	NM_000033.4	NP_000024.2	736	752	G	['D']
ABCD1	NM_000033.4	NP_000024.2	738	754	G	['A', 'S']
ABCD1	NM_000033.4	NP_000024.2	739	756	G	['S', 'A', 'V']
ABCD1	NM_000033.4	NP_000024.2	740	757	L	['I', 'R', 'A']
ABCD1	NM_000033.4	NP_000024.2	741	758	Q	['A', 'R', 'P', 'H']
ABCD1	NM_000033.4	NP_000024.2	742	759	G	['N', 'D', 'S']
ABCD1	NM_000033.4	NP_000024.2	743	760	A	['V', 'T']
ABCD1	NM_000033.4	NP_000024.2	744	761	S	['Q']
ABCD1	NM_000033.4	NP_000024.2	745	762	T	['S']
NP_000469.3
ALPL	NM_000478.6	NP_000469.3	2	10	I	['P']
ALPL	NM_000478.6	NP_000469.3	3	11	S	['W', 'M']
ALPL	NM_000478.6	NP_000469.3	4	12	P	['A', 'S']
ALPL	NM_000478.6	NP_000469.3	5	13	F	['A']
ALPL	NM_000478.6	NP_000469.3	6	14	L	['A', 'V']
ALPL	NM_000478.6	NP_000469.3	7	15	V	['L', 'I', 'S']
ALPL	NM_000478.6	NP_000469.3	9	17	A	['V', 'G']
ALPL	NM_000478.6	NP_000469.3	10	37	I	['V', 'M']
ALPL	NM_000478.6	NP_000469.3	11	38	G	['S', 'K']
ALPL	NM_000478.6	NP_000469.3	12	39	T	['S', 'D']
ALPL	NM_000478.6	NP_000469.3	13	40	C	['E']
ALPL	NM_000478.6	NP_000469.3	15	42	T	['A', 'M', 'S']
ALPL	NM_000478.6	NP_000469.3	16	43	N	['S', 'H', 'D']
ALPL	NM_000478.6	NP_000469.3	17	44	S	['C', 'E']
ALPL	NM_000478.6	NP_000469.3	18	45	L	['F', 'K']
ALPL	NM_000478.6	NP_000469.3	19	46	V	['G']
ALPL	NM_000478.6	NP_000469.3	20	47	P	['K']
ALPL	NM_000478.6	NP_000469.3	21	48	E	['G']
ALPL	NM_000478.6	NP_000469.3	22	49	K	['M', 'R']
ALPL	NM_000478.6	NP_000469.3	23	50	E	['L', 'S']
ALPL	NM_000478.6	NP_000469.3	24	51	K	['G', 'S']
ALPL	NM_000478.6	NP_000469.3	25	52	D	['T']
ALPL	NM_000478.6	NP_000469.3	26	53	P	['T']
ALPL	NM_000478.6	NP_000469.3	27	54	K	['E', 'G', 'T']
ALPL	NM_000478.6	NP_000469.3	28	55	Y	['S', 'T', 'W']
ALPL	NM_000478.6	NP_000469.3	29	56	W	['L']
ALPL	NM_000478.6	NP_000469.3	30	57	R	['E', 'S']
ALPL	NM_000478.6	NP_000469.3	31	58	D	['N', 'R', 'G']
ALPL	NM_000478.6	NP_000469.3	32	59	Q	['R']
ALPL	NM_000478.6	NP_000469.3	33	60	A	['R']
ALPL	NM_000478.6	NP_000469.3	34	61	Q	['A']
ALPL	NM_000478.6	NP_000469.3	35	62	E	['Q', 'K']
ALPL	NM_000478.6	NP_000469.3	36	63	T	['V']
ALPL	NM_000478.6	NP_000469.3	38	69	K	['R']
ALPL	NM_000478.6	NP_000469.3	39	70	Y	['H', 'N']
ALPL	NM_000478.6	NP_000469.3	40	71	A	['C']
ALPL	NM_000478.6	NP_000469.3	42	73	E	['G', 'K']
ALPL	NM_000478.6	NP_000469.3	43	74	L	['M']
ALPL	NM_000478.6	NP_000469.3	44	75	Q	['S']
ALPL	NM_000478.6	NP_000469.3	45	76	K	['E', 'R']
ALPL	NM_000478.6	NP_000469.3	46	77	L	['I']
ALPL	NM_000478.6	NP_000469.3	47	78	N	['D']
ALPL	NM_000478.6	NP_000469.3	48	79	T	['A']
ALPL	NM_000478.6	NP_000469.3	49	92	N	['G']
ALPL	NM_000478.6	NP_000469.3	50	93	V	['A']
ALPL	NM_000478.6	NP_000469.3	51	94	A	['V']
ALPL	NM_000478.6	NP_000469.3	52	95	K	['R']
ALPL	NM_000478.6	NP_000469.3	53	96	N	['D']
ALPL	NM_000478.6	NP_000469.3	54	97	V	['P']
ALPL	NM_000478.6	NP_000469.3	55	98	I	['H']
ALPL	NM_000478.6	NP_000469.3	56	99	M	['S']
ALPL	NM_000478.6	NP_000469.3	58	101	L	['K']
ALPL	NM_000478.6	NP_000469.3	59	102	G	['K']
ALPL	NM_000478.6	NP_000469.3	60	106	D	['S']
ALPL	NM_000478.6	NP_000469.3	61	107	G	['P']
ALPL	NM_000478.6	NP_000469.3	62	108	M	['F']
ALPL	NM_000478.6	NP_000469.3	63	109	G	['S']
ALPL	NM_000478.6	NP_000469.3	64	110	V	['R']
ALPL	NM_000478.6	NP_000469.3	65	111	S	['T']
ALPL	NM_000478.6	NP_000469.3	66	112	T	['P']
ALPL	NM_000478.6	NP_000469.3	67	113	V	['L']
ALPL	NM_000478.6	NP_000469.3	68	114	T	['L']
ALPL	NM_000478.6	NP_000469.3	69	115	A	['P']
ALPL	NM_000478.6	NP_000469.3	70	116	A	['T', 'S']
ALPL	NM_000478.6	NP_000469.3	71	117	R	['L']
ALPL	NM_000478.6	NP_000469.3	72	118	I	['A']
ALPL	NM_000478.6	NP_000469.3	74	120	K	['M', 'T']
ALPL	NM_000478.6	NP_000469.3	76	122	Q	['S']
ALPL	NM_000478.6	NP_000469.3	77	123	L	['C']
ALPL	NM_000478.6	NP_000469.3	78	124	H	['S', 'R']
ALPL	NM_000478.6	NP_000469.3	79	125	H	['P', 'N']
ALPL	NM_000478.6	NP_000469.3	80	126	N	['R']
ALPL	NM_000478.6	NP_000469.3	81	127	P	['T']
ALPL	NM_000478.6	NP_000469.3	82	128	G	['R']
ALPL	NM_000478.6	NP_000469.3	85	138	T	['P']
ALPL	NM_000478.6	NP_000469.3	86	139	R	['K', 'M', 'H']
ALPL	NM_000478.6	NP_000469.3	87	140	L	['S']
ALPL	NM_000478.6	NP_000469.3	88	141	E	['S']
ALPL	NM_000478.6	NP_000469.3	89	142	M	['A']
ALPL	NM_000478.6	NP_000469.3	90	143	D	['G']
ALPL	NM_000478.6	NP_000469.3	91	144	K	['H']
ALPL	NM_000478.6	NP_000469.3	92	145	F	['M']
ALPL	NM_000478.6	NP_000469.3	93	155	P	['T', 'S']
ALPL	NM_000478.6	NP_000469.3	94	156	F	['L', 'S']
ALPL	NM_000478.6	NP_000469.3	95	157	V	['L', 'C', 'M']
ALPL	NM_000478.6	NP_000469.3	96	158	A	['S']
ALPL	NM_000478.6	NP_000469.3	97	159	L	['H', 'W']
ALPL	NM_000478.6	NP_000469.3	98	160	S	['L', 'E']
ALPL	NM_000478.6	NP_000469.3	99	161	K	['Q', 'M']
ALPL	NM_000478.6	NP_000469.3	137	199	S	['T']
ALPL	NM_000478.6	NP_000469.3	138	200	R	['Q']
ALPL	NM_000478.6	NP_000469.3	152	214	R	['H']
ALPL	NM_000478.6	NP_000469.3	209	271	M	['V']
ALPL	NM_000478.6	NP_000469.3	213	275	R	['K']
ALPL	NM_000478.6	NP_000469.3	214	276	D	['N']
ALPL	NM_000478.6	NP_000469.3	216	278	D	['E']
ALPL	NM_000478.6	NP_000469.3	231	293	K	['R']
ALPL	NM_000478.6	NP_000469.3	238	300	S	['I', 'M', 'T']
ALPL	NM_000478.6	NP_000469.3	251	313	D	['N']
ALPL	NM_000478.6	NP_000469.3	253	315	V	['I']
ALPL	NM_000478.6	NP_000469.3	254	316	D	['N']
ALPL	NM_000478.6	NP_000469.3	255	317	T	['I', 'V']
ALPL	NM_000478.6	NP_000469.3	258	320	S	['N']
ALPL	NM_000478.6	NP_000469.3	262	324	R	['K', 'T']
ALPL	NM_000478.6	NP_000469.3	263	325	Y	['H', 'R', 'N', 'D']
ALPL	NM_000478.6	NP_000469.3	266	343	S	['T']
ALPL	NM_000478.6	NP_000469.3	269	346	I	['V']
ALPL	NM_000478.6	NP_000469.3	273	350	T	['S']
ALPL	NM_000478.6	NP_000469.3	276	353	L	['M']
ALPL	NM_000478.6	NP_000469.3	277	354	T	['A', 'K', 'N']
ALPL	NM_000478.6	NP_000469.3	279	356	D	['N']
ALPL	NM_000478.6	NP_000469.3	280	357	P	['L']
ALPL	NM_000478.6	NP_000469.3	281	358	H	['Y', 'N', 'S']
ALPL	NM_000478.6	NP_000469.3	282	359	N	['T', 'A']
ALPL	NM_000478.6	NP_000469.3	295	372	M	['L']
ALPL	NM_000478.6	NP_000469.3	296	373	Q	['E']
ALPL	NM_000478.6	NP_000469.3	304	381	V	['L', 'M']
ALPL	NM_000478.6	NP_000469.3	310	387	S	['T']
ALPL	NM_000478.6	NP_000469.3	314	391	V	['T', 'E', 'K', 'G']
ALPL	NM_000478.6	NP_000469.3	318	395	Q	['R']
ALPL	NM_000478.6	NP_000469.3	319	396	I	['V']
ALPL	NM_000478.6	NP_000469.3	321	398	R	['Q', 'K']
ALPL	NM_000478.6	NP_000469.3	325	402	K	['R']
ALPL	NM_000478.6	NP_000469.3	357	434	R	['Q']
ALPL	NM_000478.6	NP_000469.3	360	437	G	['E']
ALPL	NM_000478.6	NP_000469.3	361	438	Q	['L', 'R']
ALPL	NM_000478.6	NP_000469.3	363	440	G	['D']
ALPL	NM_000478.6	NP_000469.3	364	441	S	['N', 'I', 'D', 'T']
ALPL	NM_000478.6	NP_000469.3	365	442	L	['M', 'I']
ALPL	NM_000478.6	NP_000469.3	368	445	S	['L', 'T']
ALPL	NM_000478.6	NP_000469.3	369	446	E	['Q', 'G']
ALPL	NM_000478.6	NP_000469.3	402	479	L	['V']
ALPL	NM_000478.6	NP_000469.3	425	502	G	['D']
ALPL	NM_000478.6	NP_000469.3	433	510	M	['T']
ALPL	NM_000478.6	NP_000469.3	438	515	H	['N']
ALPL	NM_000478.6	NP_000469.3	451	528	H	['Y']
ALPL	NM_000478.6	NP_000469.3	463	540	S	['A']
ALPL	NM_000478.6	NP_000469.3	480	557	V	['I']
ALPL	NM_000478.6	NP_000469.3	488	565	A	['S']
ALPL	NM_000478.6	NP_000469.3	490	567	I	['V']
ALPL	NM_000478.6	NP_000469.3	494	571	L	['V']
ALPL	NM_000478.6	NP_000469.3	495	572	G	['D', 'N']
ALPL	NM_000478.6	NP_000469.3	498	575	A	['T']
ALPL	NM_000478.6	NP_000469.3	499	576	P	['H', 'Q', 'S', 'R']
ALPL	NM_000478.6	NP_000469.3	502	579	S	['A', 'P']
ALPL	NM_000478.6	NP_000469.3	504	581	G	['R', 'S']
ALPL	NM_000478.6	NP_000469.3	505	582	S	['G', 'N']
ALPL	NM_000478.6	NP_000469.3	506	583	L	['P']
ALPL	NM_000478.6	NP_000469.3	508	585	A	['P', 'L']
ALPL	NM_000478.6	NP_000469.3	509	586	G	['V']
ALPL	NM_000478.6	NP_000469.3	510	587	P	['A']
ALPL	NM_000478.6	NP_000469.3	514	591	A	['P', 'L', 'S']
ALPL	NM_000478.6	NP_000469.3	518	595	Y	['F', 'L']
ALPL	NM_000478.6	NP_000469.3	519	596	P	['S']
ALPL	NM_000478.6	NP_000469.3	520	597	L	['M']
ALPL	NM_000478.6	NP_000469.3	521	598	S	['R', 'G']
ALPL	NM_000478.6	NP_000469.3	522	599	V	['I', 'S', 'H', 'M']
NP_000035.2
AR	NM_000044.6	NP_000035.2	2	2	E	['D']
AR	NM_000044.6	NP_000035.2	4	4	Q	['L']
AR	NM_000044.6	NP_000035.2	12	12	P	['T']
AR	NM_000044.6	NP_000035.2	14	14	P	['Q']
AR	NM_000044.6	NP_000035.2	39	39	P	['T', 'S']
AR	NM_000044.6	NP_000035.2	42	42	P	['L']
AR	NM_000044.6	NP_000035.2	45	45	A	['V']
AR	NM_000044.6	NP_000035.2	50	50	P	['V']
AR	NM_000044.6	NP_000035.2	51	51	G	['S']
AR	NM_000044.6	NP_000035.2	53	53	S	['R', 'G', 'H']
AR	NM_000044.6	NP_000035.2	68	68	Q	['L']
AR	NM_000044.6	NP_000035.2	69	69	Q	['P', 'L']
AR	NM_000044.6	NP_000035.2	70	70	Q	['L', 'R']
AR	NM_000044.6	NP_000035.2	72	72	Q	['P']
AR	NM_000044.6	NP_000035.2	73	73	Q	['P', 'L']
AR	NM_000044.6	NP_000035.2	74	74	Q	['P', 'H']
AR	NM_000044.6	NP_000035.2	75	75	Q	['P', 'N']
AR	NM_000044.6	NP_000035.2	76	76	Q	['P', 'R']
AR	NM_000044.6	NP_000035.2	77	77	Q	['P', 'H']
AR	NM_000044.6	NP_000035.2	78	78	Q	['P']
AR	NM_000044.6	NP_000035.2	79	79	Q	['P']
AR	NM_000044.6	NP_000035.2	81	89	E	['Q', 'H']
AR	NM_000044.6	NP_000035.2	85	93	R	['P', 'S']
AR	NM_000044.6	NP_000035.2	87	95	Q	['R']
AR	NM_000044.6	NP_000035.2	88	96	Q	['E']
AR	NM_000044.6	NP_000035.2	89	97	Q	['R']
AR	NM_000044.6	NP_000035.2	90	98	Q	['K']
AR	NM_000044.6	NP_000035.2	91	103	Q	['H']
AR	NM_000044.6	NP_000035.2	92	105	G	['V']
AR	NM_000044.6	NP_000035.2	93	106	E	['D']
AR	NM_000044.6	NP_000035.2	94	107	D	['N', 'K']
AR	NM_000044.6	NP_000035.2	95	108	G	['S']
AR	NM_000044.6	NP_000035.2	99	112	A	['V']
AR	NM_000044.6	NP_000035.2	100	113	H	['Q']
AR	NM_000044.6	NP_000035.2	101	114	R	['S', 'G']
AR	NM_000044.6	NP_000035.2	103	116	G	['N']
AR	NM_000044.6	NP_000035.2	104	117	P	['R']
AR	NM_000044.6	NP_000035.2	105	118	T	['R']
AR	NM_000044.6	NP_000035.2	109	122	V	['A']
AR	NM_000044.6	NP_000035.2	112	125	E	['G']
AR	NM_000044.6	NP_000035.2	114	127	Q	['R']
AR	NM_000044.6	NP_000035.2	115	128	Q	['E']
AR	NM_000044.6	NP_000035.2	116	129	P	['V', 'H']
AR	NM_000044.6	NP_000035.2	119	132	P	['Q']
AR	NM_000044.6	NP_000035.2	121	134	S	['T']
AR	NM_000044.6	NP_000035.2	123	136	L	['P', 'T']
AR	NM_000044.6	NP_000035.2	124	137	E	['D']
AR	NM_000044.6	NP_000035.2	127	140	P	['H']
AR	NM_000044.6	NP_000035.2	128	141	E	['D', 'K']
AR	NM_000044.6	NP_000035.2	129	142	R	['S']
AR	NM_000044.6	NP_000035.2	130	143	G	['S', 'R']
AR	NM_000044.6	NP_000035.2	136	149	G	['E', 'A']
AR	NM_000044.6	NP_000035.2	137	150	A	['V']
AR	NM_000044.6	NP_000035.2	138	151	A	['S']
AR	NM_000044.6	NP_000035.2	139	152	V	['A', 'T', 'F']
AR	NM_000044.6	NP_000035.2	140	153	A	['V']
AR	NM_000044.6	NP_000035.2	142	155	S	['G']
AR	NM_000044.6	NP_000035.2	146	159	P	['Q']
AR	NM_000044.6	NP_000035.2	149	162	L	['P']
AR	NM_000044.6	NP_000035.2	150	163	P	['S']
AR	NM_000044.6	NP_000035.2	153	166	P	['S']
AR	NM_000044.6	NP_000035.2	154	167	D	['E']
AR	NM_000044.6	NP_000035.2	155	168	E	['D']
AR	NM_000044.6	NP_000035.2	156	169	D	['N']
AR	NM_000044.6	NP_000035.2	160	173	A	['V']
AR	NM_000044.6	NP_000035.2	165	178	S	['A']
AR	NM_000044.6	NP_000035.2	173	186	G	['S']
AR	NM_000044.6	NP_000035.2	175	188	S	['N']
AR	NM_000044.6	NP_000035.2	180	193	D	['Q']
AR	NM_000044.6	NP_000035.2	182	195	K	['D']
AR	NM_000044.6	NP_000035.2	183	196	D	['K']
AR	NM_000044.6	NP_000035.2	184	197	I	['V']
AR	NM_000044.6	NP_000035.2	185	198	L	['T']
AR	NM_000044.6	NP_000035.2	186	199	S	['N']
AR	NM_000044.6	NP_000035.2	189	202	S	['G', 'P']

In [222]:
# variants= variants sites from clinvar
v= variants.keys()
print(len(v))
v
variants['NM_000492.4'].keys()

41

dict_keys(['gene', 'protein', 'sites', 'wilds', 'muts'])

In [199]:
# variable = variant sites from orthologs alignment

vv= variable.keys()
print(len(vv))
#variable['NM_000492.3']
print(vv)
variable['NM_000492.4']
#results

41
dict_keys(['NM_000033.4', 'NM_000478.6', 'NM_000044.6', 'NM_000053.4', 'NM_000061.3', 'NM_000388.4', 'NM_000071.3', 'NM_000492.4', 'NM_000492.3', 'NM_000397.4', 'NM_019616.4', 'NM_000131.5', 'NM_000131.4', 'NM_000132.4', 'NM_000133.4', 'NM_000402.4', 'NM_001360016.2', 'NM_001042351.3', 'NM_000155.4', 'NM_000157.4', 'NM_001097642.3', 'NM_000166.6', 'NM_000518.5', 'NM_000518.4', 'NM_000194.2', 'NM_000194.3', 'NM_000206.3', 'NM_000238.4', 'NM_000218.3', 'NM_001278116.2', 'NM_000527.4', 'NM_000527.5', 'NM_000530.8', 'NM_000257.4', 'NM_000372.5', 'NM_000277.3', 'NM_000303.3', 'NM_000539.3', 'NM_000546.6', 'NM_000371.4', 'NM_000552.5'])

{1: ['W', 'G', 'N', 'P', 'F', 'Q'],
 2: ['R', 'K', 'A', 'S'],
 3: ['P', 'G', 'E', 'D', 'K', 'N'],
 4: ['N', 'T', 'L', 'A'],
 5: ['Q', 'D', 'V', 'K'],
 6: ['V', 'I', 'T', 'C'],
 7: ['K', 'N', 'Y'],
 8: ['I', 'R', 'G', 'T', 'E'],
 9: ['S', 'C', 'Y', 'V', 'N', 'L'],
 10: ['G', 'N', 'I', 'F', 'A'],
 11: ['C', 'A', 'S', 'F', 'L'],
 12: ['L', 'S', 'I'],
 13: ['A', 'R', 'V', 'F'],
 14: ['S', 'G', 'R', 'F'],
 15: ['V', 'F', 'S'],
 16: ['Y', 'L'],
 17: ['R', 'G'],
 18: ['Q', 'P', 'A', 'L'],
 23: ['V'],
 25: ['K', 'S'],
 33: ['Q'],
 34: ['S'],
 43: ['A', 'S'],
 48: ['Y'],
 68: ['R'],
 80: ['K'],
 82: ['T'],
 87: ['L', 'I'],
 97: ['I'],
 115: ['V', 'T', 'A'],
 125: ['V'],
 132: ['T', 'V'],
 133: ['L'],
 135: ['M'],
 164: ['I'],
 181: ['I'],
 183: ['F'],
 204: ['V'],
 209: ['M', 'T'],
 215: ['L'],
 217: ['D'],
 233: ['I'],
 236: ['V'],
 238: ['S'],
 246: ['E'],
 250: ['K'],
 254: ['Q'],
 256: ['N'],
 269: ['L'],
 283: ['N'],
 284: ['I'],
 332: ['V', 'A'],
 388: ['M'],
 405: ['I'],
 408: ['F'],
 410: ['Q'],
 412: ['V'],
 415: ['E'],
 416: ['S'],
 417: ['S', 'D'],
 418: ['S', 'K'],
 420: ['E', 'N'],
 421: ['I', 'A'],
 423: ['S', 'K'],
 424: ['D'],
 426: ['N'],
 427: ['N'],
 433: ['L'],
 434: ['A', 'G'],
 438: ['A'],
 442: ['R'],
 443: ['E'],
 445: ['S'],
 455: ['T'],
 470: ['M'],
 478: ['L'],
 492: ['P'],
 504: ['D'],
 510: ['I'],
 515: ['C'],
 525: ['R'],
 531: ['A'],
 539: ['T'],
 577: ['H'],
 591: ['I', 'A'],
 592: ['T'],
 593: ['Q', 'R'],
 612: ['R'],
 623: ['I'],
 624: ['I'],
 637: ['R'],
 647: ['Y', 'F'],
 649: ['Y'],
 653: ['Y'],
 655: ['S'],
 667: ['R'],
 668: ['H'],
 671: ['F'],
 675: ['S'],
 676: ['A', 'T', 'S'],
 677: ['I'],
 679: ['R'],
 680: ['N'],
 682: ['R', 'M'],
 684: ['R'],
 685: ['S'],
 686: ['P'],
 693: ['I', 'L'],
 704: ['S'],
 708: ['V', 'M', 'L'],
 711: ['I'],
 713: ['V'],
 715: ['P'],
 720: ['P'],
 721: ['I'],
 722: ['S'],
 728: ['P', 'F'],
 729: ['E'],
 730: ['D'],
 732: ['S', 'F', 'V'],
 736: ['V'],
 739: ['I'],
 747: ['V'],
 748: ['T'],
 751: ['H'],
 752: ['S'],
 753: ['N', 'G'],
 754: ['M'],
 755: ['F'],
 756: ['N', 'K'],
 757: ['A'],
 759: ['L'],
 760: ['A', 'M', 'P'],
 761: ['F'],
 763: ['G', 'V'],
 764: ['Q'],
 772: ['M'],
 775: ['Q'],
 777: ['I'],
 778: ['T'],
 780: ['D'],
 781: ['P', 'H'],
 782: ['S'],
 783: ['V', 'G'],
 784: ['Q'],
 785: ['Q'],
 786: ['I', 'M'],
 787: ['N'],
 788: ['A'],
 789: ['I'],
 790: ['A'],
 791: ['P'],
 794: ['M'],
 796: ['I'],
 797: ['V'],
 799: ['P'],
 800: ['T'],
 802: ['F'],
 803: ['S', 'H'],
 805: ['M'],
 814: ['R'],
 816: ['S'],
 817: ['S', 'C'],
 828: ['Y'],
 834: ['C'],
 837: ['V', 'A'],
 838: ['D'],
 839: ['N', 'G'],
 848: ['I'],
 853: ['V', 'L'],
 854: ['A'],
 855: ['L', 'I'],
 856: ['N'],
 858: ['T'],
 860: ['S'],
 861: ['L'],
 868: ['A'],
 872: ['V'],
 876: ['V', 'I'],
 877: ['F'],
 879: ['A'],
 880: ['L', 'M'],
 882: ['S', 'L'],
 883: ['F', 'I'],
 884: ['F'],
 885: ['R', 'D'],
 886: ['K', 'R'],
 887: ['A', 'I', 'S'],
 888: ['R'],
 889: ['P', 'F', 'A', 'R'],
 890: ['Y', 'H'],
 891: ['N', 'S'],
 892: ['E', 'N'],
 895: ['N', 'G'],
 897: ['Y', 'I', 'A', 'T', 'V'],
 898: ['G'],
 899: ['A', 'P', 'G', 'T', 'I'],
 901: ['G', 'S'],
 903: ['S'],
 904: ['P'],
 909: ['R', 'N'],
 912: ['A'],
 915: ['L'],
 916: ['L'],
 929: ['L'],
 932: ['I'],
 940: ['S'],
 947: ['M'],
 950: ['N', 'R'],
 951: ['R'],
 958: ['R', 'H'],
 966: ['A', 'M'],
 991: ['V'],
 994: ['L'],
 995: ['V'],
 997: ['V'],
 998: ['C'],
 1004: ['T'],
 1005: ['V'],
 1006: ['V'],
 1009: ['S'],
 1017: ['L'],
 1024: ['A'],
 1025: ['S', 'T'],
 1027: ['V'],
 1028: ['L', 'I'],
 1031: ['G'],
 1035: ['H'],
 1046: ['A'],
 1049: ['T'],
 1088: ['S'],
 1106: ['V'],
 1109: ['M', 'V'],
 1113: ['V'],
 1119: ['V'],
 1124: ['N'],
 1125: ['S'],
 1127: ['F'],
 1128: ['T', 'A', 'Q', 'E'],
 1129: ['I', 'N'],
 1130: ['P'],
 1131: ['Q'],
 1132: ['S'],
 1135: ['I'],
 1137: ['K'],
 1138: ['S'],
 1139: ['E'],
 1140: ['F'],
 1141: ['G', 'P'],
 1142: ['S'],
 1143: ['S'],
 1144: ['T'],
 1145: ['I'],
 1146: ['Y'],
 1147: ['L'],
 1148: ['A'],
 1149: ['G'],
 1150: ['Q'],
 1151: ['W'],
 1152: ['H'],
 1153: ['S'],
 1154: ['S'],
 1155: ['F'],
 1156: ['Q'],
 1161: ['R'],
 1163: ['I'],
 1169: ['I'],
 1171: ['K'],
 1173: ['D', 'C'],
 1174: ['R'],
 1175: ['S'],
 1177: ['R'],
 1179: ['I', 'V'],
 1180: ['T'],
 1181: ['A', 'L'],
 1182: ['S'],
 1183: ['R'],
 1184: ['D'],
 1185: ['C'],
 1186: ['P', 'R', 'H'],
 1187: ['V'],
 1188: ['L'],
 1190: ['L'],
 1192: ['V'],
 1193: ['F'],
 1194: ['K'],
 1196: ['P', 'L'],
 1198: ['M', 'A'],
 1199: ['E'],
 1201: ['S'],
 1202: ['Y'],
 1203: ['V'],
 1212: ['I'],
 1213: ['R'],
 1216: ['S'],
 1218: ['R'],
 1220: ['I', 'V', 'L'],
 1221: ['D'],
 1222: ['S'],
 1225: ['P'],
 1226: ['V'],
 1233: ['L'],
 1248: ['A'],
 1255: ['L'],
 1257: ['L'],
 1262: ['Q'],
 1264: ['K'],
 1266: ['D'],
 1268: ['H'],
 1275: ['N'],
 1277: ['V'],
 1297: ['T'],
 1317: ['E'],
 1326: ['A', 'T'],
 1340: ['L'],
 1344: ['Y', 'S'],
 1348: ['R'],
 1379: ['I'],
 1380: ['A'],
 1387: ['A'],
 1393: ['V'],
 1394: ['N'],
 1395: ['S'],
 1408: ['S'],
 1412: ['R', 'G'],
 1419: ['S'],
 1420: ['N', 'R'],
 1422: ['Q'],
 1427: ['L'],
 1432: ['S'],
 1434: ['K'],
 1435: ['N'],
 1438: ['Q'],
 1441: ['L'],
 1443: ['H', 'L'],
 1445: ['E'],
 1447: ['M'],
 1451: ['S'],
 1452: ['R', 'L'],
 1454: ['H'],
 1458: ['Y', 'H', 'R', 'G', 'Q', 'S'],
 1460: ['T', 'A'],
 1461: ['Q', 'R'],
 1462: ['S'],
 1463: ['P'],
 1465: ['T'],
 1466: ['S'],
 1471: ['M'],
 1474: ['D'],
 1476: ['H'],
 1477: ['E']}

#### This is same as 7A
##### Can be ignored after the first run, this just stores the output as 'results', and saves as "Variable_sites_match_30JUL.tsv"

In [135]:
results = []

for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        protein = translation[transcript]
        fasta_file = os.path.join("fasta_match", f"{gene}_{protein}_match.fasta")
        aln_file = os.path.join("aln_match", f"{gene}_{protein}_match.aln")

        print(f"\n{gene}")
        print(transcript, protein)

        fasta = None

        for record in SeqIO.parse(fasta_file, "fasta"):
            if record.description.split()[0] == protein:
                fasta = record
                break
        if fasta is None:
            raise ValueError(f"{protein} not found")


        align = AlignIO.read(aln_file, "fasta")
        aln = None
        for record in align:
            if record.id == protein:
                aln = record
                break
        if aln is None:
            raise ValueError(f"{protein} not found")


        alni = get_aln_positions(gene, protein)

        for i in range(len(fasta)):
            j = alni[i]
            counts = pd.Series(list(align[:, j])).value_counts()
            alleles = counts.index.tolist()
            remove_element(alleles, "-")
            n = len(alleles)
            remove_element(alleles, fasta.seq[i])

            if n > 1:
                results.append({
                    "gene": gene,
                    "transcript": transcript,
                    "protein": protein,
                    "human_site": i + 1,
                    "alignment_site": j + 1,
                    "reference_aa": str(fasta.seq[i]),
                    "variable_amino_acids": ",".join(alleles)
                })

variable_df = pd.DataFrame(results)
variable_df.to_csv(
    "Variable_sites_match_30JUL.tsv",
    sep="\t",
    index= False)

ABCD1
NM_000033.4 NP_000024.2

ALPL
NM_000478.6 NP_000469.3

AR
NM_000044.6 NP_000035.2

ATP7B
NM_000053.4 NP_000044.2

BTK
NM_000061.3 NP_000052.1

CASR
NM_000388.4 NP_000379.3

CBS
NM_000071.3 NP_000062.1

CFTR
NM_000492.4 NP_000483.3

CFTR
NM_000492.3 NP_000483.3

CYBB
NM_000397.4 NP_000388.2

F7
NM_019616.4 NP_062562.1

F7
NM_000131.5 NP_000122.1

F7
NM_000131.4 NP_000122.1

F8
NM_000132.4 NP_000123.1

F9
NM_000133.4 NP_000124.1

G6PD
NM_000402.4 NP_000393.4

G6PD
NM_001360016.2 NP_001035810.1

G6PD
NM_001042351.3 NP_001035810.1

GALT
NM_000155.4 NP_000146.2

GBA1
NM_000157.4 NP_000148.2

GJB1
NM_001097642.3 NP_000157.1

GJB1
NM_000166.6 NP_000157.1

HBB
NM_000518.5 NP_000509.1

HBB
NM_000518.4 NP_000509.1

HPRT1
NM_000194.2 NP_000185.1

HPRT1
NM_000194.3 NP_000185.1

IL2RG
NM_000206.3 NP_000197.1

KCNH2
NM_000238.4 NP_000229.1

KCNQ1
NM_000218.3 NP_000209.2

L1CAM
NM_001278116.2 NP_000416.1

LDLR
NM_000527.4 NP_000518.1

LDLR
NM_000527.5 NP_000518.1

MPZ
NM_000530.8 NP_000521.2

MYH7
NM_000257.4 NP_000248.2

TYR
NM_000372.5 NP_000363.1

PAH
NM_000277.3 NP_000268.1

PMM2
NM_000303.3 NP_000294.1

RHO
NM_000539.3 NP_000530.1

TP53
NM_000546.6 NP_000537.3

TTR
NM_000371.4 NP_000362.1

VWF
NM_000552.5 NP_000543.3

In [201]:
run kondrashov

## Identify putative CPDs

### STEP 8
#### Next we compare and dentify pathogenic variants () that are nevertheless observed as natural amino acid substitutions in the homologs alignment
### save output to file 'invalidated_CPDs_match_....tsv'

In [245]:
with open("invalidated_CPDs_match_JUL31.tsv", "w") as outfile:
    
    print('gene\ttranscript\tprotein \tsite\twild\tmut\tvar')
    final_transcripts = variants.keys()
    for gene in loci:
        transcripts = vartranscripts_filtered[gene]
        for transcript in transcripts:
            if transcript in final_transcripts:
                sites = variants[transcript]['sites']
                wilds = variants[transcript]['wilds']
                muts = variants[transcript]['muts']
                protein = variants[transcript]['protein']
                #print(gene, transcript, sites, wilds, muts)
                tmp_variable = variable[transcript]
                variable_sites = tmp_variable.keys()
                n= len(sites)
                for i in range(n):
                    if sites[i] is None:
                        continue
                    site = int(sites[i])
                    #print(sites)
                    if (site in variable_sites) and (muts[i] in tmp_variable[site]):
                        print(gene, transcript, protein, site, wilds[i], muts[i], tmp_variable[site], sep= '\t')
                        print(gene, transcript, protein, site, wilds[i], muts[i], ",".join(tmp_variable[site]), sep="\t", file=outfile)
        
print("Results saved to invalidated_CPDs_match_JUL31.tsv")

gene	transcript	protein 	site	wild	mut	var
ALPL	NM_000478.6	NP_000469.3	51	A	V	['V']
ALPL	NM_000478.6	NP_000469.3	82	G	R	['R']
ALPL	NM_000478.6	NP_000469.3	82	G	R	['R']
ALPL	NM_000478.6	NP_000469.3	85	T	P	['P']
ALPL	NM_000478.6	NP_000469.3	93	P	S	['T', 'S']
ALPL	NM_000478.6	NP_000469.3	295	M	L	['L']
ATP7B	NM_000053.4	NP_000044.2	969	R	Q	['Q']
ATP7B	NM_000053.4	NP_000044.2	335	G	E	['E', 'R']
CBS	NM_000071.3	NP_000062.1	65	H	L	['L']
CFTR	NM_000492.4	NP_000483.3	13	S	F	['A', 'R', 'V', 'F']
F8	NM_000132.4	NP_000123.1	2038	N	S	['K', 'S', 'H']
F8	NM_000132.4	NP_000123.1	2157	N	S	['S']
F9	NM_000133.4	NP_000124.1	75	R	Q	['Q']
G6PD	NM_000402.4	NP_000393.4	3	R	W	['W', 'M', 'E', 'T', 'G']
GALT	NM_000155.4	NP_000146.2	223	R	H	['H', 'C']
GBA1	NM_000157.4	NP_000148.2	502	R	C	['C']
GBA1	NM_000157.4	NP_000148.2	535	R	H	['H']
GBA1	NM_000157.4	NP_000148.2	227	N	S	['S']
GBA1	NM_000157.4	NP_000148.2	351	W	C	['C']
GBA1	NM_000157.4	NP_000148.2	350	H	R	['R']
GBA1	NM_000157.4	NP_000148.2	416	G	S	['S']
GBA1	NM_000157.4	NP_000148.2	426	P	L	['L']
GBA1	NM_000157.4	NP_000148.2	230	V	G	['G']
GBA1	NM_000157.4	NP_000148.2	351	W	C	['C']
GBA1	NM_000157.4	NP_000148.2	391	V	A	['A']
HBB	NM_000518.4	NP_000509.1	102	E	Q	['Q']
KCNQ1	NM_000218.3	NP_000209.2	114	L	P	['M', 'P']
KCNQ1	NM_000218.3	NP_000209.2	115	E	G	['K', 'G', 'L', 'Q']
KCNQ1	NM_000218.3	NP_000209.2	125	Y	D	['F', 'D', 'A', 'S']
KCNQ1	NM_000218.3	NP_000209.2	117	P	S	['S', 'E', 'A', 'R']
KCNQ1	NM_000218.3	NP_000209.2	119	G	S	['S', 'N']
LDLR	NM_000527.5	NP_000518.1	46	C	S	['S']
LDLR	NM_000527.5	NP_000518.1	583	H	D	['D']
LDLR	NM_000527.5	NP_000518.1	579	D	G	['G']
LDLR	NM_000527.5	NP_000518.1	88	R	K	['K']
LDLR	NM_000527.5	NP_000518.1	301	D	V	['H', 'V']
PAH	NM_000277.3	NP_000268.1	164	I	T	['T']
PAH	NM_000277.3	NP_000268.1	176	R	Q	['Q']
PAH	NM_000277.3	NP_000268.1	413	R	H	['H']
PAH	NM_000277.3	NP_000268.1	156	A	G	['E', 'R', 'G']
PMM2	NM_000303.3	NP_000294.1	237	T	R	['R']
PMM2	NM_000303.3	NP_000294.1	239	R	S	['K', 'S']
TTR	NM_000371.4	NP_000362.1	142	V	I	['I']
TTR	NM_000371.4	NP_000362.1	127	I	V	['V']
TTR	NM_000371.4	NP_000362.1	82	E	K	['K']
TTR	NM_000371.4	NP_000362.1	77	G	R	['R']
TTR	NM_000371.4	NP_000362.1	126	T	I	['I']
VWF	NM_000552.5	NP_000543.3	528	N	S	['S']
Results saved to invalidated_CPDs_match_JUL31.tsv

In [ ]:
# Same code as above except without writing to file, just printing to console

print('gene\ttranscript\tprotein \tsite\twild\tmut\tvar')
final_transcripts = variants.keys()
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        if transcript in final_transcripts:
            sites = variants[transcript]['sites']
            wilds = variants[transcript]['wilds']
            muts = variants[transcript]['muts']
            protein = variants[transcript]['protein']
            #print(gene, transcript, sites, wilds, muts)
            tmp_variable = variable[transcript]
            variable_sites = tmp_variable.keys()
            n= len(sites)
            for i in range(n):
                if sites[i] is None:
                    continue
                site = int(sites[i])
                #print(sites)
                if (site in variable_sites) and (muts[i] in tmp_variable[site]):
                    print(gene, transcript, protein, site, wilds[i], muts[i], tmp_variable[site], sep= '\t')

gene	transcript	protein 	site	wild	mut	var
ALPL	NM_000478.6	NP_000469.3	51	A	V	['V']
ALPL	NM_000478.6	NP_000469.3	82	G	R	['R']
ALPL	NM_000478.6	NP_000469.3	82	G	R	['R']
ALPL	NM_000478.6	NP_000469.3	85	T	P	['P']
ALPL	NM_000478.6	NP_000469.3	93	P	S	['T', 'S']
ALPL	NM_000478.6	NP_000469.3	295	M	L	['L']
ATP7B	NM_000053.4	NP_000044.2	969	R	Q	['Q']
ATP7B	NM_000053.4	NP_000044.2	335	G	E	['E', 'R']
CBS	NM_000071.3	NP_000062.1	65	H	L	['L']
CFTR	NM_000492.4	NP_000483.3	13	S	F	['A', 'R', 'V', 'F']
F8	NM_000132.4	NP_000123.1	2038	N	S	['K', 'S', 'H']
F8	NM_000132.4	NP_000123.1	2157	N	S	['S']
F9	NM_000133.4	NP_000124.1	75	R	Q	['Q']
G6PD	NM_000402.4	NP_000393.4	3	R	W	['W', 'M', 'E', 'T', 'G']
GALT	NM_000155.4	NP_000146.2	223	R	H	['H', 'C']
GBA1	NM_000157.4	NP_000148.2	502	R	C	['C']
GBA1	NM_000157.4	NP_000148.2	535	R	H	['H']
GBA1	NM_000157.4	NP_000148.2	227	N	S	['S']
GBA1	NM_000157.4	NP_000148.2	351	W	C	['C']
GBA1	NM_000157.4	NP_000148.2	350	H	R	['R']
GBA1	NM_000157.4	NP_000148.2	416	G	S	['S']
GBA1	NM_000157.4	NP_000148.2	426	P	L	['L']
GBA1	NM_000157.4	NP_000148.2	230	V	G	['G']
GBA1	NM_000157.4	NP_000148.2	351	W	C	['C']
GBA1	NM_000157.4	NP_000148.2	391	V	A	['A']
HBB	NM_000518.4	NP_000509.1	102	E	Q	['Q']
KCNQ1	NM_000218.3	NP_000209.2	114	L	P	['M', 'P']
KCNQ1	NM_000218.3	NP_000209.2	115	E	G	['K', 'G', 'L', 'Q']
KCNQ1	NM_000218.3	NP_000209.2	125	Y	D	['F', 'D', 'A', 'S']
KCNQ1	NM_000218.3	NP_000209.2	117	P	S	['S', 'E', 'A', 'R']
KCNQ1	NM_000218.3	NP_000209.2	119	G	S	['S', 'N']
LDLR	NM_000527.5	NP_000518.1	46	C	S	['S']
LDLR	NM_000527.5	NP_000518.1	583	H	D	['D']
LDLR	NM_000527.5	NP_000518.1	579	D	G	['G']
LDLR	NM_000527.5	NP_000518.1	88	R	K	['K']
LDLR	NM_000527.5	NP_000518.1	301	D	V	['H', 'V']
PAH	NM_000277.3	NP_000268.1	164	I	T	['T']
PAH	NM_000277.3	NP_000268.1	176	R	Q	['Q']
PAH	NM_000277.3	NP_000268.1	413	R	H	['H']
PAH	NM_000277.3	NP_000268.1	156	A	G	['E', 'R', 'G']
PMM2	NM_000303.3	NP_000294.1	237	T	R	['R']
PMM2	NM_000303.3	NP_000294.1	239	R	S	['K', 'S']
TTR	NM_000371.4	NP_000362.1	142	V	I	['I']
TTR	NM_000371.4	NP_000362.1	127	I	V	['V']
TTR	NM_000371.4	NP_000362.1	82	E	K	['K']
TTR	NM_000371.4	NP_000362.1	77	G	R	['R']
TTR	NM_000371.4	NP_000362.1	126	T	I	['I']
VWF	NM_000552.5	NP_000543.3	528	N	S	['S']

## Look at particular sites

The following command allows you to double check particular sites.  It now also outputs which site each species has.

In [307]:
run kondrashov

In [306]:
get_alleles('ATP7B', translation['NM_000053.4'], 335, True)

     Gene: ATP7B
    Human: 335 G
Alignment: 415 G
G    29
E     4
R     1
Name: count, dtype: int64

G XP_053419999.1 Nycticebus coucang
G XP_012668202.1 Otolemur garnettii
E XP_012638109.2 Microcebus murinus
E XP_012504526.1 Propithecus coquereli
E XP_069323793.1 Eulemur rufifrons
E XP_045423253.1 Lemur catta
R XP_008070482.1 Carlito syrichta
G XP_011920046.1 Cercocebus atys
G XP_023043183.1 Piliocolobus tephrosceles
G XP_033033524.1 Trachypithecus francoisi
G XP_011794322.1 Colobus angolensis palliatus
G XP_017713762.1 Rhinopithecus bieti
G XP_010351222.1 Rhinopithecus roxellana
G XP_037842588.2 Chlorocebus sabaeus
G XP_050622214.1 Macaca thibetana thibetana
G XP_011754956.2 Macaca nemestrina
G XP_025220038.1 Theropithecus gelada
G XP_011844134.1 Mandrillus leucophaeus
G XP_028693404.2 Macaca mulatta
G XP_065389351.1 Macaca fascicularis
G XP_017806752.3 Papio anubis
G XP_058293894.1 Hylobates moloch
G XP_030669295.1 Nomascus leucogenys
G XP_054302292.2 Pongo pygmaeus
G XP_024086846.3 Pongo abelii
G NP_000044.2 Homo sapiens
G XP_016780791.3 Pan troglodytes
G XP_024781039.4 Pan paniscus
G XP_004054587.3 Gorilla gorilla gorilla
G XP_035153347.2 Callithrix jacchus
G XP_003927227.1 Saimiri boliviensis
G XP_032150439.1 Sapajus apella
G XP_017397954.1 Cebus imitator
G XP_012321637.1 Aotus nancymaae

(True,
 335,
 'G',
 G    29
 E     4
 R     1
 Name: count, dtype: int64)

In [308]:
get_alleles('F8', translation['NM_000132.4'], 2157, True)

     Gene: F8
    Human: 2157 N
Alignment: 2174 N
N    29
-     2
S     1
Name: count, dtype: int64

N XP_053435824.1 Nycticebus coucang
N XP_003802782.1 Otolemur garnettii
N XP_075855879.1 Microcebus murinus
N XP_012517042.1 Propithecus coquereli
N XP_069319343.1 Eulemur rufifrons
N XP_045394744.1 Lemur catta
S XP_064227599.1 Aotus nancymaae
N XP_078219844.1 Callithrix jacchus
N XP_003943974.1 Saimiri boliviensis
N XP_032121190.1 Sapajus apella
N XP_017376032.2 Cebus imitator
N XP_026307119.1 Piliocolobus tephrosceles
N XP_072869373.1 Chlorocebus sabaeus
N XP_005595091.3 Macaca fascicularis
N XP_014984059.2 Macaca mulatta
N XP_050631365.1 Macaca thibetana thibetana
N XP_011716754.2 Macaca nemestrina
N XP_011889280.1 Cercocebus atys
N XP_025227752.1 Theropithecus gelada
- XP_031516314.1 Papio anubis
N XP_011818598.1 Colobus angolensis palliatus
N XP_033057806.1 Trachypithecus francoisi
N XP_010351130.1 Rhinopithecus roxellana
N XP_003279379.1 Nomascus leucogenys
N XP_055125143.1 Symphalangus syndactylus
- XP_058297352.1 Hylobates moloch
N XP_054327961.1 Pongo pygmaeus
N XP_024096329.1 Pongo abelii
N NP_000123.1 Homo sapiens
N XP_004065205.1 Gorilla gorilla gorilla
N XP_003317837.1 Pan troglodytes
N XP_003810005.2 Pan paniscus

(True,
 2157,
 'N',
 N    29
 -     2
 S     1
 Name: count, dtype: int64)

In [265]:
get_alleles('GALT', translation['NM_000155.4'], 223, True)

     Gene: GALT
    Human: 223 R
Alignment: 239 R
R    27
H     4
C     2
Name: count, dtype: int64

R XP_070934053.1 Macaca nemestrina
C XP_008068994.1 Carlito syrichta
R XP_053425949.1 Nycticebus coucang
R XP_003800307.1 Otolemur garnettii
R XP_012625552.1 Microcebus murinus
R XP_012512299.1 Propithecus coquereli
R XP_069330487.1 Eulemur rufifrons
R XP_045418884.1 Lemur catta
R XP_009186860.2 Papio anubis
H XP_033094120.1 Trachypithecus francoisi
H XP_011924618.1 Cercocebus atys
R XP_011805904.1 Colobus angolensis palliatus
R XP_011835461.1 Mandrillus leucophaeus
R XP_023059053.1 Piliocolobus tephrosceles
R XP_017747545.1 Rhinopithecus bieti
R XP_073873350.1 Macaca fascicularis
R XP_028690927.1 Macaca mulatta
R XP_025214557.1 Theropithecus gelada
R XP_050616753.1 Macaca thibetana thibetana
R XP_012318674.1 Aotus nancymaae
R XP_003732050.1 Callithrix jacchus
R XP_010330019.1 Saimiri boliviensis
R XP_032155758.1 Sapajus apella
R XP_017398495.1 Cebus imitator
R NP_000146.2 Homo sapiens
C XP_001163419.2 Pan troglodytes
R XP_003829858.2 Pan paniscus
H XP_004048011.1 Gorilla gorilla gorilla
R XP_054376965.2 Pongo abelii
R XP_054358709.1 Pongo pygmaeus
H XP_003263433.1 Nomascus leucogenys
R XP_032019924.1 Hylobates moloch
R XP_055149891.1 Symphalangus syndactylus

(True,
 223,
 'R',
 R    27
 H     4
 C     2
 Name: count, dtype: int64)

In [322]:
get_alleles('LDLR', translation['NM_000527.5'], 301, True)

     Gene: LDLR
    Human: 301 D
Alignment: 343 D
D    32
H     1
V     1
Name: count, dtype: int64

D XP_021573646.1 Carlito syrichta
D XP_020139390.1 Microcebus murinus
D XP_064237923.1 Aotus nancymaae
D XP_002761791.3 Callithrix jacchus
D XP_039321728.1 Saimiri boliviensis
D XP_032107631.1 Sapajus apella
D XP_037583448.1 Cebus imitator
D XP_031790584.1 Piliocolobus tephrosceles
D XP_011810343.1 Colobus angolensis palliatus
D XP_030676686.1 Nomascus leucogenys
D XP_055094492.1 Symphalangus syndactylus
D XP_032025606.1 Hylobates moloch
D XP_054319927.2 Pongo pygmaeus
D XP_063576005.1 Pongo abelii
D NP_000518.1 Homo sapiens
D XP_018871450.1 Gorilla gorilla gorilla
D XP_034800281.1 Pan paniscus
D XP_024206933.1 Pan troglodytes
H XP_011884149.1 Cercocebus atys
D XP_033056644.1 Trachypithecus francoisi
D XP_017724974.1 Rhinopithecus bieti
D XP_030791739.1 Rhinopithecus roxellana
D XP_072873051.1 Chlorocebus sabaeus
D XP_025222238.1 Theropithecus gelada
D XP_031515756.1 Papio anubis
D XP_011850139.1 Mandrillus leucophaeus
D XP_014978386.3 Macaca mulatta
D XP_005588053.3 Macaca fascicularis
D XP_070942884.1 Macaca nemestrina
D XP_053439240.1 Nycticebus coucang
D XP_023373820.1 Otolemur garnettii
V XP_012496802.1 Propithecus coquereli
D XP_069334632.1 Eulemur rufifrons
D XP_045402139.1 Lemur catta

(True,
 301,
 'D',
 D    32
 H     1
 V     1
 Name: count, dtype: int64)

# Validate CPDs

Here we test whether a putative CPD is valid by investigating the vicinity of the sequence, 10 amino acids on either side of the site.

This function pulls out the species and protein IDs showing a particular amino acid at a site.

In [309]:
run kondrashov

In [336]:
get_species_with_allele('ATP7B', translation['NM_000053.4'], 335, 'E')

[('Microcebus murinus', 'XP_012638109.2'),
 ('Propithecus coquereli', 'XP_012504526.1'),
 ('Eulemur rufifrons', 'XP_069323793.1'),
 ('Lemur catta', 'XP_045423253.1')]

In [323]:
get_species_with_allele('GALT', translation['NM_000155.4'], 223, 'H')

[('Trachypithecus francoisi', 'XP_033094120.1'),
 ('Cercocebus atys', 'XP_011924618.1'),
 ('Gorilla gorilla gorilla', 'XP_004048011.1'),
 ('Nomascus leucogenys', 'XP_003263433.1')]

This function compares the human and nonhuman sequences in the -10 / +10 range.  The output at the bottom shows the numbers of:

* differences between the sequences
* gaps 
* sites out of range

For example, the GBA1 site at the end means that 9 sites are outside the range.  The GALT sequence shows some aminoacid differences.

In [324]:
run kondrashov

In [334]:
local_compare_to_human('ATP7B', translation['NM_000053.4'], 335, 'XP_008070482.1')

-10 V V
-9 S S
-8 L L
-7 P P
-6 D D
-5 G E
-4 A A
-3 E E
-2 G G
-1 S S
0 G R
1 T T
2 D G
3 H H
4 R E
5 S S
6 S S
7 S S
8 S C
9 H H
10 S T

(5, 0, 0)

In [327]:
local_compare_to_human('GALT', translation['NM_000155.4'], 223, 'XP_033094120.1')

-10 H H
-9 G G
-8 E E
-7 P P
-6 L L
-5 L L
-4 M M
-3 E E
-2 Y Y
-1 S S
0 R H
1 Q Q
2 E E
3 L L
4 L L
5 R R
6 K K
7 E E
8 R R
9 L L
10 V V

(0, 0, 0)

This function spits out a site by site comparison of the human and nonhuman sequences.  Only the differences are shown.

In [335]:
global_compare_to_human('ATP7B', translation['NM_000053.4'], 'XP_008070482.1', True)

199 A T
224 A T
226 R P
229 L I
241 P S
245 K Q
257 G S
262 G C
267 V M
268 A T
269 T I
272 V I
288 D G
289 R V
292 N G
297 I V
298 S N
299 M I
307 S R
318 C S
337 E G
340 A P
350 A T
374 K T
375 V I
384 V A
389 S G
412 N T
422 S N
424 V M
427 L R
435 E G
445 P L
446 L S
447 S A
465 H Q
473 I V
474 D E
479 K M
493 L P
497 S N
510 K Q
517 S N
520 A S
540 G E
545 G R
547 D G
549 R E
553 S C
555 S T
557 G A
559 P L
560 P Q
565 Q P
567 T M
572 L V
573 I L
574 A T
581 A V
585 H Q
590 M L
593 Q Y
594 L R
601 S T
609 A G
610 T V
613 Y H
614 N D
627 I V
634 A V
637 V I
638 S P
663 S N
664 C Y
669 L A
673 S N
682 T P
683 D G
685 T V
687 T V
695 H R
696 T A
697 G E
698 R G
701 A S
704 A N
705 P A
706 D G
707 I H
708 L S
709 A S
712 P L
713 Q P
716 R G
785 V I
799 I V
802 D S
810 E R
814 F L
824 V I
832 D L
834 N D
838 T I
864 A T
888 I V
907 A T
943 P S
949 Q E
994 R K
1052 L I
1097 G D
1100 V I
1143 A S
1200 M I
1221 R K
1315 G V
1321 P T
1404 S G
1408 E G
1409 A V
1428 V T
1429 P S
1484 T I
1570 N S
1590 N M
1602 V I
1684 Q R
1716 R W
1724 H R
1736 H Y
1743 W Q
1770 K R
1781 D S
1791 G D

{199: ('A', 'T'),
 224: ('A', 'T'),
 226: ('R', 'P'),
 229: ('L', 'I'),
 241: ('P', 'S'),
 245: ('K', 'Q'),
 257: ('G', 'S'),
 262: ('G', 'C'),
 267: ('V', 'M'),
 268: ('A', 'T'),
 269: ('T', 'I'),
 272: ('V', 'I'),
 288: ('D', 'G'),
 289: ('R', 'V'),
 292: ('N', 'G'),
 297: ('I', 'V'),
 298: ('S', 'N'),
 299: ('M', 'I'),
 307: ('S', 'R'),
 318: ('C', 'S'),
 337: ('E', 'G'),
 340: ('A', 'P'),
 350: ('A', 'T'),
 374: ('K', 'T'),
 375: ('V', 'I'),
 384: ('V', 'A'),
 389: ('S', 'G'),
 412: ('N', 'T'),
 422: ('S', 'N'),
 424: ('V', 'M'),
 427: ('L', 'R'),
 435: ('E', 'G'),
 445: ('P', 'L'),
 446: ('L', 'S'),
 447: ('S', 'A'),
 465: ('H', 'Q'),
 473: ('I', 'V'),
 474: ('D', 'E'),
 479: ('K', 'M'),
 493: ('L', 'P'),
 497: ('S', 'N'),
 510: ('K', 'Q'),
 517: ('S', 'N'),
 520: ('A', 'S'),
 540: ('G', 'E'),
 545: ('G', 'R'),
 547: ('D', 'G'),
 549: ('R', 'E'),
 553: ('S', 'C'),
 555: ('S', 'T'),
 557: ('G', 'A'),
 559: ('P', 'L'),
 560: ('P', 'Q'),
 565: ('Q', 'P'),
 567: ('T', 'M'),
 572: ('L', 'V'),
 573: ('I', 'L'),
 574: ('A', 'T'),
 581: ('A', 'V'),
 585: ('H', 'Q'),
 590: ('M', 'L'),
 593: ('Q', 'Y'),
 594: ('L', 'R'),
 601: ('S', 'T'),
 609: ('A', 'G'),
 610: ('T', 'V'),
 613: ('Y', 'H'),
 614: ('N', 'D'),
 627: ('I', 'V'),
 634: ('A', 'V'),
 637: ('V', 'I'),
 638: ('S', 'P'),
 663: ('S', 'N'),
 664: ('C', 'Y'),
 669: ('L', 'A'),
 673: ('S', 'N'),
 682: ('T', 'P'),
 683: ('D', 'G'),
 685: ('T', 'V'),
 687: ('T', 'V'),
 695: ('H', 'R'),
 696: ('T', 'A'),
 697: ('G', 'E'),
 698: ('R', 'G'),
 701: ('A', 'S'),
 704: ('A', 'N'),
 705: ('P', 'A'),
 706: ('D', 'G'),
 707: ('I', 'H'),
 708: ('L', 'S'),
 709: ('A', 'S'),
 712: ('P', 'L'),
 713: ('Q', 'P'),
 716: ('R', 'G'),
 785: ('V', 'I'),
 799: ('I', 'V'),
 802: ('D', 'S'),
 810: ('E', 'R'),
 814: ('F', 'L'),
 824: ('V', 'I'),
 832: ('D', 'L'),
 834: ('N', 'D'),
 838: ('T', 'I'),
 864: ('A', 'T'),
 888: ('I', 'V'),
 907: ('A', 'T'),
 943: ('P', 'S'),
 949: ('Q', 'E'),
 994: ('R', 'K'),
 1052: ('L', 'I'),
 1097: ('G', 'D'),
 1100: ('V', 'I'),
 1143: ('A', 'S'),
 1200: ('M', 'I'),
 1221: ('R', 'K'),
 1315: ('G', 'V'),
 1321: ('P', 'T'),
 1404: ('S', 'G'),
 1408: ('E', 'G'),
 1409: ('A', 'V'),
 1428: ('V', 'T'),
 1429: ('P', 'S'),
 1484: ('T', 'I'),
 1570: ('N', 'S'),
 1590: ('N', 'M'),
 1602: ('V', 'I'),
 1684: ('Q', 'R'),
 1716: ('R', 'W'),
 1724: ('H', 'R'),
 1736: ('H', 'Y'),
 1743: ('W', 'Q'),
 1770: ('K', 'R'),
 1781: ('D', 'S'),
 1791: ('G', 'D')}

In [330]:
global_compare_to_human('GALT', translation['NM_000155.4'], 'XP_003800307.1', True)

47 R C
54 T A
56 P L
57 Q D
58 Q R
67 A I
68 A P
69 A V
71 T A
73 R Q
75 N S
138 I T
158 Q H
161 S A
202 K E
203 S A
226 V M
252 A V
275 A S
318 Q R
321 K Q
326 E V
338 L I
339 R K
367 T V
411 P S
502 E A
508 A D
511 N D
768 H C
770 G R
794 T A

{47: ('R', 'C'),
 54: ('T', 'A'),
 56: ('P', 'L'),
 57: ('Q', 'D'),
 58: ('Q', 'R'),
 67: ('A', 'I'),
 68: ('A', 'P'),
 69: ('A', 'V'),
 71: ('T', 'A'),
 73: ('R', 'Q'),
 75: ('N', 'S'),
 138: ('I', 'T'),
 158: ('Q', 'H'),
 161: ('S', 'A'),
 202: ('K', 'E'),
 203: ('S', 'A'),
 226: ('V', 'M'),
 252: ('A', 'V'),
 275: ('A', 'S'),
 318: ('Q', 'R'),
 321: ('K', 'Q'),
 326: ('E', 'V'),
 338: ('L', 'I'),
 339: ('R', 'K'),
 367: ('T', 'V'),
 411: ('P', 'S'),
 502: ('E', 'A'),
 508: ('A', 'D'),
 511: ('N', 'D'),
 768: ('H', 'C'),
 770: ('G', 'R'),
 794: ('T', 'A')}

In [25]:
get_species_with_allele('CFTR', translation['NM_000492.4'], 13, 'F')

[('Otolemur garnettii', 'XP_003789873.1')]

In [317]:
local_compare_to_human('CFTR', translation['NM_000492.4'], 13, 'XP_003789873.1')

-10 - -
-9 - -
-8 - -
-7 - -
-6 - -
-5 - -
-4 - -
-3 S N
-2 V L
-1 V L
0 S F
1 K F
2 L L
3 - -
4 - -
5 - -
6 - -
7 - -
8 - -
9 - -
10 - -

(4, 0, 0)

In [331]:
translation['NM_000132.4']

'NP_000123.1'

In [332]:
get_species_with_allele('F8', 'NP_000123.1', 2183, 'V')

[]

In [333]:
local_compare_to_human('F8', 'NP_000123.1', 2183, 'XP_003789873.1')

UnboundLocalError: cannot access local variable 'nonaln' where it is not associated with a value