# Find putative CPDs

## Rerun clean up commands

Since the ClinVar data was modified we begin by rerun the commands in the [clean_up.ipynb](clean_up.ipynb) notebook.

### Extract transcript IDs from variants

Pull the transcript record IDs from the ClinVar records of each gene.

**Output:** `vartranscripts` dictionary with genes as keys and lists of transcripts as values.  The new `dict` has 68 transcripts instead of 72.

In [13]:
import os
os.getcwd()

'c:\\Users\\adesi\\Documents\\GitHub\\kondrashov'

In [28]:
run kondrashov

#### Step 1

In [34]:
i = 0
vartranscripts = {}
for gene in loci:
    vt = get_transcripts_from_variants(gene, True)
    #i += len(vt)    
    print(gene, vt[0], len(vt), 'transcripts')
    vartranscripts.update({gene: vt})

ABCD1 NM_000033.4 1 transcripts
ALPL NM_000478.6 1 transcripts
AR NM_000044.6 1 transcripts
ATP7B NM_000053.4 1 transcripts
BTK NM_000061.3 1 transcripts
CASR NM_000388.4 1 transcripts
CBS NM_000071.3 1 transcripts
CFTR NM_000492.3 3 transcripts
CYBB NM_000397.4 1 transcripts
F7 NM_019616.4 5 transcripts
F8 NC_000023.11:g.155022771G>A 2 transcripts
F9 NC_000023.11:g.139530710G>C 4 transcripts
G6PD NM_001360016.2 3 transcripts
GALT NM_000155.4 1 transcripts
GBA1 NM_000157.4 1 transcripts
GJB1 NM_000166.6 2 transcripts
HBB NC_000011.10:g.5227147G>T 10 transcripts
HPRT1 NM_000194.3 3 transcripts
IL2RG NM_000206.3 1 transcripts
KCNH2 NM_000238.4 1 transcripts
KCNQ1 NM_000218.3 1 transcripts
L1CAM NM_001278116.2 1 transcripts
LDLR NM_000527.4 2 transcripts
MPZ NM_000530.8 1 transcripts
MYH7 NM_000257.4 1 transcripts
TYR NM_000372.5 1 transcripts
PAH NM_000277.3 1 transcripts
PMM2 NM_000303.3 2 transcripts
RHO NM_000539.3 1 transcripts
TP53 NM_000546.6 1 transcripts
TTR NM_000371.4 1 transcripts
VWF NM_000552.5 1 transcripts

### Step 2
##### Extract human protein sequence records from the fasta files

Take the fasta files containing ortholog sequences, search for human sequences and extract the corresponding record.

**Output:** `protrecs` dictionary with genes as keys and lists of protein records as values. Unchanged.

In [35]:
i = 1
protrecs = {}
for gene in loci:
    protrecs.update({gene: []})
    for record in SeqIO.parse('fasta/{0}.fasta'.format(gene), 'fasta'):
        sp = get_species(record)
        if sp=='Homo sapiens':
            protrecs[gene].append(record)
            print(i, gene, record.id, len(record))
            i += 1

1 ABCD1 NP_000024.2 745
2 ABCD1 NP_001427676.1 845
3 ABCD1 XP_047297873.1 575
4 ABCD1 NP_002981.2 93
5 ABCD1 XP_047290405.1 106
6 ABCD1 XP_054169574.1 106
7 ABCD1 XP_054169575.1 93
8 ALPL NP_000469.3 524
9 ALPL NP_001120973.2 469
10 ALPL NP_001170991.1 447
11 ALPL XP_016856392.1 472
12 ALPL XP_054191723.1 472
13 AR NP_000035.2 920
14 AR NP_001011645.1 388
15 AR NP_001334990.1 644
16 AR NP_001334992.1 648
17 AR NP_001334993.1 572
18 AR NP_001648.1 252
19 AR NP_001333071.1 172
20 AR NP_001619.1 316
21 ATP7B NP_000044.2 1465
22 ATP7B NP_001005918.1 1258
23 ATP7B NP_001230111.1 1354
24 ATP7B NP_001317507.1 1387
25 ATP7B NP_001317508.1 1381
26 ATP7B NP_001393442.1 1463
27 ATP7B NP_001393443.1 1454
28 ATP7B NP_001393444.1 1447
29 ATP7B NP_001393446.1 1433
30 ATP7B NP_001393448.1 1420
31 ATP7B NP_001393449.1 1417
32 ATP7B NP_001393452.1 1404
33 ATP7B NP_001393453.1 1406
34 ATP7B NP_001393454.1 1400
35 ATP7B NP_001393455.1 1397
36 ATP7B NP_001393459.1 1385
37 ATP7B NP_001393463.1 1369
38 ATP7B NP_001393464.1 1355
39 ATP7B NP_001393465.1 1355
40 ATP7B NP_001393466.1 1352
41 ATP7B NP_001393467.1 1339
42 ATP7B NP_001393468.1 1322
43 ATP7B NP_001393469.1 1316
44 ATP7B NP_001393470.1 1303
45 ATP7B NP_001393472.1 1301
46 ATP7B NP_001393473.1 1271
47 ATP7B NP_001393474.1 1249
48 ATP7B NP_001393475.1 1238
49 ATP7B NP_001393476.1 1184
50 ATP7B NP_001393477.1 1035
51 BTK NP_000052.1 659
52 BTK NP_001274273.1 693
53 BTK NP_001274274.1 483
54 CASR NP_000379.3 1078
55 CASR NP_001171536.2 1088
56 CASR XP_047305021.1 917
57 CASR XP_054204069.1 1078
58 CASR XP_054204072.1 917
59 CBS NP_000062.1 551
60 CBS NP_001308001.1 446
61 CBS XP_011528076.1 582
62 CBS XP_011528079.1 565
63 CBS XP_011528085.1 460
64 CBS XP_047296974.1 568
65 CBS XP_047296988.1 496
66 CBS XP_054180885.1 582
67 CBS XP_054180887.1 568
68 CBS XP_054180903.1 461
69 CFTR NP_000483.3 1480
70 CYBB NP_000388.2 570
71 CYBB XP_047297811.1 468
72 F7 NP_000122.1 466
73 F7 NP_001254483.1 382
74 F7 NP_062562.1 444
75 F7 XP_006720026.2 412
76 F7 XP_011535776.2 495
77 F7 XP_011535777.2 433
78 F7 XP_011535778.1 364
79 F7 XP_047286081.1 452
80 F8 NP_000123.1 2351
81 F8 NP_063916.1 216
82 F9 NP_000124.1 461
83 F9 NP_001300842.1 423
84 F9 XP_005262454.1 418
85 F9 XP_054182657.1 418
86 G6PD NP_000393.4 545
87 G6PD NP_001035810.1 515
88 GALT NP_000146.2 379
89 GALT NP_001245261.1 270
90 GALT NP_919299.3 498
91 GALT XP_006719831.1 479
92 GALT XP_011533238.1 458
93 GALT XP_011533240.1 449
94 GALT XP_047286067.1 298
95 GBA1 NP_000148.2 536
96 GBA1 NP_001165282.1 449
97 GBA1 NP_001165283.1 487
98 GJB1 NP_000157.1 283
99 HBB NP_000509.1 147
100 HPRT1 NP_000185.1 218
101 IL2RG NP_000197.1 369
102 IL2RG NP_001425799.1 260
103 KCNH2 NP_000229.1 1159
104 KCNH2 NP_001191727.1 548
105 KCNH2 NP_001393682.1 1063
106 KCNH2 NP_001393684.1 829
107 KCNH2 NP_001393685.1 792
108 KCNH2 NP_001393686.1 788
109 KCNH2 NP_742053.1 888
110 KCNH2 NP_742054.1 819
111 KCNH2 XP_011514487.1 1059
112 KCNH2 XP_016867684.1 1109
113 KCNH2 XP_016867685.1 1100
114 KCNH2 XP_047276304.1 1185
115 KCNH2 XP_047276305.1 936
116 KCNQ1 NP_000209.2 676
117 KCNQ1 NP_001393765.1 644
118 KCNQ1 NP_001393766.1 586
119 KCNQ1 NP_001393767.1 496
120 KCNQ1 NP_001393768.1 180
121 KCNQ1 NP_861463.1 549
122 L1CAM NP_000416.1 1257
123 L1CAM NP_001137435.1 1248
124 L1CAM NP_076493.1 1253
125 LDLR NP_000518.1 860
126 LDLR NP_001182727.1 858
127 LDLR NP_001182728.1 819
128 LDLR NP_001182729.1 692
129 LDLR NP_001182732.1 682
130 LDLR NP_001393790.1 202
131 LDLR XP_011526312.1 834
132 LDLR XP_047294787.1 596
133 MPZ NP_000521.2 248
134 MPZ NP_001302420.1 312
135 MPZ XP_016856810.1 240
136 MYH7 NP_000248.2 1935
137 TYR NP_000363.1 529
138 TYR XP_011541272.1 471
139 TYR XP_054225790.1 471
140 PAH NP_000268.1 452
141 PAH XP_016874859.1 240
142 PMM2 NP_000294.1 246
143 PMM2 XP_047290171.1 163
144 RHO NP_000530.1 348
145 RHO NP_001287815.1 144
146 RHO NP_055393.1 210
147 TP53 NP_000537.3 393
148 TP53 NP_001119585.1 346
149 TP53 NP_001119586.1 341
150 TP53 NP_001119587.1 261
151 TP53 NP_001119588.1 209
152 TP53 NP_001119589.1 214
153 TP53 NP_001119590.1 354
154 TP53 NP_001263624.1 307
155 TP53 NP_001263625.1 302
156 TP53 NP_001263626.1 234
157 TP53 NP_001263627.1 182
158 TP53 NP_001263628.1 187
159 TTR NP_000362.1 147
160 VWF NP_000543.3 2813
161 VWF XP_054229108.1 2813

### STEP 3 
##### Match variant transcript IDs with ortholog proteins

Take variant transcript ID, query the NCBI database, extract the corresponding protein, and look for it in the ortholog set.  Flag problems.

**Output:** `translation` dictionary with transcript IDs as keys and lists of protein IDs as values.

In [36]:
#%%time
translation = {}
i = 1
for gene in loci:
    for transcript in vartranscripts[gene]:
        if transcript[:3] == 'NM_':
            rec = get_transcript(transcript)
            seq = get_CDS(rec)
            match = False
            for prot in protrecs[gene]: 
                if seq[4] == prot.seq:
                    print(i, gene, transcript, prot.id)
                    match = True
                    translation.update({transcript: prot.id})
            if not match:
                print(i, gene, transcript, 'no matching protein         <<<<<')
        else:
            print(i, gene, transcript, 'invalid transcript name         *****')
        i += 1

1 ABCD1 NM_000033.4 NP_000024.2
2 ALPL NM_000478.6 NP_000469.3
3 AR NM_000044.6 NP_000035.2
4 ATP7B NM_000053.4 NP_000044.2
5 BTK NM_000061.3 NP_000052.1
6 CASR NM_000388.4 NP_000379.3
7 CBS NM_000071.3 NP_000062.1
8 CFTR NM_000492.3 NP_000483.3
9 CFTR NC_000007.14:g.117675861C>T invalid transcript name         *****
10 CFTR NM_000492.4 NP_000483.3
11 CYBB NM_000397.4 NP_000388.2
12 F7 NM_019616.4 NP_062562.1
13 F7 NM_000131.4 NP_000122.1
14 F7 NM_000131.5 NP_000122.1
15 F7 NC_000013.11:g.113105748C>G invalid transcript name         *****
16 F7 NC_000013.11:g.113105784G>A invalid transcript name         *****
17 F8 NC_000023.11:g.155022771G>A invalid transcript name         *****
18 F8 NM_000132.4 NP_000123.1
19 F9 NC_000023.11:g.139530710G>C invalid transcript name         *****
20 F9 NM_000133.4 NP_000124.1
21 F9 NC_000023.11:g.139530731A>T invalid transcript name         *****
22 F9 NC_000023.11:g.139530716T>A invalid transcript name         *****
23 G6PD NM_001360016.2 NP_001035810.1
24 G6PD NM_001042351.3 NP_001035810.1
25 G6PD NM_000402.4 NP_000393.4
26 GALT NM_000155.4 NP_000146.2
27 GBA1 NM_000157.4 NP_000148.2
28 GJB1 NM_000166.6 NP_000157.1
29 GJB1 NM_001097642.3 NP_000157.1
30 HBB NC_000011.10:g.5227147G>T invalid transcript name         *****
31 HBB NC_000011.10:g.5227097T>G invalid transcript name         *****
32 HBB NC_000011.10:g.5227100T>C invalid transcript name         *****
33 HBB NC_000011.10:g.5227172G>A invalid transcript name         *****
34 HBB NC_000011.10:g.5227096C>A invalid transcript name         *****
35 HBB NC_000011.10:g.5227101A>C invalid transcript name         *****
36 HBB NC_000011.10:g.5227159G>A invalid transcript name         *****
37 HBB NM_000518.4 NP_000509.1
38 HBB NC_000011.10:g.5227098T>A invalid transcript name         *****
39 HBB NM_000518.5 NP_000509.1
40 HPRT1 NM_000194.3 NP_000185.1
41 HPRT1 HPRT CHERMSIDE invalid transcript name         *****
42 HPRT1 NM_000194.2 NP_000185.1
43 IL2RG NM_000206.3 NP_000197.1
44 KCNH2 NM_000238.4 NP_000229.1
45 KCNQ1 NM_000218.3 NP_000209.2
46 L1CAM NM_001278116.2 NP_000416.1
47 LDLR NM_000527.4 NP_000518.1
48 LDLR NM_000527.5 NP_000518.1
49 MPZ NM_000530.8 NP_000521.2
50 MYH7 NM_000257.4 NP_000248.2
51 TYR NM_000372.5 NP_000363.1
52 PAH NM_000277.3 NP_000268.1
53 PMM2 NM_000303.3 NP_000294.1
54 PMM2 NC_000016.10:g.8797716G>T invalid transcript name         *****
55 RHO NM_000539.3 NP_000530.1
56 TP53 NM_000546.6 NP_000537.3
57 TTR NM_000371.4 NP_000362.1
58 VWF NM_000552.5 NP_000543.3

## clean up variants not matching any protein
* HBB 
* G6PD

In [ ]:
vardata = pd.read_csv('pathogenic/HBB.csv')
i = vardata['Name'].tolist().index('Hb Little Rock')
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
14,30278,single nucleotide variant,NM_000518.5(HBB):c.82G>T (p.Ala28Ser),3043,HBB,HGNC:4827,Pathogenic,1,"Apr 07, 2026",35424040,...,A,-,-,-,-,-,-,SCV007592675,-,-
15,30280,single nucleotide variant,NM_000518.5(HBB):c.295G>A (p.Val99Met),3043,HBB,HGNC:4827,Pathogenic,1,"Aug 07, 2025",33933298,...,T,-,-,-,-,-,-,SCV000603896|SCV000919454|SCV002089199|SCV0040...,-,-
16,30289,single nucleotide variant,Hb Little Rock,3043,HBB,HGNC:4827,Pathogenic,1,"Jan 01, 1987",36020563,...,Y,-,-,-,-,-,-,SCV000763147,-,-
17,30290,single nucleotide variant,NM_000518.5(HBB):c.127T>C (p.Phe43Leu),3043,HBB,HGNC:4827,Likely pathogenic,1,"May 30, 2025",33924146,...,G,-,-,-,-,-,-,SCV007535976,-,-
18,30291,single nucleotide variant,NM_000518.5(HBB):c.89G>A (p.Gly30Asp),3043,HBB,HGNC:4827,Likely pathogenic,1,"Aug 07, 2024",35685286,...,T,-,-,-,-,-,-,SCV005625782,-,-

In [ ]:
vardata.loc[i, 'Name'] = 'NM_000518.5(HBB):c.432C>R (p.His144Gln)'
vardata.to_csv('pathogenic/HBB.csv', index=False)
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
14,30278,single nucleotide variant,NM_000518.5(HBB):c.82G>T (p.Ala28Ser),3043,HBB,HGNC:4827,Pathogenic,1,"Apr 07, 2026",35424040,...,A,-,-,-,-,-,-,SCV007592675,-,-
15,30280,single nucleotide variant,NM_000518.5(HBB):c.295G>A (p.Val99Met),3043,HBB,HGNC:4827,Pathogenic,1,"Aug 07, 2025",33933298,...,T,-,-,-,-,-,-,SCV000603896|SCV000919454|SCV002089199|SCV0040...,-,-
16,30289,single nucleotide variant,NM_000518.5(HBB):c.432C>R (p.His144Gln),3043,HBB,HGNC:4827,Pathogenic,1,"Jan 01, 1987",36020563,...,Y,-,-,-,-,-,-,SCV000763147,-,-
17,30290,single nucleotide variant,NM_000518.5(HBB):c.127T>C (p.Phe43Leu),3043,HBB,HGNC:4827,Likely pathogenic,1,"May 30, 2025",33924146,...,G,-,-,-,-,-,-,SCV007535976,-,-
18,30291,single nucleotide variant,NM_000518.5(HBB):c.89G>A (p.Gly30Asp),3043,HBB,HGNC:4827,Likely pathogenic,1,"Aug 07, 2024",35685286,...,T,-,-,-,-,-,-,SCV005625782,-,-

### G6PD

In [ ]:
vardata = pd.read_csv('pathogenic/G6PD.csv')
i = vardata['Name'].tolist().index('G6PD ZURICH') 
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
40,25455,single nucleotide variant,NM_000402.4(G6PD):c.298T>C (p.Tyr100His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Nov 25, 2024",137852349,...,G,-,-,-,-,-,-,SCV001443096|SCV002599323|SCV003445326|SCV0038...,-,-
41,25456,single nucleotide variant,NM_000402.4(G6PD):c.683G>A (p.Arg228His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Jan 02, 2026",137852332,...,T,-,-,-,-,-,-,SCV001142107|SCV002599340|SCV004299714|SCV0050...,-,-
42,25459,single nucleotide variant,G6PD ZURICH,2539,G6PD,HGNC:4057,Pathogenic,1,"Aug 12, 2022",2070350038,...,C,-,-,-,-,-,-,SCV002599384,-,-
43,25461,single nucleotide variant,NM_000402.4(G6PD):c.1466G>C (p.Arg489Pro),2539,G6PD,HGNC:4057,Pathogenic,1,"Feb 05, 2024",72554665,...,G,-,-,-,-,-,-,SCV000330997|SCV000914284|SCV001367223|SCV0013...,-,-
44,99398,single nucleotide variant,NM_001360016.2(G6PD):c.1360C>T (p.Arg454Cys),2539,G6PD,HGNC:4057,Pathogenic,1,"Apr 29, 2026",398123546,...,A,-,-,-,-,-,-,SCV000225263|SCV000281545|SCV000603769|SCV0006...,-,-

In [ ]:
vardata.loc[i, 'Name'] = 'NM_001360016.2(G6PD):c.1288-2A>G)'
vardata.to_csv('pathogenic/G6PD.csv', index=False)
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
40,25455,single nucleotide variant,NM_000402.4(G6PD):c.298T>C (p.Tyr100His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Nov 25, 2024",137852349,...,G,-,-,-,-,-,-,SCV001443096|SCV002599323|SCV003445326|SCV0038...,-,-
41,25456,single nucleotide variant,NM_000402.4(G6PD):c.683G>A (p.Arg228His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Jan 02, 2026",137852332,...,T,-,-,-,-,-,-,SCV001142107|SCV002599340|SCV004299714|SCV0050...,-,-
42,25459,single nucleotide variant,NM_001360016.2(G6PD):c.1288-2A>G),2539,G6PD,HGNC:4057,Pathogenic,1,"Aug 12, 2022",2070350038,...,C,-,-,-,-,-,-,SCV002599384,-,-
43,25461,single nucleotide variant,NM_000402.4(G6PD):c.1466G>C (p.Arg489Pro),2539,G6PD,HGNC:4057,Pathogenic,1,"Feb 05, 2024",72554665,...,G,-,-,-,-,-,-,SCV000330997|SCV000914284|SCV001367223|SCV0013...,-,-
44,99398,single nucleotide variant,NM_001360016.2(G6PD):c.1360C>T (p.Arg454Cys),2539,G6PD,HGNC:4057,Pathogenic,1,"Apr 29, 2026",398123546,...,A,-,-,-,-,-,-,SCV000225263|SCV000281545|SCV000603769|SCV0006...,-,-

### STEP 4  
##### Extract individual variants

Process each ClinVar dataset and extract variants for each transcript.

**Output:** `variants` dictionary with transcript IDs as keys and lists of changes as values.

In [37]:
print('gene transcript protein changes errors')
for gene in loci:
    transcripts = vartranscripts[gene]
    for transcript in transcripts:
        sites, wilds, muts, errs = get_all_changes(gene, transcript, True)
        print(gene, transcript, translation[transcript], len(sites), len(errs))

gene transcript protein changes errors

KeyError: 'Accession'

Let's look more closely at the variants where there are errors.  **They appear to be variants where the name does not specify an amino acid change.**  We can ignore them.

In [7]:
print('gene transcript protein changes errors')
for gene in loci:
    transcripts = vartranscripts[gene]
    for transcript in transcripts:
        sites, wilds, muts, errs = get_all_changes(gene, transcript, True)
        if len(errs)>0:
            print(gene, transcript, translation[transcript], len(sites), len(errs))
            print('   ', errs)

gene transcript protein changes errors
ATP7B NM_000053.3 XP_005266487.1 0 2
    [('NM_000053.3(ATP7B):c.3809A>G', 'VCV000003859'), ('NM_000053.3(ATP7B):c.[3443T>C;3526G>A]', 'VCV000003863')]
BTK NM_001287345.1 NP_001274274.1 0 8
    [('NM_001287345.1(BTK):c.1039-1398T>C', 'VCV000571649'), ('NM_001287345.1(BTK):c.1039-1411G>T', 'VCV000656776'), ('NM_001287345.1(BTK):c.1039-1418C>A', 'VCV000011375'), ('NM_001287345.1(BTK):c.1038+1529A>G', 'VCV000011343'), ('NM_001287345.1(BTK):c.1038+1516C>A', 'VCV000011374'), ('NM_001287345.1(BTK):c.1038+1464T>C', 'VCV000011373'), ('NM_001287345.1(BTK):c.1038+813T>G', 'VCV000011371'), ('NM_001287345.1(BTK):c.1038+44A>G', 'VCV000011346')]
BTK NM_000061.3 NP_000052.1 25 1
    [('NM_000061.3(BTK):c.763C>T', 'VCV000011363')]
CASR NM_000388.4 NP_000379.3 108 1
    [('NM_000388.4(CASR):c.1609-2A>G', 'VCV000854168')]
CFTR NM_000492.3 NP_000483.3 225 7
    [('NM_000492.3(CFTR):c.[350G>A;1210-12[5]]', 'VCV000209047'), ('NM_000492.3(CFTR):c.[1075C>A;1079C>A]', 'VCV000040200'), ('NM_000492.3(CFTR):c.[1397C>G;3209G>A]', 'VCV000634835'), ('NM_000492.3(CFTR):c.[1521_1523delCTT;3080T>C]', 'VCV000634837'), ('NM_000492.3(CFTR):c.[1327G>T;1727G>C;2002C>T]', 'VCV000870319'), ('NM_000492.3(CFTR):c.[2735C>T;3731G>T]', 'VCV000007239'), ('NM_000492.3(CFTR):c.[2816A>G;2846A>T]', 'VCV000996223')]
CFTR NM_000492.4 NP_000483.3 153 6
    [('NM_000492.4(CFTR):c.274G>A', 'VCV000007181'), ('NM_000492.4(CFTR):c.376G>A', 'VCV000053808'), ('NM_000492.4(CFTR):c.1013C>T', 'VCV000007193'), ('NM_000492.4(CFTR):c.1367T>C', 'VCV000035821'), ('NM_000492.4(CFTR):c.1516A>C', 'VCV000053275'), ('NM_000492.4(CFTR):c.1705T>G', 'VCV000053352')]
F9 NM_001313913.1 NP_001300842.1 1 5
    [('NM_001313913.1(F9):c.277+3690A>G', 'VCV000010576'), ('NM_001313913.1(F9):c.277+3699A>C', 'VCV000010577'), ('NM_001313913.1(F9):c.277+3713C>G', 'VCV000010578'), ('NM_001313913.1(F9):c.277+3740G>A', 'VCV000010643'), ('NM_001313913.1(F9):c.277+3741A>G', 'VCV000010580')]
G6PD NM_001042351.1 NP_001346945.1 0 1
    [('NM_001042351.1(G6PD):c.[317C>G;544C>T;592C>T]', 'VCV000010392')]
G6PD NM_001360016.2 NP_001346945.1 25 1
    [('NM_001360016.2(G6PD):c.[376A>G;968T>C]', 'VCV001065168')]
GALT NM_000155.2 NP_000146.2 0 1
    [('NM_000155.2(GALT):c.[940A>G;-119_-116delGTCA]', 'VCV000140570')]
GBA NM_000157.3 NP_001005742.1 0 2
    [('NM_000157.3(GBA):c.1603C>T', 'VCV000242383'), ('NM_000157.3(GBA):c.1448T>C', 'VCV000004288')]
GBA NM_001005741.2 NP_001005742.1 0 3
    [('NM_001005741.2(GBA):c.[1448T>C;1483G>C;1497G>C]', 'VCV000004297'), ('NM_001005741.2(GBA):c.[880T>G;1342G>C]', 'VCV000004334'), ('NM_001005741.2(GBA):c.[535G>C;c.1093G>A]', 'VCV000004299')]
HBB NM_000518.4 NP_000509.1 41 5
    [('NM_000518.4(HBB):c.[20A>T;364G>A]', 'VCV000446736'), ('NM_000518.4(HBB):c.[20A>T;271G>A]', 'VCV000446747'), ('NM_000518.4(HBB):c.[20A>T;249G>Y]', 'VCV000446737'), ('NM_000518.4(HBB):c.[20A>T;428C>T]', 'VCV000446738'), ('NM_000518.4(HBB):c.[20A>T;70G>A]', 'VCV000446735')]
KCNQ1 NM_000218.2 NP_000209.2 17 1
    [('NM_000218.2(KCNQ1):c.[1249G>A;760G>A]', 'VCV000444879')]
LDLR NM_001195800.2 NP_001182729.1 0 3
    [('NM_001195800.2(LDLR):c.314-2016G>A', 'VCV000441186'), ('NM_001195800.2(LDLR):c.314-2007G>T', 'VCV000441187'), ('NM_001195800.2(LDLR):c.314-1999C>T', 'VCV000431511')]
LDLR NM_001195803.2 NP_001182732.1 0 1
    [('NM_001195803.2(LDLR):c.1606+203C>A', 'VCV000441227')]
LDLR NM_000527.4 NP_000518.1 160 3
    [('NM_000527.4:c.[829G>A;1268T>C]', 'VCV000430765'), ('NM_000527.4:c.[932A>G;939C>G]', 'VCV000430769'), ('NM_000527.4:c.[1979A>C;2359G>A]', 'VCV000430800')]
MPZ NM_000530.6 NP_000521.2 0 3
    [('NM_000530.6(MPZ):c.[341T>C;346A>C;382G>A]', 'VCV000014180'), ('NM_000530.6(MPZ):c.[266T>A;274G>A;486C>G]', 'VCV000014182'), ('NM_000530.6(MPZ):c.[241C>T;337G>T]', 'VCV000208147')]
MYH7 NM_000257.3 XP_016876829.1 0 1
    [('NM_000257.3(MYH7):c.[1816G>A;2183C>T]', 'VCV000487487')]
PAH NM_000277.1 NP_001341233.1 0 1
    [('NM_000277.1(PAH):c.[353-507G>T;754C>T]', 'VCV000217885')]
TP53 NM_001126118.1 NP_001263690.1 0 1
    [('NM_001126118.1(TP53):c.-13G>T', 'VCV000012371')]
TP53 NM_001276697.2 NP_001263626.1 0 9
    [('NM_001276697.2(TP53):c.-26C>G', 'VCV000376640'), ('NM_001276697.2(TP53):c.-27C>G', 'VCV000376641'), ('NM_001276697.2(TP53):c.-46G>T', 'VCV000376648'), ('NM_001276697.2(TP53):c.-50T>C', 'VCV000804214'), ('NM_001276697.2(TP53):c.-57T>A', 'VCV000376567'), ('NM_001276697.2(TP53):c.-57T>G', 'VCV000376566'), ('NM_001276697.2(TP53):c.-57T>C', 'VCV000376565'), ('NM_001276697.2(TP53):c.-66G>C', 'VCV000012376'), ('NM_001276697.2(TP53):c.-75T>C', 'VCV000376560')]
TP53 NM_001126113.2 NP_001119585.1 0 1
    [('NM_001126113.2(TP53):c.*50T>C', 'VCV000012375')]
TP53 NM_001126115.1 NP_001119587.1 0 1
    [('NM_001126115.1(TP53):c.-2A>C', 'VCV000376627')]
TP53 NM_000546.6 NP_001119584.1 48 4
    [('NM_000546.6(TP53):c.1045G>T', 'VCV000634695'), ('NM_000546.6(TP53):c.880G>T', 'VCV000379471'), ('NM_000546.6(TP53):c.537T>A', 'VCV000406578'), ('NM_000546.6(TP53):c.438G>A', 'VCV000428890')]
TTR NM_000371.4 NP_000362.1 25 2
    [('NM_000371.4(TTR):c.194C>A', 'VCV000181702'), ('NM_000371.4(TTR):c.239C>T', 'VCV000577420')]

We collect all valid variants in a `variants` dictionary.

In [8]:
variants = {}
for gene in loci:
    print(gene, end=' ... ')
    transcripts = vartranscripts[gene]
    for transcript in transcripts:
        sites, wilds, muts, errs = get_all_changes(gene, transcript, True)
        if len(sites)>0:
            variants.update({transcript: (sites, wilds, muts, errs)})

ABCD1 ... ALPL ... AR ... ATP7B ... BTK ... CASR ... CBS ... CFTR ... CYBB ... F7 ... F8 ... F9 ... G6PD ... GALT ... GBA ... GJB1 ... HBB ... HPRT1 ... IL2RG ... KCNH2 ... KCNQ1 ... L1CAM ... LDLR ... MPZ ... MYH7 ... TYR ... PAH ... PMM2 ... RHO ... TP53 ... TTR ... VWF ...

In [9]:
sites, wilds, muts, errs = variants['NM_000518.4']
print(sites)
print(wilds)
print(muts)

[147, 147, 147, 143, 128, 125, 122, 111, 107, 107, 102, 101, 100, 100, 100, 100, 100, 100, 98, 95, 93, 93, 92, 90, 89, 83, 83, 83, 69, 68, 61, 46, 43, 37, 33, 31, 29, 27, 24, 9, 7]
['H', 'H', 'H', 'A', 'Q', 'P', 'E', 'L', 'L', 'L', 'E', 'P', 'D', 'D', 'D', 'D', 'D', 'D', 'H', 'D', 'H', 'H', 'L', 'S', 'L', 'K', 'K', 'K', 'L', 'V', 'V', 'F', 'F', 'P', 'L', 'R', 'L', 'E', 'V', 'K', 'E']
['P', 'L', 'D', 'D', 'R', 'R', 'K', 'P', 'R', 'Q', 'K', 'L', 'A', 'G', 'V', 'Y', 'H', 'N', 'L', 'H', 'N', 'Y', 'P', 'N', 'P', 'T', 'M', 'E', 'H', 'E', 'E', 'S', 'V', 'H', 'Q', 'T', 'Q', 'G', 'F', 'E', 'K']

## Extract variable sites

Process each alignment and extract variable sites for each protein.

**Output:** `variable` dictionary with transcript IDs as keys and dictionaries of variable sites as values.

In [10]:
variable = {}
for gene in loci:
    print(gene, end=' ... ')
    transcripts = vartranscripts[gene]
    for transcript in transcripts:
        protein = translation[transcript]
        variable.update({transcript: get_variable_sites(gene, protein, False)})

ABCD1 ... ALPL ... AR ... ATP7B ... BTK ... CASR ... CBS ... CFTR ... CYBB ... F7 ... F8 ... F9 ... G6PD ... GALT ... GBA ... GJB1 ... HBB ... HPRT1 ... IL2RG ... KCNH2 ... KCNQ1 ... L1CAM ... LDLR ... MPZ ... MYH7 ... TYR ... PAH ... PMM2 ... RHO ... TP53 ... TTR ... VWF ...

In [11]:
!open .

## Identify putative CPDs

In [12]:
print('gene\ttranscript\tsite\twild\tmut\tvar')
final_transcripts = variants.keys()
for gene in loci:
    transcripts = vartranscripts[gene]
    for transcript in transcripts:
        if transcript in final_transcripts:
            sites, wilds, muts, errs = variants[transcript]
            tmp_variable = variable[transcript]
            variable_sites = tmp_variable.keys()
            n = len(sites)
            for i in range(n):
                site = sites[i]
                if (site in variable_sites) and (muts[i] in tmp_variable[site]):
                    print(gene, transcript, site, wilds[i], muts[i], tmp_variable[site], sep='\t')

gene	transcript	site	wild	mut	var
ALPL	NM_000478.6	491	G	R	['R']
AR	NM_000044.6	611	N	K	['E', 'K']
AR	NM_000044.6	788	M	V	['V', 'C', 'Y', 'I']
ATP7B	NM_000053.4	1178	T	A	['A']
ATP7B	NM_000053.4	969	R	Q	['Q']
CFTR	NM_000492.4	1	M	R	['L', 'P', 'Q', 'R']
CFTR	NM_000492.4	13	S	F	['G', 'F']
F8	NM_000132.3	2319	P	L	['L']
F8	NM_000132.3	2185	L	S	['S']
F8	NM_000132.3	2183	M	V	['G', 'V']
F8	NM_000132.3	2038	N	S	['H', 'K', 'S']
F8	NM_000132.3	1979	G	V	['V']
F8	NM_000132.3	585	I	T	['M', 'T']
F8	NM_000132.3	584	Q	K	['K', 'S', 'P']
F8	NM_000132.3	494	I	T	['T']
F9	NM_000133.3	75	R	Q	['Q']
GALT	NM_000155.4	23	T	A	['A', 'W']
GALT	NM_000155.4	97	N	D	['Q', 'D', 'E']
GALT	NM_000155.4	114	H	L	['L']
GALT	NM_000155.4	129	M	L	['L']
GALT	NM_000155.4	186	H	Y	['Y']
GALT	NM_000155.4	198	I	T	['D', 'T', 'V']
GALT	NM_000155.4	204	R	P	['P']
GALT	NM_000155.4	212	Q	P	['P']
GALT	NM_000155.4	226	L	P	['P']
GALT	NM_000155.4	319	H	Q	['Q']
GALT	NM_000155.4	329	S	P	['P']
GALT	NM_000155.4	333	R	L	['L', 'S']
GALT	NM_000155.4	363	E	K	['D', 'K', 'R', 'G']
GBA	NM_000157.4	535	R	H	['L', 'H']
GBA	NM_000157.4	502	R	C	['C']
GBA	NM_000157.4	416	G	S	['S']
GBA	NM_000157.4	351	W	C	['C']
GBA	NM_000157.4	350	H	R	['R']
GBA	NM_000157.4	324	R	C	['T', 'C']
GBA	NM_000157.4	227	N	S	['S']
GBA	NM_000157.4	223	W	R	['R']
KCNH2	NM_172056.2	92	R	L	['L']
KCNH2	NM_172056.2	72	P	L	['L']
KCNH2	NM_172056.2	65	T	P	['V', 'P']
KCNH2	NM_172056.2	56	R	Q	['T', 'Q']
KCNQ1	NM_000218.2	1	M	K	['K', 'R']
KCNQ1	NM_000218.2	2	A	G	['L', 'P', 'G']
KCNQ1	NM_000218.2	114	L	P	['M', 'P', 'V']
KCNQ1	NM_000218.2	115	E	K	['K', 'Q', 'G', 'L', 'R']
KCNQ1	NM_000218.2	117	P	S	['S', 'E', 'A', 'C', 'R']
KCNQ1	NM_000218.2	125	Y	D	['F', 'T', 'D', 'S', 'A']
KCNQ1	NM_181798.1	145	G	D	['D']
LDLR	NM_000527.4	88	R	K	['K']
LDLR	NM_000527.4	215	R	H	['H']
LDLR	NM_000527.4	470	S	G	['G']
LDLR	NM_000527.4	471	R	K	['K', 'G']
LDLR	NM_000527.4	578	V	A	['A']
LDLR	NM_000527.5	36	D	E	['E', 'P']
LDLR	NM_000527.5	46	C	S	['S']
LDLR	NM_000527.5	137	G	S	['S']
LDLR	NM_000527.5	579	D	G	['G']
LDLR	NM_000527.5	583	H	D	['D']
TYR	NM_000372.5	346	G	V	['A', 'V']
TYR	NM_000372.5	370	M	I	['I']
PAH	NM_000277.3	413	R	H	['H']
PAH	NM_000277.3	400	R	S	['S']
PAH	NM_000277.3	176	R	Q	['Q']
PMM2	NM_000303.3	226	T	S	['V', 'S', 'L']
TP53	NM_000546.5	276	A	G	['G']
TP53	NM_000546.5	273	R	G	['G']
TTR	NM_000371.3	77	G	R	['R']
TTR	NM_000371.3	82	E	K	['K']
TTR	NM_000371.3	127	I	V	['V', 'F']
TTR	NM_000371.3	131	L	M	['T', 'M']
TTR	NM_000371.3	136	Y	S	['S', 'W', 'R']
TTR	NM_000371.4	142	V	I	['I', 'L']
VWF	NM_000552.4	528	N	S	['S']

## Look at particular sites

The following command allows you to double check particular sites.  It now also outputs which site each species has.

In [13]:
get_alleles('ATP7B', translation['NM_000053.4'], 969, True)

     Gene: ATP7B
    Human: 969 R
Alignment: 1102 R
R    105
-      6
Q      1
dtype: int64

R XP_012668202.1 Otolemur garnettii
R XP_023363838.1 Otolemur garnettii
R XP_023363839.1 Otolemur garnettii
R XP_012638114.1 Microcebus murinus
R XP_012638117.1 Microcebus murinus
R XP_020145970.1 Microcebus murinus
R XP_012638108.1 Microcebus murinus
R XP_012504533.1 Propithecus coquereli
R XP_012504538.1 Propithecus coquereli
R XP_012504534.1 Propithecus coquereli
R XP_012504529.1 Propithecus coquereli
R XP_008070488.1 Carlito syrichta
R XP_008070485.1 Carlito syrichta
R XP_008070483.1 Carlito syrichta
- XP_008070484.1 Carlito syrichta
R XP_008070486.1 Carlito syrichta
R XP_021561720.1 Carlito syrichta
R XP_008070482.1 Carlito syrichta
R XP_011920046.1 Cercocebus atys
R XP_016780802.1 Pan troglodytes
R XP_005266488.1 Homo sapiens
R XP_016876116.1 Homo sapiens
R NP_001005918.1 Homo sapiens
R NP_001230111.1 Homo sapiens
R NP_001317507.1 Homo sapiens
R NP_001317508.1 Homo sapiens
R XP_005266487.1 Homo sapiens
R XP_024086846.1 Pongo abelii
R XP_018895400.1 Gorilla gorilla gorilla
R XP_018895395.1 Gorilla gorilla gorilla
R XP_018895399.1 Gorilla gorilla gorilla
R XP_018895398.1 Gorilla gorilla gorilla
R XP_018895397.1 Gorilla gorilla gorilla
R XP_004054587.1 Gorilla gorilla gorilla
R XP_024781041.2 Pan paniscus
R XP_008960333.2 Pan paniscus
R XP_008960332.2 Pan paniscus
R XP_024781039.2 Pan paniscus
R XP_016780804.1 Pan troglodytes
R XP_016780795.1 Pan troglodytes
- XP_016780803.1 Pan troglodytes
R XP_016780796.1 Pan troglodytes
- XP_016780801.1 Pan troglodytes
R XP_016780799.1 Pan troglodytes
R XP_016780797.1 Pan troglodytes
R XP_016780798.1 Pan troglodytes
R XP_016780792.1 Pan troglodytes
R XP_032006829.1 Hylobates moloch
Q XP_030669295.1 Nomascus leucogenys
R XP_033033526.1 Trachypithecus francoisi
R XP_033033524.1 Trachypithecus francoisi
R XP_023043183.1 Piliocolobus tephrosceles
R XP_011794363.1 Colobus angolensis palliatus
R XP_011794355.1 Colobus angolensis palliatus
- XP_011794340.1 Colobus angolensis palliatus
R XP_011794322.1 Colobus angolensis palliatus
R XP_011794349.1 Colobus angolensis palliatus
R XP_011794331.1 Colobus angolensis palliatus
R XP_010351222.1 Rhinopithecus roxellana
R XP_017713761.1 Rhinopithecus bieti
R XP_017713762.1 Rhinopithecus bieti
R XP_017713764.1 Rhinopithecus bieti
R XP_037842590.1 Chlorocebus sabaeus
R XP_037842589.1 Chlorocebus sabaeus
R XP_021785340.1 Papio anubis
R XP_031511724.1 Papio anubis
R XP_021785339.1 Papio anubis
R XP_025220045.1 Theropithecus gelada
R XP_025220042.1 Theropithecus gelada
R XP_025220040.1 Theropithecus gelada
R XP_025220044.1 Theropithecus gelada
- XP_025220041.1 Theropithecus gelada
R XP_025220043.1 Theropithecus gelada
R XP_025220038.1 Theropithecus gelada
R XP_028693405.1 Macaca mulatta
R XP_011754962.1 Macaca nemestrina
R XP_011754960.1 Macaca nemestrina
R XP_011754959.1 Macaca nemestrina
R XP_011754965.1 Macaca nemestrina
R XP_014976602.2 Macaca mulatta
R XP_017806754.3 Papio anubis
R XP_017806752.3 Papio anubis
R XP_021785338.2 Papio anubis
R XP_014976601.2 Macaca mulatta
R XP_011844139.1 Mandrillus leucophaeus
R XP_011844138.1 Mandrillus leucophaeus
- XP_011844136.1 Mandrillus leucophaeus
R XP_011844134.1 Mandrillus leucophaeus
R XP_011844137.1 Mandrillus leucophaeus
R XP_011844135.1 Mandrillus leucophaeus
R XP_015294467.1 Macaca fascicularis
R XP_015294466.1 Macaca fascicularis
R XP_005585947.1 Macaca fascicularis
R XP_015294469.1 Macaca fascicularis
R XP_035153347.1 Callithrix jacchus
R XP_035153336.1 Callithrix jacchus
R XP_035153361.1 Callithrix jacchus
R XP_035153372.1 Callithrix jacchus
R XP_035153325.1 Callithrix jacchus
R XP_035153322.1 Callithrix jacchus
R XP_010336209.1 Saimiri boliviensis boliviensis
R XP_003927227.1 Saimiri boliviensis boliviensis
R XP_010336210.1 Saimiri boliviensis boliviensis
R XP_012321638.1 Aotus nancymaae
R XP_032150437.1 Sapajus apella
R XP_032150436.1 Sapajus apella
R XP_017397952.1 Cebus imitator
R XP_017397951.1 Cebus imitator
R XP_032150439.1 Sapajus apella
R XP_032150438.1 Sapajus apella
R XP_017397954.1 Cebus imitator
R XP_017397953.1 Cebus imitator

(True,
 969,
 'R',
 R    105
 -      6
 Q      1
 dtype: int64)

In [14]:
get_alleles('F8', translation['NM_000132.3'], 2038, True)

     Gene: F8
    Human: 2038 N
Alignment: 2964 N
N    46
-    14
H     4
S     3
K     3
dtype: int64

N XP_021524500.1 Aotus nancymaae
K XP_003802782.1 Otolemur garnettii
K XP_012517042.1 Propithecus coquereli
K XP_020140823.1 Microcebus murinus
N XP_017376032.2 Cebus imitator
N XP_032121193.1 Sapajus apella
N XP_032121192.1 Sapajus apella
N XP_032121191.1 Sapajus apella
N XP_032121190.1 Sapajus apella
N XP_003943974.1 Saimiri boliviensis boliviensis
S XP_035144731.1 Callithrix jacchus
S XP_035144732.1 Callithrix jacchus
S XP_035144729.1 Callithrix jacchus
- XP_008960582.2 Pan paniscus
- XP_030861623.1 Gorilla gorilla gorilla
- XP_030662513.1 Nomascus leucogenys
N XP_032612179.1 Hylobates moloch
N XP_003279379.1 Nomascus leucogenys
- NP_063916.1 Homo sapiens
N NP_000123.1 Homo sapiens
N XP_034806192.1 Pan paniscus
N XP_003810005.2 Pan paniscus
N XP_034806193.1 Pan paniscus
N XP_016800115.1 Pan troglodytes
N XP_009438145.1 Pan troglodytes
N XP_016800113.1 Pan troglodytes
N XP_016800114.1 Pan troglodytes
N XP_003317837.1 Pan troglodytes
N XP_016800116.1 Pan troglodytes
N XP_004065205.1 Gorilla gorilla gorilla
N XP_018874840.1 Gorilla gorilla gorilla
- XP_024096330.1 Pongo abelii
N XP_024096329.1 Pongo abelii
N XP_031516315.1 Papio anubis
- XP_025227753.1 Theropithecus gelada
N XP_033057806.1 Trachypithecus francoisi
N XP_011818598.1 Colobus angolensis palliatus
- XP_026307119.1 Piliocolobus tephrosceles
N XP_010351146.1 Rhinopithecus roxellana
N XP_025227752.1 Theropithecus gelada
N XP_031516316.1 Papio anubis
N XP_031516314.1 Papio anubis
N XP_010351139.1 Rhinopithecus roxellana
N XP_010351130.1 Rhinopithecus roxellana
N XP_010351142.1 Rhinopithecus roxellana
N XP_011889285.1 Cercocebus atys
N XP_011889280.1 Cercocebus atys
H XP_011716757.1 Macaca nemestrina
- XP_011716758.1 Macaca nemestrina
N XP_005595091.1 Macaca fascicularis
N XP_015299410.1 Macaca fascicularis
N XP_015299411.1 Macaca fascicularis
H XP_011716756.1 Macaca nemestrina
H XP_011716754.1 Macaca nemestrina
H XP_011716755.1 Macaca nemestrina
N XP_014984060.2 Macaca mulatta
N XP_014984059.2 Macaca mulatta
- XP_030789545.1 Rhinopithecus roxellana
- XP_030789544.1 Rhinopithecus roxellana
N XP_037845232.1 Chlorocebus sabaeus
N XP_011889284.1 Cercocebus atys
N XP_011889283.1 Cercocebus atys
N XP_011889281.1 Cercocebus atys
N XP_005595095.1 Macaca fascicularis
- XP_028698333.1 Macaca mulatta
N XP_028698332.1 Macaca mulatta
- XP_011889287.1 Cercocebus atys
N XP_015299412.1 Macaca fascicularis
- XP_011889288.1 Cercocebus atys
- XP_011889289.1 Cercocebus atys

(True,
 2038,
 'N',
 N    46
 -    14
 H     4
 S     3
 K     3
 dtype: int64)

In [18]:
translation['NM_000157.4']

'NP_001005742.1'

In [15]:
get_alleles('TTR', translation['NM_000371.3'], 142, True)

     Gene: TTR
    Human: 142 V
Alignment: 144 V
V    26
-     2
L     1
I     1
dtype: int64

L XP_011788672.1 Colobus angolensis palliatus
- XP_010333769.1 Saimiri boliviensis boliviensis
V XP_010333768.1 Saimiri boliviensis boliviensis
V XP_032149005.1 Sapajus apella
V XP_012302669.1 Aotus nancymaae
V NP_001254679.1 Callithrix jacchus
V XP_003784812.1 Otolemur garnettii
V XP_012638014.1 Microcebus murinus
V XP_012512049.1 Propithecus coquereli
V NP_001127064.1 Pongo abelii
V NP_000362.1 Homo sapiens
V XP_004059337.1 Gorilla gorilla gorilla
V XP_032008476.1 Hylobates moloch
V XP_003830303.2 Pan paniscus
V NP_001009137.1 Pan troglodytes
V XP_011930274.1 Cercocebus atys
I XP_007972558.2 Chlorocebus sabaeus
V XP_011829762.1 Mandrillus leucophaeus
V XP_025220794.1 Theropithecus gelada
V XP_025220793.1 Theropithecus gelada
V XP_023063511.2 Piliocolobus tephrosceles
V XP_017713537.1 Rhinopithecus bieti
V XP_010379114.1 Rhinopithecus roxellana
V XP_011788674.1 Colobus angolensis palliatus
V XP_011788673.1 Colobus angolensis palliatus
V XP_033033949.1 Trachypithecus francoisi
- XP_021562314.1 Carlito syrichta
V XP_021562313.1 Carlito syrichta
V XP_021562312.1 Carlito syrichta
V XP_008071577.1 Carlito syrichta

(True,
 142,
 'V',
 V    26
 -     2
 L     1
 I     1
 dtype: int64)

In [16]:
get_alleles('GBA', translation['NM_000157.4'], 535, True)

     Gene: GBA
    Human: 535 R
Alignment: 547 R
R    36
L     3
H     1
-     1
dtype: int64

- XP_037855735.1 Chlorocebus sabaeus
R XP_012514200.1 Propithecus coquereli
R XP_012623306.1 Microcebus murinus
R XP_012623305.1 Microcebus murinus
R XP_023372167.1 Otolemur garnettii
R XP_012664043.1 Otolemur garnettii
R XP_008048281.1 Carlito syrichta
R XP_021564251.1 Carlito syrichta
R XP_008048283.1 Carlito syrichta
R XP_011932225.1 Cercocebus atys
R XP_021528768.1 Aotus nancymaae
R XP_039315825.1 Saimiri boliviensis boliviensis
R XP_010346697.1 Saimiri boliviensis boliviensis
R XP_032129098.1 Sapajus apella
R XP_017368970.1 Cebus imitator
H XP_032010219.1 Hylobates moloch
R XP_030866469.1 Gorilla gorilla gorilla
R XP_030866465.1 Gorilla gorilla gorilla
R NP_001165282.1 Homo sapiens
R NP_001165283.1 Homo sapiens
R NP_001005742.1 Homo sapiens
R XP_030680202.1 Nomascus leucogenys
R XP_024098242.1 Pongo abelii
R NP_001127488.1 Pongo abelii
L XP_005541629.1 Macaca fascicularis
L XP_005541627.1 Macaca fascicularis
L XP_005541626.1 Macaca fascicularis
R XP_030791630.1 Rhinopithecus roxellana
R XP_030791629.1 Rhinopithecus roxellana
R XP_028684174.1 Macaca mulatta
R XP_014966769.2 Macaca mulatta
R XP_028684167.1 Macaca mulatta
R XP_014966754.2 Macaca mulatta
R XP_033052144.1 Trachypithecus francoisi
R XP_033052142.1 Trachypithecus francoisi
R XP_033052141.1 Trachypithecus francoisi
R XP_033052140.1 Trachypithecus francoisi
R XP_011783701.1 Colobus angolensis palliatus
R XP_011783702.1 Colobus angolensis palliatus
R XP_025237659.1 Theropithecus gelada
R XP_031509384.1 Papio anubis

(True,
 535,
 'R',
 R    36
 L     3
 H     1
 -     1
 dtype: int64)

In [17]:
get_alleles('GALT', translation['NM_000155.4'], 23, True)

     Gene: GALT
    Human: 23 T
Alignment: 43 T
T    37
-    24
W     1
A     1
dtype: int64

T XP_035106695.1 Callithrix jacchus
T XP_008068994.1 Carlito syrichta
- XP_034823261.1 Pan paniscus
T XP_034823259.1 Pan paniscus
T XP_034823258.1 Pan paniscus
T XP_034823256.1 Pan paniscus
- XP_023059055.1 Piliocolobus tephrosceles
- XP_037854236.1 Chlorocebus sabaeus
- XP_033094123.1 Trachypithecus francoisi
- XP_017747549.1 Rhinopithecus bieti
- XP_028690929.1 Macaca mulatta
- XP_011805906.1 Colobus angolensis palliatus
- NP_001245261.1 Homo sapiens
- XP_034823265.1 Pan paniscus
T XP_011924614.1 Cercocebus atys
W XP_011924616.1 Cercocebus atys
T XP_011924615.1 Cercocebus atys
- XP_011924617.1 Cercocebus atys
T XP_021783112.2 Papio anubis
T XP_025214557.1 Theropithecus gelada
T XP_021783108.2 Papio anubis
- XP_021783109.2 Papio anubis
- XP_021783111.1 Papio anubis
T XP_009186860.2 Papio anubis
T XP_033094120.1 Trachypithecus francoisi
- XP_033094122.1 Trachypithecus francoisi
- XP_023059054.1 Piliocolobus tephrosceles
T XP_011835461.1 Mandrillus leucophaeus
T XP_011805904.1 Colobus angolensis palliatus
T XP_011924618.1 Cercocebus atys
T XP_007967100.2 Chlorocebus sabaeus
T XP_023059053.1 Piliocolobus tephrosceles
T XP_028690927.1 Macaca mulatta
- XP_007967102.2 Chlorocebus sabaeus
T XP_017747545.1 Rhinopithecus bieti
- XP_030775929.1 Rhinopithecus roxellana
T NP_000146.2 Homo sapiens
- XP_034823262.1 Pan paniscus
T XP_004048011.1 Gorilla gorilla gorilla
T XP_001163419.1 Pan troglodytes
T XP_003829858.2 Pan paniscus
T XP_009242596.2 Pongo abelii
T XP_003263433.1 Nomascus leucogenys
- XP_032019925.1 Hylobates moloch
T XP_032019924.1 Hylobates moloch
T XP_032019923.1 Hylobates moloch
- XP_012318677.1 Aotus nancymaae
T XP_012318674.1 Aotus nancymaae
- XP_035106712.1 Callithrix jacchus
T XP_008996942.1 Callithrix jacchus
T XP_003732050.1 Callithrix jacchus
- XP_037599582.1 Cebus imitator
- XP_010330022.1 Saimiri boliviensis boliviensis
T XP_010330018.1 Saimiri boliviensis boliviensis
T XP_010330019.1 Saimiri boliviensis boliviensis
T XP_032155758.1 Sapajus apella
T XP_037599581.1 Cebus imitator
T XP_017398495.1 Cebus imitator
- XP_023375102.1 Otolemur garnettii
A XP_003800307.1 Otolemur garnettii
T XP_012625552.1 Microcebus murinus
- XP_012512307.1 Propithecus coquereli
T XP_012512299.1 Propithecus coquereli

(True,
 23,
 'T',
 T    37
 -    24
 W     1
 A     1
 dtype: int64)

In [18]:
get_alleles('F9', translation['NM_000133.3'], 75, True)

     Gene: F9
    Human: 75 R
Alignment: 75 R
R    39
Q     1
dtype: int64

R XP_002763378.1 Callithrix jacchus
R XP_012325320.1 Aotus nancymaae
R XP_017355402.1 Cebus imitator
R XP_032124214.1 Sapajus apella
R XP_003940777.1 Saimiri boliviensis boliviensis
R XP_011930388.1 Cercocebus atys
R XP_037844800.1 Chlorocebus sabaeus
R XP_007991031.1 Chlorocebus sabaeus
R NP_001103153.1 Macaca mulatta
R XP_028697500.1 Macaca mulatta
R XP_011739181.1 Macaca nemestrina
R XP_028697499.1 Macaca mulatta
R XP_025228623.1 Theropithecus gelada
R XP_025228622.1 Theropithecus gelada
R XP_017809908.1 Papio anubis
R XP_003918402.1 Papio anubis
R XP_023058339.1 Piliocolobus tephrosceles
R XP_023058338.1 Piliocolobus tephrosceles
R XP_033057437.1 Trachypithecus francoisi
R XP_010387043.1 Rhinopithecus roxellana
R XP_011816431.1 Colobus angolensis palliatus
R XP_011816430.1 Colobus angolensis palliatus
R XP_009233598.2 Pongo abelii
R XP_002832230.2 Pongo abelii
R XP_032612351.1 Hylobates moloch
R XP_032612350.1 Hylobates moloch
R XP_012354229.1 Nomascus leucogenys
R XP_003272634.1 Nomascus leucogenys
R XP_016798133.1 Pan troglodytes
R XP_003812356.2 Pan paniscus
R XP_004064996.1 Gorilla gorilla gorilla
R XP_005262454.1 Homo sapiens
R NP_001300842.1 Homo sapiens
R NP_000124.1 Homo sapiens
R XP_008059975.1 Carlito syrichta
R XP_008059974.1 Carlito syrichta
Q XP_023373463.1 Otolemur garnettii
R XP_012520761.1 Propithecus coquereli
R XP_012637955.1 Microcebus murinus
R XP_012637954.1 Microcebus murinus

(True,
 75,
 'R',
 R    39
 Q     1
 dtype: int64)

In [14]:
translation['NM_000527.4']

'NP_000518.1'

In [13]:
get_alleles('LDLR', translation['NM_000527.4'], 215, True)

     Gene: LDLR
    Human: 215 R
Alignment: 351 R
R    35
-     9
H     9
dtype: int64

R XP_020139390.1 Microcebus murinus
R XP_012496802.1 Propithecus coquereli
H XP_021573646.1 Carlito syrichta
H XP_023373820.1 Otolemur garnettii
H XP_012665677.1 Otolemur garnettii
H XP_021532454.1 Aotus nancymaae
H XP_035141328.1 Callithrix jacchus
H XP_002761791.1 Callithrix jacchus
H XP_039321728.1 Saimiri boliviensis boliviensis
H XP_037583448.1 Cebus imitator
H XP_032107631.1 Sapajus apella
R XP_011810343.1 Colobus angolensis palliatus
R XP_032025606.1 Hylobates moloch
R XP_030676686.1 Nomascus leucogenys
R XP_024092494.1 Pongo abelii
R XP_024092493.1 Pongo abelii
- XP_024206936.1 Pan troglodytes
- NP_001182729.1 Homo sapiens
R NP_001182728.1 Homo sapiens
- NP_001182732.1 Homo sapiens
R XP_011526312.1 Homo sapiens
R NP_001182727.1 Homo sapiens
R NP_000518.1 Homo sapiens
R XP_018871452.1 Gorilla gorilla gorilla
R XP_018871450.1 Gorilla gorilla gorilla
- XP_034800282.1 Pan paniscus
R XP_034800281.1 Pan paniscus
R XP_024206935.1 Pan troglodytes
R XP_024206934.1 Pan troglodytes
R XP_024206933.1 Pan troglodytes
R XP_037848032.1 Chlorocebus sabaeus
R XP_011884149.1 Cercocebus atys
R XP_031790584.1 Piliocolobus tephrosceles
R XP_033056644.1 Trachypithecus francoisi
R XP_030791739.1 Rhinopithecus roxellana
R XP_017724974.1 Rhinopithecus bieti
- XP_011748364.1 Macaca nemestrina
- XP_011850155.1 Mandrillus leucophaeus
- XP_011850148.1 Mandrillus leucophaeus
- XP_025222242.1 Theropithecus gelada
- XP_025222241.1 Theropithecus gelada
R NP_001028078.1 Macaca mulatta
R XP_014978386.2 Macaca mulatta
R XP_028694161.1 Macaca mulatta
R XP_015296177.1 Macaca fascicularis
R XP_005588053.1 Macaca fascicularis
R XP_011850142.1 Mandrillus leucophaeus
R XP_011850140.1 Mandrillus leucophaeus
R XP_011850139.1 Mandrillus leucophaeus
R XP_031515756.1 Papio anubis
R XP_025222240.1 Theropithecus gelada
R XP_025222239.1 Theropithecus gelada
R XP_025222238.1 Theropithecus gelada

(True,
 215,
 'R',
 R    35
 -     9
 H     9
 dtype: int64)

# Validate CPDs

Here we test whether a putative CPD is valid by investigating the vicinity of the sequence, 10 amino acids on either side of the site.

This function pulls out the species and protein IDs showing a particular amino acid at a site.

In [19]:
get_species_with_allele('GBA', translation['NM_000157.4'], 535, 'L')

[('Macaca fascicularis', 'XP_005541629.1'),
 ('Macaca fascicularis', 'XP_005541627.1'),
 ('Macaca fascicularis', 'XP_005541626.1')]

In [20]:
get_species_with_allele('GALT', translation['NM_000155.4'], 23, 'A')

[('Otolemur garnettii', 'XP_003800307.1')]

This function compares the human and nonhuman sequences in the -10 / +10 range.  The output at the bottom shows the numbers of:

* differences between the sequences
* gaps 
* sites out of range

For example, the GBA site at the end means that 9 sites are outside the range.  The GALT sequence shows some aminoacid differences.

In [21]:
local_compare_to_human('GBA', translation['NM_000157.4'], 535, 'XP_005541629.1')

-10 G G
-9 Y Y
-8 S S
-7 I I
-6 H H
-5 T T
-4 Y Y
-3 L L
-2 W W
-1 R C
0 R L
1 Q Q
2 outside sequence
3 outside sequence
4 outside sequence
5 outside sequence
6 outside sequence
7 outside sequence
8 outside sequence
9 outside sequence
10 outside sequence

(1, 0, 9)

In [22]:
local_compare_to_human('GALT', translation['NM_000155.4'], 23, 'XP_003800307.1')

-10 Q Q
-9 A A
-8 S S
-7 E E
-6 A A
-5 D D
-4 A I
-3 A P
-2 A V
-1 A A
0 T A
1 F F
2 R Q
3 A A
4 N S
5 D D
6 H H
7 Q Q
8 H H
9 I I
10 R R

(5, 0, 0)

This function spits out a site by site comparison of the human and nonhuman sequences.  Only the differences are shown.

In [23]:
global_compare_to_human('GBA', translation['NM_000157.4'], 'XP_005541629.1')

5 S -
6 S -
7 P -
10 E K
16 L S
17 S G
24 G A
67 F L
68 D E
70 P L
94 M T
96 P T
101 H R
213 R H
344 V -
345 L -
346 T -
347 D -
348 P -
349 E -
350 A -
351 A -
352 K -
353 Y -
354 V -
355 H -
356 G -
357 I -
358 A -
359 V -
360 H -
361 W -
362 Y -
363 L -
364 D -
365 F -
366 L -
367 A -
368 P -
369 A -
370 K -
371 A -
372 T -
373 L -
374 G -
375 E -
376 T -
377 H -
378 R -
379 L -
380 F -
381 P -
382 N -
383 T -
384 M -
385 L -
386 F -
387 A -
388 S -
389 E -
390 A -
391 C -
392 V -
393 G -
394 S -
395 K -
396 F -
397 W -
398 E -
399 Q -
401 S -
402 V -
403 R -
404 L -
405 G -
406 S -
407 W -
408 D -
409 R -
410 G -
411 M -
412 Q -
413 Y -
414 S -
415 H -
416 S -
417 I -
418 I -
419 T -
452 I V
496 A T
507 A T
546 R C
547 R L

In [24]:
global_compare_to_human('GALT', translation['NM_000155.4'], 'XP_003800307.1')

23 R C
26 T A
28 P L
29 Q D
30 Q R
39 A I
40 A P
41 A V
43 T A
45 R Q
47 N S
106 I T
115 Q H
118 S A
153 K E
154 S A
177 V M
203 A V
216 A S
248 Q R
251 K Q
256 E V
268 L I
269 R K
289 T V
310 P S
360 E A
363 A D
366 N D
669 H C
671 G R
828 T A

In [25]:
get_species_with_allele('CFTR', translation['NM_000492.4'], 13, 'F')

[('Otolemur garnettii', 'XP_003789873.1')]

In [26]:
local_compare_to_human('CFTR', translation['NM_000492.4'], 13, 'XP_003789873.1')

-10 P P
-9 L L
-8 E K
-7 K K
-6 A L
-5 S N
-4 V L
-3 V L
-2 - -
-1 - -
0 S F
1 K F
2 L L
3 F Y
4 F F
5 S S
6 W W
7 T T
8 R R
9 P P
10 I I

(7, 0, 0)

In [28]:
translation['NM_000132.3']

'NP_000123.1'

In [29]:
get_species_with_allele('F8', 'NP_000123.1', 2183, 'V')

[('Hylobates moloch', 'XP_032612179.1')]

In [30]:
local_compare_to_human('F8', 'NP_000123.1', 2183, 'XP_003789873.1')

UnboundLocalError: local variable 'nonaln' referenced before assignment