# Find putative CPDs

## Rerun clean up commands

Since the ClinVar data was modified we begin by rerun the commands in the [clean_up.ipynb](clean_up.ipynb) notebook.

### Extract transcript IDs from variants

Pull the transcript record IDs from the ClinVar records of each gene.

**Output:** `vartranscripts` dictionary with genes as keys and lists of transcripts as values.  The new `dict` has 68 transcripts instead of 72.

In [1]:
import os
os.getcwd()

'c:\\Users\\adesi\\Documents\\GitHub\\kondrashov'

In [1]:
run kondrashov

In [ ]:
import pandas as pd
var = pd.read_csv('pathogenic_lociii/HBB.csv', sep = '\t')
var.head()
#var[var['VariationID,Name']] = var[var['VariationID,Name'].astype(str)]

var.dtypes
var['GeneID']

Type                        str
Name                        str
GeneID                  float64
GeneSymbol                  str
ClinicalSignificance        str
Assembly                    str
VariationID,Name            str
dtype: object

#### Step 1

In [23]:
i = 0
vartranscripts = {}
for gene in lociii:
    vt = get_transcripts_from_variants(gene, True)
    #i += len(vt)    
    print(gene, vt[0], len(vt), 'transcripts')
    vartranscripts.update({gene: vt})

ABCA12 NM_173076.3 1 transcripts
ABCD1 NM_000033.4 1 transcripts
ACAD9 NM_014049.5 1 transcripts
ACADM NM_000016.6 1 transcripts
ACADVL NM_000018.4 1 transcripts
ACAT1 NM_000019.4 1 transcripts
ADA NM_000022.4 1 transcripts
AGL NM_000642.3 1 transcripts
AGXT NM_000030.3 1 transcripts
AHI1 NM_001134831.2 1 transcripts
AIRE NM_000383.4 1 transcripts
ALMS1 NM_001378454.1 1 transcripts
ALOX12B NM_001139.3 1 transcripts
ALPL NM_000478.6 1 transcripts
ANK1 NM_000037.4 1 transcripts
ANO5 NM_213599.3 1 transcripts
APC NM_001127511.3 3 transcripts
AR NM_000044.6 1 transcripts
ARSA NM_000487.6 1 transcripts
ARSB NM_000046.5 1 transcripts
ASL NM_000048.4 1 transcripts
ASPA NM_000049.4 1 transcripts
ASPM NM_018136.5 1 transcripts
ATM NM_000051.4 1 transcripts
ATP7B NM_000053.4 1 transcripts
BBS2 NM_031885.5 1 transcripts
BCKDHA NM_000709.4 1 transcripts
BEST1 NM_004183.4 1 transcripts
BLM NM_000057.4 1 transcripts
BRIP1 NM_032043.3 1 transcripts
BTD NM_001370658.1 1 transcripts
BTK NM_000061.3 1 transcripts
CASR NM_000388.4 1 transcripts
CBS NM_000071.3 1 transcripts
CC2D2A NM_001378615.1 1 transcripts
CDH23 NM_022124.6 1 transcripts
CEP290 NM_025114.4 1 transcripts
CERKL NM_201548.5 1 transcripts
CFTR NM_000492.4 3 transcripts
CHD7 NM_017780.4 1 transcripts
CHEK2 NM_007194.4 1 transcripts
CLN3 NM_001042432.2 1 transcripts
CNGB3 NM_019098.5 1 transcripts
CPS1 NM_001875.5 1 transcripts
CRB1 NM_201253.3 1 transcripts
CTNS NM_004937.3 2 transcripts
CYBB NM_000397.4 1 transcripts
CYP11B1 NM_000497.4 1 transcripts
CYP17A1 NM_000102.4 1 transcripts
CYP27A1 NM_000784.4 1 transcripts
DCLRE1C NM_001033855.3 1 transcripts
DICER1 NM_177438.3 1 transcripts
DUOX2 NM_001363711.2 1 transcripts
EHMT1 NM_024757.5 1 transcripts
ELP1 NM_003640.5 1 transcripts
ERCC6 NM_000124.4 2 transcripts
EVC NM_153717.3 1 transcripts
EVC2 NM_147127.5 1 transcripts
EXT1 NM_000127.3 1 transcripts
EXT2 NM_207122.2 1 transcripts
EYS NM_001142800.2 1 transcripts
F7 NM_000131.5 5 transcripts
F8 NM_000132.4 2 transcripts
F9 NM_000133.4 4 transcripts
FANCA NM_000135.4 1 transcripts
FANCI NM_001113378.2 1 transcripts
FBN2 NM_001999.4 1 transcripts
FKRP NM_024301.5 1 transcripts
FLCN NM_144997.7 1 transcripts
FRAS1 NM_025074.7 1 transcripts
G6PD NM_000402.4 3 transcripts
GAA NM_000152.5 1 transcripts
GALC NM_000153.4 1 transcripts
GALNS NM_000512.5 1 transcripts
GALT NM_000155.4 1 transcripts
GBA1 NM_000157.4 1 transcripts
GBE1 NM_000158.4 1 transcripts
GCDH NM_000159.4 1 transcripts
GJB1 NM_000166.6 2 transcripts
GLB1 NM_000404.4 1 transcripts
GNE NM_001128227.3 2 transcripts
GNPTAB NM_024312.5 1 transcripts
HBB NC_000011.10:g.5227101A>C 11 transcripts
HEXA NM_000520.6 1 transcripts
HEXB NM_000521.4 1 transcripts
HGD NM_000187.4 1 transcripts
HGSNAT NM_152419.3 1 transcripts
HMBS NM_000190.4 1 transcripts
HPRT1 NM_000194.3 3 transcripts
HPS3 NM_032383.5 1 transcripts
IL2RG NM_000206.3 1 transcripts
ITGA2B NM_000419.5 1 transcripts
IVD NM_002225.5 1 transcripts
KCNH2 NM_000238.4 1 transcripts
KCNQ1 NM_000218.3 1 transcripts
KRIT1 NM_194454.3 1 transcripts
L1CAM NM_001278116.2 1 transcripts
LDLR NM_000527.5 2 transcripts
LIPA NM_000235.4 1 transcripts
LOXHD1 NM_001384474.1 1 transcripts
LPL NM_000237.3 1 transcripts
LRPPRC NM_133259.4 1 transcripts
LYST NM_000081.4 1 transcripts
MAN2B1 NM_000528.4 1 transcripts
MCCC1 NM_020166.5 1 transcripts
MCCC2 NM_022132.5 1 transcripts
MED13L NM_015335.5 1 transcripts
MFN2 NM_014874.4 1 transcripts
MKS1 NM_017777.4 1 transcripts
MMUT NM_000255.4 1 transcripts
MPZ NM_000530.8 1 transcripts
MSH2 NM_000251.3 1 transcripts
MTHFR NM_005957.5 1 transcripts
MUTYH NM_001128425.2 2 transcripts
MYH7 NM_000257.4 1 transcripts
NAGLU NM_000263.4 1 transcripts
NF1 NM_001042492.3 1 transcripts
NF2 NM_000268.4 1 transcripts
NIPBL NM_133433.4 1 transcripts
NPC1 NM_000271.5 1 transcripts
NSD1 NM_022455.5 1 transcripts
OCA2 NM_000275.3 1 transcripts
OPA1 NM_130837.3 1 transcripts
PAH NM_000277.3 1 transcripts
PALB2 PALB2:c.2515-1G>T 2 transcripts
PAX3 NM_181457.3 2 transcripts
PAX6 NM_001368894.2 2 transcripts
PCDH15 NM_033056.4 2 transcripts
PCNT NM_006031.6 1 transcripts
PKHD1 NM_138694.4 1 transcripts
PMM2 NM_000303.3 2 transcripts
POMGNT1 NM_017739.4 1 transcripts
PRPF31 NM_015629.4 1 transcripts
PYGM NM_005609.4 1 transcripts
RAD50 NM_005732.4 1 transcripts
RARS2 NM_020320.5 1 transcripts
RECQL4 NM_004260.4 1 transcripts
RHO NM_000539.3 1 transcripts
RP1 NM_001375654.1 2 transcripts
RPGRIP1L NM_015272.5 1 transcripts
SACS NM_014363.6 1 transcripts
SATB2 NM_001172509.2 2 transcripts
SCN4A NM_000334.4 1 transcripts
SERPING1 NC_000011.10:g.57597582C>T 2 transcripts
SGSH NM_000199.5 1 transcripts
SI NM_001041.4 1 transcripts
SLC12A6 NM_001365088.1 1 transcripts
SLC25A13 NM_014251.3 1 transcripts
SLC26A4 NM_000441.2 1 transcripts
SMPD1 NM_000543.5 1 transcripts
SPAST NM_014946.4 1 transcripts
SPG11 NM_025137.4 1 transcripts
SYNE1 NM_182961.4 2 transcripts
TCIRG1 NM_006019.4 1 transcripts
TMC1 NM_138691.3 1 transcripts
TMEM67 NM_153704.6 1 transcripts
TP53 NM_000546.6 1 transcripts
TPP1 NM_000391.4 1 transcripts
TSC1 NM_000368.5 1 transcripts
TTR NM_000371.4 1 transcripts
TYR NM_000372.5 1 transcripts
UNC13D NM_199242.3 1 transcripts
USH1C NM_153676.4 2 transcripts
USH2A NM_206933.4 1 transcripts
VHL NM_000551.4 1 transcripts
VPS13A NM_033305.3 1 transcripts
VPS13B NM_152564.5 2 transcripts
VWF NM_000552.5 1 transcripts
WFS1 NM_006005.3 1 transcripts
WRN NM_000553.6 1 transcripts
WT1 NM_024426.6 1 transcripts
XPC NM_004628.5 1 transcripts
ZEB2 NM_014795.4 1 transcripts
ZFYVE26 NM_015346.4 1 transcripts

In [ ]:
gene = "ABCD1"
vardata = pd.read_csv("pathogenic_lociii/" + gene + ".csv", sep= "\t")
names = vardata["Name"].tolist()

#vardata

for name in names:
    transcript = get_transcript_from_variant(name)
print(name, transcript)

NM_000033.4(ABCD1):c.1256T>C (p.Val419Ala) NM_000033.4

In [24]:
vartranscripts_filtered = {
    gene: [v for v in values if v.startswith("NM_")]
    for gene, values in vartranscripts.items()
}
vartranscripts_filtered

{'ABCA12': ['NM_173076.3'],
 'ABCD1': ['NM_000033.4'],
 'ACAD9': ['NM_014049.5'],
 'ACADM': ['NM_000016.6'],
 'ACADVL': ['NM_000018.4'],
 'ACAT1': ['NM_000019.4'],
 'ADA': ['NM_000022.4'],
 'AGL': ['NM_000642.3'],
 'AGXT': ['NM_000030.3'],
 'AHI1': ['NM_001134831.2'],
 'AIRE': ['NM_000383.4'],
 'ALMS1': ['NM_001378454.1'],
 'ALOX12B': ['NM_001139.3'],
 'ALPL': ['NM_000478.6'],
 'ANK1': ['NM_000037.4'],
 'ANO5': ['NM_213599.3'],
 'APC': ['NM_001127511.3', 'NM_001127510.3', 'NM_000038.6'],
 'AR': ['NM_000044.6'],
 'ARSA': ['NM_000487.6'],
 'ARSB': ['NM_000046.5'],
 'ASL': ['NM_000048.4'],
 'ASPA': ['NM_000049.4'],
 'ASPM': ['NM_018136.5'],
 'ATM': ['NM_000051.4'],
 'ATP7B': ['NM_000053.4'],
 'BBS2': ['NM_031885.5'],
 'BCKDHA': ['NM_000709.4'],
 'BEST1': ['NM_004183.4'],
 'BLM': ['NM_000057.4'],
 'BRIP1': ['NM_032043.3'],
 'BTD': ['NM_001370658.1'],
 'BTK': ['NM_000061.3'],
 'CASR': ['NM_000388.4'],
 'CBS': ['NM_000071.3'],
 'CC2D2A': ['NM_001378615.1'],
 'CDH23': ['NM_022124.6'],
 'CEP290': ['NM_025114.4'],
 'CERKL': ['NM_201548.5'],
 'CFTR': ['NM_000492.4', 'NM_000492.3'],
 'CHD7': ['NM_017780.4'],
 'CHEK2': ['NM_007194.4'],
 'CLN3': ['NM_001042432.2'],
 'CNGB3': ['NM_019098.5'],
 'CPS1': ['NM_001875.5'],
 'CRB1': ['NM_201253.3'],
 'CTNS': ['NM_004937.3'],
 'CYBB': ['NM_000397.4'],
 'CYP11B1': ['NM_000497.4'],
 'CYP17A1': ['NM_000102.4'],
 'CYP27A1': ['NM_000784.4'],
 'DCLRE1C': ['NM_001033855.3'],
 'DICER1': ['NM_177438.3'],
 'DUOX2': ['NM_001363711.2'],
 'EHMT1': ['NM_024757.5'],
 'ELP1': ['NM_003640.5'],
 'ERCC6': ['NM_000124.4', 'NM_001277058.2'],
 'EVC': ['NM_153717.3'],
 'EVC2': ['NM_147127.5'],
 'EXT1': ['NM_000127.3'],
 'EXT2': ['NM_207122.2'],
 'EYS': ['NM_001142800.2'],
 'F7': ['NM_000131.5', 'NM_019616.4', 'NM_000131.4'],
 'F8': ['NM_000132.4'],
 'F9': ['NM_000133.4'],
 'FANCA': ['NM_000135.4'],
 'FANCI': ['NM_001113378.2'],
 'FBN2': ['NM_001999.4'],
 'FKRP': ['NM_024301.5'],
 'FLCN': ['NM_144997.7'],
 'FRAS1': ['NM_025074.7'],
 'G6PD': ['NM_000402.4', 'NM_001360016.2', 'NM_001042351.3'],
 'GAA': ['NM_000152.5'],
 'GALC': ['NM_000153.4'],
 'GALNS': ['NM_000512.5'],
 'GALT': ['NM_000155.4'],
 'GBA1': ['NM_000157.4'],
 'GBE1': ['NM_000158.4'],
 'GCDH': ['NM_000159.4'],
 'GJB1': ['NM_000166.6', 'NM_001097642.3'],
 'GLB1': ['NM_000404.4'],
 'GNE': ['NM_001128227.3', 'NM_005476.7'],
 'GNPTAB': ['NM_024312.5'],
 'HBB': ['NM_000518.4', 'NM_000518.5'],
 'HEXA': ['NM_000520.6'],
 'HEXB': ['NM_000521.4'],
 'HGD': ['NM_000187.4'],
 'HGSNAT': ['NM_152419.3'],
 'HMBS': ['NM_000190.4'],
 'HPRT1': ['NM_000194.3', 'NM_000194.2'],
 'HPS3': ['NM_032383.5'],
 'IL2RG': ['NM_000206.3'],
 'ITGA2B': ['NM_000419.5'],
 'IVD': ['NM_002225.5'],
 'KCNH2': ['NM_000238.4'],
 'KCNQ1': ['NM_000218.3'],
 'KRIT1': ['NM_194454.3'],
 'L1CAM': ['NM_001278116.2'],
 'LDLR': ['NM_000527.5', 'NM_000527.4'],
 'LIPA': ['NM_000235.4'],
 'LOXHD1': ['NM_001384474.1'],
 'LPL': ['NM_000237.3'],
 'LRPPRC': ['NM_133259.4'],
 'LYST': ['NM_000081.4'],
 'MAN2B1': ['NM_000528.4'],
 'MCCC1': ['NM_020166.5'],
 'MCCC2': ['NM_022132.5'],
 'MED13L': ['NM_015335.5'],
 'MFN2': ['NM_014874.4'],
 'MKS1': ['NM_017777.4'],
 'MMUT': ['NM_000255.4'],
 'MPZ': ['NM_000530.8'],
 'MSH2': ['NM_000251.3'],
 'MTHFR': ['NM_005957.5'],
 'MUTYH': ['NM_001128425.2', 'NM_001048174.2'],
 'MYH7': ['NM_000257.4'],
 'NAGLU': ['NM_000263.4'],
 'NF1': ['NM_001042492.3'],
 'NF2': ['NM_000268.4'],
 'NIPBL': ['NM_133433.4'],
 'NPC1': ['NM_000271.5'],
 'NSD1': ['NM_022455.5'],
 'OCA2': ['NM_000275.3'],
 'OPA1': ['NM_130837.3'],
 'PAH': ['NM_000277.3'],
 'PALB2': ['NM_024675.4'],
 'PAX3': ['NM_181457.3', 'NM_181458.4'],
 'PAX6': ['NM_001368894.2', 'NM_000280.6'],
 'PCDH15': ['NM_033056.4', 'NM_001384140.1'],
 'PCNT': ['NM_006031.6'],
 'PKHD1': ['NM_138694.4'],
 'PMM2': ['NM_000303.3'],
 'POMGNT1': ['NM_017739.4'],
 'PRPF31': ['NM_015629.4'],
 'PYGM': ['NM_005609.4'],
 'RAD50': ['NM_005732.4'],
 'RARS2': ['NM_020320.5'],
 'RECQL4': ['NM_004260.4'],
 'RHO': ['NM_000539.3'],
 'RP1': ['NM_001375654.1', 'NM_006269.2'],
 'RPGRIP1L': ['NM_015272.5'],
 'SACS': ['NM_014363.6'],
 'SATB2': ['NM_001172509.2', 'NM_001172517.1'],
 'SCN4A': ['NM_000334.4'],
 'SERPING1': ['NM_000062.3'],
 'SGSH': ['NM_000199.5'],
 'SI': ['NM_001041.4'],
 'SLC12A6': ['NM_001365088.1'],
 'SLC25A13': ['NM_014251.3'],
 'SLC26A4': ['NM_000441.2'],
 'SMPD1': ['NM_000543.5'],
 'SPAST': ['NM_014946.4'],
 'SPG11': ['NM_025137.4'],
 'SYNE1': ['NM_182961.4', 'NM_001347702.2'],
 'TCIRG1': ['NM_006019.4'],
 'TMC1': ['NM_138691.3'],
 'TMEM67': ['NM_153704.6'],
 'TP53': ['NM_000546.6'],
 'TPP1': ['NM_000391.4'],
 'TSC1': ['NM_000368.5'],
 'TTR': ['NM_000371.4'],
 'TYR': ['NM_000372.5'],
 'UNC13D': ['NM_199242.3'],
 'USH1C': ['NM_153676.4', 'NM_005709.4'],
 'USH2A': ['NM_206933.4'],
 'VHL': ['NM_000551.4'],
 'VPS13A': ['NM_033305.3'],
 'VPS13B': ['NM_152564.5', 'NM_017890.5'],
 'VWF': ['NM_000552.5'],
 'WFS1': ['NM_006005.3'],
 'WRN': ['NM_000553.6'],
 'WT1': ['NM_024426.6'],
 'XPC': ['NM_004628.5'],
 'ZEB2': ['NM_014795.4'],
 'ZFYVE26': ['NM_015346.4']}

### Step 2
##### Extract human protein sequence records from the fasta files

Take the fasta files containing ortholog sequences, search for human sequences and extract the corresponding record.

**Output:** `protrecs` dictionary with genes as keys and lists of protein records as values. Unchanged.

In [26]:
import os
#os.listdir('fasta_lociii_match')
#os.getcwd()
os.listdir('fasta_lociii_match')

['VWF_NP_000543.3_match.fasta',
 'USH1C_NP_005700.2_match.fasta',
 'RHO_NP_000530.1_match.fasta',
 'NF2_NP_000259.1_match.fasta',
 'PKHD1_NP_619639.3_match.fasta',
 'EYS_NP_001136272.1_match.fasta',
 'ASPA_NP_000040.1_match.fasta',
 'CBS_NP_000062.1_match.fasta',
 'BBS2_NP_114091.4_match.fasta',
 'ATP7B_NP_000044.2_match.fasta',
 'CPS1_NP_001866.2_match.fasta',
 'RP1_NP_006260.1_match.fasta',
 'ASPM_NP_060606.3_match.fasta',
 'IVD_NP_002216.3_match.fasta',
 'MFN2_NP_055689.1_match.fasta',
 'ATM_NP_000042.3_match.fasta',
 'VPS13A_NP_150648.2_match.fasta',
 'PALB2_NP_078951.2_match.fasta',
 'MCCC1_NP_064551.3_match.fasta',
 'AGL_NP_000633.2_match.fasta',
 'BTD_NP_001357587.1_match.fasta',
 'EXT2_NP_997005.1_match.fasta',
 'CDH23_NP_071407.4_match.fasta',
 'LDLR_NP_000518.1_match.fasta',
 'PRPF31_NP_056444.3_match.fasta',
 'BLM_NP_000048.1_match.fasta',
 'FLCN_NP_659434.2_match.fasta',
 'CASR_NP_000379.3_match.fasta',
 'GBE1_NP_000149.4_match.fasta',
 '.DS_Store',
 'CYBB_NP_000388.2_match.fasta',
 'UNC13D_NP_954712.1_match.fasta',
 'FRAS1_NP_079350.5_match.fasta',
 'MSH2_NP_000242.1_match.fasta',
 'ASL_NP_000039.2_match.fasta',
 'PCDH15_NP_001371069.1_match.fasta',
 'MPZ_NP_000521.2_match.fasta',
 'CYP17A1_NP_000093.1_match.fasta',
 'SMPD1_NP_000534.3_match.fasta',
 'ALPL_NP_000469.3_match.fasta',
 'OCA2_NP_000266.2_match.fasta',
 'MUTYH_NP_001041639.1_match.fasta',
 'GNPTAB_NP_077288.2_match.fasta',
 'HPRT1_NP_000185.1_match.fasta',
 'HGSNAT_NP_689632.2_match.fasta',
 'VHL_NP_000542.1_match.fasta',
 'OPA1_NP_570850.2_match.fasta',
 'RECQL4_NP_004251.4_match.fasta',
 'EVC2_NP_667338.3_match.fasta',
 'LYST_NP_000072.2_match.fasta',
 'ALMS1_NP_001365383.1_match.fasta',
 'WRN_NP_000544.2_match.fasta',
 'SERPING1_NP_000053.2_match.fasta',
 'LOXHD1_NP_001371403.1_match.fasta',
 'AR_NP_000035.2_match.fasta',
 'PAX3_NP_852122.1_match.fasta',
 'FKRP_NP_077277.1_match.fasta',
 'CYP27A1_NP_000775.1_match.fasta',
 'APC_NP_001120982.1_match.fasta',
 'SI_NP_001032.2_match.fasta',
 'GALC_NP_000144.2_match.fasta',
 'G6PD_NP_000393.4_match.fasta',
 'MAN2B1_NP_000519.2_match.fasta',
 'KCNH2_NP_000229.1_match.fasta',
 'F8_NP_000123.1_match.fasta',
 'RARS2_NP_064716.2_match.fasta',
 'MMUT_NP_000246.2_match.fasta',
 'GNE_NP_001121699.1_match.fasta',
 'GJB1_NP_001091111.1_match.fasta',
 'SATB2_NP_001165980.1_match.fasta',
 'CHEK2_NP_009125.1_match.fasta',
 'ANK1_NP_000028.3_match.fasta',
 'MED13L_NP_056150.1_match.fasta',
 'ARSB_NP_000037.2_match.fasta',
 'USH1C_NP_710142.1_match.fasta',
 'TMC1_NP_619636.2_match.fasta',
 'XPC_NP_004619.3_match.fasta',
 'CRB1_NP_957705.1_match.fasta',
 'ACAD9_NP_054768.2_match.fasta',
 'SPAST_NP_055761.2_match.fasta',
 'GCDH_NP_000150.1_match.fasta',
 'HGD_NP_000178.2_match.fasta',
 'VPS13B_NP_060360.3_match.fasta',
 'TTR_NP_000362.1_match.fasta',
 'ELP1_NP_003631.2_match.fasta',
 'ERCC6_NP_001263987.1_match.fasta',
 'SPG11_NP_079413.3_match.fasta',
 'KCNQ1_NP_000209.2_match.fasta',
 'PAX6_NP_001355823.1_match.fasta',
 'AHI1_NP_001128303.1_match.fasta',
 'ADA_NP_000013.2_match.fasta',
 'GALT_NP_000146.2_match.fasta',
 'RP1_NP_001362583.1_match.fasta',
 'L1CAM_NP_001265045.1_match.fasta',
 'CERKL_NP_963842.1_match.fasta',
 'CNGB3_NP_061971.3_match.fasta',
 'NSD1_NP_071900.2_match.fasta',
 'MTHFR_NP_005948.3_match.fasta',
 'ALOX12B_NP_001130.1_match.fasta',
 'TMEM67_NP_714915.3_match.fasta',
 'EXT1_NP_000118.2_match.fasta',
 'LPL_NP_000228.1_match.fasta',
 'GBA1_NP_000148.2_match.fasta',
 'HEXA_NP_000511.2_match.fasta',
 'TP53_NP_000537.3_match.fasta',
 'CHD7_NP_060250.2_match.fasta',
 'PYGM_NP_005600.1_match.fasta',
 'FBN2_NP_001990.2_match.fasta',
 'SGSH_NP_000190.1_match.fasta',
 'SCN4A_NP_000325.4_match.fasta',
 'DICER1_NP_803187.1_match.fasta',
 'MKS1_NP_060247.2_match.fasta',
 'KRIT1_NP_919436.1_match.fasta',
 'WFS1_NP_005996.2_match.fasta',
 'F7_NP_062562.1_match.fasta',
 'CEP290_NP_079390.3_match.fasta',
 'EHMT1_NP_079033.4_match.fasta',
 'RAD50_NP_005723.2_match.fasta',
 'GALNS_NP_000503.1_match.fasta',
 'PAH_NP_000268.1_match.fasta',
 'G6PD_NP_001346945.1_match.fasta',
 'PCNT_NP_006022.3_match.fasta',
 'SLC12A6_NP_001352017.1_match.fasta',
 'APC_NP_000029.2_match.fasta',
 'DUOX2_NP_001350640.1_match.fasta',
 'FANCI_NP_001106849.1_match.fasta',
 'HMBS_NP_000181.2_match.fasta',
 'EVC_NP_714928.1_match.fasta',
 'ABCA12_NP_775099.2_match.fasta',
 'DCLRE1C_NP_001029027.1_match.fasta',
 'GLB1_NP_000395.3_match.fasta',
 'LRPPRC_NP_573566.2_match.fasta',
 'USH2A_NP_996816.3_match.fasta',
 'BTK_NP_000052.1_match.fasta',
 'ITGA2B_NP_000410.2_match.fasta',
 'RPGRIP1L_NP_056087.2_match.fasta',
 'F7_NP_000122.1_match.fasta',
 'VPS13B_NP_689777.3_match.fasta',
 'PAX3_NP_852123.1_match.fasta',
 'CYP11B1_NP_000488.3_match.fasta',
 'IL2RG_NP_000197.1_match.fasta',
 'SYNE1_NP_892006.3_match.fasta',
 'G6PD_NP_001035810.1_match.fasta',
 'ACAT1_NP_000010.1_match.fasta',
 'ERCC6_NP_000115.1_match.fasta',
 'AGXT_NP_000021.1_match.fasta',
 'CLN3_NP_001035897.1_match.fasta',
 'HPS3_NP_115759.2_match.fasta',
 'APC_NP_001120983.2_match.fasta',
 'BRIP1_NP_114432.2_match.fasta',
 'SATB2_NP_001165988.1_match.fasta',
 'LIPA_NP_000226.2_match.fasta',
 'PCDH15_NP_149045.3_match.fasta',
 'MCCC2_NP_071415.1_match.fasta',
 'TCIRG1_NP_006010.2_match.fasta',
 'HEXB_NP_000512.2_match.fasta',
 'SYNE1_NP_001334631.1_match.fasta',
 'ZEB2_NP_055610.1_match.fasta',
 'BCKDHA_NP_000700.1_match.fasta',
 'NAGLU_NP_000254.2_match.fasta',
 'MUTYH_NP_001121897.1_match.fasta',
 'SACS_NP_055178.3_match.fasta',
 'PMM2_NP_000294.1_match.fasta',
 'WT1_NP_077744.4_match.fasta',
 'NIPBL_NP_597677.2_match.fasta',
 'ANO5_NP_998764.1_match.fasta',
 'NF1_NP_001035957.1_match.fasta',
 'GAA_NP_000143.2_match.fasta',
 'GNE_NP_005467.1_match.fasta',
 'F9_NP_000124.1_match.fasta',
 'TSC1_NP_000359.1_match.fasta',
 'HBB_NP_000509.1_match.fasta',
 'NPC1_NP_000262.2_match.fasta',
 'FANCA_NP_000126.2_match.fasta',
 'ACADM_NP_000007.1_match.fasta',
 'GJB1_NP_000157.1_match.fasta',
 'TYR_NP_000363.1_match.fasta',
 'ACADVL_NP_000009.1_match.fasta',
 'ZFYVE26_NP_056161.2_match.fasta',
 'MYH7_NP_000248.2_match.fasta',
 'BEST1_NP_004174.1_match.fasta',
 'SLC25A13_NP_055066.1_match.fasta',
 'POMGNT1_NP_060209.4_match.fasta',
 'CTNS_NP_004928.2_match.fasta',
 'TPP1_NP_000382.3_match.fasta',
 'CC2D2A_NP_001365544.1_match.fasta',
 'CFTR_NP_000483.3_match.fasta',
 'SLC26A4_NP_000432.1_match.fasta',
 'ABCD1_NP_000024.2_match.fasta',
 'AIRE_NP_000374.1_match.fasta',
 'ARSA_NP_000478.3_match.fasta',
 'PAX6_NP_000271.1_match.fasta']

In [ ]:
#skip!

#loci = ['ABCD1', 'ALPL', 'AR', 'ATP7B']
i = 1
protrecs = {}
for gene in loci:
    protrecs.update({gene: []})
    for record in SeqIO.parse('fasta_lociii_match/{gene}.fasta', 'fasta'):
        sp = get_species(record)
        if sp=='Homo sapiens':
            protrecs[gene].append(record)
            print(i, gene, record.id, len(record))
            i += 1

FileNotFoundError: [Errno 2] No such file or directory: 'fasta_lociii_match/{gene}.fasta'

### This code works for fasta_match/ directory which has a different naming scheme

In [27]:
import os
from Bio import SeqIO

protrecs = {}
i = 1
for filename in os.listdir("fasta_lociii_match"):
    if not filename.endswith(".fasta"):
        continue
    gene = filename.split("_")[0]
    protrecs.setdefault(gene, [])
    filepath = os.path.join("fasta_lociii_match", filename)

    for record in SeqIO.parse(filepath, "fasta"):
        if get_species(record) == "Homo sapiens":
            protrecs[gene].append(record)
            print(i, gene, record.id, len(record))
            i += 1

1 VWF NP_000543.3 2813
2 USH1C NP_005700.2 552
3 RHO NP_000530.1 348
4 NF2 NP_000259.1 595
5 PKHD1 NP_619639.3 4074
6 EYS NP_001136272.1 3144
7 ASPA NP_000040.1 313
8 CBS NP_000062.1 551
9 BBS2 NP_001364385.1 721
10 ATP7B NP_000044.2 1465
11 RP1 NP_006260.1 2156
12 ASPM NP_060606.3 3477
13 IVD NP_002216.3 423
14 MFN2 NP_001121132.1 757
15 ATM NP_000042.3 3056
16 VPS13A NP_150648.2 3174
17 PALB2 NP_078951.2 1186
18 MCCC1 NP_064551.3 725
19 AGL NP_000019.2 1532
20 BTD NP_001268652.2 523
21 EXT2 NP_001376557.1 718
22 CDH23 NP_071407.4 3354
23 LDLR NP_000518.1 860
24 PRPF31 NP_056444.3 499
25 BLM NP_000048.1 1417
26 FLCN NP_001340159.1 579
27 CASR NP_000379.3 1078
28 GBE1 NP_000149.4 702
29 CYBB NP_000388.2 570
30 UNC13D NP_954712.1 1090
31 FRAS1 NP_079350.5 4012
32 MSH2 NP_000242.1 934
33 ASL NP_000039.2 464
34 PCDH15 NP_001371069.1 1740
35 MPZ NP_000521.2 248
36 CYP17A1 NP_000093.1 508
37 SMPD1 NP_000534.3 631
38 ALPL NP_000469.3 524
39 OCA2 NP_000266.2 838
40 MUTYH NP_001041636.2 521
41 GNPTAB NP_077288.2 1256
42 HPRT1 NP_000185.1 218
43 HGSNAT NP_689632.2 635
44 VHL NP_000542.1 213
45 OPA1 NP_570850.2 1015
46 RECQL4 NP_004251.4 1208
47 EVC2 NP_667338.3 1308
48 LYST NP_000072.2 3801
49 ALMS1 NP_001365383.1 4168
50 WRN NP_000544.2 1432
51 SERPING1 NP_000053.2 500
52 LOXHD1 NP_001371403.1 2273
53 AR NP_000035.2 920
54 PAX3 NP_852122.1 479
55 FKRP NP_001034974.1 495
56 CYP27A1 NP_000775.1 531
57 APC NP_000029.2 2843
58 SI NP_001032.2 1827
59 GALC NP_000144.2 685
60 G6PD NP_000393.4 545
61 MAN2B1 NP_000519.2 1011
62 KCNH2 NP_000229.1 1159
63 F8 NP_000123.1 2351
64 RARS2 NP_064716.2 578
65 MMUT NP_000246.2 750
66 GNE NP_001121699.1 753
67 GJB1 NP_000157.1 283
68 SATB2 NP_001165980.1 733
69 CHEK2 NP_009125.1 543
70 ANK1 NP_000028.3 1880
71 MED13L NP_056150.1 2210
72 ARSB NP_000037.2 533
73 USH1C NP_710142.1 899
74 TMC1 NP_619636.2 760
75 XPC NP_004619.3 940
76 CRB1 NP_957705.1 1406
77 ACAD9 NP_054768.2 621
78 SPAST NP_055761.2 616
79 GCDH NP_000150.1 438
80 HGD NP_000178.2 445
81 VPS13B NP_060360.3 4022
82 TTR NP_000362.1 147
83 ELP1 NP_003631.2 1332
84 ERCC6 NP_001263987.1 1061
85 SPG11 NP_079413.3 2443
86 KCNQ1 NP_000209.2 676
87 PAX6 NP_001245391.1 436
88 AHI1 NP_001128302.1 1196
89 ADA NP_000013.2 363
90 GALT NP_000146.2 379
91 RP1 NP_001362583.1 1383
92 L1CAM NP_000416.1 1257
93 CERKL NP_963842.1 532
94 CNGB3 NP_061971.3 809
95 NSD1 NP_001396230.1 2696
96 MTHFR NP_005948.3 656
97 ALOX12B NP_001130.1 701
98 TMEM67 NP_714915.3 995
99 EXT1 NP_000118.2 746
100 LPL NP_000228.1 475
101 GBA1 NP_000148.2 536
102 HEXA NP_000511.2 529
103 TP53 NP_000537.3 393
104 CHD7 NP_060250.2 2997
105 PYGM NP_005600.1 842
106 FBN2 NP_001990.2 2912
107 SGSH NP_000190.1 502
108 SCN4A NP_000325.4 1836
109 DICER1 NP_001258211.1 1922
110 MKS1 NP_060247.2 559
111 KRIT1 NP_001337601.1 736
112 WFS1 NP_001139325.1 890
113 F7 NP_062562.1 444
114 CEP290 NP_079390.3 2479
115 EHMT1 NP_079033.4 1298
116 RAD50 NP_005723.2 1312
117 GALNS NP_000503.1 522
118 PAH NP_000268.1 452
119 G6PD NP_001035810.1 515
120 PCNT NP_006022.3 3336
121 SLC12A6 NP_001352017.1 1150
122 APC NP_000029.2 2843
123 DUOX2 NP_001350640.1 1548
124 FANCI NP_001106849.1 1328
125 HMBS NP_000181.2 361
126 EVC NP_714928.1 992
127 ABCA12 NP_775099.2 2595
128 DCLRE1C NP_001029027.1 692
129 GLB1 NP_000395.3 677
130 LRPPRC NP_573566.2 1394
131 USH2A NP_996816.3 5202
132 BTK NP_000052.1 659
133 ITGA2B NP_000410.2 1039
134 RPGRIP1L NP_056087.2 1315
135 F7 NP_000122.1 466
136 VPS13B NP_689777.3 3997
137 PAX3 NP_852123.1 484
138 CYP11B1 NP_000488.3 503
139 IL2RG NP_000197.1 369
140 SYNE1 NP_892006.3 8797
141 G6PD NP_001035810.1 515
142 ACAT1 NP_000010.1 427
143 ERCC6 NP_000115.1 1493
144 AGXT NP_000021.1 392
145 CLN3 NP_000077.1 438
146 HPS3 NP_115759.2 1004
147 APC NP_001120983.2 2825
148 BRIP1 NP_114432.2 1249
149 SATB2 NP_001165980.1 733
150 LIPA NP_000226.2 399
151 PCDH15 NP_149045.3 1955
152 MCCC2 NP_071415.1 563
153 TCIRG1 NP_001427481.1 830
154 HEXB NP_000512.2 556
155 SYNE1 NP_001334631.1 975
156 ZEB2 NP_055610.1 1214
157 BCKDHA NP_000700.1 445
158 NAGLU NP_000254.2 743
159 MUTYH NP_001121897.1 549
160 SACS NP_055178.3 4579
161 PMM2 NP_000294.1 246
162 WT1 NP_077744.4 522
163 NIPBL NP_597677.2 2804
164 ANO5 NP_998764.1 913
165 NF1 NP_001035957.1 2839
166 GAA NP_000143.2 952
167 GNE NP_005467.1 722
168 F9 NP_000124.1 461
169 TSC1 NP_000359.1 1164
170 HBB NP_000509.1 147
171 NPC1 NP_000262.2 1278
172 FANCA NP_000126.2 1455
173 ACADM NP_000007.1 421
174 GJB1 NP_000157.1 283
175 TYR NP_000363.1 529
176 ACADVL NP_000009.1 655
177 ZFYVE26 NP_056161.2 2539
178 MYH7 NP_000248.2 1935
179 BEST1 NP_004174.1 585
180 SLC25A13 NP_055066.1 675
181 POMGNT1 NP_001424582.1 660
182 CTNS NP_004928.2 367
183 TPP1 NP_000382.3 563
184 CC2D2A NP_001073991.2 1620
185 CFTR NP_000483.3 1480
186 SLC26A4 NP_000432.1 780
187 ABCD1 NP_000024.2 745
188 AIRE NP_000374.1 545
189 ARSA NP_000478.3 509
190 PAX6 NP_000271.1 422

In [83]:
xx = protrecs['TYR'][0]
#print(xx)
#print(protrecs['TYR'][0])
type(xx)
xx[0:10]

protrecs['AGL']

[SeqRecord(seq=Seq('MGHSKQIRILLLNEMEKLEKTLFRLEQGYELQFRLGPTLQGKAVTVYTNYPFPG...YDL'), id='NP_000019.2', name='NP_000019.2', description='NP_000019.2 glycogen debranching enzyme isoform 1 [Homo sapiens]', dbxrefs=[])]

### STEP 3 
##### Match variant transcript IDs with ortholog proteins

Take variant transcript ID, query the NCBI database, extract the corresponding protein, and look for it in the ortholog set.  Flag problems.

**Output:** `translation` dictionary with transcript IDs as keys and lists of protein IDs as values.

In [50]:
vartranscripts_filtered
#transcript

{'ABCA12': ['NM_173076.3'],
 'ABCD1': ['NM_000033.4'],
 'ACAD9': ['NM_014049.5'],
 'ACADM': ['NM_000016.6'],
 'ACADVL': ['NM_000018.4'],
 'ACAT1': ['NM_000019.4'],
 'ADA': ['NM_000022.4'],
 'AGL': ['NM_000642.3'],
 'AGXT': ['NM_000030.3'],
 'AHI1': ['NM_001134831.2'],
 'AIRE': ['NM_000383.4'],
 'ALMS1': ['NM_001378454.1'],
 'ALOX12B': ['NM_001139.3'],
 'ALPL': ['NM_000478.6'],
 'ANK1': ['NM_000037.4'],
 'ANO5': ['NM_213599.3'],
 'APC': ['NM_001127511.3', 'NM_001127510.3', 'NM_000038.6'],
 'AR': ['NM_000044.6'],
 'ARSA': ['NM_000487.6'],
 'ARSB': ['NM_000046.5'],
 'ASL': ['NM_000048.4'],
 'ASPA': ['NM_000049.4'],
 'ASPM': ['NM_018136.5'],
 'ATM': ['NM_000051.4'],
 'ATP7B': ['NM_000053.4'],
 'BBS2': ['NM_031885.5'],
 'BCKDHA': ['NM_000709.4'],
 'BEST1': ['NM_004183.4'],
 'BLM': ['NM_000057.4'],
 'BRIP1': ['NM_032043.3'],
 'BTD': ['NM_001370658.1'],
 'BTK': ['NM_000061.3'],
 'CASR': ['NM_000388.4'],
 'CBS': ['NM_000071.3'],
 'CC2D2A': ['NM_001378615.1'],
 'CDH23': ['NM_022124.6'],
 'CEP290': ['NM_025114.4'],
 'CERKL': ['NM_201548.5'],
 'CFTR': ['NM_000492.4', 'NM_000492.3'],
 'CHD7': ['NM_017780.4'],
 'CHEK2': ['NM_007194.4'],
 'CLN3': ['NM_001042432.2'],
 'CNGB3': ['NM_019098.5'],
 'CPS1': ['NM_001875.5'],
 'CRB1': ['NM_201253.3'],
 'CTNS': ['NM_004937.3'],
 'CYBB': ['NM_000397.4'],
 'CYP11B1': ['NM_000497.4'],
 'CYP17A1': ['NM_000102.4'],
 'CYP27A1': ['NM_000784.4'],
 'DCLRE1C': ['NM_001033855.3'],
 'DICER1': ['NM_177438.3'],
 'DUOX2': ['NM_001363711.2'],
 'EHMT1': ['NM_024757.5'],
 'ELP1': ['NM_003640.5'],
 'ERCC6': ['NM_000124.4', 'NM_001277058.2'],
 'EVC': ['NM_153717.3'],
 'EVC2': ['NM_147127.5'],
 'EXT1': ['NM_000127.3'],
 'EXT2': ['NM_207122.2'],
 'EYS': ['NM_001142800.2'],
 'F7': ['NM_000131.5', 'NM_019616.4', 'NM_000131.4'],
 'F8': ['NM_000132.4'],
 'F9': ['NM_000133.4'],
 'FANCA': ['NM_000135.4'],
 'FANCI': ['NM_001113378.2'],
 'FBN2': ['NM_001999.4'],
 'FKRP': ['NM_024301.5'],
 'FLCN': ['NM_144997.7'],
 'FRAS1': ['NM_025074.7'],
 'G6PD': ['NM_000402.4', 'NM_001360016.2', 'NM_001042351.3'],
 'GAA': ['NM_000152.5'],
 'GALC': ['NM_000153.4'],
 'GALNS': ['NM_000512.5'],
 'GALT': ['NM_000155.4'],
 'GBA1': ['NM_000157.4'],
 'GBE1': ['NM_000158.4'],
 'GCDH': ['NM_000159.4'],
 'GJB1': ['NM_000166.6', 'NM_001097642.3'],
 'GLB1': ['NM_000404.4'],
 'GNE': ['NM_001128227.3', 'NM_005476.7'],
 'GNPTAB': ['NM_024312.5'],
 'HBB': ['NM_000518.4', 'NM_000518.5'],
 'HEXA': ['NM_000520.6'],
 'HEXB': ['NM_000521.4'],
 'HGD': ['NM_000187.4'],
 'HGSNAT': ['NM_152419.3'],
 'HMBS': ['NM_000190.4'],
 'HPRT1': ['NM_000194.3', 'NM_000194.2'],
 'HPS3': ['NM_032383.5'],
 'IL2RG': ['NM_000206.3'],
 'ITGA2B': ['NM_000419.5'],
 'IVD': ['NM_002225.5'],
 'KCNH2': ['NM_000238.4'],
 'KCNQ1': ['NM_000218.3'],
 'KRIT1': ['NM_194454.3'],
 'L1CAM': ['NM_001278116.2'],
 'LDLR': ['NM_000527.5', 'NM_000527.4'],
 'LIPA': ['NM_000235.4'],
 'LOXHD1': ['NM_001384474.1'],
 'LPL': ['NM_000237.3'],
 'LRPPRC': ['NM_133259.4'],
 'LYST': ['NM_000081.4'],
 'MAN2B1': ['NM_000528.4'],
 'MCCC1': ['NM_020166.5'],
 'MCCC2': ['NM_022132.5'],
 'MED13L': ['NM_015335.5'],
 'MFN2': ['NM_014874.4'],
 'MKS1': ['NM_017777.4'],
 'MMUT': ['NM_000255.4'],
 'MPZ': ['NM_000530.8'],
 'MSH2': ['NM_000251.3'],
 'MTHFR': ['NM_005957.5'],
 'MUTYH': ['NM_001128425.2', 'NM_001048174.2'],
 'MYH7': ['NM_000257.4'],
 'NAGLU': ['NM_000263.4'],
 'NF1': ['NM_001042492.3'],
 'NF2': ['NM_000268.4'],
 'NIPBL': ['NM_133433.4'],
 'NPC1': ['NM_000271.5'],
 'NSD1': ['NM_022455.5'],
 'OCA2': ['NM_000275.3'],
 'OPA1': ['NM_130837.3'],
 'PAH': ['NM_000277.3'],
 'PALB2': ['NM_024675.4'],
 'PAX3': ['NM_181457.3', 'NM_181458.4'],
 'PAX6': ['NM_001368894.2', 'NM_000280.6'],
 'PCDH15': ['NM_033056.4', 'NM_001384140.1'],
 'PCNT': ['NM_006031.6'],
 'PKHD1': ['NM_138694.4'],
 'PMM2': ['NM_000303.3'],
 'POMGNT1': ['NM_017739.4'],
 'PRPF31': ['NM_015629.4'],
 'PYGM': ['NM_005609.4'],
 'RAD50': ['NM_005732.4'],
 'RARS2': ['NM_020320.5'],
 'RECQL4': ['NM_004260.4'],
 'RHO': ['NM_000539.3'],
 'RP1': ['NM_001375654.1', 'NM_006269.2'],
 'RPGRIP1L': ['NM_015272.5'],
 'SACS': ['NM_014363.6'],
 'SATB2': ['NM_001172509.2', 'NM_001172517.1'],
 'SCN4A': ['NM_000334.4'],
 'SERPING1': ['NM_000062.3'],
 'SGSH': ['NM_000199.5'],
 'SI': ['NM_001041.4'],
 'SLC12A6': ['NM_001365088.1'],
 'SLC25A13': ['NM_014251.3'],
 'SLC26A4': ['NM_000441.2'],
 'SMPD1': ['NM_000543.5'],
 'SPAST': ['NM_014946.4'],
 'SPG11': ['NM_025137.4'],
 'SYNE1': ['NM_182961.4', 'NM_001347702.2'],
 'TCIRG1': ['NM_006019.4'],
 'TMC1': ['NM_138691.3'],
 'TMEM67': ['NM_153704.6'],
 'TP53': ['NM_000546.6'],
 'TPP1': ['NM_000391.4'],
 'TSC1': ['NM_000368.5'],
 'TTR': ['NM_000371.4'],
 'TYR': ['NM_000372.5'],
 'UNC13D': ['NM_199242.3'],
 'USH1C': ['NM_153676.4', 'NM_005709.4'],
 'USH2A': ['NM_206933.4'],
 'VHL': ['NM_000551.4'],
 'VPS13A': ['NM_033305.3'],
 'VPS13B': ['NM_152564.5', 'NM_017890.5'],
 'VWF': ['NM_000552.5'],
 'WFS1': ['NM_006005.3'],
 'WRN': ['NM_000553.6'],
 'WT1': ['NM_024426.6'],
 'XPC': ['NM_004628.5'],
 'ZEB2': ['NM_014795.4'],
 'ZFYVE26': ['NM_015346.4']}

In [ ]:
#%%time
translation = {}
i = 1
for gene in lociii:
    for transcript in vartranscripts_filtered[gene]:
        if transcript[:3] == 'NM_':
            rec = get_transcript(transcript)
            seq = get_CDS(rec)
            match = False
            for prot in protrecs[gene]: 
                if seq[4] == prot.seq:
                    print(i, gene, transcript, prot.id)
                    match = True
                    translation.update({transcript: prot.id})
            if not match:
                print(i, gene, transcript, 'no matching protein         <<<<<')
        else:
            print(i, gene, transcript, 'invalid transcript name         *****')
        i += 1

1 ABCA12 NM_173076.3 NP_775099.2
2 ABCD1 NM_000033.4 NP_000024.2
3 ACAD9 NM_014049.5 NP_054768.2
4 ACADM NM_000016.6 NP_000007.1
5 ACADVL NM_000018.4 NP_000009.1
6 ACAT1 NM_000019.4 NP_000010.1
7 ADA NM_000022.4 NP_000013.2
8 AGL NM_000642.3 NP_000019.2
9 AGXT NM_000030.3 NP_000021.1
10 AHI1 NM_001134831.2 NP_001128302.1
11 AIRE NM_000383.4 NP_000374.1
12 ALMS1 NM_001378454.1 NP_001365383.1
13 ALOX12B NM_001139.3 NP_001130.1
14 ALPL NM_000478.6 NP_000469.3
15 ANK1 NM_000037.4 NP_000028.3
16 ANO5 NM_213599.3 NP_998764.1
17 APC NM_001127511.3 NP_001120983.2
18 APC NM_001127510.3 NP_000029.2
18 APC NM_001127510.3 NP_000029.2
19 APC NM_000038.6 NP_000029.2
19 APC NM_000038.6 NP_000029.2
20 AR NM_000044.6 NP_000035.2
21 ARSA NM_000487.6 NP_000478.3
22 ARSB NM_000046.5 NP_000037.2
23 ASL NM_000048.4 NP_000039.2
24 ASPA NM_000049.4 NP_000040.1
25 ASPM NM_018136.5 NP_060606.3
26 ATM NM_000051.4 NP_000042.3
27 ATP7B NM_000053.4 NP_000044.2
28 BBS2 NM_031885.5 NP_001364385.1
29 BCKDHA NM_000709.4 NP_000700.1
30 BEST1 NM_004183.4 NP_004174.1
31 BLM NM_000057.4 NP_000048.1
32 BRIP1 NM_032043.3 NP_114432.2
33 BTD NM_001370658.1 NP_001268652.2
34 BTK NM_000061.3 NP_000052.1
35 CASR NM_000388.4 NP_000379.3
36 CBS NM_000071.3 NP_000062.1
37 CC2D2A NM_001378615.1 NP_001073991.2
38 CDH23 NM_022124.6 NP_071407.4
39 CEP290 NM_025114.4 NP_079390.3
40 CERKL NM_201548.5 NP_963842.1
41 CFTR NM_000492.4 NP_000483.3
42 CFTR NM_000492.3 NP_000483.3
43 CHD7 NM_017780.4 NP_060250.2
44 CHEK2 NM_007194.4 NP_009125.1
45 CLN3 NM_001042432.2 NP_000077.1
46 CNGB3 NM_019098.5 NP_061971.3
47 CPS1 NM_001875.5 no matching protein         <<<<<
48 CRB1 NM_201253.3 NP_957705.1
49 CTNS NM_004937.3 NP_004928.2
50 CYBB NM_000397.4 NP_000388.2
51 CYP11B1 NM_000497.4 NP_000488.3
52 CYP17A1 NM_000102.4 NP_000093.1
53 CYP27A1 NM_000784.4 NP_000775.1
54 DCLRE1C NM_001033855.3 NP_001029027.1
55 DICER1 NM_177438.3 NP_001258211.1
56 DUOX2 NM_001363711.2 NP_001350640.1
57 EHMT1 NM_024757.5 NP_079033.4
58 ELP1 NM_003640.5 NP_003631.2
59 ERCC6 NM_000124.4 NP_000115.1
60 ERCC6 NM_001277058.2 NP_001263987.1
61 EVC NM_153717.3 NP_714928.1
62 EVC2 NM_147127.5 NP_667338.3
63 EXT1 NM_000127.3 NP_000118.2
64 EXT2 NM_207122.2 NP_001376557.1
65 EYS NM_001142800.2 NP_001136272.1
66 F7 NM_000131.5 NP_000122.1
67 F7 NM_019616.4 NP_062562.1
68 F7 NM_000131.4 NP_000122.1
69 F8 NM_000132.4 NP_000123.1
70 F9 NM_000133.4 NP_000124.1
71 FANCA NM_000135.4 NP_000126.2
72 FANCI NM_001113378.2 NP_001106849.1
73 FBN2 NM_001999.4 NP_001990.2
74 FKRP NM_024301.5 NP_001034974.1
75 FLCN NM_144997.7 NP_001340159.1
76 FRAS1 NM_025074.7 NP_079350.5
77 G6PD NM_000402.4 NP_000393.4
78 G6PD NM_001360016.2 NP_001035810.1
78 G6PD NM_001360016.2 NP_001035810.1
79 G6PD NM_001042351.3 NP_001035810.1
79 G6PD NM_001042351.3 NP_001035810.1
80 GAA NM_000152.5 NP_000143.2
81 GALC NM_000153.4 NP_000144.2
82 GALNS NM_000512.5 NP_000503.1
83 GALT NM_000155.4 NP_000146.2
84 GBA1 NM_000157.4 NP_000148.2
85 GBE1 NM_000158.4 NP_000149.4
86 GCDH NM_000159.4 NP_000150.1
87 GJB1 NM_000166.6 NP_000157.1
87 GJB1 NM_000166.6 NP_000157.1
88 GJB1 NM_001097642.3 NP_000157.1
88 GJB1 NM_001097642.3 NP_000157.1
89 GLB1 NM_000404.4 NP_000395.3
90 GNE NM_001128227.3 NP_001121699.1
91 GNE NM_005476.7 NP_005467.1
92 GNPTAB NM_024312.5 NP_077288.2
93 HBB NM_000518.4 NP_000509.1
94 HBB NM_000518.5 NP_000509.1
95 HEXA NM_000520.6 NP_000511.2
96 HEXB NM_000521.4 NP_000512.2
97 HGD NM_000187.4 NP_000178.2
98 HGSNAT NM_152419.3 NP_689632.2
99 HMBS NM_000190.4 NP_000181.2
100 HPRT1 NM_000194.3 NP_000185.1
101 HPRT1 NM_000194.2 NP_000185.1
102 HPS3 NM_032383.5 NP_115759.2
103 IL2RG NM_000206.3 NP_000197.1
104 ITGA2B NM_000419.5 NP_000410.2
105 IVD NM_002225.5 NP_002216.3
106 KCNH2 NM_000238.4 NP_000229.1
107 KCNQ1 NM_000218.3 NP_000209.2
108 KRIT1 NM_194454.3 NP_001337601.1
109 L1CAM NM_001278116.2 NP_000416.1
110 LDLR NM_000527.5 NP_000518.1
111 LDLR NM_000527.4 NP_000518.1
112 LIPA NM_000235.4 NP_000226.2
113 LOXHD1 NM_001384474.1 NP_001371403.1
114 LPL NM_000237.3 NP_000228.1
115 LRPPRC NM_133259.4 NP_573566.2
116 LYST NM_000081.4 NP_000072.2
117 MAN2B1 NM_000528.4 NP_000519.2
118 MCCC1 NM_020166.5 NP_064551.3
119 MCCC2 NM_022132.5 NP_071415.1
120 MED13L NM_015335.5 NP_056150.1
121 MFN2 NM_014874.4 NP_001121132.1
122 MKS1 NM_017777.4 NP_060247.2
123 MMUT NM_000255.4 NP_000246.2
124 MPZ NM_000530.8 NP_000521.2
125 MSH2 NM_000251.3 NP_000242.1
126 MTHFR NM_005957.5 NP_005948.3
127 MUTYH NM_001128425.2 NP_001121897.1
128 MUTYH NM_001048174.2 NP_001041636.2
129 MYH7 NM_000257.4 NP_000248.2
130 NAGLU NM_000263.4 NP_000254.2
131 NF1 NM_001042492.3 NP_001035957.1
132 NF2 NM_000268.4 NP_000259.1
133 NIPBL NM_133433.4 NP_597677.2
134 NPC1 NM_000271.5 NP_000262.2
135 NSD1 NM_022455.5 NP_001396230.1
136 OCA2 NM_000275.3 NP_000266.2
137 OPA1 NM_130837.3 NP_570850.2
138 PAH NM_000277.3 NP_000268.1
139 PALB2 NM_024675.4 NP_078951.2
140 PAX3 NM_181457.3 NP_852122.1
141 PAX3 NM_181458.4 NP_852123.1
142 PAX6 NM_001368894.2 NP_001245391.1
143 PAX6 NM_000280.6 NP_000271.1
144 PCDH15 NM_033056.4 NP_149045.3
145 PCDH15 NM_001384140.1 NP_001371069.1
146 PCNT NM_006031.6 NP_006022.3
147 PKHD1 NM_138694.4 NP_619639.3
148 PMM2 NM_000303.3 NP_000294.1
149 POMGNT1 NM_017739.4 NP_001424582.1
150 PRPF31 NM_015629.4 NP_056444.3
151 PYGM NM_005609.4 NP_005600.1
152 RAD50 NM_005732.4 NP_005723.2
153 RARS2 NM_020320.5 NP_064716.2
154 RECQL4 NM_004260.4 NP_004251.4
155 RHO NM_000539.3 NP_000530.1
156 RP1 NM_001375654.1 NP_001362583.1
157 RP1 NM_006269.2 NP_006260.1
158 RPGRIP1L NM_015272.5 NP_056087.2
159 SACS NM_014363.6 NP_055178.3
160 SATB2 NM_001172509.2 NP_001165980.1
160 SATB2 NM_001172509.2 NP_001165980.1
161 SATB2 NM_001172517.1 NP_001165980.1
161 SATB2 NM_001172517.1 NP_001165980.1
162 SCN4A NM_000334.4 NP_000325.4
163 SERPING1 NM_000062.3 NP_000053.2
164 SGSH NM_000199.5 NP_000190.1
165 SI NM_001041.4 NP_001032.2
166 SLC12A6 NM_001365088.1 NP_001352017.1
167 SLC25A13 NM_014251.3 NP_055066.1
168 SLC26A4 NM_000441.2 NP_000432.1
169 SMPD1 NM_000543.5 NP_000534.3
170 SPAST NM_014946.4 NP_055761.2
171 SPG11 NM_025137.4 NP_079413.3
172 SYNE1 NM_182961.4 NP_892006.3
173 SYNE1 NM_001347702.2 NP_001334631.1
174 TCIRG1 NM_006019.4 NP_001427481.1
175 TMC1 NM_138691.3 NP_619636.2
176 TMEM67 NM_153704.6 NP_714915.3
177 TP53 NM_000546.6 NP_000537.3
178 TPP1 NM_000391.4 NP_000382.3
179 TSC1 NM_000368.5 NP_000359.1
180 TTR NM_000371.4 NP_000362.1
181 TYR NM_000372.5 NP_000363.1
182 UNC13D NM_199242.3 NP_954712.1
183 USH1C NM_153676.4 NP_710142.1
184 USH1C NM_005709.4 NP_005700.2
185 USH2A NM_206933.4 NP_996816.3
186 VHL NM_000551.4 NP_000542.1
187 VPS13A NM_033305.3 NP_150648.2
188 VPS13B NM_152564.5 NP_689777.3
189 VPS13B NM_017890.5 NP_060360.3
190 VWF NM_000552.5 NP_000543.3
191 WFS1 NM_006005.3 NP_001139325.1
192 WRN NM_000553.6 NP_000544.2
193 WT1 NM_024426.6 NP_077744.4
194 XPC NM_004628.5 NP_004619.3
195 ZEB2 NM_014795.4 NP_055610.1
196 ZFYVE26 NM_015346.4 NP_056161.2

#### Correction;  47 CPS1 NM_001875.5 no matching protein         <<<<<
#### matching protein exists for NM_001875.5 = 'NP_001866.2'

In [54]:
# Insert matching protein 
translation['NM_001875.5'] = 'NP_001866.2'
translation['NM_001875.5']

'NP_001866.2'

In [55]:
translation

{'NM_173076.3': 'NP_775099.2',
 'NM_000033.4': 'NP_000024.2',
 'NM_014049.5': 'NP_054768.2',
 'NM_000016.6': 'NP_000007.1',
 'NM_000018.4': 'NP_000009.1',
 'NM_000019.4': 'NP_000010.1',
 'NM_000022.4': 'NP_000013.2',
 'NM_000642.3': 'NP_000019.2',
 'NM_000030.3': 'NP_000021.1',
 'NM_001134831.2': 'NP_001128302.1',
 'NM_000383.4': 'NP_000374.1',
 'NM_001378454.1': 'NP_001365383.1',
 'NM_001139.3': 'NP_001130.1',
 'NM_000478.6': 'NP_000469.3',
 'NM_000037.4': 'NP_000028.3',
 'NM_213599.3': 'NP_998764.1',
 'NM_001127511.3': 'NP_001120983.2',
 'NM_001127510.3': 'NP_000029.2',
 'NM_000038.6': 'NP_000029.2',
 'NM_000044.6': 'NP_000035.2',
 'NM_000487.6': 'NP_000478.3',
 'NM_000046.5': 'NP_000037.2',
 'NM_000048.4': 'NP_000039.2',
 'NM_000049.4': 'NP_000040.1',
 'NM_018136.5': 'NP_060606.3',
 'NM_000051.4': 'NP_000042.3',
 'NM_000053.4': 'NP_000044.2',
 'NM_031885.5': 'NP_001364385.1',
 'NM_000709.4': 'NP_000700.1',
 'NM_004183.4': 'NP_004174.1',
 'NM_000057.4': 'NP_000048.1',
 'NM_032043.3': 'NP_114432.2',
 'NM_001370658.1': 'NP_001268652.2',
 'NM_000061.3': 'NP_000052.1',
 'NM_000388.4': 'NP_000379.3',
 'NM_000071.3': 'NP_000062.1',
 'NM_001378615.1': 'NP_001073991.2',
 'NM_022124.6': 'NP_071407.4',
 'NM_025114.4': 'NP_079390.3',
 'NM_201548.5': 'NP_963842.1',
 'NM_000492.4': 'NP_000483.3',
 'NM_000492.3': 'NP_000483.3',
 'NM_017780.4': 'NP_060250.2',
 'NM_007194.4': 'NP_009125.1',
 'NM_001042432.2': 'NP_000077.1',
 'NM_019098.5': 'NP_061971.3',
 'NM_201253.3': 'NP_957705.1',
 'NM_004937.3': 'NP_004928.2',
 'NM_000397.4': 'NP_000388.2',
 'NM_000497.4': 'NP_000488.3',
 'NM_000102.4': 'NP_000093.1',
 'NM_000784.4': 'NP_000775.1',
 'NM_001033855.3': 'NP_001029027.1',
 'NM_177438.3': 'NP_001258211.1',
 'NM_001363711.2': 'NP_001350640.1',
 'NM_024757.5': 'NP_079033.4',
 'NM_003640.5': 'NP_003631.2',
 'NM_000124.4': 'NP_000115.1',
 'NM_001277058.2': 'NP_001263987.1',
 'NM_153717.3': 'NP_714928.1',
 'NM_147127.5': 'NP_667338.3',
 'NM_000127.3': 'NP_000118.2',
 'NM_207122.2': 'NP_001376557.1',
 'NM_001142800.2': 'NP_001136272.1',
 'NM_000131.5': 'NP_000122.1',
 'NM_019616.4': 'NP_062562.1',
 'NM_000131.4': 'NP_000122.1',
 'NM_000132.4': 'NP_000123.1',
 'NM_000133.4': 'NP_000124.1',
 'NM_000135.4': 'NP_000126.2',
 'NM_001113378.2': 'NP_001106849.1',
 'NM_001999.4': 'NP_001990.2',
 'NM_024301.5': 'NP_001034974.1',
 'NM_144997.7': 'NP_001340159.1',
 'NM_025074.7': 'NP_079350.5',
 'NM_000402.4': 'NP_000393.4',
 'NM_001360016.2': 'NP_001035810.1',
 'NM_001042351.3': 'NP_001035810.1',
 'NM_000152.5': 'NP_000143.2',
 'NM_000153.4': 'NP_000144.2',
 'NM_000512.5': 'NP_000503.1',
 'NM_000155.4': 'NP_000146.2',
 'NM_000157.4': 'NP_000148.2',
 'NM_000158.4': 'NP_000149.4',
 'NM_000159.4': 'NP_000150.1',
 'NM_000166.6': 'NP_000157.1',
 'NM_001097642.3': 'NP_000157.1',
 'NM_000404.4': 'NP_000395.3',
 'NM_001128227.3': 'NP_001121699.1',
 'NM_005476.7': 'NP_005467.1',
 'NM_024312.5': 'NP_077288.2',
 'NM_000518.4': 'NP_000509.1',
 'NM_000518.5': 'NP_000509.1',
 'NM_000520.6': 'NP_000511.2',
 'NM_000521.4': 'NP_000512.2',
 'NM_000187.4': 'NP_000178.2',
 'NM_152419.3': 'NP_689632.2',
 'NM_000190.4': 'NP_000181.2',
 'NM_000194.3': 'NP_000185.1',
 'NM_000194.2': 'NP_000185.1',
 'NM_032383.5': 'NP_115759.2',
 'NM_000206.3': 'NP_000197.1',
 'NM_000419.5': 'NP_000410.2',
 'NM_002225.5': 'NP_002216.3',
 'NM_000238.4': 'NP_000229.1',
 'NM_000218.3': 'NP_000209.2',
 'NM_194454.3': 'NP_001337601.1',
 'NM_001278116.2': 'NP_000416.1',
 'NM_000527.5': 'NP_000518.1',
 'NM_000527.4': 'NP_000518.1',
 'NM_000235.4': 'NP_000226.2',
 'NM_001384474.1': 'NP_001371403.1',
 'NM_000237.3': 'NP_000228.1',
 'NM_133259.4': 'NP_573566.2',
 'NM_000081.4': 'NP_000072.2',
 'NM_000528.4': 'NP_000519.2',
 'NM_020166.5': 'NP_064551.3',
 'NM_022132.5': 'NP_071415.1',
 'NM_015335.5': 'NP_056150.1',
 'NM_014874.4': 'NP_001121132.1',
 'NM_017777.4': 'NP_060247.2',
 'NM_000255.4': 'NP_000246.2',
 'NM_000530.8': 'NP_000521.2',
 'NM_000251.3': 'NP_000242.1',
 'NM_005957.5': 'NP_005948.3',
 'NM_001128425.2': 'NP_001121897.1',
 'NM_001048174.2': 'NP_001041636.2',
 'NM_000257.4': 'NP_000248.2',
 'NM_000263.4': 'NP_000254.2',
 'NM_001042492.3': 'NP_001035957.1',
 'NM_000268.4': 'NP_000259.1',
 'NM_133433.4': 'NP_597677.2',
 'NM_000271.5': 'NP_000262.2',
 'NM_022455.5': 'NP_001396230.1',
 'NM_000275.3': 'NP_000266.2',
 'NM_130837.3': 'NP_570850.2',
 'NM_000277.3': 'NP_000268.1',
 'NM_024675.4': 'NP_078951.2',
 'NM_181457.3': 'NP_852122.1',
 'NM_181458.4': 'NP_852123.1',
 'NM_001368894.2': 'NP_001245391.1',
 'NM_000280.6': 'NP_000271.1',
 'NM_033056.4': 'NP_149045.3',
 'NM_001384140.1': 'NP_001371069.1',
 'NM_006031.6': 'NP_006022.3',
 'NM_138694.4': 'NP_619639.3',
 'NM_000303.3': 'NP_000294.1',
 'NM_017739.4': 'NP_001424582.1',
 'NM_015629.4': 'NP_056444.3',
 'NM_005609.4': 'NP_005600.1',
 'NM_005732.4': 'NP_005723.2',
 'NM_020320.5': 'NP_064716.2',
 'NM_004260.4': 'NP_004251.4',
 'NM_000539.3': 'NP_000530.1',
 'NM_001375654.1': 'NP_001362583.1',
 'NM_006269.2': 'NP_006260.1',
 'NM_015272.5': 'NP_056087.2',
 'NM_014363.6': 'NP_055178.3',
 'NM_001172509.2': 'NP_001165980.1',
 'NM_001172517.1': 'NP_001165980.1',
 'NM_000334.4': 'NP_000325.4',
 'NM_000062.3': 'NP_000053.2',
 'NM_000199.5': 'NP_000190.1',
 'NM_001041.4': 'NP_001032.2',
 'NM_001365088.1': 'NP_001352017.1',
 'NM_014251.3': 'NP_055066.1',
 'NM_000441.2': 'NP_000432.1',
 'NM_000543.5': 'NP_000534.3',
 'NM_014946.4': 'NP_055761.2',
 'NM_025137.4': 'NP_079413.3',
 'NM_182961.4': 'NP_892006.3',
 'NM_001347702.2': 'NP_001334631.1',
 'NM_006019.4': 'NP_001427481.1',
 'NM_138691.3': 'NP_619636.2',
 'NM_153704.6': 'NP_714915.3',
 'NM_000546.6': 'NP_000537.3',
 'NM_000391.4': 'NP_000382.3',
 'NM_000368.5': 'NP_000359.1',
 'NM_000371.4': 'NP_000362.1',
 'NM_000372.5': 'NP_000363.1',
 'NM_199242.3': 'NP_954712.1',
 'NM_153676.4': 'NP_710142.1',
 'NM_005709.4': 'NP_005700.2',
 'NM_206933.4': 'NP_996816.3',
 'NM_000551.4': 'NP_000542.1',
 'NM_033305.3': 'NP_150648.2',
 'NM_152564.5': 'NP_689777.3',
 'NM_017890.5': 'NP_060360.3',
 'NM_000552.5': 'NP_000543.3',
 'NM_006005.3': 'NP_001139325.1',
 'NM_000553.6': 'NP_000544.2',
 'NM_024426.6': 'NP_077744.4',
 'NM_004628.5': 'NP_004619.3',
 'NM_014795.4': 'NP_055610.1',
 'NM_015346.4': 'NP_056161.2',
 'NM_001875.5': 'NP_001866.2'}

## clean up variants not matching any protein
* HBB 
* G6PD
#### Clean up is required only once

In [ ]:
vardata = pd.read_csv('pathogenic_lociii/HBB.csv', sep= "\t")
i = vardata['Name'].tolist().index('Hb Little Rock')
#vardata[(vardata.index<i+3) & (vardata.index>i-3)]
vardata[(vardata.index == i)]
#vardata

,Type,Name,GeneID,GeneSymbol,ClinicalSignificance,Assembly,"VariationID,Name"
16,single nucleotide variant,NM_000518.5(HBB):c.432C>R (p.His144Gln),3043.0,HBB,Pathogenic,GRCh38,"15250,"

In [131]:
vardata.loc[i, 'Name'] = 'NM_000518.5(HBB):c.432C>R (p.His144Gln)'
vardata.to_csv('pathogenic_lociii/HBB.csv', index=False, sep= "\t")
#vardata[(vardata.index<i+3) & (vardata.index>i-3)]
vardata[(vardata.index == i)]
#vardata

,Type,Name,GeneID,GeneSymbol,ClinicalSignificance,Assembly,"VariationID,Name"
16,single nucleotide variant,NM_000518.5(HBB):c.432C>R (p.His144Gln),3043.0,HBB,Pathogenic,GRCh38,"15250,"

### G6PD

#### 'G6PD ZURICH' = 'NM_001360016.2:c.1288-2A>G' [G6PD ZURICH](https://www.ncbi.nlm.nih.gov/clinvar/variation/10420/?term=%22G6PD%22%5BVARNAME%5D+AND+%22ZURICH%22%5BVARNAME%5D) 
#### Hence we correct the 'Name' column to 'NM_001360016.2(G6PD):c.1288-2A>G)'

In [ ]:
vardata = pd.read_csv('pathogenic_lociii/G6PD.csv', sep= "\t")
i = vardata['Name'].tolist().index('G6PD ZURICH') 
#vardata[(vardata.index<i+3) & (vardata.index>i-3)]
vardata[vardata.index == i]

In [ ]:
vardata.loc[i, 'Name'] = 'NM_001360016.2(G6PD):c.1288-2A>G)'
vardata.to_csv('pathogenic_lociii/G6PD.csv', index=False, sep= "\t")
#vardata[(vardata.index<i+3) & (vardata.index>i-3)]
vardata[vardata.index == i]

### STEP 4 (STEP 5 is the correct code) to run
##### Extract individual variants

Process each ClinVar dataset and extract variants for each transcript.

**Output:** `variants` dictionary with transcript IDs as keys and lists of changes as values.

In [56]:
run kondrashov

In [ ]:
print('gene transcript protein changes errors')
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        #print(transcript)
        sites, wilds, muts, errs = get_all_changes(gene, transcript, True)
        #print(gene, transcript, translation[transcript], len(sites), len(errs))

#### I keep gettng this KeyError: '00='

In [57]:
# I'll do a step-by-step troubleshooting, first view the names 
for gene in lociii:
    #transcripts = vartranscripts_filtered[gene]
    #for transcript in transcripts:
    vardata = pd.read_csv("pathogenic_lociii/" + gene + ".csv", sep= "\t")
    n = len(vardata)
    for i in range(n):
        name = vardata["Name"][i]
        print(name)

NM_173076.3(ABCA12):c.4142G>A (p.Gly1381Glu)
NM_173076.3(ABCA12):c.4139A>G (p.Asn1380Ser)
NM_173076.3(ABCA12):c.4951G>A (p.Gly1651Ser)
NM_173076.3(ABCA12):c.4541G>A (p.Arg1514His)
NM_173076.3(ABCA12):c.6610C>T (p.Arg2204Ter)
NM_173076.3(ABCA12):c.3535G>A (p.Gly1179Arg)
NM_173076.3(ABCA12):c.3889C>T (p.Arg1297Ter)
NM_173076.3(ABCA12):c.3256A>T (p.Lys1086Ter)
NM_173076.3(ABCA12):c.2531A>G (p.Asp844Gly)
NM_173076.3(ABCA12):c.2140C>T (p.Arg714Ter)
NM_173076.3(ABCA12):c.1660C>T (p.Gln554Ter)
NM_173076.3(ABCA12):c.1300C>T (p.Arg434Ter)
NM_173076.3(ABCA12):c.859C>T (p.Arg287Ter)
NM_173076.3(ABCA12):c.179G>C (p.Arg60Pro)
NM_173076.3(ABCA12):c.178C>T (p.Arg60Ter)
NM_173076.3(ABCA12):c.5787T>G (p.Tyr1929Ter)
NM_173076.3(ABCA12):c.130C>T (p.Arg44Trp)
NM_173076.3(ABCA12):c.2121+2T>G
NM_173076.3(ABCA12):c.7444C>T (p.Arg2482Ter)
NM_173076.3(ABCA12):c.7172G>A (p.Ser2391Asn)
NM_173076.3(ABCA12):c.2593-1G>A
NM_173076.3(ABCA12):c.5939+4A>G
NM_173076.3(ABCA12):c.5414C>G (p.Ser1805Ter)
NM_173076.3(ABCA12):c.6234-1G>C
NM_173076.3(ABCA12):c.5381+1G>C
NM_173076.3(ABCA12):c.4108G>T (p.Glu1370Ter)
NM_173076.3(ABCA12):c.2296C>T (p.Gln766Ter)
NM_173076.3(ABCA12):c.5128+2T>C
NM_173076.3(ABCA12):c.6353C>G (p.Ser2118Ter)
NM_173076.3(ABCA12):c.5231G>A (p.Trp1744Ter)
NM_173076.3(ABCA12):c.1657+1G>T
NM_173076.3(ABCA12):c.596G>A (p.Trp199Ter)
NM_173076.3(ABCA12):c.693+1G>A
NM_173076.3(ABCA12):c.7277G>A (p.Arg2426Gln)
NM_173076.3(ABCA12):c.7247C>T (p.Pro2416Leu)
NM_173076.3(ABCA12):c.3446T>C (p.Leu1149Pro)
NM_173076.3(ABCA12):c.5878C>T (p.Arg1960Ter)
NM_173076.3(ABCA12):c.694-1G>A
NM_173076.3(ABCA12):c.6458G>T (p.Gly2153Val)
NM_173076.3(ABCA12):c.5128+1G>A
NM_173076.3(ABCA12):c.7105-1G>A
NM_173076.3(ABCA12):c.3882G>A (p.Trp1294Ter)
NM_173076.3(ABCA12):c.1210C>T (p.Arg404Ter)
NM_173076.3(ABCA12):c.2956C>T (p.Arg986Trp)
NM_173076.3(ABCA12):c.7405T>C (p.Cys2469Arg)
NM_173076.3(ABCA12):c.6293C>A (p.Ala2098Asp)
NM_173076.3(ABCA12):c.4676G>T (p.Gly1559Val)
NM_173076.3(ABCA12):c.4540C>T (p.Arg1514Cys)
NM_173076.3(ABCA12):c.1782G>A (p.Glu594=)
NM_173076.3(ABCA12):c.3656C>T (p.Ala1219Val)
NM_173076.3(ABCA12):c.667C>T (p.Gln223Ter)
NM_173076.3(ABCA12):c.7344-1G>C
NM_173076.3(ABCA12):c.7172G>T (p.Ser2391Ile)
NM_173076.3(ABCA12):c.5848C>T (p.Arg1950Ter)
NM_173076.3(ABCA12):c.3666C>A (p.Tyr1222Ter)
NM_173076.3(ABCA12):c.4579G>T (p.Ala1527Ser)
NM_173076.3(ABCA12):c.5641C>T (p.Arg1881Ter)
NM_173076.3(ABCA12):c.6463G>T (p.Gly2155Cys)
NM_173076.3(ABCA12):c.4151A>G (p.Lys1384Arg)
NM_173076.3(ABCA12):c.7240-1G>T
NM_173076.3(ABCA12):c.6037C>T (p.Gln2013Ter)
NM_173076.3(ABCA12):c.6852+2T>G
NM_173076.3(ABCA12):c.5607C>G (p.Tyr1869Ter)
NM_173076.3(ABCA12):c.2394G>A (p.Trp798Ter)
NM_173076.3(ABCA12):c.4543C>T (p.Arg1515Ter)
NM_173076.3(ABCA12):c.3673C>T (p.Arg1225Ter)
NM_173076.3(ABCA12):c.3470C>T (p.Ser1157Leu)
NM_173076.3(ABCA12):c.3295-1G>A
NM_173076.3(ABCA12):c.1216A>T (p.Lys406Ter)
NM_173076.3(ABCA12):c.1060C>T (p.Gln354Ter)
NM_173076.3(ABCA12):c.682C>T (p.Gln228Ter)
NM_173076.3(ABCA12):c.6963-2A>G
NM_173076.3(ABCA12):c.5451T>A (p.Cys1817Ter)
NM_173076.3(ABCA12):c.6962+1G>T
NM_173076.3(ABCA12):c.4163+1G>T
NM_173076.3(ABCA12):c.5939+1G>A
NM_173076.3(ABCA12):c.2332+2T>C
NM_173076.3(ABCA12):c.5779-2A>G
NM_173076.3(ABCA12):c.4579+1G>T
NM_173076.3(ABCA12):c.3124C>T (p.Gln1042Ter)
NM_173076.3(ABCA12):c.317+1G>A
NM_173076.3(ABCA12):c.985+1G>A
NM_173076.3(ABCA12):c.1062-2A>G
NM_173076.3(ABCA12):c.2592+1G>A
NM_173076.3(ABCA12):c.2035C>T (p.Gln679Ter)
NM_173076.3(ABCA12):c.1658-2A>G
NM_173076.3(ABCA12):c.5690+1G>A
NM_173076.3(ABCA12):c.409+2T>C
NM_173076.3(ABCA12):c.6962+2T>C
NM_173076.3(ABCA12):c.2728C>T (p.Gln910Ter)
NM_173076.3(ABCA12):c.2194C>T (p.Gln732Ter)
NM_173076.3(ABCA12):c.196G>A (p.Gly66Arg)
NM_173076.3(ABCA12):c.7542+1G>A
NM_173076.3(ABCA12):c.5381+1G>T
NM_173076.3(ABCA12):c.5381+1G>A
NM_173076.3(ABCA12):c.179G>A (p.Arg60Gln)
NM_173076.3(ABCA12):c.541C>T (p.Arg181Ter)
NM_173076.3(ABCA12):c.6394-2A>G
NM_173076.3(ABCA12):c.5884G>A (p.Gly1962Ser)
NM_173076.3(ABCA12):c.6447A>T (p.Gln2149His)
NM_173076.3(ABCA12):c.3535G>T (p.Gly1179Ter)
NM_173076.3(ABCA12):c.4798C>T (p.Gln1600Ter)
NM_173076.3(ABCA12):c.2155C>T (p.Gln719Ter)
NM_173076.3(ABCA12):c.1782+1G>T
NM_173076.3(ABCA12):c.5382-2A>G
NM_173076.3(ABCA12):c.5691-10C>G
NM_173076.3(ABCA12):c.3548A>G (p.Tyr1183Cys)
NM_173076.3(ABCA12):c.790C>T (p.Gln264Ter)
NM_173076.3(ABCA12):c.2785C>T (p.Arg929Cys)
NM_173076.3(ABCA12):c.6963-1G>A
NM_173076.3(ABCA12):c.4977G>A (p.Glu1659=)
NM_173076.3(ABCA12):c.1657+2T>G
NM_173076.3(ABCA12):c.693+1G>T
NM_173076.3(ABCA12):c.517C>T (p.Gln173Ter)
NM_173076.3(ABCA12):c.2T>A (p.Met1Lys)
NM_173076.3(ABCA12):c.6052C>T (p.Gln2018Ter)
NM_173076.3(ABCA12):c.5562+1G>A
NM_173076.3(ABCA12):c.573C>A (p.Tyr191Ter)
NM_173076.3(ABCA12):c.4462T>C (p.Ser1488Pro)
NM_173076.3(ABCA12):c.873-2A>G
NM_173076.3(ABCA12):c.1444G>T (p.Glu482Ter)
NM_173076.3(ABCA12):c.775C>T (p.Gln259Ter)
NM_173076.3(ABCA12):c.1931T>G (p.Leu644Ter)
NM_173076.3(ABCA12):c.163T>G (p.Cys55Gly)
NM_173076.3(ABCA12):c.1657+1G>A
NM_173076.3(ABCA12):c.6962+1G>A
NM_173076.3(ABCA12):c.1245T>A (p.Tyr415Ter)
NM_173076.3(ABCA12):c.1288-1G>A
NM_173076.3(ABCA12):c.1783-1G>A
NM_173076.3(ABCA12):c.1783-1G>T
NM_173076.3(ABCA12):c.2473-2A>T
NM_173076.3(ABCA12):c.5128+3A>G
NM_173076.3(ABCA12):c.1131C>G (p.Tyr377Ter)
NM_173076.3(ABCA12):c.2864-2A>T
NM_000033.4(ABCD1):c.871G>A (p.Glu291Lys)
NM_000033.4(ABCD1):c.1451C>G (p.Pro484Arg)
NM_000033.4(ABCD1):c.1635-2A>G
NM_000033.4(ABCD1):c.1165C>G (p.Arg389Gly)
NM_000033.4(ABCD1):c.443A>G (p.Asn148Ser)
NM_000033.4(ABCD1):c.520T>G (p.Tyr174Asp)
NM_000033.4(ABCD1):c.796G>A (p.Gly266Arg)
NM_000033.4(ABCD1):c.1202G>A (p.Arg401Gln)
NM_000033.4(ABCD1):c.1252C>T (p.Arg418Trp)
NM_000033.4(ABCD1):c.1390C>T (p.Arg464Ter)
NM_000033.4(ABCD1):c.1429G>T (p.Glu477Ter)
NM_000033.4(ABCD1):c.1544C>T (p.Ser515Phe)
NM_000033.4(ABCD1):c.1552C>T (p.Arg518Trp)
NM_000033.4(ABCD1):c.1634+1G>A
NM_000033.4(ABCD1):c.1817C>T (p.Ser606Leu)
NM_000033.4(ABCD1):c.1850G>A (p.Arg617His)
NM_000033.4(ABCD1):c.1849C>T (p.Arg617Cys)
NM_000033.4(ABCD1):c.1865+1G>A
NM_000033.4(ABCD1):c.900G>A (p.Glu300=)
NM_000033.4(ABCD1):c.421G>A (p.Ala141Thr)
NM_000033.4(ABCD1):c.838C>T (p.Arg280Cys)
NM_000033.4(ABCD1):c.1396C>T (p.Gln466Ter)
NM_000033.4(ABCD1):c.1553G>A (p.Arg518Gln)
NM_000033.4(ABCD1):c.1586G>A (p.Gly529Asp)
NM_000033.4(ABCD1):c.1660C>A (p.Arg554Ser)
NM_000033.4(ABCD1):c.1679C>T (p.Pro560Leu)
NM_000033.4(ABCD1):c.1771C>T (p.Arg591Trp)
NM_000033.4(ABCD1):c.1802G>A (p.Trp601Ter)
NM_000033.4(ABCD1):c.1866-10G>A
NM_000033.4(ABCD1):c.346G>A (p.Gly116Arg)
NM_000033.4(ABCD1):c.406C>T (p.Gln136Ter)
NM_000033.4(ABCD1):c.1661G>A (p.Arg554His)
NM_000033.4(ABCD1):c.1825G>A (p.Glu609Lys)
NM_000033.4(ABCD1):c.1201C>G (p.Arg401Gly)
NM_000033.4(ABCD1):c.887A>G (p.Tyr296Cys)
NM_000033.4(ABCD1):c.886T>C (p.Tyr296His)
NM_000033.4(ABCD1):c.1288C>T (p.Gln430Ter)
NM_000033.4(ABCD1):c.1781-1G>A
NM_000033.4(ABCD1):c.651G>C (p.Lys217Asn)
NM_000033.4(ABCD1):c.1166G>A (p.Arg389His)
NM_000033.4(ABCD1):c.529C>T (p.Gln177Ter)
NM_000033.4(ABCD1):c.488G>A (p.Arg163His)
NM_000033.4(ABCD1):c.1895C>T (p.Thr632Ile)
NM_000033.4(ABCD1):c.565C>T (p.Arg189Trp)
NM_000033.4(ABCD1):c.761C>T (p.Thr254Met)
NM_000033.4(ABCD1):c.1082-1G>A
NM_000033.4(ABCD1):c.2037G>A (p.Trp679Ter)
NM_000033.4(ABCD1):c.311G>A (p.Arg104His)
NM_000033.4(ABCD1):c.442A>T (p.Asn148Tyr)
NM_000033.4(ABCD1):c.1772G>A (p.Arg591Gln)
NM_000033.4(ABCD1):c.1979G>T (p.Arg660Leu)
NM_000033.4(ABCD1):c.1780+2T>G
NM_000033.4(ABCD1):c.293C>T (p.Ser98Leu)
NM_000033.4(ABCD1):c.521A>G (p.Tyr174Cys)
NM_000033.4(ABCD1):c.1270C>T (p.Gln424Ter)
NM_000033.4(ABCD1):c.1998C>A (p.Tyr666Ter)
NM_000033.4(ABCD1):c.1201C>T (p.Arg401Trp)
NM_000033.4(ABCD1):c.887A>C (p.Tyr296Ser)
NM_000033.4(ABCD1):c.2035T>A (p.Trp679Arg)
NM_000033.4(ABCD1):c.1866-1G>C
NM_000033.4(ABCD1):c.843C>A (p.Tyr281Ter)
NM_000033.4(ABCD1):c.1567C>T (p.Leu523Phe)
NM_000033.4(ABCD1):c.1628C>T (p.Pro543Leu)
NM_000033.4(ABCD1):c.1552C>G (p.Arg518Gly)
NM_000033.4(ABCD1):c.2003C>T (p.Thr668Ile)
NM_000033.4(ABCD1):c.876G>C (p.Glu292Asp)
NM_000033.4(ABCD1):c.1826A>G (p.Glu609Gly)
NM_000033.4(ABCD1):c.433A>G (p.Thr145Ala)
NM_000033.4(ABCD1):c.454C>T (p.Arg152Cys)
NM_000033.4(ABCD1):c.1126G>T (p.Glu376Ter)
NM_000033.4(ABCD1):c.1876G>A (p.Ala626Thr)
NM_000033.4(ABCD1):c.1866-1G>A
NM_000033.4(ABCD1):c.1096A>T (p.Lys366Ter)
NM_000033.4(ABCD1):c.1534G>A (p.Gly512Ser)
NM_000033.4(ABCD1):c.1978C>T (p.Arg660Trp)
NM_000033.4(ABCD1):c.320T>C (p.Leu107Pro)
NM_000033.4(ABCD1):c.662A>C (p.Asp221Ala)
NM_000033.4(ABCD1):c.80A>C (p.Tyr27Ser)
NM_000033.4(ABCD1):c.487C>T (p.Arg163Cys)
NM_000033.4(ABCD1):c.593C>T (p.Thr198Met)
NM_000033.4(ABCD1):c.1165C>T (p.Arg389Cys)
NM_000033.4(ABCD1):c.1186G>A (p.Ala396Thr)
NM_000033.4(ABCD1):c.1597A>C (p.Lys533Gln)
NM_000033.4(ABCD1):c.1973C>T (p.Thr658Ile)
NM_000033.4(ABCD1):c.900G>C (p.Glu300Asp)
NM_000033.4(ABCD1):c.346G>C (p.Gly116Arg)
NM_000033.4(ABCD1):c.829G>A (p.Gly277Arg)
NM_000033.4(ABCD1):c.892G>A (p.Gly298Ser)
NM_000033.4(ABCD1):c.919C>T (p.Gln307Ter)
NM_000033.4(ABCD1):c.1454C>G (p.Ser485Ter)
NM_000033.4(ABCD1):c.1784G>A (p.Trp595Ter)
NM_000033.4(ABCD1):c.1919A>G (p.Glu640Gly)
NM_000033.4(ABCD1):c.1489-1G>A
NM_000033.4(ABCD1):c.1635-1G>A
NM_000033.4(ABCD1):c.521A>C (p.Tyr174Ser)
NM_000033.4(ABCD1):c.422C>T (p.Ala141Val)
NM_000033.4(ABCD1):c.1015T>C (p.Trp339Arg)
NM_000033.4(ABCD1):c.1219A>T (p.Lys407Ter)
NM_000033.4(ABCD1):c.1967C>T (p.Ser656Phe)
NM_000033.4(ABCD1):c.341T>C (p.Leu114Pro)
NM_000033.4(ABCD1):c.878T>C (p.Ile293Thr)
NM_000033.4(ABCD1):c.1144A>C (p.Thr382Pro)
NM_000033.4(ABCD1):c.1501A>T (p.Met501Leu)
NM_000033.4(ABCD1):c.1998C>G (p.Tyr666Ter)
NM_000033.4(ABCD1):c.1A>G (p.Met1Val)
NM_000033.4(ABCD1):c.442A>G (p.Asn148Asp)
NM_000033.4(ABCD1):c.797G>A (p.Gly266Glu)
NM_000033.4(ABCD1):c.847C>G (p.His283Asp)
NM_000033.4(ABCD1):c.994C>T (p.Gln332Ter)
NM_000033.4(ABCD1):c.1028G>A (p.Gly343Asp)
NM_000033.4(ABCD1):c.1631A>G (p.Gln544Arg)
NM_000033.4(ABCD1):c.1678C>A (p.Pro560Thr)
NM_000033.4(ABCD1):c.1961T>C (p.Leu654Pro)
NM_000033.4(ABCD1):c.1081+1G>A
NM_000033.4(ABCD1):c.1628C>G (p.Pro543Arg)
NM_000033.4(ABCD1):c.1991G>A (p.Trp664Ter)
NM_000033.4(ABCD1):c.1699C>T (p.Gln567Ter)
NM_000033.4(ABCD1):c.411G>A (p.Trp137Ter)
NM_000033.4(ABCD1):c.659T>C (p.Leu220Pro)
NM_000033.4(ABCD1):c.1027G>C (p.Gly343Arg)
NM_000033.4(ABCD1):c.1414C>T (p.Gln472Ter)
NM_000033.4(ABCD1):c.1508T>C (p.Leu503Pro)
NM_000033.4(ABCD1):c.1675T>C (p.Tyr559His)
NM_000033.4(ABCD1):c.578C>G (p.Pro193Arg)
NM_000033.4(ABCD1):c.580G>A (p.Asp194Asn)
NM_000033.4(ABCD1):c.787C>T (p.Pro263Ser)
NM_000033.4(ABCD1):c.1892G>A (p.Cys631Tyr)
NM_000033.4(ABCD1):c.2006A>G (p.His669Arg)
NM_000033.4(ABCD1):c.1488+1G>A
NM_000033.4(ABCD1):c.661G>A (p.Asp221Asn)
NM_000033.4(ABCD1):c.1822G>A (p.Gly608Ser)
NM_000033.4(ABCD1):c.1899C>G (p.Ser633Arg)
NM_000033.4(ABCD1):c.290A>C (p.His97Pro)
NM_000033.4(ABCD1):c.1484T>A (p.Ile495Asn)
NM_000033.4(ABCD1):c.1768C>T (p.Gln590Ter)
NM_000033.4(ABCD1):c.1907G>T (p.Ser636Ile)
NM_000033.4(ABCD1):c.30G>A (p.Trp10Ter)
NM_000033.4(ABCD1):c.323C>T (p.Ser108Leu)
NM_000033.4(ABCD1):c.454C>A (p.Arg152Ser)
NM_000033.4(ABCD1):c.1849C>G (p.Arg617Gly)
NM_000033.4(ABCD1):c.830G>T (p.Gly277Val)
NM_000033.4(ABCD1):c.598G>A (p.Asp200Asn)
NM_000033.4(ABCD1):c.1247C>G (p.Thr416Arg)
NM_000033.4(ABCD1):c.873G>C (p.Glu291Asp)
NM_000033.4(ABCD1):c.1442T>C (p.Ile481Thr)
NM_000033.4(ABCD1):c.785C>G (p.Ser262Trp)
NM_000033.4(ABCD1):c.965T>C (p.Leu322Pro)
NM_000033.4(ABCD1):c.1138G>T (p.Glu380Ter)
NM_000033.4(ABCD1):c.1780G>C (p.Gly594Arg)
NM_000033.4(ABCD1):c.1817C>A (p.Ser606Ter)
NM_000033.4(ABCD1):c.221G>T (p.Arg74Leu)
NM_000033.4(ABCD1):c.900+2T>C
NM_000033.4(ABCD1):c.518T>C (p.Leu173Pro)
NM_000033.4(ABCD1):c.829G>T (p.Gly277Trp)
NM_000033.4(ABCD1):c.482C>A (p.Ser161Ter)
NM_000033.4(ABCD1):c.29G>A (p.Trp10Ter)
NM_000033.4(ABCD1):c.901-1G>A
NM_000033.4(ABCD1):c.395G>A (p.Trp132Ter)
NM_000033.4(ABCD1):c.268G>T (p.Glu90Ter)
NM_000033.4(ABCD1):c.488G>T (p.Arg163Leu)
NM_000033.4(ABCD1):c.901-2A>C
NM_000033.4(ABCD1):c.901-2A>G
NM_000033.4(ABCD1):c.847C>T (p.His283Tyr)
NM_000033.4(ABCD1):c.488G>C (p.Arg163Pro)
NM_000033.4(ABCD1):c.487C>G (p.Arg163Gly)
NM_000033.4(ABCD1):c.931C>T (p.Gln311Ter)
NM_000033.4(ABCD1):c.455G>C (p.Arg152Pro)
NM_000033.4(ABCD1):c.1519G>A (p.Gly507Ser)
NM_000033.4(ABCD1):c.1679C>G (p.Pro560Arg)
NM_000033.4(ABCD1):c.1891T>C (p.Cys631Arg)
NM_000033.4(ABCD1):c.310C>T (p.Arg104Cys)
NM_000033.4(ABCD1):c.1823G>C (p.Gly608Ala)
NM_000033.4(ABCD1):c.851C>A (p.Ser284Ter)
NM_000033.4(ABCD1):c.1224G>A (p.Glu408=)
NM_000033.4(ABCD1):c.1720C>T (p.Gln574Ter)
NM_000033.4(ABCD1):c.1999C>G (p.His667Asp)
NM_000033.4(ABCD1):c.154G>T (p.Glu52Ter)
NM_000033.4(ABCD1):c.1677C>A (p.Tyr559Ter)
NM_000033.4(ABCD1):c.848A>G (p.His283Arg)
NM_000033.4(ABCD1):c.522C>G (p.Tyr174Ter)
NM_000033.4(ABCD1):c.290A>G (p.His97Arg)
NM_000033.4(ABCD1):c.632T>G (p.Leu211Arg)
NM_000033.4(ABCD1):c.2051T>C (p.Leu684Pro)
NM_000033.4(ABCD1):c.1529G>A (p.Gly510Asp)
NM_000033.4(ABCD1):c.760A>G (p.Thr254Ala)
NM_000033.4(ABCD1):c.1535G>T (p.Gly512Val)
NM_000033.4(ABCD1):c.454C>G (p.Arg152Gly)
NM_000033.4(ABCD1):c.853C>G (p.Arg285Gly)
NM_000033.4(ABCD1):c.901-5C>A
NM_000033.4(ABCD1):c.1523C>T (p.Pro508Leu)
NM_000033.4(ABCD1):c.1886A>T (p.Asp629Val)
NM_000033.4(ABCD1):c.1785G>A (p.Trp595Ter)
NM_000033.4(ABCD1):c.293C>G (p.Ser98Trp)
NM_000033.4(ABCD1):c.1781-2A>G
NM_000033.4(ABCD1):c.1802G>C (p.Trp601Ser)
NM_000033.4(ABCD1):c.1117A>T (p.Lys373Ter)
NM_000033.4(ABCD1):c.1075G>T (p.Glu359Ter)
NM_000033.4(ABCD1):c.1537A>T (p.Lys513Ter)
NM_000033.4(ABCD1):c.583C>T (p.Gln195Ter)
NM_000033.4(ABCD1):c.953A>T (p.Asn318Ile)
NM_000033.4(ABCD1):c.1547T>C (p.Leu516Pro)
NM_000033.4(ABCD1):c.2014C>T (p.Gln672Ter)
NM_000033.4(ABCD1):c.1073C>G (p.Ser358Ter)
NM_000033.4(ABCD1):c.1028G>T (p.Gly343Val)
NM_000033.4(ABCD1):c.1574C>T (p.Pro525Leu)
NM_000033.4(ABCD1):c.1528G>A (p.Gly510Ser)
NM_000033.4(ABCD1):c.338G>C (p.Arg113Pro)
NM_000033.4(ABCD1):c.469C>T (p.Gln157Ter)
NM_000033.4(ABCD1):c.904G>A (p.Glu302Lys)
NM_000033.4(ABCD1):c.1016G>A (p.Trp339Ter)
NM_000033.4(ABCD1):c.1259A>C (p.His420Pro)
NM_000033.4(ABCD1):c.1393+1G>A
NM_000033.4(ABCD1):c.1520G>A (p.Gly507Asp)
NM_000033.4(ABCD1):c.1570T>C (p.Trp524Arg)
NM_000033.4(ABCD1):c.1991+1G>A
NM_000033.4(ABCD1):c.1450C>T (p.Pro484Ser)
NM_000033.4(ABCD1):c.1489-2A>G
NM_000033.4(ABCD1):c.797G>C (p.Gly266Ala)
NM_000033.4(ABCD1):c.1006A>G (p.Lys336Glu)
NM_000033.4(ABCD1):c.1253G>C (p.Arg418Pro)
NM_000033.4(ABCD1):c.1224+2T>A
NM_000033.4(ABCD1):c.1713C>G (p.Tyr571Ter)
NM_000033.4(ABCD1):c.430G>A (p.Ala144Thr)
NM_000033.4(ABCD1):c.1600C>A (p.Pro534Thr)
NM_000033.4(ABCD1):c.1224+1G>T
NM_000033.4(ABCD1):c.1634+1G>C
NM_000033.4(ABCD1):c.346G>T (p.Gly116Ter)
NM_000033.4(ABCD1):c.2000A>G (p.His667Arg)
NM_000033.4(ABCD1):c.1875C>A (p.Tyr625Ter)
NM_000033.4(ABCD1):c.397C>T (p.Gln133Ter)
NM_000033.4(ABCD1):c.220C>T (p.Arg74Trp)
NM_000033.4(ABCD1):c.1510C>T (p.Leu504Phe)
NM_000033.4(ABCD1):c.935A>G (p.Asp312Gly)
NM_000033.4(ABCD1):c.331G>A (p.Val111Met)
NM_000033.4(ABCD1):c.978G>A (p.Trp326Ter)
NM_000033.4(ABCD1):c.893G>A (p.Gly298Asp)
NM_000033.4(ABCD1):c.2080G>T (p.Glu694Ter)
NM_000033.4(ABCD1):c.1454C>A (p.Ser485Ter)
NM_000033.4(ABCD1):c.1781-1G>T
NM_000033.4(ABCD1):c.830G>A (p.Gly277Glu)
NM_000033.4(ABCD1):c.1678C>T (p.Pro560Ser)
NM_000033.4(ABCD1):c.1081+1G>C
NM_000033.4(ABCD1):c.872A>C (p.Glu291Ala)
NM_000033.4(ABCD1):c.1478T>A (p.Leu493His)
NM_000033.4(ABCD1):c.830G>C (p.Gly277Ala)
NM_000033.4(ABCD1):c.455G>A (p.Arg152His)
NM_000033.4(ABCD1):c.824G>A (p.Arg275Gln)
NM_000033.4(ABCD1):c.992A>T (p.Glu331Val)
NM_000033.4(ABCD1):c.99C>A (p.Tyr33Ter)
NM_000033.4(ABCD1):c.250C>T (p.Pro84Ser)
NM_000033.4(ABCD1):c.293C>A (p.Ser98Ter)
NM_000033.4(ABCD1):c.359G>C (p.Arg120Pro)
NM_000033.4(ABCD1):c.520T>C (p.Tyr174His)
NM_000033.4(ABCD1):c.788C>T (p.Pro263Leu)
NM_000033.4(ABCD1):c.836T>C (p.Leu279Pro)
NM_000033.4(ABCD1):c.869C>G (p.Ser290Trp)
NM_000033.4(ABCD1):c.1394-2A>G
NM_000033.4(ABCD1):c.1478T>C (p.Leu493Pro)
NM_000033.4(ABCD1):c.1600C>T (p.Pro534Ser)
NM_000033.4(ABCD1):c.1667A>G (p.Gln556Arg)
NM_000033.4(ABCD1):c.1772G>C (p.Arg591Pro)
NM_000033.4(ABCD1):c.1918G>A (p.Glu640Lys)
NM_000033.4(ABCD1):c.1241G>A (p.Gly414Asp)
NM_000033.4(ABCD1):c.1222G>T (p.Glu408Ter)
NM_000033.4(ABCD1):c.1831C>T (p.Gln611Ter)
NM_000033.4(ABCD1):c.1961T>A (p.Leu654Gln)
NM_000033.4(ABCD1):c.1634+1G>T
NM_000033.4(ABCD1):c.1586G>T (p.Gly529Val)
NM_000033.4(ABCD1):c.581A>T (p.Asp194Val)
NM_000033.4(ABCD1):c.309C>A (p.Ser103Arg)
NM_000033.4(ABCD1):c.850T>C (p.Ser284Pro)
NM_000033.4(ABCD1):c.917T>G (p.Leu306Arg)
NM_000033.4(ABCD1):c.1877C>T (p.Ala626Val)
NM_000033.4(ABCD1):c.659T>G (p.Leu220Arg)
NM_000033.4(ABCD1):c.1939G>T (p.Ala647Ser)
NM_000033.4(ABCD1):c.1866-2A>T
NM_000033.4(ABCD1):c.686T>C (p.Leu229Pro)
NM_000033.4(ABCD1):c.893G>T (p.Gly298Val)
NM_000033.4(ABCD1):c.1533C>A (p.Cys511Ter)
NM_000033.4(ABCD1):c.1428C>A (p.Cys476Ter)
NM_000033.4(ABCD1):c.1673T>C (p.Ile558Thr)
NM_000033.4(ABCD1):c.900+1G>C
NM_000033.4(ABCD1):c.892G>T (p.Gly298Cys)
NM_000033.4(ABCD1):c.1252C>G (p.Arg418Gly)
NM_000033.4(ABCD1):c.1831C>G (p.Gln611Glu)
NM_000033.4(ABCD1):c.1993A>T (p.Lys665Ter)
NM_000033.4(ABCD1):c.1781-1G>C
NM_000033.4(ABCD1):c.91A>T (p.Lys31Ter)
NM_000033.4(ABCD1):c.396G>A (p.Trp132Ter)
NM_000033.4(ABCD1):c.532C>T (p.Gln178Ter)
NM_000033.4(ABCD1):c.569T>C (p.Leu190Pro)
NM_000033.4(ABCD1):c.668C>A (p.Ala223Asp)
NM_000033.4(ABCD1):c.760A>C (p.Thr254Pro)
NM_000033.4(ABCD1):c.900+1G>T
NM_000033.4(ABCD1):c.906G>C (p.Glu302Asp)
NM_000033.4(ABCD1):c.1531T>C (p.Cys511Arg)
NM_000033.4(ABCD1):c.1640A>G (p.Tyr547Cys)
NM_000033.4(ABCD1):c.1666C>T (p.Gln556Ter)
NM_000033.4(ABCD1):c.898G>T (p.Glu300Ter)
NM_000033.4(ABCD1):c.1489-1G>T
NM_000033.4(ABCD1):c.938T>C (p.Leu313Pro)
NM_000033.4(ABCD1):c.163C>T (p.Gln55Ter)
NM_000033.4(ABCD1):c.1202G>T (p.Arg401Leu)
NM_000033.4(ABCD1):c.977G>A (p.Trp326Ter)
NM_000033.4(ABCD1):c.1082-2A>G
NM_000033.4(ABCD1):c.1597A>G (p.Lys533Glu)
NM_000033.4(ABCD1):c.1865+1G>C
NM_000033.4(ABCD1):c.2005C>T (p.His669Tyr)
NM_000033.4(ABCD1):c.632T>C (p.Leu211Pro)
NM_000033.4(ABCD1):c.1833G>C (p.Gln611His)
NM_000033.4(ABCD1):c.1187C>A (p.Ala396Glu)
NM_000033.4(ABCD1):c.311G>C (p.Arg104Pro)
NM_000033.4(ABCD1):c.582C>A (p.Asp194Glu)
NM_000033.4(ABCD1):c.427C>G (p.Pro143Ala)
NM_000033.4(ABCD1):c.1715C>A (p.Ser572Ter)
NM_000033.4(ABCD1):c.1865+1G>T
NM_000033.4(ABCD1):c.901-1G>C
NM_000033.4(ABCD1):c.1888G>T (p.Glu630Ter)
NM_000033.4(ABCD1):c.1894A>C (p.Thr632Pro)
NM_000033.4(ABCD1):c.433A>C (p.Thr145Pro)
NM_000033.4(ABCD1):c.487C>A (p.Arg163Ser)
NM_000033.4(ABCD1):c.509C>A (p.Ala170Asp)
NM_000033.4(ABCD1):c.1640A>T (p.Tyr547Phe)
NM_000033.4(ABCD1):c.1976A>G (p.His659Arg)
NM_000033.4(ABCD1):c.796G>C (p.Gly266Arg)
NM_000033.4(ABCD1):c.274G>C (p.Gly92Arg)
NM_000033.4(ABCD1):c.1256T>C (p.Val419Ala)
NM_014049.5(ACAD9):c.1249C>T (p.Arg417Cys)
NM_014049.5(ACAD9):c.130T>A (p.Phe44Ile)
NM_014049.5(ACAD9):c.797G>A (p.Arg266Gln)
NM_014049.5(ACAD9):c.976G>C (p.Ala326Pro)
NM_014049.5(ACAD9):c.1594C>T (p.Arg532Trp)
NM_014049.5(ACAD9):c.1A>G (p.Met1Val)
NM_014049.5(ACAD9):c.151-2A>G
NM_014049.5(ACAD9):c.796C>T (p.Arg266Trp)
NM_014049.5(ACAD9):c.1237G>A (p.Glu413Lys)
NM_014049.5(ACAD9):c.1552C>T (p.Arg518Cys)
NM_014049.5(ACAD9):c.1595G>A (p.Arg532Gln)
NM_014049.5(ACAD9):c.1687C>G (p.His563Asp)
NM_014049.5(ACAD9):c.514G>A (p.Gly172Arg)
NM_014049.5(ACAD9):c.1240C>T (p.Arg414Cys)
NM_014049.5(ACAD9):c.1030-1G>A
NM_014049.5(ACAD9):c.1693-2A>G
NM_014049.5(ACAD9):c.1825C>T (p.Arg609Ter)
NM_014049.5(ACAD9):c.453+2T>A
NM_014049.5(ACAD9):c.1429C>T (p.Arg477Ter)
NM_014049.5(ACAD9):c.1553G>A (p.Arg518His)
NM_014049.5(ACAD9):c.1563+1G>A
NM_014049.5(ACAD9):c.1358+1G>C
NM_014049.5(ACAD9):c.632A>G (p.Lys211Arg)
NM_014049.5(ACAD9):c.842C>T (p.Pro281Leu)
NM_014049.5(ACAD9):c.1173G>A (p.Trp391Ter)
NM_014049.5(ACAD9):c.633+2T>A
NM_014049.5(ACAD9):c.1278+1G>A
NM_014049.5(ACAD9):c.882+1G>A
NM_014049.5(ACAD9):c.1359-2A>G
NM_014049.5(ACAD9):c.253C>T (p.Arg85Ter)
NM_014049.5(ACAD9):c.1218C>A (p.Tyr406Ter)
NM_014049.5(ACAD9):c.1462G>T (p.Gly488Ter)

### some variants have a "=" in their name: e.g
* NM_000033.4(ABCD1):c.900G>A (p.Glu300=)
* NM_000033.4(ABCD1):c.1224G>A (p.Glu408=)
##### Let's take a closer look at all vairants with that naming style

In [58]:
for gene in lociii:
    vardata = pd.read_csv("pathogenic_lociii/" + gene + ".csv", sep= "\t")
    for x in vardata["Name"]:
        if "(p." in x and "=" in x:
            print(x)

NM_173076.3(ABCA12):c.1782G>A (p.Glu594=)
NM_173076.3(ABCA12):c.4977G>A (p.Glu1659=)
NM_000033.4(ABCD1):c.900G>A (p.Glu300=)
NM_000033.4(ABCD1):c.1224G>A (p.Glu408=)
NM_000016.6(ACADM):c.85C>A (p.Arg29=)
NM_000018.4(ACADVL):c.1332G>A (p.Lys444=)
NM_000018.4(ACADVL):c.552C>A (p.Ile184=)
NM_000018.4(ACADVL):c.852G>A (p.Val284=)
NM_001134831.2(AHI1):c.2106G>A (p.Thr702=)
NM_000478.6(ALPL):c.1161A>G (p.Gly387=)
NM_000038.6(APC):c.834G>A (p.Gln278=)
NM_000038.6(APC):c.1956C>T (p.His652=)
NM_000038.6(APC):c.1548G>A (p.Lys516=)
NM_000038.6(APC):c.1957A>C (p.Arg653=)
NM_000038.6(APC):c.933G>A (p.Lys311=)
NM_000044.6(AR):c.2667C>T (p.Ser889=)
NM_000487.6(ARSA):c.1200C>T (p.Phe400=)
NM_000049.4(ASPA):c.432G>A (p.Lys144=)
NM_018136.5(ASPM):c.5064T>N (p.Thr1688=)
NM_000051.4(ATM):c.3576G>A (p.Lys1192=)
NM_000051.4(ATM):c.6807G>A (p.Gln2269=)
NM_000051.4(ATM):c.7788G>A (p.Glu2596=)
NM_000051.4(ATM):c.3873T>G (p.Leu1291=)
NM_000051.4(ATM):c.6451A>C (p.Arg2151=)
NM_000051.4(ATM):c.72G>A (p.Lys24=)
NM_000051.4(ATM):c.5319G>A (p.Lys1773=)
NM_000053.4(ATP7B):c.2355G>A (p.Lys785=)
NM_000053.4(ATP7B):c.1488C>T (p.Gly496=)
NM_031885.5(BBS2):c.471G>A (p.Thr157=)
NM_031885.5(BBS2):c.1797G>A (p.Lys599=)
NM_004183.4(BEST1):c.102C>T (p.Gly34=)
NM_032043.3(BRIP1):c.507G>A (p.Gln169=)
NM_032043.3(BRIP1):c.1794G>A (p.Val598=)
NM_001370658.1(BTD):c.399G>A (p.Glu133=)
NM_000061.3(BTK):c.240G>A (p.Pro80=)
NM_001378615.1(CC2D2A):c.2625G>A (p.Ser875=)
NM_022124.6(CDH23):c.5712G>A (p.Thr1904=)
NM_022124.6(CDH23):c.7362G>A (p.Thr2454=)
NM_022124.6(CDH23):c.7872G>A (p.Glu2624=)
NM_025114.4(CEP290):c.180G>A (p.Lys60=)
NM_025114.4(CEP290):c.3309G>A (p.Glu1103=)
NM_000492.4(CFTR):c.2988G>A (p.Gln996=)
NM_000492.4(CFTR):c.1209G>A (p.Glu403=)
NM_000492.4(CFTR):c.3468G>A (p.Leu1156=)
NM_000492.4(CFTR):c.3717G>A (p.Arg1239=)
NM_000492.4(CFTR):c.273G>C (p.Gly91=)
NM_000492.4(CFTR):c.1398A>T (p.Ser466=)
NM_017780.4(CHD7):c.4533G>A (p.Lys1511=)
NM_201253.3(CRB1):c.2598A>C (p.Pro866=)
NM_004937.3(CTNS):c.681G>A (p.Glu227=)
NM_000397.4(CYBB):c.252G>A (p.Ala84=)
NM_000397.4(CYBB):c.483G>A (p.Lys161=)
NM_000497.4(CYP11B1):c.954G>A (p.Thr318=)
NM_000497.4(CYP11B1):c.954G>C (p.Thr318=)
NM_000497.4(CYP11B1):c.954G>T (p.Thr318=)
NM_000102.4(CYP17A1):c.1263G>A (p.Ala421=)
NM_000102.4(CYP17A1):c.969G>A (p.Gln323=)
NM_000784.4(CYP27A1):c.1017G>C (p.Thr339=)
NM_000784.4(CYP27A1):c.435G>T (p.Gly145=)
NM_177438.3(DICER1):c.5439G>A (p.Glu1813=)
NM_177438.3(DICER1):c.2523A>G (p.Gln841=)
NM_024757.5(EHMT1):c.3447C>T (p.Gly1149=)
NM_003640.5(ELP1):c.312T>C (p.Cys104=)
NM_153717.3(EVC):c.384G>T (p.Arg128=)
NM_207122.2(EXT2):c.1173G>A (p.Gln391=)
NM_207122.2(EXT2):c.1242C>T (p.Ile414=)
NM_001142800.2(EYS):c.1485G>C (p.Gly495=)
NM_019616.4(F7):c.225G>C (p.Thr75=)
NM_000132.4(F8):c.5586G>A (p.Leu1862=)
NM_000132.4(F8):c.1569G>T (p.Leu523=)
NM_000132.4(F8):c.5217C>T (p.Asn1739=)
NM_000132.4(F8):c.6273G>A (p.Lys2091=)
NM_000132.4(F8):c.1167A>G (p.Gln389=)
NM_000133.4(F9):c.459G>A (p.Val153=)
NM_000133.4(F9):c.723G>A (p.Gln241=)
NM_000133.4(F9):c.484C>A (p.Arg162=)
NM_000135.4(FANCA):c.3513G>A (p.Leu1171=)
NM_000135.4(FANCA):c.1470G>A (p.Gln490=)
NM_000135.4(FANCA):c.792G>A (p.Gln264=)
NM_144997.7(FLCN):c.1176G>C (p.Arg392=)
NM_144997.7(FLCN):c.1176G>A (p.Arg392=)
NM_144997.7(FLCN):c.1176G>T (p.Arg392=)
NM_001360016.2(G6PD):c.219C>T (p.Ser73=)
NM_001360016.2(G6PD):c.312C>T (p.Arg104=)
NM_000152.5(GAA):c.1437G>A (p.Lys479=)
NM_000152.5(GAA):c.546G>A (p.Thr182=)
NM_000152.5(GAA):c.546G>C (p.Thr182=)
NM_000152.5(GAA):c.546G>T (p.Thr182=)
NM_000152.5(GAA):c.858G>A (p.Thr286=)
NM_000152.5(GAA):c.2040G>A (p.Leu680=)
NM_000152.5(GAA):c.2799G>A (p.Lys933=)
NM_000153.4(GALC):c.195G>C (p.Gly65=)
NM_000512.5(GALNS):c.181C>A (p.Arg61=)
NM_000155.4(GALT):c.1014C>G (p.Gly338=)
NM_000155.4(GALT):c.1014C>T (p.Gly338=)
NM_000158.4(GBE1):c.141C>T (p.Arg47=)
NM_000159.4(GCDH):c.333A>G (p.Lys111=)
NM_000166.6(GJB1):c.57C>T (p.Ala19=)
NM_000166.6(GJB1):c.48T>C (p.His16=)
NM_005476.7(GNE):c.711G>A (p.Leu237=)
NM_024312.5(GNPTAB):c.771G>A (p.Leu257=)
NM_000518.5(HBB):c.75T>A (p.Gly25=)
NM_000518.5(HBB):c.91A>C (p.Arg31=)
NM_000518.5(HBB):c.51C>T (p.Gly17=)
NM_000520.6(HEXA):c.1305C>T (p.Tyr435=)
NM_000520.6(HEXA):c.570G>A (p.Leu190=)
NM_000521.4(HEXB):c.1242G>A (p.Lys414=)
NM_000187.4(HGD):c.753C>T (p.Gly251=)
NM_000187.4(HGD):c.189G>A (p.Arg63=)
NM_000187.4(HGD):c.15G>A (p.Lys5=)
NM_000187.4(HGD):c.507T>C (p.Phe169=)
NM_000187.4(HGD):c.549G>A (p.Gln183=)
NM_000206.3(IL2RG):c.924G>A (p.Ser308=)
NM_000206.3(IL2RG):c.924G>C (p.Ser308=)
NM_000419.5(ITGA2B):c.3060G>A (p.Lys1020=)
NM_000419.5(ITGA2B):c.408G>C (p.Val136=)
NM_000238.4(KCNH2):c.1128G>A (p.Gln376=)
NM_000218.3(KCNQ1):c.1032G>A (p.Ala344=)
NM_000218.3(KCNQ1):c.1032G>C (p.Ala344=)
NM_000218.3(KCNQ1):c.921G>A (p.Val307=)
NM_000218.3(KCNQ1):c.1032G>T (p.Ala344=)
NM_001278116.2(L1CAM):c.924C>T (p.Gly308=)
NM_000527.5(LDLR):c.1216C>A (p.Arg406=)
NM_000527.5(LDLR):c.621C>T (p.Gly207=)
NM_000527.5(LDLR):c.1813C>T (p.Leu605=)
NM_000527.5(LDLR):c.528C>T (p.Gly176=)
NM_000527.5(LDLR):c.2253G>A (p.Arg751=)
NM_000527.5(LDLR):c.2139A>G (p.Thr713=)
NM_000235.4(LIPA):c.894G>A (p.Gln298=)
NM_000235.4(LIPA):c.600G>A (p.Leu200=)
NM_000528.4(MAN2B1):c.2355G>A (p.Thr785=)
NM_000530.8(MPZ):c.276G>A (p.Val92=)
NM_000530.8(MPZ):c.309G>T (p.Gly103=)
NM_000530.8(MPZ):c.411C>T (p.Gly137=)
NM_000530.8(MPZ):c.279G>T (p.Gly93=)
NM_000251.3(MSH2):c.2634G>A (p.Glu878=)
NM_000251.3(MSH2):c.942G>A (p.Gln314=)
NM_000251.3(MSH2):c.2004T>A (p.Thr668=)
NM_005957.5(MTHFR):c.1320G>A (p.Ser440=)
NM_005957.5(MTHFR):c.1530G>A (p.Lys510=)
NM_005957.5(MTHFR):c.474A>T (p.Gly158=)
NM_005957.5(MTHFR):c.1011G>T (p.Gly337=)
NM_001048174.2(MUTYH):c.606G>A (p.Gln202=)
NM_001042492.3(NF1):c.2709G>A (p.Val903=)
NM_001042492.3(NF1):c.4332G>A (p.Lys1444=)
NM_001042492.3(NF1):c.6864A>G (p.Gln2288=)
NM_001042492.3(NF1):c.1062G>A (p.Lys354=)
NM_001042492.3(NF1):c.2325G>A (p.Glu775=)
NM_001042492.3(NF1):c.2850G>A (p.Gln950=)
NM_001042492.3(NF1):c.1845G>A (p.Lys615=)
NM_001042492.3(NF1):c.6921G>A (p.Lys2307=)
NM_001042492.3(NF1):c.1185G>A (p.Lys395=)
NM_001042492.3(NF1):c.288G>T (p.Gly96=)
NM_001042492.3(NF1):c.6006G>A (p.Gln2002=)
NM_001042492.3(NF1):c.6858C>T (p.Asn2286=)
NM_001042492.3(NF1):c.5610G>T (p.Arg1870=)
NM_000268.4(NF2):c.810G>A (p.Glu270=)
NM_133433.4(NIPBL):c.345A>G (p.Arg115=)
NM_133433.4(NIPBL):c.7623G>A (p.Gln2541=)
NM_133433.4(NIPBL):c.5427G>A (p.Arg1809=)
NM_133433.4(NIPBL):c.6819G>T (p.Gly2273=)
NM_133433.4(NIPBL):c.4086A>G (p.Gly1362=)
NM_000275.3(OCA2):c.1080C>T (p.Ser360=)
NM_000275.3(OCA2):c.1860G>C (p.Gly620=)
NM_000275.3(OCA2):c.2139G>A (p.Lys713=)
NM_130837.3(OPA1):c.1149G>A (p.Lys383=)
NM_130837.3(OPA1):c.2661G>A (p.Leu887=)
NM_130837.3(OPA1):c.1305G>A (p.Glu435=)
NM_130837.3(OPA1):c.1935G>T (p.Arg645=)
NM_000277.3(PAH):c.1197A>T (p.Val399=)
NM_000277.3(PAH):c.1194A>G (p.Lys398=)
NM_000277.3(PAH):c.912G>A (p.Gln304=)
NM_024675.4(PALB2):c.2559C>T (p.Gly853=)
NM_024675.4(PALB2):c.18G>T (p.Gly6=)
NM_024675.4(PALB2):c.48G>A (p.Lys16=)
NM_181458.4(PAX3):c.450A>G (p.Ser150=)
NM_001368894.2(PAX6):c.723A>G (p.Lys241=)
NM_001368894.2(PAX6):c.375C>A (p.Val125=)
NM_001368894.2(PAX6):c.216C>T (p.Gly72=)
NM_001368894.2(PAX6):c.807G>A (p.Gln269=)
NM_001368894.2(PAX6):c.141G>A (p.Gln47=)
NM_138694.4(PKHD1):c.6900C>T (p.Asn2300=)
NM_138694.4(PKHD1):c.51A>G (p.Ala17=)
NM_017739.4(POMGNT1):c.636C>T (p.Phe212=)
NM_005609.4(PYGM):c.1827G>A (p.Lys609=)
NM_006269.2(RP1):c.5502G>A (p.Leu1834=)
NM_014251.3(SLC25A13):c.15G>A (p.Lys5=)
NM_000441.2(SLC26A4):c.1002G>T (p.Gly334=)
NM_000441.2(SLC26A4):c.1206G>A (p.Val402=)
NM_000441.2(SLC26A4):c.1230G>A (p.Thr410=)
NM_000543.5(SMPD1):c.1167T>G (p.Arg389=)
NM_014946.4(SPAST):c.870G>A (p.Lys290=)
NM_014946.4(SPAST):c.1107A>G (p.Thr369=)
NM_014946.4(SPAST):c.1242A>G (p.Lys414=)
NM_014946.4(SPAST):c.780T>G (p.Leu260=)
NM_025137.4(SPG11):c.6204A>G (p.Thr2068=)
NM_006019.4(TCIRG1):c.630G>A (p.Thr210=)
NM_153704.6(TMEM67):c.2439G>A (p.Ala813=)
NM_000546.6(TP53):c.672G>A (p.Glu224=)
NM_000546.6(TP53):c.375G>A (p.Thr125=)
NM_000546.6(TP53):c.375G>T (p.Thr125=)
NM_000546.6(TP53):c.993G>A (p.Gln331=)
NM_000546.6(TP53):c.375G>C (p.Thr125=)
NM_000546.6(TP53):c.549A>T (p.Ser183=)
NM_000546.6(TP53):c.801G>C (p.Arg267=)
NM_000391.4(TPP1):c.225A>G (p.Gln75=)
NM_153676.4(USH1C):c.216G>A (p.Val72=)
NM_206933.4(USH2A):c.949C>A (p.Arg317=)
NM_206933.4(USH2A):c.2139C>T (p.Gly713=)
NM_206933.4(USH2A):c.15192A>G (p.Gln5064=)
NM_206933.4(USH2A):c.14103A>G (p.Glu4701=)
NM_206933.4(USH2A):c.4083A>C (p.Ala1361=)
NM_000551.4(VHL):c.414A>G (p.Pro138=)
NM_000551.4(VHL):c.462A>T (p.Pro154=)
NM_033305.3(VPS13A):c.7806G>A (p.Pro2602=)
NM_152564.5(VPS13B):c.1563G>A (p.Lys521=)
NM_000552.5(VWF):c.7437G>A (p.Ser2479=)
NM_000552.5(VWF):c.7464C>T (p.Gly2488=)
NM_000552.5(VWF):c.3390C>T (p.Cys1130=)
NM_000552.5(VWF):c.7056C>T (p.Gly2352=)
NM_000553.6(WRN):c.561A>G (p.Lys187=)

### Apparently ClinVar Naming style depends on the form of variation occuring:
* NM_024301.5(FKRP):c.899T>C (p.Val300Ala)   means  @ aminoacid 300   Val → Ala
* NM_000166.6(GJB1):c.131G>A (p.Trp44Ter)   means  @ aminoacid 44    Trp → STOP codon
* NM_000033.4(ABCD1):c.900G>A (p.Glu300=)   means  @ aminoacid 300   Glu → Glu (remains unchanged)
* NM_001033855.3(DCLRE1C):c.1085C>N (p.Ser362Xaa)   means  @ aminoacid 362   Ser → Unknown

#### Rerun STEP 4 after cleanup (if need be)

### STEP 5 
#### Match variant transcript to corresponding protein (this will serve as reference protein)

In [62]:
run kondrashov

In [63]:
print('gene \t transcript \t protein \t changes')
for gene in lociii:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        #print(transcript)
        sites, wilds, muts = get_all_changes(gene, transcript, True)
        print(gene, '\t', transcript, '\t', translation[transcript], '\t', len(sites))

gene 	 transcript 	 protein 	 changes
ABCA12 	 NM_173076.3 	 NP_775099.2 	 134
ABCD1 	 NM_000033.4 	 NP_000024.2 	 327
ACAD9 	 NM_014049.5 	 NP_054768.2 	 103
ACADM 	 NM_000016.6 	 NP_000007.1 	 253
ACADVL 	 NM_000018.4 	 NP_000009.1 	 286
ACAT1 	 NM_000019.4 	 NP_000010.1 	 119
ADA 	 NM_000022.4 	 NP_000013.2 	 106
AGL 	 NM_000642.3 	 NP_000019.2 	 307
AGXT 	 NM_000030.3 	 NP_000021.1 	 232
AHI1 	 NM_001134831.2 	 NP_001128302.1 	 134
AIRE 	 NM_000383.4 	 NP_000374.1 	 120
ALMS1 	 NM_001378454.1 	 NP_001365383.1 	 435
ALOX12B 	 NM_001139.3 	 NP_001130.1 	 104
ALPL 	 NM_000478.6 	 NP_000469.3 	 404
ANK1 	 NM_000037.4 	 NP_000028.3 	 222
ANO5 	 NM_213599.3 	 NP_998764.1 	 127
APC 	 NM_001127511.3 	 NP_001120983.2 	 5
APC 	 NM_001127510.3 	 NP_000029.2 	 1
APC 	 NM_000038.6 	 NP_000029.2 	 758
AR 	 NM_000044.6 	 NP_000035.2 	 269
ARSA 	 NM_000487.6 	 NP_000478.3 	 263
ARSB 	 NM_000046.5 	 NP_000037.2 	 166
ASL 	 NM_000048.4 	 NP_000039.2 	 176
ASPA 	 NM_000049.4 	 NP_000040.1 	 112
ASPM 	 NM_018136.5 	 NP_060606.3 	 151
ATM 	 NM_000051.4 	 NP_000042.3 	 1343
ATP7B 	 NM_000053.4 	 NP_000044.2 	 424
BBS2 	 NM_031885.5 	 NP_001364385.1 	 133
BCKDHA 	 NM_000709.4 	 NP_000700.1 	 113
BEST1 	 NM_004183.4 	 NP_004174.1 	 278
BLM 	 NM_000057.4 	 NP_000048.1 	 221
BRIP1 	 NM_032043.3 	 NP_114432.2 	 326
BTD 	 NM_001370658.1 	 NP_001268652.2 	 161
BTK 	 NM_000061.3 	 NP_000052.1 	 244
CASR 	 NM_000388.4 	 NP_000379.3 	 206
CBS 	 NM_000071.3 	 NP_000062.1 	 197
CC2D2A 	 NM_001378615.1 	 NP_001073991.2 	 194
CDH23 	 NM_022124.6 	 NP_071407.4 	 382
CEP290 	 NM_025114.4 	 NP_079390.3 	 463
CERKL 	 NM_201548.5 	 NP_963842.1 	 104
CFTR 	 NM_000492.4 	 NP_000483.3 	 770
CFTR 	 NM_000492.3 	 NP_000483.3 	 2
CHD7 	 NM_017780.4 	 NP_060250.2 	 426
CHEK2 	 NM_007194.4 	 NP_009125.1 	 295
CLN3 	 NM_001042432.2 	 NP_000077.1 	 127
CNGB3 	 NM_019098.5 	 NP_061971.3 	 147
CPS1 	 NM_001875.5 	 NP_001866.2 	 262
CRB1 	 NM_201253.3 	 NP_957705.1 	 357
CTNS 	 NM_004937.3 	 NP_004928.2 	 112
CYBB 	 NM_000397.4 	 NP_000388.2 	 141
CYP11B1 	 NM_000497.4 	 NP_000488.3 	 126
CYP17A1 	 NM_000102.4 	 NP_000093.1 	 107
CYP27A1 	 NM_000784.4 	 NP_000775.1 	 124
DCLRE1C 	 NM_001033855.3 	 NP_001029027.1 	 103
DICER1 	 NM_177438.3 	 NP_001258211.1 	 326
DUOX2 	 NM_001363711.2 	 NP_001350640.1 	 145
EHMT1 	 NM_024757.5 	 NP_079033.4 	 129
ELP1 	 NM_003640.5 	 NP_003631.2 	 229
ERCC6 	 NM_000124.4 	 NP_000115.1 	 172
ERCC6 	 NM_001277058.2 	 NP_001263987.1 	 6
EVC 	 NM_153717.3 	 NP_714928.1 	 149
EVC2 	 NM_147127.5 	 NP_667338.3 	 173
EXT1 	 NM_000127.3 	 NP_000118.2 	 242
EXT2 	 NM_207122.2 	 NP_001376557.1 	 115
EYS 	 NM_001142800.2 	 NP_001136272.1 	 483
F7 	 NM_000131.5 	 NP_000122.1 	 1
F7 	 NM_019616.4 	 NP_062562.1 	 75
F7 	 NM_000131.4 	 NP_000122.1 	 2
F8 	 NM_000132.4 	 NP_000123.1 	 511
F9 	 NM_000133.4 	 NP_000124.1 	 271
FANCA 	 NM_000135.4 	 NP_000126.2 	 528
FANCI 	 NM_001113378.2 	 NP_001106849.1 	 141
FBN2 	 NM_001999.4 	 NP_001990.2 	 116
FKRP 	 NM_024301.5 	 NP_001034974.1 	 119
FLCN 	 NM_144997.7 	 NP_001340159.1 	 156
FRAS1 	 NM_025074.7 	 NP_079350.5 	 180
G6PD 	 NM_000402.4 	 NP_000393.4 	 42
G6PD 	 NM_001360016.2 	 NP_001035810.1 	 164
G6PD 	 NM_001042351.3 	 NP_001035810.1 	 1
GAA 	 NM_000152.5 	 NP_000143.2 	 451
GALC 	 NM_000153.4 	 NP_000144.2 	 233
GALNS 	 NM_000512.5 	 NP_000503.1 	 222
GALT 	 NM_000155.4 	 NP_000146.2 	 247
GBA1 	 NM_000157.4 	 NP_000148.2 	 293
GBE1 	 NM_000158.4 	 NP_000149.4 	 121
GCDH 	 NM_000159.4 	 NP_000150.1 	 257
GJB1 	 NM_000166.6 	 NP_000157.1 	 200
GJB1 	 NM_001097642.3 	 NP_000157.1 	 1
GLB1 	 NM_000404.4 	 NP_000395.3 	 229
GNE 	 NM_001128227.3 	 NP_001121699.1 	 4
GNE 	 NM_005476.7 	 NP_005467.1 	 133
GNPTAB 	 NM_024312.5 	 NP_077288.2 	 195
HBB 	 NM_000518.4 	 NP_000509.1 	 33
HBB 	 NM_000518.5 	 NP_000509.1 	 141
HEXA 	 NM_000520.6 	 NP_000511.2 	 207
HEXB 	 NM_000521.4 	 NP_000512.2 	 103
HGD 	 NM_000187.4 	 NP_000178.2 	 203
HGSNAT 	 NM_152419.3 	 NP_689632.2 	 113
HMBS 	 NM_000190.4 	 NP_000181.2 	 108
HPRT1 	 NM_000194.3 	 NP_000185.1 	 61
HPRT1 	 NM_000194.2 	 NP_000185.1 	 9
HPS3 	 NM_032383.5 	 NP_115759.2 	 122
IL2RG 	 NM_000206.3 	 NP_000197.1 	 113
ITGA2B 	 NM_000419.5 	 NP_000410.2 	 165
IVD 	 NM_002225.5 	 NP_002216.3 	 107
KCNH2 	 NM_000238.4 	 NP_000229.1 	 320
KCNQ1 	 NM_000218.3 	 NP_000209.2 	 365
KRIT1 	 NM_194454.3 	 NP_001337601.1 	 156
L1CAM 	 NM_001278116.2 	 NP_000416.1 	 146
LDLR 	 NM_000527.5 	 NP_000518.1 	 1087
LDLR 	 NM_000527.4 	 NP_000518.1 	 6
LIPA 	 NM_000235.4 	 NP_000226.2 	 102
LOXHD1 	 NM_001384474.1 	 NP_001371403.1 	 253
LPL 	 NM_000237.3 	 NP_000228.1 	 115
LRPPRC 	 NM_133259.4 	 NP_573566.2 	 169
LYST 	 NM_000081.4 	 NP_000072.2 	 150
MAN2B1 	 NM_000528.4 	 NP_000519.2 	 187
MCCC1 	 NM_020166.5 	 NP_064551.3 	 107
MCCC2 	 NM_022132.5 	 NP_071415.1 	 133
MED13L 	 NM_015335.5 	 NP_056150.1 	 149
MFN2 	 NM_014874.4 	 NP_001121132.1 	 162
MKS1 	 NM_017777.4 	 NP_060247.2 	 107
MMUT 	 NM_000255.4 	 NP_000246.2 	 288
MPZ 	 NM_000530.8 	 NP_000521.2 	 143
MSH2 	 NM_000251.3 	 NP_000242.1 	 614
MTHFR 	 NM_005957.5 	 NP_005948.3 	 130
MUTYH 	 NM_001128425.2 	 NP_001121897.1 	 5
MUTYH 	 NM_001048174.2 	 NP_001041636.2 	 207
MYH7 	 NM_000257.4 	 NP_000248.2 	 406
NAGLU 	 NM_000263.4 	 NP_000254.2 	 183
NF1 	 NM_001042492.3 	 NP_001035957.1 	 1881
NF2 	 NM_000268.4 	 NP_000259.1 	 161
NIPBL 	 NM_133433.4 	 NP_597677.2 	 309
NPC1 	 NM_000271.5 	 NP_000262.2 	 361
NSD1 	 NM_022455.5 	 NP_001396230.1 	 365
OCA2 	 NM_000275.3 	 NP_000266.2 	 199
OPA1 	 NM_130837.3 	 NP_570850.2 	 210
PAH 	 NM_000277.3 	 NP_000268.1 	 689
PALB2 	 NM_024675.4 	 NP_078951.2 	 390
PAX3 	 NM_181457.3 	 NP_852122.1 	 1
PAX3 	 NM_181458.4 	 NP_852123.1 	 125
PAX6 	 NM_001368894.2 	 NP_001245391.1 	 226
PAX6 	 NM_000280.6 	 NP_000271.1 	 1
PCDH15 	 NM_033056.4 	 NP_149045.3 	 9
PCDH15 	 NM_001384140.1 	 NP_001371069.1 	 196
PCNT 	 NM_006031.6 	 NP_006022.3 	 188
PKHD1 	 NM_138694.4 	 NP_619639.3 	 786
PMM2 	 NM_000303.3 	 NP_000294.1 	 173
POMGNT1 	 NM_017739.4 	 NP_001424582.1 	 139
PRPF31 	 NM_015629.4 	 NP_056444.3 	 117
PYGM 	 NM_005609.4 	 NP_005600.1 	 157
RAD50 	 NM_005732.4 	 NP_005723.2 	 210
RARS2 	 NM_020320.5 	 NP_064716.2 	 140
RECQL4 	 NM_004260.4 	 NP_004251.4 	 180
RHO 	 NM_000539.3 	 NP_000530.1 	 173
RP1 	 NM_001375654.1 	 NP_001362583.1 	 1
RP1 	 NM_006269.2 	 NP_006260.1 	 128
RPGRIP1L 	 NM_015272.5 	 NP_056087.2 	 178
SACS 	 NM_014363.6 	 NP_055178.3 	 339
SATB2 	 NM_001172509.2 	 NP_001165980.1 	 116
SATB2 	 NM_001172517.1 	 NP_001165980.1 	 1
SCN4A 	 NM_000334.4 	 NP_000325.4 	 135
SERPING1 	 NM_000062.3 	 NP_000053.2 	 200
SGSH 	 NM_000199.5 	 NP_000190.1 	 124
SI 	 NM_001041.4 	 NP_001032.2 	 103
SLC12A6 	 NM_001365088.1 	 NP_001352017.1 	 116
SLC25A13 	 NM_014251.3 	 NP_055066.1 	 118
SLC26A4 	 NM_000441.2 	 NP_000432.1 	 438
SMPD1 	 NM_000543.5 	 NP_000534.3 	 225
SPAST 	 NM_014946.4 	 NP_055761.2 	 354
SPG11 	 NM_025137.4 	 NP_079413.3 	 236
SYNE1 	 NM_182961.4 	 NP_892006.3 	 233
SYNE1 	 NM_001347702.2 	 NP_001334631.1 	 2
TCIRG1 	 NM_006019.4 	 NP_001427481.1 	 135
TMC1 	 NM_138691.3 	 NP_619636.2 	 118
TMEM67 	 NM_153704.6 	 NP_714915.3 	 162
TP53 	 NM_000546.6 	 NP_000537.3 	 414
TPP1 	 NM_000391.4 	 NP_000382.3 	 131
TSC1 	 NM_000368.5 	 NP_000359.1 	 281
TTR 	 NM_000371.4 	 NP_000362.1 	 130
TYR 	 NM_000372.5 	 NP_000363.1 	 237
UNC13D 	 NM_199242.3 	 NP_954712.1 	 105
USH1C 	 NM_153676.4 	 NP_710142.1 	 107
USH1C 	 NM_005709.4 	 NP_005700.2 	 5
USH2A 	 NM_206933.4 	 NP_996816.3 	 1202
VHL 	 NM_000551.4 	 NP_000542.1 	 235
VPS13A 	 NM_033305.3 	 NP_150648.2 	 242
VPS13B 	 NM_152564.5 	 NP_689777.3 	 466
VPS13B 	 NM_017890.5 	 NP_060360.3 	 8
VWF 	 NM_000552.5 	 NP_000543.3 	 310
WFS1 	 NM_006005.3 	 NP_001139325.1 	 154
WRN 	 NM_000553.6 	 NP_000544.2 	 220
WT1 	 NM_024426.6 	 NP_077744.4 	 102
XPC 	 NM_004628.5 	 NP_004619.3 	 108
ZEB2 	 NM_014795.4 	 NP_055610.1 	 159
ZFYVE26 	 NM_015346.4 	 NP_056161.2 	 211

#### save output to file "gene_transcript_changes.tsv"

In [66]:
with open("AllGenes_variantChanges.tsv", "w") as outfile:

    # Write header
    print("gene\ttranscript\tprotein\tchanges", file=outfile)

    for gene in lociii:
        transcripts = vartranscripts_filtered[gene]

        for transcript in transcripts:
            sites, wilds, muts = get_all_changes(gene, transcript, True)

            print(
                gene,
                transcript,
                translation[transcript],
                len(sites),
                sep="\t",
                file=outfile
            )

print("Results saved to 'AllGenes_variantChanges.tsv'")

Results saved to 'AllGenes_variantChanges.tsv'

### STEP 6
#### collect all valid variants in a `variants` dictionary.

In [ ]:
variants = {}
for gene in lociii:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        sites, wilds, muts = get_all_changes(gene, transcript, True)
        if len(sites)>0:
            variants.update({transcript: (sites, wilds, muts)})
    print(gene, transcript, sites[], wilds, muts)

ABCD1 NM_000033.4 ['291', '484', None, '389', '148', '174', '266', '401', '418', '464', '477', '515', '518', None, '606', '617', '617', None, '300', '141', '280', '466', '518', '529', '554', '560', '591', '601', None, '116', '136', '554', '609', '401', '296', '296', '430', None, '217', '389', '177', '163', '632', '189', '254', None, '679', '104', '148', '591', '660', None, '98', '174', '424', '666', '401', '296', '679', None, '281', '523', '543', '518', '668', '292', '609', '145', '152', '376', '626', None, '366', '512', '660', '107', '221', '27', '163', '198', '389', '396', '533', '658', '300', '116', '277', '298', '307', '485', '595', '640', None, None, '174', '141', '339', '407', '656', '114', '293', '382', '501', '666', '1', '148', '266', '283', '332', '343', '544', '560', '654', None, '543', '664', '567', '137', '220', '343', '472', '503', '559', '193', '194', '263', '631', '669', None, '221', '608', '633', '97', '495', '590', '636', '10', '108', '152', '617', '277', '200', '416', '291', '481', '262', '322', '380', '594', '606', '74', None, '173', '277', '161', '10', None, '132', '90', '163', None, None, '283', '163', '163', '311', '152', '507', '560', '631', '104', '608', '284', '408', '574', '667', '52', '559', '283', '174', '97', '211', '684', '510', '254', '512', '152', '285', None, '508', '629', '595', '98', None, '601', '373', '359', '513', '195', '318', '516', '672', '358', '343', '525', '510', '113', '157', '302', '339', '420', None, '507', '524', None, '484', None, '266', '336', '418', None, '571', '144', '534', None, None, '116', '667', '625', '133', '74', '504', '312', '111', '326', '298', '694', '485', None, '277', '560', None, '291', '493', '277', '152', '275', '331', '33', '84', '98', '120', '174', '263', '279', '290', None, '493', '534', '556', '591', '640', '414', '408', '611', '654', None, '529', '194', '103', '284', '306', '626', '220', '647', None, '229', '298', '511', '476', '558', None, '298', '418', '611', '665', None, '31', '132', '178', '190', '223', '254', None, '302', '511', '547', '556', '300', None, '313', '55', '401', '326', None, '533', None, '669', '211', '611', '396', '104', '194', '143', '572', None, None, '630', '632', '145', '163', '170', '547', '659', '266', '92', '419'] ['E', 'P', None, 'R', 'N', 'Y', 'G', 'R', 'R', 'R', 'E', 'S', 'R', None, 'S', 'R', 'R', None, 'E', 'A', 'R', 'Q', 'R', 'G', 'R', 'P', 'R', 'W', None, 'G', 'Q', 'R', 'E', 'R', 'Y', 'Y', 'Q', None, 'K', 'R', 'Q', 'R', 'T', 'R', 'T', None, 'W', 'R', 'N', 'R', 'R', None, 'S', 'Y', 'Q', 'Y', 'R', 'Y', 'W', None, 'Y', 'L', 'P', 'R', 'T', 'E', 'E', 'T', 'R', 'E', 'A', None, 'K', 'G', 'R', 'L', 'D', 'Y', 'R', 'T', 'R', 'A', 'K', 'T', 'E', 'G', 'G', 'G', 'Q', 'S', 'W', 'E', None, None, 'Y', 'A', 'W', 'K', 'S', 'L', 'I', 'T', 'M', 'Y', 'M', 'N', 'G', 'H', 'Q', 'G', 'Q', 'P', 'L', None, 'P', 'W', 'Q', 'W', 'L', 'G', 'Q', 'L', 'Y', 'P', 'D', 'P', 'C', 'H', None, 'D', 'G', 'S', 'H', 'I', 'Q', 'S', 'W', 'S', 'R', 'R', 'G', 'D', 'T', 'E', 'I', 'S', 'L', 'E', 'G', 'S', 'R', None, 'L', 'G', 'S', 'W', None, 'W', 'E', 'R', None, None, 'H', 'R', 'R', 'Q', 'R', 'G', 'P', 'C', 'R', 'G', 'S', 'E', 'Q', 'H', 'E', 'Y', 'H', 'Y', 'H', 'L', 'L', 'G', 'T', 'G', 'R', 'R', None, 'P', 'D', 'W', 'S', None, 'W', 'K', 'E', 'K', 'Q', 'N', 'L', 'Q', 'S', 'G', 'P', 'G', 'R', 'Q', 'E', 'W', 'H', None, 'G', 'W', None, 'P', None, 'G', 'K', 'R', None, 'Y', 'A', 'P', None, None, 'G', 'H', 'Y', 'Q', 'R', 'L', 'D', 'V', 'W', 'G', 'E', 'S', None, 'G', 'P', None, 'E', 'L', 'G', 'R', 'R', 'E', 'Y', 'P', 'S', 'R', 'Y', 'P', 'L', 'S', None, 'L', 'P', 'Q', 'R', 'E', 'G', 'E', 'Q', 'L', None, 'G', 'D', 'S', 'S', 'L', 'A', 'L', 'A', None, 'L', 'G', 'C', 'C', 'I', None, 'G', 'R', 'Q', 'K', None, 'K', 'W', 'Q', 'L', 'A', 'T', None, 'E', 'C', 'Y', 'Q', 'E', None, 'L', 'Q', 'R', 'W', None, 'K', None, 'H', 'L', 'Q', 'A', 'R', 'D', 'P', 'S', None, None, 'E', 'T', 'T', 'R', 'A', 'Y', 'H', 'G', 'G', 'V'] ['K', 'R', None, 'G', 'S', 'D', 'R', 'Q', 'W', '*', '*', 'F', 'W', None, 'L', 'H', 'C', None, 'E', 'T', 'C', '*', 'Q', 'D', 'S', 'L', 'W', '*', None, 'R', '*', 'H', 'K', 'G', 'C', 'H', '*', None, 'N', 'H', '*', 'H', 'I', 'W', 'M', None, '*', 'H', 'Y', 'Q', 'L', None, 'L', 'C', '*', '*', 'W', 'S', 'R', None, '*', 'F', 'L', 'G', 'I', 'D', 'G', 'A', 'C', '*', 'T', None, '*', 'S', 'W', 'P', 'A', 'S', 'C', 'M', 'C', 'T', 'Q', 'I', 'D', 'R', 'R', 'S', '*', '*', '*', 'G', None, None, 'S', 'V', 'R', '*', 'F', 'P', 'T', 'P', 'L', '*', 'V', 'D', 'E', 'D', '*', 'D', 'R', 'T', 'P', None, 'R', '*', '*', '*', 'P', 'R', '*', 'P', 'H', 'R', 'N', 'S', 'Y', 'R', None, 'N', 'S', 'R', 'P', 'N', '*', 'I', '*', 'L', 'S', 'G', 'V', 'N', 'R', 'D', 'T', 'W', 'P', '*', 'R', '*', 'L', None, 'P', 'W', '*', '*', None, '*', '*', 'L', None, None, 'Y', 'P', 'G', '*', 'P', 'S', 'R', 'R', 'C', 'A', '*', 'E', '*', 'D', '*', '*', 'R', '*', 'R', 'R', 'P', 'D', 'A', 'V', 'G', 'G', None, 'L', 'V', '*', 'W', None, 'S', '*', '*', '*', '*', 'I', 'P', '*', '*', 'V', 'L', 'S', 'P', '*', 'K', '*', 'P', None, 'D', 'R', None, 'S', None, 'A', 'E', 'P', None, '*', 'T', 'T', None, None, '*', 'R', '*', '*', 'W', 'F', 'G', 'M', '*', 'D', '*', '*', None, 'E', 'S', None, 'A', 'H', 'A', 'H', 'Q', 'V', '*', 'S', '*', 'P', 'H', 'L', 'P', 'W', None, 'P', 'S', 'R', 'P', 'K', 'D', '*', '*', 'Q', None, 'V', 'V', 'R', 'P', 'R', 'V', 'R', 'S', None, 'P', 'V', '*', '*', 'T', None, 'C', 'G', 'E', '*', None, '*', '*', '*', 'P', 'D', 'P', None, 'D', 'R', 'C', '*', '*', None, 'P', '*', 'L', '*', None, 'E', None, 'Y', 'P', 'H', 'E', 'P', 'E', 'A', '*', None, None, '*', 'P', 'P', 'S', 'D', 'F', 'R', 'R', 'R', 'A']
ALPL NM_000478.6 ['179', '71', '294', '71', '207', '33', '298', '378', '334', '327', '136', '162', '116', None, '417', '108', '456', '249', '176', '272', '72', '181', '223', '264', '270', '291', '297', None, '30', '44', None, None, None, '382', '455', '476', '223', '76', '468', '114', '272', '63', '184', '29', '166', '88', '141', None, '347', '106', '123', '136', '445', '459', '112', '210', '224', '348', '378', '442', '459', '294', '337', '491', '220', '221', '391', '391', '429', '487', '332', '132', '381', '308', '100', '111', '473', '476', None, '428', '191', '467', None, '275', '359', '388', '136', '317', '192', '450', '32', '40', '167', '167', None, '206', '246', '428', '341', '472', '410', '443', '219', '221', '112', '170', '382', None, '68', '71', '75', '101', '162', '178', '186', '220', '296', '326', '333', '414', '389', '219', '476', '292', '181', '493', '454', '121', '201', '72', '83', '473', '95', '1', '116', '184', '141', '179', '132', '395', '388', '153', '456', '476', None, '336', '456', '272', '327', '411', '468', '482', '399', '423', '377', '388', '191', '339', '374', '426', '446', '468', '476', '341', '40', '452', '132', '178', '299', '311', '455', '101', '297', '235', '459', '397', '351', '37', '171', '221', '291', '292', '295', '395', '93', '428', '173', '334', '466', '173', None, '285', '61', '477', '340', '389', '227', '414', '129', '51', '10', '420', '318', '341', '387', '82', '82', '176', '443', '416', '378', '386', '220', '171', '420', '420', '236', '178', '138', '71', '128', '76', '426', None, '117', '399', None, '497', '256', '268', '187', '1', None, '423', '71', '148', '307', '339', '371', '406', '490', None, '220', '177', '33', '294', '102', '359', '174', '466', '452', '184', '298', '262', '327', None, '63', '191', '391', '239', None, '297', '414', '294', '115', None, '443', '291', '58', '489', '441', '107', '195', '386', '55', None, '268', '489', '384', '221', '226', '226', '236', None, '111', '339', '66', '134', '408', None, '1', '306', None, '102', '491', '261', '218', '378', '389', '456', '162', '155', '171', '326', '76', None, None, '306', '102', '28', '445', None, '436', '106', '109', '112', '17', '134', '136', '148', '153', '154', None, None, '28', '29', '188', '199', '212', '226', '235', '236', None, '288', '289', '290', '292', '295', '297', '297', '328', None, None, '47', '334', '337', '340', '341', '348', '351', '371', '379', '386', '393', '1', '406', None, '420', '426', '426', '429', '430', None, '62', '441', '443', '62', '454', '466', '62', '478', '63', '489', '497', '497', '69', '75', '6', '84', '84', '85', '93', None, None, '101', '208', None, '235', '295', '384', '178', '447', '294', '377', '76', '146', '294', '306', '341', '356', '393', '393', '146', '396'] ['A', 'R', 'D', 'R', 'Q', 'A', 'E', 'D', 'G', 'F', 'R', 'G', 'A', None, 'N', 'P', 'G', 'G', 'A', 'R', 'I', 'S', 'R', 'K', 'W', 'E', 'Y', None, 'R', 'Q', None, None, None, 'V', 'G', 'E', 'R', 'Q', 'A', 'A', 'R', 'G', 'R', 'W', 'T', 'E', 'T', None, 'Q', 'Q', 'A', 'R', 'S', 'V', 'G', 'H', 'K', 'A', 'D', 'Q', 'V', 'D', 'D', 'G', 'G', 'G', 'R', 'R', 'E', 'A', 'E', 'A', 'H', 'S', 'T', 'A', 'G', 'E', None, 'R', 'E', 'M', None, 'L', 'I', 'Y', 'R', 'I', 'M', 'R', 'Q', 'A', 'T', 'T', None, 'Y', 'R', 'R', 'H', 'H', 'F', 'A', 'M', 'G', 'G', 'N', 'V', None, 'T', 'R', 'G', 'Y', 'G', 'Y', 'W', 'G', 'Q', 'G', 'G', 'L', 'T', 'M', 'E', 'P', 'S', 'N', 'H', 'V', 'C', 'I', 'E', 'G', 'V', 'M', 'A', 'R', 'T', 'A', 'A', 'I', 'Y', 'W', 'G', 'E', None, 'I', 'G', 'R', 'F', 'T', 'A', 'H', 'A', 'V', 'A', 'Y', 'E', 'G', 'V', 'G', 'A', 'A', 'E', 'H', 'A', 'E', 'A', 'Y', 'L', 'E', 'G', 'Y', 'Y', 'E', 'V', 'G', 'E', 'L', 'H', 'G', 'E', 'P', 'M', 'I', 'P', 'R', 'T', 'G', 'P', 'T', None, 'Y', 'G', 'Q', 'H', 'T', 'Y', 'L', 'G', 'A', 'I', 'G', 'Q', 'H', 'G', 'G', 'G', 'A', 'A', 'G', 'D', 'G', 'G', 'H', 'G', 'G', 'Y', 'Y', 'R', 'R', 'V', 'Q', 'G', None, 'Y', 'A', None, 'C', 'W', 'F', 'Y', 'M', None, 'V', 'R', 'T', 'P', 'G', 'T', 'D', 'I', None, 'G', 'A', 'A', 'D', 'N', 'I', 'P', 'P', 'E', 'R', 'E', 'R', 'F', None, 'G', 'E', 'R', 'D', None, 'Y', 'L', 'D', 'T', None, 'A', 'E', 'L', 'C', 'Y', 'V', 'E', 'G', 'I', None, 'F', 'C', 'T', 'G', 'M', 'M', 'Y', None, 'A', 'G', 'T', 'T', 'K', None, 'M', 'D', None, 'N', 'G', 'P', 'I', 'D', 'T', 'G', 'G', 'K', 'H', 'G', 'Q', None, None, 'D', 'N', 'Y', 'S', None, 'Y', 'Q', 'D', 'G', 'S', 'T', 'R', 'T', 'W', 'A', None, None, 'Y', 'W', 'S', 'Q', 'I', 'M', 'E', 'Y', None, 'G', 'L', 'F', 'P', 'M', 'Y', 'Y', 'F', None, None, 'N', 'G', 'D', 'H', 'H', 'A', 'E', 'T', 'H', 'G', 'N', 'M', 'D', None, 'G', 'G', 'G', 'E', 'N', None, 'M', 'Y', 'A', 'M', 'H', 'P', 'M', 'N', 'G', 'C', 'C', 'C', 'A', 'G', 'L', 'E', 'E', 'T', 'P', None, None, 'Y', 'L', None, 'E', 'M', 'T', 'Y', 'V', 'D', 'A', 'Q', 'E', 'D', 'D', 'H', 'D', 'N', 'N', 'E', 'F'] ['T', 'C', 'A', 'P', 'P', 'V', 'K', 'V', 'D', 'L', 'H', 'V', 'T', None, 'S', 'L', 'R', 'V', 'T', 'C', 'T', 'L', 'W', 'R', '*', 'K', '*', None, '*', '*', None, None, None, 'I', 'S', '*', 'Q', 'R', 'V', 'T', 'H', 'V', 'W', '*', 'I', 'K', 'N', None, '*', 'H', 'D', 'P', 'P', 'L', 'S', 'R', 'E', 'T', 'H', '*', 'M', 'Y', 'G', 'R', 'R', 'R', 'C', 'H', 'K', 'V', '*', 'V', 'R', '*', 'M', 'T', 'S', 'K', None, '*', '*', 'T', None, 'P', 'M', 'H', 'C', 'F', 'T', 'C', '*', 'V', 'K', 'M', None, 'C', 'S', 'P', 'R', 'R', 'L', 'V', 'V', 'C', 'A', 'D', 'D', None, 'M', 'H', 'S', '*', 'S', 'H', '*', 'A', '*', 'R', '*', 'M', 'N', 'I', 'A', 'T', 'W', 'K', 'Y', 'M', 'R', 'V', '*', 'D', 'E', 'V', 'S', 'Q', 'I', 'V', 'G', 'V', 'C', '*', 'E', 'G', None, 'T', 'A', 'L', 'C', 'A', 'T', 'N', 'S', 'A', 'V', '*', 'G', 'R', 'M', 'S', 'T', 'S', 'Q', 'Q', 'T', 'K', 'T', '*', 'P', 'K', 'D', 'C', 'N', 'D', 'A', 'V', '*', 'P', 'R', 'V', '*', 'S', 'V', 'T', 'L', 'Q', 'I', 'S', 'A', 'A', None, '*', 'E', 'K', 'Y', 'P', '*', 'V', 'E', 'V', 'T', 'A', '*', 'L', 'G', 'R', 'R', 'V', 'G', 'V', 'Y', 'D', 'V', 'D', 'D', 'S', 'C', '*', 'P', 'S', 'M', '*', 'D', None, '*', 'V', None, 'S', '*', 'L', '*', 'I', None, 'M', 'G', 'I', 'S', 'E', 'I', 'G', 'F', None, 'E', 'S', 'G', 'G', 'I', 'V', 'S', 'R', 'D', 'G', 'D', '*', 'L', None, 'C', 'Q', 'S', 'G', None, '*', 'P', 'N', 'I', None, 'T', 'Q', 'P', 'S', 'S', 'I', '*', 'R', 'N', None, 'L', 'F', 'P', 'A', 'R', 'I', '*', None, 'V', 'R', 'R', 'S', 'R', None, 'T', 'Y', None, 'T', 'R', 'S', 'T', 'G', 'A', 'W', 'D', '*', 'Y', 'V', 'H', None, None, 'V', 'K', 'D', 'C', None, 'C', 'R', 'E', 'R', 'F', 'N', 'L', 'A', 'R', 'V', None, None, 'C', 'R', 'P', '*', 'F', 'I', 'G', '*', None, 'A', 'F', 'L', 'L', 'I', 'D', 'H', 'L', None, None, 'H', 'R', 'N', 'P', 'Q', 'D', 'G', 'N', 'N', 'C', 'S', 'I', 'N', None, 'V', 'A', 'C', 'D', 'S', None, 'I', '*', 'E', 'I', 'R', 'L', 'V', 'I', 'R', 'S', 'R', 'Y', 'T', 'D', '*', 'K', 'V', 'P', 'S', None, None, 'D', 'F', None, 'V', 'L', 'K', 'C', 'L', 'E', 'T', 'E', 'A', 'H', 'G', 'Y', 'Y', 'I', 'K', '*', 'S']
AR NM_000044.6 ['775', '719', '867', '797', '591', '648', '764', '884', '597', '788', '857', '775', '608', '867', '856', '870', '60', '609', '841', '841', '878', '678', '878', '875', '903', '708', '580', '583', '2', '781', None, '174', '808', '889', None, '713', '578', '866', '690', '744', '744', '741', '702', '602', '753', '562', None, '772', '856', '74', '616', '856', '890', '608', '289', '753', '713', '574', '766', None, '914', '630', '750', '131', '743', '890', '908', '616', '697', None, '605', '813', '98', '766', '900', '90', '579', '602', '617', '726', '787', '832', '899', '107', '481', '701', '535', '72', '73', '248', '395', '563', '580', '605', '682', '696', '702', '706', '719', '724', '753', '767', '781', '865', '871', '77', '569', '685', None, None, '91', '633', '747', '843', '893', '155', '572', '781', '856', '710', '916', '68', '488', '611', '739', '741', '742', '764', '804', '780', '681', '746', '355', '742', '724', '752', '588', None, '886', None, '829', '752', '523', '581', '59', '904', '733', '890', '742', '832', '709', '709', '481', '1', '120', '773', None, '838', '839', '493', '70', '399', '403', '728', '828', None, '835', '692', '686', '832', '645', '579', '252', '583', '696', '719', '752', '904', '921', '102', '408', None, '586', '323', '740', '854', '741', '474', '386', '736', '454', '879', '773', '757', '596', '782', '691', '511', '825', '447', '780', '429', '535', '658', '723', '745', '831', '893', '187', '64', '581', '742', None, '63', '618', '687', '787', None, '625', '693', '612', '763', '1', '768', '426', '765', '365', '688', None, '871', '204', '610', '807', '586', '682', '871', '859', '905', '749', '914', '590', None, '682', '777', '856', '581', '711', '811', '602', '900', '766', '79', '596', '406', '584', '831', '1', '585', '58', '585', '860', '604', '893', '577', '691', '348', '723', '864', '587'] ['R', 'W', 'V', 'W', 'K', 'S', 'Y', 'K', 'A', 'M', 'F', 'R', 'R', 'V', 'R', 'I', 'Q', 'R', 'R', 'R', 'T', 'L', 'T', 'H', 'Q', 'L', 'C', 'F', 'E', 'M', None, 'L', 'M', 'S', None, 'L', 'G', 'S', 'H', 'G', 'G', 'S', 'L', 'C', 'R', 'I', None, 'N', 'R', 'Q', 'R', 'R', 'V', 'R', 'E', 'R', 'L', 'A', 'A', None, 'P', 'R', 'M', 'C', 'M', 'V', 'L', 'R', 'S', None, 'D', 'L', 'Q', 'A', 'I', 'Q', 'S', 'C', 'L', 'F', 'R', 'R', 'I', 'Y', 'Y', 'L', 'Y', 'Q', 'Q', 'G', 'Y', 'C', 'C', 'D', 'E', 'D', 'L', 'N', 'W', 'P', 'R', 'P', 'M', 'D', 'A', 'Q', 'G', 'V', None, None, 'Q', 'K', 'V', 'I', 'P', 'E', 'Y', 'M', 'R', 'E', 'Y', 'Q', 'Q', 'N', 'Q', 'S', 'W', 'Y', 'E', 'R', 'I', 'M', 'E', 'W', 'P', 'W', 'A', None, 'H', None, 'D', 'W', 'E', 'K', 'Q', 'V', 'D', 'V', 'W', 'R', 'G', 'G', 'Y', 'M', 'Q', 'E', None, 'E', 'L', 'Q', 'Q', 'W', 'A', 'N', 'F', None, 'Y', 'N', 'V', 'R', 'E', 'S', 'E', 'F', 'D', 'W', 'W', 'V', '*', 'R', 'Y', None, 'R', 'E', 'Y', 'S', 'S', 'E', 'R', 'A', 'G', 'F', 'E', 'N', 'C', 'Y', 'D', 'R', 'Q', 'Y', 'R', 'A', 'Y', 'Q', 'L', 'L', 'L', 'P', 'E', 'Q', 'K', 'W', None, 'Q', 'R', 'C', 'R', None, 'M', 'N', 'C', 'L', 'M', 'D', 'S', 'F', 'Y', 'A', None, 'A', 'E', 'K', 'C', 'R', 'E', 'A', 'Q', 'P', 'A', 'P', 'G', None, 'E', 'H', 'R', 'K', 'R', 'L', 'C', 'I', 'A', 'Q', 'C', 'C', 'F', 'L', 'M', 'K', 'Q', 'K', 'L', 'I', 'P', 'C', 'D', 'Y', 'L', 'L', 'A'] ['C', '*', 'M', '*', '*', 'N', 'C', '*', 'T', 'V', 'L', 'H', 'Q', 'L', 'H', 'M', '*', 'K', 'H', 'C', 'A', 'P', 'S', 'Y', 'R', 'R', 'F', 'Y', 'K', 'I', None, '*', 'T', 'S', None, 'F', 'R', 'P', 'P', 'V', 'E', 'C', 'H', 'G', '*', 'T', None, 'H', 'L', '*', 'H', 'C', 'M', '*', '*', 'L', 'I', 'P', 'D', None, 'T', 'W', 'V', '*', 'K', 'L', 'H', 'C', 'Y', None, 'H', 'P', '*', 'T', 'F', '*', 'T', 'Y', 'P', 'L', '*', 'Q', 'T', '*', '*', 'F', '*', '*', '*', 'V', '*', 'Y', 'Y', 'G', 'K', 'N', 'F', 'S', 'R', 'L', 'Q', 'A', 'I', 'N', 'V', '*', 'W', 'I', None, None, '*', '*', 'M', 'T', 'L', '*', 'C', 'K', 'S', 'K', 'S', '*', '*', 'K', 'R', 'F', 'S', 'H', 'G', 'W', 'N', 'T', '*', 'L', 'S', 'S', 'P', None, 'L', None, 'V', '*', '*', 'T', '*', 'L', 'N', 'L', '*', '*', 'E', 'V', '*', 'L', '*', 'G', None, '*', 'I', '*', '*', 'R', 'V', 'K', 'L', None, '*', 'K', 'L', 'G', '*', 'R', '*', 'L', 'V', '*', '*', 'M', 'R', '*', '*', None, '*', '*', '*', '*', 'P', 'G', 'L', 'D', 'R', 'S', 'K', 'S', 'Y', 'D', 'G', '*', 'K', '*', 'P', 'D', '*', '*', 'F', 'F', 'F', 'S', '*', '*', 'N', '*', None, '*', 'W', 'R', 'Q', None, 'V', 'K', 'S', 'V', 'I', 'Y', '*', 'L', '*', 'V', None, 'G', '*', 'E', '*', 'K', 'D', 'E', '*', 'L', 'V', 'S', 'E', None, 'G', 'D', 'P', 'R', 'G', 'P', 'F', 'M', 'S', '*', 'R', '*', 'V', 'H', 'T', 'Q', '*', 'E', 'F', 'F', 'R', 'R', 'E', '*', 'S', 'R', 'D']

CASR NM_000388.4 ['795', '297', '185', '127', '227', '582', '681', '151', '118', '128', '191', '612', '773', '670', '39', '227', '138', '143', '62', '66', '788', '47', '616', '881', '648', None, '843', '185', '125', '820', '788', '604', '94', '465', '727', '180', '582', '553', '509', '559', '645', '69', '748', '812', '882', '127', '215', '221', '29', '828', '143', '680', '55', '788', '544', '25', '395', '817', '218', '584', '811', '886', '172', '610', '802', '871', '178', '680', '798', '95', '551', '193', '227', '217', '220', '220', '128', '245', '227', '392', '66', None, '168', '555', '818', None, '557', '56', '582', None, '661', '886', '218', '767', None, '127', '810', '844', '554', '839', '459', '509', '352', '361', '70', '681', '718', '173', None, '1', '530', '802', None, '670', '549', None, '832', '117', '128', '514', None, '670', '53', '719', '47', '167', '689', '64', '839', '572', None, '1', '69', '24', '1', '220', '245', '728', '352', '1', '613', None, None, '767', '675', '787', '147', '697', '173', '118', None, '133', '101', '657', None, '190', '228', '607', None, '293', '63', None, None, '368', '350', '571', '842', '636', '489', '53', '221', '326', '835', '744', '456', '581', '132', '671', '299', None, '562', None, None, '476', '608', '742', '388', '1', '787', '183', '140', '224', '296', '551', '309', '171', '164', '208', '20', '241', '742', '112', '829', '754', '802', '119', '174', '218', '812'] ['R', 'E', 'R', 'E', 'R', 'C', 'Q', 'T', 'N', 'F', 'E', 'F', 'L', 'G', 'P', 'R', 'T', 'G', 'R', 'R', 'F', 'K', 'L', 'F', 'R', None, 'A', 'R', 'L', 'S', 'F', 'E', 'G', 'R', 'L', 'F', 'C', 'G', 'G', 'P', 'A', 'R', 'P', 'L', 'K', 'E', 'D', 'P', 'K', 'T', 'G', 'R', 'P', 'F', 'R', 'R', 'C', 'V', 'Y', 'K', 'M', 'R', 'R', 'E', 'N', 'E', 'N', 'R', 'P', 'Y', 'R', 'Q', 'R', 'D', 'R', 'R', 'F', 'Q', 'R', 'R', 'R', None, 'A', 'I', 'W', None, 'G', 'E', 'C', None, 'C', 'R', 'Y', 'E', None, 'E', 'S', 'A', 'I', 'I', 'Q', 'G', 'W', 'Q', 'W', 'Q', 'W', 'L', None, 'M', 'W', 'N', None, 'G', 'G', None, 'F', 'Q', 'F', 'Y', None, 'G', 'S', 'W', 'K', 'Y', 'V', 'N', 'I', 'E', None, 'M', 'R', 'Q', 'M', 'R', 'Q', 'V', 'W', 'M', 'G', None, None, 'E', 'W', 'C', 'S', 'V', 'L', 'N', None, 'E', 'C', 'S', None, 'D', 'E', 'S', None, 'W', 'Y', None, None, 'L', 'E', 'G', 'L', 'K', 'Y', 'S', 'P', 'Q', 'A', 'Y', 'E', 'A', 'S', 'E', 'W', None, 'C', None, None, 'Q', 'W', 'W', 'S', 'M', 'C', 'F', 'A', 'E', 'S', 'R', 'Q', 'S', 'Q', 'W', 'Y', 'E', 'W', 'L', 'Y', 'Q', 'N', 'K', 'L', 'Y', 'L'] ['W', 'K', 'Q', 'A', 'L', 'Y', 'H', 'M', 'K', 'L', 'K', 'S', 'R', 'E', 'A', 'Q', 'M', 'E', 'M', 'C', 'C', 'N', 'V', 'L', '*', None, 'E', '*', 'P', 'F', 'L', 'K', '*', 'Q', 'Q', 'C', 'F', 'R', 'R', 'H', 'D', 'H', 'Q', 'P', '*', 'G', 'H', 'L', 'E', 'P', 'R', 'H', 'L', 'L', '*', '*', 'R', 'I', 'D', '*', 'V', 'P', 'G', '*', 'S', '*', 'D', 'C', 'L', 'C', 'K', '*', 'G', 'Y', 'W', 'Q', 'L', '*', '*', '*', 'H', None, 'V', 'T', '*', None, 'E', '*', 'S', None, '*', 'W', 'C', 'K', None, 'K', 'N', 'V', 'T', 'T', 'R', 'R', '*', '*', '*', 'R', '*', 'P', None, 'V', '*', 'H', None, 'R', 'R', None, 'S', '*', 'L', '*', None, 'R', 'P', '*', 'E', '*', 'M', 'D', 'N', '*', None, 'L', 'S', '*', 'R', 'P', 'R', 'F', 'G', 'T', 'E', None, None, 'Q', '*', 'Y', 'L', 'M', 'F', 'K', None, 'V', '*', 'Y', None, 'G', 'Q', '*', None, '*', '*', None, None, '*', '*', 'W', 'P', '*', 'H', '*', 'S', '*', 'D', '*', '*', 'V', '*', '*', '*', None, 'F', None, None, '*', '*', 'R', '*', 'I', 'F', 'L', 'V', '*', 'N', 'G', '*', 'R', '*', '*', '*', '*', '*', 'R', 'C', '*', 'I', 'R', 'R', 'S', 'R']
CBS NM_000071.3 ['307', '145', '114', '278', '144', '384', '539', '266', '444', None, '353', '191', '336', None, '379', '347', '257', '121', '116', '101', '125', '262', '121', '408', '379', '371', '351', '331', '323', None, '234', '176', '121', '109', '85', '54', '49', '125', None, '441', '336', '320', None, '301', '226', '148', None, None, '370', '272', None, '165', '259', None, '217', None, '288', None, '526', None, None, None, None, '228', None, None, None, None, '165', '176', None, '376', None, '384', '456', '409', '151', '52', '228', '228', '409', '143', '314', '404', '239', '213', '177', '144', '301', '336', None, '290', None, '466', '88', '290', '288', None, None, '158', None, None, '47', '52', '208', None, '114', '390', None, None, '65', '262', '359', '454', '338', '317', None, '515', '47', '148', None, '352', '128', '176', None, '256', '436', '230', None, '243', '305', None, '136', '486', None, None, '420', '440', '297', '232', None, None, '266', '346', '145', '88', '307', '262', '259', '152', '349', '336', '176', '349', '307', '158', '109', '528', None, '275', '65', '95', '371', '379', '121', '307', '226', '453', None, None, '278', None, None, None, None, '295', '410', None, '348', None, '355', None, None, '160', '279', '1', '242', '444', '153', '148', '349', '393', None, '518', '540', None, '283', '65'] ['G', 'P', 'A', 'I', 'E', 'K', 'L', 'R', 'D', None, 'T', 'T', 'R', None, 'R', 'G', 'T', 'R', 'G', 'L', 'R', 'T', 'R', 'W', 'R', 'V', 'G', 'A', 'W', None, 'D', 'E', 'R', 'C', 'G', 'W', 'P', 'R', None, 'K', 'R', 'V', None, 'Y', 'A', 'G', None, None, 'C', 'C', None, 'C', 'G', None, 'S', None, 'A', None, 'Q', None, None, None, None, 'N', None, None, None, None, 'C', 'E', None, 'D', None, 'K', 'L', 'W', 'G', 'C', 'N', 'N', 'W', 'I', 'V', 'E', 'E', 'E', 'K', 'E', 'Y', 'R', None, 'P', None, 'S', 'P', 'P', 'A', None, None, 'A', None, None, 'D', 'C', 'W', None, 'A', 'W', None, None, 'H', 'T', 'K', 'V', 'L', 'R', None, 'Q', 'D', 'G', None, 'S', 'E', 'E', None, 'G', 'E', 'L', None, 'Q', 'G', None, 'L', 'Q', None, None, 'S', 'E', 'E', 'H', None, None, 'R', 'C', 'P', 'P', 'G', 'T', 'G', 'I', 'S', 'R', 'E', 'S', 'G', 'A', 'C', 'Q', None, 'C', 'H', 'I', 'V', 'R', 'R', 'G', 'A', 'G', None, None, 'I', None, None, None, None, 'Q', 'W', None, 'G', None, 'A', None, None, 'V', 'G', 'M', 'Q', 'D', 'G', 'G', 'S', 'Q', None, 'Y', 'L', None, 'E', 'H'] ['S', 'L', 'V', 'T', 'K', 'E', 'S', 'K', 'N', None, 'M', 'M', 'C', None, 'Q', 'S', 'M', 'H', 'R', 'P', 'Q', 'M', 'L', '*', 'W', 'M', 'R', 'E', '*', None, 'N', '*', 'C', 'R', 'R', '*', 'L', 'W', None, '*', 'H', 'A', None, '*', 'T', 'R', None, None, 'Y', '*', None, 'Y', 'S', None, 'F', None, 'T', None, '*', None, None, None, None, 'S', None, None, None, None, 'G', 'K', None, 'N', None, 'N', 'P', '*', 'R', '*', 'K', 'K', '*', 'M', 'A', '*', '*', '*', '*', '*', '*', 'P', None, 'L', None, '*', 'S', 'Q', 'P', None, None, 'V', None, None, 'A', 'S', '*', None, 'S', '*', None, None, 'R', 'A', '*', 'E', 'P', 'G', None, '*', 'N', 'A', None, 'R', '*', 'D', None, 'V', '*', 'Q', None, '*', 'R', None, 'P', '*', None, None, '*', '*', '*', 'D', None, None, 'G', 'R', 'R', 'R', 'V', 'R', 'D', 'M', 'R', 'S', 'G', 'G', 'A', 'T', 'Y', '*', None, '*', 'L', 'N', 'L', 'G', 'G', 'D', 'S', 'R', None, None, 'S', None, None, None, None, '*', '*', None, 'S', None, 'P', None, None, 'M', 'V', 'I', '*', 'H', 'V', 'E', 'N', '*', None, '*', 'Q', None, '*', 'P']

### STEP 7 (Run 7A instead) 
#### Process each homologous alignment (/aln) and extract variable sites for each protein.

**Output:** '`variable`' dictionary with transcript IDs as keys and dictionaries of variable sites as values.

* Orig = position of aminoacid in reference protein sequence 	
* Aln = position of aminoacid after alignmemt (taking into considering gaps included)	
* Human = Aminoacid at position in human
* Others = variants observed at that position in other homologs

In [176]:
os.listdir('aln_match')

['ABCD1_NP_000024.2_match.aln',
 'ALPL_NP_000469.3_match.aln',
 'AR_NP_000035.2_match.aln',
 'ATP7B_NP_000044.2_match.aln',
 'BTK_NP_000052.1_match.aln',
 'CASR_NP_000379.3_match.aln',
 'CBS_NP_000062.1_match.aln',
 'CFTR_NP_000483.3_match.aln',
 'CYBB_NP_000388.2_match.aln',
 'F7_NP_000122.1_match.aln',
 'F7_NP_062562.1_match.aln',
 'F8_NP_000123.1_match.aln',
 'F9_NP_000124.1_match.aln',
 'G6PD_NP_000393.4_match.aln',
 'G6PD_NP_001035810.1_match.aln',
 'GALT_NP_000146.2_match.aln',
 'GBA1_NP_000148.2_match.aln',
 'GJB1_NP_000157.1_match.aln',
 'HBB_NP_000509.1_match.aln',
 'HPRT1_NP_000185.1_match.aln',
 'IL2RG_NP_000197.1_match.aln',
 'KCNH2_NP_000229.1_match.aln',
 'KCNQ1_NP_000209.2_match.aln',
 'L1CAM_NP_000416.1_match.aln',
 'LDLR_NP_000518.1_match.aln',
 'MPZ_NP_000521.2_match.aln',
 'MYH7_NP_000248.2_match.aln',
 'PAH_NP_000268.1_match.aln',
 'PMM2_NP_000294.1_match.aln',
 'RHO_NP_000530.1_match.aln',
 'TP53_NP_000537.3_match.aln',
 'TTR_NP_000362.1_match.aln',
 'TYR_NP_000363.1_match.aln',
 'VWF_NP_000543.3_match.aln']

In [70]:
run kondrashov

In [ ]:
len(fasta)

In [136]:
for gene in loci:
    protein = 'NP_000469.3'
    for filename in os.listdir("fasta_match"):
        if not filename.startswith(gene + "_"):
            continue
        filepath = os.path.join("fasta_match", filename)
        for record in SeqIO.parse(filepath, "fasta"):
            recordid = record.description.split(" ")[0]
            if recordid == protein:
                fasta = record
                #lenn = len(fasta)
                print(gene, filepath, recordid)

ALPL fasta_match\ALPL_NP_000469.3_match.fasta NP_000469.3

In [117]:
for gene in loci:
    protein = 'NP_000469.3'
    for filename in os.listdir("aln_match"):
        if not filename.startswith(gene + "_"):
            continue
        filepath = os.path.join("aln_match", filename)
        align = AlignIO.read(filepath, "fasta")
        for record in align:
            if record.id == protein:
                aln = record
                print(gene, filepath, record.id)

ALPL aln_match\ALPL_NP_000469.3_match.aln NP_000469.3

In [119]:
protein = 'NP_000469.3'
gene = 'ALPL'

for filename in os.listdir("fasta_match"):
    if not filename.startswith(gene + "_"):
        continue
    filepath = os.path.join("fasta_match", filename)
    for record in SeqIO.parse(filepath, "fasta"):
        recordid = record.description.split(" ")[0]
        if recordid == protein:
            fasta = record
            break

for filename in os.listdir("aln_match"):
    if not filename.startswith(gene + "_"):
        continue
    filepath = os.path.join("aln_match", filename)
    align = AlignIO.read(filepath, "fasta")
    for record in align:
        if record.id == protein:
            aln = record
            break
i = 0
j = 0
L = len(fasta)
alni = []
while i < L:
    if aln.seq[j] != "-":
        alni.append(j)
        i += 1
        j += 1
    else:
        j += 1
print(gene, filepath, L, i, j)

ALPL aln_match\ALPL_NP_000469.3_match.aln 524 524 601

In [120]:
print(gene, filepath, L, i, j)
print(len(fasta))

import pandas as pd
for i in range(L):
    j = alni[i]
    counts = pd.Series(list(align[:, j])).value_counts()
    alleles = counts.index.tolist()
    remove_element(alleles, "-")
    n = len(alleles)
    remove_element(alleles, fasta[i])
    if n > 1:
        variable.update({i + 1: alleles})
        #if verbose:
        print(i + 1, j + 1, fasta[i], alleles, sep="\t")

ALPL aln_match\ALPL_NP_000469.3_match.aln 524 524 601
524
2	10	I	['P']
3	11	S	['W', 'M']
4	12	P	['A', 'S']
5	13	F	['A']
6	14	L	['A', 'V']
7	15	V	['L', 'I', 'S']
9	17	A	['V', 'G']
10	37	I	['V', 'M']
11	38	G	['S', 'K']
12	39	T	['S', 'D']
13	40	C	['E']
15	42	T	['A', 'M', 'S']
16	43	N	['S', 'H', 'D']
17	44	S	['C', 'E']
18	45	L	['F', 'K']
19	46	V	['G']
20	47	P	['K']
21	48	E	['G']
22	49	K	['M', 'R']
23	50	E	['L', 'S']
24	51	K	['G', 'S']
25	52	D	['T']
26	53	P	['T']
27	54	K	['E', 'G', 'T']
28	55	Y	['S', 'T', 'W']
29	56	W	['L']
30	57	R	['E', 'S']
31	58	D	['N', 'R', 'G']
32	59	Q	['R']
33	60	A	['R']
34	61	Q	['A']
35	62	E	['Q', 'K']
36	63	T	['V']
38	69	K	['R']
39	70	Y	['H', 'N']
40	71	A	['C']
42	73	E	['G', 'K']
43	74	L	['M']
44	75	Q	['S']
45	76	K	['E', 'R']
46	77	L	['I']
47	78	N	['D']
48	79	T	['A']
49	92	N	['G']
50	93	V	['A']
51	94	A	['V']
52	95	K	['R']
53	96	N	['D']
54	97	V	['P']
55	98	I	['H']
56	99	M	['S']
58	101	L	['K']
59	102	G	['K']
60	106	D	['S']
61	107	G	['P']
62	108	M	['F']
63	109	G	['S']
64	110	V	['R']
65	111	S	['T']
66	112	T	['P']
67	113	V	['L']
68	114	T	['L']
69	115	A	['P']
70	116	A	['T', 'S']
71	117	R	['L']
72	118	I	['A']
74	120	K	['M', 'T']
76	122	Q	['S']
77	123	L	['C']
78	124	H	['S', 'R']
79	125	H	['P', 'N']
80	126	N	['R']
81	127	P	['T']
82	128	G	['R']
85	138	T	['P']
86	139	R	['K', 'M', 'H']
87	140	L	['S']
88	141	E	['S']
89	142	M	['A']
90	143	D	['G']
91	144	K	['H']
92	145	F	['M']
93	155	P	['T', 'S']
94	156	F	['L', 'S']
95	157	V	['L', 'C', 'M']
96	158	A	['S']
97	159	L	['H', 'W']
98	160	S	['L', 'E']
99	161	K	['Q', 'M']
137	199	S	['T']
138	200	R	['Q']
152	214	R	['H']
209	271	M	['V']
213	275	R	['K']
214	276	D	['N']
216	278	D	['E']
231	293	K	['R']
238	300	S	['I', 'M', 'T']
251	313	D	['N']
253	315	V	['I']
254	316	D	['N']
255	317	T	['I', 'V']
258	320	S	['N']
262	324	R	['K', 'T']
263	325	Y	['H', 'R', 'N', 'D']
266	343	S	['T']
269	346	I	['V']
273	350	T	['S']
276	353	L	['M']
277	354	T	['A', 'K', 'N']
279	356	D	['N']
280	357	P	['L']
281	358	H	['Y', 'N', 'S']
282	359	N	['T', 'A']
295	372	M	['L']
296	373	Q	['E']
304	381	V	['L', 'M']
310	387	S	['T']
314	391	V	['T', 'E', 'K', 'G']
318	395	Q	['R']
319	396	I	['V']
321	398	R	['Q', 'K']
325	402	K	['R']
357	434	R	['Q']
360	437	G	['E']
361	438	Q	['L', 'R']
363	440	G	['D']
364	441	S	['N', 'I', 'D', 'T']
365	442	L	['M', 'I']
368	445	S	['L', 'T']
369	446	E	['Q', 'G']
402	479	L	['V']
425	502	G	['D']
433	510	M	['T']
438	515	H	['N']
451	528	H	['Y']
463	540	S	['A']
480	557	V	['I']
488	565	A	['S']
490	567	I	['V']
494	571	L	['V']
495	572	G	['D', 'N']
498	575	A	['T']
499	576	P	['H', 'Q', 'S', 'R']
502	579	S	['A', 'P']
504	581	G	['R', 'S']
505	582	S	['G', 'N']
506	583	L	['P']
508	585	A	['P', 'L']
509	586	G	['V']
510	587	P	['A']
514	591	A	['P', 'L', 'S']
518	595	Y	['F', 'L']
519	596	P	['S']
520	597	L	['M']
521	598	S	['R', 'G']
522	599	V	['I', 'S', 'H', 'M']

In [72]:
run kondrashov

In [74]:
alni = get_aln_positions('ABCA12', 'NP_775099.2')
alni

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

### STEP 7A
##### I'll try modifyng 'get_variables_sites' to fit genes with multiple reference proteins

In [78]:
for gene in lociii:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        protein = translation[transcript]
    print(gene, transcript, protein)

ABCA12 NM_173076.3 NP_775099.2
ABCD1 NM_000033.4 NP_000024.2
ACAD9 NM_014049.5 NP_054768.2
ACADM NM_000016.6 NP_000007.1
ACADVL NM_000018.4 NP_000009.1
ACAT1 NM_000019.4 NP_000010.1
ADA NM_000022.4 NP_000013.2
AGL NM_000642.3 NP_000019.2
AGXT NM_000030.3 NP_000021.1
AHI1 NM_001134831.2 NP_001128302.1
AIRE NM_000383.4 NP_000374.1
ALMS1 NM_001378454.1 NP_001365383.1
ALOX12B NM_001139.3 NP_001130.1
ALPL NM_000478.6 NP_000469.3
ANK1 NM_000037.4 NP_000028.3
ANO5 NM_213599.3 NP_998764.1
APC NM_000038.6 NP_000029.2
AR NM_000044.6 NP_000035.2
ARSA NM_000487.6 NP_000478.3
ARSB NM_000046.5 NP_000037.2
ASL NM_000048.4 NP_000039.2
ASPA NM_000049.4 NP_000040.1
ASPM NM_018136.5 NP_060606.3
ATM NM_000051.4 NP_000042.3
ATP7B NM_000053.4 NP_000044.2
BBS2 NM_031885.5 NP_001364385.1
BCKDHA NM_000709.4 NP_000700.1
BEST1 NM_004183.4 NP_004174.1
BLM NM_000057.4 NP_000048.1
BRIP1 NM_032043.3 NP_114432.2
BTD NM_001370658.1 NP_001268652.2
BTK NM_000061.3 NP_000052.1
CASR NM_000388.4 NP_000379.3
CBS NM_000071.3 NP_000062.1
CC2D2A NM_001378615.1 NP_001073991.2
CDH23 NM_022124.6 NP_071407.4
CEP290 NM_025114.4 NP_079390.3
CERKL NM_201548.5 NP_963842.1
CFTR NM_000492.3 NP_000483.3
CHD7 NM_017780.4 NP_060250.2
CHEK2 NM_007194.4 NP_009125.1
CLN3 NM_001042432.2 NP_000077.1
CNGB3 NM_019098.5 NP_061971.3
CPS1 NM_001875.5 NP_001866.2
CRB1 NM_201253.3 NP_957705.1
CTNS NM_004937.3 NP_004928.2
CYBB NM_000397.4 NP_000388.2
CYP11B1 NM_000497.4 NP_000488.3
CYP17A1 NM_000102.4 NP_000093.1
CYP27A1 NM_000784.4 NP_000775.1
DCLRE1C NM_001033855.3 NP_001029027.1
DICER1 NM_177438.3 NP_001258211.1
DUOX2 NM_001363711.2 NP_001350640.1
EHMT1 NM_024757.5 NP_079033.4
ELP1 NM_003640.5 NP_003631.2
ERCC6 NM_001277058.2 NP_001263987.1
EVC NM_153717.3 NP_714928.1
EVC2 NM_147127.5 NP_667338.3
EXT1 NM_000127.3 NP_000118.2
EXT2 NM_207122.2 NP_001376557.1
EYS NM_001142800.2 NP_001136272.1
F7 NM_000131.4 NP_000122.1
F8 NM_000132.4 NP_000123.1
F9 NM_000133.4 NP_000124.1
FANCA NM_000135.4 NP_000126.2
FANCI NM_001113378.2 NP_001106849.1
FBN2 NM_001999.4 NP_001990.2
FKRP NM_024301.5 NP_001034974.1
FLCN NM_144997.7 NP_001340159.1
FRAS1 NM_025074.7 NP_079350.5
G6PD NM_001042351.3 NP_001035810.1
GAA NM_000152.5 NP_000143.2
GALC NM_000153.4 NP_000144.2
GALNS NM_000512.5 NP_000503.1
GALT NM_000155.4 NP_000146.2
GBA1 NM_000157.4 NP_000148.2
GBE1 NM_000158.4 NP_000149.4
GCDH NM_000159.4 NP_000150.1
GJB1 NM_001097642.3 NP_000157.1
GLB1 NM_000404.4 NP_000395.3
GNE NM_005476.7 NP_005467.1
GNPTAB NM_024312.5 NP_077288.2
HBB NM_000518.5 NP_000509.1
HEXA NM_000520.6 NP_000511.2
HEXB NM_000521.4 NP_000512.2
HGD NM_000187.4 NP_000178.2
HGSNAT NM_152419.3 NP_689632.2
HMBS NM_000190.4 NP_000181.2
HPRT1 NM_000194.2 NP_000185.1
HPS3 NM_032383.5 NP_115759.2
IL2RG NM_000206.3 NP_000197.1
ITGA2B NM_000419.5 NP_000410.2
IVD NM_002225.5 NP_002216.3
KCNH2 NM_000238.4 NP_000229.1
KCNQ1 NM_000218.3 NP_000209.2
KRIT1 NM_194454.3 NP_001337601.1
L1CAM NM_001278116.2 NP_000416.1
LDLR NM_000527.4 NP_000518.1
LIPA NM_000235.4 NP_000226.2
LOXHD1 NM_001384474.1 NP_001371403.1
LPL NM_000237.3 NP_000228.1
LRPPRC NM_133259.4 NP_573566.2
LYST NM_000081.4 NP_000072.2
MAN2B1 NM_000528.4 NP_000519.2
MCCC1 NM_020166.5 NP_064551.3
MCCC2 NM_022132.5 NP_071415.1
MED13L NM_015335.5 NP_056150.1
MFN2 NM_014874.4 NP_001121132.1
MKS1 NM_017777.4 NP_060247.2
MMUT NM_000255.4 NP_000246.2
MPZ NM_000530.8 NP_000521.2
MSH2 NM_000251.3 NP_000242.1
MTHFR NM_005957.5 NP_005948.3
MUTYH NM_001048174.2 NP_001041636.2
MYH7 NM_000257.4 NP_000248.2
NAGLU NM_000263.4 NP_000254.2
NF1 NM_001042492.3 NP_001035957.1
NF2 NM_000268.4 NP_000259.1
NIPBL NM_133433.4 NP_597677.2
NPC1 NM_000271.5 NP_000262.2
NSD1 NM_022455.5 NP_001396230.1
OCA2 NM_000275.3 NP_000266.2
OPA1 NM_130837.3 NP_570850.2
PAH NM_000277.3 NP_000268.1
PALB2 NM_024675.4 NP_078951.2
PAX3 NM_181458.4 NP_852123.1
PAX6 NM_000280.6 NP_000271.1
PCDH15 NM_001384140.1 NP_001371069.1
PCNT NM_006031.6 NP_006022.3
PKHD1 NM_138694.4 NP_619639.3
PMM2 NM_000303.3 NP_000294.1
POMGNT1 NM_017739.4 NP_001424582.1
PRPF31 NM_015629.4 NP_056444.3
PYGM NM_005609.4 NP_005600.1
RAD50 NM_005732.4 NP_005723.2
RARS2 NM_020320.5 NP_064716.2
RECQL4 NM_004260.4 NP_004251.4
RHO NM_000539.3 NP_000530.1
RP1 NM_006269.2 NP_006260.1
RPGRIP1L NM_015272.5 NP_056087.2
SACS NM_014363.6 NP_055178.3
SATB2 NM_001172517.1 NP_001165980.1
SCN4A NM_000334.4 NP_000325.4
SERPING1 NM_000062.3 NP_000053.2
SGSH NM_000199.5 NP_000190.1
SI NM_001041.4 NP_001032.2
SLC12A6 NM_001365088.1 NP_001352017.1
SLC25A13 NM_014251.3 NP_055066.1
SLC26A4 NM_000441.2 NP_000432.1
SMPD1 NM_000543.5 NP_000534.3
SPAST NM_014946.4 NP_055761.2
SPG11 NM_025137.4 NP_079413.3
SYNE1 NM_001347702.2 NP_001334631.1
TCIRG1 NM_006019.4 NP_001427481.1
TMC1 NM_138691.3 NP_619636.2
TMEM67 NM_153704.6 NP_714915.3
TP53 NM_000546.6 NP_000537.3
TPP1 NM_000391.4 NP_000382.3
TSC1 NM_000368.5 NP_000359.1
TTR NM_000371.4 NP_000362.1
TYR NM_000372.5 NP_000363.1
UNC13D NM_199242.3 NP_954712.1
USH1C NM_005709.4 NP_005700.2
USH2A NM_206933.4 NP_996816.3
VHL NM_000551.4 NP_000542.1
VPS13A NM_033305.3 NP_150648.2
VPS13B NM_017890.5 NP_060360.3
VWF NM_000552.5 NP_000543.3
WFS1 NM_006005.3 NP_001139325.1
WRN NM_000553.6 NP_000544.2
WT1 NM_024426.6 NP_077744.4
XPC NM_004628.5 NP_004619.3
ZEB2 NM_014795.4 NP_055610.1
ZFYVE26 NM_015346.4 NP_056161.2

In [87]:
import os
from Bio import AlignIO

variable = {}
for gene in lociii:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        protein = translation[transcript]

    fasta_file = os.path.join("fasta_lociii_match", f"{gene}_{protein}_match.fasta")
    aln_file = os.path.join("aln_lociii_match", f"{gene}_{protein}_match.aln")

    print(protein, fasta_file, aln_file)

    fasta = None
    for record in SeqIO.parse(fasta_file, "fasta"):
        recordid = record.description.split()[0]
        if recordid == protein:
            fasta = record
            break
    if fasta is None:
        raise ValueError(f"{protein} not found in {fasta_file}")    
    #print(fasta)

    align = AlignIO.read(aln_file, "fasta")
    aln = None
    for record in align:
        if record.id == protein:
            aln = record
            break
    if aln is None:
        raise ValueError(f"{protein} not found in {aln_file}")
    #print(aln)
    print("gene\tHum\tAln\tsite\tvariable_amino_acids")
    
    alni = get_aln_positions(gene, protein)
    L = len(fasta)
    for i in range(L):
        j = alni[i]
        counts = pd.Series(list(align[:, j])).value_counts()
        alleles = counts.index.tolist()
        remove_element(alleles, "-")
        n = len(alleles)
        remove_element(alleles, fasta[i])
        if n > 1:
            variable.update({i + 1: alleles})
            #if verbose:
            print(gene, i + 1, j + 1, fasta[i], alleles, sep="\t")

NP_775099.2 fasta_lociii_match/ABCA12_NP_775099.2_match.fasta aln_lociii_match/ABCA12_NP_775099.2_match.aln
gene	Hum	Aln	site	variable_amino_acids
ABCA12	2	2	A	['V']
ABCA12	4	4	L	['Q']
ABCA12	5	5	F	['C']
ABCA12	9	9	Q	['R']
ABCA12	18	18	G	['M']
ABCA12	19	19	V	['L']
ABCA12	21	21	R	['S']
ABCA12	22	22	Q	['H']
ABCA12	25	25	W	['F']
ABCA12	28	28	V	['F']
ABCA12	29	29	L	['V']
ABCA12	30	30	I	['V']
ABCA12	31	31	L	['F']
ABCA12	92	92	L	['M']
ABCA12	98	98	I	['F', 'M']
ABCA12	99	99	D	['S', 'H']
ABCA12	100	100	D	['A', 'Y']
ABCA12	101	101	A	['T', 'S']
ABCA12	104	104	K	['N', 'D']
ABCA12	105	105	D	['N']
ABCA12	108	108	I	['L', 'M']
ABCA12	113	113	S	['P']
ABCA12	116	116	D	['E']
ABCA12	119	119	S	['G']
ABCA12	120	120	S	['N']
ABCA12	123	123	F	['L', 'P']
ABCA12	124	124	Q	['R']
ABCA12	128	128	V	['A']
ABCA12	131	131	R	['G']
ABCA12	132	132	R	['K']
ABCA12	137	137	A	['V']
ABCA12	138	138	T	['M', 'A']
ABCA12	139	139	V	['I']
ABCA12	144	144	S	['R', 'N']
ABCA12	145	145	S	['P']
ABCA12	147	147	L	['W', 'F']
ABCA12	149	149	I	['S']
ABCA12	150	150	P	['I', 'N', 'T', 'H']
ABCA12	151	151	G	['R', 'E']
ABCA12	152	152	T	['R', 'S']
ABCA12	153	153	Y	['D']
ABCA12	154	154	T	['I', 'A']
ABCA12	158	158	S	['T']
ABCA12	162	162	A	['T']
ABCA12	163	163	R	['Q', 'H']
ABCA12	167	167	L	['S']
ABCA12	169	169	K	['E']
ABCA12	172	172	K	['E']
ABCA12	173	173	Q	['K']
ABCA12	178	178	E	['D']
ABCA12	180	180	I	['T']
ABCA12	182	182	R	['K']
ABCA12	186	186	D	['E', 'A']
ABCA12	187	187	S	['T', 'R', 'I']
ABCA12	188	188	Y	['H']
ABCA12	189	189	S	['P']
ABCA12	190	190	G	['E', 'V']
ABCA12	192	192	I	['V', 'T', 'A']
ABCA12	193	193	V	['A', 'E']
ABCA12	195	195	D	['Y', 'N']
ABCA12	201	201	F	['T', 'L']
ABCA12	204	204	R	['K']
ABCA12	206	206	V	['I']
ABCA12	207	207	F	['L']
ABCA12	208	208	N	['T']
ABCA12	209	209	K	['E', 'Q']
ABCA12	212	212	L	['F']
ABCA12	215	215	M	['K']
ABCA12	225	225	L	['I']
ABCA12	226	226	N	['K']
ABCA12	227	227	K	['R']
ABCA12	229	229	F	['Y']
ABCA12	230	230	S	['C', 'F']
ABCA12	231	231	Q	['R', 'K']
ABCA12	232	232	L	['I', 'H']
ABCA12	233	233	S	['A']
ABCA12	234	234	S	['G', 'I']
ABCA12	235	235	D	['N']
ABCA12	236	236	P	['E']
ABCA12	237	237	N	['G', 'Q']
ABCA12	238	238	N	['Q']
ABCA12	239	239	Q	['K']
ABCA12	240	240	K	['E']
ABCA12	241	241	I	['V']
ABCA12	242	242	V	['A']
ABCA12	245	245	E	['D']
ABCA12	246	246	I	['M', 'L']
ABCA12	247	247	V	['G', 'I']
ABCA12	248	248	R	['S', 'G']
ABCA12	249	249	M	['V', 'A', 'L']
ABCA12	250	250	L	['I']
ABCA12	251	251	S	['P']
ABCA12	252	252	F	['Y']
ABCA12	253	253	F	['V']
ABCA12	254	254	S	['G']
ABCA12	255	255	Q	['P', 'E']
ABCA12	260	260	K	['T', 'R']
ABCA12	261	261	A	['V']
ABCA12	262	262	V	['L']
ABCA12	264	264	Q	['H']
ABCA12	265	265	L	['F']
ABCA12	271	271	N	['D']
ABCA12	273	273	F	['L']
ABCA12	276	276	D	['N']
ABCA12	277	277	T	['V']
ABCA12	280	280	S	['R']
ABCA12	281	281	N	['S', 'H']
ABCA12	282	282	L	['I']
ABCA12	287	287	R	['Q']
ABCA12	288	288	K	['H']
ABCA12	289	289	A	['F']
ABCA12	290	290	N	['T']
ABCA12	291	291	S	['G', 'R']
ABCA12	292	292	V	['A']
ABCA12	294	294	L	['M']
ABCA12	295	295	V	['A', 'I']
ABCA12	296	296	V	['I']
ABCA12	300	300	Y	['N']
ABCA12	302	302	R	['H']
ABCA12	303	303	F	['V']
ABCA12	304	304	A	['T']
ABCA12	305	305	T	['S']
ABCA12	312	312	L	['F']
ABCA12	313	313	Q	['R']
ABCA12	321	321	Y	['N']
ABCA12	327	327	A	['D']
ABCA12	328	328	Q	['P']
ABCA12	330	330	D	['N']
ABCA12	332	332	D	['G', 'N', 'E']
ABCA12	334	334	I	['T', 'V']
ABCA12	335	335	T	['S']
ABCA12	336	336	H	['Q']
ABCA12	337	337	V	['M', 'A']
ABCA12	339	339	N	['S', 'M', 'K']
ABCA12	340	340	E	['K']
ABCA12	342	342	D	['V']
ABCA12	343	343	G	['E']
ABCA12	345	345	T	['I', 'M', 'R']
ABCA12	349	349	S	['G']
ABCA12	353	353	A	['T']
ABCA12	365	365	L	['V']
ABCA12	368	368	I	['V']
ABCA12	375	375	I	['V', 'T']
ABCA12	378	378	L	['M']
ABCA12	379	379	A	['V']
ABCA12	384	384	V	['M']
ABCA12	386	386	D	['G', 'Y']
ABCA12	387	387	S	['N', 'D', 'H', 'T']
ABCA12	390	390	R	['T']
ABCA12	391	391	G	['S']
ABCA12	393	393	P	['Q', 'S']
ABCA12	396	396	L	['I']
ABCA12	400	400	Q	['K', 'W']
ABCA12	404	404	R	['Q']
ABCA12	405	405	F	['L']
ABCA12	406	406	K	['R']
ABCA12	409	409	F	['L']
ABCA12	411	411	R	['Q']
ABCA12	412	412	N	['S']
ABCA12	413	413	G	['D']
ABCA12	415	415	Y	['C']
ABCA12	416	416	E	['K']
ABCA12	418	418	Y	['H']
ABCA12	419	419	F	['I']
ABCA12	421	421	P	['S']
ABCA12	423	423	P	['A']
ABCA12	424	424	E	['K']
ABCA12	425	425	V	['I']
ABCA12	428	428	S	['A']
ABCA12	431	431	S	['A']
ABCA12	432	432	Q	['H']
ABCA12	438	438	E	['K']
ABCA12	442	442	E	['K']
ABCA12	446	446	F	['S', 'Y']
ABCA12	447	447	S	['N', 'H', 'T']
ABCA12	448	448	L	['V', 'W']
ABCA12	449	449	I	['M', 'V']
ABCA12	452	452	S	['T']
ABCA12	454	454	Q	['H']
ABCA12	455	455	L	['F']
ABCA12	456	456	S	['T']
ABCA12	457	457	D	['N', 'A', 'T']
ABCA12	458	458	M	['L', 'I', 'T']
ABCA12	460	460	F	['Y']
ABCA12	461	461	G	['R', 'E', 'K']
ABCA12	462	462	S	['R']
ABCA12	463	463	L	['I']
ABCA12	464	464	C	['M']
ABCA12	465	465	E	['G', 'K']
ABCA12	466	466	E	['D', 'N', 'V']
ABCA12	467	467	S	['G', 'Q']
ABCA12	468	468	E	['A', 'M']
ABCA12	470	470	D	['R']
ABCA12	472	472	Q	['R']
ABCA12	473	473	L	['F', 'M']
ABCA12	475	475	E	['P']
ABCA12	476	476	A	['L']
ABCA12	477	477	A	['P']
ABCA12	478	478	E	['D']
ABCA12	481	481	T	['S', 'A']
ABCA12	482	482	E	['G']
ABCA12	483	483	I	['M']
ABCA12	484	484	A	['V', 'T']
ABCA12	485	485	A	['T', 'G']
ABCA12	487	487	L	['F']
ABCA12	493	493	V	['L', 'A']
ABCA12	494	494	I	['M', 'V']
ABCA12	496	496	K	['E', 'T']
ABCA12	498	498	V	['L']
ABCA12	499	499	R	['T']
ABCA12	502	502	L	['M']
ABCA12	505	505	D	['N']
ABCA12	507	507	S	['A']
ABCA12	513	513	M	['L', 'V']
ABCA12	515	515	Q	['W', 'R']
ABCA12	520	520	A	['T']
ABCA12	523	523	M	['L']
ABCA12	524	524	N	['K']
ABCA12	525	525	Y	['A']
ABCA12	526	526	L	['M']
ABCA12	531	531	Q	['L']
ABCA12	534	534	P	['L']
ABCA12	535	535	I	['T', 'M']
ABCA12	536	536	I	['V']
ABCA12	538	538	A	['V']
ABCA12	539	539	M	['I']
ABCA12	544	544	N	['S', 'K']
ABCA12	546	546	A	['E']
ABCA12	547	547	D	['N']
ABCA12	548	548	A	['T']
ABCA12	549	549	S	['T']
ABCA12	550	550	E	['A']
ABCA12	551	551	K	['F']
ABCA12	552	552	P	['Q']
ABCA12	553	553	G	['S']
ABCA12	556	556	L	['I', 'T']
ABCA12	558	558	M	['L']
ABCA12	563	563	E	['D']
ABCA12	564	564	E	['Q']
ABCA12	567	567	E	['G', 'A', 'D', 'K']
ABCA12	568	568	D	['E', 'A']
ABCA12	572	572	T	['M', 'S', 'A']
ABCA12	573	573	T	['A']
ABCA12	574	574	G	['A']
ABCA12	577	577	N	['D', 'T']
ABCA12	578	578	R	['S', 'N']
ABCA12	579	579	T	['S']
ABCA12	581	581	D	['N']
ABCA12	582	582	K	['E']
ABCA12	586	586	I	['V', 'L']
ABCA12	594	594	E	['K']
ABCA12	596	596	I	['V']
ABCA12	598	598	Q	['R']
ABCA12	602	602	L	['M']
ABCA12	607	607	T	['A', 'G', 'I', 'V']
ABCA12	609	609	I	['V', 'A']
ABCA12	611	611	T	['N']
ABCA12	612	612	P	['L']
ABCA12	613	613	K	['E']
ABCA12	618	618	M	['V', 'L']
ABCA12	623	623	N	['S', 'K']
ABCA12	625	625	S	['P']
ABCA12	626	626	L	['F']
ABCA12	627	627	S	['P', 'L', 'A']
ABCA12	631	631	R	['W', 'H', 'Q']
ABCA12	637	637	G	['A']
ABCA12	640	640	L	['F']
ABCA12	642	642	H	['R']
ABCA12	645	645	N	['D']
ABCA12	646	646	I	['V']
ABCA12	650	650	T	['I']
ABCA12	659	659	D	['H']
ABCA12	665	665	K	['R']
ABCA12	667	667	M	['I']
ABCA12	671	671	I	['M', 'T']
ABCA12	674	674	K	['R']
ABCA12	675	675	E	['Q']
ABCA12	678	678	N	['S']
ABCA12	683	683	G	['S']
ABCA12	684	684	T	['A']
ABCA12	685	685	H	['Q']
ABCA12	695	695	K	['R']
ABCA12	697	697	M	['L', 'R']
ABCA12	698	698	H	['Q']
ABCA12	699	699	L	['V']
ABCA12	700	700	P	['S']
ABCA12	702	702	S	['N']
ABCA12	708	708	A	['V']
ABCA12	710	710	Y	['S']
ABCA12	712	712	S	['N', 'G']
ABCA12	713	713	N	['K', 'D']
ABCA12	714	714	R	['Q']
ABCA12	715	715	M	['I']
ABCA12	716	716	N	['S', 'D']
ABCA12	718	718	P	['T']
ABCA12	723	723	S	['R']
ABCA12	740	740	T	['I']
ABCA12	741	741	A	['S']
ABCA12	748	748	R	['K']
ABCA12	755	755	K	['R']
ABCA12	761	761	K	['N']
ABCA12	763	763	T	['S']
ABCA12	765	765	E	['K', 'Q']
ABCA12	768	768	A	['S']
ABCA12	769	769	S	['A']
ABCA12	775	775	I	['L', 'M']
ABCA12	776	776	N	['K', 'H', 'D', 'Q']
ABCA12	777	777	S	['T']
ABCA12	778	778	T	['S']
ABCA12	779	779	P	['S', 'E']
ABCA12	780	780	F	['Y']
ABCA12	781	781	C	['T']
ABCA12	782	782	F	['L']
ABCA12	783	783	S	['M']
ABCA12	784	784	L	['M']
ABCA12	785	785	Y	['I']
ABCA12	788	788	I	['V']
ABCA12	789	789	I	['L']
ABCA12	808	808	R	['K']
ABCA12	817	817	V	['A']
ABCA12	818	818	T	['N']
ABCA12	820	820	A	['N']
ABCA12	822	822	M	['V']
ABCA12	823	823	E	['Y']
ABCA12	824	824	K	['S']
ABCA12	827	827	V	['I']
ABCA12	838	838	K	['R']
ABCA12	862	862	M	['V']
ABCA12	876	876	V	['I']
ABCA12	896	896	I	['A']
ABCA12	899	899	L	['M', 'T']
ABCA12	900	900	K	['T', 'R']
ABCA12	931	931	Q	['K']
ABCA12	932	932	A	['G']
ABCA12	933	933	A	['S']
ABCA12	934	934	K	['E']
ABCA12	936	936	I	['V']
ABCA12	937	937	D	['E', 'G']
ABCA12	938	938	E	['D']
ABCA12	941	941	R	['K']
ABCA12	942	942	E	['Q']
ABCA12	944	944	K	['N']
ABCA12	947	947	Y	['N']
ABCA12	949	949	S	['R', 'T']
ABCA12	959	959	K	['T', 'N']
ABCA12	960	960	L	['V']
ABCA12	963	963	N	['H']
ABCA12	966	966	W	['R', 'Q']
ABCA12	968	968	R	['G', 'K']
ABCA12	971	971	D	['G']
ABCA12	973	973	G	['E', 'Q']
ABCA12	974	974	N	['H']
ABCA12	975	975	V	['I']
ABCA12	976	976	F	['L']
ABCA12	981	981	I	['V']
ABCA12	982	982	K	['R']
ABCA12	998	998	L	['I']
ABCA12	1000	1000	T	['S', 'A']
ABCA12	1013	1013	H	['N']
ABCA12	1033	1033	I	['V']
ABCA12	1044	1044	I	['T']
ABCA12	1061	1061	F	['Y']
ABCA12	1079	1079	V	['I']
ABCA12	1108	1108	C	['S']
ABCA12	1124	1124	V	['I']
ABCA12	1127	1127	V	['A', 'M']
ABCA12	1135	1135	F	['L']
ABCA12	1156	1156	F	['L']
ABCA12	1201	1201	S	['N']
ABCA12	1204	1204	L	['V', 'I']
ABCA12	1208	1208	M	['V']
ABCA12	1223	1223	I	['V']
ABCA12	1225	1225	R	['Q']
ABCA12	1236	1236	E	['D']
ABCA12	1240	1240	T	['S']
ABCA12	1243	1243	V	['I']
ABCA12	1244	1244	Q	['E']
ABCA12	1256	1256	L	['F']
ABCA12	1262	1262	F	['C']
ABCA12	1267	1267	I	['V']
ABCA12	1271	1271	V	['I']
ABCA12	1289	1289	I	['V']
ABCA12	1291	1291	P	['L']
ABCA12	1301	1301	A	['S']
ABCA12	1303	1303	V	['E']
ABCA12	1304	1304	K	['N']
ABCA12	1305	1305	P	['R']
ABCA12	1306	1306	E	['Q']
ABCA12	1309	1309	N	['S']
ABCA12	1312	1312	M	['V']
ABCA12	1320	1320	N	['S']
ABCA12	1325	1325	A	['T']
ABCA12	1326	1326	S	['R']
ABCA12	1327	1330	P	['L', 'F']
ABCA12	1328	1331	E	['D']
ABCA12	1329	1332	Y	['H']
ABCA12	1330	1333	M	['T', 'V', 'I']
ABCA12	1331	1334	F	['V', 'I']
ABCA12	1332	1335	S	['P']
ABCA12	1335	1338	I	['V']
ABCA12	1354	1357	I	['F', 'M', 'T']
ABCA12	1356	1359	G	['S']
ABCA12	1397	1400	A	['T']
ABCA12	1398	1401	S	['T']
ABCA12	1413	1416	L	['P']
ABCA12	1414	1417	H	['N', 'D']
ABCA12	1415	1418	T	['I', 'M']
ABCA12	1419	1422	N	['S']
ABCA12	1445	1448	I	['V']
ABCA12	1449	1452	H	['Q']
ABCA12	1452	1455	K	['R']
ABCA12	1498	1501	R	['G']
ABCA12	1522	1525	S	['C']
ABCA12	1530	1533	I	['M']
ABCA12	1552	1555	Q	['H']
ABCA12	1567	1570	A	['T']
ABCA12	1575	1578	T	['I']
ABCA12	1581	1584	S	['R']
ABCA12	1582	1585	P	['Q']
ABCA12	1584	1587	L	['M', 'V']
ABCA12	1585	1588	N	['S']
ABCA12	1586	1589	A	['V']
ABCA12	1588	1591	A	['I', 'M']
ABCA12	1589	1592	V	['I', 'T']
ABCA12	1600	1603	Q	['R']
ABCA12	1605	1608	E	['D', 'G', 'Q']
ABCA12	1624	1627	S	['N']
ABCA12	1633	1636	S	['A']
ABCA12	1640	1643	N	['T', 'S', 'D']
ABCA12	1643	1646	G	['A']
ABCA12	1644	1647	D	['H']
ABCA12	1667	1670	E	['D']
ABCA12	1668	1671	S	['P']
ABCA12	1669	1672	Q	['H']
ABCA12	1670	1673	K	['H']
ABCA12	1671	1674	N	['S']
ABCA12	1673	1676	A	['N', 'S', 'D']
ABCA12	1674	1677	M	['V']
ABCA12	1676	1679	L	['I']
ABCA12	1678	1681	H	['Y', 'N']
ABCA12	1680	1683	T	['M']
ABCA12	1684	1687	I	['V']
ABCA12	1686	1689	N	['S', 'T']
ABCA12	1688	1691	N	['S', 'G']
ABCA12	1689	1692	A	['T']
ABCA12	1704	1707	N	['S']
ABCA12	1716	1719	G	['R', 'V']
ABCA12	1722	1725	F	['L', 'C']
ABCA12	1723	1726	G	['R']
ABCA12	1730	1733	M	['L', 'I', 'T']
ABCA12	1734	1737	I	['F']
ABCA12	1746	1749	G	['S']
ABCA12	1747	1750	L	['F']
ABCA12	1752	1755	I	['V']
ABCA12	1755	1758	I	['V']
ABCA12	1756	1759	V	['I']
ABCA12	1769	1772	N	['D', 'S']
ABCA12	1773	1776	S	['I', 'G']
ABCA12	1777	1780	I	['M']
ABCA12	1778	1781	Q	['E', 'L']
ABCA12	1780	1783	S	['A']
ABCA12	1782	1785	S	['C']
ABCA12	1787	1790	S	['A']
ABCA12	1788	1791	E	['K']
ABCA12	1791	1794	A	['S']
ABCA12	1794	1797	A	['G']
ABCA12	1796	1799	Y	['S', 'D']
ABCA12	1799	1802	S	['N']
ABCA12	1801	1804	E	['K']
ABCA12	1802	1805	A	['G', 'S', 'E', 'V']
ABCA12	1804	1807	V	['E']
ABCA12	1809	1812	D	['N']
ABCA12	1813	1816	I	['V']
ABCA12	1816	1819	M	['L', 'V', 'T']
ABCA12	1820	1823	T	['I']
ABCA12	1822	1825	D	['N']
ABCA12	1823	1826	L	['P']
ABCA12	1824	1827	Q	['R', 'L', 'W']
ABCA12	1827	1830	N	['K']
ABCA12	1828	1831	K	['E']
ABCA12	1829	1832	D	['G', 'E']
ABCA12	1830	1833	S	['R']
ABCA12	1832	1835	E	['G', 'K']
ABCA12	1842	1845	T	['M']
ABCA12	1846	1849	V	['L']
ABCA12	1853	1856	V	['I']
ABCA12	1860	1863	N	['S']
ABCA12	1862	1865	S	['A']
ABCA12	1873	1876	V	['I']
ABCA12	1876	1879	N	['D']
ABCA12	1880	1883	Q	['H']
ABCA12	1882	1885	V	['M', 'L']
ABCA12	1888	1891	S	['T']
ABCA12	1892	1895	E	['K']
ABCA12	1899	1902	G	['A']
ABCA12	1900	1903	G	['T']
ABCA12	1901	1904	W	['F']
ABCA12	1903	1906	F	['W']
ABCA12	1909	1912	K	['T', 'E']
ABCA12	1912	1915	R	['H', 'M', 'Q']
ABCA12	1913	1916	F	['Y']
ABCA12	1914	1917	D	['L']
ABCA12	1915	1918	I	['L', 'V']
ABCA12	1916	1919	T	['A']
ABCA12	1917	1920	G	['P', 'A']
ABCA12	1918	1921	V	['I', 'L']
ABCA12	1919	1922	P	['F']
ABCA12	1920	1923	A	['H', 'T']
ABCA12	1921	1924	N	['E']
ABCA12	1922	1925	R	['T']
ABCA12	1923	1926	T	['G']
ABCA12	1924	1927	L	['M']
ABCA12	1926	1929	K	['F']
ABCA12	1927	1930	V	['I']
ABCA12	1928	1931	W	['T']
ABCA12	1935	1938	H	['V']
ABCA12	1936	1939	S	['C']
ABCA12	1937	1940	L	['I']
ABCA12	1938	1941	P	['N']
ABCA12	1939	1942	A	['L']
ABCA12	1940	1943	Y	['F']
ABCA12	1941	1946	L	['I']
ABCA12	1944	1949	L	['I']
ABCA12	1945	1950	N	['V']
ABCA12	1946	1951	N	['S']
ABCA12	1947	1952	F	['L']
ABCA12	1948	1953	L	['S']
ABCA12	1949	1954	L	['V']
ABCA12	1950	1955	R	['V']
ABCA12	1951	1956	V	['Y']
ABCA12	1952	1957	N	['F']
ABCA12	1953	1958	M	['L']
ABCA12	1955	1960	K	['T', 'N']
ABCA12	1956	1961	Y	['E']
ABCA12	1957	1962	D	['N']
ABCA12	1963	1968	I	['K']
ABCA12	1964	1969	I	['V']
ABCA12	1965	1970	M	['T']
ABCA12	1971	1976	P	['A']
ABCA12	1974	1979	Q	['K']
ABCA12	1975	1980	D	['P']
ABCA12	1976	1981	Q	['N']
ABCA12	1977	1982	E	['D']
ABCA12	1978	1983	Q	['P']
ABCA12	1979	1984	A	['V']
ABCA12	1980	1985	T	['R']
ABCA12	2008	2013	V	['I']
ABCA12	2024	2029	G	['N']
ABCA12	2025	2030	I	['T']
ABCA12	2026	2031	G	['K']
ABCA12	2028	2033	T	['S']
ABCA12	2037	2042	Y	['A']
ABCA12	2038	2043	D	['T']
ABCA12	2039	2044	M	['L']
ABCA12	2041	2046	F	['Y']
ABCA12	2042	2047	Y	['I']
ABCA12	2043	2048	L	['F']
ABCA12	2044	2049	V	['F']
ABCA12	2052	2057	I	['V']
ABCA12	2065	2070	N	['S']
ABCA12	2075	2080	L	['V', 'F']
ABCA12	2178	2183	N	['S']
ABCA12	2184	2189	N	['D']
ABCA12	2195	2200	S	['A']
ABCA12	2199	2204	M	['V']
ABCA12	2202	2207	S	['F', 'L', 'V']
ABCA12	2210	2215	S	['W', 'R']
ABCA12	2211	2216	L	['V']
ABCA12	2215	2220	L	['I', 'F']
ABCA12	2219	2224	F	['L']
ABCA12	2225	2230	S	['P']
ABCA12	2226	2231	H	['P']
ABCA12	2227	2232	V	['A', 'I']
ABCA12	2228	2233	R	['M', 'V']
ABCA12	2229	2234	E	['D']
ABCA12	2230	2235	T	['A']
ABCA12	2231	2236	I	['T']
ABCA12	2246	2251	S	['G']
ABCA12	2251	2256	F	['V', 'C']
ABCA12	2257	2262	Y	['H']
ABCA12	2258	2263	C	['R', 'H']
ABCA12	2262	2267	T	['I']
ABCA12	2278	2283	I	['L']
ABCA12	2282	2287	A	['S']
ABCA12	2283	2288	G	['N']
ABCA12	2284	2289	E	['Q']
ABCA12	2307	2312	I	['V']
ABCA12	2311	2316	S	['T']
ABCA12	2319	2324	K	['N']
ABCA12	2324	2329	G	['S']
ABCA12	2326	2331	V	['A']
ABCA12	2330	2335	S	['N']
ABCA12	2333	2338	V	['I']
ABCA12	2346	2351	V	['L']
ABCA12	2369	2374	T	['I']
ABCA12	2380	2385	M	['I']
ABCA12	2382	2387	F	['Y']
ABCA12	2385	2390	R	['K']
ABCA12	2386	2391	A	['P', 'T']
ABCA12	2389	2394	M	['L', 'T']
ABCA12	2439	2444	K	['R']
ABCA12	2466	2471	K	['R']
ABCA12	2480	2485	F	['X']
ABCA12	2481	2486	G	['R']
ABCA12	2482	2487	R	['T']
ABCA12	2483	2488	G	['N']
ABCA12	2486	2492	V	['D']
ABCA12	2487	2493	K	['G']
ABCA12	2488	2494	V	['I']
ABCA12	2490	2496	L	['F']
ABCA12	2491	2497	K	['S']
ABCA12	2492	2498	N	['S', 'H']
ABCA12	2493	2499	N	['T']
ABCA12	2494	2500	K	['N', 'R']
ABCA12	2495	2501	V	['L']
ABCA12	2496	2502	T	['S', 'D']
ABCA12	2497	2503	M	['R', 'L']
ABCA12	2498	2504	E	['D']
ABCA12	2499	2508	T	['S', 'I', 'N']
ABCA12	2500	2509	L	['T']
ABCA12	2502	2511	K	['Q']
ABCA12	2503	2512	F	['H']
ABCA12	2504	2513	M	['C']
ABCA12	2505	2514	Q	['K']
ABCA12	2506	2515	L	['I', 'M']
ABCA12	2507	2516	H	['K']
ABCA12	2509	2518	P	['F']
ABCA12	2510	2519	K	['L']
ABCA12	2511	2520	T	['L']
ABCA12	2512	2521	Y	['V', 'H']
ABCA12	2513	2522	L	['P']
ABCA12	2514	2523	K	['Q']
ABCA12	2541	2550	T	['A']
ABCA12	2544	2553	T	['I']
ABCA12	2575	2584	A	['V', 'I']
ABCA12	2578	2587	S	['R']
ABCA12	2581	2590	G	['A']
ABCA12	2584	2593	I	['V', 'L']
ABCA12	2586	2595	V	['T', 'A']
ABCA12	2592	2601	Q	['H']
ABCA12	2593	2602	M	['I']
NP_000024.2 fasta_lociii_match/ABCD1_NP_000024.2_match.fasta aln_lociii_match/ABCD1_NP_000024.2_match.aln
gene	Hum	Aln	site	variable_amino_acids
ABCD1	6	6	R	['T', 'M']
ABCD1	9	9	P	['T', 'S']
ABCD1	10	10	W	['S']
ABCD1	12	12	G	['V']
ABCD1	13	13	N	['S', 'T']
ABCD1	14	14	T	['R']
ABCD1	21	21	L	['V']
ABCD1	25	25	A	['T']
ABCD1	29	29	A	['V']
ABCD1	32	32	V	['I', 'A']
ABCD1	35	35	L	['W']
ABCD1	39	39	C	['Y']
ABCD1	42	42	P	['L', 'S', 'V']
ABCD1	43	43	A	['V']
ABCD1	45	45	G	['D', 'V', 'S']
ABCD1	46	46	L	['P', 'S', 'T']
ABCD1	47	47	Q	['P']
ABCD1	48	48	A	['V', 'G']
ABCD1	49	49	P	['L']
ABCD1	50	50	A	['T']
ABCD1	51	51	G	['R', 'K']
ABCD1	52	52	E	['D']
ABCD1	53	53	P	['S']
ABCD1	54	54	T	['A', 'M']
ABCD1	56	56	E	['D']
ABCD1	57	57	A	['V', 'S']
ABCD1	58	58	S	['P']
ABCD1	60	60	V	['A', 'S']
ABCD1	61	61	A	['T', 'S']
ABCD1	62	62	A	['V', 'T']
ABCD1	65	65	A	['T']
ABCD1	67	67	M	['V']
ABCD1	70	70	V	['I']
ABCD1	76	76	L	['M']
ABCD1	86	86	V	['I']
ABCD1	87	87	L	['V']
ABCD1	88	88	C	['X']
ABCD1	89	89	R	['P']
ABCD1	95	95	A	['V']
ABCD1	99	99	A	['S', 'G']
ABCD1	100	100	A	['T']
ABCD1	128	128	R	['Q']
ABCD1	132	132	W	['R']
ABCD1	139	139	L	['F']
ABCD1	147	147	V	['I']
ABCD1	159	159	A	['T']
ABCD1	172	172	R	['S']
ABCD1	176	176	S	['A']
ABCD1	195	195	Q	['H']
ABCD1	231	231	R	['Q']
ABCD1	236	236	R	['H']
ABCD1	261	261	F	['C']
ABCD1	288	288	A	['S']
ABCD1	300	300	E	['K']
ABCD1	308	311	R	['H', 'Q']
ABCD1	312	315	D	['N', 'R', 'E']
ABCD1	360	363	S	['T']
ABCD1	361	364	D	['A']
ABCD1	362	365	A	['S', 'P', 'Q']
ABCD1	365	368	V	['M', 'T']
ABCD1	366	369	K	['R']
ABCD1	367	370	K	['H']
ABCD1	368	371	A	['S']
ABCD1	370	373	L	['V']
ABCD1	372	375	K	['E']
ABCD1	373	376	K	['R', 'E']
ABCD1	374	377	E	['G', 'K']
ABCD1	375	378	E	['K']
ABCD1	376	379	E	['K']
ABCD1	387	390	I	['K']
ABCD1	388	391	A	['K']
ABCD1	389	392	R	['K']
ABCD1	399	402	I	['T']
ABCD1	402	405	I	['K']
ABCD1	403	406	M	['K']
ABCD1	404	407	S	['K']
ABCD1	415	418	Y	['K']
ABCD1	416	419	T	['K']
ABCD1	417	420	A	['K']
ABCD1	427	430	E	['A']
ABCD1	429	432	V	['K']
ABCD1	430	433	Q	['H', 'K', 'R']
ABCD1	431	434	R	['H', 'K']
ABCD1	432	435	C	['S']
ABCD1	433	436	H	['R']
ABCD1	435	438	K	['R']
ABCD1	437	440	P	['A']
ABCD1	438	441	R	['G']
ABCD1	440	443	L	['P']
ABCD1	443	446	A	['T', 'E', 'S']
ABCD1	444	447	Q	['K']
ABCD1	445	448	A	['P', 'K', 'L']
ABCD1	446	449	G	['N']
ABCD1	447	450	S	['P']
ABCD1	449	452	T	['A']
ABCD1	450	453	I	['M']
ABCD1	451	454	G	['V', 'A']
ABCD1	452	455	R	['Q']
ABCD1	453	456	S	['A', 'P']
ABCD1	456	459	R	['H', 'Y']
ABCD1	457	460	V	['M', 'L']
ABCD1	458	461	E	['D']
ABCD1	460	463	P	['A', 'S']
ABCD1	464	467	R	['Q', 'L']
ABCD1	469	472	D	['E']
ABCD1	470	473	V	['K']
ABCD1	471	474	E	['K']
ABCD1	472	475	Q	['K']
ABCD1	482	485	V	['I']
ABCD1	484	487	P	['K']
ABCD1	485	488	S	['T', 'A', 'K']
ABCD1	486	489	G	['K']
ABCD1	491	494	A	['T']
ABCD1	495	498	I	['M']
ABCD1	496	499	R	['K']
ABCD1	498	501	E	['K']
ABCD1	509	512	N	['K']
ABCD1	510	513	G	['K']
ABCD1	511	514	C	['K']
ABCD1	512	515	G	['K']
ABCD1	519	522	I	['V']
ABCD1	521	524	G	['S']
ABCD1	524	527	W	['K']
ABCD1	525	528	P	['K']
ABCD1	526	529	T	['K']
ABCD1	527	530	Y	['N']
ABCD1	532	535	Y	['C']
ABCD1	538	541	R	['Q']
ABCD1	539	542	M	['K']
ABCD1	540	543	F	['K']
ABCD1	541	544	Y	['N']
ABCD1	549	552	S	['T']
ABCD1	555	558	D	['E', 'N']
ABCD1	556	559	Q	['K']
ABCD1	557	560	V	['K']
ABCD1	558	561	I	['N']
ABCD1	564	567	E	['A', 'G']
ABCD1	567	570	Q	['R']
ABCD1	570	573	G	['K']
ABCD1	571	574	Y	['H', 'K']
ABCD1	572	575	S	['K']
ABCD1	574	577	Q	['R', 'K']
ABCD1	575	578	D	['H']
ABCD1	578	581	A	['T']
ABCD1	582	585	V	['I']
ABCD1	584	587	H	['K']
ABCD1	585	588	L	['K']
ABCD1	586	589	H	['K']
ABCD1	587	590	H	['N']
ABCD1	598	601	M	['V']
ABCD1	599	602	C	['R']

FileNotFoundError: [Errno 2] No such file or directory: 'fasta_lociii_match/BBS2_NP_001364385.1_match.fasta'

#### save output file as "Variable_sites_match_29JUL.tsv"

In [222]:
import os
import pandas as pd
from Bio import SeqIO, AlignIO

results = []

for gene in loci:

    transcripts = vartranscripts_filtered[gene]

    for transcript in transcripts:

        protein = translation[transcript]

        fasta_file = os.path.join(
            "fasta_match",
            f"{gene}_{protein}_match.fasta"
        )

        aln_file = os.path.join(
            "aln_match",
            f"{gene}_{protein}_match.aln"
        )

        print(protein, fasta_file, aln_file)

        # Find the reference protein sequence
        fasta = None
        for record in SeqIO.parse(fasta_file, "fasta"):
            recordid = record.description.split()[0]
            if recordid == protein:
                fasta = record
                break

        if fasta is None:
            raise ValueError(f"{protein} not found in {fasta_file}")

        # Read alignment
        align = AlignIO.read(aln_file, "fasta")

        aln = None
        for record in align:
            if record.id == protein:
                aln = record
                break

        if aln is None:
            raise ValueError(f"{protein} not found in {aln_file}")

        alni = get_aln_positions(gene, protein)

        L = len(fasta)

        for i in range(L):

            j = alni[i]

            counts = pd.Series(list(align[:, j])).value_counts()

            alleles = counts.index.tolist()

            remove_element(alleles, "-")

            n = len(alleles)

            remove_element(alleles, fasta[i])

            if n > 1:

                results.append({
                    "gene": gene,
                    "transcript": transcript,
                    "protein": protein,
                    "human_site": i + 1,
                    "alignment_site": j + 1,
                    "reference_aa": str(fasta.seq[i]),
                    "variable_amino_acids": ",".join(alleles)
                })

                print(
                    gene,
                    i + 1,
                    j + 1,
                    fasta.seq[i],
                    alleles,
                    sep="\t"
                )

# Save results
variable_df = pd.DataFrame(results)

variable_df.to_csv(
    "Variable_sites_match_29JUL.tsv",
    sep="\t",
    index=False
)

print(f"\nSaved {len(variable_df)} variable sites to Variable_sites_match_29JUL.tsv")

NP_000024.2 fasta_match\ABCD1_NP_000024.2_match.fasta aln_match\ABCD1_NP_000024.2_match.aln
ABCD1	6	6	R	['T', 'M']
ABCD1	9	9	P	['T', 'S']
ABCD1	10	10	W	['S']
ABCD1	12	12	G	['V']
ABCD1	13	13	N	['S', 'T']
ABCD1	14	14	T	['R']
ABCD1	21	21	L	['V']
ABCD1	25	25	A	['T']
ABCD1	29	29	A	['V']
ABCD1	32	32	V	['I', 'A']
ABCD1	35	35	L	['W']
ABCD1	39	39	C	['Y']
ABCD1	42	42	P	['L', 'S', 'V']
ABCD1	43	43	A	['V']
ABCD1	45	45	G	['D', 'V', 'S']
ABCD1	46	46	L	['P', 'S', 'T']
ABCD1	47	47	Q	['P']
ABCD1	48	48	A	['V', 'G']
ABCD1	49	49	P	['L']
ABCD1	50	50	A	['T']
ABCD1	51	51	G	['R', 'K']
ABCD1	52	52	E	['D']
ABCD1	53	53	P	['S']
ABCD1	54	54	T	['A', 'M']
ABCD1	56	56	E	['D']
ABCD1	57	57	A	['V', 'S']
ABCD1	58	58	S	['P']
ABCD1	60	60	V	['A', 'S']
ABCD1	61	61	A	['T', 'S']
ABCD1	62	62	A	['V', 'T']
ABCD1	65	65	A	['T']
ABCD1	67	67	M	['V']
ABCD1	70	70	V	['I']
ABCD1	76	76	L	['M']
ABCD1	86	86	V	['I']
ABCD1	87	87	L	['V']
ABCD1	95	95	A	['V']
ABCD1	99	99	A	['S', 'G']
ABCD1	100	100	A	['T']
ABCD1	128	128	R	['Q']
ABCD1	132	132	W	['R']
ABCD1	139	139	L	['F']
ABCD1	147	147	V	['I']
ABCD1	159	159	A	['T']
ABCD1	172	172	R	['S']
ABCD1	176	176	S	['A']
ABCD1	195	195	Q	['H']
ABCD1	231	231	R	['Q']
ABCD1	236	236	R	['H']
ABCD1	261	261	F	['C']
ABCD1	288	288	A	['S']
ABCD1	300	300	E	['K']
ABCD1	308	311	R	['H', 'Q']
ABCD1	312	315	D	['N', 'R', 'E']
ABCD1	360	363	S	['T']
ABCD1	361	364	D	['A']
ABCD1	362	365	A	['S', 'P', 'Q']
ABCD1	365	368	V	['M', 'T']
ABCD1	366	369	K	['R']
ABCD1	367	370	K	['H']
ABCD1	368	371	A	['S']
ABCD1	370	373	L	['V']
ABCD1	372	375	K	['E']
ABCD1	373	376	K	['R', 'E']
ABCD1	374	377	E	['G', 'K']
ABCD1	375	378	E	['K']
ABCD1	376	379	E	['K']
ABCD1	387	390	I	['K']
ABCD1	388	391	A	['K']
ABCD1	389	392	R	['K']
ABCD1	399	402	I	['T']
ABCD1	402	405	I	['K']
ABCD1	403	406	M	['K']
ABCD1	404	407	S	['K']
ABCD1	415	418	Y	['K']
ABCD1	416	419	T	['K']
ABCD1	417	420	A	['K']
ABCD1	427	430	E	['A']
ABCD1	429	432	V	['K']
ABCD1	430	433	Q	['H', 'K', 'R']
ABCD1	431	434	R	['H', 'K']
ABCD1	432	435	C	['S']
ABCD1	433	436	H	['R']
ABCD1	435	438	K	['R']
ABCD1	437	440	P	['A']
ABCD1	438	441	R	['G']
ABCD1	440	443	L	['P']
ABCD1	443	446	A	['T', 'E', 'S']
ABCD1	444	447	Q	['K']
ABCD1	445	448	A	['P', 'K', 'L']
ABCD1	446	449	G	['N']
ABCD1	447	450	S	['P']
ABCD1	449	452	T	['A']
ABCD1	450	453	I	['M']
ABCD1	451	454	G	['V', 'A']
ABCD1	452	455	R	['Q']
ABCD1	453	456	S	['A', 'P']
ABCD1	456	459	R	['H', 'Y']
ABCD1	457	460	V	['M', 'L']
ABCD1	458	461	E	['D']
ABCD1	460	463	P	['A', 'S']
ABCD1	464	467	R	['Q', 'L']
ABCD1	469	472	D	['E']
ABCD1	470	473	V	['K']
ABCD1	471	474	E	['K']
ABCD1	472	475	Q	['K']
ABCD1	482	485	V	['I']
ABCD1	484	487	P	['K']
ABCD1	485	488	S	['T', 'A', 'K']
ABCD1	486	489	G	['K']
ABCD1	491	494	A	['T']
ABCD1	495	498	I	['M']
ABCD1	496	499	R	['K']
ABCD1	498	501	E	['K']
ABCD1	509	512	N	['K']
ABCD1	510	513	G	['K']
ABCD1	511	514	C	['K']
ABCD1	512	515	G	['K']
ABCD1	519	522	I	['V']
ABCD1	521	524	G	['S']
ABCD1	524	527	W	['K']
ABCD1	525	528	P	['K']
ABCD1	526	529	T	['K']
ABCD1	527	530	Y	['N']
ABCD1	532	535	Y	['C']
ABCD1	538	541	R	['Q']
ABCD1	539	542	M	['K']
ABCD1	540	543	F	['K']
ABCD1	541	544	Y	['N']
ABCD1	549	552	S	['T']
ABCD1	555	558	D	['E', 'N']
ABCD1	556	559	Q	['K']
ABCD1	557	560	V	['K']
ABCD1	558	561	I	['N']
ABCD1	564	567	E	['A', 'G']
ABCD1	567	570	Q	['R']
ABCD1	570	573	G	['K']
ABCD1	571	574	Y	['H', 'K']
ABCD1	572	575	S	['K']
ABCD1	574	577	Q	['R', 'K']
ABCD1	575	578	D	['H']
ABCD1	578	581	A	['T']
ABCD1	582	585	V	['I']
ABCD1	584	587	H	['K']
ABCD1	585	588	L	['K']
ABCD1	586	589	H	['K', 'Q']
ABCD1	587	590	H	['N']
ABCD1	598	601	M	['V']
ABCD1	599	602	C	['R']
ABCD1	604	607	V	['I']
ABCD1	611	614	Q	['K']
ABCD1	612	615	R	['K']
ABCD1	613	616	I	['K']
ABCD1	623	626	P	['K']
ABCD1	635	638	V	['E']
ABCD1	636	639	S	['K']
ABCD1	637	640	I	['K']
ABCD1	638	641	D	['N']
ABCD1	649	652	D	['E']
ABCD1	650	653	A	['K', 'T']
ABCD1	651	654	G	['K']
ABCD1	652	655	I	['K']
ABCD1	661	664	P	['S']
ABCD1	674	690	D	['K']
ABCD1	675	691	G	['K']
ABCD1	676	692	E	['Q', 'K']
ABCD1	677	693	G	['S']
ABCD1	678	694	G	['S']
ABCD1	682	698	E	['Q']
ABCD1	686	702	S	['P']
ABCD1	688	704	A	['T', 'V']
ABCD1	703	719	L	['K']
ABCD1	704	720	A	['K']
ABCD1	705	721	G	['K']
ABCD1	709	725	M	['I']
ABCD1	711	727	R	['Q']
ABCD1	714	730	Q	['R']
ABCD1	717	733	C	['R']
ABCD1	724	740	V	['M']
ABCD1	727	743	A	['G']
ABCD1	728	744	H	['Q', 'E']
ABCD1	729	745	V	['P', 'A', 'L', 'S']
ABCD1	730	746	P	['L']
ABCD1	731	747	A	['V', 'S']
ABCD1	732	748	P	['L', 'Q']
ABCD1	733	749	S	['G', 'R', 'W']
ABCD1	734	750	P	['S', 'C', 'L']
ABCD1	735	751	Q	['E', 'M']
ABCD1	736	752	G	['D']
ABCD1	738	754	G	['A', 'S']
ABCD1	739	756	G	['S', 'A', 'V']
ABCD1	740	757	L	['I', 'R', 'A']
ABCD1	741	758	Q	['A', 'R', 'P', 'H']
ABCD1	742	759	G	['N', 'D', 'S']
ABCD1	743	760	A	['V', 'T']
ABCD1	744	761	S	['Q']
ABCD1	745	762	T	['S']
NP_000469.3 fasta_match\ALPL_NP_000469.3_match.fasta aln_match\ALPL_NP_000469.3_match.aln
ALPL	2	10	I	['P']
ALPL	3	11	S	['W', 'M']
ALPL	4	12	P	['A', 'S']
ALPL	5	13	F	['A']
ALPL	6	14	L	['A', 'V']
ALPL	7	15	V	['L', 'I', 'S']
ALPL	9	17	A	['V', 'G']
ALPL	10	37	I	['V', 'M']
ALPL	11	38	G	['S', 'K']
ALPL	12	39	T	['S', 'D']
ALPL	13	40	C	['E']
ALPL	15	42	T	['A', 'M', 'S']
ALPL	16	43	N	['S', 'H', 'D']
ALPL	17	44	S	['C', 'E']
ALPL	18	45	L	['F', 'K']
ALPL	19	46	V	['G']
ALPL	20	47	P	['K']
ALPL	21	48	E	['G']
ALPL	22	49	K	['M', 'R']
ALPL	23	50	E	['L', 'S']
ALPL	24	51	K	['G', 'S']
ALPL	25	52	D	['T']
ALPL	26	53	P	['T']
ALPL	27	54	K	['E', 'G', 'T']
ALPL	28	55	Y	['S', 'T', 'W']
ALPL	29	56	W	['L']
ALPL	30	57	R	['E', 'S']
ALPL	31	58	D	['N', 'R', 'G']
ALPL	32	59	Q	['R']
ALPL	33	60	A	['R']
ALPL	34	61	Q	['A']
ALPL	35	62	E	['Q', 'K']
ALPL	36	63	T	['V']
ALPL	38	69	K	['R']
ALPL	39	70	Y	['H', 'N']
ALPL	40	71	A	['C']
ALPL	42	73	E	['G', 'K']
ALPL	43	74	L	['M']
ALPL	44	75	Q	['S']
ALPL	45	76	K	['E', 'R']
ALPL	46	77	L	['I']
ALPL	47	78	N	['D']
ALPL	48	79	T	['A']
ALPL	49	92	N	['G']
ALPL	50	93	V	['A']
ALPL	51	94	A	['V']
ALPL	52	95	K	['R']
ALPL	53	96	N	['D']
ALPL	54	97	V	['P']
ALPL	55	98	I	['H']
ALPL	56	99	M	['S']
ALPL	58	101	L	['K']
ALPL	59	102	G	['K']
ALPL	60	106	D	['S']
ALPL	61	107	G	['P']
ALPL	62	108	M	['F']
ALPL	63	109	G	['S']
ALPL	64	110	V	['R']
ALPL	65	111	S	['T']
ALPL	66	112	T	['P']
ALPL	67	113	V	['L']
ALPL	68	114	T	['L']
ALPL	69	115	A	['P']
ALPL	70	116	A	['T', 'S']
ALPL	71	117	R	['L']
ALPL	72	118	I	['A']
ALPL	74	120	K	['M', 'T']
ALPL	76	122	Q	['S']
ALPL	77	123	L	['C']
ALPL	78	124	H	['S', 'R']
ALPL	79	125	H	['P', 'N']
ALPL	80	126	N	['R']
ALPL	81	127	P	['T']
ALPL	82	128	G	['R']
ALPL	85	138	T	['P']
ALPL	86	139	R	['K', 'M', 'H']
ALPL	87	140	L	['S']
ALPL	88	141	E	['S']
ALPL	89	142	M	['A']
ALPL	90	143	D	['G']
ALPL	91	144	K	['H']
ALPL	92	145	F	['M']
ALPL	93	155	P	['T', 'S']
ALPL	94	156	F	['L', 'S']
ALPL	95	157	V	['L', 'C', 'M']
ALPL	96	158	A	['S']
ALPL	97	159	L	['H', 'W']
ALPL	98	160	S	['L', 'E']
ALPL	99	161	K	['Q', 'M']
ALPL	137	199	S	['T']
ALPL	138	200	R	['Q']
ALPL	152	214	R	['H']
ALPL	209	271	M	['V']
ALPL	213	275	R	['K']
ALPL	214	276	D	['N']
ALPL	216	278	D	['E']
ALPL	231	293	K	['R']
ALPL	238	300	S	['I', 'M', 'T']
ALPL	251	313	D	['N']
ALPL	253	315	V	['I']
ALPL	254	316	D	['N']
ALPL	255	317	T	['I', 'V']
ALPL	258	320	S	['N']
ALPL	262	324	R	['K', 'T']
ALPL	263	325	Y	['H', 'R', 'N', 'D']
ALPL	266	343	S	['T']
ALPL	269	346	I	['V']
ALPL	273	350	T	['S']
ALPL	276	353	L	['M']
ALPL	277	354	T	['A', 'K', 'N']
ALPL	279	356	D	['N']
ALPL	280	357	P	['L']
ALPL	281	358	H	['Y', 'N', 'S']
ALPL	282	359	N	['T', 'A']
ALPL	295	372	M	['L']
ALPL	296	373	Q	['E']
ALPL	304	381	V	['L', 'M']
ALPL	310	387	S	['T']
ALPL	314	391	V	['T', 'E', 'K', 'G']
ALPL	318	395	Q	['R']
ALPL	319	396	I	['V']
ALPL	321	398	R	['Q', 'K']
ALPL	325	402	K	['R']
ALPL	357	434	R	['Q']
ALPL	360	437	G	['E']
ALPL	361	438	Q	['L', 'R']
ALPL	363	440	G	['D']
ALPL	364	441	S	['N', 'I', 'D', 'T']
ALPL	365	442	L	['M', 'I']
ALPL	368	445	S	['L', 'T']
ALPL	369	446	E	['Q', 'G']
ALPL	402	479	L	['V']
ALPL	425	502	G	['D']
ALPL	433	510	M	['T']
ALPL	438	515	H	['N']
ALPL	451	528	H	['Y']
ALPL	463	540	S	['A']
ALPL	480	557	V	['I']
ALPL	488	565	A	['S']
ALPL	490	567	I	['V']
ALPL	494	571	L	['V']
ALPL	495	572	G	['D', 'N']
ALPL	498	575	A	['T']
ALPL	499	576	P	['H', 'Q', 'S', 'R']
ALPL	502	579	S	['A', 'P']
ALPL	504	581	G	['R', 'S']
ALPL	505	582	S	['G', 'N']
ALPL	506	583	L	['P']
ALPL	508	585	A	['P', 'L']
ALPL	509	586	G	['V']
ALPL	510	587	P	['A']
ALPL	514	591	A	['P', 'L', 'S']
ALPL	518	595	Y	['F', 'L']
ALPL	519	596	P	['S']
ALPL	520	597	L	['M']
ALPL	521	598	S	['R', 'G']
ALPL	522	599	V	['I', 'S', 'H', 'M']
NP_000035.2 fasta_match\AR_NP_000035.2_match.fasta aln_match\AR_NP_000035.2_match.aln
AR	2	2	E	['D']
AR	4	4	Q	['L']
AR	12	12	P	['T']
AR	14	14	P	['Q']
AR	39	39	P	['T', 'S']
AR	42	42	P	['L']
AR	45	45	A	['V']
AR	50	50	P	['V']
AR	51	51	G	['S']
AR	53	53	S	['R', 'G', 'H']
AR	68	68	Q	['L']
AR	69	69	Q	['P', 'L']
AR	70	70	Q	['L', 'R']
AR	72	72	Q	['P']
AR	73	73	Q	['P', 'L']
AR	74	74	Q	['P', 'H']
AR	75	75	Q	['P', 'N']
AR	76	76	Q	['P', 'R']
AR	77	77	Q	['P', 'H']
AR	78	78	Q	['P']
AR	79	79	Q	['P']
AR	81	89	E	['Q', 'H']
AR	85	93	R	['P', 'S']
AR	87	95	Q	['R']
AR	88	96	Q	['E']
AR	89	97	Q	['R']
AR	90	98	Q	['K']
AR	91	103	Q	['H']
AR	92	105	G	['V']
AR	93	106	E	['D']
AR	94	107	D	['N', 'K']
AR	95	108	G	['S']
AR	99	112	A	['V']
AR	100	113	H	['Q']
AR	101	114	R	['S', 'G']
AR	103	116	G	['N']
AR	104	117	P	['R']
AR	105	118	T	['R']
AR	109	122	V	['A']
AR	112	125	E	['G']
AR	114	127	Q	['R']
AR	115	128	Q	['E']
AR	116	129	P	['V', 'H']
AR	119	132	P	['Q']
AR	121	134	S	['T']
AR	123	136	L	['P', 'T']
AR	124	137	E	['D']
AR	127	140	P	['H']
AR	128	141	E	['D', 'K']
AR	129	142	R	['S']
AR	130	143	G	['S', 'R']
AR	136	149	G	['E', 'A']
AR	137	150	A	['V']
AR	138	151	A	['S']
AR	139	152	V	['A', 'T', 'F']
AR	140	153	A	['V']
AR	142	155	S	['G']
AR	146	159	P	['Q']
AR	149	162	L	['P']
AR	150	163	P	['S']
AR	153	166	P	['S']
AR	154	167	D	['E']
AR	155	168	E	['D']
AR	156	169	D	['N']
AR	160	173	A	['V']
AR	165	178	S	['A']
AR	173	186	G	['S']
AR	175	188	S	['N']
AR	180	193	D	['Q']
AR	182	195	K	['D']
AR	183	196	D	['K']
AR	184	197	I	['V']
AR	185	198	L	['T']
AR	186	199	S	['N']
AR	189	202	S	['G', 'P']
AR	190	203	T	['S']
AR	191	204	M	['L']
AR	196	209	Q	['R', 'P']
AR	197	210	Q	['P']
AR	203	216	S	['C']
AR	204	217	E	['K']
AR	206	219	S	['R', 'N']
AR	208	221	S	['N', 'G']
AR	211	224	A	['V']
AR	214	227	A	['T']
AR	215	228	S	['A', 'T']
AR	218	231	P	['S', 'A']
AR	219	232	T	['I', 'S']
AR	220	233	S	['A']
AR	224	237	N	['S']
AR	227	240	G	['V', 'E']
AR	231	244	T	['S']
AR	235	248	N	['S']
AR	236	249	A	['P']
AR	240	253	C	['I']
AR	253	266	A	['T']
AR	258	271	S	['N']
AR	261	274	E	['D']
AR	262	275	Q	['H']
AR	271	284	P	['S', 'Q']
AR	272	285	L	['V']
AR	274	287	G	['V']
AR	275	288	V	['G']
AR	277	290	P	['S', 'L']
AR	278	291	A	['S', 'G']
AR	282	295	T	['I', 'S']
AR	285	298	A	['T']
AR	286	299	P	['S']
AR	288	301	A	['G']
AR	293	306	S	['P']
AR	298	311	S	['R', 'T', 'G']
AR	300	313	G	['D']
AR	302	315	S	['G', 'R']
AR	305	318	D	['E']
AR	306	319	T	['P']
AR	307	320	A	['V']
AR	310	324	S	['T', 'N']
AR	311	325	P	['S']
AR	315	329	G	['S']
AR	317	331	T	['A']
AR	318	332	K	['Q']
AR	319	333	G	['V']
AR	320	334	L	['I']
AR	322	336	G	['V']
AR	323	337	E	['D']
AR	324	338	S	['T']
AR	326	340	G	['V']
AR	328	342	S	['P']
AR	331	345	A	['S', 'G']
AR	332	346	A	['E']
AR	333	347	A	['G']
AR	335	349	S	['T', 'N']
AR	336	350	S	['A']
AR	338	352	T	['A', 'V']
AR	343	357	S	['C']
AR	344	358	T	['A']
AR	346	360	S	['P']
AR	354	368	D	['E']
AR	356	370	A	['T']
AR	357	371	A	['V', 'T']
AR	358	372	A	['S', 'P']
AR	361	375	S	['N']
AR	363	377	D	['E']
AR	370	384	A	['T']
AR	372	386	A	['T']
AR	379	393	P	['L']
AR	392	406	P	['Q']
AR	396	410	G	['S']
AR	398	412	A	['S']
AR	404	418	A	['T']
AR	408	422	Y	['F']
AR	412	426	A	['T']
AR	416	430	G	['S']
AR	417	431	A	['G', 'T']
AR	418	432	G	['V']
AR	419	433	A	['P', 'T']
AR	420	434	A	['T']
AR	421	435	G	['A']
AR	422	436	P	['S', 'Q']
AR	423	437	G	['S']
AR	430	444	A	['S']
AR	432	446	S	['A']
AR	442	456	E	['D']
AR	443	457	E	['Q', 'N']
AR	446	460	L	['V']
AR	449	463	P	['Q']
AR	464	482	G	['S']
AR	465	483	G	['C']
AR	468	486	G	['A', 'S']
AR	470	488	G	['A']
AR	471	489	G	['S', 'A']
AR	472	490	G	['A']
AR	473	491	G	['D']
AR	475	493	A	['T', 'S']
AR	477	495	A	['S']
AR	478	496	V	['I']
AR	479	497	A	['T', 'N', 'V', 'D']
AR	484	502	T	['S', 'N', 'P']
AR	487	505	P	['S', 'L']
AR	492	510	G	['S']
AR	495	513	S	['G']
AR	498	516	T	['P']
AR	507	525	G	['S']
AR	508	526	M	['V']
AR	509	527	V	['M']
AR	510	528	S	['R']
AR	511	529	R	['G']
AR	516	538	S	['N']
AR	518	540	T	['S']
AR	524	546	M	['T']
AR	525	547	G	['S']
AR	529	551	D	['E']
AR	530	552	S	['N', 'T']
AR	537	559	D	['Y']
AR	538	560	M	['V']
AR	539	561	R	['S']
AR	543	565	A	['T']
AR	640	662	L	['V']
AR	646	668	A	['T']
AR	649	671	T	['A']
AR	650	672	T	['S']
AR	653	675	T	['N']
AR	654	676	E	['D']
AR	656	678	T	['S', 'P']
AR	657	679	T	['A', 'S']
AR	665	687	I	['V']
AR	737	759	V	['I']
AR	878	900	T	['X']
NP_000044.2 fasta_match\ATP7B_NP_000044.2_match.fasta aln_match\ATP7B_NP_000044.2_match.aln
ATP7B	2	82	P	['K']
ATP7B	3	83	E	['G', 'K']
ATP7B	4	84	Q	['P', 'R']
ATP7B	5	85	E	['K', 'V']
ATP7B	6	86	R	['P']
ATP7B	7	87	Q	['H', 'R']
ATP7B	8	88	I	['L', 'M']
ATP7B	9	89	T	['L']
ATP7B	10	90	A	['L', 'T']
ATP7B	11	91	R	['E']
ATP7B	12	92	E	['L']
ATP7B	13	93	G	['E']
ATP7B	14	94	A	['P', 'V', 'T']
ATP7B	16	96	R	['A', 'P']
ATP7B	17	97	K	['Q']
ATP7B	18	98	I	['V', 'M']
ATP7B	19	99	L	['S', 'I']
ATP7B	20	100	S	['T']
ATP7B	26	106	T	['A', 'N']
ATP7B	27	107	R	['H', 'C', 'P']
ATP7B	28	108	A	['D', 'E']
ATP7B	30	110	E	['G']
ATP7B	31	111	P	['S']
ATP7B	32	112	A	['T']
ATP7B	35	115	K	['Q']
ATP7B	42	122	V	['I']
ATP7B	44	124	Y	['F']
ATP7B	47	127	G	['S', 'T']
ATP7B	48	128	L	['P', 'V']
ATP7B	50	130	G	['S', 'D']
ATP7B	51	131	L	['Q']
ATP7B	52	132	G	['C', 'S']
ATP7B	53	133	P	['A', 'L']
ATP7B	54	134	S	['F']
ATP7B	55	135	S	['P']
ATP7B	56	136	Q	['P']
ATP7B	57	137	V	['M']
ATP7B	58	138	A	['D', 'T', 'S']
ATP7B	59	139	T	['I']
ATP7B	60	140	S	['N']
ATP7B	61	141	T	['M', 'L', 'V']
ATP7B	62	142	V	['I']
ATP7B	63	143	R	['K', 'S']
ATP7B	65	145	L	['W']
ATP7B	68	148	T	['A']
ATP7B	74	154	K	['Q']
ATP7B	78	158	D	['G', 'N']
ATP7B	79	159	R	['M', 'V']
ATP7B	82	162	N	['S', 'G', 'T']
ATP7B	86	166	I	['V']
ATP7B	87	167	I	['V', 'A']
ATP7B	88	168	S	['N']
ATP7B	89	169	M	['I', 'V']
ATP7B	90	170	K	['E', 'Q']
ATP7B	92	172	S	['F']
ATP7B	93	173	L	['V']
ATP7B	97	177	S	['R']
ATP7B	100	180	V	['M']
ATP7B	101	181	K	['N', 'Q']
ATP7B	102	182	Y	['H']
ATP7B	107	187	V	['I', 'L']
ATP7B	108	188	C	['S', 'N']
ATP7B	109	189	L	['P']
ATP7B	110	190	Q	['R']
ATP7B	115	195	Q	['R']
ATP7B	117	197	G	['E']
ATP7B	122	202	E	['K']
ATP7B	125	205	I	['V']
ATP7B	126	206	A	['T']
ATP7B	127	207	E	['P', 'Q', 'G']
ATP7B	130	210	A	['P']
ATP7B	131	211	A	['G']
ATP7B	138	218	L	['W']
ATP7B	140	220	A	['T', 'S', 'P']
ATP7B	145	225	V	['A']
ATP7B	146	226	K	['R']
ATP7B	150	230	E	['K', 'Q']
ATP7B	159	239	S	['G']
ATP7B	160	240	S	['T']
ATP7B	163	243	G	['S']
ATP7B	164	244	K	['T']
ATP7B	165	245	V	['I']
ATP7B	166	246	R	['G']
ATP7B	173	253	R	['K']
ATP7B	174	254	V	['A']
ATP7B	175	255	K	['R']
ATP7B	179	259	S	['G']
ATP7B	180	260	N	['H', 'S']
ATP7B	184	264	V	['I']
ATP7B	185	265	I	['V']
ATP7B	195	275	E	['K']
ATP7B	202	282	N	['T']
ATP7B	203	283	D	['G']
ATP7B	209	289	A	['V']
ATP7B	212	292	S	['N']
ATP7B	213	293	K	['R']
ATP7B	214	294	V	['A', 'M', 'L']
ATP7B	215	295	A	['T']
ATP7B	217	297	L	['R']
ATP7B	225	305	E	['G', 'R']
ATP7B	226	306	R	['Q']
ATP7B	228	308	Q	['E']
ATP7B	231	311	N	['Y']
ATP7B	234	314	R	['M', 'T']
ATP7B	235	315	P	['L']
ATP7B	236	316	L	['F', 'S']
ATP7B	237	317	S	['A', 'T']
ATP7B	238	318	S	['F']
ATP7B	239	319	A	['T']
ATP7B	241	321	Q	['E']
ATP7B	243	323	F	['S', 'I']
ATP7B	244	324	N	['S']
ATP7B	249	329	L	['S', 'R']
ATP7B	251	331	H	['Q', 'N']
ATP7B	253	333	G	['E']
ATP7B	254	334	S	['R', 'N']
ATP7B	255	335	H	['N', 'Q']
ATP7B	258	338	T	['V']
ATP7B	262	342	R	['G']
ATP7B	263	343	I	['V']
ATP7B	264	344	D	['Q', 'G', 'E']
ATP7B	269	349	K	['T', 'N', 'I', 'M']
ATP7B	272	352	V	['I']
ATP7B	274	354	N	['S']
ATP7B	277	357	E	['G']
ATP7B	278	358	N	['S']
ATP7B	283	363	L	['P']
ATP7B	285	365	V	['I']
ATP7B	287	367	S	['N']
ATP7B	289	369	Q	['R', 'K']
ATP7B	294	374	N	['D']
ATP7B	295	375	K	['R']
ATP7B	298	378	Q	['R', 'E']
ATP7B	299	379	V	['I']
ATP7B	300	380	K	['Q']
ATP7B	302	382	D	['H']
ATP7B	303	383	P	['S']
ATP7B	305	385	C	['R', 'L']
ATP7B	307	387	S	['N']
ATP7B	309	389	V	['M']
ATP7B	310	390	A	['S']
ATP7B	312	392	Q	['R']
ATP7B	313	393	R	['T', 'M', 'K']
ATP7B	326	406	S	['Y']
ATP7B	330	410	G	['A', 'E', 'R']
ATP7B	332	412	E	['K']
ATP7B	334	414	S	['C', 'Y']
ATP7B	335	415	G	['E', 'R']
ATP7B	336	416	T	['I']
ATP7B	337	417	D	['G', 'E']
ATP7B	338	418	H	['P', 'L']
ATP7B	339	419	R	['G', 'E']
ATP7B	340	420	S	['P']
ATP7B	341	421	S	['P', 'F']
ATP7B	342	422	S	['N', 'G']
ATP7B	343	423	S	['C']
ATP7B	344	424	H	['L', 'R']
ATP7B	345	425	S	['N', 'Y', 'T']
ATP7B	346	426	P	['L']
ATP7B	347	427	G	['A']
ATP7B	348	428	S	['F']
ATP7B	349	429	P	['S', 'L', 'Y']
ATP7B	350	430	P	['Q']
ATP7B	352	432	N	['D']
ATP7B	354	434	V	['G', 'A']
ATP7B	355	435	Q	['P']
ATP7B	356	436	G	['S']
ATP7B	357	437	T	['S', 'M']
ATP7B	358	438	C	['S']
ATP7B	359	439	S	['D', 'N']
ATP7B	360	440	T	['P']
ATP7B	361	441	T	['A']
ATP7B	362	442	L	['V', 'E']
ATP7B	363	443	I	['L']
ATP7B	364	444	A	['T']
ATP7B	365	445	I	['V']
ATP7B	367	447	G	['S']
ATP7B	369	449	T	['S']
ATP7B	371	451	A	['V']
ATP7B	374	454	V	['A']
ATP7B	375	455	H	['Q']
ATP7B	376	456	S	['T', 'A']
ATP7B	378	458	E	['K', 'Q']
ATP7B	380	460	M	['V', 'A', 'L']
ATP7B	383	463	Q	['R', 'Y']
ATP7B	384	464	L	['R']
ATP7B	385	465	E	['D']
ATP7B	390	470	I	['V', 'M']
ATP7B	391	471	S	['T']
ATP7B	396	476	E	['K']
ATP7B	397	477	G	['E']
ATP7B	398	478	T	['I', 'S']
ATP7B	399	479	A	['G']
ATP7B	400	480	T	['A', 'V']
ATP7B	401	481	V	['I']
ATP7B	403	483	Y	['H']
ATP7B	404	484	N	['D']
ATP7B	405	485	P	['H']
ATP7B	409	489	S	['T']
ATP7B	410	490	P	['S']
ATP7B	412	492	E	['D']
ATP7B	414	494	R	['S']
ATP7B	415	495	A	['T', 'V', 'S']
ATP7B	417	497	I	['V']
ATP7B	423	503	E	['V']
ATP7B	424	504	A	['V']
ATP7B	425	505	S	['L']
ATP7B	426	506	V	['I', 'F']
ATP7B	427	507	V	['I', 'A']
ATP7B	428	508	S	['P']
ATP7B	429	509	E	['A', 'V']
ATP7B	430	511	S	['N']
ATP7B	431	512	C	['H', 'Y']
ATP7B	433	514	T	['F', 'L']
ATP7B	434	515	N	['S']
ATP7B	435	516	P	['S']
ATP7B	436	517	L	['A', 'V']
ATP7B	438	519	N	['D', 'H', 'K', 'S']
ATP7B	439	520	H	['L', 'P']
ATP7B	440	521	S	['N']
ATP7B	441	522	A	['G', 'T']
ATP7B	442	523	G	['S']
ATP7B	443	524	N	['T']
ATP7B	445	526	M	['V']
ATP7B	448	529	T	['I']
ATP7B	449	530	T	['I', 'P']
ATP7B	450	531	D	['G']
ATP7B	451	532	G	['V', 'C']
ATP7B	452	533	T	['V', 'P', 'A']
ATP7B	453	534	P	['H']
ATP7B	454	535	T	['V', 'A']
ATP7B	457	538	Q	['H', 'R']
ATP7B	461	542	P	['L']
ATP7B	462	543	H	['R']
ATP7B	463	544	T	['A', 'P']
ATP7B	464	545	G	['E']
ATP7B	465	546	R	['G', 'S', 'E']
ATP7B	466	547	L	['A', 'F']
ATP7B	467	548	P	['S']
ATP7B	468	549	A	['T', 'Q', 'S']
ATP7B	469	550	N	['S', 'H', 'I']
ATP7B	471	552	A	['L', 'V', 'T', 'D', 'G', 'E', 'N']
ATP7B	472	553	P	['L', 'A']
ATP7B	473	554	D	['S', 'G']
ATP7B	474	555	I	['H', 'R']
ATP7B	475	556	L	['W', 'S', 'M']
ATP7B	476	557	A	['P', 'S']
ATP7B	477	558	K	['N']
ATP7B	478	559	S	['A']
ATP7B	479	560	P	['L', 'S']
ATP7B	480	561	Q	['R', 'P', 'E']
ATP7B	481	562	S	['A', 'P']
ATP7B	482	563	T	['S', 'P', 'A']
ATP7B	483	564	R	['G']
ATP7B	484	565	A	['T']
ATP7B	485	566	V	['A']
ATP7B	486	567	A	['G']
ATP7B	487	568	P	['L']
ATP7B	503	584	V	['I']
ATP7B	505	586	N	['T']
ATP7B	512	593	K	['N']
ATP7B	513	594	E	['K']
ATP7B	516	597	V	['I']
ATP7B	517	598	L	['V']
ATP7B	530	611	I	['V']
ATP7B	533	614	D	['N', 'S']
ATP7B	536	617	V	['I']
ATP7B	537	618	I	['V']
ATP7B	540	621	L	['P', 'H']
ATP7B	541	622	E	['R', 'Q']
ATP7B	542	623	I	['V']
ATP7B	545	626	F	['L']
ATP7B	546	627	I	['V']
ATP7B	547	628	Q	['T']
ATP7B	548	629	D	['E']
ATP7B	549	630	L	['Q']
ATP7B	554	635	A	['T']
ATP7B	555	636	V	['I']
ATP7B	559	640	Y	['S']
ATP7B	560	641	A	['T']
ATP7B	562	643	S	['C']
ATP7B	563	644	D	['V', 'N', 'S', 'L']
ATP7B	565	646	N	['D', 'S', 'E']
ATP7B	569	650	T	['I']
ATP7B	570	651	I	['V']
ATP7B	576	657	A	['T']
ATP7B	581	662	N	['T']
ATP7B	587	668	T	['M']
ATP7B	590	671	N	['D', 'S']
ATP7B	594	675	Y	['H']
ATP7B	595	676	A	['T']
ATP7B	612	693	I	['V']
ATP7B	619	700	I	['V']
ATP7B	620	701	K	['R']
ATP7B	622	703	I	['F']
ATP7B	628	709	H	['R']
ATP7B	631	712	L	['V', 'P']
ATP7B	633	714	Q	['R']
ATP7B	635	716	N	['I', 'K']
ATP7B	637	718	N	['S', 'R']
ATP7B	638	719	A	['T']
ATP7B	639	720	H	['R']

In [195]:
run kondrashov

In [ ]:
variable = {}
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        protein = translation[transcript]
        variable.update({transcript: get_variable_sites(gene, protein, True)})
        print(gene, transcript, protein, variable, sep= '\t')

#### save output to file "variable_sites.tsv"

In [31]:
with open("variable_sites.tsv", "w") as outfile:

    print("gene\ttranscript\tsite\tvariable_amino_acids", file=outfile)

    for gene in loci:
        transcripts = vartranscripts_filtered[gene]

        for transcript in transcripts:
            protein = translation[transcript]
            tmp_variable = get_variable_sites(gene, protein, True)

            variable[transcript] = tmp_variable

            for site, aas in tmp_variable.items():
                print(
                    gene,
                    transcript,
                    site,
                    ",".join(aas),
                    sep="\t",
                    file=outfile
                )

print("Saved to variable.tsv")

Orig	Aln	Human	Others
6	6	R	['T', 'M']
9	9	P	['T', 'S']
10	10	W	['S']
12	12	G	['V']
13	13	N	['S', 'T']
14	14	T	['R']
21	21	L	['V']
25	25	A	['T']
29	29	A	['V']
32	32	V	['I', 'A']
35	35	L	['W']
39	39	C	['Y']
42	42	P	['L', 'S', 'V']
43	43	A	['V']
45	45	G	['V', 'D', 'S']
46	46	L	['S', 'P', 'T']
47	47	Q	['P']
48	48	A	['V', 'G']
49	49	P	['L']
50	50	A	['T']
51	51	G	['R', 'K']
52	52	E	['D']
53	53	P	['S']
54	54	T	['A', 'M']
55	55	Q	['D']
56	56	E	['M', 'D']
57	57	A	['V', 'S', 'T']
58	58	S	['P']
60	60	V	['A', 'S', 'L']
61	61	A	['T', 'R', 'S']
62	62	A	['V', 'H', 'T']
63	63	A	['T']
64	64	K	['G']
65	65	A	['Q', 'T']
66	66	G	['S']
67	67	M	['V']
68	68	N	['A', 'D']
70	70	V	['I']
76	76	L	['M']
86	86	V	['I']
87	87	L	['V']
88	88	C	['X']
89	89	R	['P']
95	95	A	['V']
97	97	H	['Q']
98	98	S	['T']
99	99	A	['S', 'G']
100	100	A	['L', 'T']
128	128	R	['Q']
132	132	W	['R']
134	134	L	['V']
136	136	Q	['V']
137	137	W	['L']
139	139	L	['A', 'F']
140	140	I	['V']
143	143	P	['Q']
147	147	V	['I']
159	159	A	['T']
172	172	R	['S']
176	176	S	['A']
195	195	Q	['H']
231	231	R	['Q']
236	236	R	['H']
237	237	G	['E']
240	240	T	['P']
261	261	F	['C']
265	265	F	['Y']
267	267	E	['A']
268	268	L	['N']
269	269	V	['M']
270	270	A	['E']
271	271	E	['D']
272	272	E	['S']
273	273	A	['V']
274	274	R	['C']
275	275	R	['C']
276	276	K	['R']
277	277	G	['D']
278	278	E	['Y']
279	279	L	['V']
282	282	M	['R']
288	288	A	['S']
300	300	E	['K']
301	304	V	['L']
302	305	E	['P']
304	307	A	['R']
305	308	L	['V']
306	309	L	['V']
307	310	Q	['K']
308	311	R	['H', 'Q']
309	312	S	['F']
312	315	D	['N', 'E', 'R']
340	343	S	['T']
341	344	A	['S']
360	363	S	['T', 'Q']
361	364	D	['E', 'A']
362	365	A	['P', 'S', 'Q']
365	368	V	['M', 'T']
366	369	K	['R']
367	370	K	['H']
368	371	A	['S']
370	373	L	['V']
371	374	E	['N']
372	375	K	['G', 'E']
373	376	K	['R', 'E']
374	377	E	['G', 'K']
375	378	E	['K']
376	379	E	['K']
387	390	I	['K']
388	391	A	['K']
389	392	R	['K']
399	402	I	['T']
402	405	I	['K']
403	406	M	['K']
404	407	S	['K']
415	418	Y	['K']
416	419	T	['K']
417	420	A	['K']
427	430	E	['A']
429	432	V	['K']
430	433	Q	['R', 'H', 'K']
431	434	R	['H', 'K']
432	435	C	['S']
433	436	H	['R']
435	438	K	['R']
437	440	P	['A']
438	441	R	['G']
440	443	L	['P']
443	446	A	['T', 'E', 'S']
444	447	Q	['K']
445	448	A	['P', 'L', 'K']
446	449	G	['N']
447	450	S	['P']
449	452	T	['A']
450	453	I	['M']
451	454	G	['V', 'A']
452	455	R	['Q']
453	456	S	['P', 'A']
456	459	R	['H', 'Y']
457	460	V	['M', 'L']
458	461	E	['D']
460	463	P	['A', 'S']
464	467	R	['Q', 'L']
467	570	V	['Q']
469	572	D	['E']
470	573	V	['K']
471	574	E	['K']
472	575	Q	['K']
478	581	N	['K']
479	582	I	['V']
481	584	I	['V']
482	585	V	['I', 'S']
483	586	T	['V']
484	587	P	['K']
485	588	S	['T', 'A', 'K']
486	589	G	['K']
491	594	A	['T']
495	598	I	['M']
496	599	R	['K']
497	600	V	['R']
498	601	E	['K', 'W']
499	602	E	['P']
500	603	G	['L']
501	604	M	['S']
502	605	H	['Q']
504	607	L	['G']
505	608	I	['N']
506	609	T	['G', 'H']
507	610	G	['S']
509	612	N	['D', 'K', 'A', 'R', 'S']
510	613	G	['S', 'K']
511	614	C	['K', 'R']
512	616	G	['K']
513	617	K	['R']
514	618	S	['Q']
515	619	S	['A']
516	620	L	['R']
517	621	F	['W']
519	623	I	['V', 'R']
520	624	L	['R']
521	625	G	['S']
524	628	W	['K', 'L']
525	629	P	['K', 'M']
526	630	T	['K', 'W', 'S']
527	631	Y	['N']
528	632	G	['R']
530	634	V	['S']
531	635	L	['S']
532	636	Y	['A', 'T', 'C']
533	637	K	['R', 'E']
534	638	P	['T', 'K']
535	639	P	['S', 'A']
537	641	Q	['S', 'P']
538	642	R	['Q', 'L']
539	643	M	['K', 'G']
540	644	F	['K', 'A']
541	645	Y	['N', 'S']
542	646	I	['L', 'V']
543	647	P	['S']
544	648	Q	['P', 'S', 'H', 'A']
545	649	R	['S']
546	650	P	['A']
547	651	Y	['G', 'L']
548	652	M	['V', 'L']
549	653	S	['V', 'T']
550	654	V	['L', 'I']
551	655	G	['L', 'C']
552	656	S	['T', 'G']
553	657	L	['F']
554	658	R	['Q']
555	659	D	['E', 'N']
556	660	Q	['K', 'R', 'P']
557	661	V	['E', 'W', 'K']
558	662	I	['N', 'W', 'L']
559	663	Y	['C', 'W', 'L']
560	664	P	['A']
561	665	D	['A']
563	667	V	['T']
564	668	E	['A', 'G']
567	671	Q	['R']
570	674	G	['K']
571	675	Y	['H', 'K']
572	676	S	['K']
574	678	Q	['R', 'K']
575	679	D	['H']
578	682	A	['T']
582	686	V	['I']
584	688	H	['K']
585	689	L	['K']
586	690	H	['Q', 'K']
587	691	H	['N']
593	697	G	['S']
596	700	E	['R']
597	701	A	['K']
598	702	M	['V', 'A']
599	703	C	['R']
604	708	V	['I']
611	715	Q	['K', 'R']
612	716	R	['K', 'Q']
613	717	I	['K']
615	719	M	['L']
616	720	A	['S']
623	727	P	['K']
630	734	E	['I']
632	736	T	['S']
634	738	A	['Q']
635	739	V	['E']
636	740	S	['K']
637	741	I	['K']
638	742	D	['N']
649	753	D	['E']
650	754	A	['K', 'T']
651	755	G	['K']
652	756	I	['K']
654	758	L	['P']
655	759	L	['M', 'V']
656	760	S	['A', 'C', 'R']
657	761	I	['A', 'L', 'V']
658	762	T	['A', 'H', 'S']
659	763	H	['R', 'T', 'V']
660	764	R	['A', 'C']
661	765	P	['S', 'L']
662	766	S	['R', 'C', 'A']
663	767	L	['V', 'S', 'M']
665	782	K	['V']
666	783	Y	['C']
674	791	D	['K']
675	792	G	['K']
676	793	E	['Q', 'K']
677	794	G	['S']
678	795	G	['S']
682	799	E	['Q']
684	801	L	['V']
685	802	D	['G']
686	803	S	['P']
687	804	A	['G']
688	805	A	['T', 'P', 'V']
690	807	L	['T']
691	808	S	['V']
692	809	L	['V']
693	810	T	['C']
694	811	E	['S']
695	812	E	['T']
696	813	K	['S']
697	814	Q	['P']
698	815	R	['H']
699	816	L	['P']
700	817	E	['S']
703	820	L	['K']
704	821	A	['K']
705	822	G	['K']
707	824	P	['A', 'T']
708	825	K	['W', 'C']
709	826	M	['V', 'I', 'S', 'L']
710	827	Q	['K', 'T', 'R']
711	828	R	['Q', 'M', 'L', 'S']
712	829	R	['I', 'P', 'H']
713	830	L	['R', 'C']
714	831	Q	['N', 'G', 'R', 'H']
715	832	E	['K', 'P', 'D']
716	833	L	['T', 'M']
717	834	C	['R', 'S', 'G']
718	835	Q	['H']
724	841	V	['M', 'L']
725	842	A	['G']
727	844	A	['G', 'T']
728	845	H	['Q', 'L', 'E']
729	883	V	['P', 'A', 'L', 'S']
730	884	P	['L', 'G', 'W', 'Q']
731	885	A	['S', 'V', 'N']
732	886	P	['L', 'H', 'D', 'Q']
733	887	S	['G', 'R', 'W', 'A', 'Y', 'C', 'L']
734	888	P	['S', 'V', 'C', 'L', 'I']
735	889	Q	['E', 'M', 'A', 'V', 'T']
736	890	G	['D', 'A', 'Q', 'R', 'T']
737	927	P	['A']
738	928	G	['A', 'V', 'Q', 'S']
739	938	G	['S', 'P', 'A', 'R', 'V']
740	939	L	['R', 'A', 'M', 'I', 'K', 'V']
741	940	Q	['S', 'A', 'P', 'D', 'E', 'R', 'H', 'V']
742	941	G	['P', 'S', 'N', 'D', 'A', 'F', 'E', 'C']
743	942	A	['T', 'L', 'V', 'H', 'S', 'E', 'R']
744	943	S	['E', 'A', 'Q', 'H', 'G', 'P']
745	944	T	['S', 'K', 'A']
Orig	Aln	Human	Others
1	76	M	['P']
2	77	I	['S', 'V']
3	78	S	['Q']
4	79	P	['A', 'H']
5	80	F	['L']
6	81	L	['Q', 'V']
7	82	V	['P', 'L', 'I']
8	83	L	['T']
9	84	A	['W', 'V']
10	85	I	['V']
11	86	G	['K']
12	87	T	['D']
13	88	C	['E']
15	90	T	['M', 'A', 'S']
16	91	N	['S', 'D', 'H']
17	92	S	['E', 'C']
18	93	L	['F', 'K']
19	94	V	['G']
20	95	P	['K']
21	96	E	['G']
22	97	K	['M']
23	98	E	['L']
24	99	K	['G']
25	100	D	['M']
26	101	P	['T']
27	102	K	['W', 'E', 'L', 'G']
28	103	Y	['S', 'G', 'T']
29	104	W	['F', 'L']
30	105	R	['S']
31	106	D	['S', 'N', 'R', 'G']
32	107	Q	['S', 'R']
33	108	A	['T', 'R']
34	109	Q	['P', 'A']
35	110	E	['T', 'Q', 'M', 'K']
36	111	T	['W', 'V']
37	112	L	['P']
38	117	K	['R']
39	118	Y	['H', 'N']
40	119	A	['C']
42	121	E	['G', 'K']
43	122	L	['M']
44	123	Q	['S']
45	124	K	['E', 'R']
46	125	L	['I']
47	126	N	['D']
48	127	T	['A']
49	128	N	['L']
50	129	V	['N']
51	130	A	['R']
52	131	K	['H']
53	132	N	['F']
54	133	V	['Q']
55	134	I	['K']
56	135	M	['R']
57	136	F	['E']
58	137	L	['G']
60	139	D	['P']
62	156	M	['F']
63	157	G	['S']
64	158	V	['R']
65	159	S	['T']
66	160	T	['P']
67	161	V	['M', 'L']
68	162	T	['S', 'L']
69	163	A	['S', 'P']
70	164	A	['C', 'T', 'S']
71	165	R	['S', 'L']
72	166	I	['W', 'A']
73	167	L	['E']
74	168	K	['M', 'T']
76	170	Q	['S']
77	171	L	['C']
78	172	H	['R', 'S']
79	173	H	['N', 'P']
80	174	N	['R']
81	175	P	['T']
82	176	G	['R']
84	178	E	['R']
85	179	T	['P']
86	180	R	['K', 'M', 'L']
88	182	E	['T']
89	183	M	['P']
90	184	D	['P']
91	185	K	['E']
92	202	F	['L']
93	203	P	['T']
94	204	F	['L']
95	205	V	['M', 'L']
96	206	A	['S']
97	207	L	['H']
98	208	S	['L']
99	209	K	['Q']
137	247	S	['T']
138	248	R	['Q']
152	262	R	['H']
209	319	M	['V']
213	323	R	['K']
214	324	D	['N']
216	326	D	['E']
231	341	K	['R']
238	348	S	['I', 'M', 'T']
251	361	D	['N']
253	363	V	['I']
254	364	D	['N']
255	365	T	['I', 'V']
258	368	S	['N']
262	372	R	['K', 'T']
263	373	Y	['H', 'R', 'N', 'D']
266	391	S	['T']
269	394	I	['V']
273	398	T	['S']
276	401	L	['M']
277	402	T	['A', 'K', 'N']
279	404	D	['N']
280	405	P	['L']
281	406	H	['Y', 'N', 'S']
282	407	N	['T', 'A']
295	420	M	['L']
296	421	Q	['E']
304	429	V	['L', 'M']
310	435	S	['T']
314	439	V	['E', 'T', 'K', 'G']
318	443	Q	['R']
319	444	I	['V']
321	446	R	['Q', 'K']
325	450	K	['R']
357	482	R	['Q']
360	485	G	['E']
361	486	Q	['L', 'R']
363	488	G	['D']
364	489	S	['N', 'I', 'T', 'D']
365	490	L	['M', 'I']
368	493	S	['L', 'T']
369	494	E	['G', 'Q']
402	527	L	['V']
425	550	G	['D']
433	558	M	['T']
437	562	A	['V']
438	563	H	['N', 'Y', 'L']
439	564	N	['K', 'R']
440	565	N	['T']
441	566	Y	['L']
442	567	Q	['R']
443	568	A	['L']
444	569	Q	['V', 'C']
445	570	S	['H', 'D']
446	571	A	['P', 'F']
447	572	V	['I', 'T']
448	573	P	['F']
449	574	L	['Y']
450	582	R	['P']
451	583	H	['Y', 'S', 'F']
452	584	E	['G', 'R']
453	585	T	['S']
454	586	H	['R']
456	588	G	['S']
457	589	E	['K']
459	591	V	['A']
461	593	V	['M']
462	594	F	['L']
463	595	S	['A', 'T']
464	596	K	['T']
465	597	G	['T']
466	598	P	['T']
467	599	M	['R']
468	600	A	['R']
469	601	H	['S']
472	604	H	['C']
473	605	G	['P']
474	606	V	['C']
475	607	H	['A']
476	608	E	['T']
477	609	Q	['R']
478	610	N	['P']
479	611	Y	['T']
480	612	V	['I', 'A']
481	613	P	['G']
482	614	H	['R']
483	615	V	['M']
486	618	Y	['W']
487	619	A	['P']
488	620	A	['S']
489	621	C	['S']
490	622	I	['V', 'P']
491	623	G	['R']
493	625	N	['P']
494	626	L	['V', 'W']
495	627	G	['D', 'N', 'H']
496	628	H	['T']
498	630	A	['T', 'C']
499	631	P	['H', 'Q', 'S', 'R', 'T']
502	634	S	['A', 'M', 'P']
503	635	A	['S']
504	636	G	['R', 'S']
505	637	S	['G', 'N', 'T']
506	638	L	['P', 'T']
507	639	A	['S']
508	640	A	['P', 'L']
509	641	G	['V', 'T']
510	642	P	['A']
512	644	L	['F']
514	646	A	['P', 'S', 'L']
515	647	L	['K']
516	648	A	['R']
517	649	L	['V']
518	650	Y	['F', 'L']
519	651	P	['S']
520	652	L	['M']
521	653	S	['R', 'G', 'K']
522	654	V	['I', 'S', 'M', 'H']
523	655	L	['V']
Orig	Aln	Human	Others
1	3	M	['S']
2	4	E	['R', 'C', 'D']
3	5	V	['L']
4	6	Q	['L']
6	8	G	['N']
7	9	L	['N']
8	10	G	['M']
9	11	R	['A']
10	12	V	['K', 'A']
11	13	Y	['M', 'P']
12	14	P	['L', 'T']
13	15	R	['I', 'L']
14	16	P	['Q', 'L']
15	17	P	['G']
16	18	S	['L', 'A']
17	19	K	['G', 'P']
18	20	T	['V']
19	21	Y	['W']
20	22	R	['K']
21	23	G	['S']
22	24	A	['P']
23	25	F	['P']
24	26	Q	['G']
25	27	N	['Q']
26	28	L	['V']
27	29	F	['T']
28	30	Q	['E']
29	31	S	['A', 'V']
30	32	V	['L']
31	33	R	['K', 'S']
32	34	E	['V', 'L']
33	35	V	['A', 'L']
35	37	Q	['L']
36	38	N	['D', 'G']
37	39	P	['V', 'S']
39	41	P	['T', 'S', 'Y', 'H']
40	42	R	['Y']
42	44	P	['I', 'L']
43	45	E	['D']
44	46	A	['C']
45	47	A	['V']
46	48	S	['H']
47	49	A	['V']
48	50	A	['Y']
49	51	P	['Q', 'A']
50	52	P	['N', 'A', 'V']
51	53	G	['E', 'S']
52	54	A	['N', 'L']
53	55	S	['R', 'E', 'G', 'D', 'H']
54	56	L	['V']
55	57	L	['G', 'Q']
56	58	L	['V']
57	59	L	['A', 'Q']
58	60	Q	['I']
60	62	Q	['E']
61	63	Q	['K']
62	64	Q	['L']
63	65	Q	['R']
64	66	Q	['E']
66	68	Q	['V']
67	69	Q	['V']
68	70	Q	['K']
69	71	Q	['R', 'P']
70	72	Q	['R']
72	74	Q	['P']
73	75	Q	['L', 'P']
74	76	Q	['P', 'H']
75	77	Q	['P', 'N']
76	78	Q	['P', 'R']
77	83	Q	['P', 'E', 'H']
78	84	Q	['P', 'E']
79	85	Q	['P', 'L']
80	86	Q	['F']
81	87	E	['Q', 'I', 'H']
82	88	T	['V']
84	90	P	['K']
85	91	R	['P', 'L', 'S']
86	94	Q	['T']
87	95	Q	['R', 'Y']
88	96	Q	['E', 'H']
89	97	Q	['E']
90	101	Q	['K', 'D']
91	102	Q	['G', 'T']
92	104	G	['V', 'S']
93	105	E	['K', 'D', 'G']
94	106	D	['N', 'G', 'K']
95	107	G	['S', 'A', 'R']
96	108	S	['C', 'E']
97	109	P	['Q']
98	110	Q	['K', 'F']
99	111	A	['T', 'S', 'V']
100	112	H	['Q', 'L', 'G']
101	113	R	['S', 'G', 'D']
102	114	R	['D', 'H']
103	115	G	['N', 'L', 'S']
104	116	P	['R', 'K', 'A']
105	117	T	['L', 'D', 'R']
106	118	G	['D']
107	119	Y	['F']
108	120	L	['E']
109	121	V	['A', 'D']
110	122	L	['T']
111	123	D	['Y', 'S']
112	124	E	['G', 'L', 'R']
113	125	E	['I', 'S']
114	126	Q	['R', 'H', 'E']
115	127	Q	['W', 'M', 'E']
116	128	P	['S', 'V', 'H']
117	129	S	['T']
118	130	Q	['G']
119	131	P	['Q', 'F', 'S']
120	132	Q	['K', 'E']
121	133	S	['P', 'I', 'T']
122	134	A	['G', 'S']
123	135	L	['P', 'K', 'T']
124	136	E	['D', 'V']
125	137	C	['F', 'S']
126	138	H	['F', 'E']
127	139	P	['M', 'H']
128	140	E	['D', 'P', 'K']
129	141	R	['S']
130	142	G	['S', 'R']
131	143	C	['S']
132	144	V	['E']
134	146	E	['S']
135	147	P	['S']
136	148	G	['E', 'A']
137	149	A	['V']
138	150	A	['D', 'S']
139	151	V	['A', 'T', 'Y', 'F']
140	152	A	['V', 'D']
141	153	A	['Y']
142	154	S	['G']
143	155	K	['E']
144	156	G	['E']
145	157	L	['Y']
146	158	P	['Q', 'D']
147	159	Q	['N']
148	160	Q	['E']
149	161	L	['P']
150	162	P	['S']
153	165	P	['S', 'L']
154	166	D	['E']
155	167	E	['D']
156	168	D	['N', 'S']
157	169	D	['G']
158	170	S	['N']
159	171	A	['V']
160	172	A	['V']
163	175	T	['D']
164	176	L	['T']
165	177	S	['N', 'A']
166	178	L	['I']
170	182	T	['Q']
171	183	F	['I']
173	185	G	['S']
174	186	L	['Y']
175	187	S	['N']
176	188	S	['D']
177	189	C	['T']
178	190	S	['W']
179	191	A	['V']
180	192	D	['A', 'Q']
181	193	L	['M']
182	194	K	['E', 'D']
183	195	D	['E', 'M', 'K']
184	196	I	['L', 'V']
185	197	L	['V', 'T']
186	198	S	['D', 'N']
187	199	E	['D']
188	200	A	['G', 'S']
189	201	S	['G', 'L', 'V', 'P']
190	202	T	['V', 'R', 'S']
191	203	M	['K', 'V', 'L']
193	206	L	['V']
194	207	L	['V']
195	208	Q	['K']
196	209	Q	['P', 'R']
197	210	Q	['P']
199	212	Q	['N']
200	213	E	['K']
201	214	A	['T']
202	215	V	['E']
203	216	S	['C']
204	217	E	['K']
205	218	G	['N']
206	219	S	['R', 'N', 'T']
208	221	S	['N', 'G', 'D']
209	222	G	['K']
210	223	R	['P']
211	224	A	['V', 'K']
213	226	E	['K']
214	227	A	['K', 'T']
215	228	S	['A', 'T', 'K']
217	230	A	['G']
218	231	P	['S', 'A', 'K']
219	232	T	['S', 'I', 'N']
220	233	S	['A', 'G']
221	234	S	['K']
222	235	K	['N']
223	236	D	['R']
224	237	N	['S', 'R']
225	238	Y	['N']
226	239	L	['R']
227	240	G	['V', 'K', 'E']
228	241	G	['K']
229	242	T	['K']
230	243	S	['N']
231	244	T	['S', 'P']
232	245	I	['C']
233	246	S	['N']
234	247	D	['A']
235	248	N	['S', 'E']
236	249	A	['F', 'P']
237	250	K	['Q']
238	251	E	['N']
239	252	L	['F']
240	253	C	['I']
241	254	K	['N']
242	255	A	['S']
243	256	V	['F']
244	257	S	['N']
248	261	G	['A']
249	262	L	['I']
251	264	V	['I']
252	265	E	['S']
253	266	A	['N', 'T']
254	267	L	['F']
255	268	E	['N']
258	271	S	['Q', 'N']
259	272	P	['V']
260	273	G	['E']
261	274	E	['D', 'M', 'T']
262	275	Q	['I', 'H']
263	276	L	['I']
264	277	R	['N', 'H']
266	279	D	['E']
268	281	M	['K']
270	283	A	['K', 'I']
271	284	P	['S', 'E', 'Q']
272	285	L	['V', 'G', 'H']
274	287	G	['K', 'E', 'V']
275	288	V	['G', 'Y']
276	289	P	['K']
277	290	P	['L', 'S']
278	291	A	['S', 'G']
280	293	R	['N']
281	294	P	['Q']
282	295	T	['I', 'S']
283	296	P	['E']
285	298	A	['H', 'T']
286	299	P	['S', 'V']
287	300	L	['Y', 'T']
288	301	A	['L', 'C', 'G']
289	302	E	['K']
291	304	K	['Q']
292	305	G	['Q']
293	306	S	['P', 'E']
294	307	L	['Y']
295	308	L	['F']
296	309	D	['G']
297	310	D	['E']
298	311	S	['R', 'T', 'G']
299	312	A	['C']
300	313	G	['D']
301	314	K	['E']
302	315	S	['G', 'T', 'R', 'K']
303	316	T	['Q', 'S']
304	317	E	['M']
305	318	D	['E', 'K']
306	319	T	['P', 'L']
307	320	A	['I', 'H', 'V']
308	321	E	['Q', 'S']
309	322	Y	['M']
310	324	S	['T', 'C']
311	325	P	['Q']
312	326	F	['S']
315	329	G	['S']
317	331	T	['A']
318	332	K	['Q']
319	333	G	['V']
320	334	L	['I']
322	336	G	['V']
323	337	E	['D']
324	338	S	['T']
326	340	G	['V']
328	342	S	['P']
331	345	A	['S', 'G']
332	346	A	['E']
333	347	A	['G']
335	349	S	['T', 'N']
336	350	S	['A']
338	352	T	['V', 'A']
341	355	L	['I']
342	356	P	['D']
343	357	S	['C']
344	358	T	['S', 'A']
346	360	S	['P']
354	368	D	['E']
356	370	A	['T']
357	371	A	['V', 'T']
358	372	A	['S', 'P']
361	375	S	['N']
363	377	D	['E']
369	383	L	['I']
370	384	A	['V', 'T']
371	385	L	['V']
372	386	A	['T']
373	387	G	['A']
374	388	P	['Y']
375	389	P	['S']
377	391	P	['L']
378	392	P	['G']
379	393	P	['L', 'S']
381	395	P	['D']
382	396	H	['R']
386	400	R	['K']
388	402	K	['A']
390	404	E	['A']
391	405	N	['A']
392	406	P	['I', 'Q']
393	407	L	['A']
394	408	D	['A']
395	409	Y	['F']
396	410	G	['S', 'M']
398	412	A	['S']
399	413	W	['V']
400	414	A	['L', 'I', 'P']
401	415	A	['K', 'L']
402	416	A	['P', 'T']
403	417	A	['E']
404	418	A	['D', 'V', 'T']
405	419	Q	['P']
406	420	C	['S']
407	421	R	['L']
408	422	Y	['F', 'L']
409	423	G	['E']
412	426	A	['T']
416	430	G	['S']
417	431	A	['G', 'T']
418	432	G	['V']
419	433	A	['P', 'T']
420	434	A	['T']
421	435	G	['A']
422	436	P	['S', 'Q']
423	437	G	['S']
428	442	S	['R']
429	443	A	['I']
430	444	A	['K', 'S']
432	446	S	['A', 'I']
433	447	S	['A']
434	448	S	['A']
435	449	W	['K']
437	451	T	['N', 'A']
438	452	L	['K', 'V']
439	453	F	['T', 'I']
441	455	A	['V']
442	456	E	['Q', 'D']
443	457	E	['L', 'Q']
444	458	G	['R']
445	459	Q	['R']
446	460	L	['Q', 'V']
449	463	P	['Q']
464	482	G	['S']
465	483	G	['C']
468	486	G	['A', 'S']
470	488	G	['A']
471	489	G	['S', 'A']
472	490	G	['A']
473	491	G	['D']
475	493	A	['T', 'S']
477	495	A	['S']
478	496	V	['I']
479	497	A	['T', 'N', 'V', 'D']
484	502	T	['S', 'N', 'P']
487	505	P	['S', 'L']
492	510	G	['S']
495	513	S	['G']
498	516	T	['P']
507	525	G	['S']
508	526	M	['V']
509	527	V	['L', 'M']
510	528	S	['I', 'R']
511	529	R	['G']
512	530	V	['F']
514	532	Y	['M']
515	533	P	['Q']
516	538	S	['N']
517	539	P	['L']
518	540	T	['S', 'V']
519	541	C	['V']
520	542	V	['I']
521	543	K	['P']
522	544	S	['K']
523	545	E	['S']
524	546	M	['V', 'T']
525	547	G	['T', 'S']
528	550	M	['V']
529	551	D	['E', 'R']
530	552	S	['R', 'T', 'N', 'K']
531	553	Y	['I']
532	554	S	['A', 'E']
533	555	G	['E']
534	556	P	['N', 'E']
535	557	Y	['F', 'A']
536	558	G	['K', 'E']
537	559	D	['V', 'E', 'Y']
538	560	M	['F', 'V', 'H', 'R']
539	561	R	['D', 'S', 'K']
540	562	L	['F']
541	563	E	['N']
542	564	T	['L']
543	565	A	['S', 'T', 'R']
544	566	R	['S']
545	567	D	['Q', 'K']
546	568	H	['D', 'R']
547	569	V	['M', 'L']
548	570	L	['T', 'W']
549	571	P	['T']
550	572	I	['L']
551	573	D	['L', 'S']
552	574	Y	['S', 'F']
554	576	F	['N']
555	577	P	['R']
556	578	P	['N']
557	579	Q	['W']
558	580	K	['R']
559	581	T	['V']
561	583	L	['A']
562	584	I	['L']
563	585	C	['L']
590	612	G	['A']
591	613	K	['P']
592	614	Q	['E']
593	615	K	['R']
594	616	Y	['L']
595	617	L	['I']
596	618	C	['N', 'I', 'E']
597	619	A	['R']
598	620	S	['K', 'Q']
599	621	R	['I', 'C', 'K']
600	622	N	['S']
601	623	D	['S', 'H', 'F']
602	624	C	['T']
603	625	T	['I', 'S', 'G']
604	626	I	['C', 'A']
605	627	D	['S', 'N']
606	628	K	['P', 'H', 'N']
607	629	F	['L', 'Q', 'R']
608	630	R	['S', 'N']
609	631	R	['H', 'E', 'Q', 'L', 'S']
610	632	K	['E', 'T', 'H']
611	633	N	['D', 'E', 'L']
612	634	C	['Y', 'V', 'G', 'L']
613	635	P	['N']
614	636	S	['F', 'V']
615	637	C	['H', 'R', 'A']
616	638	R	['E', 'A', 'Q']
617	639	L	['E', 'Q', 'I', 'A']
618	640	R	['F', 'K', 'A', 'S']
629	651	A	['E', 'V', 'G']
630	652	R	['A', 'K', 'D', 'V']
631	653	K	['V', 'F', 'A', 'L']
632	654	L	['V', 'R', 'G']
640	662	L	['V']
646	668	A	['T']
649	671	T	['A']
650	672	T	['S']
653	675	T	['N']
654	676	E	['D']
656	678	T	['S', 'P']
657	679	T	['A', 'S']
665	687	I	['V']
708	730	L	['V']
709	731	G	['V', 'S']
710	732	E	['S', 'N']
711	733	R	['E', 'C', 'Y']
712	734	Q	['R', 'K']
713	735	L	['I', 'H']
714	736	V	['L']
715	737	H	['K', 'R', 'G']
716	738	V	['M', 'L']
717	739	V	['T', 'F', 'A']
718	740	K	['G', 'R']
719	741	W	['V', 'P', 'T']
720	742	A	['S']
721	743	K	['E', 'A']
722	744	A	['W', 'C']
723	745	L	['F']
737	759	V	['I']
809	831	K	['E']
810	832	A	['R']
812	834	L	['P']
813	835	L	['S']
814	836	F	['D']
816	838	I	['Q']
817	839	I	['L']
818	840	P	['L']
819	841	V	['I']
820	842	D	['H']
821	843	G	['N']
822	844	L	['R']
823	845	K	['D']
824	846	N	['Q']
825	847	Q	['P']
826	848	K	['F']
828	850	F	['V']
830	852	E	['D']
831	853	L	['S']
832	854	R	['F']
833	855	M	['L']
834	856	N	['A']
835	857	Y	['A']
836	858	I	['F']
837	859	K	['E']
838	860	E	['N']
839	861	L	['H']
840	862	D	['I']
841	863	R	['L']
842	864	I	['L']
844	866	A	['N']
848	870	K	['A']
849	871	N	['A']
850	872	P	['S']
851	873	T	['V']
852	874	S	['N', 'H']
853	875	C	['F']
854	876	S	['E']
878	900	T	['X']
887	909	M	['A']
888	910	V	['A']
891	913	D	['H']
Orig	Aln	Human	Others
1	144	M	['S', 'N', 'G', 'Q']
2	145	P	['T', 'A']
3	146	E	['K', 'P', 'T', 'S', 'I', 'V']

## Identify putative CPDs

### STEP 8
#### Next we compare and dentify pathogenic variants () that are nevertheless observed as natural amino acid substitutions in the homologs alignment

In [32]:
print('gene\ttranscript\tsite\twild\tmut\tvar')
final_transcripts = variants.keys()
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        if transcript in final_transcripts:
            sites, wilds, muts = variants[transcript]
            #print(gene, transcript, sites, wilds, muts)
            tmp_variable = variable[transcript]
            #print(tmp_variable)
            variable_sites = tmp_variable.keys()
            #print(variable_sites)
            n= len(sites)
            for i in range(n):
                if sites[i] is None:
                    continue
                site = int(sites[i])
                #print(sites)
                #print(type(site))
                #print(type(next(iter(variable_sites))))
                #if (site in variable_sites) and (muts[i] in tmp_variable[site]):
                if (site in tmp_variable) and (muts[i] in tmp_variable[site]):
                    print(gene, transcript, site, wilds[i], muts[i], tmp_variable[site], sep= '\t')

gene	transcript	site	wild	mut	var
ABCD1	NM_000033.4	654	L	P	['P']
ABCD1	NM_000033.4	507	G	S	['S']
ABCD1	NM_000033.4	510	G	S	['S', 'K']
ABCD1	NM_000033.4	534	P	T	['T', 'K']
ABCD1	NM_000033.4	556	Q	R	['K', 'R', 'P']
ABCD1	NM_000033.4	511	C	R	['K', 'R']
ABCD1	NM_000033.4	533	K	E	['R', 'E']
ABCD1	NM_000033.4	659	H	R	['R', 'T', 'V']
ALPL	NM_000478.6	491	G	R	['R']
ALPL	NM_000478.6	459	V	A	['A']
ALPL	NM_000478.6	37	L	P	['P']
ALPL	NM_000478.6	82	G	R	['R']
ALPL	NM_000478.6	82	G	R	['R']
ALPL	NM_000478.6	71	R	S	['S', 'L']
ALPL	NM_000478.6	489	C	S	['S']
ALPL	NM_000478.6	491	G	R	['R']
ALPL	NM_000478.6	454	H	R	['R']
ALPL	NM_000478.6	489	C	S	['S']
ALPL	NM_000478.6	85	T	P	['P']
ALPL	NM_000478.6	295	M	L	['L']
AR	NM_000044.6	713	L	I	['I', 'H']
AR	NM_000044.6	709	G	V	['V', 'S']
AR	NM_000044.6	723	L	F	['F']
AR	NM_000044.6	610	K	E	['E', 'T', 'H']
ATP7B	NM_000053.4	969	R	Q	['Q']
ATP7B	NM_000053.4	858	T	A	['A']
ATP7B	NM_000053.4	335	G	E	['E', 'R']
CBS	NM_000071.3	539	L	S	['G', 'P', 'Q', 'A', 'V', 'S']
CBS	NM_000071.3	85	G	R	['R']
CBS	NM_000071.3	456	L	P	['P', 'T']
CBS	NM_000071.3	88	P	R	['R']
CBS	NM_000071.3	65	H	L	['Q', 'L']
CFTR	NM_000492.4	1	M	T	['F', 'G', 'L', 'P', 'Y', 'T']
CFTR	NM_000492.4	13	S	F	['V', 'A', 'R', 'F']
F7	NM_000131.5	44	V	I	['G', 'K', 'I', 'L']
F7	NM_019616.4	13	L	P	['V', 'P', 'A', 'S']
F7	NM_019616.4	63	E	K	['K', 'Q']
F7	NM_019616.4	1	M	T	['P', 'T', 'A', 'S', 'G']
F7	NM_019616.4	22	V	I	['G', 'K', 'I', 'L']
F7	NM_019616.4	386	H	R	['R']
F8	NM_000132.4	2228	R	Q	['Q']
F8	NM_000132.4	2135	R	P	['P']
F8	NM_000132.4	2038	N	S	['K', 'S', 'H', 'G']
F8	NM_000132.4	2319	P	L	['L']
F8	NM_000132.4	2344	G	D	['D', 'S']
F8	NM_000132.4	2107	G	D	['D']
F8	NM_000132.4	2198	G	R	['R']
F8	NM_000132.4	2035	V	A	['A']
F8	NM_000132.4	2208	Q	E	['E']
F8	NM_000132.4	19	S	R	['G', 'R']
F8	NM_000132.4	2237	A	T	['T']
F8	NM_000132.4	2157	N	S	['S']
F9	NM_000133.4	75	R	Q	['Q']
G6PD	NM_000402.4	3	R	W	['M', 'W', 'T', 'G', 'E']
GALT	NM_000155.4	319	H	Q	['P', 'Q']
GALT	NM_000155.4	186	H	Y	['Y', 'S']
GALT	NM_000155.4	209	Y	C	['C', 'V']
GALT	NM_000155.4	328	R	H	['H', 'S']
GALT	NM_000155.4	336	M	L	['P', 'L']
GALT	NM_000155.4	51	R	Q	['G', 'P', 'Q']
GALT	NM_000155.4	320	A	V	['V', 'P']
GALT	NM_000155.4	329	S	P	['Q', 'P']
GALT	NM_000155.4	67	R	H	['L', 'P', 'H']
GALT	NM_000155.4	319	H	Q	['P', 'Q']
GALT	NM_000155.4	48	R	S	['K', 'S']
GALT	NM_000155.4	271	E	D	['D', 'G']
GALT	NM_000155.4	223	R	H	['H', 'C', 'L']
GALT	NM_000155.4	1	M	L	['L', 'S', 'P']
GALT	NM_000155.4	236	S	I	['N', 'K', 'E', 'I', 'P']
GALT	NM_000155.4	336	M	L	['P', 'L']
GBA1	NM_000157.4	502	R	C	['C']
GBA1	NM_000157.4	535	R	H	['H']
GBA1	NM_000157.4	227	N	S	['S']
GBA1	NM_000157.4	351	W	C	['C']
GBA1	NM_000157.4	350	H	R	['R']
GBA1	NM_000157.4	416	G	S	['S']
GBA1	NM_000157.4	426	P	L	['L']
GBA1	NM_000157.4	230	V	G	['G']
GBA1	NM_000157.4	351	W	C	['C']
GBA1	NM_000157.4	391	V	A	['A']
HBB	NM_000518.4	102	E	Q	['Q']
KCNH2	NM_000238.4	58	E	K	['S', 'K']
KCNH2	NM_000238.4	837	D	G	['G']
KCNH2	NM_000238.4	87	L	P	['Q', 'P']
KCNQ1	NM_000218.3	591	R	C	['C', 'S']
KCNQ1	NM_000218.3	114	L	P	['V', 'M', 'P']
KCNQ1	NM_000218.3	115	E	G	['K', 'Q', 'G', 'L', 'R']
KCNQ1	NM_000218.3	303	L	P	['P']
KCNQ1	NM_000218.3	125	Y	D	['F', 'S', 'D', 'A', 'T']
KCNQ1	NM_000218.3	117	P	S	['S', 'R', 'E', 'A', 'C']
KCNQ1	NM_000218.3	119	G	S	['N', 'S', 'A']
KCNQ1	NM_000218.3	591	R	S	['C', 'S']
LDLR	NM_000527.5	46	C	S	['S']
LDLR	NM_000527.5	583	H	D	['D']
LDLR	NM_000527.5	828	Y	S	['F', 'V', 'E', 'S']
LDLR	NM_000527.5	1	M	L	['L', 'S']
LDLR	NM_000527.5	1	M	L	['L', 'S']
LDLR	NM_000527.5	34	C	S	['S', 'L']
LDLR	NM_000527.5	579	D	G	['G']
LDLR	NM_000527.5	88	R	K	['K']
TYR	NM_000372.5	346	G	V	['V', 'A']
TYR	NM_000372.5	370	M	I	['I']
TYR	NM_000372.5	406	P	A	['A']
PAH	NM_000277.3	164	I	T	['T']
PAH	NM_000277.3	176	R	Q	['Q']
PAH	NM_000277.3	413	R	H	['H', 'F']
PAH	NM_000277.3	416	P	T	['R', 'T']
PAH	NM_000277.3	156	A	G	['E', 'R', 'G']
PMM2	NM_000303.3	231	V	M	['S', 'A', 'L', 'M', 'E', 'I']
PMM2	NM_000303.3	226	T	S	['P', 'C', 'A', 'S', 'Q', 'N', 'L']
PMM2	NM_000303.3	243	L	P	['E', 'V', 'T', 'P', 'Q', 'M', 'S', 'A', 'N']
PMM2	NM_000303.3	228	G	R	['A', 'T', 'V', 'E', 'L', 'H', 'R']
PMM2	NM_000303.3	223	D	N	['S', 'N', 'A', 'K', 'T', 'R']
PMM2	NM_000303.3	239	R	T	['T', 'Q', 'K', 'D', 'S', 'P', 'C', 'A', 'V']
PMM2	NM_000303.3	231	V	L	['S', 'A', 'L', 'M', 'E', 'I']
PMM2	NM_000303.3	231	V	L	['S', 'A', 'L', 'M', 'E', 'I']
PMM2	NM_000303.3	239	R	S	['T', 'Q', 'K', 'D', 'S', 'P', 'C', 'A', 'V']
RHO	NM_000539.3	180	P	T	['T']
TTR	NM_000371.4	131	L	M	['M', 'T']
TTR	NM_000371.4	142	V	I	['L', 'I']
TTR	NM_000371.4	127	I	V	['V', 'F']
TTR	NM_000371.4	136	Y	S	['R', 'W', 'S']
TTR	NM_000371.4	82	E	K	['K']
TTR	NM_000371.4	77	G	R	['R']
TTR	NM_000371.4	140	A	V	['V']
TTR	NM_000371.4	126	T	I	['I', 'V']
VWF	NM_000552.5	528	N	S	['S']

### save output to file 'invalidated_CPDs.tsv'

In [ ]:
with open("invalidated_CPDs.tsv", "w") as outfile:

    # Write header
    print('gene\ttranscript\tsite\twild\tmut\tvar', file=outfile)

    final_transcripts = variants.keys()

    for gene in loci:
        transcripts = vartranscripts_filtered[gene]

        for transcript in transcripts:
            if transcript in final_transcripts:

                sites, wilds, muts = variants[transcript]
                tmp_variable = variable[transcript]

                for i in range(len(sites)):

                    if sites[i] is None:
                        continue

                    site = int(sites[i])

                    if (site in tmp_variable) and (muts[i] in tmp_variable[site]):
                        print(
                            gene,
                            transcript,
                            site,
                            wilds[i],
                            muts[i],
                            ",".join(tmp_variable[site]),   # Write amino acids as comma-separated
                            sep="\t",
                            file=outfile
                        )

print("Results saved to invalidated_CPDs.tsv")

Results saved to clinvar_matches.tsv

## Look at particular sites

The following command allows you to double check particular sites.  It now also outputs which site each species has.

In [33]:
get_alleles('ATP7B', translation['NM_000053.4'], 969, True)

     Gene: ATP7B
    Human: 969 R
Alignment: 1238 R
R    181
-     27
Q      1
Name: count, dtype: int64

R XP_053420007.1 Nycticebus coucang
R XP_053420006.1 Nycticebus coucang
R XP_053420005.1 Nycticebus coucang
R XP_053419999.1 Nycticebus coucang
R XP_053420008.1 Nycticebus coucang
R XP_023363838.1 Otolemur garnettii
R XP_012668202.1 Otolemur garnettii
R XP_023363839.1 Otolemur garnettii
R XP_012638108.2 Microcebus murinus
R XP_012638109.2 Microcebus murinus
R XP_012504534.1 Propithecus coquereli
R XP_012504526.1 Propithecus coquereli
R XP_012504533.1 Propithecus coquereli
R XP_012504538.1 Propithecus coquereli
R XP_045423256.1 Lemur catta
R XP_045423253.1 Lemur catta
- XP_045423254.1 Lemur catta
R XP_069323794.1 Eulemur rufifrons
R XP_069323793.1 Eulemur rufifrons
R XP_069323796.1 Eulemur rufifrons
R XP_069323797.1 Eulemur rufifrons
R XP_008070488.1 Carlito syrichta
R XP_008070483.1 Carlito syrichta
R XP_008070485.1 Carlito syrichta
- XP_008070484.1 Carlito syrichta
R XP_008070486.1 Carlito syrichta
R XP_008070482.1 Carlito syrichta
R XP_021561720.1 Carlito syrichta
R XP_011920046.1 Cercocebus atys
Q XP_030669295.1 Nomascus leucogenys
R XP_058293898.1 Hylobates moloch
R XP_058293899.1 Hylobates moloch
R XP_058293895.1 Hylobates moloch
R XP_058293894.1 Hylobates moloch
R XP_058293897.1 Hylobates moloch
R XP_054520950.2 Pan troglodytes
R XP_054520946.2 Pan troglodytes
R XP_016780802.3 Pan troglodytes
R XP_054520945.2 Pan troglodytes
R XP_063648654.1 Pan troglodytes
- NP_001393454.1 Homo sapiens
- NP_001393469.1 Homo sapiens
- NP_001393475.1 Homo sapiens
- NP_001393476.1 Homo sapiens
R NP_001393459.1 Homo sapiens
R NP_001393465.1 Homo sapiens
R NP_001393472.1 Homo sapiens
R NP_001393468.1 Homo sapiens
R NP_001393473.1 Homo sapiens
R NP_001393446.1 Homo sapiens
R NP_001393467.1 Homo sapiens
R NP_001393463.1 Homo sapiens
R NP_001317507.1 Homo sapiens
R NP_001393453.1 Homo sapiens
R NP_001393449.1 Homo sapiens
- NP_001393466.1 Homo sapiens
R NP_001230111.1 Homo sapiens
R NP_001393455.1 Homo sapiens
R NP_001393452.1 Homo sapiens
R NP_001393470.1 Homo sapiens
R NP_001393442.1 Homo sapiens
R NP_000044.2 Homo sapiens
R NP_001393474.1 Homo sapiens
R NP_001393443.1 Homo sapiens
R NP_001317508.1 Homo sapiens
R NP_001393477.1 Homo sapiens
R NP_001005918.1 Homo sapiens
R NP_001393448.1 Homo sapiens
R NP_001393444.1 Homo sapiens
- NP_001393464.1 Homo sapiens
R XP_024086846.3 Pongo abelii
R XP_054385033.2 Pongo abelii
R XP_054302291.2 Pongo pygmaeus
R XP_063506961.1 Pongo pygmaeus
R XP_054302295.2 Pongo pygmaeus
R XP_054302292.2 Pongo pygmaeus
R XP_018895400.1 Gorilla gorilla gorilla
R XP_018895395.3 Gorilla gorilla gorilla
R XP_018895399.3 Gorilla gorilla gorilla
R XP_018895397.3 Gorilla gorilla gorilla
- XP_055215870.2 Gorilla gorilla gorilla
R XP_018895398.3 Gorilla gorilla gorilla
R XP_055215868.2 Gorilla gorilla gorilla
R XP_004054587.3 Gorilla gorilla gorilla
R XP_008960332.4 Pan paniscus
R XP_008960333.4 Pan paniscus
R XP_054952782.2 Pan paniscus
R XP_024781039.4 Pan paniscus
R XP_063451845.1 Pan paniscus
R XP_063648656.1 Pan troglodytes
R XP_016780798.3 Pan troglodytes
- XP_054520944.2 Pan troglodytes
R XP_016780791.3 Pan troglodytes
R XP_063648645.1 Pan troglodytes
- XP_016780801.3 Pan troglodytes
R XP_016780797.3 Pan troglodytes
- XP_054520943.2 Pan troglodytes
R XP_054520941.2 Pan troglodytes
R XP_016780799.3 Pan troglodytes
R XP_054520940.2 Pan troglodytes
- XP_054520949.2 Pan troglodytes
R XP_054520939.2 Pan troglodytes
R XP_016780796.3 Pan troglodytes
- XP_054520942.2 Pan troglodytes
- XP_054520951.2 Pan troglodytes
- XP_054520947.2 Pan troglodytes
- XP_054520948.2 Pan troglodytes
R XP_063648641.1 Pan troglodytes
R XP_016780795.3 Pan troglodytes
R XP_063648640.1 Pan troglodytes
R XP_063648648.1 Pan troglodytes
R XP_063648643.1 Pan troglodytes
R XP_063648647.1 Pan troglodytes
- XP_063648653.1 Pan troglodytes
R XP_063648652.1 Pan troglodytes
R XP_063648646.1 Pan troglodytes
R XP_063648638.1 Pan troglodytes
- XP_063648649.1 Pan troglodytes
R XP_072870464.1 Chlorocebus sabaeus
R XP_037842590.2 Chlorocebus sabaeus
R XP_037842588.2 Chlorocebus sabaeus
R XP_050622211.1 Macaca thibetana thibetana
R XP_050622212.1 Macaca thibetana thibetana
R XP_050622214.1 Macaca thibetana thibetana
R XP_011754956.2 Macaca nemestrina
R XP_011754959.2 Macaca nemestrina
R XP_011754960.2 Macaca nemestrina
R XP_011754963.2 Macaca nemestrina
R XP_025220045.1 Theropithecus gelada
R XP_025220040.1 Theropithecus gelada
R XP_025220042.1 Theropithecus gelada
R XP_025220044.1 Theropithecus gelada
- XP_025220041.1 Theropithecus gelada
R XP_025220038.1 Theropithecus gelada
R XP_025220043.1 Theropithecus gelada
R XP_017806754.3 Papio anubis
R XP_017806752.3 Papio anubis
R XP_021785336.2 Papio anubis
R XP_021785339.1 Papio anubis
R XP_031511724.1 Papio anubis
R XP_021785340.1 Papio anubis
R XP_014976600.3 Macaca mulatta
R XP_014976599.3 Macaca mulatta
R XP_077829965.1 Macaca mulatta
R XP_077829964.1 Macaca mulatta
R XP_028693404.2 Macaca mulatta
R XP_077829967.1 Macaca mulatta
R XP_077829968.1 Macaca mulatta
R XP_014976601.3 Macaca mulatta
R XP_077829966.1 Macaca mulatta
R XP_011844139.1 Mandrillus leucophaeus
R XP_011844138.1 Mandrillus leucophaeus
- XP_011844136.1 Mandrillus leucophaeus
R XP_011844134.1 Mandrillus leucophaeus
R XP_011844135.1 Mandrillus leucophaeus
R XP_011844137.1 Mandrillus leucophaeus
R XP_073878190.1 Macaca fascicularis
R XP_073878186.1 Macaca fascicularis
R XP_073878192.1 Macaca fascicularis
R XP_065389341.1 Macaca fascicularis
R XP_073878182.1 Macaca fascicularis
R XP_065389345.1 Macaca fascicularis
- XP_065389352.1 Macaca fascicularis
R XP_065389351.1 Macaca fascicularis
R XP_073878180.1 Macaca fascicularis
R XP_065389349.1 Macaca fascicularis
- XP_065389350.1 Macaca fascicularis
R XP_065389342.1 Macaca fascicularis
- XP_065389348.1 Macaca fascicularis
- XP_065389344.1 Macaca fascicularis
R XP_065389340.1 Macaca fascicularis
R XP_045233104.2 Macaca fascicularis
- XP_073878193.1 Macaca fascicularis
R XP_033033524.1 Trachypithecus francoisi
R XP_033033526.1 Trachypithecus francoisi
R XP_023043183.1 Piliocolobus tephrosceles
R XP_011794363.1 Colobus angolensis palliatus
R XP_011794355.1 Colobus angolensis palliatus
- XP_011794340.1 Colobus angolensis palliatus
R XP_011794322.1 Colobus angolensis palliatus
R XP_011794331.1 Colobus angolensis palliatus
R XP_011794349.1 Colobus angolensis palliatus
R XP_010351222.1 Rhinopithecus roxellana
R XP_017713761.1 Rhinopithecus bieti
R XP_017713762.1 Rhinopithecus bieti
R XP_017713763.1 Rhinopithecus bieti
R XP_078208662.1 Callithrix jacchus
R XP_078208642.1 Callithrix jacchus
R XP_078208620.1 Callithrix jacchus
R XP_035153336.2 Callithrix jacchus
R XP_035153347.2 Callithrix jacchus
R XP_078208602.1 Callithrix jacchus
R XP_078208570.1 Callithrix jacchus
R XP_035153372.2 Callithrix jacchus
R XP_078208546.1 Callithrix jacchus
R XP_035153316.2 Callithrix jacchus
R XP_035153352.2 Callithrix jacchus
R XP_078208309.1 Callithrix jacchus
R XP_003927227.1 Saimiri boliviensis
R XP_074243757.1 Saimiri boliviensis
R XP_012321637.1 Aotus nancymaae
R XP_032150436.1 Sapajus apella
R XP_032150437.1 Sapajus apella
R XP_017397951.1 Cebus imitator
R XP_017397952.1 Cebus imitator
R XP_032150438.1 Sapajus apella
R XP_032150439.1 Sapajus apella
R XP_017397953.1 Cebus imitator
R XP_017397954.1 Cebus imitator

(True,
 969,
 'R',
 R    181
 -     27
 Q      1
 Name: count, dtype: int64)

In [26]:
get_alleles('F8', translation['NM_000132.4'], 2038, True)

     Gene: F8
    Human: 2038 N
Alignment: 2056 N
N    67
-    22
K    11
S     5
H     4
G     1
Name: count, dtype: int64

N XP_003943974.1 Saimiri boliviensis
N XP_074247980.1 Saimiri boliviensis
N XP_074247981.1 Saimiri boliviensis
S XP_078219843.1 Callithrix jacchus
S XP_078219845.1 Callithrix jacchus
S XP_035144731.3 Callithrix jacchus
S XP_054106981.2 Callithrix jacchus
S XP_078219844.1 Callithrix jacchus
N XP_064227602.1 Aotus nancymaae
N XP_064227600.1 Aotus nancymaae
N XP_064227599.1 Aotus nancymaae
N XP_064227601.1 Aotus nancymaae
- XP_064227603.1 Aotus nancymaae
N XP_017376032.2 Cebus imitator
N XP_032121193.1 Sapajus apella
N XP_032121192.1 Sapajus apella
N XP_032121190.1 Sapajus apella
N XP_032121191.1 Sapajus apella
- XP_030662513.1 Nomascus leucogenys
- XP_055125146.1 Symphalangus syndactylus
- XP_055125144.1 Symphalangus syndactylus
- XP_055125145.1 Symphalangus syndactylus
N XP_063559080.1 Gorilla gorilla gorilla
N XP_003279379.1 Nomascus leucogenys
N XP_058297352.1 Hylobates moloch
N XP_055125143.1 Symphalangus syndactylus
N XP_063490715.1 Symphalangus syndactylus
- NP_063916.1 Homo sapiens
N NP_000123.1 Homo sapiens
N XP_003810005.2 Pan paniscus
N XP_063660765.1 Pan troglodytes
N XP_063660764.1 Pan troglodytes
N XP_003317837.1 Pan troglodytes
N XP_016800114.1 Pan troglodytes
N XP_016800113.1 Pan troglodytes
N XP_009438145.1 Pan troglodytes
N XP_016800116.1 Pan troglodytes
- XP_054532326.1 Pan troglodytes
N XP_004065205.1 Gorilla gorilla gorilla
N XP_063559079.1 Gorilla gorilla gorilla
- XP_030861623.1 Gorilla gorilla gorilla
- XP_063559081.1 Gorilla gorilla gorilla
N XP_031516315.1 Papio anubis
N XP_024096329.1 Pongo abelii
N XP_054327961.1 Pongo pygmaeus
N XP_054327960.1 Pongo pygmaeus
- XP_025227753.1 Theropithecus gelada
N XP_054327962.1 Pongo pygmaeus
- XP_063516080.1 Pongo pygmaeus
- XP_054327963.1 Pongo pygmaeus
N XP_033057806.1 Trachypithecus francoisi
N XP_077845133.1 Macaca mulatta
N XP_011889285.1 Cercocebus atys
N XP_011889280.1 Cercocebus atys
N XP_011889281.1 Cercocebus atys
N XP_011889284.1 Cercocebus atys
N XP_011889283.1 Cercocebus atys
N XP_050631367.1 Macaca thibetana thibetana
N XP_050631366.1 Macaca thibetana thibetana
N XP_050631365.1 Macaca thibetana thibetana
N XP_045239765.2 Macaca fascicularis
N XP_045239766.2 Macaca fascicularis
N XP_005595091.3 Macaca fascicularis
N XP_077845130.1 Macaca mulatta
N XP_077845132.1 Macaca mulatta
N XP_077845131.1 Macaca mulatta
N XP_077845129.1 Macaca mulatta
N XP_077845128.1 Macaca mulatta
N XP_014984059.2 Macaca mulatta
H XP_011716756.2 Macaca nemestrina
H XP_011716755.2 Macaca nemestrina
H XP_011716754.2 Macaca nemestrina
N XP_025227752.1 Theropithecus gelada
N XP_031516314.1 Papio anubis
N XP_031516316.1 Papio anubis
N XP_011818598.1 Colobus angolensis palliatus
- XP_026307119.1 Piliocolobus tephrosceles
N XP_010351146.1 Rhinopithecus roxellana
N XP_072869377.1 Chlorocebus sabaeus
N XP_072869373.1 Chlorocebus sabaeus
N XP_072869375.1 Chlorocebus sabaeus
N XP_072869374.1 Chlorocebus sabaeus
N XP_010351139.1 Rhinopithecus roxellana
N XP_010351142.1 Rhinopithecus roxellana
N XP_010351130.1 Rhinopithecus roxellana
- XP_030789544.1 Rhinopithecus roxellana
- XP_030789545.1 Rhinopithecus roxellana
N XP_072869376.1 Chlorocebus sabaeus
- XP_077845134.1 Macaca mulatta
N XP_028698332.1 Macaca mulatta
- XP_077845136.1 Macaca mulatta
- XP_072869379.1 Chlorocebus sabaeus
G XP_070944606.1 Macaca nemestrina
- XP_005595097.1 Macaca fascicularis
- XP_072869378.1 Chlorocebus sabaeus
N XP_045239768.1 Macaca fascicularis
H XP_011716757.2 Macaca nemestrina
- XP_011889288.1 Cercocebus atys
K XP_003802782.1 Otolemur garnettii
K XP_053435824.1 Nycticebus coucang
K XP_053435825.1 Nycticebus coucang
K XP_053435826.1 Nycticebus coucang
K XP_012517042.1 Propithecus coquereli
K XP_075855879.1 Microcebus murinus
K XP_045394744.1 Lemur catta
K XP_069319345.1 Eulemur rufifrons
K XP_069319346.1 Eulemur rufifrons
K XP_069319344.1 Eulemur rufifrons
K XP_069319343.1 Eulemur rufifrons
- XP_069319347.1 Eulemur rufifrons

(True,
 2038,
 'N',
 N    67
 -    22
 K    11
 S     5
 H     4
 G     1
 Name: count, dtype: int64)

In [27]:
translation['NM_000157.4']

'NP_000148.2'

In [30]:
get_alleles('GALT', translation['NM_000155.4'], 23, True)

     Gene: GALT
    Human: 23 T
Alignment: 71 T
T    56
-    33
S     5
A     4
G     1
Name: count, dtype: int64

S XP_047286067.1 Homo sapiens
S XP_011533240.1 Homo sapiens
S XP_011533238.1 Homo sapiens
S NP_919299.3 Homo sapiens
S XP_006719831.1 Homo sapiens
T XP_008068994.1 Carlito syrichta
- XP_023059055.1 Piliocolobus tephrosceles
- XP_033094123.1 Trachypithecus francoisi
- XP_017747549.1 Rhinopithecus bieti
- XP_073873355.1 Macaca fascicularis
- XP_070934053.1 Macaca nemestrina
T XP_033094120.1 Trachypithecus francoisi
- XP_033094121.1 Trachypithecus francoisi
- XP_011805905.1 Colobus angolensis palliatus
T XP_009186860.2 Papio anubis
T XP_017747545.1 Rhinopithecus bieti
- XP_023059054.1 Piliocolobus tephrosceles
T XP_011805904.1 Colobus angolensis palliatus
T XP_011835461.1 Mandrillus leucophaeus
T XP_011924618.1 Cercocebus atys
T XP_023059053.1 Piliocolobus tephrosceles
- XP_014973013.1 Macaca mulatta
- XP_073873354.1 Macaca fascicularis
- XP_073873351.1 Macaca fascicularis
- XP_028690928.1 Macaca mulatta
T XP_028690927.1 Macaca mulatta
T XP_073873350.1 Macaca fascicularis
- NP_001245261.1 Homo sapiens
- XP_063465890.1 Symphalangus syndactylus
- XP_055207613.1 Gorilla gorilla gorilla
- XP_063644719.1 Pan troglodytes
- XP_057159138.1 Pan paniscus
T XP_011924615.1 Cercocebus atys
G XP_011924616.1 Cercocebus atys
A XP_011924617.1 Cercocebus atys
T XP_012625552.1 Microcebus murinus
T XP_075864929.1 Microcebus murinus
T XP_012512299.1 Propithecus coquereli
- XP_012512307.1 Propithecus coquereli
T XP_045418889.1 Lemur catta
T XP_069330487.1 Eulemur rufifrons
- XP_045418888.1 Lemur catta
T XP_045418886.1 Lemur catta
T XP_045418885.1 Lemur catta
T XP_045418884.1 Lemur catta
- XP_053425969.1 Nycticebus coucang
A XP_053425960.1 Nycticebus coucang
A XP_053425949.1 Nycticebus coucang
A XP_003800307.1 Otolemur garnettii
- XP_023375102.1 Otolemur garnettii
T XP_063506265.1 Pongo pygmaeus
T XP_063644718.1 Pan troglodytes
T XP_054514788.1 Pan troglodytes
- XP_057159136.1 Pan paniscus
- XP_063552339.1 Gorilla gorilla gorilla
T XP_063552338.1 Gorilla gorilla gorilla
T XP_063552337.1 Gorilla gorilla gorilla
T XP_057159135.1 Pan paniscus
T XP_057159134.1 Pan paniscus
T XP_057159133.1 Pan paniscus
T XP_054376965.2 Pongo abelii
T XP_063570026.1 Pongo abelii
T XP_054376964.2 Pongo abelii
T XP_003263433.1 Nomascus leucogenys
T NP_000146.2 Homo sapiens
- XP_034823262.1 Pan paniscus
T XP_001163419.2 Pan troglodytes
T XP_004048011.1 Gorilla gorilla gorilla
T XP_055207611.1 Gorilla gorilla gorilla
T XP_063450500.1 Pan paniscus
T XP_063450498.1 Pan paniscus
T XP_003829858.2 Pan paniscus
T XP_063506264.1 Pongo pygmaeus
T XP_054358709.1 Pongo pygmaeus
- XP_054358710.1 Pongo pygmaeus
- XP_055149893.1 Symphalangus syndactylus
T XP_032019924.1 Hylobates moloch
T XP_055149891.1 Symphalangus syndactylus
T XP_012318674.1 Aotus nancymaae
- XP_012318675.1 Aotus nancymaae
- XP_032155759.1 Sapajus apella
- XP_010330020.1 Saimiri boliviensis
T XP_010330018.1 Saimiri boliviensis
T XP_010330019.1 Saimiri boliviensis
T XP_032155758.1 Sapajus apella
T XP_037599581.1 Cebus imitator
T XP_017398495.1 Cebus imitator
T XP_003732050.1 Callithrix jacchus
T XP_008996942.1 Callithrix jacchus
- XP_008996946.1 Callithrix jacchus
- XP_078227234.1 Callithrix jacchus
- XP_021783110.1 Papio anubis
T XP_011924614.1 Cercocebus atys
T XP_077822063.1 Macaca mulatta
T XP_021783112.2 Papio anubis
T XP_050616753.1 Macaca thibetana thibetana
T XP_025214557.1 Theropithecus gelada
T XP_021783108.2 Papio anubis
- XP_021783109.2 Papio anubis

(True,
 23,
 'T',
 T    56
 -    33
 S     5
 A     4
 G     1
 Name: count, dtype: int64)

In [32]:
translation['NM_000527.4']

'NP_000518.1'

In [33]:
get_alleles('LDLR', translation['NM_000527.4'], 215, True)

     Gene: LDLR
    Human: 215 R
Alignment: 305 R
R    58
-    16
H     9
Name: count, dtype: int64

- NP_001393790.1 Homo sapiens
H XP_021573646.1 Carlito syrichta
R XP_020139390.1 Microcebus murinus
H XP_074240716.1 Saimiri boliviensis
H XP_064237923.1 Aotus nancymaae
H XP_002761791.3 Callithrix jacchus
H XP_039321728.1 Saimiri boliviensis
H XP_032107631.1 Sapajus apella
H XP_037583448.1 Cebus imitator
R XP_063472056.1 Symphalangus syndactylus
R XP_063472057.1 Symphalangus syndactylus
R XP_011884149.1 Cercocebus atys
R XP_030676686.1 Nomascus leucogenys
R XP_032025606.1 Hylobates moloch
- XP_055094495.1 Symphalangus syndactylus
R XP_055094494.1 Symphalangus syndactylus
- XP_055094497.1 Symphalangus syndactylus
R XP_063472058.1 Symphalangus syndactylus
R XP_055094493.1 Symphalangus syndactylus
R XP_055094492.1 Symphalangus syndactylus
R XP_047294787.1 Homo sapiens
- XP_063576006.1 Pongo abelii
R XP_054319927.2 Pongo pygmaeus
R XP_063513896.1 Pongo pygmaeus
R XP_063576005.1 Pongo abelii
- XP_063576007.1 Pongo abelii
- NP_001182729.1 Homo sapiens
R NP_001182728.1 Homo sapiens
- NP_001182732.1 Homo sapiens
R XP_011526312.1 Homo sapiens
R NP_001182727.1 Homo sapiens
R NP_000518.1 Homo sapiens
R XP_018871450.1 Gorilla gorilla gorilla
R XP_018871452.1 Gorilla gorilla gorilla
R XP_034800281.1 Pan paniscus
- XP_034800282.1 Pan paniscus
R XP_063657276.1 Pan troglodytes
R XP_024206934.1 Pan troglodytes
R XP_024206933.1 Pan troglodytes
R XP_031790584.1 Piliocolobus tephrosceles
R XP_011810343.1 Colobus angolensis palliatus
R XP_077831915.1 Macaca mulatta
R XP_077831886.1 Macaca mulatta
R XP_077831924.1 Macaca mulatta
R XP_077831887.1 Macaca mulatta
R XP_077831923.1 Macaca mulatta
R XP_033056644.1 Trachypithecus francoisi
R XP_017724974.1 Rhinopithecus bieti
R XP_030791739.1 Rhinopithecus roxellana
- XP_011850155.1 Mandrillus leucophaeus
- XP_011850148.1 Mandrillus leucophaeus
- XP_025222242.1 Theropithecus gelada
- XP_025222241.1 Theropithecus gelada
R XP_072873051.1 Chlorocebus sabaeus
R XP_031515756.1 Papio anubis
R XP_025222240.1 Theropithecus gelada
R XP_025222239.1 Theropithecus gelada
R XP_025222238.1 Theropithecus gelada
R XP_011850142.1 Mandrillus leucophaeus
R XP_011850140.1 Mandrillus leucophaeus
R XP_011850139.1 Mandrillus leucophaeus
R XP_070942884.1 Macaca nemestrina
R XP_070942885.1 Macaca nemestrina
R XP_077831917.1 Macaca mulatta
R NP_001028078.1 Macaca mulatta
R XP_077831910.1 Macaca mulatta
R XP_014978386.3 Macaca mulatta
- XP_077831920.1 Macaca mulatta
- XP_073882014.1 Macaca fascicularis
R XP_065391446.1 Macaca fascicularis
R XP_045237058.2 Macaca fascicularis
R XP_045237056.2 Macaca fascicularis
R XP_005588053.3 Macaca fascicularis
R XP_053439240.1 Nycticebus coucang
H XP_012665677.1 Otolemur garnettii
H XP_023373820.1 Otolemur garnettii
R XP_012496802.1 Propithecus coquereli
R XP_045402139.1 Lemur catta
R XP_069334646.1 Eulemur rufifrons
R XP_069334639.1 Eulemur rufifrons
R XP_069334632.1 Eulemur rufifrons
- XP_069334659.1 Eulemur rufifrons
- XP_069334650.1 Eulemur rufifrons

(True,
 215,
 'R',
 R    58
 -    16
 H     9
 Name: count, dtype: int64)

# Validate CPDs

Here we test whether a putative CPD is valid by investigating the vicinity of the sequence, 10 amino acids on either side of the site.

This function pulls out the species and protein IDs showing a particular amino acid at a site.

In [37]:
get_species_with_allele('ATP7B', translation['NM_000053.4'], 969, 'R')

[('Nycticebus coucang', 'XP_053420007.1'),
 ('Nycticebus coucang', 'XP_053420006.1'),
 ('Nycticebus coucang', 'XP_053420005.1'),
 ('Nycticebus coucang', 'XP_053419999.1'),
 ('Nycticebus coucang', 'XP_053420008.1'),
 ('Otolemur garnettii', 'XP_023363838.1'),
 ('Otolemur garnettii', 'XP_012668202.1'),
 ('Otolemur garnettii', 'XP_023363839.1'),
 ('Microcebus murinus', 'XP_012638108.2'),
 ('Microcebus murinus', 'XP_012638109.2'),
 ('Propithecus coquereli', 'XP_012504534.1'),
 ('Propithecus coquereli', 'XP_012504526.1'),
 ('Propithecus coquereli', 'XP_012504533.1'),
 ('Propithecus coquereli', 'XP_012504538.1'),
 ('Lemur catta', 'XP_045423256.1'),
 ('Lemur catta', 'XP_045423253.1'),
 ('Eulemur rufifrons', 'XP_069323794.1'),
 ('Eulemur rufifrons', 'XP_069323793.1'),
 ('Eulemur rufifrons', 'XP_069323796.1'),
 ('Eulemur rufifrons', 'XP_069323797.1'),
 ('Carlito syrichta', 'XP_008070488.1'),
 ('Carlito syrichta', 'XP_008070483.1'),
 ('Carlito syrichta', 'XP_008070485.1'),
 ('Carlito syrichta', 'XP_008070486.1'),
 ('Carlito syrichta', 'XP_008070482.1'),
 ('Carlito syrichta', 'XP_021561720.1'),
 ('Cercocebus atys', 'XP_011920046.1'),
 ('Hylobates moloch', 'XP_058293898.1'),
 ('Hylobates moloch', 'XP_058293899.1'),
 ('Hylobates moloch', 'XP_058293895.1'),
 ('Hylobates moloch', 'XP_058293894.1'),
 ('Hylobates moloch', 'XP_058293897.1'),
 ('Pan troglodytes', 'XP_054520950.2'),
 ('Pan troglodytes', 'XP_054520946.2'),
 ('Pan troglodytes', 'XP_016780802.3'),
 ('Pan troglodytes', 'XP_054520945.2'),
 ('Pan troglodytes', 'XP_063648654.1'),
 ('Homo sapiens', 'NP_001393459.1'),
 ('Homo sapiens', 'NP_001393465.1'),
 ('Homo sapiens', 'NP_001393472.1'),
 ('Homo sapiens', 'NP_001393468.1'),
 ('Homo sapiens', 'NP_001393473.1'),
 ('Homo sapiens', 'NP_001393446.1'),
 ('Homo sapiens', 'NP_001393467.1'),
 ('Homo sapiens', 'NP_001393463.1'),
 ('Homo sapiens', 'NP_001317507.1'),
 ('Homo sapiens', 'NP_001393453.1'),
 ('Homo sapiens', 'NP_001393449.1'),
 ('Homo sapiens', 'NP_001230111.1'),
 ('Homo sapiens', 'NP_001393455.1'),
 ('Homo sapiens', 'NP_001393452.1'),
 ('Homo sapiens', 'NP_001393470.1'),
 ('Homo sapiens', 'NP_001393442.1'),
 ('Homo sapiens', 'NP_000044.2'),
 ('Homo sapiens', 'NP_001393474.1'),
 ('Homo sapiens', 'NP_001393443.1'),
 ('Homo sapiens', 'NP_001317508.1'),
 ('Homo sapiens', 'NP_001393477.1'),
 ('Homo sapiens', 'NP_001005918.1'),
 ('Homo sapiens', 'NP_001393448.1'),
 ('Homo sapiens', 'NP_001393444.1'),
 ('Pongo abelii', 'XP_024086846.3'),
 ('Pongo abelii', 'XP_054385033.2'),
 ('Pongo pygmaeus', 'XP_054302291.2'),
 ('Pongo pygmaeus', 'XP_063506961.1'),
 ('Pongo pygmaeus', 'XP_054302295.2'),
 ('Pongo pygmaeus', 'XP_054302292.2'),
 ('Gorilla gorilla gorilla', 'XP_018895400.1'),
 ('Gorilla gorilla gorilla', 'XP_018895395.3'),
 ('Gorilla gorilla gorilla', 'XP_018895399.3'),
 ('Gorilla gorilla gorilla', 'XP_018895397.3'),
 ('Gorilla gorilla gorilla', 'XP_018895398.3'),
 ('Gorilla gorilla gorilla', 'XP_055215868.2'),
 ('Gorilla gorilla gorilla', 'XP_004054587.3'),
 ('Pan paniscus', 'XP_008960332.4'),
 ('Pan paniscus', 'XP_008960333.4'),
 ('Pan paniscus', 'XP_054952782.2'),
 ('Pan paniscus', 'XP_024781039.4'),
 ('Pan paniscus', 'XP_063451845.1'),
 ('Pan troglodytes', 'XP_063648656.1'),
 ('Pan troglodytes', 'XP_016780798.3'),
 ('Pan troglodytes', 'XP_016780791.3'),
 ('Pan troglodytes', 'XP_063648645.1'),
 ('Pan troglodytes', 'XP_016780797.3'),
 ('Pan troglodytes', 'XP_054520941.2'),
 ('Pan troglodytes', 'XP_016780799.3'),
 ('Pan troglodytes', 'XP_054520940.2'),
 ('Pan troglodytes', 'XP_054520939.2'),
 ('Pan troglodytes', 'XP_016780796.3'),
 ('Pan troglodytes', 'XP_063648641.1'),
 ('Pan troglodytes', 'XP_016780795.3'),
 ('Pan troglodytes', 'XP_063648640.1'),
 ('Pan troglodytes', 'XP_063648648.1'),
 ('Pan troglodytes', 'XP_063648643.1'),
 ('Pan troglodytes', 'XP_063648647.1'),
 ('Pan troglodytes', 'XP_063648652.1'),
 ('Pan troglodytes', 'XP_063648646.1'),
 ('Pan troglodytes', 'XP_063648638.1'),
 ('Chlorocebus sabaeus', 'XP_072870464.1'),
 ('Chlorocebus sabaeus', 'XP_037842590.2'),
 ('Chlorocebus sabaeus', 'XP_037842588.2'),
 ('Macaca thibetana thibetana', 'XP_050622211.1'),
 ('Macaca thibetana thibetana', 'XP_050622212.1'),
 ('Macaca thibetana thibetana', 'XP_050622214.1'),
 ('Macaca nemestrina', 'XP_011754956.2'),
 ('Macaca nemestrina', 'XP_011754959.2'),
 ('Macaca nemestrina', 'XP_011754960.2'),
 ('Macaca nemestrina', 'XP_011754963.2'),
 ('Theropithecus gelada', 'XP_025220045.1'),
 ('Theropithecus gelada', 'XP_025220040.1'),
 ('Theropithecus gelada', 'XP_025220042.1'),
 ('Theropithecus gelada', 'XP_025220044.1'),
 ('Theropithecus gelada', 'XP_025220038.1'),
 ('Theropithecus gelada', 'XP_025220043.1'),
 ('Papio anubis', 'XP_017806754.3'),
 ('Papio anubis', 'XP_017806752.3'),
 ('Papio anubis', 'XP_021785336.2'),
 ('Papio anubis', 'XP_021785339.1'),
 ('Papio anubis', 'XP_031511724.1'),
 ('Papio anubis', 'XP_021785340.1'),
 ('Macaca mulatta', 'XP_014976600.3'),
 ('Macaca mulatta', 'XP_014976599.3'),
 ('Macaca mulatta', 'XP_077829965.1'),
 ('Macaca mulatta', 'XP_077829964.1'),
 ('Macaca mulatta', 'XP_028693404.2'),
 ('Macaca mulatta', 'XP_077829967.1'),
 ('Macaca mulatta', 'XP_077829968.1'),
 ('Macaca mulatta', 'XP_014976601.3'),
 ('Macaca mulatta', 'XP_077829966.1'),
 ('Mandrillus leucophaeus', 'XP_011844139.1'),
 ('Mandrillus leucophaeus', 'XP_011844138.1'),
 ('Mandrillus leucophaeus', 'XP_011844134.1'),
 ('Mandrillus leucophaeus', 'XP_011844135.1'),
 ('Mandrillus leucophaeus', 'XP_011844137.1'),
 ('Macaca fascicularis', 'XP_073878190.1'),
 ('Macaca fascicularis', 'XP_073878186.1'),
 ('Macaca fascicularis', 'XP_073878192.1'),
 ('Macaca fascicularis', 'XP_065389341.1'),
 ('Macaca fascicularis', 'XP_073878182.1'),
 ('Macaca fascicularis', 'XP_065389345.1'),
 ('Macaca fascicularis', 'XP_065389351.1'),
 ('Macaca fascicularis', 'XP_073878180.1'),
 ('Macaca fascicularis', 'XP_065389349.1'),
 ('Macaca fascicularis', 'XP_065389342.1'),
 ('Macaca fascicularis', 'XP_065389340.1'),
 ('Macaca fascicularis', 'XP_045233104.2'),
 ('Trachypithecus francoisi', 'XP_033033524.1'),
 ('Trachypithecus francoisi', 'XP_033033526.1'),
 ('Piliocolobus tephrosceles', 'XP_023043183.1'),
 ('Colobus angolensis palliatus', 'XP_011794363.1'),
 ('Colobus angolensis palliatus', 'XP_011794355.1'),
 ('Colobus angolensis palliatus', 'XP_011794322.1'),
 ('Colobus angolensis palliatus', 'XP_011794331.1'),
 ('Colobus angolensis palliatus', 'XP_011794349.1'),
 ('Rhinopithecus roxellana', 'XP_010351222.1'),
 ('Rhinopithecus bieti', 'XP_017713761.1'),
 ('Rhinopithecus bieti', 'XP_017713762.1'),
 ('Rhinopithecus bieti', 'XP_017713763.1'),
 ('Callithrix jacchus', 'XP_078208662.1'),
 ('Callithrix jacchus', 'XP_078208642.1'),
 ('Callithrix jacchus', 'XP_078208620.1'),
 ('Callithrix jacchus', 'XP_035153336.2'),
 ('Callithrix jacchus', 'XP_035153347.2'),
 ('Callithrix jacchus', 'XP_078208602.1'),
 ('Callithrix jacchus', 'XP_078208570.1'),
 ('Callithrix jacchus', 'XP_035153372.2'),
 ('Callithrix jacchus', 'XP_078208546.1'),
 ('Callithrix jacchus', 'XP_035153316.2'),
 ('Callithrix jacchus', 'XP_035153352.2'),
 ('Callithrix jacchus', 'XP_078208309.1'),
 ('Saimiri boliviensis', 'XP_003927227.1'),
 ('Saimiri boliviensis', 'XP_074243757.1'),
 ('Aotus nancymaae', 'XP_012321637.1'),
 ('Sapajus apella', 'XP_032150436.1'),
 ('Sapajus apella', 'XP_032150437.1'),
 ('Cebus imitator', 'XP_017397951.1'),
 ('Cebus imitator', 'XP_017397952.1'),
 ('Sapajus apella', 'XP_032150438.1'),
 ('Sapajus apella', 'XP_032150439.1'),
 ('Cebus imitator', 'XP_017397953.1'),
 ('Cebus imitator', 'XP_017397954.1')]

In [38]:
get_species_with_allele('GALT', translation['NM_000155.4'], 23, 'A')

[('Cercocebus atys', 'XP_011924617.1'),
 ('Nycticebus coucang', 'XP_053425960.1'),
 ('Nycticebus coucang', 'XP_053425949.1'),
 ('Otolemur garnettii', 'XP_003800307.1')]

This function compares the human and nonhuman sequences in the -10 / +10 range.  The output at the bottom shows the numbers of:

* differences between the sequences
* gaps 
* sites out of range

For example, the GBA1 site at the end means that 9 sites are outside the range.  The GALT sequence shows some aminoacid differences.

In [42]:
local_compare_to_human('GBA', translation['NM_000157.4'], 535, 'XP_005541629.1')
GBA1	NM_000157.4	502	R

UnboundLocalError: cannot access local variable 'nonaln' where it is not associated with a value

In [43]:
local_compare_to_human('GALT', translation['NM_000155.4'], 247, 'NP_000146.2')

UnboundLocalError: cannot access local variable 'nonaln' where it is not associated with a value

This function spits out a site by site comparison of the human and nonhuman sequences.  Only the differences are shown.

In [23]:
global_compare_to_human('GBA', translation['NM_000157.4'], 'XP_005541629.1')

5 S -
6 S -
7 P -
10 E K
16 L S
17 S G
24 G A
67 F L
68 D E
70 P L
94 M T
96 P T
101 H R
213 R H
344 V -
345 L -
346 T -
347 D -
348 P -
349 E -
350 A -
351 A -
352 K -
353 Y -
354 V -
355 H -
356 G -
357 I -
358 A -
359 V -
360 H -
361 W -
362 Y -
363 L -
364 D -
365 F -
366 L -
367 A -
368 P -
369 A -
370 K -
371 A -
372 T -
373 L -
374 G -
375 E -
376 T -
377 H -
378 R -
379 L -
380 F -
381 P -
382 N -
383 T -
384 M -
385 L -
386 F -
387 A -
388 S -
389 E -
390 A -
391 C -
392 V -
393 G -
394 S -
395 K -
396 F -
397 W -
398 E -
399 Q -
401 S -
402 V -
403 R -
404 L -
405 G -
406 S -
407 W -
408 D -
409 R -
410 G -
411 M -
412 Q -
413 Y -
414 S -
415 H -
416 S -
417 I -
418 I -
419 T -
452 I V
496 A T
507 A T
546 R C
547 R L

In [24]:
global_compare_to_human('GALT', translation['NM_000155.4'], 'XP_003800307.1')

23 R C
26 T A
28 P L
29 Q D
30 Q R
39 A I
40 A P
41 A V
43 T A
45 R Q
47 N S
106 I T
115 Q H
118 S A
153 K E
154 S A
177 V M
203 A V
216 A S
248 Q R
251 K Q
256 E V
268 L I
269 R K
289 T V
310 P S
360 E A
363 A D
366 N D
669 H C
671 G R
828 T A

In [25]:
get_species_with_allele('CFTR', translation['NM_000492.4'], 13, 'F')

[('Otolemur garnettii', 'XP_003789873.1')]

In [ ]:
local_compare_to_human('CFTR', translation['NM_000492.4'], 13, 'XP_003789873.1')

-10 P P
-9 L L
-8 E K
-7 K K
-6 A L
-5 S N
-4 V L
-3 V L
-2 - -
-1 - -
0 S F
1 K F
2 L L
3 F Y
4 F F
5 S S
6 W W
7 T T
8 R R
9 P P
10 I I

(7, 0, 0)

In [28]:
translation['NM_000132.3']

'NP_000123.1'

In [29]:
get_species_with_allele('F8', 'NP_000123.1', 2183, 'V')

[('Hylobates moloch', 'XP_032612179.1')]

In [30]:
local_compare_to_human('F8', 'NP_000123.1', 2183, 'XP_003789873.1')

UnboundLocalError: local variable 'nonaln' referenced before assignment