# Find putative CPDs

## Rerun clean up commands

Since the ClinVar data was modified we begin by rerun the commands in the [clean_up.ipynb](clean_up.ipynb) notebook.

### Extract transcript IDs from variants

Pull the transcript record IDs from the ClinVar records of each gene.

**Output:** `vartranscripts` dictionary with genes as keys and lists of transcripts as values.  The new `dict` has 68 transcripts instead of 72.

In [1]:
import os
os.getcwd()

'c:\\Users\\adesi\\Documents\\GitHub\\kondrashov'

In [2]:
run kondrashov

#### Step 1

In [3]:
i = 0
vartranscripts = {}
for gene in loci:
    vt = get_transcripts_from_variants(gene, True)
    #i += len(vt)    
    print(gene, vt[0], len(vt), 'transcripts')
    vartranscripts.update({gene: vt})

ABCD1 NM_000033.4 1 transcripts
ALPL NM_000478.6 1 transcripts
AR NM_000044.6 1 transcripts
ATP7B NM_000053.4 1 transcripts
BTK NM_000061.3 1 transcripts
CASR NM_000388.4 1 transcripts
CBS NM_000071.3 1 transcripts
CFTR NC_000007.14:g.117675861C>T 3 transcripts
CYBB NM_000397.4 1 transcripts
F7 NC_000013.11:g.113105748C>G 5 transcripts
F8 NC_000023.11:g.155022771G>A 2 transcripts
F9 NC_000023.11:g.139530731A>T 4 transcripts
G6PD NM_001042351.3 3 transcripts
GALT NM_000155.4 1 transcripts
GBA1 NM_000157.4 1 transcripts
GJB1 NM_000166.6 2 transcripts
HBB NC_000011.10:g.5227098T>A 10 transcripts
HPRT1 NM_000194.2 3 transcripts
IL2RG NM_000206.3 1 transcripts
KCNH2 NM_000238.4 1 transcripts
KCNQ1 NM_000218.3 1 transcripts
L1CAM NM_001278116.2 1 transcripts
LDLR NM_000527.5 2 transcripts
MPZ NM_000530.8 1 transcripts
MYH7 NM_000257.4 1 transcripts
TYR NM_000372.5 1 transcripts
PAH NM_000277.3 1 transcripts
PMM2 NC_000016.10:g.8797716G>T 2 transcripts
RHO NM_000539.3 1 transcripts
TP53 NM_000546.6 1 transcripts
TTR NM_000371.4 1 transcripts
VWF NM_000552.5 1 transcripts

In [9]:
vartranscripts

{'ABCD1': ['NM_000033.4'],
 'ALPL': ['NM_000478.6'],
 'AR': ['NM_000044.6'],
 'ATP7B': ['NM_000053.4'],
 'BTK': ['NM_000061.3'],
 'CASR': ['NM_000388.4'],
 'CBS': ['NM_000071.3'],
 'CFTR': ['NC_000007.14:g.117675861C>T', 'NM_000492.4', 'NM_000492.3'],
 'CYBB': ['NM_000397.4'],
 'F7': ['NM_000131.5',
  'NM_019616.4',
  'NC_000013.11:g.113105784G>A',
  'NC_000013.11:g.113105748C>G',
  'NM_000131.4'],
 'F8': ['NC_000023.11:g.155022771G>A', 'NM_000132.4'],
 'F9': ['NC_000023.11:g.139530731A>T',
  'NC_000023.11:g.139530716T>A',
  'NC_000023.11:g.139530710G>C',
  'NM_000133.4'],
 'G6PD': ['NM_001042351.3', 'NM_000402.4', 'NM_001360016.2'],
 'GALT': ['NM_000155.4'],
 'GBA1': ['NM_000157.4'],
 'GJB1': ['NM_000166.6', 'NM_001097642.3'],
 'HBB': ['NC_000011.10:g.5227147G>T',
  'NC_000011.10:g.5227100T>C',
  'NM_000518.4',
  'NC_000011.10:g.5227172G>A',
  'NC_000011.10:g.5227096C>A',
  'NC_000011.10:g.5227098T>A',
  'NC_000011.10:g.5227101A>C',
  'NC_000011.10:g.5227097T>G',
  'NM_000518.5',
  'NC_000011.10:g.5227159G>A'],
 'HPRT1': ['NM_000194.3', 'NM_000194.2', 'HPRT CHERMSIDE'],
 'IL2RG': ['NM_000206.3'],
 'KCNH2': ['NM_000238.4'],
 'KCNQ1': ['NM_000218.3'],
 'L1CAM': ['NM_001278116.2'],
 'LDLR': ['NM_000527.4', 'NM_000527.5'],
 'MPZ': ['NM_000530.8'],
 'MYH7': ['NM_000257.4'],
 'TYR': ['NM_000372.5'],
 'PAH': ['NM_000277.3'],
 'PMM2': ['NM_000303.3', 'NC_000016.10:g.8797716G>T'],
 'RHO': ['NM_000539.3'],
 'TP53': ['NM_000546.6'],
 'TTR': ['NM_000371.4'],
 'VWF': ['NM_000552.5']}

In [4]:
vartranscripts_filtered = {
    gene: [v for v in values if v.startswith("NM_")]
    for gene, values in vartranscripts.items()
}
vartranscripts_filtered

{'ABCD1': ['NM_000033.4'],
 'ALPL': ['NM_000478.6'],
 'AR': ['NM_000044.6'],
 'ATP7B': ['NM_000053.4'],
 'BTK': ['NM_000061.3'],
 'CASR': ['NM_000388.4'],
 'CBS': ['NM_000071.3'],
 'CFTR': ['NM_000492.3', 'NM_000492.4'],
 'CYBB': ['NM_000397.4'],
 'F7': ['NM_000131.4', 'NM_000131.5', 'NM_019616.4'],
 'F8': ['NM_000132.4'],
 'F9': ['NM_000133.4'],
 'G6PD': ['NM_001042351.3', 'NM_001360016.2', 'NM_000402.4'],
 'GALT': ['NM_000155.4'],
 'GBA1': ['NM_000157.4'],
 'GJB1': ['NM_000166.6', 'NM_001097642.3'],
 'HBB': ['NM_000518.5', 'NM_000518.4'],
 'HPRT1': ['NM_000194.2', 'NM_000194.3'],
 'IL2RG': ['NM_000206.3'],
 'KCNH2': ['NM_000238.4'],
 'KCNQ1': ['NM_000218.3'],
 'L1CAM': ['NM_001278116.2'],
 'LDLR': ['NM_000527.5', 'NM_000527.4'],
 'MPZ': ['NM_000530.8'],
 'MYH7': ['NM_000257.4'],
 'TYR': ['NM_000372.5'],
 'PAH': ['NM_000277.3'],
 'PMM2': ['NM_000303.3'],
 'RHO': ['NM_000539.3'],
 'TP53': ['NM_000546.6'],
 'TTR': ['NM_000371.4'],
 'VWF': ['NM_000552.5']}

### Step 2
##### Extract human protein sequence records from the fasta files

Take the fasta files containing ortholog sequences, search for human sequences and extract the corresponding record.

**Output:** `protrecs` dictionary with genes as keys and lists of protein records as values. Unchanged.

In [11]:
import os
os.listdir('fasta_match')

['ABCD1_NP_000024.2_match.fasta',
 'ABCD1_NP_000024.2_match_1.fasta',
 'ALPL_NP_000469.3_match.fasta',
 'AR_NP_000035.2_match.fasta',
 'ATP7B_NP_000044.2_match.fasta',
 'BTK_NP_000052.1_match.fasta',
 'CASR_NP_000379.3_match.fasta',
 'CBS_NP_000062.1_match.fasta',
 'CFTR_NP_000483.3_match.fasta',
 'CYBB_NP_000388.2_match.fasta',
 'F7_NP_000122.1_match.fasta',
 'F7_NP_062562.1_match.fasta',
 'F8_NP_000123.1_match.fasta',
 'F9_NP_000124.1_match.fasta',
 'G6PD_NP_000393.4_match.fasta',
 'G6PD_NP_001035810.1_match.fasta',
 'G6PD_NP_001346945.1_match.fasta',
 'GALT_NP_000146.2_match.fasta',
 'GBA1_NP_000148.2_match.fasta',
 'GJB1_NP_000157.1_match.fasta',
 'GJB1_NP_001091111.1_match.fasta',
 'HBB_NP_000509.1_match.fasta',
 'HPRT1_NP_000185.1_match.fasta',
 'IL2RG_NP_000197.1_match.fasta',
 'KCNH2_NP_000229.1_match.fasta',
 'KCNQ1_NP_000209.2_match.fasta',
 'L1CAM_NP_001265045.1_match.fasta',
 'LDLR_NP_000518.1_match.fasta',
 'MPZ_NP_000521.2_match.fasta',
 'MYH7_NP_000248.2_match.fasta',
 'PAH_NP_000268.1_match.fasta',
 'PMM2_NP_000294.1_match.fasta',
 'RHO_NP_000530.1_match.fasta',
 'TP53_NP_000537.3_match.fasta',
 'TTR_NP_000362.1_match.fasta',
 'TYR_NP_000363.1_match.fasta',
 'VWF_NP_000543.3_match.fasta']

In [ ]:
#loci = ['ABCD1', 'ALPL', 'AR', 'ATP7B']
i = 1
protrecs = {}
for gene in loci:
    protrecs.update({gene: []})
    for record in SeqIO.parse('fasta_match/{gene}.fasta', 'fasta'):
        sp = get_species(record)
        if sp=='Homo sapiens':
            protrecs[gene].append(record)
            print(i, gene, record.id, len(record))
            i += 1

### This code works for fasta_match/ directory which has a different naming scheme

In [5]:
import os
from Bio import SeqIO

protrecs = {}
i = 1
for filename in os.listdir("fasta_match"):
    if not filename.endswith(".fasta"):
        continue
    gene = filename.split("_")[0]
    protrecs.setdefault(gene, [])
    filepath = os.path.join("fasta_match", filename)

    for record in SeqIO.parse(filepath, "fasta"):
        if get_species(record) == "Homo sapiens":
            protrecs[gene].append(record)
            print(i, gene, record.id, len(record))
            i += 1

1 ABCD1 NP_000024.2 745
2 ABCD1 NP_000024.2 745
3 ALPL NP_000469.3 524
4 AR NP_000035.2 920
5 ATP7B NP_000044.2 1465
6 BTK NP_000052.1 659
7 CASR NP_000379.3 1078
8 CBS NP_000062.1 551
9 CFTR NP_000483.3 1480
10 CYBB NP_000388.2 570
11 F7 NP_000122.1 466
12 F7 NP_062562.1 444
13 F8 NP_000123.1 2351
14 F9 NP_000124.1 461
15 G6PD NP_000393.4 545
16 G6PD NP_001035810.1 515
17 G6PD NP_001035810.1 515
18 GALT NP_000146.2 379
19 GBA1 NP_000148.2 536
20 GJB1 NP_000157.1 283
21 GJB1 NP_000157.1 283
22 HBB NP_000509.1 147
23 HPRT1 NP_000185.1 218
24 IL2RG NP_000197.1 369
25 KCNH2 NP_000229.1 1159
26 KCNQ1 NP_000209.2 676
27 L1CAM NP_000416.1 1257
28 LDLR NP_000518.1 860
29 MPZ NP_000521.2 248
30 MYH7 NP_000248.2 1935
31 PAH NP_000268.1 452
32 PMM2 NP_000294.1 246
33 RHO NP_000530.1 348
34 TP53 NP_000537.3 393
35 TTR NP_000362.1 147
36 TYR NP_000363.1 529
37 VWF NP_000543.3 2813

### STEP 3 
##### Match variant transcript IDs with ortholog proteins

Take variant transcript ID, query the NCBI database, extract the corresponding protein, and look for it in the ortholog set.  Flag problems.

**Output:** `translation` dictionary with transcript IDs as keys and lists of protein IDs as values.

In [6]:
#%%time
translation = {}
i = 1
for gene in loci:
    for transcript in vartranscripts_filtered[gene]:
        if transcript[:3] == 'NM_':
            rec = get_transcript(transcript)
            seq = get_CDS(rec)
            match = False
            for prot in protrecs[gene]: 
                if seq[4] == prot.seq:
                    print(i, gene, transcript, prot.id)
                    match = True
                    translation.update({transcript: prot.id})
            if not match:
                print(i, gene, transcript, 'no matching protein         <<<<<')
        else:
            print(i, gene, transcript, 'invalid transcript name         *****')
        i += 1

1 ABCD1 NM_000033.4 NP_000024.2
1 ABCD1 NM_000033.4 NP_000024.2
2 ALPL NM_000478.6 NP_000469.3
3 AR NM_000044.6 NP_000035.2
4 ATP7B NM_000053.4 NP_000044.2
5 BTK NM_000061.3 NP_000052.1
6 CASR NM_000388.4 NP_000379.3
7 CBS NM_000071.3 NP_000062.1
8 CFTR NM_000492.3 NP_000483.3
9 CFTR NM_000492.4 NP_000483.3
10 CYBB NM_000397.4 NP_000388.2
11 F7 NM_000131.4 NP_000122.1
12 F7 NM_000131.5 NP_000122.1
13 F7 NM_019616.4 NP_062562.1
14 F8 NM_000132.4 NP_000123.1
15 F9 NM_000133.4 NP_000124.1
16 G6PD NM_001042351.3 NP_001035810.1
16 G6PD NM_001042351.3 NP_001035810.1
17 G6PD NM_001360016.2 NP_001035810.1
17 G6PD NM_001360016.2 NP_001035810.1
18 G6PD NM_000402.4 NP_000393.4
19 GALT NM_000155.4 NP_000146.2
20 GBA1 NM_000157.4 NP_000148.2
21 GJB1 NM_000166.6 NP_000157.1
21 GJB1 NM_000166.6 NP_000157.1
22 GJB1 NM_001097642.3 NP_000157.1
22 GJB1 NM_001097642.3 NP_000157.1
23 HBB NM_000518.5 NP_000509.1
24 HBB NM_000518.4 NP_000509.1
25 HPRT1 NM_000194.2 NP_000185.1
26 HPRT1 NM_000194.3 NP_000185.1
27 IL2RG NM_000206.3 NP_000197.1
28 KCNH2 NM_000238.4 NP_000229.1
29 KCNQ1 NM_000218.3 NP_000209.2
30 L1CAM NM_001278116.2 NP_000416.1
31 LDLR NM_000527.5 NP_000518.1
32 LDLR NM_000527.4 NP_000518.1
33 MPZ NM_000530.8 NP_000521.2
34 MYH7 NM_000257.4 NP_000248.2
35 TYR NM_000372.5 NP_000363.1
36 PAH NM_000277.3 NP_000268.1
37 PMM2 NM_000303.3 NP_000294.1
38 RHO NM_000539.3 NP_000530.1
39 TP53 NM_000546.6 NP_000537.3
40 TTR NM_000371.4 NP_000362.1
41 VWF NM_000552.5 NP_000543.3

## clean up variants not matching any protein
* HBB 
* G6PD
#### Clean up is required only once

In [ ]:
vardata = pd.read_csv('pathogenic/HBB.csv')
i = vardata['Name'].tolist().index('Hb Little Rock')
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

In [10]:
vardata.loc[i, 'Name'] = 'NM_000518.5(HBB):c.432C>R (p.His144Gln)'
vardata.to_csv('pathogenic/HBB.csv', index=False)
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
40,30404,single nucleotide variant,NM_000518.5(HBB):c.431A>C (p.His144Pro),3043,HBB,HGNC:4827,Pathogenic,1,"Jul 14, 2025",33918338,...,G,-,-,-,-,-,-,SCV001158641,-,-
41,30417,single nucleotide variant,NM_000518.4(HBB):c.320T>A (p.Leu107Gln),3043,HBB,HGNC:4827,Pathogenic,1,"May 20, 2023",33941844,...,T,-,-,-,-,-,-,SCV005329471,-,-
42,30425,single nucleotide variant,NM_000518.5(HBB):c.432C>R (p.His144Gln),3043,HBB,HGNC:4827,Pathogenic,1,"Nov 13, 2020",33954632,...,T,-,-,-,-,-,-,SCV002046407,-,-
43,30429,single nucleotide variant,NM_000518.4(HBB):c.293A>T (p.His98Leu),3043,HBB,HGNC:4827,Likely pathogenic,1,"May 22, 2025",33951978,...,A,-,-,-,-,-,-,SCV005876053,-,-
44,30434,single nucleotide variant,NM_000518.4(HBB):c.440A>C (p.His147Pro),3043,HBB,HGNC:4827,Pathogenic,1,"May 24, 2024",33954264,...,G,-,-,-,-,-,-,SCV006104266,-,-

### G6PD

In [ ]:
vardata = pd.read_csv('pathogenic/G6PD.csv')
i = vardata['Name'].tolist().index('G6PD ZURICH') 
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

In [12]:
vardata.loc[i, 'Name'] = 'NM_001360016.2(G6PD):c.1288-2A>G)'
vardata.to_csv('pathogenic/G6PD.csv', index=False)
vardata[(vardata.index<i+3) & (vardata.index>i-3)]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
40,25455,single nucleotide variant,NM_000402.4(G6PD):c.298T>C (p.Tyr100His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Nov 25, 2024",137852349,...,G,-,-,-,-,-,-,SCV001443096|SCV002599323|SCV003445326|SCV0038...,-,-
41,25456,single nucleotide variant,NM_000402.4(G6PD):c.683G>A (p.Arg228His),2539,G6PD,HGNC:4057,Pathogenic/Likely pathogenic,1,"Jan 02, 2026",137852332,...,T,-,-,-,-,-,-,SCV001142107|SCV002599340|SCV004299714|SCV0050...,-,-
42,25459,single nucleotide variant,NM_001360016.2(G6PD):c.1288-2A>G),2539,G6PD,HGNC:4057,Pathogenic,1,"Aug 12, 2022",2070350038,...,C,-,-,-,-,-,-,SCV002599384,-,-
43,25461,single nucleotide variant,NM_000402.4(G6PD):c.1466G>C (p.Arg489Pro),2539,G6PD,HGNC:4057,Pathogenic,1,"Feb 05, 2024",72554665,...,G,-,-,-,-,-,-,SCV000330997|SCV000914284|SCV001367223|SCV0013...,-,-
44,99398,single nucleotide variant,NM_001360016.2(G6PD):c.1360C>T (p.Arg454Cys),2539,G6PD,HGNC:4057,Pathogenic,1,"Apr 29, 2026",398123546,...,A,-,-,-,-,-,-,SCV000225263|SCV000281545|SCV000603769|SCV0006...,-,-

### STEP 4 (STEP 5 is the correct code)
##### Extract individual variants

Process each ClinVar dataset and extract variants for each transcript.

**Output:** `variants` dictionary with transcript IDs as keys and lists of changes as values.

In [7]:
run kondrashov

In [ ]:
print('gene transcript protein changes errors')
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        #print(transcript)
        sites, wilds, muts, errs = get_all_changes(gene, transcript, True)
        #print(gene, transcript, translation[transcript], len(sites), len(errs))

#### I keep gettng this KeyError: '00='

In [15]:
# I'll do a step-by-step troubleshooting, first view the names 
for gene in loci:
    #transcripts = vartranscripts_filtered[gene]
    #for transcript in transcripts:
    vardata = pd.read_csv("pathogenic/" + gene + ".csv")
    n = len(vardata)
    for i in range(n):
        name = vardata["Name"][i]
        print(name)

NM_000033.4(ABCD1):c.871G>A (p.Glu291Lys)
NM_000033.4(ABCD1):c.1451C>G (p.Pro484Arg)
NM_000033.4(ABCD1):c.1635-2A>G
NM_000033.4(ABCD1):c.1165C>G (p.Arg389Gly)
NM_000033.4(ABCD1):c.443A>G (p.Asn148Ser)
NM_000033.4(ABCD1):c.520T>G (p.Tyr174Asp)
NM_000033.4(ABCD1):c.796G>A (p.Gly266Arg)
NM_000033.4(ABCD1):c.1202G>A (p.Arg401Gln)
NM_000033.4(ABCD1):c.1252C>T (p.Arg418Trp)
NM_000033.4(ABCD1):c.1390C>T (p.Arg464Ter)
NM_000033.4(ABCD1):c.1429G>T (p.Glu477Ter)
NM_000033.4(ABCD1):c.1544C>T (p.Ser515Phe)
NM_000033.4(ABCD1):c.1552C>T (p.Arg518Trp)
NM_000033.4(ABCD1):c.1634+1G>A
NM_000033.4(ABCD1):c.1817C>T (p.Ser606Leu)
NM_000033.4(ABCD1):c.1850G>A (p.Arg617His)
NM_000033.4(ABCD1):c.1849C>T (p.Arg617Cys)
NM_000033.4(ABCD1):c.1865+1G>A
NM_000033.4(ABCD1):c.900G>A (p.Glu300=)
NM_000033.4(ABCD1):c.421G>A (p.Ala141Thr)
NM_000033.4(ABCD1):c.838C>T (p.Arg280Cys)
NM_000033.4(ABCD1):c.1396C>T (p.Gln466Ter)
NM_000033.4(ABCD1):c.1553G>A (p.Arg518Gln)
NM_000033.4(ABCD1):c.1586G>A (p.Gly529Asp)
NM_000033.4(ABCD1):c.1660C>A (p.Arg554Ser)
NM_000033.4(ABCD1):c.1679C>T (p.Pro560Leu)
NM_000033.4(ABCD1):c.1771C>T (p.Arg591Trp)
NM_000033.4(ABCD1):c.1802G>A (p.Trp601Ter)
NM_000033.4(ABCD1):c.1866-10G>A
NM_000033.4(ABCD1):c.346G>A (p.Gly116Arg)
NM_000033.4(ABCD1):c.406C>T (p.Gln136Ter)
NM_000033.4(ABCD1):c.1661G>A (p.Arg554His)
NM_000033.4(ABCD1):c.1825G>A (p.Glu609Lys)
NM_000033.4(ABCD1):c.1201C>G (p.Arg401Gly)
NM_000033.4(ABCD1):c.887A>G (p.Tyr296Cys)
NM_000033.4(ABCD1):c.886T>C (p.Tyr296His)
NM_000033.4(ABCD1):c.1288C>T (p.Gln430Ter)
NM_000033.4(ABCD1):c.1781-1G>A
NM_000033.4(ABCD1):c.651G>C (p.Lys217Asn)
NM_000033.4(ABCD1):c.1166G>A (p.Arg389His)
NM_000033.4(ABCD1):c.529C>T (p.Gln177Ter)
NM_000033.4(ABCD1):c.488G>A (p.Arg163His)
NM_000033.4(ABCD1):c.1895C>T (p.Thr632Ile)
NM_000033.4(ABCD1):c.565C>T (p.Arg189Trp)
NM_000033.4(ABCD1):c.761C>T (p.Thr254Met)
NM_000033.4(ABCD1):c.1082-1G>A
NM_000033.4(ABCD1):c.2037G>A (p.Trp679Ter)
NM_000033.4(ABCD1):c.311G>A (p.Arg104His)
NM_000033.4(ABCD1):c.442A>T (p.Asn148Tyr)
NM_000033.4(ABCD1):c.1772G>A (p.Arg591Gln)
NM_000033.4(ABCD1):c.1979G>T (p.Arg660Leu)
NM_000033.4(ABCD1):c.1780+2T>G
NM_000033.4(ABCD1):c.293C>T (p.Ser98Leu)
NM_000033.4(ABCD1):c.521A>G (p.Tyr174Cys)
NM_000033.4(ABCD1):c.1270C>T (p.Gln424Ter)
NM_000033.4(ABCD1):c.1998C>A (p.Tyr666Ter)
NM_000033.4(ABCD1):c.1201C>T (p.Arg401Trp)
NM_000033.4(ABCD1):c.887A>C (p.Tyr296Ser)
NM_000033.4(ABCD1):c.2035T>A (p.Trp679Arg)
NM_000033.4(ABCD1):c.1866-1G>C
NM_000033.4(ABCD1):c.843C>A (p.Tyr281Ter)
NM_000033.4(ABCD1):c.1567C>T (p.Leu523Phe)
NM_000033.4(ABCD1):c.1628C>T (p.Pro543Leu)
NM_000033.4(ABCD1):c.1552C>G (p.Arg518Gly)
NM_000033.4(ABCD1):c.2003C>T (p.Thr668Ile)
NM_000033.4(ABCD1):c.876G>C (p.Glu292Asp)
NM_000033.4(ABCD1):c.1826A>G (p.Glu609Gly)
NM_000033.4(ABCD1):c.433A>G (p.Thr145Ala)
NM_000033.4(ABCD1):c.454C>T (p.Arg152Cys)
NM_000033.4(ABCD1):c.1126G>T (p.Glu376Ter)
NM_000033.4(ABCD1):c.1876G>A (p.Ala626Thr)
NM_000033.4(ABCD1):c.1866-1G>A
NM_000033.4(ABCD1):c.1096A>T (p.Lys366Ter)
NM_000033.4(ABCD1):c.1534G>A (p.Gly512Ser)
NM_000033.4(ABCD1):c.1978C>T (p.Arg660Trp)
NM_000033.4(ABCD1):c.320T>C (p.Leu107Pro)
NM_000033.4(ABCD1):c.662A>C (p.Asp221Ala)
NM_000033.4(ABCD1):c.80A>C (p.Tyr27Ser)
NM_000033.4(ABCD1):c.487C>T (p.Arg163Cys)
NM_000033.4(ABCD1):c.593C>T (p.Thr198Met)
NM_000033.4(ABCD1):c.1165C>T (p.Arg389Cys)
NM_000033.4(ABCD1):c.1186G>A (p.Ala396Thr)
NM_000033.4(ABCD1):c.1597A>C (p.Lys533Gln)
NM_000033.4(ABCD1):c.1973C>T (p.Thr658Ile)
NM_000033.4(ABCD1):c.900G>C (p.Glu300Asp)
NM_000033.4(ABCD1):c.346G>C (p.Gly116Arg)
NM_000033.4(ABCD1):c.829G>A (p.Gly277Arg)
NM_000033.4(ABCD1):c.892G>A (p.Gly298Ser)
NM_000033.4(ABCD1):c.919C>T (p.Gln307Ter)
NM_000033.4(ABCD1):c.1454C>G (p.Ser485Ter)
NM_000033.4(ABCD1):c.1784G>A (p.Trp595Ter)
NM_000033.4(ABCD1):c.1919A>G (p.Glu640Gly)
NM_000033.4(ABCD1):c.1489-1G>A
NM_000033.4(ABCD1):c.1635-1G>A
NM_000033.4(ABCD1):c.521A>C (p.Tyr174Ser)
NM_000033.4(ABCD1):c.422C>T (p.Ala141Val)
NM_000033.4(ABCD1):c.1015T>C (p.Trp339Arg)
NM_000033.4(ABCD1):c.1219A>T (p.Lys407Ter)
NM_000033.4(ABCD1):c.1967C>T (p.Ser656Phe)
NM_000033.4(ABCD1):c.341T>C (p.Leu114Pro)
NM_000033.4(ABCD1):c.878T>C (p.Ile293Thr)
NM_000033.4(ABCD1):c.1144A>C (p.Thr382Pro)
NM_000033.4(ABCD1):c.1501A>T (p.Met501Leu)
NM_000033.4(ABCD1):c.1998C>G (p.Tyr666Ter)
NM_000033.4(ABCD1):c.1A>G (p.Met1Val)
NM_000033.4(ABCD1):c.442A>G (p.Asn148Asp)
NM_000033.4(ABCD1):c.797G>A (p.Gly266Glu)
NM_000033.4(ABCD1):c.847C>G (p.His283Asp)
NM_000033.4(ABCD1):c.994C>T (p.Gln332Ter)
NM_000033.4(ABCD1):c.1028G>A (p.Gly343Asp)
NM_000033.4(ABCD1):c.1631A>G (p.Gln544Arg)
NM_000033.4(ABCD1):c.1678C>A (p.Pro560Thr)
NM_000033.4(ABCD1):c.1961T>C (p.Leu654Pro)
NM_000033.4(ABCD1):c.1081+1G>A
NM_000033.4(ABCD1):c.1628C>G (p.Pro543Arg)
NM_000033.4(ABCD1):c.1991G>A (p.Trp664Ter)
NM_000033.4(ABCD1):c.1699C>T (p.Gln567Ter)
NM_000033.4(ABCD1):c.411G>A (p.Trp137Ter)
NM_000033.4(ABCD1):c.659T>C (p.Leu220Pro)
NM_000033.4(ABCD1):c.1027G>C (p.Gly343Arg)
NM_000033.4(ABCD1):c.1414C>T (p.Gln472Ter)
NM_000033.4(ABCD1):c.1508T>C (p.Leu503Pro)
NM_000033.4(ABCD1):c.1675T>C (p.Tyr559His)
NM_000033.4(ABCD1):c.578C>G (p.Pro193Arg)
NM_000033.4(ABCD1):c.580G>A (p.Asp194Asn)
NM_000033.4(ABCD1):c.787C>T (p.Pro263Ser)
NM_000033.4(ABCD1):c.1892G>A (p.Cys631Tyr)
NM_000033.4(ABCD1):c.2006A>G (p.His669Arg)
NM_000033.4(ABCD1):c.1488+1G>A
NM_000033.4(ABCD1):c.661G>A (p.Asp221Asn)
NM_000033.4(ABCD1):c.1822G>A (p.Gly608Ser)
NM_000033.4(ABCD1):c.1899C>G (p.Ser633Arg)
NM_000033.4(ABCD1):c.290A>C (p.His97Pro)
NM_000033.4(ABCD1):c.1484T>A (p.Ile495Asn)
NM_000033.4(ABCD1):c.1768C>T (p.Gln590Ter)
NM_000033.4(ABCD1):c.1907G>T (p.Ser636Ile)
NM_000033.4(ABCD1):c.30G>A (p.Trp10Ter)
NM_000033.4(ABCD1):c.323C>T (p.Ser108Leu)
NM_000033.4(ABCD1):c.454C>A (p.Arg152Ser)
NM_000033.4(ABCD1):c.1849C>G (p.Arg617Gly)
NM_000033.4(ABCD1):c.830G>T (p.Gly277Val)
NM_000033.4(ABCD1):c.598G>A (p.Asp200Asn)
NM_000033.4(ABCD1):c.1247C>G (p.Thr416Arg)
NM_000033.4(ABCD1):c.873G>C (p.Glu291Asp)
NM_000033.4(ABCD1):c.1442T>C (p.Ile481Thr)
NM_000033.4(ABCD1):c.785C>G (p.Ser262Trp)
NM_000033.4(ABCD1):c.965T>C (p.Leu322Pro)
NM_000033.4(ABCD1):c.1138G>T (p.Glu380Ter)
NM_000033.4(ABCD1):c.1780G>C (p.Gly594Arg)
NM_000033.4(ABCD1):c.1817C>A (p.Ser606Ter)
NM_000033.4(ABCD1):c.221G>T (p.Arg74Leu)
NM_000033.4(ABCD1):c.900+2T>C
NM_000033.4(ABCD1):c.518T>C (p.Leu173Pro)
NM_000033.4(ABCD1):c.829G>T (p.Gly277Trp)
NM_000033.4(ABCD1):c.482C>A (p.Ser161Ter)
NM_000033.4(ABCD1):c.29G>A (p.Trp10Ter)
NM_000033.4(ABCD1):c.901-1G>A
NM_000033.4(ABCD1):c.395G>A (p.Trp132Ter)
NM_000033.4(ABCD1):c.268G>T (p.Glu90Ter)
NM_000033.4(ABCD1):c.488G>T (p.Arg163Leu)
NM_000033.4(ABCD1):c.901-2A>C
NM_000033.4(ABCD1):c.901-2A>G
NM_000033.4(ABCD1):c.847C>T (p.His283Tyr)
NM_000033.4(ABCD1):c.488G>C (p.Arg163Pro)
NM_000033.4(ABCD1):c.487C>G (p.Arg163Gly)
NM_000033.4(ABCD1):c.931C>T (p.Gln311Ter)
NM_000033.4(ABCD1):c.455G>C (p.Arg152Pro)
NM_000033.4(ABCD1):c.1519G>A (p.Gly507Ser)
NM_000033.4(ABCD1):c.1679C>G (p.Pro560Arg)
NM_000033.4(ABCD1):c.1891T>C (p.Cys631Arg)
NM_000033.4(ABCD1):c.310C>T (p.Arg104Cys)
NM_000033.4(ABCD1):c.1823G>C (p.Gly608Ala)
NM_000033.4(ABCD1):c.851C>A (p.Ser284Ter)
NM_000033.4(ABCD1):c.1224G>A (p.Glu408=)
NM_000033.4(ABCD1):c.1720C>T (p.Gln574Ter)
NM_000033.4(ABCD1):c.1999C>G (p.His667Asp)
NM_000033.4(ABCD1):c.154G>T (p.Glu52Ter)
NM_000033.4(ABCD1):c.1677C>A (p.Tyr559Ter)
NM_000033.4(ABCD1):c.848A>G (p.His283Arg)
NM_000033.4(ABCD1):c.522C>G (p.Tyr174Ter)
NM_000033.4(ABCD1):c.290A>G (p.His97Arg)
NM_000033.4(ABCD1):c.632T>G (p.Leu211Arg)
NM_000033.4(ABCD1):c.2051T>C (p.Leu684Pro)
NM_000033.4(ABCD1):c.1529G>A (p.Gly510Asp)
NM_000033.4(ABCD1):c.760A>G (p.Thr254Ala)
NM_000033.4(ABCD1):c.1535G>T (p.Gly512Val)
NM_000033.4(ABCD1):c.454C>G (p.Arg152Gly)
NM_000033.4(ABCD1):c.853C>G (p.Arg285Gly)
NM_000033.4(ABCD1):c.901-5C>A
NM_000033.4(ABCD1):c.1523C>T (p.Pro508Leu)
NM_000033.4(ABCD1):c.1886A>T (p.Asp629Val)
NM_000033.4(ABCD1):c.1785G>A (p.Trp595Ter)
NM_000033.4(ABCD1):c.293C>G (p.Ser98Trp)
NM_000033.4(ABCD1):c.1781-2A>G
NM_000033.4(ABCD1):c.1802G>C (p.Trp601Ser)
NM_000033.4(ABCD1):c.1117A>T (p.Lys373Ter)
NM_000033.4(ABCD1):c.1075G>T (p.Glu359Ter)
NM_000033.4(ABCD1):c.1537A>T (p.Lys513Ter)
NM_000033.4(ABCD1):c.583C>T (p.Gln195Ter)
NM_000033.4(ABCD1):c.953A>T (p.Asn318Ile)
NM_000033.4(ABCD1):c.1547T>C (p.Leu516Pro)
NM_000033.4(ABCD1):c.2014C>T (p.Gln672Ter)
NM_000033.4(ABCD1):c.1073C>G (p.Ser358Ter)
NM_000033.4(ABCD1):c.1028G>T (p.Gly343Val)
NM_000033.4(ABCD1):c.1574C>T (p.Pro525Leu)
NM_000033.4(ABCD1):c.1528G>A (p.Gly510Ser)
NM_000033.4(ABCD1):c.338G>C (p.Arg113Pro)
NM_000033.4(ABCD1):c.469C>T (p.Gln157Ter)
NM_000033.4(ABCD1):c.904G>A (p.Glu302Lys)
NM_000033.4(ABCD1):c.1016G>A (p.Trp339Ter)
NM_000033.4(ABCD1):c.1259A>C (p.His420Pro)
NM_000033.4(ABCD1):c.1393+1G>A
NM_000033.4(ABCD1):c.1520G>A (p.Gly507Asp)
NM_000033.4(ABCD1):c.1570T>C (p.Trp524Arg)
NM_000033.4(ABCD1):c.1991+1G>A
NM_000033.4(ABCD1):c.1450C>T (p.Pro484Ser)
NM_000033.4(ABCD1):c.1489-2A>G
NM_000033.4(ABCD1):c.797G>C (p.Gly266Ala)
NM_000033.4(ABCD1):c.1006A>G (p.Lys336Glu)
NM_000033.4(ABCD1):c.1253G>C (p.Arg418Pro)
NM_000033.4(ABCD1):c.1224+2T>A
NM_000033.4(ABCD1):c.1713C>G (p.Tyr571Ter)
NM_000033.4(ABCD1):c.430G>A (p.Ala144Thr)
NM_000033.4(ABCD1):c.1600C>A (p.Pro534Thr)
NM_000033.4(ABCD1):c.1224+1G>T
NM_000033.4(ABCD1):c.1634+1G>C
NM_000033.4(ABCD1):c.346G>T (p.Gly116Ter)
NM_000033.4(ABCD1):c.2000A>G (p.His667Arg)
NM_000033.4(ABCD1):c.1875C>A (p.Tyr625Ter)
NM_000033.4(ABCD1):c.397C>T (p.Gln133Ter)
NM_000033.4(ABCD1):c.220C>T (p.Arg74Trp)
NM_000033.4(ABCD1):c.1510C>T (p.Leu504Phe)
NM_000033.4(ABCD1):c.935A>G (p.Asp312Gly)
NM_000033.4(ABCD1):c.331G>A (p.Val111Met)
NM_000033.4(ABCD1):c.978G>A (p.Trp326Ter)
NM_000033.4(ABCD1):c.893G>A (p.Gly298Asp)
NM_000033.4(ABCD1):c.2080G>T (p.Glu694Ter)
NM_000033.4(ABCD1):c.1454C>A (p.Ser485Ter)
NM_000033.4(ABCD1):c.1781-1G>T
NM_000033.4(ABCD1):c.830G>A (p.Gly277Glu)
NM_000033.4(ABCD1):c.1678C>T (p.Pro560Ser)
NM_000033.4(ABCD1):c.1081+1G>C
NM_000033.4(ABCD1):c.872A>C (p.Glu291Ala)
NM_000033.4(ABCD1):c.1478T>A (p.Leu493His)
NM_000033.4(ABCD1):c.830G>C (p.Gly277Ala)
NM_000033.4(ABCD1):c.455G>A (p.Arg152His)
NM_000033.4(ABCD1):c.824G>A (p.Arg275Gln)
NM_000033.4(ABCD1):c.992A>T (p.Glu331Val)
NM_000033.4(ABCD1):c.99C>A (p.Tyr33Ter)
NM_000033.4(ABCD1):c.250C>T (p.Pro84Ser)
NM_000033.4(ABCD1):c.293C>A (p.Ser98Ter)
NM_000033.4(ABCD1):c.359G>C (p.Arg120Pro)
NM_000033.4(ABCD1):c.520T>C (p.Tyr174His)
NM_000033.4(ABCD1):c.788C>T (p.Pro263Leu)
NM_000033.4(ABCD1):c.836T>C (p.Leu279Pro)
NM_000033.4(ABCD1):c.869C>G (p.Ser290Trp)
NM_000033.4(ABCD1):c.1394-2A>G
NM_000033.4(ABCD1):c.1478T>C (p.Leu493Pro)
NM_000033.4(ABCD1):c.1600C>T (p.Pro534Ser)
NM_000033.4(ABCD1):c.1667A>G (p.Gln556Arg)
NM_000033.4(ABCD1):c.1772G>C (p.Arg591Pro)
NM_000033.4(ABCD1):c.1918G>A (p.Glu640Lys)
NM_000033.4(ABCD1):c.1241G>A (p.Gly414Asp)
NM_000033.4(ABCD1):c.1222G>T (p.Glu408Ter)
NM_000033.4(ABCD1):c.1831C>T (p.Gln611Ter)
NM_000033.4(ABCD1):c.1961T>A (p.Leu654Gln)
NM_000033.4(ABCD1):c.1634+1G>T
NM_000033.4(ABCD1):c.1586G>T (p.Gly529Val)
NM_000033.4(ABCD1):c.581A>T (p.Asp194Val)
NM_000033.4(ABCD1):c.309C>A (p.Ser103Arg)
NM_000033.4(ABCD1):c.850T>C (p.Ser284Pro)
NM_000033.4(ABCD1):c.917T>G (p.Leu306Arg)
NM_000033.4(ABCD1):c.1877C>T (p.Ala626Val)
NM_000033.4(ABCD1):c.659T>G (p.Leu220Arg)
NM_000033.4(ABCD1):c.1939G>T (p.Ala647Ser)
NM_000033.4(ABCD1):c.1866-2A>T
NM_000033.4(ABCD1):c.686T>C (p.Leu229Pro)
NM_000033.4(ABCD1):c.893G>T (p.Gly298Val)
NM_000033.4(ABCD1):c.1533C>A (p.Cys511Ter)
NM_000033.4(ABCD1):c.1428C>A (p.Cys476Ter)
NM_000033.4(ABCD1):c.1673T>C (p.Ile558Thr)
NM_000033.4(ABCD1):c.900+1G>C
NM_000033.4(ABCD1):c.892G>T (p.Gly298Cys)
NM_000033.4(ABCD1):c.1252C>G (p.Arg418Gly)
NM_000033.4(ABCD1):c.1831C>G (p.Gln611Glu)
NM_000033.4(ABCD1):c.1993A>T (p.Lys665Ter)
NM_000033.4(ABCD1):c.1781-1G>C
NM_000033.4(ABCD1):c.91A>T (p.Lys31Ter)
NM_000033.4(ABCD1):c.396G>A (p.Trp132Ter)
NM_000033.4(ABCD1):c.532C>T (p.Gln178Ter)
NM_000033.4(ABCD1):c.569T>C (p.Leu190Pro)
NM_000033.4(ABCD1):c.668C>A (p.Ala223Asp)
NM_000033.4(ABCD1):c.760A>C (p.Thr254Pro)
NM_000033.4(ABCD1):c.900+1G>T
NM_000033.4(ABCD1):c.906G>C (p.Glu302Asp)
NM_000033.4(ABCD1):c.1531T>C (p.Cys511Arg)
NM_000033.4(ABCD1):c.1640A>G (p.Tyr547Cys)
NM_000033.4(ABCD1):c.1666C>T (p.Gln556Ter)
NM_000033.4(ABCD1):c.898G>T (p.Glu300Ter)
NM_000033.4(ABCD1):c.1489-1G>T
NM_000033.4(ABCD1):c.938T>C (p.Leu313Pro)
NM_000033.4(ABCD1):c.163C>T (p.Gln55Ter)
NM_000033.4(ABCD1):c.1202G>T (p.Arg401Leu)
NM_000033.4(ABCD1):c.977G>A (p.Trp326Ter)
NM_000033.4(ABCD1):c.1082-2A>G
NM_000033.4(ABCD1):c.1597A>G (p.Lys533Glu)
NM_000033.4(ABCD1):c.1865+1G>C
NM_000033.4(ABCD1):c.2005C>T (p.His669Tyr)
NM_000033.4(ABCD1):c.632T>C (p.Leu211Pro)
NM_000033.4(ABCD1):c.1833G>C (p.Gln611His)
NM_000033.4(ABCD1):c.1187C>A (p.Ala396Glu)
NM_000033.4(ABCD1):c.311G>C (p.Arg104Pro)
NM_000033.4(ABCD1):c.582C>A (p.Asp194Glu)
NM_000033.4(ABCD1):c.427C>G (p.Pro143Ala)
NM_000033.4(ABCD1):c.1715C>A (p.Ser572Ter)
NM_000033.4(ABCD1):c.1865+1G>T
NM_000033.4(ABCD1):c.901-1G>C
NM_000033.4(ABCD1):c.1888G>T (p.Glu630Ter)
NM_000033.4(ABCD1):c.1894A>C (p.Thr632Pro)
NM_000033.4(ABCD1):c.433A>C (p.Thr145Pro)
NM_000033.4(ABCD1):c.487C>A (p.Arg163Ser)
NM_000033.4(ABCD1):c.509C>A (p.Ala170Asp)
NM_000033.4(ABCD1):c.1640A>T (p.Tyr547Phe)
NM_000033.4(ABCD1):c.1976A>G (p.His659Arg)
NM_000033.4(ABCD1):c.796G>C (p.Gly266Arg)
NM_000033.4(ABCD1):c.274G>C (p.Gly92Arg)
NM_000033.4(ABCD1):c.1256T>C (p.Val419Ala)
NM_000478.6(ALPL):c.535G>A (p.Ala179Thr)
NM_000478.6(ALPL):c.211C>T (p.Arg71Cys)
NM_000478.6(ALPL):c.881A>C (p.Asp294Ala)
NM_000478.6(ALPL):c.212G>C (p.Arg71Pro)
NM_000478.6(ALPL):c.620A>C (p.Gln207Pro)
NM_000478.6(ALPL):c.98C>T (p.Ala33Val)
NM_000478.6(ALPL):c.892G>A (p.Glu298Lys)
NM_000478.6(ALPL):c.1133A>T (p.Asp378Val)
NM_000478.6(ALPL):c.1001G>A (p.Gly334Asp)
NM_000478.6(ALPL):c.979T>C (p.Phe327Leu)
NM_000478.6(ALPL):c.407G>A (p.Arg136His)
NM_000478.6(ALPL):c.485G>T (p.Gly162Val)
NM_000478.6(ALPL):c.346G>A (p.Ala116Thr)
NM_000478.6(ALPL):c.648+1G>A
NM_000478.6(ALPL):c.1250A>G (p.Asn417Ser)
NM_000478.6(ALPL):c.323C>T (p.Pro108Leu)
NM_000478.6(ALPL):c.1366G>A (p.Gly456Arg)
NM_000478.6(ALPL):c.746G>T (p.Gly249Val)
NM_000478.6(ALPL):c.526G>A (p.Ala176Thr)
NM_000478.6(ALPL):c.814C>T (p.Arg272Cys)
NM_000478.6(ALPL):c.215T>C (p.Ile72Thr)
NM_000478.6(ALPL):c.542C>T (p.Ser181Leu)
NM_000478.6(ALPL):c.667C>T (p.Arg223Trp)
NM_000478.6(ALPL):c.791A>G (p.Lys264Arg)
NM_000478.6(ALPL):c.809G>A (p.Trp270Ter)
NM_000478.6(ALPL):c.871G>A (p.Glu291Lys)
NM_000478.6(ALPL):c.891C>A (p.Tyr297Ter)
NM_000478.6(ALPL):c.61+2T>G
NM_000478.6(ALPL):c.88C>T (p.Arg30Ter)
NM_000478.6(ALPL):c.130C>T (p.Gln44Ter)
NM_000478.6(ALPL):c.297+2T>A
NM_000478.6(ALPL):c.997+2T>G
NM_000478.6(ALPL):c.998-2A>G
NM_000478.6(ALPL):c.1144G>A (p.Val382Ile)
NM_000478.6(ALPL):c.1363G>A (p.Gly455Ser)
NM_000478.6(ALPL):c.1426G>T (p.Glu476Ter)
NM_000478.6(ALPL):c.668G>A (p.Arg223Gln)
NM_000478.6(ALPL):c.227A>G (p.Gln76Arg)
NM_000478.6(ALPL):c.1403C>T (p.Ala468Val)
NM_000478.6(ALPL):c.340G>A (p.Ala114Thr)
NM_000478.6(ALPL):c.815G>A (p.Arg272His)
NM_000478.6(ALPL):c.188G>T (p.Gly63Val)
NM_000478.6(ALPL):c.550C>T (p.Arg184Trp)
NM_000478.6(ALPL):c.87G>A (p.Trp29Ter)
NM_000478.6(ALPL):c.497C>T (p.Thr166Ile)
NM_000478.6(ALPL):c.262G>A (p.Glu88Lys)
NM_000478.6(ALPL):c.422C>A (p.Thr141Asn)
NM_000478.6(ALPL):c.862+1G>A
NM_000478.6(ALPL):c.1039C>T (p.Gln347Ter)
NM_000478.6(ALPL):c.318G>C (p.Gln106His)
NM_000478.6(ALPL):c.368C>A (p.Ala123Asp)
NM_000478.6(ALPL):c.407G>C (p.Arg136Pro)
NM_000478.6(ALPL):c.1333T>C (p.Ser445Pro)
NM_000478.6(ALPL):c.1375G>T (p.Val459Leu)
NM_000478.6(ALPL):c.334G>A (p.Gly112Ser)
NM_000478.6(ALPL):c.629A>G (p.His210Arg)
NM_000478.6(ALPL):c.670A>G (p.Lys224Glu)
NM_000478.6(ALPL):c.1042G>A (p.Ala348Thr)
NM_000478.6(ALPL):c.1132G>C (p.Asp378His)
NM_000478.6(ALPL):c.1324C>T (p.Gln442Ter)
NM_000478.6(ALPL):c.1375G>A (p.Val459Met)
NM_000478.6(ALPL):c.880G>T (p.Asp294Tyr)
NM_000478.6(ALPL):c.1010A>G (p.Asp337Gly)
NM_000478.6(ALPL):c.1471G>A (p.Gly491Arg)
NM_000478.6(ALPL):c.658G>A (p.Gly220Arg)
NM_000478.6(ALPL):c.661G>C (p.Gly221Arg)
NM_000478.6(ALPL):c.1171C>T (p.Arg391Cys)
NM_000478.6(ALPL):c.1172G>A (p.Arg391His)
NM_000478.6(ALPL):c.1285G>A (p.Glu429Lys)
NM_000478.6(ALPL):c.1460C>T (p.Ala487Val)
NM_000478.6(ALPL):c.994G>T (p.Glu332Ter)
NM_000478.6(ALPL):c.395C>T (p.Ala132Val)
NM_000478.6(ALPL):c.1142A>G (p.His381Arg)
NM_000478.6(ALPL):c.923C>G (p.Ser308Ter)
NM_000478.6(ALPL):c.299C>T (p.Thr100Met)
NM_000478.6(ALPL):c.331G>A (p.Ala111Thr)
NM_000478.6(ALPL):c.1417G>A (p.Gly473Ser)
NM_000478.6(ALPL):c.1426G>A (p.Glu476Lys)
NM_000478.6(ALPL):c.997+1G>T
NM_000478.6(ALPL):c.1282C>T (p.Arg428Ter)
NM_000478.6(ALPL):c.571G>T (p.Glu191Ter)
NM_000478.6(ALPL):c.1400T>C (p.Met467Thr)
NM_000478.6(ALPL):c.997+2T>A
NM_000478.6(ALPL):c.824T>C (p.Leu275Pro)
NM_000478.6(ALPL):c.1077C>G (p.Ile359Met)
NM_000478.6(ALPL):c.1162T>C (p.Tyr388His)
NM_000478.6(ALPL):c.406C>T (p.Arg136Cys)
NM_000478.6(ALPL):c.949A>T (p.Ile317Phe)
NM_000478.6(ALPL):c.575T>C (p.Met192Thr)
NM_000478.6(ALPL):c.1348C>T (p.Arg450Cys)
NM_000478.6(ALPL):c.94C>T (p.Gln32Ter)
NM_000478.6(ALPL):c.119C>T (p.Ala40Val)
NM_000478.6(ALPL):c.500C>A (p.Thr167Lys)
NM_000478.6(ALPL):c.500C>T (p.Thr167Met)
NM_000478.6(ALPL):c.1190-2A>T
NM_000478.6(ALPL):c.617A>G (p.Tyr206Cys)
NM_000478.6(ALPL):c.738G>T (p.Arg246Ser)
NM_000478.6(ALPL):c.1283G>C (p.Arg428Pro)
NM_000478.6(ALPL):c.1022A>G (p.His341Arg)
NM_000478.6(ALPL):c.1415A>G (p.His472Arg)
NM_000478.6(ALPL):c.1228T>C (p.Phe410Leu)
NM_000478.6(ALPL):c.1328C>T (p.Ala443Val)
NM_000478.6(ALPL):c.655A>G (p.Met219Val)
NM_000478.6(ALPL):c.661G>T (p.Gly221Cys)
NM_000478.6(ALPL):c.335G>C (p.Gly112Ala)
NM_000478.6(ALPL):c.508A>G (p.Asn170Asp)
NM_000478.6(ALPL):c.1145T>A (p.Val382Asp)
NM_000478.6(ALPL):c.182-2A>G
NM_000478.6(ALPL):c.203C>T (p.Thr68Met)
NM_000478.6(ALPL):c.212G>A (p.Arg71His)
NM_000478.6(ALPL):c.223G>A (p.Gly75Ser)
NM_000478.6(ALPL):c.303C>A (p.Tyr101Ter)
NM_000478.6(ALPL):c.484G>A (p.Gly162Ser)
NM_000478.6(ALPL):c.532T>C (p.Tyr178His)
NM_000478.6(ALPL):c.558G>A (p.Trp186Ter)
NM_000478.6(ALPL):c.659G>C (p.Gly220Ala)
NM_000478.6(ALPL):c.886C>T (p.Gln296Ter)
NM_000478.6(ALPL):c.976G>C (p.Gly326Arg)
NM_000478.6(ALPL):c.997G>T (p.Gly333Ter)
NM_000478.6(ALPL):c.1240C>A (p.Leu414Met)
NM_000478.6(ALPL):c.1166C>A (p.Thr389Asn)
NM_000478.6(ALPL):c.657G>T (p.Met219Ile)
NM_000478.6(ALPL):c.1427A>C (p.Glu476Ala)
NM_000478.6(ALPL):c.874C>A (p.Pro292Thr)
NM_000478.6(ALPL):c.542C>G (p.Ser181Trp)
NM_000478.6(ALPL):c.1479C>A (p.Asn493Lys)
NM_000478.6(ALPL):c.1360C>T (p.His454Tyr)
NM_000478.6(ALPL):c.361G>A (p.Val121Met)
NM_000478.6(ALPL):c.601T>C (p.Cys201Arg)
NM_000478.6(ALPL):c.214A>G (p.Ile72Val)
NM_000478.6(ALPL):c.247G>T (p.Glu83Ter)
NM_000478.6(ALPL):c.1418G>A (p.Gly473Asp)
NM_000478.6(ALPL):c.284T>A (p.Val95Glu)
NM_000478.6(ALPL):c.1A>G (p.Met1Val)
NM_000478.6(ALPL):c.346G>T (p.Ala116Ser)
NM_000478.6(ALPL):c.551G>A (p.Arg184Gln)
NM_000478.6(ALPL):c.422C>T (p.Thr141Ile)
NM_000478.6(ALPL):c.536C>T (p.Ala179Val)
NM_000478.6(ALPL):c.395C>G (p.Ala132Gly)
NM_000478.6(ALPL):c.1183A>G (p.Ile395Val)
NM_000478.6(ALPL):c.1163A>G (p.Tyr388Cys)
NM_000478.6(ALPL):c.459G>A (p.Trp153Ter)
NM_000478.6(ALPL):c.1367G>A (p.Gly456Glu)
NM_000478.6(ALPL):c.1427A>G (p.Glu476Gly)
NM_000478.6(ALPL):c.649-1G>A
NM_000478.6(ALPL):c.1007T>C (p.Ile336Thr)
NM_000478.6(ALPL):c.1367G>C (p.Gly456Ala)
NM_000478.6(ALPL):c.815G>T (p.Arg272Leu)
NM_000478.6(ALPL):c.980T>G (p.Phe327Cys)
NM_000478.6(ALPL):c.1231A>G (p.Thr411Ala)
NM_000478.6(ALPL):c.1402G>A (p.Ala468Thr)
NM_000478.6(ALPL):c.1444C>A (p.His482Asn)
NM_000478.6(ALPL):c.1195G>T (p.Ala399Ser)
NM_000478.6(ALPL):c.1268T>C (p.Val423Ala)
NM_000478.6(ALPL):c.1130C>T (p.Ala377Val)
NM_000478.6(ALPL):c.1164C>A (p.Tyr388Ter)
NM_000478.6(ALPL):c.572A>G (p.Glu191Gly)
NM_000478.6(ALPL):c.1015G>A (p.Gly339Arg)
NM_000478.6(ALPL):c.1120G>A (p.Val374Met)
NM_000478.6(ALPL):c.1276G>A (p.Gly426Ser)
NM_000478.6(ALPL):c.1336G>A (p.Ala446Thr)
NM_000478.6(ALPL):c.1402G>T (p.Ala468Ser)

### some variants have a "=" in their name: e.g
* NM_000033.4(ABCD1):c.900G>A (p.Glu300=)
* NM_000033.4(ABCD1):c.1224G>A (p.Glu408=)
##### Let's take a closer look at all vairants with that naming style

In [16]:
for gene in loci:
    vardata = pd.read_csv("pathogenic/" + gene + ".csv")
    for x in vardata["Name"]:
        if "(p." in x and "=" in x:
            print(x)

NM_000033.4(ABCD1):c.900G>A (p.Glu300=)
NM_000033.4(ABCD1):c.1224G>A (p.Glu408=)
NM_000478.6(ALPL):c.1161A>G (p.Gly387=)
NM_000044.6(AR):c.2667C>T (p.Ser889=)
NM_000053.4(ATP7B):c.2355G>A (p.Lys785=)
NM_000053.4(ATP7B):c.1488C>T (p.Gly496=)
NM_000061.3(BTK):c.240G>A (p.Pro80=)
NM_000492.4(CFTR):c.2988G>A (p.Gln996=)
NM_000492.4(CFTR):c.1209G>A (p.Glu403=)
NM_000492.4(CFTR):c.3468G>A (p.Leu1156=)
NM_000492.4(CFTR):c.3717G>A (p.Arg1239=)
NM_000492.4(CFTR):c.273G>C (p.Gly91=)
NM_000492.4(CFTR):c.1398A>T (p.Ser466=)
NM_000397.4(CYBB):c.252G>A (p.Ala84=)
NM_000397.4(CYBB):c.483G>A (p.Lys161=)
NM_019616.4(F7):c.225G>C (p.Thr75=)
NM_000132.4(F8):c.5586G>A (p.Leu1862=)
NM_000132.4(F8):c.1569G>T (p.Leu523=)
NM_000132.4(F8):c.5217C>T (p.Asn1739=)
NM_000132.4(F8):c.6273G>A (p.Lys2091=)
NM_000132.4(F8):c.1167A>G (p.Gln389=)
NM_000133.4(F9):c.459G>A (p.Val153=)
NM_000133.4(F9):c.723G>A (p.Gln241=)
NM_000133.4(F9):c.484C>A (p.Arg162=)
NM_001360016.2(G6PD):c.219C>T (p.Ser73=)
NM_001360016.2(G6PD):c.312C>T (p.Arg104=)
NM_000155.4(GALT):c.1014C>G (p.Gly338=)
NM_000155.4(GALT):c.1014C>T (p.Gly338=)
NM_000166.6(GJB1):c.57C>T (p.Ala19=)
NM_000166.6(GJB1):c.48T>C (p.His16=)
NM_000518.5(HBB):c.75T>A (p.Gly25=)
NM_000518.5(HBB):c.91A>C (p.Arg31=)
NM_000518.5(HBB):c.51C>T (p.Gly17=)
NM_000206.3(IL2RG):c.924G>A (p.Ser308=)
NM_000206.3(IL2RG):c.924G>C (p.Ser308=)
NM_000238.4(KCNH2):c.1128G>A (p.Gln376=)
NM_000218.3(KCNQ1):c.1032G>A (p.Ala344=)
NM_000218.3(KCNQ1):c.1032G>C (p.Ala344=)
NM_000218.3(KCNQ1):c.921G>A (p.Val307=)
NM_000218.3(KCNQ1):c.1032G>T (p.Ala344=)
NM_001278116.2(L1CAM):c.924C>T (p.Gly308=)
NM_000527.5(LDLR):c.1216C>A (p.Arg406=)
NM_000527.5(LDLR):c.621C>T (p.Gly207=)
NM_000527.5(LDLR):c.1813C>T (p.Leu605=)
NM_000527.5(LDLR):c.528C>T (p.Gly176=)
NM_000527.5(LDLR):c.2253G>A (p.Arg751=)
NM_000527.5(LDLR):c.2139A>G (p.Thr713=)
NM_000530.8(MPZ):c.276G>A (p.Val92=)
NM_000530.8(MPZ):c.309G>T (p.Gly103=)
NM_000530.8(MPZ):c.411C>T (p.Gly137=)
NM_000530.8(MPZ):c.279G>T (p.Gly93=)
NM_000277.3(PAH):c.1197A>T (p.Val399=)
NM_000277.3(PAH):c.1194A>G (p.Lys398=)
NM_000277.3(PAH):c.912G>A (p.Gln304=)
NM_000546.6(TP53):c.672G>A (p.Glu224=)
NM_000546.6(TP53):c.375G>A (p.Thr125=)
NM_000546.6(TP53):c.375G>T (p.Thr125=)
NM_000546.6(TP53):c.993G>A (p.Gln331=)
NM_000546.6(TP53):c.375G>C (p.Thr125=)
NM_000546.6(TP53):c.549A>T (p.Ser183=)
NM_000546.6(TP53):c.801G>C (p.Arg267=)
NM_000552.5(VWF):c.7437G>A (p.Ser2479=)
NM_000552.5(VWF):c.7464C>T (p.Gly2488=)
NM_000552.5(VWF):c.3390C>T (p.Cys1130=)
NM_000552.5(VWF):c.7056C>T (p.Gly2352=)

### Apparently ClinVar Naming style depends on the form of variation occuring:
* NM_000033.4(ABCD1):c.900G>A (p.Glu300=)   means  @ aminoacid 300   Val → Met
* NM_000166.6(GJB1):c.131G>A (p.Trp44Ter)   means  @ aminoacid 44    Trp → STOP codon
* NM_000033.4(ABCD1):c.900G>A (p.Glu300=)   means  @ aminoacid 300   Glu → Glu (remains unchanged)

#### Rerun STEP 4 after cleanup (if need be)

### STEP 5 
#### Match variant transcript to corresponding protein (this will serve as reference protein)

In [25]:
run kondrashov

In [26]:
print('gene \t transcript \t protein \t changes')
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        #print(transcript)
        sites, wilds, muts = get_all_changes(gene, transcript, True)
        print(gene, '\t', transcript, '\t', translation[transcript], '\t', len(sites))

gene 	 transcript 	 protein 	 changes
ABCD1 	 NM_000033.4 	 NP_000024.2 	 327
ALPL 	 NM_000478.6 	 NP_000469.3 	 404
AR 	 NM_000044.6 	 NP_000035.2 	 269
ATP7B 	 NM_000053.4 	 NP_000044.2 	 424
BTK 	 NM_000061.3 	 NP_000052.1 	 245
CASR 	 NM_000388.4 	 NP_000379.3 	 209
CBS 	 NM_000071.3 	 NP_000062.1 	 198
CFTR 	 NM_000492.4 	 NP_000483.3 	 770
CFTR 	 NM_000492.3 	 NP_000483.3 	 2
CYBB 	 NM_000397.4 	 NP_000388.2 	 141
F7 	 NM_000131.5 	 NP_000122.1 	 1
F7 	 NM_019616.4 	 NP_062562.1 	 75
F7 	 NM_000131.4 	 NP_000122.1 	 2
F8 	 NM_000132.4 	 NP_000123.1 	 514
F9 	 NM_000133.4 	 NP_000124.1 	 271
G6PD 	 NM_001042351.3 	 NP_001035810.1 	 1
G6PD 	 NM_000402.4 	 NP_000393.4 	 42
G6PD 	 NM_001360016.2 	 NP_001035810.1 	 164
GALT 	 NM_000155.4 	 NP_000146.2 	 247
GBA1 	 NM_000157.4 	 NP_000148.2 	 293
GJB1 	 NM_000166.6 	 NP_000157.1 	 200
GJB1 	 NM_001097642.3 	 NP_000157.1 	 1
HBB 	 NM_000518.4 	 NP_000509.1 	 32
HBB 	 NM_000518.5 	 NP_000509.1 	 143
HPRT1 	 NM_000194.3 	 NP_000185.1 	 61
HPRT1 	 NM_000194.2 	 NP_000185.1 	 9
IL2RG 	 NM_000206.3 	 NP_000197.1 	 113
KCNH2 	 NM_000238.4 	 NP_000229.1 	 320
KCNQ1 	 NM_000218.3 	 NP_000209.2 	 365
L1CAM 	 NM_001278116.2 	 NP_000416.1 	 146
LDLR 	 NM_000527.4 	 NP_000518.1 	 6
LDLR 	 NM_000527.5 	 NP_000518.1 	 1090
MPZ 	 NM_000530.8 	 NP_000521.2 	 143
MYH7 	 NM_000257.4 	 NP_000248.2 	 412
TYR 	 NM_000372.5 	 NP_000363.1 	 237
PAH 	 NM_000277.3 	 NP_000268.1 	 692
PMM2 	 NM_000303.3 	 NP_000294.1 	 173
RHO 	 NM_000539.3 	 NP_000530.1 	 173
TP53 	 NM_000546.6 	 NP_000537.3 	 417
TTR 	 NM_000371.4 	 NP_000362.1 	 130
VWF 	 NM_000552.5 	 NP_000543.3 	 310

#### save output to file "gene_transcript_changes.tsv"

In [28]:
with open("gene_transcript_changes.tsv", "w") as outfile:

    # Write header
    print("gene\ttranscript\tprotein\tchanges", file=outfile)

    for gene in loci:
        transcripts = vartranscripts_filtered[gene]

        for transcript in transcripts:
            sites, wilds, muts = get_all_changes(gene, transcript, True)

            print(
                gene,
                transcript,
                translation[transcript],
                len(sites),
                sep="\t",
                file=outfile
            )

print("Results saved to 'gene_transcript_changes.tsv'")

Results saved to 'gene_transcript_changes.tsv'

### STEP 6
#### collect all valid variants in a `variants` dictionary.

In [29]:
variants = {}
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        sites, wilds, muts = get_all_changes(gene, transcript, True)
        if len(sites)>0:
            variants.update({transcript: (sites, wilds, muts)})
    print(gene, transcript, sites, wilds, muts)

ABCD1 NM_000033.4 ['291', '484', None, '389', '148', '174', '266', '401', '418', '464', '477', '515', '518', None, '606', '617', '617', None, '300', '141', '280', '466', '518', '529', '554', '560', '591', '601', None, '116', '136', '554', '609', '401', '296', '296', '430', None, '217', '389', '177', '163', '632', '189', '254', None, '679', '104', '148', '591', '660', None, '98', '174', '424', '666', '401', '296', '679', None, '281', '523', '543', '518', '668', '292', '609', '145', '152', '376', '626', None, '366', '512', '660', '107', '221', '27', '163', '198', '389', '396', '533', '658', '300', '116', '277', '298', '307', '485', '595', '640', None, None, '174', '141', '339', '407', '656', '114', '293', '382', '501', '666', '1', '148', '266', '283', '332', '343', '544', '560', '654', None, '543', '664', '567', '137', '220', '343', '472', '503', '559', '193', '194', '263', '631', '669', None, '221', '608', '633', '97', '495', '590', '636', '10', '108', '152', '617', '277', '200', '416', '291', '481', '262', '322', '380', '594', '606', '74', None, '173', '277', '161', '10', None, '132', '90', '163', None, None, '283', '163', '163', '311', '152', '507', '560', '631', '104', '608', '284', '408', '574', '667', '52', '559', '283', '174', '97', '211', '684', '510', '254', '512', '152', '285', None, '508', '629', '595', '98', None, '601', '373', '359', '513', '195', '318', '516', '672', '358', '343', '525', '510', '113', '157', '302', '339', '420', None, '507', '524', None, '484', None, '266', '336', '418', None, '571', '144', '534', None, None, '116', '667', '625', '133', '74', '504', '312', '111', '326', '298', '694', '485', None, '277', '560', None, '291', '493', '277', '152', '275', '331', '33', '84', '98', '120', '174', '263', '279', '290', None, '493', '534', '556', '591', '640', '414', '408', '611', '654', None, '529', '194', '103', '284', '306', '626', '220', '647', None, '229', '298', '511', '476', '558', None, '298', '418', '611', '665', None, '31', '132', '178', '190', '223', '254', None, '302', '511', '547', '556', '300', None, '313', '55', '401', '326', None, '533', None, '669', '211', '611', '396', '104', '194', '143', '572', None, None, '630', '632', '145', '163', '170', '547', '659', '266', '92', '419'] ['E', 'P', None, 'R', 'N', 'Y', 'G', 'R', 'R', 'R', 'E', 'S', 'R', None, 'S', 'R', 'R', None, 'E', 'A', 'R', 'Q', 'R', 'G', 'R', 'P', 'R', 'W', None, 'G', 'Q', 'R', 'E', 'R', 'Y', 'Y', 'Q', None, 'K', 'R', 'Q', 'R', 'T', 'R', 'T', None, 'W', 'R', 'N', 'R', 'R', None, 'S', 'Y', 'Q', 'Y', 'R', 'Y', 'W', None, 'Y', 'L', 'P', 'R', 'T', 'E', 'E', 'T', 'R', 'E', 'A', None, 'K', 'G', 'R', 'L', 'D', 'Y', 'R', 'T', 'R', 'A', 'K', 'T', 'E', 'G', 'G', 'G', 'Q', 'S', 'W', 'E', None, None, 'Y', 'A', 'W', 'K', 'S', 'L', 'I', 'T', 'M', 'Y', 'M', 'N', 'G', 'H', 'Q', 'G', 'Q', 'P', 'L', None, 'P', 'W', 'Q', 'W', 'L', 'G', 'Q', 'L', 'Y', 'P', 'D', 'P', 'C', 'H', None, 'D', 'G', 'S', 'H', 'I', 'Q', 'S', 'W', 'S', 'R', 'R', 'G', 'D', 'T', 'E', 'I', 'S', 'L', 'E', 'G', 'S', 'R', None, 'L', 'G', 'S', 'W', None, 'W', 'E', 'R', None, None, 'H', 'R', 'R', 'Q', 'R', 'G', 'P', 'C', 'R', 'G', 'S', 'E', 'Q', 'H', 'E', 'Y', 'H', 'Y', 'H', 'L', 'L', 'G', 'T', 'G', 'R', 'R', None, 'P', 'D', 'W', 'S', None, 'W', 'K', 'E', 'K', 'Q', 'N', 'L', 'Q', 'S', 'G', 'P', 'G', 'R', 'Q', 'E', 'W', 'H', None, 'G', 'W', None, 'P', None, 'G', 'K', 'R', None, 'Y', 'A', 'P', None, None, 'G', 'H', 'Y', 'Q', 'R', 'L', 'D', 'V', 'W', 'G', 'E', 'S', None, 'G', 'P', None, 'E', 'L', 'G', 'R', 'R', 'E', 'Y', 'P', 'S', 'R', 'Y', 'P', 'L', 'S', None, 'L', 'P', 'Q', 'R', 'E', 'G', 'E', 'Q', 'L', None, 'G', 'D', 'S', 'S', 'L', 'A', 'L', 'A', None, 'L', 'G', 'C', 'C', 'I', None, 'G', 'R', 'Q', 'K', None, 'K', 'W', 'Q', 'L', 'A', 'T', None, 'E', 'C', 'Y', 'Q', 'E', None, 'L', 'Q', 'R', 'W', None, 'K', None, 'H', 'L', 'Q', 'A', 'R', 'D', 'P', 'S', None, None, 'E', 'T', 'T', 'R', 'A', 'Y', 'H', 'G', 'G', 'V'] ['K', 'R', None, 'G', 'S', 'D', 'R', 'Q', 'W', '*', '*', 'F', 'W', None, 'L', 'H', 'C', None, 'E', 'T', 'C', '*', 'Q', 'D', 'S', 'L', 'W', '*', None, 'R', '*', 'H', 'K', 'G', 'C', 'H', '*', None, 'N', 'H', '*', 'H', 'I', 'W', 'M', None, '*', 'H', 'Y', 'Q', 'L', None, 'L', 'C', '*', '*', 'W', 'S', 'R', None, '*', 'F', 'L', 'G', 'I', 'D', 'G', 'A', 'C', '*', 'T', None, '*', 'S', 'W', 'P', 'A', 'S', 'C', 'M', 'C', 'T', 'Q', 'I', 'D', 'R', 'R', 'S', '*', '*', '*', 'G', None, None, 'S', 'V', 'R', '*', 'F', 'P', 'T', 'P', 'L', '*', 'V', 'D', 'E', 'D', '*', 'D', 'R', 'T', 'P', None, 'R', '*', '*', '*', 'P', 'R', '*', 'P', 'H', 'R', 'N', 'S', 'Y', 'R', None, 'N', 'S', 'R', 'P', 'N', '*', 'I', '*', 'L', 'S', 'G', 'V', 'N', 'R', 'D', 'T', 'W', 'P', '*', 'R', '*', 'L', None, 'P', 'W', '*', '*', None, '*', '*', 'L', None, None, 'Y', 'P', 'G', '*', 'P', 'S', 'R', 'R', 'C', 'A', '*', 'E', '*', 'D', '*', '*', 'R', '*', 'R', 'R', 'P', 'D', 'A', 'V', 'G', 'G', None, 'L', 'V', '*', 'W', None, 'S', '*', '*', '*', '*', 'I', 'P', '*', '*', 'V', 'L', 'S', 'P', '*', 'K', '*', 'P', None, 'D', 'R', None, 'S', None, 'A', 'E', 'P', None, '*', 'T', 'T', None, None, '*', 'R', '*', '*', 'W', 'F', 'G', 'M', '*', 'D', '*', '*', None, 'E', 'S', None, 'A', 'H', 'A', 'H', 'Q', 'V', '*', 'S', '*', 'P', 'H', 'L', 'P', 'W', None, 'P', 'S', 'R', 'P', 'K', 'D', '*', '*', 'Q', None, 'V', 'V', 'R', 'P', 'R', 'V', 'R', 'S', None, 'P', 'V', '*', '*', 'T', None, 'C', 'G', 'E', '*', None, '*', '*', '*', 'P', 'D', 'P', None, 'D', 'R', 'C', '*', '*', None, 'P', '*', 'L', '*', None, 'E', None, 'Y', 'P', 'H', 'E', 'P', 'E', 'A', '*', None, None, '*', 'P', 'P', 'S', 'D', 'F', 'R', 'R', 'R', 'A']
ALPL NM_000478.6 ['179', '71', '294', '71', '207', '33', '298', '378', '334', '327', '136', '162', '116', None, '417', '108', '456', '249', '176', '272', '72', '181', '223', '264', '270', '291', '297', None, '30', '44', None, None, None, '382', '455', '476', '223', '76', '468', '114', '272', '63', '184', '29', '166', '88', '141', None, '347', '106', '123', '136', '445', '459', '112', '210', '224', '348', '378', '442', '459', '294', '337', '491', '220', '221', '391', '391', '429', '487', '332', '132', '381', '308', '100', '111', '473', '476', None, '428', '191', '467', None, '275', '359', '388', '136', '317', '192', '450', '32', '40', '167', '167', None, '206', '246', '428', '341', '472', '410', '443', '219', '221', '112', '170', '382', None, '68', '71', '75', '101', '162', '178', '186', '220', '296', '326', '333', '414', '389', '219', '476', '292', '181', '493', '454', '121', '201', '72', '83', '473', '95', '1', '116', '184', '141', '179', '132', '395', '388', '153', '456', '476', None, '336', '456', '272', '327', '411', '468', '482', '399', '423', '377', '388', '191', '339', '374', '426', '446', '468', '476', '341', '40', '452', '132', '178', '299', '311', '455', '101', '297', '235', '459', '397', '351', '37', '171', '221', '291', '292', '295', '395', '93', '428', '173', '334', '466', '173', None, '285', '61', '477', '340', '389', '227', '414', '129', '51', '10', '420', '318', '341', '387', '82', '82', '176', '443', '416', '378', '386', '220', '171', '420', '420', '236', '178', '138', '71', '128', '76', '426', None, '117', '399', None, '497', '256', '268', '187', '1', None, '423', '71', '148', '307', '339', '371', '406', '490', None, '220', '177', '33', '294', '102', '359', '174', '466', '452', '184', '298', '262', '327', None, '63', '191', '391', '239', None, '297', '414', '294', '115', None, '443', '291', '58', '489', '441', '107', '195', '386', '55', None, '268', '489', '384', '221', '226', '226', '236', None, '111', '339', '66', '134', '408', None, '1', '306', None, '102', '491', '261', '218', '378', '389', '456', '162', '155', '171', '326', '76', None, None, '306', '102', '28', '445', None, '436', '106', '109', '112', '17', '134', '136', '148', '153', '154', None, None, '28', '29', '188', '199', '212', '226', '235', '236', None, '288', '289', '290', '292', '295', '297', '297', '328', None, None, '47', '334', '337', '340', '341', '348', '351', '371', '379', '386', '393', '1', '406', None, '420', '426', '426', '429', '430', None, '62', '441', '443', '62', '454', '466', '62', '478', '63', '489', '497', '497', '69', '75', '6', '84', '84', '85', '93', None, None, '101', '208', None, '235', '295', '384', '178', '447', '294', '377', '76', '146', '294', '306', '341', '356', '393', '393', '146', '396'] ['A', 'R', 'D', 'R', 'Q', 'A', 'E', 'D', 'G', 'F', 'R', 'G', 'A', None, 'N', 'P', 'G', 'G', 'A', 'R', 'I', 'S', 'R', 'K', 'W', 'E', 'Y', None, 'R', 'Q', None, None, None, 'V', 'G', 'E', 'R', 'Q', 'A', 'A', 'R', 'G', 'R', 'W', 'T', 'E', 'T', None, 'Q', 'Q', 'A', 'R', 'S', 'V', 'G', 'H', 'K', 'A', 'D', 'Q', 'V', 'D', 'D', 'G', 'G', 'G', 'R', 'R', 'E', 'A', 'E', 'A', 'H', 'S', 'T', 'A', 'G', 'E', None, 'R', 'E', 'M', None, 'L', 'I', 'Y', 'R', 'I', 'M', 'R', 'Q', 'A', 'T', 'T', None, 'Y', 'R', 'R', 'H', 'H', 'F', 'A', 'M', 'G', 'G', 'N', 'V', None, 'T', 'R', 'G', 'Y', 'G', 'Y', 'W', 'G', 'Q', 'G', 'G', 'L', 'T', 'M', 'E', 'P', 'S', 'N', 'H', 'V', 'C', 'I', 'E', 'G', 'V', 'M', 'A', 'R', 'T', 'A', 'A', 'I', 'Y', 'W', 'G', 'E', None, 'I', 'G', 'R', 'F', 'T', 'A', 'H', 'A', 'V', 'A', 'Y', 'E', 'G', 'V', 'G', 'A', 'A', 'E', 'H', 'A', 'E', 'A', 'Y', 'L', 'E', 'G', 'Y', 'Y', 'E', 'V', 'G', 'E', 'L', 'H', 'G', 'E', 'P', 'M', 'I', 'P', 'R', 'T', 'G', 'P', 'T', None, 'Y', 'G', 'Q', 'H', 'T', 'Y', 'L', 'G', 'A', 'I', 'G', 'Q', 'H', 'G', 'G', 'G', 'A', 'A', 'G', 'D', 'G', 'G', 'H', 'G', 'G', 'Y', 'Y', 'R', 'R', 'V', 'Q', 'G', None, 'Y', 'A', None, 'C', 'W', 'F', 'Y', 'M', None, 'V', 'R', 'T', 'P', 'G', 'T', 'D', 'I', None, 'G', 'A', 'A', 'D', 'N', 'I', 'P', 'P', 'E', 'R', 'E', 'R', 'F', None, 'G', 'E', 'R', 'D', None, 'Y', 'L', 'D', 'T', None, 'A', 'E', 'L', 'C', 'Y', 'V', 'E', 'G', 'I', None, 'F', 'C', 'T', 'G', 'M', 'M', 'Y', None, 'A', 'G', 'T', 'T', 'K', None, 'M', 'D', None, 'N', 'G', 'P', 'I', 'D', 'T', 'G', 'G', 'K', 'H', 'G', 'Q', None, None, 'D', 'N', 'Y', 'S', None, 'Y', 'Q', 'D', 'G', 'S', 'T', 'R', 'T', 'W', 'A', None, None, 'Y', 'W', 'S', 'Q', 'I', 'M', 'E', 'Y', None, 'G', 'L', 'F', 'P', 'M', 'Y', 'Y', 'F', None, None, 'N', 'G', 'D', 'H', 'H', 'A', 'E', 'T', 'H', 'G', 'N', 'M', 'D', None, 'G', 'G', 'G', 'E', 'N', None, 'M', 'Y', 'A', 'M', 'H', 'P', 'M', 'N', 'G', 'C', 'C', 'C', 'A', 'G', 'L', 'E', 'E', 'T', 'P', None, None, 'Y', 'L', None, 'E', 'M', 'T', 'Y', 'V', 'D', 'A', 'Q', 'E', 'D', 'D', 'H', 'D', 'N', 'N', 'E', 'F'] ['T', 'C', 'A', 'P', 'P', 'V', 'K', 'V', 'D', 'L', 'H', 'V', 'T', None, 'S', 'L', 'R', 'V', 'T', 'C', 'T', 'L', 'W', 'R', '*', 'K', '*', None, '*', '*', None, None, None, 'I', 'S', '*', 'Q', 'R', 'V', 'T', 'H', 'V', 'W', '*', 'I', 'K', 'N', None, '*', 'H', 'D', 'P', 'P', 'L', 'S', 'R', 'E', 'T', 'H', '*', 'M', 'Y', 'G', 'R', 'R', 'R', 'C', 'H', 'K', 'V', '*', 'V', 'R', '*', 'M', 'T', 'S', 'K', None, '*', '*', 'T', None, 'P', 'M', 'H', 'C', 'F', 'T', 'C', '*', 'V', 'K', 'M', None, 'C', 'S', 'P', 'R', 'R', 'L', 'V', 'V', 'C', 'A', 'D', 'D', None, 'M', 'H', 'S', '*', 'S', 'H', '*', 'A', '*', 'R', '*', 'M', 'N', 'I', 'A', 'T', 'W', 'K', 'Y', 'M', 'R', 'V', '*', 'D', 'E', 'V', 'S', 'Q', 'I', 'V', 'G', 'V', 'C', '*', 'E', 'G', None, 'T', 'A', 'L', 'C', 'A', 'T', 'N', 'S', 'A', 'V', '*', 'G', 'R', 'M', 'S', 'T', 'S', 'Q', 'Q', 'T', 'K', 'T', '*', 'P', 'K', 'D', 'C', 'N', 'D', 'A', 'V', '*', 'P', 'R', 'V', '*', 'S', 'V', 'T', 'L', 'Q', 'I', 'S', 'A', 'A', None, '*', 'E', 'K', 'Y', 'P', '*', 'V', 'E', 'V', 'T', 'A', '*', 'L', 'G', 'R', 'R', 'V', 'G', 'V', 'Y', 'D', 'V', 'D', 'D', 'S', 'C', '*', 'P', 'S', 'M', '*', 'D', None, '*', 'V', None, 'S', '*', 'L', '*', 'I', None, 'M', 'G', 'I', 'S', 'E', 'I', 'G', 'F', None, 'E', 'S', 'G', 'G', 'I', 'V', 'S', 'R', 'D', 'G', 'D', '*', 'L', None, 'C', 'Q', 'S', 'G', None, '*', 'P', 'N', 'I', None, 'T', 'Q', 'P', 'S', 'S', 'I', '*', 'R', 'N', None, 'L', 'F', 'P', 'A', 'R', 'I', '*', None, 'V', 'R', 'R', 'S', 'R', None, 'T', 'Y', None, 'T', 'R', 'S', 'T', 'G', 'A', 'W', 'D', '*', 'Y', 'V', 'H', None, None, 'V', 'K', 'D', 'C', None, 'C', 'R', 'E', 'R', 'F', 'N', 'L', 'A', 'R', 'V', None, None, 'C', 'R', 'P', '*', 'F', 'I', 'G', '*', None, 'A', 'F', 'L', 'L', 'I', 'D', 'H', 'L', None, None, 'H', 'R', 'N', 'P', 'Q', 'D', 'G', 'N', 'N', 'C', 'S', 'I', 'N', None, 'V', 'A', 'C', 'D', 'S', None, 'I', '*', 'E', 'I', 'R', 'L', 'V', 'I', 'R', 'S', 'R', 'Y', 'T', 'D', '*', 'K', 'V', 'P', 'S', None, None, 'D', 'F', None, 'V', 'L', 'K', 'C', 'L', 'E', 'T', 'E', 'A', 'H', 'G', 'Y', 'Y', 'I', 'K', '*', 'S']
AR NM_000044.6 ['775', '719', '867', '797', '591', '648', '764', '884', '597', '788', '857', '775', '608', '867', '856', '870', '60', '609', '841', '841', '878', '678', '878', '875', '903', '708', '580', '583', '2', '781', None, '174', '808', '889', None, '713', '578', '866', '690', '744', '744', '741', '702', '602', '753', '562', None, '772', '856', '74', '616', '856', '890', '608', '289', '753', '713', '574', '766', None, '914', '630', '750', '131', '743', '890', '908', '616', '697', None, '605', '813', '98', '766', '900', '90', '579', '602', '617', '726', '787', '832', '899', '107', '481', '701', '535', '72', '73', '248', '395', '563', '580', '605', '682', '696', '702', '706', '719', '724', '753', '767', '781', '865', '871', '77', '569', '685', None, None, '91', '633', '747', '843', '893', '155', '572', '781', '856', '710', '916', '68', '488', '611', '739', '741', '742', '764', '804', '780', '681', '746', '355', '742', '724', '752', '588', None, '886', None, '829', '752', '523', '581', '59', '904', '733', '890', '742', '832', '709', '709', '481', '1', '120', '773', None, '838', '839', '493', '70', '399', '403', '728', '828', None, '835', '692', '686', '832', '645', '579', '252', '583', '696', '719', '752', '904', '921', '102', '408', None, '586', '323', '740', '854', '741', '474', '386', '736', '454', '879', '773', '757', '596', '782', '691', '511', '825', '447', '780', '429', '535', '658', '723', '745', '831', '893', '187', '64', '581', '742', None, '63', '618', '687', '787', None, '625', '693', '612', '763', '1', '768', '426', '765', '365', '688', None, '871', '204', '610', '807', '586', '682', '871', '859', '905', '749', '914', '590', None, '682', '777', '856', '581', '711', '811', '602', '900', '766', '79', '596', '406', '584', '831', '1', '585', '58', '585', '860', '604', '893', '577', '691', '348', '723', '864', '587'] ['R', 'W', 'V', 'W', 'K', 'S', 'Y', 'K', 'A', 'M', 'F', 'R', 'R', 'V', 'R', 'I', 'Q', 'R', 'R', 'R', 'T', 'L', 'T', 'H', 'Q', 'L', 'C', 'F', 'E', 'M', None, 'L', 'M', 'S', None, 'L', 'G', 'S', 'H', 'G', 'G', 'S', 'L', 'C', 'R', 'I', None, 'N', 'R', 'Q', 'R', 'R', 'V', 'R', 'E', 'R', 'L', 'A', 'A', None, 'P', 'R', 'M', 'C', 'M', 'V', 'L', 'R', 'S', None, 'D', 'L', 'Q', 'A', 'I', 'Q', 'S', 'C', 'L', 'F', 'R', 'R', 'I', 'Y', 'Y', 'L', 'Y', 'Q', 'Q', 'G', 'Y', 'C', 'C', 'D', 'E', 'D', 'L', 'N', 'W', 'P', 'R', 'P', 'M', 'D', 'A', 'Q', 'G', 'V', None, None, 'Q', 'K', 'V', 'I', 'P', 'E', 'Y', 'M', 'R', 'E', 'Y', 'Q', 'Q', 'N', 'Q', 'S', 'W', 'Y', 'E', 'R', 'I', 'M', 'E', 'W', 'P', 'W', 'A', None, 'H', None, 'D', 'W', 'E', 'K', 'Q', 'V', 'D', 'V', 'W', 'R', 'G', 'G', 'Y', 'M', 'Q', 'E', None, 'E', 'L', 'Q', 'Q', 'W', 'A', 'N', 'F', None, 'Y', 'N', 'V', 'R', 'E', 'S', 'E', 'F', 'D', 'W', 'W', 'V', '*', 'R', 'Y', None, 'R', 'E', 'Y', 'S', 'S', 'E', 'R', 'A', 'G', 'F', 'E', 'N', 'C', 'Y', 'D', 'R', 'Q', 'Y', 'R', 'A', 'Y', 'Q', 'L', 'L', 'L', 'P', 'E', 'Q', 'K', 'W', None, 'Q', 'R', 'C', 'R', None, 'M', 'N', 'C', 'L', 'M', 'D', 'S', 'F', 'Y', 'A', None, 'A', 'E', 'K', 'C', 'R', 'E', 'A', 'Q', 'P', 'A', 'P', 'G', None, 'E', 'H', 'R', 'K', 'R', 'L', 'C', 'I', 'A', 'Q', 'C', 'C', 'F', 'L', 'M', 'K', 'Q', 'K', 'L', 'I', 'P', 'C', 'D', 'Y', 'L', 'L', 'A'] ['C', '*', 'M', '*', '*', 'N', 'C', '*', 'T', 'V', 'L', 'H', 'Q', 'L', 'H', 'M', '*', 'K', 'H', 'C', 'A', 'P', 'S', 'Y', 'R', 'R', 'F', 'Y', 'K', 'I', None, '*', 'T', 'S', None, 'F', 'R', 'P', 'P', 'V', 'E', 'C', 'H', 'G', '*', 'T', None, 'H', 'L', '*', 'H', 'C', 'M', '*', '*', 'L', 'I', 'P', 'D', None, 'T', 'W', 'V', '*', 'K', 'L', 'H', 'C', 'Y', None, 'H', 'P', '*', 'T', 'F', '*', 'T', 'Y', 'P', 'L', '*', 'Q', 'T', '*', '*', 'F', '*', '*', '*', 'V', '*', 'Y', 'Y', 'G', 'K', 'N', 'F', 'S', 'R', 'L', 'Q', 'A', 'I', 'N', 'V', '*', 'W', 'I', None, None, '*', '*', 'M', 'T', 'L', '*', 'C', 'K', 'S', 'K', 'S', '*', '*', 'K', 'R', 'F', 'S', 'H', 'G', 'W', 'N', 'T', '*', 'L', 'S', 'S', 'P', None, 'L', None, 'V', '*', '*', 'T', '*', 'L', 'N', 'L', '*', '*', 'E', 'V', '*', 'L', '*', 'G', None, '*', 'I', '*', '*', 'R', 'V', 'K', 'L', None, '*', 'K', 'L', 'G', '*', 'R', '*', 'L', 'V', '*', '*', 'M', 'R', '*', '*', None, '*', '*', '*', '*', 'P', 'G', 'L', 'D', 'R', 'S', 'K', 'S', 'Y', 'D', 'G', '*', 'K', '*', 'P', 'D', '*', '*', 'F', 'F', 'F', 'S', '*', '*', 'N', '*', None, '*', 'W', 'R', 'Q', None, 'V', 'K', 'S', 'V', 'I', 'Y', '*', 'L', '*', 'V', None, 'G', '*', 'E', '*', 'K', 'D', 'E', '*', 'L', 'V', 'S', 'E', None, 'G', 'D', 'P', 'R', 'G', 'P', 'F', 'M', 'S', '*', 'R', '*', 'V', 'H', 'T', 'Q', '*', 'E', 'F', 'F', 'R', 'R', 'E', '*', 'S', 'R', 'D']

### STEP 7 
#### Process each homologous alignment (/aln) and extract variable sites for each protein.

**Output:** '`variable`' dictionary with transcript IDs as keys and dictionaries of variable sites as values.

* Orig = position of aminoacid in reference protein sequence 	
* Aln = position of aminoacid after alignmemt (taking into considering gaps included)	
* Human = Aminoacid at position in human
* Others = variants observed at that position in other homologs

In [8]:
os.listdir('aln_match')

['ABCD1_NP_000024.2_match.aln',
 'ABCD1_NP_000024.2_match_1.aln',
 'ALPL_NP_000469.3_match.aln',
 'AR_NP_000035.2_match.aln',
 'ATP7B_NP_000044.2_match.aln',
 'BTK_NP_000052.1_match.aln',
 'CASR_NP_000379.3_match.aln',
 'CBS_NP_000062.1_match.aln',
 'CFTR_NP_000483.3_match.aln',
 'CYBB_NP_000388.2_match.aln',
 'F7_NP_000122.1_match.aln',
 'F7_NP_062562.1_match.aln',
 'F8_NP_000123.1_match.aln',
 'F9_NP_000124.1_match.aln',
 'G6PD_NP_000393.4_match.aln',
 'G6PD_NP_001035810.1_match.aln',
 'G6PD_NP_001346945.1_match.aln',
 'GALT_NP_000146.2_match.aln',
 'GBA1_NP_000148.2_match.aln',
 'GJB1_NP_000157.1_match.aln',
 'GJB1_NP_001091111.1_match.aln',
 'HBB_NP_000509.1_match.aln',
 'HPRT1_NP_000185.1_match.aln',
 'IL2RG_NP_000197.1_match.aln',
 'KCNH2_NP_000229.1_match.aln',
 'KCNQ1_NP_000209.2_match.aln',
 'L1CAM_NP_001265045.1_match.aln',
 'LDLR_NP_000518.1_match.aln',
 'MPZ_NP_000521.2_match.aln',
 'MYH7_NP_000248.2_match.aln',
 'PAH_NP_000268.1_match.aln',
 'PMM2_NP_000294.1_match.aln',
 'RHO_NP_000530.1_match.aln',
 'TP53_NP_000537.3_match.aln',
 'TTR_NP_000362.1_match.aln',
 'TYR_NP_000363.1_match.aln',
 'VWF_NP_000543.3_match.aln']

In [11]:
run kondrashov

In [12]:
variable = {}
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        protein = translation[transcript]
        variable.update({transcript: get_variable_sites(gene, protein, True)})
        #print(gene, transcript, protein, variable, sep= '\t')

Orig	Aln	Human	Others
6	6	R	['T', 'M']
9	9	P	['T', 'S']
10	10	W	['S']
12	12	G	['V']
13	13	N	['S', 'T']
14	14	T	['R']
21	21	L	['V']
25	25	A	['T']
29	29	A	['V']
32	32	V	['I', 'A']
35	35	L	['W']
39	39	C	['Y']
42	42	P	['L', 'S', 'V']
43	43	A	['V']
45	45	G	['D', 'V', 'S']
46	46	L	['P', 'S', 'T']
47	47	Q	['P']
48	48	A	['V', 'G']
49	49	P	['L']
50	50	A	['T']
51	51	G	['R', 'K']
52	52	E	['D']
53	53	P	['S']
54	54	T	['A', 'M']
56	56	E	['D']
57	57	A	['V', 'S']
58	58	S	['P']
60	60	V	['A', 'S']
61	61	A	['T', 'S']
62	62	A	['V', 'T']
65	65	A	['T']
67	67	M	['V']
70	70	V	['I']
76	76	L	['M']
86	86	V	['I']
87	87	L	['V']
88	88	C	['X']
89	89	R	['P']
95	95	A	['V']
99	99	A	['S', 'G']
100	100	A	['T']
128	128	R	['Q']
132	132	W	['R']
139	139	L	['F']
147	147	V	['I']
159	159	A	['T']
172	172	R	['S']
176	176	S	['A']
195	195	Q	['H']
231	231	R	['Q']
236	236	R	['H']
261	261	F	['C']
288	288	A	['S']
300	300	E	['K']
308	311	R	['H', 'Q']
312	315	D	['N', 'R', 'E']
360	363	S	['T']
361	364	D	['A']
362	365	A	['S', 'P', 'Q']
365	368	V	['M', 'T']
366	369	K	['R']
367	370	K	['H']
368	371	A	['S']
370	373	L	['V']
372	375	K	['E']
373	376	K	['R', 'E']
374	377	E	['G', 'K']
375	378	E	['K']
376	379	E	['K']
387	390	I	['K']
388	391	A	['K']
389	392	R	['K']
399	402	I	['T']
402	405	I	['K']
403	406	M	['K']
404	407	S	['K']
415	418	Y	['K']
416	419	T	['K']
417	420	A	['K']
427	430	E	['A']
429	432	V	['K']
430	433	Q	['H', 'K', 'R']
431	434	R	['H', 'K']
432	435	C	['S']
433	436	H	['R']
435	438	K	['R']
437	440	P	['A']
438	441	R	['G']
440	443	L	['P']
443	446	A	['T', 'E', 'S']
444	447	Q	['K']
445	448	A	['P', 'K', 'L']
446	449	G	['N']
447	450	S	['P']
449	452	T	['A']
450	453	I	['M']
451	454	G	['V', 'A']
452	455	R	['Q']
453	456	S	['A', 'P']
456	459	R	['H', 'Y']
457	460	V	['M', 'L']
458	461	E	['D']
460	463	P	['A', 'S']
464	467	R	['Q', 'L']
467	570	V	['R', 'Q']
470	573	V	['G', 'K']
471	574	E	['Y', 'H', 'K']
472	575	Q	['S', 'K']
474	577	I	['Q', 'R', 'K']
475	578	I	['D', 'H']
478	581	N	['A', 'T']
482	585	V	['I']
484	587	P	['H', 'K']
485	588	S	['L', 'K']
486	589	G	['H', 'K', 'Q']
487	590	E	['H', 'N']
498	601	E	['M', 'V']
499	602	E	['C', 'R']
504	607	L	['V', 'I']
511	614	C	['Q', 'K']
512	616	G	['I', 'K']
522	626	G	['P', 'K']
534	638	P	['V', 'E']
535	639	P	['S', 'K']
536	640	P	['I', 'K']
537	641	Q	['D', 'N']
548	652	M	['D', 'E']
549	653	S	['A', 'K', 'T']
550	654	V	['G', 'K']
551	655	G	['I', 'K']
560	664	P	['S']
586	690	H	['D', 'K']
587	691	H	['G', 'K']
588	692	I	['E', 'Q', 'K']
589	693	L	['G', 'S']
590	694	Q	['G', 'S']
594	698	G	['E', 'Q']
598	702	M	['S', 'P']
600	704	D	['A', 'T', 'V']
615	719	M	['L', 'K']
616	720	A	['K']
617	721	R	['G', 'K']
621	725	H	['M', 'I']
623	727	P	['R', 'Q']
626	730	A	['Q', 'R']
629	733	D	['C', 'R']
636	740	S	['V', 'M']
639	743	V	['A', 'G']
640	744	E	['Q', 'H']
700	817	E	['G', 'A', 'S']
701	818	Q	['S', 'I']
702	819	Q	['G', 'S', 'A', 'V']
703	820	L	['A', 'I', 'R']
704	821	A	['Q', 'R', 'P', 'H', 'V']
705	822	G	['N', 'D', 'S', 'C']
706	823	I	['A', 'V', 'T', 'R']
707	824	P	['S', 'Q', 'A']
708	825	K	['T', 'S']
709	826	M	['K', 'C', 'A']
710	827	Q	['K', 'C']
711	828	R	['K', 'Q', 'P']
712	829	R	['L', 'G']
713	830	L	['P', 'R', 'D']
714	831	Q	['R', 'P']
715	832	E	['P', 'T']
716	833	L	['G', 'A']
717	834	C	['P', 'F', 'T']
718	835	Q	['R', 'V']
719	836	I	['P', 'C']
720	837	L	['Q']
721	838	G	['A', 'S']
723	840	A	['K']
724	841	V	['K', 'L']
725	842	A	['K', 'S']
726	843	P	['R']
727	844	A	['R', 'W']
728	845	H	['Q', 'A']

IndexError: index out of range

#### save output to file "variable_sites.tsv"

In [31]:
with open("variable_sites.tsv", "w") as outfile:

    print("gene\ttranscript\tsite\tvariable_amino_acids", file=outfile)

    for gene in loci:
        transcripts = vartranscripts_filtered[gene]

        for transcript in transcripts:
            protein = translation[transcript]
            tmp_variable = get_variable_sites(gene, protein, True)

            variable[transcript] = tmp_variable

            for site, aas in tmp_variable.items():
                print(
                    gene,
                    transcript,
                    site,
                    ",".join(aas),
                    sep="\t",
                    file=outfile
                )

print("Saved to variable.tsv")

Orig	Aln	Human	Others
6	6	R	['T', 'M']
9	9	P	['T', 'S']
10	10	W	['S']
12	12	G	['V']
13	13	N	['S', 'T']
14	14	T	['R']
21	21	L	['V']
25	25	A	['T']
29	29	A	['V']
32	32	V	['I', 'A']
35	35	L	['W']
39	39	C	['Y']
42	42	P	['L', 'S', 'V']
43	43	A	['V']
45	45	G	['V', 'D', 'S']
46	46	L	['S', 'P', 'T']
47	47	Q	['P']
48	48	A	['V', 'G']
49	49	P	['L']
50	50	A	['T']
51	51	G	['R', 'K']
52	52	E	['D']
53	53	P	['S']
54	54	T	['A', 'M']
55	55	Q	['D']
56	56	E	['M', 'D']
57	57	A	['V', 'S', 'T']
58	58	S	['P']
60	60	V	['A', 'S', 'L']
61	61	A	['T', 'R', 'S']
62	62	A	['V', 'H', 'T']
63	63	A	['T']
64	64	K	['G']
65	65	A	['Q', 'T']
66	66	G	['S']
67	67	M	['V']
68	68	N	['A', 'D']
70	70	V	['I']
76	76	L	['M']
86	86	V	['I']
87	87	L	['V']
88	88	C	['X']
89	89	R	['P']
95	95	A	['V']
97	97	H	['Q']
98	98	S	['T']
99	99	A	['S', 'G']
100	100	A	['L', 'T']
128	128	R	['Q']
132	132	W	['R']
134	134	L	['V']
136	136	Q	['V']
137	137	W	['L']
139	139	L	['A', 'F']
140	140	I	['V']
143	143	P	['Q']
147	147	V	['I']
159	159	A	['T']
172	172	R	['S']
176	176	S	['A']
195	195	Q	['H']
231	231	R	['Q']
236	236	R	['H']
237	237	G	['E']
240	240	T	['P']
261	261	F	['C']
265	265	F	['Y']
267	267	E	['A']
268	268	L	['N']
269	269	V	['M']
270	270	A	['E']
271	271	E	['D']
272	272	E	['S']
273	273	A	['V']
274	274	R	['C']
275	275	R	['C']
276	276	K	['R']
277	277	G	['D']
278	278	E	['Y']
279	279	L	['V']
282	282	M	['R']
288	288	A	['S']
300	300	E	['K']
301	304	V	['L']
302	305	E	['P']
304	307	A	['R']
305	308	L	['V']
306	309	L	['V']
307	310	Q	['K']
308	311	R	['H', 'Q']
309	312	S	['F']
312	315	D	['N', 'E', 'R']
340	343	S	['T']
341	344	A	['S']
360	363	S	['T', 'Q']
361	364	D	['E', 'A']
362	365	A	['P', 'S', 'Q']
365	368	V	['M', 'T']
366	369	K	['R']
367	370	K	['H']
368	371	A	['S']
370	373	L	['V']
371	374	E	['N']
372	375	K	['G', 'E']
373	376	K	['R', 'E']
374	377	E	['G', 'K']
375	378	E	['K']
376	379	E	['K']
387	390	I	['K']
388	391	A	['K']
389	392	R	['K']
399	402	I	['T']
402	405	I	['K']
403	406	M	['K']
404	407	S	['K']
415	418	Y	['K']
416	419	T	['K']
417	420	A	['K']
427	430	E	['A']
429	432	V	['K']
430	433	Q	['R', 'H', 'K']
431	434	R	['H', 'K']
432	435	C	['S']
433	436	H	['R']
435	438	K	['R']
437	440	P	['A']
438	441	R	['G']
440	443	L	['P']
443	446	A	['T', 'E', 'S']
444	447	Q	['K']
445	448	A	['P', 'L', 'K']
446	449	G	['N']
447	450	S	['P']
449	452	T	['A']
450	453	I	['M']
451	454	G	['V', 'A']
452	455	R	['Q']
453	456	S	['P', 'A']
456	459	R	['H', 'Y']
457	460	V	['M', 'L']
458	461	E	['D']
460	463	P	['A', 'S']
464	467	R	['Q', 'L']
467	570	V	['Q']
469	572	D	['E']
470	573	V	['K']
471	574	E	['K']
472	575	Q	['K']
478	581	N	['K']
479	582	I	['V']
481	584	I	['V']
482	585	V	['I', 'S']
483	586	T	['V']
484	587	P	['K']
485	588	S	['T', 'A', 'K']
486	589	G	['K']
491	594	A	['T']
495	598	I	['M']
496	599	R	['K']
497	600	V	['R']
498	601	E	['K', 'W']
499	602	E	['P']
500	603	G	['L']
501	604	M	['S']
502	605	H	['Q']
504	607	L	['G']
505	608	I	['N']
506	609	T	['G', 'H']
507	610	G	['S']
509	612	N	['D', 'K', 'A', 'R', 'S']
510	613	G	['S', 'K']
511	614	C	['K', 'R']
512	616	G	['K']
513	617	K	['R']
514	618	S	['Q']
515	619	S	['A']
516	620	L	['R']
517	621	F	['W']
519	623	I	['V', 'R']
520	624	L	['R']
521	625	G	['S']
524	628	W	['K', 'L']
525	629	P	['K', 'M']
526	630	T	['K', 'W', 'S']
527	631	Y	['N']
528	632	G	['R']
530	634	V	['S']
531	635	L	['S']
532	636	Y	['A', 'T', 'C']
533	637	K	['R', 'E']
534	638	P	['T', 'K']
535	639	P	['S', 'A']
537	641	Q	['S', 'P']
538	642	R	['Q', 'L']
539	643	M	['K', 'G']
540	644	F	['K', 'A']
541	645	Y	['N', 'S']
542	646	I	['L', 'V']
543	647	P	['S']
544	648	Q	['P', 'S', 'H', 'A']
545	649	R	['S']
546	650	P	['A']
547	651	Y	['G', 'L']
548	652	M	['V', 'L']
549	653	S	['V', 'T']
550	654	V	['L', 'I']
551	655	G	['L', 'C']
552	656	S	['T', 'G']
553	657	L	['F']
554	658	R	['Q']
555	659	D	['E', 'N']
556	660	Q	['K', 'R', 'P']
557	661	V	['E', 'W', 'K']
558	662	I	['N', 'W', 'L']
559	663	Y	['C', 'W', 'L']
560	664	P	['A']
561	665	D	['A']
563	667	V	['T']
564	668	E	['A', 'G']
567	671	Q	['R']
570	674	G	['K']
571	675	Y	['H', 'K']
572	676	S	['K']
574	678	Q	['R', 'K']
575	679	D	['H']
578	682	A	['T']
582	686	V	['I']
584	688	H	['K']
585	689	L	['K']
586	690	H	['Q', 'K']
587	691	H	['N']
593	697	G	['S']
596	700	E	['R']
597	701	A	['K']
598	702	M	['V', 'A']
599	703	C	['R']
604	708	V	['I']
611	715	Q	['K', 'R']
612	716	R	['K', 'Q']
613	717	I	['K']
615	719	M	['L']
616	720	A	['S']
623	727	P	['K']
630	734	E	['I']
632	736	T	['S']
634	738	A	['Q']
635	739	V	['E']
636	740	S	['K']
637	741	I	['K']
638	742	D	['N']
649	753	D	['E']
650	754	A	['K', 'T']
651	755	G	['K']
652	756	I	['K']
654	758	L	['P']
655	759	L	['M', 'V']
656	760	S	['A', 'C', 'R']
657	761	I	['A', 'L', 'V']
658	762	T	['A', 'H', 'S']
659	763	H	['R', 'T', 'V']
660	764	R	['A', 'C']
661	765	P	['S', 'L']
662	766	S	['R', 'C', 'A']
663	767	L	['V', 'S', 'M']
665	782	K	['V']
666	783	Y	['C']
674	791	D	['K']
675	792	G	['K']
676	793	E	['Q', 'K']
677	794	G	['S']
678	795	G	['S']
682	799	E	['Q']
684	801	L	['V']
685	802	D	['G']
686	803	S	['P']
687	804	A	['G']
688	805	A	['T', 'P', 'V']
690	807	L	['T']
691	808	S	['V']
692	809	L	['V']
693	810	T	['C']
694	811	E	['S']
695	812	E	['T']
696	813	K	['S']
697	814	Q	['P']
698	815	R	['H']
699	816	L	['P']
700	817	E	['S']
703	820	L	['K']
704	821	A	['K']
705	822	G	['K']
707	824	P	['A', 'T']
708	825	K	['W', 'C']
709	826	M	['V', 'I', 'S', 'L']
710	827	Q	['K', 'T', 'R']
711	828	R	['Q', 'M', 'L', 'S']
712	829	R	['I', 'P', 'H']
713	830	L	['R', 'C']
714	831	Q	['N', 'G', 'R', 'H']
715	832	E	['K', 'P', 'D']
716	833	L	['T', 'M']
717	834	C	['R', 'S', 'G']
718	835	Q	['H']
724	841	V	['M', 'L']
725	842	A	['G']
727	844	A	['G', 'T']
728	845	H	['Q', 'L', 'E']
729	883	V	['P', 'A', 'L', 'S']
730	884	P	['L', 'G', 'W', 'Q']
731	885	A	['S', 'V', 'N']
732	886	P	['L', 'H', 'D', 'Q']
733	887	S	['G', 'R', 'W', 'A', 'Y', 'C', 'L']
734	888	P	['S', 'V', 'C', 'L', 'I']
735	889	Q	['E', 'M', 'A', 'V', 'T']
736	890	G	['D', 'A', 'Q', 'R', 'T']
737	927	P	['A']
738	928	G	['A', 'V', 'Q', 'S']
739	938	G	['S', 'P', 'A', 'R', 'V']
740	939	L	['R', 'A', 'M', 'I', 'K', 'V']
741	940	Q	['S', 'A', 'P', 'D', 'E', 'R', 'H', 'V']
742	941	G	['P', 'S', 'N', 'D', 'A', 'F', 'E', 'C']
743	942	A	['T', 'L', 'V', 'H', 'S', 'E', 'R']
744	943	S	['E', 'A', 'Q', 'H', 'G', 'P']
745	944	T	['S', 'K', 'A']
Orig	Aln	Human	Others
1	76	M	['P']
2	77	I	['S', 'V']
3	78	S	['Q']
4	79	P	['A', 'H']
5	80	F	['L']
6	81	L	['Q', 'V']
7	82	V	['P', 'L', 'I']
8	83	L	['T']
9	84	A	['W', 'V']
10	85	I	['V']
11	86	G	['K']
12	87	T	['D']
13	88	C	['E']
15	90	T	['M', 'A', 'S']
16	91	N	['S', 'D', 'H']
17	92	S	['E', 'C']
18	93	L	['F', 'K']
19	94	V	['G']
20	95	P	['K']
21	96	E	['G']
22	97	K	['M']
23	98	E	['L']
24	99	K	['G']
25	100	D	['M']
26	101	P	['T']
27	102	K	['W', 'E', 'L', 'G']
28	103	Y	['S', 'G', 'T']
29	104	W	['F', 'L']
30	105	R	['S']
31	106	D	['S', 'N', 'R', 'G']
32	107	Q	['S', 'R']
33	108	A	['T', 'R']
34	109	Q	['P', 'A']
35	110	E	['T', 'Q', 'M', 'K']
36	111	T	['W', 'V']
37	112	L	['P']
38	117	K	['R']
39	118	Y	['H', 'N']
40	119	A	['C']
42	121	E	['G', 'K']
43	122	L	['M']
44	123	Q	['S']
45	124	K	['E', 'R']
46	125	L	['I']
47	126	N	['D']
48	127	T	['A']
49	128	N	['L']
50	129	V	['N']
51	130	A	['R']
52	131	K	['H']
53	132	N	['F']
54	133	V	['Q']
55	134	I	['K']
56	135	M	['R']
57	136	F	['E']
58	137	L	['G']
60	139	D	['P']
62	156	M	['F']
63	157	G	['S']
64	158	V	['R']
65	159	S	['T']
66	160	T	['P']
67	161	V	['M', 'L']
68	162	T	['S', 'L']
69	163	A	['S', 'P']
70	164	A	['C', 'T', 'S']
71	165	R	['S', 'L']
72	166	I	['W', 'A']
73	167	L	['E']
74	168	K	['M', 'T']
76	170	Q	['S']
77	171	L	['C']
78	172	H	['R', 'S']
79	173	H	['N', 'P']
80	174	N	['R']
81	175	P	['T']
82	176	G	['R']
84	178	E	['R']
85	179	T	['P']
86	180	R	['K', 'M', 'L']
88	182	E	['T']
89	183	M	['P']
90	184	D	['P']
91	185	K	['E']
92	202	F	['L']
93	203	P	['T']
94	204	F	['L']
95	205	V	['M', 'L']
96	206	A	['S']
97	207	L	['H']
98	208	S	['L']
99	209	K	['Q']
137	247	S	['T']
138	248	R	['Q']
152	262	R	['H']
209	319	M	['V']
213	323	R	['K']
214	324	D	['N']
216	326	D	['E']
231	341	K	['R']
238	348	S	['I', 'M', 'T']
251	361	D	['N']
253	363	V	['I']
254	364	D	['N']
255	365	T	['I', 'V']
258	368	S	['N']
262	372	R	['K', 'T']
263	373	Y	['H', 'R', 'N', 'D']
266	391	S	['T']
269	394	I	['V']
273	398	T	['S']
276	401	L	['M']
277	402	T	['A', 'K', 'N']
279	404	D	['N']
280	405	P	['L']
281	406	H	['Y', 'N', 'S']
282	407	N	['T', 'A']
295	420	M	['L']
296	421	Q	['E']
304	429	V	['L', 'M']
310	435	S	['T']
314	439	V	['E', 'T', 'K', 'G']
318	443	Q	['R']
319	444	I	['V']
321	446	R	['Q', 'K']
325	450	K	['R']
357	482	R	['Q']
360	485	G	['E']
361	486	Q	['L', 'R']
363	488	G	['D']
364	489	S	['N', 'I', 'T', 'D']
365	490	L	['M', 'I']
368	493	S	['L', 'T']
369	494	E	['G', 'Q']
402	527	L	['V']
425	550	G	['D']
433	558	M	['T']
437	562	A	['V']
438	563	H	['N', 'Y', 'L']
439	564	N	['K', 'R']
440	565	N	['T']
441	566	Y	['L']
442	567	Q	['R']
443	568	A	['L']
444	569	Q	['V', 'C']
445	570	S	['H', 'D']
446	571	A	['P', 'F']
447	572	V	['I', 'T']
448	573	P	['F']
449	574	L	['Y']
450	582	R	['P']
451	583	H	['Y', 'S', 'F']
452	584	E	['G', 'R']
453	585	T	['S']
454	586	H	['R']
456	588	G	['S']
457	589	E	['K']
459	591	V	['A']
461	593	V	['M']
462	594	F	['L']
463	595	S	['A', 'T']
464	596	K	['T']
465	597	G	['T']
466	598	P	['T']
467	599	M	['R']
468	600	A	['R']
469	601	H	['S']
472	604	H	['C']
473	605	G	['P']
474	606	V	['C']
475	607	H	['A']
476	608	E	['T']
477	609	Q	['R']
478	610	N	['P']
479	611	Y	['T']
480	612	V	['I', 'A']
481	613	P	['G']
482	614	H	['R']
483	615	V	['M']
486	618	Y	['W']
487	619	A	['P']
488	620	A	['S']
489	621	C	['S']
490	622	I	['V', 'P']
491	623	G	['R']
493	625	N	['P']
494	626	L	['V', 'W']
495	627	G	['D', 'N', 'H']
496	628	H	['T']
498	630	A	['T', 'C']
499	631	P	['H', 'Q', 'S', 'R', 'T']
502	634	S	['A', 'M', 'P']
503	635	A	['S']
504	636	G	['R', 'S']
505	637	S	['G', 'N', 'T']
506	638	L	['P', 'T']
507	639	A	['S']
508	640	A	['P', 'L']
509	641	G	['V', 'T']
510	642	P	['A']
512	644	L	['F']
514	646	A	['P', 'S', 'L']
515	647	L	['K']
516	648	A	['R']
517	649	L	['V']
518	650	Y	['F', 'L']
519	651	P	['S']
520	652	L	['M']
521	653	S	['R', 'G', 'K']
522	654	V	['I', 'S', 'M', 'H']
523	655	L	['V']
Orig	Aln	Human	Others
1	3	M	['S']
2	4	E	['R', 'C', 'D']
3	5	V	['L']
4	6	Q	['L']
6	8	G	['N']
7	9	L	['N']
8	10	G	['M']
9	11	R	['A']
10	12	V	['K', 'A']
11	13	Y	['M', 'P']
12	14	P	['L', 'T']
13	15	R	['I', 'L']
14	16	P	['Q', 'L']
15	17	P	['G']
16	18	S	['L', 'A']
17	19	K	['G', 'P']
18	20	T	['V']
19	21	Y	['W']
20	22	R	['K']
21	23	G	['S']
22	24	A	['P']
23	25	F	['P']
24	26	Q	['G']
25	27	N	['Q']
26	28	L	['V']
27	29	F	['T']
28	30	Q	['E']
29	31	S	['A', 'V']
30	32	V	['L']
31	33	R	['K', 'S']
32	34	E	['V', 'L']
33	35	V	['A', 'L']
35	37	Q	['L']
36	38	N	['D', 'G']
37	39	P	['V', 'S']
39	41	P	['T', 'S', 'Y', 'H']
40	42	R	['Y']
42	44	P	['I', 'L']
43	45	E	['D']
44	46	A	['C']
45	47	A	['V']
46	48	S	['H']
47	49	A	['V']
48	50	A	['Y']
49	51	P	['Q', 'A']
50	52	P	['N', 'A', 'V']
51	53	G	['E', 'S']
52	54	A	['N', 'L']
53	55	S	['R', 'E', 'G', 'D', 'H']
54	56	L	['V']
55	57	L	['G', 'Q']
56	58	L	['V']
57	59	L	['A', 'Q']
58	60	Q	['I']
60	62	Q	['E']
61	63	Q	['K']
62	64	Q	['L']
63	65	Q	['R']
64	66	Q	['E']
66	68	Q	['V']
67	69	Q	['V']
68	70	Q	['K']
69	71	Q	['R', 'P']
70	72	Q	['R']
72	74	Q	['P']
73	75	Q	['L', 'P']
74	76	Q	['P', 'H']
75	77	Q	['P', 'N']
76	78	Q	['P', 'R']
77	83	Q	['P', 'E', 'H']
78	84	Q	['P', 'E']
79	85	Q	['P', 'L']
80	86	Q	['F']
81	87	E	['Q', 'I', 'H']
82	88	T	['V']
84	90	P	['K']
85	91	R	['P', 'L', 'S']
86	94	Q	['T']
87	95	Q	['R', 'Y']
88	96	Q	['E', 'H']
89	97	Q	['E']
90	101	Q	['K', 'D']
91	102	Q	['G', 'T']
92	104	G	['V', 'S']
93	105	E	['K', 'D', 'G']
94	106	D	['N', 'G', 'K']
95	107	G	['S', 'A', 'R']
96	108	S	['C', 'E']
97	109	P	['Q']
98	110	Q	['K', 'F']
99	111	A	['T', 'S', 'V']
100	112	H	['Q', 'L', 'G']
101	113	R	['S', 'G', 'D']
102	114	R	['D', 'H']
103	115	G	['N', 'L', 'S']
104	116	P	['R', 'K', 'A']
105	117	T	['L', 'D', 'R']
106	118	G	['D']
107	119	Y	['F']
108	120	L	['E']
109	121	V	['A', 'D']
110	122	L	['T']
111	123	D	['Y', 'S']
112	124	E	['G', 'L', 'R']
113	125	E	['I', 'S']
114	126	Q	['R', 'H', 'E']
115	127	Q	['W', 'M', 'E']
116	128	P	['S', 'V', 'H']
117	129	S	['T']
118	130	Q	['G']
119	131	P	['Q', 'F', 'S']
120	132	Q	['K', 'E']
121	133	S	['P', 'I', 'T']
122	134	A	['G', 'S']
123	135	L	['P', 'K', 'T']
124	136	E	['D', 'V']
125	137	C	['F', 'S']
126	138	H	['F', 'E']
127	139	P	['M', 'H']
128	140	E	['D', 'P', 'K']
129	141	R	['S']
130	142	G	['S', 'R']
131	143	C	['S']
132	144	V	['E']
134	146	E	['S']
135	147	P	['S']
136	148	G	['E', 'A']
137	149	A	['V']
138	150	A	['D', 'S']
139	151	V	['A', 'T', 'Y', 'F']
140	152	A	['V', 'D']
141	153	A	['Y']
142	154	S	['G']
143	155	K	['E']
144	156	G	['E']
145	157	L	['Y']
146	158	P	['Q', 'D']
147	159	Q	['N']
148	160	Q	['E']
149	161	L	['P']
150	162	P	['S']
153	165	P	['S', 'L']
154	166	D	['E']
155	167	E	['D']
156	168	D	['N', 'S']
157	169	D	['G']
158	170	S	['N']
159	171	A	['V']
160	172	A	['V']
163	175	T	['D']
164	176	L	['T']
165	177	S	['N', 'A']
166	178	L	['I']
170	182	T	['Q']
171	183	F	['I']
173	185	G	['S']
174	186	L	['Y']
175	187	S	['N']
176	188	S	['D']
177	189	C	['T']
178	190	S	['W']
179	191	A	['V']
180	192	D	['A', 'Q']
181	193	L	['M']
182	194	K	['E', 'D']
183	195	D	['E', 'M', 'K']
184	196	I	['L', 'V']
185	197	L	['V', 'T']
186	198	S	['D', 'N']
187	199	E	['D']
188	200	A	['G', 'S']
189	201	S	['G', 'L', 'V', 'P']
190	202	T	['V', 'R', 'S']
191	203	M	['K', 'V', 'L']
193	206	L	['V']
194	207	L	['V']
195	208	Q	['K']
196	209	Q	['P', 'R']
197	210	Q	['P']
199	212	Q	['N']
200	213	E	['K']
201	214	A	['T']
202	215	V	['E']
203	216	S	['C']
204	217	E	['K']
205	218	G	['N']
206	219	S	['R', 'N', 'T']
208	221	S	['N', 'G', 'D']
209	222	G	['K']
210	223	R	['P']
211	224	A	['V', 'K']
213	226	E	['K']
214	227	A	['K', 'T']
215	228	S	['A', 'T', 'K']
217	230	A	['G']
218	231	P	['S', 'A', 'K']
219	232	T	['S', 'I', 'N']
220	233	S	['A', 'G']
221	234	S	['K']
222	235	K	['N']
223	236	D	['R']
224	237	N	['S', 'R']
225	238	Y	['N']
226	239	L	['R']
227	240	G	['V', 'K', 'E']
228	241	G	['K']
229	242	T	['K']
230	243	S	['N']
231	244	T	['S', 'P']
232	245	I	['C']
233	246	S	['N']
234	247	D	['A']
235	248	N	['S', 'E']
236	249	A	['F', 'P']
237	250	K	['Q']
238	251	E	['N']
239	252	L	['F']
240	253	C	['I']
241	254	K	['N']
242	255	A	['S']
243	256	V	['F']
244	257	S	['N']
248	261	G	['A']
249	262	L	['I']
251	264	V	['I']
252	265	E	['S']
253	266	A	['N', 'T']
254	267	L	['F']
255	268	E	['N']
258	271	S	['Q', 'N']
259	272	P	['V']
260	273	G	['E']
261	274	E	['D', 'M', 'T']
262	275	Q	['I', 'H']
263	276	L	['I']
264	277	R	['N', 'H']
266	279	D	['E']
268	281	M	['K']
270	283	A	['K', 'I']
271	284	P	['S', 'E', 'Q']
272	285	L	['V', 'G', 'H']
274	287	G	['K', 'E', 'V']
275	288	V	['G', 'Y']
276	289	P	['K']
277	290	P	['L', 'S']
278	291	A	['S', 'G']
280	293	R	['N']
281	294	P	['Q']
282	295	T	['I', 'S']
283	296	P	['E']
285	298	A	['H', 'T']
286	299	P	['S', 'V']
287	300	L	['Y', 'T']
288	301	A	['L', 'C', 'G']
289	302	E	['K']
291	304	K	['Q']
292	305	G	['Q']
293	306	S	['P', 'E']
294	307	L	['Y']
295	308	L	['F']
296	309	D	['G']
297	310	D	['E']
298	311	S	['R', 'T', 'G']
299	312	A	['C']
300	313	G	['D']
301	314	K	['E']
302	315	S	['G', 'T', 'R', 'K']
303	316	T	['Q', 'S']
304	317	E	['M']
305	318	D	['E', 'K']
306	319	T	['P', 'L']
307	320	A	['I', 'H', 'V']
308	321	E	['Q', 'S']
309	322	Y	['M']
310	324	S	['T', 'C']
311	325	P	['Q']
312	326	F	['S']
315	329	G	['S']
317	331	T	['A']
318	332	K	['Q']
319	333	G	['V']
320	334	L	['I']
322	336	G	['V']
323	337	E	['D']
324	338	S	['T']
326	340	G	['V']
328	342	S	['P']
331	345	A	['S', 'G']
332	346	A	['E']
333	347	A	['G']
335	349	S	['T', 'N']
336	350	S	['A']
338	352	T	['V', 'A']
341	355	L	['I']
342	356	P	['D']
343	357	S	['C']
344	358	T	['S', 'A']
346	360	S	['P']
354	368	D	['E']
356	370	A	['T']
357	371	A	['V', 'T']
358	372	A	['S', 'P']
361	375	S	['N']
363	377	D	['E']
369	383	L	['I']
370	384	A	['V', 'T']
371	385	L	['V']
372	386	A	['T']
373	387	G	['A']
374	388	P	['Y']
375	389	P	['S']
377	391	P	['L']
378	392	P	['G']
379	393	P	['L', 'S']
381	395	P	['D']
382	396	H	['R']
386	400	R	['K']
388	402	K	['A']
390	404	E	['A']
391	405	N	['A']
392	406	P	['I', 'Q']
393	407	L	['A']
394	408	D	['A']
395	409	Y	['F']
396	410	G	['S', 'M']
398	412	A	['S']
399	413	W	['V']
400	414	A	['L', 'I', 'P']
401	415	A	['K', 'L']
402	416	A	['P', 'T']
403	417	A	['E']
404	418	A	['D', 'V', 'T']
405	419	Q	['P']
406	420	C	['S']
407	421	R	['L']
408	422	Y	['F', 'L']
409	423	G	['E']
412	426	A	['T']
416	430	G	['S']
417	431	A	['G', 'T']
418	432	G	['V']
419	433	A	['P', 'T']
420	434	A	['T']
421	435	G	['A']
422	436	P	['S', 'Q']
423	437	G	['S']
428	442	S	['R']
429	443	A	['I']
430	444	A	['K', 'S']
432	446	S	['A', 'I']
433	447	S	['A']
434	448	S	['A']
435	449	W	['K']
437	451	T	['N', 'A']
438	452	L	['K', 'V']
439	453	F	['T', 'I']
441	455	A	['V']
442	456	E	['Q', 'D']
443	457	E	['L', 'Q']
444	458	G	['R']
445	459	Q	['R']
446	460	L	['Q', 'V']
449	463	P	['Q']
464	482	G	['S']
465	483	G	['C']
468	486	G	['A', 'S']
470	488	G	['A']
471	489	G	['S', 'A']
472	490	G	['A']
473	491	G	['D']
475	493	A	['T', 'S']
477	495	A	['S']
478	496	V	['I']
479	497	A	['T', 'N', 'V', 'D']
484	502	T	['S', 'N', 'P']
487	505	P	['S', 'L']
492	510	G	['S']
495	513	S	['G']
498	516	T	['P']
507	525	G	['S']
508	526	M	['V']
509	527	V	['L', 'M']
510	528	S	['I', 'R']
511	529	R	['G']
512	530	V	['F']
514	532	Y	['M']
515	533	P	['Q']
516	538	S	['N']
517	539	P	['L']
518	540	T	['S', 'V']
519	541	C	['V']
520	542	V	['I']
521	543	K	['P']
522	544	S	['K']
523	545	E	['S']
524	546	M	['V', 'T']
525	547	G	['T', 'S']
528	550	M	['V']
529	551	D	['E', 'R']
530	552	S	['R', 'T', 'N', 'K']
531	553	Y	['I']
532	554	S	['A', 'E']
533	555	G	['E']
534	556	P	['N', 'E']
535	557	Y	['F', 'A']
536	558	G	['K', 'E']
537	559	D	['V', 'E', 'Y']
538	560	M	['F', 'V', 'H', 'R']
539	561	R	['D', 'S', 'K']
540	562	L	['F']
541	563	E	['N']
542	564	T	['L']
543	565	A	['S', 'T', 'R']
544	566	R	['S']
545	567	D	['Q', 'K']
546	568	H	['D', 'R']
547	569	V	['M', 'L']
548	570	L	['T', 'W']
549	571	P	['T']
550	572	I	['L']
551	573	D	['L', 'S']
552	574	Y	['S', 'F']
554	576	F	['N']
555	577	P	['R']
556	578	P	['N']
557	579	Q	['W']
558	580	K	['R']
559	581	T	['V']
561	583	L	['A']
562	584	I	['L']
563	585	C	['L']
590	612	G	['A']
591	613	K	['P']
592	614	Q	['E']
593	615	K	['R']
594	616	Y	['L']
595	617	L	['I']
596	618	C	['N', 'I', 'E']
597	619	A	['R']
598	620	S	['K', 'Q']
599	621	R	['I', 'C', 'K']
600	622	N	['S']
601	623	D	['S', 'H', 'F']
602	624	C	['T']
603	625	T	['I', 'S', 'G']
604	626	I	['C', 'A']
605	627	D	['S', 'N']
606	628	K	['P', 'H', 'N']
607	629	F	['L', 'Q', 'R']
608	630	R	['S', 'N']
609	631	R	['H', 'E', 'Q', 'L', 'S']
610	632	K	['E', 'T', 'H']
611	633	N	['D', 'E', 'L']
612	634	C	['Y', 'V', 'G', 'L']
613	635	P	['N']
614	636	S	['F', 'V']
615	637	C	['H', 'R', 'A']
616	638	R	['E', 'A', 'Q']
617	639	L	['E', 'Q', 'I', 'A']
618	640	R	['F', 'K', 'A', 'S']
629	651	A	['E', 'V', 'G']
630	652	R	['A', 'K', 'D', 'V']
631	653	K	['V', 'F', 'A', 'L']
632	654	L	['V', 'R', 'G']
640	662	L	['V']
646	668	A	['T']
649	671	T	['A']
650	672	T	['S']
653	675	T	['N']
654	676	E	['D']
656	678	T	['S', 'P']
657	679	T	['A', 'S']
665	687	I	['V']
708	730	L	['V']
709	731	G	['V', 'S']
710	732	E	['S', 'N']
711	733	R	['E', 'C', 'Y']
712	734	Q	['R', 'K']
713	735	L	['I', 'H']
714	736	V	['L']
715	737	H	['K', 'R', 'G']
716	738	V	['M', 'L']
717	739	V	['T', 'F', 'A']
718	740	K	['G', 'R']
719	741	W	['V', 'P', 'T']
720	742	A	['S']
721	743	K	['E', 'A']
722	744	A	['W', 'C']
723	745	L	['F']
737	759	V	['I']
809	831	K	['E']
810	832	A	['R']
812	834	L	['P']
813	835	L	['S']
814	836	F	['D']
816	838	I	['Q']
817	839	I	['L']
818	840	P	['L']
819	841	V	['I']
820	842	D	['H']
821	843	G	['N']
822	844	L	['R']
823	845	K	['D']
824	846	N	['Q']
825	847	Q	['P']
826	848	K	['F']
828	850	F	['V']
830	852	E	['D']
831	853	L	['S']
832	854	R	['F']
833	855	M	['L']
834	856	N	['A']
835	857	Y	['A']
836	858	I	['F']
837	859	K	['E']
838	860	E	['N']
839	861	L	['H']
840	862	D	['I']
841	863	R	['L']
842	864	I	['L']
844	866	A	['N']
848	870	K	['A']
849	871	N	['A']
850	872	P	['S']
851	873	T	['V']
852	874	S	['N', 'H']
853	875	C	['F']
854	876	S	['E']
878	900	T	['X']
887	909	M	['A']
888	910	V	['A']
891	913	D	['H']
Orig	Aln	Human	Others
1	144	M	['S', 'N', 'G', 'Q']
2	145	P	['T', 'A']
3	146	E	['K', 'P', 'T', 'S', 'I', 'V']

## Identify putative CPDs

### STEP 8
#### Next we compare and dentify pathogenic variants () that are nevertheless observed as natural amino acid substitutions in the homologs alignment

In [32]:
print('gene\ttranscript\tsite\twild\tmut\tvar')
final_transcripts = variants.keys()
for gene in loci:
    transcripts = vartranscripts_filtered[gene]
    for transcript in transcripts:
        if transcript in final_transcripts:
            sites, wilds, muts = variants[transcript]
            #print(gene, transcript, sites, wilds, muts)
            tmp_variable = variable[transcript]
            #print(tmp_variable)
            variable_sites = tmp_variable.keys()
            #print(variable_sites)
            n= len(sites)
            for i in range(n):
                if sites[i] is None:
                    continue
                site = int(sites[i])
                #print(sites)
                #print(type(site))
                #print(type(next(iter(variable_sites))))
                #if (site in variable_sites) and (muts[i] in tmp_variable[site]):
                if (site in tmp_variable) and (muts[i] in tmp_variable[site]):
                    print(gene, transcript, site, wilds[i], muts[i], tmp_variable[site], sep= '\t')

gene	transcript	site	wild	mut	var
ABCD1	NM_000033.4	654	L	P	['P']
ABCD1	NM_000033.4	507	G	S	['S']
ABCD1	NM_000033.4	510	G	S	['S', 'K']
ABCD1	NM_000033.4	534	P	T	['T', 'K']
ABCD1	NM_000033.4	556	Q	R	['K', 'R', 'P']
ABCD1	NM_000033.4	511	C	R	['K', 'R']
ABCD1	NM_000033.4	533	K	E	['R', 'E']
ABCD1	NM_000033.4	659	H	R	['R', 'T', 'V']
ALPL	NM_000478.6	491	G	R	['R']
ALPL	NM_000478.6	459	V	A	['A']
ALPL	NM_000478.6	37	L	P	['P']
ALPL	NM_000478.6	82	G	R	['R']
ALPL	NM_000478.6	82	G	R	['R']
ALPL	NM_000478.6	71	R	S	['S', 'L']
ALPL	NM_000478.6	489	C	S	['S']
ALPL	NM_000478.6	491	G	R	['R']
ALPL	NM_000478.6	454	H	R	['R']
ALPL	NM_000478.6	489	C	S	['S']
ALPL	NM_000478.6	85	T	P	['P']
ALPL	NM_000478.6	295	M	L	['L']
AR	NM_000044.6	713	L	I	['I', 'H']
AR	NM_000044.6	709	G	V	['V', 'S']
AR	NM_000044.6	723	L	F	['F']
AR	NM_000044.6	610	K	E	['E', 'T', 'H']
ATP7B	NM_000053.4	969	R	Q	['Q']
ATP7B	NM_000053.4	858	T	A	['A']
ATP7B	NM_000053.4	335	G	E	['E', 'R']
CBS	NM_000071.3	539	L	S	['G', 'P', 'Q', 'A', 'V', 'S']
CBS	NM_000071.3	85	G	R	['R']
CBS	NM_000071.3	456	L	P	['P', 'T']
CBS	NM_000071.3	88	P	R	['R']
CBS	NM_000071.3	65	H	L	['Q', 'L']
CFTR	NM_000492.4	1	M	T	['F', 'G', 'L', 'P', 'Y', 'T']
CFTR	NM_000492.4	13	S	F	['V', 'A', 'R', 'F']
F7	NM_000131.5	44	V	I	['G', 'K', 'I', 'L']
F7	NM_019616.4	13	L	P	['V', 'P', 'A', 'S']
F7	NM_019616.4	63	E	K	['K', 'Q']
F7	NM_019616.4	1	M	T	['P', 'T', 'A', 'S', 'G']
F7	NM_019616.4	22	V	I	['G', 'K', 'I', 'L']
F7	NM_019616.4	386	H	R	['R']
F8	NM_000132.4	2228	R	Q	['Q']
F8	NM_000132.4	2135	R	P	['P']
F8	NM_000132.4	2038	N	S	['K', 'S', 'H', 'G']
F8	NM_000132.4	2319	P	L	['L']
F8	NM_000132.4	2344	G	D	['D', 'S']
F8	NM_000132.4	2107	G	D	['D']
F8	NM_000132.4	2198	G	R	['R']
F8	NM_000132.4	2035	V	A	['A']
F8	NM_000132.4	2208	Q	E	['E']
F8	NM_000132.4	19	S	R	['G', 'R']
F8	NM_000132.4	2237	A	T	['T']
F8	NM_000132.4	2157	N	S	['S']
F9	NM_000133.4	75	R	Q	['Q']
G6PD	NM_000402.4	3	R	W	['M', 'W', 'T', 'G', 'E']
GALT	NM_000155.4	319	H	Q	['P', 'Q']
GALT	NM_000155.4	186	H	Y	['Y', 'S']
GALT	NM_000155.4	209	Y	C	['C', 'V']
GALT	NM_000155.4	328	R	H	['H', 'S']
GALT	NM_000155.4	336	M	L	['P', 'L']
GALT	NM_000155.4	51	R	Q	['G', 'P', 'Q']
GALT	NM_000155.4	320	A	V	['V', 'P']
GALT	NM_000155.4	329	S	P	['Q', 'P']
GALT	NM_000155.4	67	R	H	['L', 'P', 'H']
GALT	NM_000155.4	319	H	Q	['P', 'Q']
GALT	NM_000155.4	48	R	S	['K', 'S']
GALT	NM_000155.4	271	E	D	['D', 'G']
GALT	NM_000155.4	223	R	H	['H', 'C', 'L']
GALT	NM_000155.4	1	M	L	['L', 'S', 'P']
GALT	NM_000155.4	236	S	I	['N', 'K', 'E', 'I', 'P']
GALT	NM_000155.4	336	M	L	['P', 'L']
GBA1	NM_000157.4	502	R	C	['C']
GBA1	NM_000157.4	535	R	H	['H']
GBA1	NM_000157.4	227	N	S	['S']
GBA1	NM_000157.4	351	W	C	['C']
GBA1	NM_000157.4	350	H	R	['R']
GBA1	NM_000157.4	416	G	S	['S']
GBA1	NM_000157.4	426	P	L	['L']
GBA1	NM_000157.4	230	V	G	['G']
GBA1	NM_000157.4	351	W	C	['C']
GBA1	NM_000157.4	391	V	A	['A']
HBB	NM_000518.4	102	E	Q	['Q']
KCNH2	NM_000238.4	58	E	K	['S', 'K']
KCNH2	NM_000238.4	837	D	G	['G']
KCNH2	NM_000238.4	87	L	P	['Q', 'P']
KCNQ1	NM_000218.3	591	R	C	['C', 'S']
KCNQ1	NM_000218.3	114	L	P	['V', 'M', 'P']
KCNQ1	NM_000218.3	115	E	G	['K', 'Q', 'G', 'L', 'R']
KCNQ1	NM_000218.3	303	L	P	['P']
KCNQ1	NM_000218.3	125	Y	D	['F', 'S', 'D', 'A', 'T']
KCNQ1	NM_000218.3	117	P	S	['S', 'R', 'E', 'A', 'C']
KCNQ1	NM_000218.3	119	G	S	['N', 'S', 'A']
KCNQ1	NM_000218.3	591	R	S	['C', 'S']
LDLR	NM_000527.5	46	C	S	['S']
LDLR	NM_000527.5	583	H	D	['D']
LDLR	NM_000527.5	828	Y	S	['F', 'V', 'E', 'S']
LDLR	NM_000527.5	1	M	L	['L', 'S']
LDLR	NM_000527.5	1	M	L	['L', 'S']
LDLR	NM_000527.5	34	C	S	['S', 'L']
LDLR	NM_000527.5	579	D	G	['G']
LDLR	NM_000527.5	88	R	K	['K']
TYR	NM_000372.5	346	G	V	['V', 'A']
TYR	NM_000372.5	370	M	I	['I']
TYR	NM_000372.5	406	P	A	['A']
PAH	NM_000277.3	164	I	T	['T']
PAH	NM_000277.3	176	R	Q	['Q']
PAH	NM_000277.3	413	R	H	['H', 'F']
PAH	NM_000277.3	416	P	T	['R', 'T']
PAH	NM_000277.3	156	A	G	['E', 'R', 'G']
PMM2	NM_000303.3	231	V	M	['S', 'A', 'L', 'M', 'E', 'I']
PMM2	NM_000303.3	226	T	S	['P', 'C', 'A', 'S', 'Q', 'N', 'L']
PMM2	NM_000303.3	243	L	P	['E', 'V', 'T', 'P', 'Q', 'M', 'S', 'A', 'N']
PMM2	NM_000303.3	228	G	R	['A', 'T', 'V', 'E', 'L', 'H', 'R']
PMM2	NM_000303.3	223	D	N	['S', 'N', 'A', 'K', 'T', 'R']
PMM2	NM_000303.3	239	R	T	['T', 'Q', 'K', 'D', 'S', 'P', 'C', 'A', 'V']
PMM2	NM_000303.3	231	V	L	['S', 'A', 'L', 'M', 'E', 'I']
PMM2	NM_000303.3	231	V	L	['S', 'A', 'L', 'M', 'E', 'I']
PMM2	NM_000303.3	239	R	S	['T', 'Q', 'K', 'D', 'S', 'P', 'C', 'A', 'V']
RHO	NM_000539.3	180	P	T	['T']
TTR	NM_000371.4	131	L	M	['M', 'T']
TTR	NM_000371.4	142	V	I	['L', 'I']
TTR	NM_000371.4	127	I	V	['V', 'F']
TTR	NM_000371.4	136	Y	S	['R', 'W', 'S']
TTR	NM_000371.4	82	E	K	['K']
TTR	NM_000371.4	77	G	R	['R']
TTR	NM_000371.4	140	A	V	['V']
TTR	NM_000371.4	126	T	I	['I', 'V']
VWF	NM_000552.5	528	N	S	['S']

### save output to file 'invalidated_CPDs.tsv'

In [ ]:
with open("invalidated_CPDs.tsv", "w") as outfile:

    # Write header
    print('gene\ttranscript\tsite\twild\tmut\tvar', file=outfile)

    final_transcripts = variants.keys()

    for gene in loci:
        transcripts = vartranscripts_filtered[gene]

        for transcript in transcripts:
            if transcript in final_transcripts:

                sites, wilds, muts = variants[transcript]
                tmp_variable = variable[transcript]

                for i in range(len(sites)):

                    if sites[i] is None:
                        continue

                    site = int(sites[i])

                    if (site in tmp_variable) and (muts[i] in tmp_variable[site]):
                        print(
                            gene,
                            transcript,
                            site,
                            wilds[i],
                            muts[i],
                            ",".join(tmp_variable[site]),   # Write amino acids as comma-separated
                            sep="\t",
                            file=outfile
                        )

print("Results saved to invalidated_CPDs.tsv")

Results saved to clinvar_matches.tsv

## Look at particular sites

The following command allows you to double check particular sites.  It now also outputs which site each species has.

In [33]:
get_alleles('ATP7B', translation['NM_000053.4'], 969, True)

     Gene: ATP7B
    Human: 969 R
Alignment: 1238 R
R    181
-     27
Q      1
Name: count, dtype: int64

R XP_053420007.1 Nycticebus coucang
R XP_053420006.1 Nycticebus coucang
R XP_053420005.1 Nycticebus coucang
R XP_053419999.1 Nycticebus coucang
R XP_053420008.1 Nycticebus coucang
R XP_023363838.1 Otolemur garnettii
R XP_012668202.1 Otolemur garnettii
R XP_023363839.1 Otolemur garnettii
R XP_012638108.2 Microcebus murinus
R XP_012638109.2 Microcebus murinus
R XP_012504534.1 Propithecus coquereli
R XP_012504526.1 Propithecus coquereli
R XP_012504533.1 Propithecus coquereli
R XP_012504538.1 Propithecus coquereli
R XP_045423256.1 Lemur catta
R XP_045423253.1 Lemur catta
- XP_045423254.1 Lemur catta
R XP_069323794.1 Eulemur rufifrons
R XP_069323793.1 Eulemur rufifrons
R XP_069323796.1 Eulemur rufifrons
R XP_069323797.1 Eulemur rufifrons
R XP_008070488.1 Carlito syrichta
R XP_008070483.1 Carlito syrichta
R XP_008070485.1 Carlito syrichta
- XP_008070484.1 Carlito syrichta
R XP_008070486.1 Carlito syrichta
R XP_008070482.1 Carlito syrichta
R XP_021561720.1 Carlito syrichta
R XP_011920046.1 Cercocebus atys
Q XP_030669295.1 Nomascus leucogenys
R XP_058293898.1 Hylobates moloch
R XP_058293899.1 Hylobates moloch
R XP_058293895.1 Hylobates moloch
R XP_058293894.1 Hylobates moloch
R XP_058293897.1 Hylobates moloch
R XP_054520950.2 Pan troglodytes
R XP_054520946.2 Pan troglodytes
R XP_016780802.3 Pan troglodytes
R XP_054520945.2 Pan troglodytes
R XP_063648654.1 Pan troglodytes
- NP_001393454.1 Homo sapiens
- NP_001393469.1 Homo sapiens
- NP_001393475.1 Homo sapiens
- NP_001393476.1 Homo sapiens
R NP_001393459.1 Homo sapiens
R NP_001393465.1 Homo sapiens
R NP_001393472.1 Homo sapiens
R NP_001393468.1 Homo sapiens
R NP_001393473.1 Homo sapiens
R NP_001393446.1 Homo sapiens
R NP_001393467.1 Homo sapiens
R NP_001393463.1 Homo sapiens
R NP_001317507.1 Homo sapiens
R NP_001393453.1 Homo sapiens
R NP_001393449.1 Homo sapiens
- NP_001393466.1 Homo sapiens
R NP_001230111.1 Homo sapiens
R NP_001393455.1 Homo sapiens
R NP_001393452.1 Homo sapiens
R NP_001393470.1 Homo sapiens
R NP_001393442.1 Homo sapiens
R NP_000044.2 Homo sapiens
R NP_001393474.1 Homo sapiens
R NP_001393443.1 Homo sapiens
R NP_001317508.1 Homo sapiens
R NP_001393477.1 Homo sapiens
R NP_001005918.1 Homo sapiens
R NP_001393448.1 Homo sapiens
R NP_001393444.1 Homo sapiens
- NP_001393464.1 Homo sapiens
R XP_024086846.3 Pongo abelii
R XP_054385033.2 Pongo abelii
R XP_054302291.2 Pongo pygmaeus
R XP_063506961.1 Pongo pygmaeus
R XP_054302295.2 Pongo pygmaeus
R XP_054302292.2 Pongo pygmaeus
R XP_018895400.1 Gorilla gorilla gorilla
R XP_018895395.3 Gorilla gorilla gorilla
R XP_018895399.3 Gorilla gorilla gorilla
R XP_018895397.3 Gorilla gorilla gorilla
- XP_055215870.2 Gorilla gorilla gorilla
R XP_018895398.3 Gorilla gorilla gorilla
R XP_055215868.2 Gorilla gorilla gorilla
R XP_004054587.3 Gorilla gorilla gorilla
R XP_008960332.4 Pan paniscus
R XP_008960333.4 Pan paniscus
R XP_054952782.2 Pan paniscus
R XP_024781039.4 Pan paniscus
R XP_063451845.1 Pan paniscus
R XP_063648656.1 Pan troglodytes
R XP_016780798.3 Pan troglodytes
- XP_054520944.2 Pan troglodytes
R XP_016780791.3 Pan troglodytes
R XP_063648645.1 Pan troglodytes
- XP_016780801.3 Pan troglodytes
R XP_016780797.3 Pan troglodytes
- XP_054520943.2 Pan troglodytes
R XP_054520941.2 Pan troglodytes
R XP_016780799.3 Pan troglodytes
R XP_054520940.2 Pan troglodytes
- XP_054520949.2 Pan troglodytes
R XP_054520939.2 Pan troglodytes
R XP_016780796.3 Pan troglodytes
- XP_054520942.2 Pan troglodytes
- XP_054520951.2 Pan troglodytes
- XP_054520947.2 Pan troglodytes
- XP_054520948.2 Pan troglodytes
R XP_063648641.1 Pan troglodytes
R XP_016780795.3 Pan troglodytes
R XP_063648640.1 Pan troglodytes
R XP_063648648.1 Pan troglodytes
R XP_063648643.1 Pan troglodytes
R XP_063648647.1 Pan troglodytes
- XP_063648653.1 Pan troglodytes
R XP_063648652.1 Pan troglodytes
R XP_063648646.1 Pan troglodytes
R XP_063648638.1 Pan troglodytes
- XP_063648649.1 Pan troglodytes
R XP_072870464.1 Chlorocebus sabaeus
R XP_037842590.2 Chlorocebus sabaeus
R XP_037842588.2 Chlorocebus sabaeus
R XP_050622211.1 Macaca thibetana thibetana
R XP_050622212.1 Macaca thibetana thibetana
R XP_050622214.1 Macaca thibetana thibetana
R XP_011754956.2 Macaca nemestrina
R XP_011754959.2 Macaca nemestrina
R XP_011754960.2 Macaca nemestrina
R XP_011754963.2 Macaca nemestrina
R XP_025220045.1 Theropithecus gelada
R XP_025220040.1 Theropithecus gelada
R XP_025220042.1 Theropithecus gelada
R XP_025220044.1 Theropithecus gelada
- XP_025220041.1 Theropithecus gelada
R XP_025220038.1 Theropithecus gelada
R XP_025220043.1 Theropithecus gelada
R XP_017806754.3 Papio anubis
R XP_017806752.3 Papio anubis
R XP_021785336.2 Papio anubis
R XP_021785339.1 Papio anubis
R XP_031511724.1 Papio anubis
R XP_021785340.1 Papio anubis
R XP_014976600.3 Macaca mulatta
R XP_014976599.3 Macaca mulatta
R XP_077829965.1 Macaca mulatta
R XP_077829964.1 Macaca mulatta
R XP_028693404.2 Macaca mulatta
R XP_077829967.1 Macaca mulatta
R XP_077829968.1 Macaca mulatta
R XP_014976601.3 Macaca mulatta
R XP_077829966.1 Macaca mulatta
R XP_011844139.1 Mandrillus leucophaeus
R XP_011844138.1 Mandrillus leucophaeus
- XP_011844136.1 Mandrillus leucophaeus
R XP_011844134.1 Mandrillus leucophaeus
R XP_011844135.1 Mandrillus leucophaeus
R XP_011844137.1 Mandrillus leucophaeus
R XP_073878190.1 Macaca fascicularis
R XP_073878186.1 Macaca fascicularis
R XP_073878192.1 Macaca fascicularis
R XP_065389341.1 Macaca fascicularis
R XP_073878182.1 Macaca fascicularis
R XP_065389345.1 Macaca fascicularis
- XP_065389352.1 Macaca fascicularis
R XP_065389351.1 Macaca fascicularis
R XP_073878180.1 Macaca fascicularis
R XP_065389349.1 Macaca fascicularis
- XP_065389350.1 Macaca fascicularis
R XP_065389342.1 Macaca fascicularis
- XP_065389348.1 Macaca fascicularis
- XP_065389344.1 Macaca fascicularis
R XP_065389340.1 Macaca fascicularis
R XP_045233104.2 Macaca fascicularis
- XP_073878193.1 Macaca fascicularis
R XP_033033524.1 Trachypithecus francoisi
R XP_033033526.1 Trachypithecus francoisi
R XP_023043183.1 Piliocolobus tephrosceles
R XP_011794363.1 Colobus angolensis palliatus
R XP_011794355.1 Colobus angolensis palliatus
- XP_011794340.1 Colobus angolensis palliatus
R XP_011794322.1 Colobus angolensis palliatus
R XP_011794331.1 Colobus angolensis palliatus
R XP_011794349.1 Colobus angolensis palliatus
R XP_010351222.1 Rhinopithecus roxellana
R XP_017713761.1 Rhinopithecus bieti
R XP_017713762.1 Rhinopithecus bieti
R XP_017713763.1 Rhinopithecus bieti
R XP_078208662.1 Callithrix jacchus
R XP_078208642.1 Callithrix jacchus
R XP_078208620.1 Callithrix jacchus
R XP_035153336.2 Callithrix jacchus
R XP_035153347.2 Callithrix jacchus
R XP_078208602.1 Callithrix jacchus
R XP_078208570.1 Callithrix jacchus
R XP_035153372.2 Callithrix jacchus
R XP_078208546.1 Callithrix jacchus
R XP_035153316.2 Callithrix jacchus
R XP_035153352.2 Callithrix jacchus
R XP_078208309.1 Callithrix jacchus
R XP_003927227.1 Saimiri boliviensis
R XP_074243757.1 Saimiri boliviensis
R XP_012321637.1 Aotus nancymaae
R XP_032150436.1 Sapajus apella
R XP_032150437.1 Sapajus apella
R XP_017397951.1 Cebus imitator
R XP_017397952.1 Cebus imitator
R XP_032150438.1 Sapajus apella
R XP_032150439.1 Sapajus apella
R XP_017397953.1 Cebus imitator
R XP_017397954.1 Cebus imitator

(True,
 969,
 'R',
 R    181
 -     27
 Q      1
 Name: count, dtype: int64)

In [26]:
get_alleles('F8', translation['NM_000132.4'], 2038, True)

     Gene: F8
    Human: 2038 N
Alignment: 2056 N
N    67
-    22
K    11
S     5
H     4
G     1
Name: count, dtype: int64

N XP_003943974.1 Saimiri boliviensis
N XP_074247980.1 Saimiri boliviensis
N XP_074247981.1 Saimiri boliviensis
S XP_078219843.1 Callithrix jacchus
S XP_078219845.1 Callithrix jacchus
S XP_035144731.3 Callithrix jacchus
S XP_054106981.2 Callithrix jacchus
S XP_078219844.1 Callithrix jacchus
N XP_064227602.1 Aotus nancymaae
N XP_064227600.1 Aotus nancymaae
N XP_064227599.1 Aotus nancymaae
N XP_064227601.1 Aotus nancymaae
- XP_064227603.1 Aotus nancymaae
N XP_017376032.2 Cebus imitator
N XP_032121193.1 Sapajus apella
N XP_032121192.1 Sapajus apella
N XP_032121190.1 Sapajus apella
N XP_032121191.1 Sapajus apella
- XP_030662513.1 Nomascus leucogenys
- XP_055125146.1 Symphalangus syndactylus
- XP_055125144.1 Symphalangus syndactylus
- XP_055125145.1 Symphalangus syndactylus
N XP_063559080.1 Gorilla gorilla gorilla
N XP_003279379.1 Nomascus leucogenys
N XP_058297352.1 Hylobates moloch
N XP_055125143.1 Symphalangus syndactylus
N XP_063490715.1 Symphalangus syndactylus
- NP_063916.1 Homo sapiens
N NP_000123.1 Homo sapiens
N XP_003810005.2 Pan paniscus
N XP_063660765.1 Pan troglodytes
N XP_063660764.1 Pan troglodytes
N XP_003317837.1 Pan troglodytes
N XP_016800114.1 Pan troglodytes
N XP_016800113.1 Pan troglodytes
N XP_009438145.1 Pan troglodytes
N XP_016800116.1 Pan troglodytes
- XP_054532326.1 Pan troglodytes
N XP_004065205.1 Gorilla gorilla gorilla
N XP_063559079.1 Gorilla gorilla gorilla
- XP_030861623.1 Gorilla gorilla gorilla
- XP_063559081.1 Gorilla gorilla gorilla
N XP_031516315.1 Papio anubis
N XP_024096329.1 Pongo abelii
N XP_054327961.1 Pongo pygmaeus
N XP_054327960.1 Pongo pygmaeus
- XP_025227753.1 Theropithecus gelada
N XP_054327962.1 Pongo pygmaeus
- XP_063516080.1 Pongo pygmaeus
- XP_054327963.1 Pongo pygmaeus
N XP_033057806.1 Trachypithecus francoisi
N XP_077845133.1 Macaca mulatta
N XP_011889285.1 Cercocebus atys
N XP_011889280.1 Cercocebus atys
N XP_011889281.1 Cercocebus atys
N XP_011889284.1 Cercocebus atys
N XP_011889283.1 Cercocebus atys
N XP_050631367.1 Macaca thibetana thibetana
N XP_050631366.1 Macaca thibetana thibetana
N XP_050631365.1 Macaca thibetana thibetana
N XP_045239765.2 Macaca fascicularis
N XP_045239766.2 Macaca fascicularis
N XP_005595091.3 Macaca fascicularis
N XP_077845130.1 Macaca mulatta
N XP_077845132.1 Macaca mulatta
N XP_077845131.1 Macaca mulatta
N XP_077845129.1 Macaca mulatta
N XP_077845128.1 Macaca mulatta
N XP_014984059.2 Macaca mulatta
H XP_011716756.2 Macaca nemestrina
H XP_011716755.2 Macaca nemestrina
H XP_011716754.2 Macaca nemestrina
N XP_025227752.1 Theropithecus gelada
N XP_031516314.1 Papio anubis
N XP_031516316.1 Papio anubis
N XP_011818598.1 Colobus angolensis palliatus
- XP_026307119.1 Piliocolobus tephrosceles
N XP_010351146.1 Rhinopithecus roxellana
N XP_072869377.1 Chlorocebus sabaeus
N XP_072869373.1 Chlorocebus sabaeus
N XP_072869375.1 Chlorocebus sabaeus
N XP_072869374.1 Chlorocebus sabaeus
N XP_010351139.1 Rhinopithecus roxellana
N XP_010351142.1 Rhinopithecus roxellana
N XP_010351130.1 Rhinopithecus roxellana
- XP_030789544.1 Rhinopithecus roxellana
- XP_030789545.1 Rhinopithecus roxellana
N XP_072869376.1 Chlorocebus sabaeus
- XP_077845134.1 Macaca mulatta
N XP_028698332.1 Macaca mulatta
- XP_077845136.1 Macaca mulatta
- XP_072869379.1 Chlorocebus sabaeus
G XP_070944606.1 Macaca nemestrina
- XP_005595097.1 Macaca fascicularis
- XP_072869378.1 Chlorocebus sabaeus
N XP_045239768.1 Macaca fascicularis
H XP_011716757.2 Macaca nemestrina
- XP_011889288.1 Cercocebus atys
K XP_003802782.1 Otolemur garnettii
K XP_053435824.1 Nycticebus coucang
K XP_053435825.1 Nycticebus coucang
K XP_053435826.1 Nycticebus coucang
K XP_012517042.1 Propithecus coquereli
K XP_075855879.1 Microcebus murinus
K XP_045394744.1 Lemur catta
K XP_069319345.1 Eulemur rufifrons
K XP_069319346.1 Eulemur rufifrons
K XP_069319344.1 Eulemur rufifrons
K XP_069319343.1 Eulemur rufifrons
- XP_069319347.1 Eulemur rufifrons

(True,
 2038,
 'N',
 N    67
 -    22
 K    11
 S     5
 H     4
 G     1
 Name: count, dtype: int64)

In [27]:
translation['NM_000157.4']

'NP_000148.2'

In [30]:
get_alleles('GALT', translation['NM_000155.4'], 23, True)

     Gene: GALT
    Human: 23 T
Alignment: 71 T
T    56
-    33
S     5
A     4
G     1
Name: count, dtype: int64

S XP_047286067.1 Homo sapiens
S XP_011533240.1 Homo sapiens
S XP_011533238.1 Homo sapiens
S NP_919299.3 Homo sapiens
S XP_006719831.1 Homo sapiens
T XP_008068994.1 Carlito syrichta
- XP_023059055.1 Piliocolobus tephrosceles
- XP_033094123.1 Trachypithecus francoisi
- XP_017747549.1 Rhinopithecus bieti
- XP_073873355.1 Macaca fascicularis
- XP_070934053.1 Macaca nemestrina
T XP_033094120.1 Trachypithecus francoisi
- XP_033094121.1 Trachypithecus francoisi
- XP_011805905.1 Colobus angolensis palliatus
T XP_009186860.2 Papio anubis
T XP_017747545.1 Rhinopithecus bieti
- XP_023059054.1 Piliocolobus tephrosceles
T XP_011805904.1 Colobus angolensis palliatus
T XP_011835461.1 Mandrillus leucophaeus
T XP_011924618.1 Cercocebus atys
T XP_023059053.1 Piliocolobus tephrosceles
- XP_014973013.1 Macaca mulatta
- XP_073873354.1 Macaca fascicularis
- XP_073873351.1 Macaca fascicularis
- XP_028690928.1 Macaca mulatta
T XP_028690927.1 Macaca mulatta
T XP_073873350.1 Macaca fascicularis
- NP_001245261.1 Homo sapiens
- XP_063465890.1 Symphalangus syndactylus
- XP_055207613.1 Gorilla gorilla gorilla
- XP_063644719.1 Pan troglodytes
- XP_057159138.1 Pan paniscus
T XP_011924615.1 Cercocebus atys
G XP_011924616.1 Cercocebus atys
A XP_011924617.1 Cercocebus atys
T XP_012625552.1 Microcebus murinus
T XP_075864929.1 Microcebus murinus
T XP_012512299.1 Propithecus coquereli
- XP_012512307.1 Propithecus coquereli
T XP_045418889.1 Lemur catta
T XP_069330487.1 Eulemur rufifrons
- XP_045418888.1 Lemur catta
T XP_045418886.1 Lemur catta
T XP_045418885.1 Lemur catta
T XP_045418884.1 Lemur catta
- XP_053425969.1 Nycticebus coucang
A XP_053425960.1 Nycticebus coucang
A XP_053425949.1 Nycticebus coucang
A XP_003800307.1 Otolemur garnettii
- XP_023375102.1 Otolemur garnettii
T XP_063506265.1 Pongo pygmaeus
T XP_063644718.1 Pan troglodytes
T XP_054514788.1 Pan troglodytes
- XP_057159136.1 Pan paniscus
- XP_063552339.1 Gorilla gorilla gorilla
T XP_063552338.1 Gorilla gorilla gorilla
T XP_063552337.1 Gorilla gorilla gorilla
T XP_057159135.1 Pan paniscus
T XP_057159134.1 Pan paniscus
T XP_057159133.1 Pan paniscus
T XP_054376965.2 Pongo abelii
T XP_063570026.1 Pongo abelii
T XP_054376964.2 Pongo abelii
T XP_003263433.1 Nomascus leucogenys
T NP_000146.2 Homo sapiens
- XP_034823262.1 Pan paniscus
T XP_001163419.2 Pan troglodytes
T XP_004048011.1 Gorilla gorilla gorilla
T XP_055207611.1 Gorilla gorilla gorilla
T XP_063450500.1 Pan paniscus
T XP_063450498.1 Pan paniscus
T XP_003829858.2 Pan paniscus
T XP_063506264.1 Pongo pygmaeus
T XP_054358709.1 Pongo pygmaeus
- XP_054358710.1 Pongo pygmaeus
- XP_055149893.1 Symphalangus syndactylus
T XP_032019924.1 Hylobates moloch
T XP_055149891.1 Symphalangus syndactylus
T XP_012318674.1 Aotus nancymaae
- XP_012318675.1 Aotus nancymaae
- XP_032155759.1 Sapajus apella
- XP_010330020.1 Saimiri boliviensis
T XP_010330018.1 Saimiri boliviensis
T XP_010330019.1 Saimiri boliviensis
T XP_032155758.1 Sapajus apella
T XP_037599581.1 Cebus imitator
T XP_017398495.1 Cebus imitator
T XP_003732050.1 Callithrix jacchus
T XP_008996942.1 Callithrix jacchus
- XP_008996946.1 Callithrix jacchus
- XP_078227234.1 Callithrix jacchus
- XP_021783110.1 Papio anubis
T XP_011924614.1 Cercocebus atys
T XP_077822063.1 Macaca mulatta
T XP_021783112.2 Papio anubis
T XP_050616753.1 Macaca thibetana thibetana
T XP_025214557.1 Theropithecus gelada
T XP_021783108.2 Papio anubis
- XP_021783109.2 Papio anubis

(True,
 23,
 'T',
 T    56
 -    33
 S     5
 A     4
 G     1
 Name: count, dtype: int64)

In [32]:
translation['NM_000527.4']

'NP_000518.1'

In [33]:
get_alleles('LDLR', translation['NM_000527.4'], 215, True)

     Gene: LDLR
    Human: 215 R
Alignment: 305 R
R    58
-    16
H     9
Name: count, dtype: int64

- NP_001393790.1 Homo sapiens
H XP_021573646.1 Carlito syrichta
R XP_020139390.1 Microcebus murinus
H XP_074240716.1 Saimiri boliviensis
H XP_064237923.1 Aotus nancymaae
H XP_002761791.3 Callithrix jacchus
H XP_039321728.1 Saimiri boliviensis
H XP_032107631.1 Sapajus apella
H XP_037583448.1 Cebus imitator
R XP_063472056.1 Symphalangus syndactylus
R XP_063472057.1 Symphalangus syndactylus
R XP_011884149.1 Cercocebus atys
R XP_030676686.1 Nomascus leucogenys
R XP_032025606.1 Hylobates moloch
- XP_055094495.1 Symphalangus syndactylus
R XP_055094494.1 Symphalangus syndactylus
- XP_055094497.1 Symphalangus syndactylus
R XP_063472058.1 Symphalangus syndactylus
R XP_055094493.1 Symphalangus syndactylus
R XP_055094492.1 Symphalangus syndactylus
R XP_047294787.1 Homo sapiens
- XP_063576006.1 Pongo abelii
R XP_054319927.2 Pongo pygmaeus
R XP_063513896.1 Pongo pygmaeus
R XP_063576005.1 Pongo abelii
- XP_063576007.1 Pongo abelii
- NP_001182729.1 Homo sapiens
R NP_001182728.1 Homo sapiens
- NP_001182732.1 Homo sapiens
R XP_011526312.1 Homo sapiens
R NP_001182727.1 Homo sapiens
R NP_000518.1 Homo sapiens
R XP_018871450.1 Gorilla gorilla gorilla
R XP_018871452.1 Gorilla gorilla gorilla
R XP_034800281.1 Pan paniscus
- XP_034800282.1 Pan paniscus
R XP_063657276.1 Pan troglodytes
R XP_024206934.1 Pan troglodytes
R XP_024206933.1 Pan troglodytes
R XP_031790584.1 Piliocolobus tephrosceles
R XP_011810343.1 Colobus angolensis palliatus
R XP_077831915.1 Macaca mulatta
R XP_077831886.1 Macaca mulatta
R XP_077831924.1 Macaca mulatta
R XP_077831887.1 Macaca mulatta
R XP_077831923.1 Macaca mulatta
R XP_033056644.1 Trachypithecus francoisi
R XP_017724974.1 Rhinopithecus bieti
R XP_030791739.1 Rhinopithecus roxellana
- XP_011850155.1 Mandrillus leucophaeus
- XP_011850148.1 Mandrillus leucophaeus
- XP_025222242.1 Theropithecus gelada
- XP_025222241.1 Theropithecus gelada
R XP_072873051.1 Chlorocebus sabaeus
R XP_031515756.1 Papio anubis
R XP_025222240.1 Theropithecus gelada
R XP_025222239.1 Theropithecus gelada
R XP_025222238.1 Theropithecus gelada
R XP_011850142.1 Mandrillus leucophaeus
R XP_011850140.1 Mandrillus leucophaeus
R XP_011850139.1 Mandrillus leucophaeus
R XP_070942884.1 Macaca nemestrina
R XP_070942885.1 Macaca nemestrina
R XP_077831917.1 Macaca mulatta
R NP_001028078.1 Macaca mulatta
R XP_077831910.1 Macaca mulatta
R XP_014978386.3 Macaca mulatta
- XP_077831920.1 Macaca mulatta
- XP_073882014.1 Macaca fascicularis
R XP_065391446.1 Macaca fascicularis
R XP_045237058.2 Macaca fascicularis
R XP_045237056.2 Macaca fascicularis
R XP_005588053.3 Macaca fascicularis
R XP_053439240.1 Nycticebus coucang
H XP_012665677.1 Otolemur garnettii
H XP_023373820.1 Otolemur garnettii
R XP_012496802.1 Propithecus coquereli
R XP_045402139.1 Lemur catta
R XP_069334646.1 Eulemur rufifrons
R XP_069334639.1 Eulemur rufifrons
R XP_069334632.1 Eulemur rufifrons
- XP_069334659.1 Eulemur rufifrons
- XP_069334650.1 Eulemur rufifrons

(True,
 215,
 'R',
 R    58
 -    16
 H     9
 Name: count, dtype: int64)

# Validate CPDs

Here we test whether a putative CPD is valid by investigating the vicinity of the sequence, 10 amino acids on either side of the site.

This function pulls out the species and protein IDs showing a particular amino acid at a site.

In [37]:
get_species_with_allele('ATP7B', translation['NM_000053.4'], 969, 'R')

[('Nycticebus coucang', 'XP_053420007.1'),
 ('Nycticebus coucang', 'XP_053420006.1'),
 ('Nycticebus coucang', 'XP_053420005.1'),
 ('Nycticebus coucang', 'XP_053419999.1'),
 ('Nycticebus coucang', 'XP_053420008.1'),
 ('Otolemur garnettii', 'XP_023363838.1'),
 ('Otolemur garnettii', 'XP_012668202.1'),
 ('Otolemur garnettii', 'XP_023363839.1'),
 ('Microcebus murinus', 'XP_012638108.2'),
 ('Microcebus murinus', 'XP_012638109.2'),
 ('Propithecus coquereli', 'XP_012504534.1'),
 ('Propithecus coquereli', 'XP_012504526.1'),
 ('Propithecus coquereli', 'XP_012504533.1'),
 ('Propithecus coquereli', 'XP_012504538.1'),
 ('Lemur catta', 'XP_045423256.1'),
 ('Lemur catta', 'XP_045423253.1'),
 ('Eulemur rufifrons', 'XP_069323794.1'),
 ('Eulemur rufifrons', 'XP_069323793.1'),
 ('Eulemur rufifrons', 'XP_069323796.1'),
 ('Eulemur rufifrons', 'XP_069323797.1'),
 ('Carlito syrichta', 'XP_008070488.1'),
 ('Carlito syrichta', 'XP_008070483.1'),
 ('Carlito syrichta', 'XP_008070485.1'),
 ('Carlito syrichta', 'XP_008070486.1'),
 ('Carlito syrichta', 'XP_008070482.1'),
 ('Carlito syrichta', 'XP_021561720.1'),
 ('Cercocebus atys', 'XP_011920046.1'),
 ('Hylobates moloch', 'XP_058293898.1'),
 ('Hylobates moloch', 'XP_058293899.1'),
 ('Hylobates moloch', 'XP_058293895.1'),
 ('Hylobates moloch', 'XP_058293894.1'),
 ('Hylobates moloch', 'XP_058293897.1'),
 ('Pan troglodytes', 'XP_054520950.2'),
 ('Pan troglodytes', 'XP_054520946.2'),
 ('Pan troglodytes', 'XP_016780802.3'),
 ('Pan troglodytes', 'XP_054520945.2'),
 ('Pan troglodytes', 'XP_063648654.1'),
 ('Homo sapiens', 'NP_001393459.1'),
 ('Homo sapiens', 'NP_001393465.1'),
 ('Homo sapiens', 'NP_001393472.1'),
 ('Homo sapiens', 'NP_001393468.1'),
 ('Homo sapiens', 'NP_001393473.1'),
 ('Homo sapiens', 'NP_001393446.1'),
 ('Homo sapiens', 'NP_001393467.1'),
 ('Homo sapiens', 'NP_001393463.1'),
 ('Homo sapiens', 'NP_001317507.1'),
 ('Homo sapiens', 'NP_001393453.1'),
 ('Homo sapiens', 'NP_001393449.1'),
 ('Homo sapiens', 'NP_001230111.1'),
 ('Homo sapiens', 'NP_001393455.1'),
 ('Homo sapiens', 'NP_001393452.1'),
 ('Homo sapiens', 'NP_001393470.1'),
 ('Homo sapiens', 'NP_001393442.1'),
 ('Homo sapiens', 'NP_000044.2'),
 ('Homo sapiens', 'NP_001393474.1'),
 ('Homo sapiens', 'NP_001393443.1'),
 ('Homo sapiens', 'NP_001317508.1'),
 ('Homo sapiens', 'NP_001393477.1'),
 ('Homo sapiens', 'NP_001005918.1'),
 ('Homo sapiens', 'NP_001393448.1'),
 ('Homo sapiens', 'NP_001393444.1'),
 ('Pongo abelii', 'XP_024086846.3'),
 ('Pongo abelii', 'XP_054385033.2'),
 ('Pongo pygmaeus', 'XP_054302291.2'),
 ('Pongo pygmaeus', 'XP_063506961.1'),
 ('Pongo pygmaeus', 'XP_054302295.2'),
 ('Pongo pygmaeus', 'XP_054302292.2'),
 ('Gorilla gorilla gorilla', 'XP_018895400.1'),
 ('Gorilla gorilla gorilla', 'XP_018895395.3'),
 ('Gorilla gorilla gorilla', 'XP_018895399.3'),
 ('Gorilla gorilla gorilla', 'XP_018895397.3'),
 ('Gorilla gorilla gorilla', 'XP_018895398.3'),
 ('Gorilla gorilla gorilla', 'XP_055215868.2'),
 ('Gorilla gorilla gorilla', 'XP_004054587.3'),
 ('Pan paniscus', 'XP_008960332.4'),
 ('Pan paniscus', 'XP_008960333.4'),
 ('Pan paniscus', 'XP_054952782.2'),
 ('Pan paniscus', 'XP_024781039.4'),
 ('Pan paniscus', 'XP_063451845.1'),
 ('Pan troglodytes', 'XP_063648656.1'),
 ('Pan troglodytes', 'XP_016780798.3'),
 ('Pan troglodytes', 'XP_016780791.3'),
 ('Pan troglodytes', 'XP_063648645.1'),
 ('Pan troglodytes', 'XP_016780797.3'),
 ('Pan troglodytes', 'XP_054520941.2'),
 ('Pan troglodytes', 'XP_016780799.3'),
 ('Pan troglodytes', 'XP_054520940.2'),
 ('Pan troglodytes', 'XP_054520939.2'),
 ('Pan troglodytes', 'XP_016780796.3'),
 ('Pan troglodytes', 'XP_063648641.1'),
 ('Pan troglodytes', 'XP_016780795.3'),
 ('Pan troglodytes', 'XP_063648640.1'),
 ('Pan troglodytes', 'XP_063648648.1'),
 ('Pan troglodytes', 'XP_063648643.1'),
 ('Pan troglodytes', 'XP_063648647.1'),
 ('Pan troglodytes', 'XP_063648652.1'),
 ('Pan troglodytes', 'XP_063648646.1'),
 ('Pan troglodytes', 'XP_063648638.1'),
 ('Chlorocebus sabaeus', 'XP_072870464.1'),
 ('Chlorocebus sabaeus', 'XP_037842590.2'),
 ('Chlorocebus sabaeus', 'XP_037842588.2'),
 ('Macaca thibetana thibetana', 'XP_050622211.1'),
 ('Macaca thibetana thibetana', 'XP_050622212.1'),
 ('Macaca thibetana thibetana', 'XP_050622214.1'),
 ('Macaca nemestrina', 'XP_011754956.2'),
 ('Macaca nemestrina', 'XP_011754959.2'),
 ('Macaca nemestrina', 'XP_011754960.2'),
 ('Macaca nemestrina', 'XP_011754963.2'),
 ('Theropithecus gelada', 'XP_025220045.1'),
 ('Theropithecus gelada', 'XP_025220040.1'),
 ('Theropithecus gelada', 'XP_025220042.1'),
 ('Theropithecus gelada', 'XP_025220044.1'),
 ('Theropithecus gelada', 'XP_025220038.1'),
 ('Theropithecus gelada', 'XP_025220043.1'),
 ('Papio anubis', 'XP_017806754.3'),
 ('Papio anubis', 'XP_017806752.3'),
 ('Papio anubis', 'XP_021785336.2'),
 ('Papio anubis', 'XP_021785339.1'),
 ('Papio anubis', 'XP_031511724.1'),
 ('Papio anubis', 'XP_021785340.1'),
 ('Macaca mulatta', 'XP_014976600.3'),
 ('Macaca mulatta', 'XP_014976599.3'),
 ('Macaca mulatta', 'XP_077829965.1'),
 ('Macaca mulatta', 'XP_077829964.1'),
 ('Macaca mulatta', 'XP_028693404.2'),
 ('Macaca mulatta', 'XP_077829967.1'),
 ('Macaca mulatta', 'XP_077829968.1'),
 ('Macaca mulatta', 'XP_014976601.3'),
 ('Macaca mulatta', 'XP_077829966.1'),
 ('Mandrillus leucophaeus', 'XP_011844139.1'),
 ('Mandrillus leucophaeus', 'XP_011844138.1'),
 ('Mandrillus leucophaeus', 'XP_011844134.1'),
 ('Mandrillus leucophaeus', 'XP_011844135.1'),
 ('Mandrillus leucophaeus', 'XP_011844137.1'),
 ('Macaca fascicularis', 'XP_073878190.1'),
 ('Macaca fascicularis', 'XP_073878186.1'),
 ('Macaca fascicularis', 'XP_073878192.1'),
 ('Macaca fascicularis', 'XP_065389341.1'),
 ('Macaca fascicularis', 'XP_073878182.1'),
 ('Macaca fascicularis', 'XP_065389345.1'),
 ('Macaca fascicularis', 'XP_065389351.1'),
 ('Macaca fascicularis', 'XP_073878180.1'),
 ('Macaca fascicularis', 'XP_065389349.1'),
 ('Macaca fascicularis', 'XP_065389342.1'),
 ('Macaca fascicularis', 'XP_065389340.1'),
 ('Macaca fascicularis', 'XP_045233104.2'),
 ('Trachypithecus francoisi', 'XP_033033524.1'),
 ('Trachypithecus francoisi', 'XP_033033526.1'),
 ('Piliocolobus tephrosceles', 'XP_023043183.1'),
 ('Colobus angolensis palliatus', 'XP_011794363.1'),
 ('Colobus angolensis palliatus', 'XP_011794355.1'),
 ('Colobus angolensis palliatus', 'XP_011794322.1'),
 ('Colobus angolensis palliatus', 'XP_011794331.1'),
 ('Colobus angolensis palliatus', 'XP_011794349.1'),
 ('Rhinopithecus roxellana', 'XP_010351222.1'),
 ('Rhinopithecus bieti', 'XP_017713761.1'),
 ('Rhinopithecus bieti', 'XP_017713762.1'),
 ('Rhinopithecus bieti', 'XP_017713763.1'),
 ('Callithrix jacchus', 'XP_078208662.1'),
 ('Callithrix jacchus', 'XP_078208642.1'),
 ('Callithrix jacchus', 'XP_078208620.1'),
 ('Callithrix jacchus', 'XP_035153336.2'),
 ('Callithrix jacchus', 'XP_035153347.2'),
 ('Callithrix jacchus', 'XP_078208602.1'),
 ('Callithrix jacchus', 'XP_078208570.1'),
 ('Callithrix jacchus', 'XP_035153372.2'),
 ('Callithrix jacchus', 'XP_078208546.1'),
 ('Callithrix jacchus', 'XP_035153316.2'),
 ('Callithrix jacchus', 'XP_035153352.2'),
 ('Callithrix jacchus', 'XP_078208309.1'),
 ('Saimiri boliviensis', 'XP_003927227.1'),
 ('Saimiri boliviensis', 'XP_074243757.1'),
 ('Aotus nancymaae', 'XP_012321637.1'),
 ('Sapajus apella', 'XP_032150436.1'),
 ('Sapajus apella', 'XP_032150437.1'),
 ('Cebus imitator', 'XP_017397951.1'),
 ('Cebus imitator', 'XP_017397952.1'),
 ('Sapajus apella', 'XP_032150438.1'),
 ('Sapajus apella', 'XP_032150439.1'),
 ('Cebus imitator', 'XP_017397953.1'),
 ('Cebus imitator', 'XP_017397954.1')]

In [38]:
get_species_with_allele('GALT', translation['NM_000155.4'], 23, 'A')

[('Cercocebus atys', 'XP_011924617.1'),
 ('Nycticebus coucang', 'XP_053425960.1'),
 ('Nycticebus coucang', 'XP_053425949.1'),
 ('Otolemur garnettii', 'XP_003800307.1')]

This function compares the human and nonhuman sequences in the -10 / +10 range.  The output at the bottom shows the numbers of:

* differences between the sequences
* gaps 
* sites out of range

For example, the GBA1 site at the end means that 9 sites are outside the range.  The GALT sequence shows some aminoacid differences.

In [42]:
local_compare_to_human('GBA', translation['NM_000157.4'], 535, 'XP_005541629.1')
GBA1	NM_000157.4	502	R

UnboundLocalError: cannot access local variable 'nonaln' where it is not associated with a value

In [43]:
local_compare_to_human('GALT', translation['NM_000155.4'], 247, 'NP_000146.2')

UnboundLocalError: cannot access local variable 'nonaln' where it is not associated with a value

This function spits out a site by site comparison of the human and nonhuman sequences.  Only the differences are shown.

In [23]:
global_compare_to_human('GBA', translation['NM_000157.4'], 'XP_005541629.1')

5 S -
6 S -
7 P -
10 E K
16 L S
17 S G
24 G A
67 F L
68 D E
70 P L
94 M T
96 P T
101 H R
213 R H
344 V -
345 L -
346 T -
347 D -
348 P -
349 E -
350 A -
351 A -
352 K -
353 Y -
354 V -
355 H -
356 G -
357 I -
358 A -
359 V -
360 H -
361 W -
362 Y -
363 L -
364 D -
365 F -
366 L -
367 A -
368 P -
369 A -
370 K -
371 A -
372 T -
373 L -
374 G -
375 E -
376 T -
377 H -
378 R -
379 L -
380 F -
381 P -
382 N -
383 T -
384 M -
385 L -
386 F -
387 A -
388 S -
389 E -
390 A -
391 C -
392 V -
393 G -
394 S -
395 K -
396 F -
397 W -
398 E -
399 Q -
401 S -
402 V -
403 R -
404 L -
405 G -
406 S -
407 W -
408 D -
409 R -
410 G -
411 M -
412 Q -
413 Y -
414 S -
415 H -
416 S -
417 I -
418 I -
419 T -
452 I V
496 A T
507 A T
546 R C
547 R L

In [24]:
global_compare_to_human('GALT', translation['NM_000155.4'], 'XP_003800307.1')

23 R C
26 T A
28 P L
29 Q D
30 Q R
39 A I
40 A P
41 A V
43 T A
45 R Q
47 N S
106 I T
115 Q H
118 S A
153 K E
154 S A
177 V M
203 A V
216 A S
248 Q R
251 K Q
256 E V
268 L I
269 R K
289 T V
310 P S
360 E A
363 A D
366 N D
669 H C
671 G R
828 T A

In [25]:
get_species_with_allele('CFTR', translation['NM_000492.4'], 13, 'F')

[('Otolemur garnettii', 'XP_003789873.1')]

In [26]:
local_compare_to_human('CFTR', translation['NM_000492.4'], 13, 'XP_003789873.1')

-10 P P
-9 L L
-8 E K
-7 K K
-6 A L
-5 S N
-4 V L
-3 V L
-2 - -
-1 - -
0 S F
1 K F
2 L L
3 F Y
4 F F
5 S S
6 W W
7 T T
8 R R
9 P P
10 I I

(7, 0, 0)

In [28]:
translation['NM_000132.3']

'NP_000123.1'

In [29]:
get_species_with_allele('F8', 'NP_000123.1', 2183, 'V')

[('Hylobates moloch', 'XP_032612179.1')]

In [30]:
local_compare_to_human('F8', 'NP_000123.1', 2183, 'XP_003789873.1')

UnboundLocalError: local variable 'nonaln' referenced before assignment